### ISSUE TITLE
Setup Prometheus server per tenant cluster

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#1]
## User Story

_-  As GiantSwarm Engineer I want to have scalable monitoring architecture so the Prometheus resource usage is not tight to the number of Tenant Clusters on Installation._

_- As GiantSwarm Engineer I want to have stable monitoring architecture so the Prometheus uptime is 100%._

_- As a GiantSwarm Engineer, I want to be able to add as much metrics to Prometheus as I need so that I have good observability of apps and services._

## Details, Background

Currently, we have one Prometheus, AlertManager and Grafana instance per installation running in a control plane. So the resource usage of Prometheus is tied to the number of tenant clusters. As the number of tenant clusters increases, Prometheus resource usages grows. This results in memory issues and downtimes of Prometheus. 

To ensure Prometheus stability, we need to have a separate Prometheus server per tenant cluster installed on the Control Plane. 

<img width="861" alt="cp_prometheus" src="https://user-images.githubusercontent.com/54959552/69556763-a6c26680-0fa5-11ea-81d4-b834d0a19b8b.png">

## TODO

- [x] https://github.com/giantswarm/giantswarm/issues/10897 Install Prometheus Operator on control planes
- [x] https://github.com/giantswarm/giantswarm/issues/8017 Enable CRs creation for Prometheus operator (prometheus-meta-operator)
- [x] https://github.com/giantswarm/giantswarm/issues/10899 Deploy `prometheus-meta-operator` to all CPs
- [x] https://github.com/giantswarm/giantswarm/issues/10898 Add support for `prometheus-meta-operator` to reconcile legacy cluster CRs
- [x] https://github.com/giantswarm/giantswarm/issues/10902 Enable access to Prometheus servers
- [x] https://github.com/giantswarm/giantswarm/issues/10905 Add nginx-ingress-controller to TC Prometheus
- [x] https://github.com/giantswarm/giantswarm/issues/11724 Add kubernetes targets to Prometheus
- [x] https://github.com/giantswarm/giantswarm/issues/11720 Add basic targets to Prometheus
- [x] https://github.com/giantswarm/giantswarm/issues/11722 Add api service targets to Prometheus for control planes
- [x] https://github.com/giantswarm/giantswarm/issues/11719 Add operator targets to Prometheus for control planes
- [x] https://github.com/giantswarm/giantswarm/issues/11721 Add monitoring targets to Prometheus for control planes
- [x] https://github.com/giantswarm/giantswarm/issues/11722 Add awkward targets to Prometheus for control planes
- [x] https://github.com/giantswarm/giantswarm/issues/10901 Update `opsctl open`
- [x] https://github.com/giantswarm/giantswarm/issues/10904 Improve labelling schema 
- [x] https://github.com/giantswarm/giantswarm/issues/11524 Enable access to CP and TC prometheus servers

## Spikes 

- https://github.com/giantswarm/giantswarm/issues/8987 How should prometheus-operator CRs work with managed apps?
- [x] https://github.com/giantswarm/giantswarm/issues/10903 Enable storage for on-prem installations

## Targets
- Docker daemon
- K8s api server / controller manager / scheduler
- Kube-proxy

**Comment by JosephSalisbury** [comment]
further notes / thoughts:

- having a service definition would be super useful (including service levels), and make sure that fits with other team's requirements
- we need to check out managed apps requirements for using prometheus-operator CRs (they want to use prometheus-operator CRs in their charts, how do we ensure that works)

**Comment by cokiengchiara** [comment]
@sslavic FYI on prometheus scaling story.

**Comment by sslavic** [comment]
Does this depend on https://github.com/giantswarm/giantswarm/issues/8395 ?

**Comment by snizhana-dynnyk** [comment]
It doesn't matter for us which catalog prometheus-operator is in, so no, it shouldn't depend.
