### ISSUE TITLE
Setup management cluster Prometheus 

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#10]
## User Story

_- As GiantSwarm Engineer I want to have observability of Control Plane components (operators, etcd etc.) so that I can avoid outages and other issues._

## Details

Setup Control Plane Prometheus to monitor Control Plane components (operators, etcd etc.) and workload cluster Prometheus servers. 

<img width="861" alt="cp_prometheus" src="https://user-images.githubusercontent.com/54959552/70867745-0eeae380-1f79-11ea-8ca5-5fab43621d43.png">

## TODO

- [x] 1. Enable CRs creation for Prometheus operator
- [x] 2. Enable Control Plane Prometheus to scrape CP components
- [x]  https://github.com/giantswarm/giantswarm/issues/13093 Enable CP and TC Prometheus servers to send alerts to Alertmanager
- [x] https://github.com/giantswarm/giantswarm/issues/13094  Add support for Grafana to query Control Plane Prometheus servers / or solve this with Promxy
- [x] https://github.com/giantswarm/giantswarm/issues/13302 Add support for sending Heartbeats to opsgenie (ensure heartbeat opsgenie alerts have same tags as other opsgenie alerts)
- [ ] https://github.com/giantswarm/giantswarm/issues/10903 Storage on onprem

## Notes / Questions

 - we want to allow customers to use our Grafana on the control plane. We might also want to think about routing alerts to them. The example of use case is IP capacity. When there are only 5 IPs left for a cluster we could have an alert but that would only trigger us to tell the customer, in stead we could alert customers directly.

**Comment by snizhana-dynnyk** [comment]
Since we don’t know how much time it will take to configure storage on onprem and this depends on customers, I will remove this story from this epic and close it. We already have management cluster Prometheus server running everywhere.
