### ISSUE TITLE
GS login tools for CAPG

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1004]
## Story
_*-As a Giant Swarm employee, I want to be able to access `GCP` management clusters with the same tools used on the other cloud providers in order to have the same experience.*_

## Tasks
- [x] https://github.com/giantswarm/opsctl/pull/1486
- [x] https://github.com/giantswarm/kubectl-gs/pull/806
- [x] add Giant Swarm employees so that they can login to `GCP`;

**Comment by alex-dabija** [comment]
Everything is working.
