### ISSUE TITLE
Make `gohan` a Giant Swarm test installation

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1005]
Make `gohan` a Giant Swarm test installation.

## Tasks
- [x] update installation config to be `test` instead of `stable`;
- [x] create appropriately named GCP project;
- [x] ensure all needed staff have access;
- [x] move `gohan` to new GCP project;

**Comment by AverageMarcus** [comment]
New `giantswarm` project set up in GCP to house this MC - https://console.cloud.google.com/compute/instances?project=giantswarm-352614
