### ISSUE TITLE
Reduce Happa build time

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#1042]
### Description
Happa build takes a lot of time and happens a lot (joe cares about credit usage, but we can probably save on carbon and developer time here too).

Therefore, to reduce the "time to build" a release:

### TODO
- [x] Get the "build time" of Happa and add in the issue (we could decide on a build time threshold later and add some monitoring)
- [x] Check the build logs and find what is consuming so much time
- [x] Provide a list and apply the optimization we can bring
- [ ] Get the new "build time" of Happa and add in the issue after optimization

**Comment by kuosandys** [comment]
Joe will be speaking to CircleCI on April 21st, so we should ideally have investigated/fixed this before then.

**Comment by kuosandys** [comment]
Credits are calculated based on build minutes, [price varies](https://circleci.com/product/features/resource-classes/) depending on the resource class used. We use Docker medium for everything except for `tests`, where we use x-large. This was necessary after we switched from SWC to Babel because tests kept timing out.

Current build times (last 30 days as of April 13th, 2022):
<img width="1067" alt="Screen Shot 2022-04-13 at 16 33 16" src="https://user-images.githubusercontent.com/62935115/163204298-3ed6757d-efbc-46de-bab6-17fcd3edb611.png">

Jobs sorted by credit usage:
<img width="1101" alt="Screen Shot 2022-04-13 at 16 37 39" src="https://user-images.githubusercontent.com/62935115/163205354-75e253cf-7d1e-4cf5-b6c6-da8a6454527e.png">

**Comment by kuosandys** [comment]
I think another area for improvement is the number of runs as well. While this doesn't necessarily improve time per build, it reduces the number of credits/resources used.

renovatebot creates around 3 PRs per day to upgrade dependencies, and merging one causes the other branches to rebase again. We can [configure this](https://docs.renovatebot.com/configuration-options/#rebasewhen) to try and reduce this. We can also examine the existing package groups to see if we can identify other groups of dependencies to update together.

**Comment by kuosandys** [comment]
After the changes from the above PR, we:
- only build FE docs when creating a release
- have combined lint, typecheck, prettier into one step
- have combined build-container and push-happa-docker/quay steps

An example from before:
<img width="1053" alt="Screen Shot 2022-04-19 at 12 31 40" src="https://user-images.githubusercontent.com/62935115/163985439-89c8c65b-1420-463a-9c70-ee12058b1313.png">

An example of the build process now:
<img width="869" alt="Screen Shot 2022-04-19 at 12 31 55" src="https://user-images.githubusercontent.com/62935115/163985435-8a8ca31f-672c-4723-9ea8-cf55361cfc7e.png">

There hasn't been enough runs to get a reliable average on the build time/credit usage, but this is something we can track overtime and reevaluate in the future if required.
