### ISSUE TITLE
Replace kube proxy by cilium and ebpf

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#1072]
```[tasklist]
### CAPVCD
- [ ] https://github.com/giantswarm/cluster-cloud-director/pull/104
- [ ] https://github.com/giantswarm/mc-bootstrap/pull/437
- [ ] https://github.com/giantswarm/cluster-cloud-director/pull/120
``` 

```[tasklist]
### CAPV
- [ ] https://github.com/giantswarm/cluster-vsphere/pull/38
- [ ] https://github.com/giantswarm/mc-bootstrap/pull/437
- [ ] https://github.com/giantswarm/mc-bootstrap/pull/462
- [ ] https://github.com/giantswarm/cluster-vsphere/pull/41
```

**Comment by cornelius-keller** [comment]
@giantswarm/team-cabbage team rocket would like to do this to get rid of iptables. As this is network related, is there an impact on your roadmap or stories you are planning?

**Comment by cornelius-keller** [comment]
Feedback from @giantswarm/wg-capi-mc: 
- capa, capg, capz should use cillium without kube-proxy 
- this involves going to use c-groups v2
- sould not interfere with any service-mesh etc.

**Comment by weatherhog** [comment]
@cornelius-keller at the moment we in @giantswarm/team-cabbage do not have something in the direction of cilium and ebpf. We are happy to help out regarding the replacement. But do not really have capacities for that at the moment

**Comment by paurosello** [comment]
From the customer side, cGroups v2 is still a big issue, we will have many customers in v1 for a while.

**Comment by kopiczko** [comment]
From CAPO point of view:

* we are on ubuntu 20.04 and [according to this](https://www.phoronix.com/scan.php?page=news_item&px=Ubuntu-21.10-systemd-cgroup) cgroups v2 are enabled with 21.10. We probably could switch to 22.04. I'm not sure if this is supported by image-builder but probably will be if not
* we need to add `--skip-phases=addon/kube-proxy` to `kubeadm init/join`. This was [added in February](https://github.com/kubernetes-sigs/cluster-api/pull/5993) to CAPI but is still not released
* general problem: "Be aware that this will break existing service connections. It will also stop service related traffic until the Cilium replacement has been installed" (from https://docs.cilium.io/en/v1.11/gettingstarted/kubeproxy-free/)
* general: requires kernel 5.8 and has some limitations (from https://docs.cilium.io/en/v1.11/gettingstarted/kubeproxy-free/#limitations)

**Comment by kopiczko** [comment]
Check https://github.com/giantswarm/roadmap/issues/1456

**Comment by gawertm** [comment]
not directly related but could be relevant: https://github.com/giantswarm/roadmap/issues/1594
Cabbage was working on Hubble and Phoenix is about to enable/introduce it for all their clusters

**Comment by kopiczko** [comment]
For CAPVCD: https://github.com/giantswarm/cluster-cloud-director/pull/104

This works for WCs, but it's not going to work in mc-bootstrap out of the box because we template kubeapi domain and we'll need to pass the IP during the bootstrap.

**Comment by vxav** [comment]
Sorry I didn't get that part? What do you mean?

> because we template kubeapi domain

**Comment by kopiczko** [comment]
This is done for CAPVCD. Now CAPV

**Comment by kopiczko** [comment]
CAPV PRs in review.

**Comment by kopiczko** [comment]
Done for CAPV.
