### ISSUE TITLE
Control Groups v2 follow-ups

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1079]
## TODOs

- [x] #1090
- [x] #1094
- [x] Move real-time processes to the root cgroup;
- [ ] If you are using uber-go/automaxprocs, make sure it works with cgroup v2 (@alex-dabija update release notes);
- [x] Use JDK 15 or later.

## Background

Giant Swarm Kubernetes clusters have `Control Groups v2` enabled by default, but we do offer the option to switch back to `v1` per each machine pool in case the customer has incompatible workloads.

## Resources
- [Five Things to Prepare for Cgroup v2 with Kubernetes](https://blog.kintone.io/entry/2022/03/08/170206);

**Comment by whites11** [comment]
mentioned to add release notes in upcoming platform releases, nothing else to do here
