### ISSUE TITLE
IRSA on management clusters

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#1084]
* A customer would like to use aws secrets manager instead of sops on the management cluster: https://github.com/giantswarm/roadmap/issues/1076
 * For CAPA we should stop using a user or KIAM and start using IRSA too

## Tasks

- [x] https://github.com/giantswarm/roadmap/issues/1375;
- [x] https://github.com/giantswarm/roadmap/issues/1255;
- [x] https://github.com/giantswarm/roadmap/issues/1640;
- [x] https://github.com/giantswarm/roadmap/issues/1981;
- [x] https://github.com/giantswarm/roadmap/issues/1781;

**Comment by PG2000** [comment]
For IRSA in our productions accounts we need public s3 buckets for the discovery endpoints
@freudl

**Comment by teemow** [comment]
@PG2000 is this a note to yourself? Or is your feedback that this should be a private bucket in the future?

**Comment by PG2000** [comment]
@teemow this was an more an internal info.
Would it be possible to make the s3 bucket only availabe to AWS? Then i would raise it as an requirement for later

**Comment by alex-dabija** [comment]
IRSA is running on management clusters for awhile now and Kiam was recently dropped.
