### ISSUE TITLE
IAM Roles for Service Accounts (IRSA) as default

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1095]
## Story

_*-As a security engineer, I want to have IAM Roles for Service Accounts (IRSA) the default solution to enable access to AWS APIs in order to increase the security of workload clusters.*_

## Background

Giant Swarm clusters are using Kiam to enable access to AWS APIs. Unfortunately, Kiam is now deprecated and the recommendation is to use IAM Roles for Service Accounts (IRSA).

## TODOs

- [x] Make IRSA the default. (Figure out how to do it: @alex-dabija create issue);
- [x] Remove Kiam from the list of default apps;
- [x] #1123
- [x] Operational aspects: monitoring & alerts, dashboards;
- [x] Notify AEs of upcoming changes;
- [x] Check the soft limit of 100 S3 buckets in the customer's accounts (should be part of the migration guide).
- [x] Clean up IP tables

## Questions

- Should Kiam still be available as on optional applications? **Yes.**

## Resources

- [GiantSwarm IRSA Documentation](https://docs.giantswarm.io/advanced/iam-roles-for-service-accounts/).

**Comment by njuettner** [comment]
With release v19.0.0 irsa-operator will bootstrap IRSA without any annotation set. The new version is rolled out in all installations.

**Comment by njuettner** [comment]
PR https://github.com/giantswarm/aws-operator/pull/3428 is ready for v19 in aws-operator. But with our current findings about the missing api-audience I'd like to wait until we fixed this first.

I'm also off next week (CW 24) so I'll unassign myself
