### ISSUE TITLE
Centralized Metrics

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#11]
## User Story

_- As GiantSwarm Engineer I want to have a high-level overview of all installations so that I can use this data for decision making._

_- As GiantSwarm Sales Manager / Marketing Manager I want to collect business metrics so that I can use this data for decision making._

## Details, Background

With an increasing number of installations, getting an overview of metrics becomes more difficult. We need a method of accessing all our metrics from one place.

## TODO

- [x] 1. Evaluate Cortex for cross installations querying 

## Blocked by / depends on

- [ ] giantswarm/roadmap#1 Prometheus server per tenant cluster
- [ ] giantswarm/roadmap#10 Control Plane Prometheus

**Comment by JosephSalisbury** [comment]
@snizhana-dynnyk what do you need from me here?

**Comment by snizhana-dynnyk** [comment]
This was done as a Hackathon project, I guess we can close the epic.
