### ISSUE TITLE
[MVP] Enable an App installation with K8S API

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#112]
Towards https://github.com/giantswarm/roadmap/issues/90 Migrate GS API to Kubernetes API

## User Story

- As a GS user with write access to CP, I can create an App using K8S API

### Acceptance criteria 

- Given that I have a 'write' access to CP API I can create an App CR which will spin-up a new App

### Tasks
- [x] add user-facing documentation 
  - [x] App/AppCatalog CR documentation
  - [x] Write docs: how to create your catalog and applications (new ticket https://github.com/giantswarm/giantswarm/issues/10758)
  - [x] kubectl gs MVP is working https://github.com/giantswarm/kubectl-gs
- [x] `Chart` CRD docs
- [ ] add CRD schema for validation
- [ ] add server-side validation and defaulting

**Comment by cokiengchiara** [comment]
@pipo02mix once we have the docs you are creating, we can update installing ingress controller via CP k8s API too right?

**Comment by pipo02mix** [comment]
Well even without docs it can be done now 😃 
My docs are describing how to create an App Catalog and install the Apps in your cluster through the Control Plane API. 

IMO this specific documentation can be added to the [existing guide](https://docs.giantswarm.io/guides/installing-optional-ingress-controller/). But I will create another ticket for that

**Comment by pipo02mix** [comment]
I need to follow [this process](https://github.com/giantswarm/docs/pull/442) to publish eh changes

**Comment by pipo02mix** [comment]
Changes published :)
I will add some definitions for `Chart` CRD

**Comment by pipo02mix** [comment]
Added Chart CRD docs too. I will move to validation next week

**Comment by pipo02mix** [comment]
This is week I have more availability to work on this

**Comment by cokiengchiara** [comment]
For this cycle, @pipo02mix will work on "Defaulting and validation of apps for people creating apps in app catalog."

**Comment by pipo02mix** [comment]
I could not get much progress here. I am going to opt out as I don't have much time and it is not under my goals team anymore.

I checked the catalog tutorial since I have another ticket to track this https://github.com/giantswarm/giantswarm/issues/10758

**Comment by JosephSalisbury** [comment]
@giantswarm/team-batman do anyone of you feel like picking this up?

**Comment by JosephSalisbury** [comment]
'this' == owning this feature, providing documentation, working with adidas (specifically) to get feedback

**Comment by snizhana-dynnyk** [comment]
@cokiengchiara closing this as MVP works and defaulting/validation is out of scope here, we need a separate issue for this.
