### ISSUE TITLE
Create clusters without using vault in mc-bootstrap

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1126]
### User Story 
- As a giant swarm developer I want to create a management cluster with previously encrypted secrets, so that I can have predictable secrets for testing and don't rely on vault. 
### Tasks 
- [x] create initial sops key 
- [x] encrypt secrets in sops
- [x] store them in config repo
- [ ] remove vault from installation 

hint: most work needs to be done in `https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/setup-config-branch.sh`

**Comment by cornelius-keller** [comment]
Let's have a minimal implementation without vault first and then do a refinement on moving config managment and secret encryption out of the bootstrap script.

**Comment by JosephSalisbury** [comment]
- Eric working with Laszlo to try and get konfigure working
- management clusters fleet needs some changes, so working with Honeybadger

**Comment by ericgraf** [comment]
- Fixed secret generation for athena which uses json string inside of yaml
- Added additional vaultless providers for gcp, vspehere, capa, cloud-director to MCF.

**Comment by JosephSalisbury** [comment]
next steps:
- get above PRs merged
- we need to work migration (we have a separate issue to track this)

**Comment by ericgraf** [comment]
PRs were merged and this is now supported in mc-bootstrap.
