### ISSUE TITLE
Implements prometheus resource in remoteWrite controller

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1140]
Towards: https://github.com/giantswarm/roadmap/issues/496

### Description

Implement a new resource in the [remoteWrite controller](https://github.com/giantswarm/roadmap/issues/1110) to configure the `Prometheus.spec.remoteWrite` field with the content of `RemoteWrite.spec.remoteWrite` field.

- A `RemoteWrite` resource is used to configure multiple `Prometheus` resources, to achieve this we rely on the `RemoteWrite.spec.clusterSelector` field, which we are going to use to select the targeted `Prometheus` CR.

Example:

- remoteWrite controller receives the following object :

```yaml
apiVersion:  monitoring.giantswarm.io/v1alpha1
kind: RemoteWrite
metadata:
  name: adidas-victoria-metrics 
spec:
  clusterSelector:
    giantswarm.io/cluster: yz2cx
  remoteWrite:
    url: https://foobar.com
    writeRelabelConfigs:
    - foo: bar
```

- the new resource select the `Prometheus` CRs to work on as follow :

```yaml
$ kubectl get prometheus --all-namespaces --selector=giantswarm.io/cluster=yz2cx -oyaml
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      app.kubernetes.io/instance: yz2cx
      app.kubernetes.io/managed-by: prometheus-meta-operator
      app.kubernetes.io/name: prometheus
      giantswarm.io/cluster: yz2cx
    name: yz2cx
    namespace: yz2cx-prometheus
  spec:
    additionalAlertManagerConfigs:
      key: alertmanager-additional.yaml
      name: new-alertmanager-config
    additionalScrapeConfigs:
      key: prometheus-additional.yaml
      name: additional-scrape-configs
    replicas: 1
```

- the new resources configure the `remoteWrite` field on the `Prometheus` CRs and update it.

```yaml
apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    labels:
      app.kubernetes.io/instance: yz2cx
      app.kubernetes.io/managed-by: prometheus-meta-operator
      app.kubernetes.io/name: prometheus
      giantswarm.io/cluster: yz2cx
    name: yz2cx
    namespace: yz2cx-prometheus
  spec:
    additionalAlertManagerConfigs:
      key: alertmanager-additional.yaml
      name: new-alertmanager-config
    additionalScrapeConfigs:
      key: prometheus-additional.yaml
      name: additional-scrape-configs
    remoteWrite:
    - url: https://foobar.com
      writeRelabelConfigs:
      - foo: bar
    replicas: 1
```

A lot of data was stripped down from those examples.

### Suggestions

* Name the new resource `prometheus-remotewrite` this helps us know what this resource is doing.
* Selecting with label should work with 
```go
config.PrometheusClient
  .MonitoringV1()
  .Prometheuses(metav1.NamespaceAll)
  .List(ctx, metav1.ListOptions{
    LabelSelector: remoteWrite.spec.clusterSelector.String(),
  })
```
* Use the `Prometheus.spec.remoteWrite[].Name` field for uniqueness ([doc](https://pkg.go.dev/github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring/v1#RemoteWriteSpec))
* We might need a logic to cleanup current values in the `Prometheus.spec.remoteWrite` field. This logic can be removed after the first release.

### TODO

- [x] Add new resource boilerplate
- [x] Implements cluster selector logic
- [x] Implements resource Create/Update/Delete logic

**Comment by mcbenjemaa** [comment]
I'd like to work on this issue if no one has any objections!
