### ISSUE TITLE
Epic: GitOps templating automation

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1141]
As a Giant Swarm customer using GitOps, I want to have automations and templates automatically created from the GitOps template repo so that I can focus on developing my projects

## Scope
The team will provide such features as a` kubectl-gs` extension plugin with a dedicated subtree. The integration will be at file system level, team will re-evaluate at later stage (likely, when tackling [the promotion of releases/environment propagation epic)](https://github.com/giantswarm/roadmap/issues/830)

Name of the plugin command TBD (in the examples below, the command is referenced with the temporary name of kgs-gitops)

The scope is divided in different use cases to be implemented following this staged order: 

1. MC 
2. Org 
3. App 
4. WC 
5. Encryption

Regarding encryption, it is not clear at the moment of refinement if this makes sense to be developed at the end of as a complementary part while we implement the steps before. This will be discovered during implementation phase. The team agreed that, if some prep work on encryption can be done while working on a previous stage (with minimal increase of scope to get the stage done and completed) then we do it, if not we keep the work on encryption as last stage of the scope. This decision call is taken at implementation stage by the dev working on it.

## Use cases

 - [x]  Add a new management cluster

As a Giant Swarm customer using GitOps I want to add the GitOps representation of a MC to my repository, with a basic directory structure, and then have support for connecting / coupling them so that I can focus on developing my projects.

Example

> kgs-gitops   create management-cluster <name>
>Your `<name>` cluster has been configured in the repository. Please accept the >`https://github.com/<user_name>/<repo_name>/pull/2` PR to finish the process and then run the below command to >connect cluster to the repository:

>`kgs-gitops connect management-cluster <name>` # creates (GitRepository,credentials) 

- [x]  Generate the folder structure for an org 

As a Giant Swarm customer using GitOps I want to generate the folder structure for a new org so that I can focus on developing my projects
Currently, `kubectl gs template` organization generates organization CRs only.
Examples:

> kgs-gitops template organization \
> --name ${ORG_NAME} \
> --generate-gpg

> kgs-gitops create organization <org_name> –mc <mc_name>
> The `<org_name>` has been added to the `<mc_name>` cluster. Please accept the 
> `https://github.com/<user_name>/<repo_name>/pull/3` PR to finish the process.

- [x] Add workload cluster to the org

As a Giant Swarm customer using GitOps I want to add workload cluster to the organization, meaning I want to prepare the repository to handle WC-related configuration, but not yet add the workload cluster definition (CRs), so that I can focus on delivering my projects.

Open point: Why separate “holder” for the cluster in the repository and cluster definition? These are naturally separated, user may have a directory structure for the cluster, configure apps for it, without ever adding the cluster definition. Hence it feels more right to leave it like that, and find some smart of adding definition later on, at any stage of work.
To be further refined and, to evaluate to make this sub-command context-aware

> kgs-gitops create workload-cluster <wc_name> –mc <mc_name> –org <org_name>
The `<wc_name>` cluster has been added to the `<mc_name>` cluster under the `<org_name>` organization. Please accept the `https://github.com/<user_name>/<repo_name>/pull/4` PR to finish the process.

> kgs-gitops add workload-cluster definition –wc <wc_name> –mc <mc_name> –org <org_name> –base <base_path> –release <release> [other_flags]
>The `<wc_name>` cluster definition has been added. Please accept the >`https://github.com/<user_name>/<repo_name>/pull/5` PR to finish the process.

- [x] Add apps to the workload cluster

As a Giant Swarm customer using GitOps I want to add apps to my workload cluster so that I can deliver my projects

> kgs-gitops add app –wc <wc_name> –mc <mc_name> –org <org_name> [–base <base_path>] –name <app_name> –  > catalog <app_catalog> …
> The `<app_name>` app has been added to the `<wc_name>` workload cluster. Please accept the 
> `https://github.com/<user_name>/<repo_name>/pull/6` PR to finish the process.

- [x] Generate version update automation with kubectl gs

As a Giant Swarm customer using GitOps I want to generate App CR with ImageRepository and ImagePolicy, so that it’s easy for me to set up automatic app upgrades.

Currently, `kubectl gs template` app generates App CR only.
Parameter: semver range

Example:

>  kubectl gs template app \
> --app-name ${APP_NAME} \
> --catalog ${APP_CATALOG} \
> --cluster ${WC_NAME} \
> --name ${APP_NAME} \
> --namespace ${APP_NAMESPACE} \
> --version {$APP_VERSION} \
> --automatic-upgrades true

- [x] Generate whole cluster + apps from existing base

Currently, `kubectl gs template cluster` generates cluster CRs only

As a Giant Swarm customer using GitOps I want to generate my entire cluster + default apps from an pre-existing base so that I can focus on delivering my projects

Example:

> kubectl gs template cluster \
> --name ${CLUSTER_NAME} \
> --gitops-base ./path/to/base/folder

- [x] Generate GitOps encryption
As a Giant Swarm customer using GitOps I want to have the SOPS _magic_ set up for me so that I can focus on developing my projects.
The secrets generation and encryption should support both org and cluster.

**Comment by MarcelMue** [comment]
Customer tracking issue here:
https://github.com/giantswarm/thg/issues/97

**Comment by ljakimczuk** [comment]
Done with:
* https://github.com/giantswarm/kubectl-gs/pull/832
* https://github.com/giantswarm/docs/pull/1538
