### ISSUE TITLE
Add Grafana cloud remote write config

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1143]
Towards: https://github.com/giantswarm/roadmap/issues/496

### Description

All our Prometheus servers are currently sending data to [Grafana Cloud](https://giantswarm.grafana.net/) for data long term persistency.

As we are re-structuring the way we handle remote write config, we need to ensure this config is kept in place.

The current remoteWrite config for Grafana Cloud was removed from prometheus-meta-operator in the scope of https://github.com/giantswarm/roadmap/issues/1111, we need to bring this config back.

Important note: We use a different url for Prometheus servers in china ([details](https://github.com/giantswarm/giantswarm/issues/17366)).

### TODO

- [x] Setup a new app for the remote write resources
- [x] Add remote write resource
- [x] Add config for china
- [x] Deploy & test

**Comment by TheoBrigitte** [comment]
* grafana-cloud remote write config now lives in the new `prometheus-remotewrite` app [link](https://github.com/giantswarm/prometheus-remotewrite/blob/main/helm/prometheus-remotewrite/templates/grafana-cloud.yaml)

* authentication credentials for grafana cloud lives in the `config` repository [here](https://github.com/giantswarm/config/blob/main/default/apps/prometheus-remotewrite/configmap-values.yaml.template) and [there]https://github.com/giantswarm/config/blob/main/installations/gauss/apps/prometheus-remotewrite/secret-values.yaml.patch)

* china config is set up

Still waiting to be tested on openstack
