### ISSUE TITLE
CAPG Workload Identity Webhook

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1149]
CAPG Workload Identity Webhook.

## TODOs:
- [x] diagram on how workload identity is configured when a cluster is created;
- [x] diagram on how an application running on the cluster can access GCP services;
- [x] propose what can be automated;
- [x] review with the team;
- [x] review with team Shield (Zach);
- [x] implement webhook;

**Comment by mnitchev** [comment]
Diagrams can be found [here](https://github.com/giantswarm/workload-identity-poc/tree/main/diagrams)

**Comment by mnitchev** [comment]
Webhook can be found [here](https://github.com/giantswarm/workload-identity-operator-gcp/) and it's already released in the gcp-app-collection
