### ISSUE TITLE
retag CPI/CSI Images for CAPVCD

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#1172]
- [x] [CSI plugin](projects.registry.vmware.com/vmware-cloud-director/cloud-director-named-disk-csi-driver)
- [x] [CPI](projects.registry.vmware.com/vmware-cloud-director/cloud-provider-for-cloud-director)
- [x] CAPVCD to build from [repo](https://github.com/vmware/cluster-api-provider-cloud-director)

- [x] Change retagger to use pattern matching instead of SHA (tags fixed upstream).

**Comment by vxav** [comment]
- **CPI & CSI**
The tags used by the CSI and CPI are currently not SemVer comformant (1.2.0.latest) so we'll have to match them per sha in retagger.
Issues created upstream, they will retag them properly.

- **CAPVCD**
Currently no image upstream for the dev branch.
push an image to quay tagged with short commit ID

**Comment by vxav** [comment]
The tags have been fixed upstream (no more .latest)

**Comment by gawertm** [comment]
hi @vxav what is left to do for this task?

**Comment by vxav** [comment]
It's a low priority task that I need to refine myself at some point but I'd like to keep it here so as to not forget about it.

**Comment by jkremser** [comment]
since `1.3.0` the cpi and csi images follow standard `x.y.z` pattern, so we should be good, PR in retagger: https://github.com/giantswarm/retagger/pull/833
