### ISSUE TITLE
 RemoteWrite Alerts/Dashboard

### ISSUE THREAD

**Issue by mcbenjemaa** [giantswarm/roadmap#1175]
Towards https://github.com/giantswarm/roadmap/issues/496

### Description

Adding alerts in case remotewrite reconciliation is failing or didn't work for any reason.

### TODO

Find relevant metrics
Build alert.
Create Dashboard for us and customers

- [x] Add alerts stating that remotewrite config was not configured
- [x] Make sure we are alerted if remote_write does not work, e.g: queues being weird (we have one alert already, let's improve it)
- [x] Update relevant docs.

**Comment by mcbenjemaa** [comment]
Discussing with Theo how to proceed, Current ideas:

- Either we copy the secrets in the remotewrite reconciliation loop

- Or we add another field in the remotewrite CR:

```yaml
secrets:
- name: grafana-cloud-basic-auth
  keys:
    username: <Base64>
    password: <Base64> 
```

**Comment by mcbenjemaa** [comment]
`operatorkit_controller_error_total`

https://github.com/giantswarm/operatorkit/blob/8b4f7dbf932c3152fd0f990cc73bf6fc3ecee79a/pkg/controller/metric.go#L18

**Comment by mcbenjemaa** [comment]
Alert has been added 
https://github.com/giantswarm/prometheus-rules/blob/master/helm/prometheus-rules/templates/alerting-rules/prometheus-meta-operator.rules.yml#L51

- [ ] Add Dashboard that shows remotewrite (use prometheus metrics)

**Comment by hervenicol** [comment]
Alert is raised for any operatorkit reconciliation error.
So I think we should either:
* rename alert so it's not named "prometheus"
* or reduce the scope of the alert so it only monitors prometheus components
* and maybe split in 2 alerts: one for atlas components, and a second alert for non-atlas components

**Comment by hervenicol** [comment]
* Alert's scope has been limited to prometheus-meta-operator
* An "operatorkit" dashboard has been created
* opsrecipe talks about the "operatorkit" dashboard
