### ISSUE TITLE
Specs for displaying GitOps-managed resources in the web UI

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1176]
Towards https://github.com/giantswarm/roadmap/issues/624

## Tasks

Create UI spec for

- [x] Cluster details page: "this cluster is managed by Flux/GitOps, so read-only"
- [x] Node pools: "This node pool is managed by ..."
- [x] Apps: "this app is managed by ..."
- [x] Organizations

**Comment by marians** [comment]
[WIP Figma prototype](https://www.figma.com/file/0lRx1WOvLklOsH8DA84vtx/Resource-managed-through-GitOps?node-id=0%3A1)

**Comment by marians** [comment]
PNGs for easier access

![Cluster](https://user-images.githubusercontent.com/273727/186381704-8ae24898-d2dc-4eb4-ae95-6380c31aa1b0.png)

![Node pool](https://user-images.githubusercontent.com/273727/186381727-64654d76-cbc3-4fba-a40b-6ab8d3d661c1.png)

![App](https://user-images.githubusercontent.com/273727/186381740-8eeae512-b434-4362-ac8f-20c97aca5a0b.png)

**Comment by marians** [comment]
Feedback call notes

- Organization details page should have the indicitator similar to the cluster details page
- Delete section on org details page gets hidden in this case
- CLI guides with editing/deletion action should show warning in gitops case

Question:

- Should GitOps be indicated on the clusters list? Yes

**Comment by marians** [comment]
## Latest spec version

### Changes

- Added organization details page with GitOps indicator
- Added home page with GitOps icon on one cluster
- Added CLI guide with GitOps indicator

### Mockups and Description

#### Home

If the Cluster resource carries the gitops label(s), we add our gitops icon to the cluster item, as shown for the first cluster in the mockup.

![Home](https://user-images.githubusercontent.com/273727/186599554-260f0c41-59ce-4e4a-9d34-886d4f791e0e.png)

#### Organization

If the Organization resource carries the gitops label(s), we add the long-form indicator to the header.

In this case, the "Delete organization" section is hidden, to prevent deletion of the organization via the UI.

![Organization](https://user-images.githubusercontent.com/273727/186599562-9a459a6c-5731-4328-af36-b188af7219d3.png)

#### Cluster

If a Cluster resource carries the gitops label(s), we show the long-form indicator in the header.

In this case, adding/removing/editing labels is not possible (which is not fully represented in the mockup). Also upgrading the cluster and changing a single node control plane cluster to HA will not be offered. The Actions tab is hidden to prevent deletion of the cluster via the UI.

![Cluster](https://user-images.githubusercontent.com/273727/186600631-40380f04-ff5c-4e18-ad75-311ced791cb4.png)

#### Node pool

In a node pool where the MachineDeployment (or equivalent) resource carries the gitops label(s), we show the gitops icon in the position where otherwise the menu is shown for a list item.

![Node pool](https://user-images.githubusercontent.com/273727/186599571-83667047-ed71-48b6-8b65-977a6ec63737.png)

#### App

If an App resource carries the gitops label(s), we hide the upgrade and values functions and instead show the long-form gitops indicator.

![App](https://user-images.githubusercontent.com/273727/186599570-ec86575a-1874-4855-b137-fce5f0b77eb2.png)

#### Management API guides

If the guide deals with a gitops-managed resource (based on the label) and explains a mutating function, we display the long-form gitops indicator in the top of the content, to remind users that executing these instructions might have unwanted consequences.

![CLI Guide](https://user-images.githubusercontent.com/273727/186599560-44aeed2b-2e11-47f1-ba6b-ca62a04015d1.png)

**Comment by marians** [comment]
FYI there is a PR for the docs content to be linked to from the long form indicator: 

- https://github.com/giantswarm/docs/pull/1533

**Comment by MarcelMue** [comment]
I like!

**Comment by puja108** [comment]
One Q: In app view, would the GitOps icon also appear next to the app when the app is not expanded? If not, I think it would make sense to add it there, too, as for consistency, as in all other views we show the icon in both collapsed and expanded states.

**Comment by marians** [comment]
@puja108 As of the current spec, the GitOps icon was NOT meant to appear on collapsed app items.

I see the value of it in a case where some apps are maintained through GitOps. In the case where all of them are, it might be a bit strange to have the icon on all apps. We might want to treat that case a bit more clever. Ideally I would leave that to a future improvement step.

**Comment by uvegla** [comment]
Which labels are considered `gitops label(s)`? Is it `giantswarm.io/managed-by: flux`? I think having a label on a cluster does not necessarily mean that everything in that cluster is managed by Flux. In an optimal world, it should be the case, but you can still apply resources manually to the cluster, no?

Also there are some labels added by Flux that might be useful to display for example to know, which Kustomization manages the resource (maybe there we could link to it and from there we could link to the source and there to the repository). For example:

```yaml
kustomize.toolkit.fluxcd.io/name: gorilla-clusters-rfjh2
kustomize.toolkit.fluxcd.io/namespace: default
```

**Comment by marians** [comment]
@uvegla The labels question has been discussed in https://github.com/giantswarm/roadmap/issues/624. Could you please add your comment there so it can be found in that context? Thanks!

**Comment by marians** [comment]
We consider this spec done. The parent issue will track the implementation effort.
