### ISSUE TITLE
Sync RemoteWrite BasicAuth secret to Prometheus namespace

### ISSUE THREAD

**Issue by mcbenjemaa** [giantswarm/roadmap#1180]
Towards https://github.com/giantswarm/roadmap/issues/496

### Description

Prometheus Operator tries to find the secrets in Prometheus namespace, 
But the BasicAuth secrets are deployed to the `monitoring` namespace.

We need a dynamic way of synchronizing secrets to Prometheus namespaces  

### TODO

- [ ] Sync BasicAuth Secrets in the controller reconcilation loop 
- [ ] Add an annotation, in order to stop the sync, in the next loops.
- [ ] Remove secrets once the RemoteWrite CR deleted.
- [ ] Update relevant docs.

**Comment by mcbenjemaa** [comment]
Discussing with Theo how to proceed, Current ideas:

- Either we copy the secrets in the remotewrite reconciliation loop

- Or we add another field in the remotewrite CR:

```yaml
secrets:
- name: grafana-cloud-basic-auth
  keys:
    username: <Base64>
    password: <Base64> 
```

**Comment by mcbenjemaa** [comment]
We agreed on adding a new field in the `RemoteWrite` CR, as mentioned above.
