### ISSUE TITLE
Get rid of `g8s-alertmanager`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#119]
## User Story

_- As a Giant Swarm Engineer, I want to get Alertmanager managed by Prometheus operator so that we can get rid of `g8s-prometheus`._
~_- As a Giant Swarm Engineer, I want to have Alertmanager HA so that there are no downtimes._~

## TODO

- [x] generate Alertmanager CR in prometheus-meta-operator (https://github.com/giantswarm/prometheus-meta-operator/pull/581)
- [x] Upgrade [prometheus-operator](https://github.com/giantswarm/prometheus-operator-app) to 0.51.0+
- [x] Re-work https://github.com/giantswarm/prometheus-meta-operator/pull/555 and update opsgenie token handling
- [x] https://github.com/giantswarm/giantswarm/issues/21330
- [x] #927
- [x] #928
- [x] #937
- [x] #936
- [x] https://github.com/giantswarm/silence-operator/pull/174
- [x] #939
- [x] #938
- [x] Remove code for the old alertmanager in PMO
- [x] Release pmo and silence operator

## Open questions

- can we run HA Alertmanager without persistent storage on on-prem installations

## Blocked by / depends on

- [x] #1 Setup Prometheus server per workload cluster

**Comment by JosephSalisbury** [comment]
note: make sure we don't regress on alert routing support, possibly clean up alert routing

**Comment by snizhana-dynnyk** [comment]
Since it is hard to solve the volume issue for on-prem installations for making an Alertmanager HA we will skip this for now. So the scope of the issue is to manage Alertmanager with prometheus operator and get rid of g8s-prometheus.

**Comment by snizhana-dynnyk** [comment]
Blocked by https://github.com/prometheus-operator/prometheus-operator/pull/4110

**Comment by TheoBrigitte** [comment]
We are no longer blocked as https://github.com/prometheus-operator/prometheus-operator/pull/4110 was merged and is part of 0.51.0 release, so any version above this works.

#### What's left to be done ?

- Re-work https://github.com/giantswarm/prometheus-meta-operator/pull/555 and update opsgenie token handling
- Upgrade [prometheus-operator](https://github.com/giantswarm/prometheus-operator-app) to 0.51.0+

**Comment by TheoBrigitte** [comment]
Magnifique :tada: :chefkiss:

**Comment by TheoBrigitte** [comment]
<img src="https://media3.giphy.com/media/3o7qDWp7hxhi1N8oF2/giphy.gif"/>

**Comment by JosephSalisbury** [comment]
c'est tout bien
