### ISSUE TITLE
Support Google Cloud Platform (GCP) in the web UI

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1192]
This issue is about supporting the Cluster API provider GCP (Google Cloud Platform) in the Giant Swarm web UI.

## Details

In a **first milestone** we are aiming to represent all the information our users are used to from other providers (vintage AWS, Azure). After that, the goal will be to allow for creation and modification of resources (clusters, node pools, apps).

- [CRDs](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/tree/main/api/v1beta1) - YAML representation is available with releases ([example](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/releases/download/v1.1.0/infrastructure-components.yaml))
- CAPG does not support MachinePool, we are using MachineDeployment for node pools
- Cluster app in [giantswarm/cluster-gcp](https://github.com/giantswarm/cluster-gcp)

## Tasks

- [x] Provide machine types metadata, based on GCP region `europe-west1`

### Spec:
- [x] #1246
- [x] Spec for displaying default apps (https://github.com/giantswarm/giantswarm/issues/21478#issuecomment-1184527026)

### Web UI:

- [x] Add support for getting GCP machine types
- [x] Add client types and functions for CAPG resources
- [x] #1215

#### Display

- [x] #1226 
- [x] #1234
- [x] #1231
- [x] #1299
- [x] #1221
- [x] #1246
- [x] Display user-installed and default apps (https://github.com/giantswarm/happa/pull/3681)
- [x] #1339 
- [x] Update CLI guides for inspecting resources:
  - [x] inspecting a cluster's release
  - [x] listing node pools
- [x] #1322 
- [x] #1397
- [x] #1369
- [x] #1385

#### Towards first milestone (read-only for cluster and node pool management)
- [x] #1350 
- [x] #1382
- [x] #1398
- [x] #1400

---

#### Creation

- Cluster and node pool creation
  - [ ] Add GCP availability zone data
  - [ ] Record cluster and node pool creation duration, so we can display stats in the UI.

**Comment by marians** [comment]
Today @kuosandys @fiunchinho and I had a call about implementation details. Notes are available in [this internal document](https://docs.google.com/document/d/1_IYZ0QlbVUtwmyVTd9vhXaMkFwOnd11pSPn_RgoAdPg/edit#).

**Comment by kuosandys** [comment]
I've started looking into the underlying resources and fields we need to display information in the web UI. [Here's a table](https://docs.google.com/spreadsheets/d/1_IOEzCA5CNLH1I2VPqO-8j7UiAPgr7U5_MhAE6RN-mg/edit?usp=sharing) I've started to keep my notes in one place - sharing it here in case it's also helpful for anyone else, and please feel free to edit!

**Comment by fiunchinho** [comment]
This command should work for templating a GCP workload cluster
```
k gs --context gs-gohan template cluster --provider gcp --organization giantswarm --region europe-west3 --gcp-project giantswarm-352614 --gcp-failure-domains europe-west3-a,europe-west3-b,europe-west3-c --gcp-machine-deployment-failure-domain europe-west3-a
```

**Comment by fiunchinho** [comment]
[Added support to allow](https://github.com/giantswarm/cluster-gcp/pull/95) defining the `machine-deployment.giantswarm.io/name` annotation to GCP clusters.

**Comment by kuosandys** [comment]
Some notes
- first milestone is to display resources, but it shouldn't be delivered at this stage (the product isn't complete)
- option 1: limit customers with RBAC to make them read-only users for the entire MAPI
  - customers would see "you do not have permissions.." in happa
  - we can explain to customers that this is an interim state
  - caveat: GS staff would still see the UI with full permissions, and it would have to be communicated that the UI does not support mutating the UI yet
- default apps could still be referred to as "preinstalled apps" - we could include a short description
  - hierarchical display of the default apps (app bundle) is not necessarily required here
  - 3 column display for the preinstalled apps should be removed in favour of a flat list (similar to the user-installed app list above, with the difference that default apps are not mutable)
  - we want to align preinstalled and user-installed apps in the UI, and display the app icon
- ingress tab - we would like to display instructions for configuring ingress regardless of whether ingress controller has been installed (this applies generally)
- client certificates tab - we would like to replace this with an "Access" tab to provide instructions on how to gain access to a WC (TODO: link related issue)

Tasks:
- Clarify with customers if the above solution would be suitable for them.
- Right now in our cluster list page (homepage) we can see a cluster app with the same name as the installation displayed (e.g. `gohan` "workload cluster" in the `gohan` installation). We should check with Team Hydra whether this Cluster resource would always be there, and consider hiding it from the list.
- We would need to gather a list of availability zones per GCP region in order to support selecting AZs during cluster and node pool creation
- Ask Team Hydra about node pool scaling (and other TODO items from the first refinement)
- Marian to clarify in #area-kaas whether we want to still refer to the cluster app's version as its "release"?
  - How should our release widget in cluster details be adapted?
  - Does it still make sense to show available upgrades?

**Comment by marians** [comment]
We came across an interesting question:

- [How to handle a CAPI management cluster CR showing up in happa](https://github.com/giantswarm/giantswarm/issues/22857)

**Comment by puja108** [comment]
@marians as you seem to be most in the know on this ticket, could you update the status collumn in the roadmap board to reflect your estimated ETA of this?

**Comment by marians** [comment]
Status field updated to 1 - 3 months.

Basic support for displaying clusters properly on GCP is currently in progress. Creation and modification will follow.

**Comment by kuosandys** [comment]
### Notes from refinement (19th August 2022)

Discussion about the first milestone:
- Downside of limiting customer permissions via RBAC: this would involve communicating with each customer to determine what permissions they need, as this would affect their access to the MAPI and not just the web UI
- idea: hide everything not currently usable, as this is a transitional stage

Decisions:
- cluster and worker nodes details should not be editable, hide creation buttons, hide actions tab
- apps installation will be adapted (can use kubectl gs template app as reference for how app installation needs to be adapted)
- organizations management, access, permissions features remain the same

**Comment by marians** [comment]
On GCP we see some new labels appear on all clusters, and which are not hidden by default currently:

![image](https://user-images.githubusercontent.com/273727/186638551-26049203-c127-4bb3-b31a-3b8be19f5b61.png)

I suggest to set the following label patterns to be hidden by default:

- Starts with `app.kubernetes.io`
- Starts with `helm.sh`

Not sure what to do about the `app` label. Opinions?

**Comment by marians** [comment]
The Kubernetes API endpoint is currently displayed as an IP address.

![image](https://user-images.githubusercontent.com/273727/186639580-5730726f-1f62-43c5-9ce6-e87025921210.png)

There has been a [change to kubectl-gs login](https://github.com/giantswarm/kubectl-gs/pull/876) to use a host name instead of the IP for the kubeconfig file. If that works for customers too, which I assume, I'd like us to be consistent in happa and show the same host name instead of the IP address.

I asked some questions in [Slack](https://gigantic.slack.com/archives/C03LV8E0RL7/p1661423050040279).

**Comment by marians** [comment]
We should indeed copy the mechanism from https://github.com/giantswarm/kubectl-gs/pull/876/files?diff=unified&w=0#diff-1f160945410f9311805f9b1ff5284e4cbb59cdd8934057db5bd7b3e40049979fR208 for happa and display a host name instead of IP to users.

**Comment by vvondruska** [comment]
Notes from refinement:
- Hide labels starting with `app.kubernetes.io` and `helm.sh` and `app`
- Show Kubernetes API hostname instead of an IP: https://github.com/giantswarm/kubectl-gs/pull/876/files#diff-1f160945410f9311805f9b1ff5284e4cbb59cdd8934057db5bd7b3e40049979fR208

**Comment by gusevda** [comment]
Let's test Happa on frieza for read-only users.
