### ISSUE TITLE
IRSA Checklist

### ISSUE THREAD

**Issue by njuettner** [giantswarm/roadmap#1194]
To ensure the operation works smoothly please go through this checklist with the customer **before** upgrading the cluster:

- [ ] Please read [docs](https://intranet.giantswarm.io/docs/dev-and-releng/irsa/) carefully
- [ ] Make sure the following IAM permissions for `GiantSwarmOperator` IAM role are set inside the AWS account where the cluster stays: 
```
iam:CreateOpenIDConnectProvider
iam:DeleteOpenIDConnectProvider
iam:TagOpenIDConnectProvider
iam:UntagOpenIDConnectProvider
iam:ListOpenIDConnectProviderTags
s3:PutObjectAcl
```
- [ ] Current IAM roles from customers must be edited, a new trust releationship must be included to allow customer pods assuming the IAM roles. An example can be found [here](https://intranet.giantswarm.io/docs/dev-and-releng/irsa/#usage)
- [ ] Double check the amount of S3 buckets doesn't scratch the limit, soft limit is 100 and can be increased to 1000. This is usually done by the aws-servicequotas-operator to ensure we have the max amount of S3 buckets available
- [ ] Ensure the release where the cluster is upgraded to contains rolling all nodes, this is necessary in order to avoid ugly behaviour in the api-server
- [ ] Set irsa annotation `alpha.aws.giantswarm.io/iam-roles-for-service-accounts: ""` on the AWSCluster CR
- [ ] Trigger the cluster upgrade
