### ISSUE TITLE
Versioning of Operators

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#12]
## User Story

As a GS Engineer, I want to have one latest version per operator codebase for all operators.

## Background / Current state

- Currently, (almost) every operator's codebase contains multiple versions. That is, we have multiple packages, with each package being part of a version.
- In the version bundle, we have each relevant package wired up into a version bundle.
- When an operator sees a Custom Resource - which has the version bundle embedded - the operator then dispatches to the right controller version dependent on the version bundle.

## TODO

- [x] Observability of control plane capacity
- [x] release-operator ensures App CRs
- [x] Deploy azure-operator to a test environment
- [x] Having branches in test catalog
- [x] Running aws-operator from catalog in control planes
- [x] Deploy multiple aws-operators 
- [x] Run multiple aws-operators 
- [x] Handle changelogs with multiple aws-operators
- [x] Correctly reconcile multiple clusters with aws-operator
- [x] CI for deploying multiple aws-operators 
- [x] Flatten aws-operator
- [x] Add support for 'opsctl deploy' to override existing App CRs during deployment  
- [x] Remove unused fields from releases repository 
- [x] Flatten cluster-operator
- [x] Add support for ensuring that multiple operators are not reconciling the same CR
- [x]  Flatten cert-operator
- [x]  Flatten chart-operator
- [x] Flatten Azure-operator
- [x] Flatten kvm-operator
- [x]  Flatten app-operator
- [x] Use label selectors for watching aws-operator CRs
- [ ] Tag repository on release version in project.go

## Deliverables

- Deployed software
- New CI architecture
- Process change
- Internal documentation

## Control Plane / Tenant Cluster

Control Plane 

## Provider

all

## Blocked by / depends on

n/a

## Customers driving/requiring this

GS product teams
