### ISSUE TITLE
Automate configuration management of installations

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#121]
## User Story

_- As a Giant Swarm Engineer, I want to have an automated way of configuration management of Control Planes so that I don't want to write and deploy all configurations for CPs manually._

_- As a Giant Swarm Engineer, I want an automated way of configuration management of Control Planes so that it enables Control Plane automation._

## Details, Background

Configuration of Control Planes is currently static and manual. The configuration is manually written for a specific Control Plane and deployed manually. Similarly to the overall automation of Control Planes, there is no interface for configuration management.

We will need a service that manages the Control Plane configuration. This service should be responsible for creating and updating configuration, as well as providing configuration to Control Planes.

For example, when a new Control Plane is created, this service creates configuration given some necessary information and then provides it to the new Control Plane. 

As updates are required, the service is responsible for receiving new configuration from operations and ensuring Control Plane configuration is updated. It should also be possible to provide reasonable defaults, on multiple levels - for example, globally, per provider, or other dimensions.

Configuration should be on the app level, not catalogue level. We should get rid of installation configmap, service provider configuration.

## [WIP] Milestone 0. Figure out the design

- [x] https://github.com/giantswarm/giantswarm/issues/13866 Figure out how to do secrets encryption 
- [x] https://github.com/giantswarm/giantswarm/issues/13872 Setup the agent (config-operator)
- [x] https://github.com/giantswarm/giantswarm/issues/13873 Design the structure of configurations repo

## Milestone 1. Move the configuration for 1 app (`aws-operator`)

- [x] https://github.com/giantswarm/giantswarm/issues/14148 Build cli for config-controller
- [x] https://github.com/giantswarm/giantswarm/issues/14149 Make config-controller an operator
- [x] https://github.com/giantswarm/giantswarm/issues/14150 Setup giantswarm/config, add necessary values
- [x] https://github.com/giantswarm/giantswarm/issues/14603 Set version annotation in collection App CRs 
- [x] https://github.com/giantswarm/giantswarm/issues/14151 Move aws-operator chart to use new config keys

## Milestone 2. Migrate all apps

- [x] https://github.com/giantswarm/giantswarm/issues/15230 Migrate all non unique Apps to giantswarm/config
- [x] https://github.com/giantswarm/giantswarm/issues/17386 Migrate unique apps
- [ ] #122 Remove draughtsman entirely 

## Milestone 3. Cleanup
- [x] https://github.com/giantswarm/giantswarm/issues/18481
- [x] https://github.com/giantswarm/giantswarm/issues/15414
- [ ] https://github.com/giantswarm/giantswarm/issues/15381
- [ ] https://github.com/giantswarm/giantswarm/issues/18258
- [x] https://github.com/giantswarm/giantswarm/issues/18260

**Comment by snizhana-dynnyk** [comment]
Slack thread https://gigantic.slack.com/archives/C0251MXL5/p1589809023494500

**Comment by JosephSalisbury** [comment]
Notes: https://docs.google.com/document/d/1gEbZGHD0qHxQv4FLkyqr-lC08wI0PX7TBjm5lRoyUus/edit

**Comment by snizhana-dynnyk** [comment]
From Pawel:

- We want to be able to deploy the same App in multiple configurations to arbitrary clusters (CPs or TCs). E.g. opsgenie-scheduler, crsync.
- We still need to be able to test app in any of those configurations, i.e. deploy it with a slightly different configuration temporarily.

**Comment by snizhana-dynnyk** [comment]
<img width="1918" alt="Screenshot 2020-10-20 at 12 00 56" src="https://user-images.githubusercontent.com/54959552/96587884-33bf8e00-12e3-11eb-92d6-09c98a50a0b6.png">

**Comment by wtty-fool** [comment]
Note: Refactoring `opsctl` or at least writing a new `service` for it might be necessary if we change the way the config is generated. 

Right now `opsctl` relies on `service/installation`, which is based on an assumption that we are using `installations` repository with subfolders for each control plane.

**Comment by JosephSalisbury** [comment]
See https://docs.google.com/document/d/1DHTuU_o_rDQSrvqTy87ujEtVDRMb4rVMakCxLMr4fxY/edit for notes from todays config management refinement
