### ISSUE TITLE
region info in opsctl

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1210]
### TODO
- [ ] add info to cluster.yaml during bootstrap
- [ ] update cluster.yaml for existing clusters
- [ ] update opctl to display it

**Comment by gawertm** [comment]
see also https://gigantic.slack.com/archives/C01BYMF6RN0/p1664186310935439
same ticket from @QuentinBisson https://github.com/giantswarm/giantswarm/issues/23790
