### ISSUE TITLE
Remove draughtsman entirely

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#122]
## User Story

___- As a Giant Swarm engineer, I want to use one way of deployment for all components so that the complexity is removed.___

## Acceptance Criteria

- [ ] `draughtsman` is not running on any control plane
- [x] when I create a new project, I don't need to manually update anything
- [ ] when I create a new installation, I don't need to manually configure anything

#### Pros
- New employees do not need to learn about draughtsman pipeline - everything via app-operator
- Removes complexity
   - Don't have to update draughtsman project lists with new repos
   - Don't have to update architect with new projects
   - Don't have to update opsctl with new projects
- Batman/Halo doesn't need to consider draughtsman / helm / tiller interactions
- Won't hit rate limit on new installations, as you're only fetching one repository

#### Cons
- app-operator is still early, so there's some risk here

#### Notes
- Removes DraughtsmanRateLimitReached alert would be removed, but replaced with a similar alert from app-collection-updater
- app-collection-updater and app-operator are in app-collection, so they can update themselves
- All components deployed to a control plane are in app-collection

## TODO

- [x] https://github.com/giantswarm/giantswarm/issues/10177 Move all CP projects to use app collections 
- [x] https://github.com/giantswarm/giantswarm/issues/10558 [SPIKE] How to deploy collections without draughtsman
- [x] https://github.com/giantswarm/giantswarm/issues/16949 Create CI workflow in giantswarm/config
- [x] https://github.com/giantswarm/giantswarm/issues/16931 Create a design document for draughtsman replacement 
- [x] https://github.com/giantswarm/giantswarm/issues/16862 Install argocd on management clusters
- [x] https://github.com/giantswarm/giantswarm/issues/16944 Make config-controller CLI access vault without opsctl
- [x] https://github.com/giantswarm/giantswarm/issues/16945 Make config-controller read data from local FS 
- [x] https://github.com/giantswarm/giantswarm/issues/16946 Make config-controller generate App CRs with injected CM and Secret
- [x] https://github.com/giantswarm/giantswarm/issues/16947 Install config-controller in argocd-repo-server
- [x] https://github.com/giantswarm/giantswarm/issues/16948 Make architect-orb create Argo Applications in argocd namespace
- [x] https://github.com/giantswarm/giantswarm/issues/17193 Create Argo Application that syncs App Collections
- [x] https://github.com/giantswarm/giantswarm/issues/17195 How can we deploy a branch of an application?
- [x] https://github.com/giantswarm/giantswarm/issues/17196 Check opsctl update draughtsman still updates configmap and secret
- [x] https://github.com/giantswarm/giantswarm/issues/17232 Adding china provider and test provider to management-clusters-fleet
- [x] https://github.com/giantswarm/giantswarm/issues/17233 Update taylorbot token to have permission to read private repos
- [x] https://github.com/giantswarm/giantswarm/issues/17197 Migrate from draughtsman to ArgoCD

### Migration
- [x] https://github.com/giantswarm/giantswarm/issues/16865 Phasing out draughtsman
- [x] https://github.com/giantswarm/giantswarm/issues/10866 Ensure observability over App collection deployment
### Cleanup
- [x] Remove GitHub Deployment support from architect (including secrets in circle) - done in WG
- [x] https://github.com/giantswarm/giantswarm/issues/10563 Remove GitHub Deployment support from `opsctl`
- [x] https://github.com/giantswarm/giantswarm/issues/10565 Update template repositories 
- [x] https://github.com/giantswarm/giantswarm/issues/18165
- [ ] https://github.com/giantswarm/giantswarm/issues/17194 Test if deleting app collection helm release after migration is safe
- [ ] https://github.com/giantswarm/giantswarm/issues/10562 Remove draughtsman configuration from installations
- [x] https://github.com/giantswarm/giantswarm/issues/10564 Update installation guide
- [x] https://github.com/giantswarm/giantswarm/issues/18502
- [ ] https://github.com/giantswarm/giantswarm/issues/17317
- [ ] https://github.com/giantswarm/giantswarm/issues/17698
- [ ] https://github.com/giantswarm/giantswarm/issues/18610
- [ ] https://github.com/giantswarm/giantswarm/issues/17790
- [x] https://github.com/giantswarm/giantswarm/issues/17703
- [x] https://github.com/giantswarm/giantswarm/issues/17265
- [ ] https://github.com/giantswarm/giantswarm/issues/17179
- [x] https://github.com/giantswarm/giantswarm/issues/17166
- [ ] https://github.com/giantswarm/giantswarm/issues/18202
- [ ] https://github.com/giantswarm/giantswarm/issues/18644
- [x] https://github.com/giantswarm/giantswarm/issues/19840

**Comment by rossf7** [comment]
So I have a few thoughts here.

How does release-operator fit into this?

If the app CRs for operators in a release are created dynamically that would be more efficient and replace the current manual cleanup which is painful.

Its great that the updater will deploy app-operator. As we have chicken egg problems there. We try to fix failed chart-operator deployments in app-operator.

Lastly there was an idea to use Flux for this. I think that's interesting and worth exploring. IIRC we've suggested customers use Flux for managing app CRs. So maybe we can do the same ourselves?

**Comment by sslavic** [comment]
We keep on being paged for failed app upgrades due to App CRs referencing test catalogs. e.g. see https://gigantic.slack.com/archives/C03CPNRTS/p1601302499107200

Helm 2 is not doing 3-way merge, so manually changed App CRs to reference test catalogs while testing the control plane app like prometheus-meta-operator, continue to use test catalog when non-test release rollout is attempted (Helm 2 patches just version, since it's not aware of catalog reference changed). Helm 2 is EOL.

Please have draughtsman changed to use Helm 3 or prioritize getting rid of draughtsman entirely.

**Comment by gianfranco-l** [comment]
@kubasobon  could you please have a look at this epic and see if and which tasks are still relevant and keep only the meaningful ones? cc @piontec

**Comment by kubasobon** [comment]
It is still relevant. I'll take a look at the tickets and try to comment on those. It mostly relates to https://github.com/giantswarm/giantswarm/issues/18503 and some cleanup/doc/CI tasks.

**Comment by kubasobon** [comment]
Closing. Superseded by https://github.com/giantswarm/giantswarm/issues/22239
