### ISSUE TITLE
Add support for DNS for CAPVCD

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1247]
### User Story 
- As a customer I want DNS entries for the Kubernetes API server and Ingress in my cluster.

### Background 
- For Openstack we have [dns-operator-openstack](https://github.com/giantswarm/dns-operator-openstack)
- for gcp whe have [dns-operator-gcp](https://github.com/giantswarm/dns-operator-gcp)

### Progress

https://github.com/giantswarm/roadmap/issues/1247#issuecomment-1198039584

**Comment by cornelius-keller** [comment]
@giantswarm/team-rocket please let's refine this asynchronously
Do we need to create another operator for VCD, or is there a way to make one of the above more generic and use them for all the providers?

**Comment by kopiczko** [comment]
@bavarianbidi it's also watching ingress LB Service and creating entry for external IP.

**Comment by kopiczko** [comment]
* Is API behind LB in VCD? And if so is API LB IP exposed somewhere in VCD cluster object?
* Are LB services supported in VCD?

**Comment by erkanerol** [comment]
@kopiczko @bavarianbidi I am under the impression that 
- `dns-operator-<provider>` must use provider-specific DNS service
- since we don't have DNS service for OpenStack, we use AWS Route 53
- For GCP, We use GCP services. See https://github.com/giantswarm/dns-operator-gcp/blob/main/pkg/registrar/package.go#L6

Therefore, the diff between providers is not only the source of information (status of some CRs) but also the DNS provider. While making existing operators more generic, we can design them according to DNS providers like `dns-operator-route53` and use some generic config (like deletion-blocker-operator) to be able to reuse the operator.

**Comment by kopiczko** [comment]
Yeah but we'll take the same approach for any on-prem provider (i.e. Route 53).

**Comment by vxav** [comment]
@kopiczko 
> * Is API behind LB in VCD? And if so is API LB IP exposed somewhere in VCD cluster object?
Yes and yes, it is in the vcdcluster objects.

> * Are LB services supported in VCD?
Yes.

**Comment by bavarianbidi** [comment]
Status:

PRs:
- [ ] https://github.com/giantswarm/dns-operator-openstack/pull/70/

Next steps:
- [ ] rename `dns-operator-openstack` to `dns-operator-route53`
- [ ] extend `helm chart` to grant infrastructure provider specific RBAC rules, depending on the target MC
- [ ] test on `CAPVCD`
- [ ] after re-name push to `capvcd-collection` as well
- [ ] after rollout on all CAPO-MCs, check if the old finalizer-name `dns-operator-openstack` was gone (on `capo.cluster`) - remove Code TODOs (introduced in PR https://github.com/giantswarm/dns-operator-openstack/pull/70/)

Future steps:
- [ ] implement ginkgo based testing

**Comment by JosephSalisbury** [comment]
In last discussion w/ mario, we talked about future steps. if we have some time in this week, erkan wants to try and invest on future steps if possible

**Comment by erkanerol** [comment]
The migration is done. The improvements will be done in the scope of a separate issue https://github.com/giantswarm/roadmap/issues/1304. 

Closing 🎈
