### ISSUE TITLE
Apps should provide an icon for usage in small, rectengular spaces

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1248]
Every app in a Giant Swarm catalog can provide an icon URL. Icons allows users to recognize and distinguish an items quicker and easier in a list of many items.

So far we have set app icons in a way that was optimized for the use in happa's app catalog list views. Example:

<details>
<summary>Examples</summary>

![image](https://user-images.githubusercontent.com/273727/179232493-a3148e6e-ffad-46b6-a3cd-e47b9caf2263.png)

![image](https://user-images.githubusercontent.com/273727/179232539-67da9290-6cad-4fdd-bee8-d6c3fdc2faf8.png)

![image](https://user-images.githubusercontent.com/273727/179232593-9659c058-b396-4f03-a9a2-bc8c4e14b874.png)

</details>

These icons often work best in a rectangular-shaped container that have a width:height ratio of 2:1.

However, so far we don't have a way to provide an icon which is guaranteed to work well in a space-constrained square shape container. The following example illustrates such a use case.

Example of a list of app without icons:

![image](https://user-images.githubusercontent.com/273727/179231964-7eadb9c6-5634-4f2c-85fd-4521769588e2.png)

Example of a similar list of app with icons:

![apps-with-icons](https://user-images.githubusercontent.com/273727/179231806-b9f36b3c-2b61-402c-ba2e-7376fd9e7372.png)

In our app metadata, we are currently limited to 1 icon URL in the Helm chart ([example](https://github.com/giantswarm/nginx-ingress-controller-app/blob/b61d4c243cc444a033b9066b8e863a5244cf999b/helm/nginx-ingress-controller-app/Chart.yaml#L5)).

## TODO

- [x] Communicate change of spec internally:
  - [x] intranet PR
  - [x] announcement
- [ ] Adapt most apps we expect to be installed in WC (default apps, preinstalled, Giant Swarm catalog)
- [x] Display app logos for catalogs in the web UI if the logo is provided

**Comment by marians** [comment]
Some options we have:

- Always use the one `icon` metadata property to specify the icon that fits in a square space. (As a result, we would loose the more expressive logos that work well in a larger space.)
- Define an additional icon annotations for the new purpose
- Define some implicit lookup logic. E. g. if the icon URL ends in `logo.svg`, we also check for an icon with the URL ending in `logo_icon.svg`.
- Use [SVG fragment identifiers](https://www.w3.org/TR/SVG11/linking.html#SVGFragmentIdentifiers). With this option, all available icon formats would be included in the same SVG file. We would define a set of views with standard names. A view is basically a rectengular part of an SVG's content. For this to work, all icon files would have to implement all views.
- For each of our apps, have additional icons hard-coded into happa

**Comment by marians** [comment]
Would be great to get some input from Honey Badger on this @gianfranco-l .

**Comment by gianfranco-l** [comment]
left a note on @giantswarm/team-honeybadger board to provide input on this

**Comment by piontec** [comment]
Hmm... I prefer explicit solutions, so if you really want to implement this, I would introduce a new annotation (`Chart.yaml`s allow for arbitrary annotations and AFAIR we're automatically copying them from chart's metadata to ACE CRs).

**Comment by uvegla** [comment]
I would go with the `logo` meta data [in Chart.yaml](https://helm.sh/docs/topics/charts/#the-chartyaml-file). It seems to be standard way and will work with custom apps created by users for private catalogs.

**Comment by marians** [comment]
Based on your feedback, and with some distance, I've been re-thinking this. How about this combined solution:

- We use the `icon` metadata field in Chart.yaml for a square icon. Because "icons" in the classical sense were exactly that: little square images.
- We introduce a new, optional annotation for an additional catalog image URL. This one is supposed to work well in the landscape image size ratio.

## Example

Icon:

![image](https://user-images.githubusercontent.com/273727/183440642-fae2aa89-2a64-44a3-b6db-f1a7c4bc658a.png)

Catalog image:

![image](https://user-images.githubusercontent.com/273727/183440743-5670249f-2477-4d64-832d-7b05942984a4.png)

**Comment by marians** [comment]
We just discussed the above proposal (https://github.com/giantswarm/roadmap/issues/1248#issuecomment-1208201606) in Rainbow and decided to pursue it this way. There will be an intranet update where other teams are invited to review. After that is merged, we'll start adapting the most important apps.

**Comment by kuosandys** [comment]
[Intranet documentation](https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/apps_in_happa/) for providing icons for apps in happa has been updated. We think the task of updating icons for apps could be a good task for Team Rainbow's working student, and the appropriate label has been added to this issue.

**Comment by marians** [comment]
Notes

- in web-assets, we want to use a naming cnovention to distinguish icon and logo. Suggestion: e. g. `logo_dark.svg` and `icon_dark.svg`
- We reference the dark version in Chart.yaml
- Based on [Grafana](https://giantswarm.grafana.net/explore?left=%7B%22datasource%22:%22000000006%22,%22queries%22:%5B%7B%22expr%22:%22sum%28aggregation:giantswarm:app_deployed_workload_cluster_total%29%20by%20%28catalog,%20app%29%22,%22format%22:%22table%22,%22instant%22:true,%22interval%22:%22%22,%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22000000006%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D&orgId=1) app usage data we add icons where they are missing, starting with the most used apps

**Comment by marians** [comment]
Ideally we would also target all `cluster-PROVIDER` and `default-apps-PROVIDER` app repos and add an icon. They are important and would look strange without one.

**Comment by mogottsch** [comment]
They are on my list and some already got their icon :+1:

**Comment by marians** [comment]
FYI @mogottsch Xavier (@vxav) wrote me that he is working on adding the icon to Cloud Director apps.

**Comment by marians** [comment]
@vxav Yes, looks good!

**Comment by weatherhog** [comment]
closing this issue
