### ISSUE TITLE
VCD: Create a tekton pipeline to build and distribute machine images

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1251]
### User Story (Updated by Erkan on 18/07/2023)
- As a giant swarm customer on VCD I want the images with new k8s and os versions to be build automatically and uploaded into my installation so that I can use them to create clusters

### Tasks

- [ ] Adapt https://github.com/giantswarm/capi-image-builder to build OVA images for CAPVCD
   - [ ] Decide where to store the images. Other teams use GS accounts on public clouds.
   - [ ] Add a pipeline for Flatcar
   - [ ] Add a pipeline for Ubuntu

**Comment by cornelius-keller** [comment]
@vxav question for you regarding this tasks: how portable are the VCD images? Can we build them in one installations and then download them and redistribute them to all others?

**Comment by vxav** [comment]
If the question is "_Can we use the same image in different installations_", the answer is yes.
If the question is "_How to programmatically create and distribute the images to multiple installation_", I don't know the answer.

**Comment by cornelius-keller** [comment]
Is there a tooling to download and upload images from and to different installations? If so we need to find a way to use it in our pipelines. Is there a rest API to VCD that allows such operations?

**Comment by vxav** [comment]
From what I can tell at first glance there's vcd-cli (which @ericgraf will hate me for mentioning).
http://vmware.github.io/vcd-cli/vcd_catalog_upload
`vcd catalog upload catalog1 photon-custom-hw11-2.0-304b817.ova`

API wise, it looks like this would be the method to use.
https://developer.vmware.com/apis/1245/vmware-cloud-director/doc/doc/types/UploadVAppTemplateParamsType.html

**Comment by glitchcrab** [comment]
Dumping  some info from the other ticket here:

- thoughts from planning
  - initial bootstrap
  - how to deal with multiple managment clusters -> how to synchronize
  - check how the VCD api works, maybe we can sync via it, it might be blocking
  - maybe prefix image names with managment cluster names

**Comment by gawertm** [comment]
awaiting image building ownerhsip from https://github.com/giantswarm/giantswarm/issues/24704

**Comment by gawertm** [comment]
@jkremser this is an older issue we had in for long time. recently we didn't know where the image builder pipeline will land. Team tinkerers will now own it. so you can get in touch with them, how to add support for CAPVCD. the goal would be to build our own flatcar images. 
maybe you can get into it, summarize the current status and what needs to be done, to get VCD support

**Comment by gawertm** [comment]
done with new image distribution operator
