### ISSUE TITLE
CAPVCD: follow-up tasks for alpha status

### ISSUE THREAD

**Issue by glitchcrab** [giantswarm/roadmap#1273]
In order to have fully functioning CAPI clusters on VMware Cloud Director, we need to address some long-tail issues to achieve alpha status:

- [ ] Debug and test GS apps and platform running on VCD - blocked by https://github.com/giantswarm/roadmap/issues/1271
   - running other apps, teams will need a stable MC for testing
   - iirc (joe), sig product has some plans on how to organise to have CNP teams test their apps 
   - see https://github.com/giantswarm/giantswarm/issues/23185
- [ ] Handle deletion of MCs for quicker turn around
   - vcd cli is bullshit
   - do something with ansible
   - clusters aren't properly running, so we need to garbage collect
   - see https://github.com/giantswarm/giantswarm/issues/23186
- [ ] Figure out how VCD wants to handle network/environment setup/teardown for prod and testing
   - possibly an issue in the roadmap. 
   - "for WCs, use MC network. can always manually create a network, deploy a cluster to it"
   - See https://github.com/giantswarm/giantswarm/issues/23189
- [ ] We need to figure out the long term test environment setup
   - not just ikoula? 
   - standardising the ikoula setup
   - ticket: sort out the email, make sure xavier is not a SPOF
   - See https://github.com/giantswarm/giantswarm/issues/23187
- [x] Drastically increase our testing environment resources

**Comment by glitchcrab** [comment]
related - https://github.com/giantswarm/roadmap/issues/1271

**Comment by JosephSalisbury** [comment]
@JosephSalisbury fucks around with the list

**Comment by JosephSalisbury** [comment]
Broken down into smaller issues, closing here
