### ISSUE TITLE
Managed transit gateway

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1306]
## Story

_*-As a cluster admin, I want traffic to be routed through a transit gateway managed by Giant Swarm in order have a centralized solution for routing traffic instead of lots of point-to-point peering connections between the management cluster VPC and the workload cluster VPCs.*_

_*-As a Giant Swarm engineer, I want to have the option to use a transit gateway while testing new features in order to simulate the customer's environment.*_

## Background

Some of our customers use a central transit gateway to manage traffic in their infrastructure and have requested to route traffic through in a similar way between Giant Swarm managed clusters.

Traffic between Giant Swarm managed clusters has been routed either through peering connections or over the Internet, protected by firewall rules.

Giant Swarm will support 3 modes for transit gateways:
- customer managed. The customer controls the transit gateway and custom integration is required to attach it to VPCs;
- Giant Swarm managed. Giant Swarm automation controls the creation and attachment of the transit gateway. The current story refers to this mode;
- none. No transit gateway. Traffic between clusters is routed using VPC endpoints and only for those services that need to be accessed from a different VPC. The customer will have the freedom to use a transit gateway or VPC peering with minimal impact on Giant Swarm automation.

## Requirements

- create a new transit gateway as part of the `mc-bootstrap` when a management cluster is created;
- the transit gateway needs to be attached to the management cluster VPC;

## Questions

- When will the Giant Swarm VPN be attached to the transit gateway?
> In the context of a private management cluster (no bastion hosts or Kubernetes API exposed to the Internet), the only way to access the Kubernetes cluster is through the Giant Swarm VPN which needs to be configured and attached to the transit gateway in order for the `mc-bootstrap` to properly create the cluster.
> The Giant Swarm VPN will only be needed after we switch to using a private load balancer for the Kubernetes API.

- How will the route tables be managed?
> The routing rules need to be updated when a management or workload clusters is created. Maybe, transit gateway propagation rules or prefix lists could be used to ease the configuration.
> Talax will have the routes already configured because they will know all the CIDR blocks before any cluster is created. This probably doesn't make much sense for a dynamic test environment.

## Resources

- [AWS Transit Gateway](https://docs.aws.amazon.com/whitepapers/latest/aws-vpc-connectivity-options/aws-transit-gateway.html);
- [Giant Swarm test proxy environment diagram](https://miro.com/app/board/uXjVODIW9Rs=/?moveToWidget=3458764531000127919&cot=14).

**Comment by alex-dabija** [comment]
The transit gateway will be part of the mc-bootstrap and it will be managed by an custom operator.

**Comment by AverageMarcus** [comment]
Todo:

- [ ] Add a "networkMode" property to `cluster-aws` that supports the options: `GiantSwarmManaged`, `UserManaged`, `None` (The three options above) - For now we'll focus on the `GiantSwarmManaged` option.
- [ ] Create a `transit-gateway-operator` that watches for `Cluster` resources and performs two actions: 1) Create a new Transit Gateway if one doesn't yet exist in the **region** of the cluster (true for both MC and WC). 2) Attach the TGW to the cluster's VPC. A finalizer will also need to be added to the MC cluster resources to ensure upon deletion of the MC that the TGW is also removed.
- [ ] Add the `transit-gateway-operator` as a default MC app for CAPA clusters.
- [ ] Update the `mc-bootstrap` to install the `transit-gateway-operator` into the Kind cluster prior to applying the MC cluster resources to ensure the TGW and the VPC are created together (one by `transit-gateway-operator` and the other by `cluster-api-provider-aws`)

Needs clarification:
* Does a TGW automatically get disconnected from a VPC when that VPC is deleted? 
* Both the `transit-gateway-operator` and `cluster-api-provider-aws` are likely to encounter errors initially while trying to create their resources as they'll be reliant on each other (e.g. VPC first, then TGW + attachment, then resources within the VPC). We'll need to make sure both are resilient to this initial complication.
* When `UserManaged` is used, the ID of the TGW will be needed (we'll need some way of accepting this from the user) but we'll also need some information about how TGW attachments to VPCs are performed. This could be (likely) customer specific. One thought is storing this info in the `config` repo to avoid having a messy values.yaml in `cluster-aws` as it will likely be the same across all MCs for a given customer.

**Comment by AverageMarcus** [comment]
### Current Status

Operator exists that can:
* create a TGW for MCs and create an attachment for MC VPC
* create additional attachments for WC VPCs
* remove attachments when WCs deleted

### TODO:
- [ ] Check for overlapping VPC CIDRs 
- [ ] Update cluster subnets route tables with routes to TGW (blocker)

**Comment by AverageMarcus** [comment]
For user managed mode:

* Transit gateway ID and Prefix List ID must be known ahead of time.
* operator sends SNS to get VPC attached (by sending CIDR and VPC Id)
* operator then uses the TGW ID and prefix list ID to update the subnet route tables

**Comment by AverageMarcus** [comment]
GiantSwarmManaged transit gateway mode now complete and deployed as a control plane application. 

UserManaged mode will be covered at a later date by its own issue.

Closing as done.
