### ISSUE TITLE
Retire app-updater app

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1314]
We created https://github.com/giantswarm/app-updater for our own purposes, but have replaced it by Flux.

Since Flux is the recommended way to do these things, I suggest we stop maintaining the app and remove it from the playground catalog.

I checked and according to https://giantswarm.grafana.net/d/s5jQpdyMz/managed-apps-usage?orgId=1&var-catalog=giantswarm-playground the app is not in use.

There is a TODO list (work in progress) regarding how to retire an app [in Slack](https://gigantic.slack.com/archives/CRZN9GLJW/p1660551123400609).

**Todos**:
- [x] Check whether the app is used in any clusters. Use [this dashboard](https://giantswarm.grafana.net/d/s5jQpdyMz/managed-apps-usage?orgId=1) for the purpose.
- [x] If the app is still in use, reach out to the people/customers using it and inform them about the plan to retire the app. Offer help to migrate to a different solution.
- [x] Update the main README in the app GitHub repository to indicate that the app is no longer maintained/developed. Ideally, point the reader to any alternative solutions.
- [x] Archive the GitHub repository.
- [x] Once the app is no longer used, remove it from the catalog(s) it has been published in. This includes entries in index YAML of the catalog repo as well as tar.gz and metadata .yaml files.
- [x] Additionally you might take a look in our [giantswarm/retagger](https://github.com/giantswarm/retagger) repository and the [docs automation](https://github.com/giantswarm/docs/blob/main/scripts/aggregate-changelogs/config.yaml) and remove relevant entries there.

**Comment by marians** [comment]
Docs for retiring an app are now in https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/retire-app/
