### ISSUE TITLE
Use apps for Storage Class, CSI and CPI on CAPVCD 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1315]
## Background
capvcd controller currently installs StorageClass, CSI, and CPI via cloud-init (static pods). in future versions, they'll use clusterresourcesets. we can move to apps then.

## Tasks 
- [x] Update mc-bootstrap to use cluster ID (see https://github.com/giantswarm/mc-bootstrap/pull/226)
- [x] Add storage class to cloud provider cloud director app
- [x] Update cluster-api-provider-cloud-director to use build without cpi/csi in cloud init.

**Comment by cornelius-keller** [comment]
@erkanerol @vxav what is the upstream timeline for moving the components out of the cpavcd operator? Is there already an upstream relase planned for this?

**Comment by vxav** [comment]
I think you want to change the title to cloud director, not vSphere.

A PR was created upstream over the weekend so I expect this to be merged within the week.

https://github.com/vmware/cluster-api-provider-cloud-director/pull/228

**Comment by glitchcrab** [comment]
tested, but broken, awaiting upstream response

**Comment by vxav** [comment]
Fixed in `quay.io/giantswarm/cluster-api-provider-cloud-director-vcd:e6a551d`

Need to add `cloud-provider-cloud-director-app` to `default apps`.

Requires `clusterid` in values file that we can get from `vcdcluster` object.
