### ISSUE TITLE
CAPI Ubuntu 22.04 images

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1324]
## Task

Generate and use Ubuntu 22.04 images for CAPG & CAPA clusters.

## Background

CAPG & CAPA cluster use Ubuntu 20.04 images with Control Groups v1 which is enabled by default. AWS vintage is already using Control Groups v2.

All the CAPI clusters, including CAPG & CAPA ones, must use Control Groups v2.

Control Groups v2 are enabled in Ubuntu 22.04 out of the box.

## TODOs:

- [x] generate CAPI images with Ubuntu 22.04;
- [x] update `gohan` to use Ubuntu 22.04 images;
- [x] update `gunter` to use Ubuntu 22.04 images;
- [x] update `frieza` to use Ubuntu 22.04 images;
- [ ] update `frieza / appstack` to use Ubuntu 22.04 images;
- [x] update `golem` to use Ubuntu 22.04 images;
- [ ] update `tornado` to use Ubuntu 22.04 images;
- [ ] any other cluster should also be migrated to use Ubuntu 22.04 images;

**Comment by AverageMarcus** [comment]
Currently, image-builder is impacted by this issue (https://github.com/hashicorp/packer/issues/11733) and unable to build Ubuntu 22.04 images without some workaround. I haven't yet managed to get a workaround to actually work though.

**Comment by AverageMarcus** [comment]
PRs:
* https://github.com/giantswarm/cilium-app/pull/44 (will need default-apps-... updating once released)
* https://github.com/giantswarm/cluster-aws/pull/129/ (blocked by first PR)
* https://github.com/giantswarm/cluster-gcp/pull/163 (blocked by first PR)
* https://github.com/kubernetes-sigs/image-builder/pull/994 (upstream)

**Comment by AverageMarcus** [comment]
Default-apps PRs:
* https://github.com/giantswarm/default-apps-gcp/pull/95
* https://github.com/giantswarm/default-apps-aws/pull/83

**Comment by AverageMarcus** [comment]
New CAPA and CAPG clusters will now use Ubuntu 22.04 by default. Existing clusters still need to be updated.

**Comment by AverageMarcus** [comment]
PR for updating `gohan` and `gunther` - https://github.com/giantswarm/management-clusters-fleet/pull/176

**Comment by AverageMarcus** [comment]
`golem` and `tornado` now managed by Flux but apps still need updating. The current versions are fairly outdated so a plan is needed to upgrade safely.

**Comment by AverageMarcus** [comment]
`tornado` needs a specific plan to upgrade. Closing this issue as all others are complete.
