### ISSUE TITLE
Build Images for CAPVCD

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1342]
### Tasks

- [ ] specify what the build pipeline should do for hydra
   - [ ] where to build? Do we need to build inside a vcenter or can we build in the pipeline
   - [ ]  where to put the image
- [ ] create an operator that pulls images into a CAPVCD MC
   - [ ] decide on technology (operator, cronjob, ...) 
   - [ ] how to deal with multiple MCs running against the same VCD api 
   - [x] can we do push based? -> will propaly not work for panamax

**Comment by cornelius-keller** [comment]
- thougths from planning
  - initial bootstrap
  - how to deal with multiple managment clusters -> how to synchronize
  - check how the VCD api works, maybe we can sync via it, it might be blocking
  - maybe prefix image names with managment cluster names
  -

**Comment by glitchcrab** [comment]
closing in favour of https://github.com/giantswarm/roadmap/issues/1251 (dupe)
