### ISSUE TITLE
Make cluster management read-only for GCP

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#1350]
Towards our first milestone for supporting GCP in the web UI.

### Tasks
- [ ] Hide "Launch new cluster" button and messages prompting users to create clusters in the cluster list page (home page)
- [ ] Disable cluster description and cluster labels editing in cluster details
- [ ] Don't display "Actions" tab in cluster details
