### ISSUE TITLE
split cluster configuration and creation steps in mc-bootstrap

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#1354]
As we agreed on the team onsite in mallorca we want to split out the configuration part of management cluster creation into separate tooling.
As a minimal viable product let's first split out mc-configuration into a separate make target, so that it can be run independently of mc-creation.

- [x] create a new target for mc-configuration
- [x] create a new target for mc-creation
- [x] use this targets in the current create-mc target, so that the current functionality is maintained.

**Comment by ericgraf** [comment]
This is dependant on https://github.com/giantswarm/giantswarm/issues/23347

**Comment by ericgraf** [comment]
This change has been pushed to mc-bootstrap. There is still functionality changes that need to be done, but is tracked by other issues.
