### ISSUE TITLE
Catalog Apps READMEs, Icons, Schema

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#136]
User story: As an app developer, I would like an app's README.md to easily describe an app's restrictions, configuration options, and dependencies, so I can install and configure it myself, without having to contact support.

From follow up conversation w @oponder to close https://github.com/giantswarm/giantswarm/issues/8828

For good UX -- All apps in both Giant Swarm Catalog and Playground Catalog should (1) have an app icon, (2) render a proper README, (3) have at least the automatically generated values.schema.json (validating the required default values?) file

Spreadsheet to keep track https://docs.google.com/spreadsheets/d/1swJ9-2iE0ymQpCJ6Ej5QsZtSWDoEJonQ-9ufO3fFDfU/edit#gid=2004681748

By Fri, 23. Oct 2020, make changes to all current apps.

Moving forward, think of a process - maybe manual or automated (e.g. extension to linting), or a combination - to make sure all apps will include them.

**Comment by cokiengchiara** [comment]
I would like to help write the READMEs, but I don't want to be the bottleneck here if anyone is excited to add a good README to one or more apps 🤪 @paurosello @yasn77 cc @giantswarm/team-halo

**Comment by oponder** [comment]
By the way I am seeing that some of the readmes are already really great! So we can probably just review them and see if there is enough information in there for someone brand new to be able to have a successful deploy.

**Comment by cokiengchiara** [comment]
Asking Simon about cert-manager here: https://github.com/giantswarm/giantswarm/issues/12000

**Comment by cokiengchiara** [comment]
@oponder and I chatted and we'd like to do a sweep of all the apps to include (1) icon (2) readme, and (3) schema (https://github.com/giantswarm/roadmap/issues/152)

Spreadsheet here: https://docs.google.com/spreadsheets/d/1swJ9-2iE0ymQpCJ6Ej5QsZtSWDoEJonQ-9ufO3fFDfU/edit#gid=2004681748

**Comment by cokiengchiara** [comment]
Note from @oponder and @rossf7  

Consider a way to automatically lint and alert the repo owners that their app is not UX friendly. We have chart linting in push-to-app-catalog - maybe that can be extended.

**Comment by cokiengchiara** [comment]
Icons by @oponder 

- [x] nginx-ingress-controller-app
- [x] cert-manager-app
- [x] kong-app
- [x] efk-stack-app
- [x] prometheus-operator-app
- [x] aqua-app
- [x] app-mesh-app
- [x] azure-ad-pod-identity-app
- [x] eventrouter-app
- [x] fluent-logshipping-app
- [x] gatling-app
- [x] giantswarm-todo-app
- [x] inlets-operator-app
- [x] istio-operator
- [x] jaeger-operator-app
- [x] k8s-initiator-app
- [x] kibana-oss-app
- [x] kubernetes-gpu
- [x] linkerd2-app
- [x] loki-stack-app
- [x] opencensus-collector-app
- [x] strimzi-kafka-operator-app

Schema

- [ ] nginx - waiting
- [x] cert manager
- [ ] kong - waiting
- [x] efk
- [x] prometheus operator
- [ ] aqua - waiting

README (render in Happa)

- [ ] cert-manager
- [ ] aqua

**Comment by cokiengchiara** [comment]
@oponder took care of the schemas and icons... I still need to check the READMEs.

**Comment by cokiengchiara** [comment]
@oponder , I think you took care of all the schemas, right? 😅 

Finally made PRs for all READMEs!

**Comment by oponder** [comment]
> I think you took care of all the schemas

Yup! I did! I haven't merged them yet.. but they totally could be merged

**Comment by cokiengchiara** [comment]
We're done. @oponder pls correct me if i'm wrong
