### ISSUE TITLE
Giant Swarm GCP group

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1377]
## Task

Create Google group for Giant Swarm staff to grant access to Giant Swarm GCP environments.

## Context

At the moment we use groups like `chapter-pe@giantswarm.io` which are very general. We had the same situation when FADI granted us access to their GCP resources. See [issue](https://github.com/giantswarm/giantswarm/issues/22746).

## Requirements

We need a new group that's not tied to a team and which represents the kind of activities that we do in their environment.

We need access for development and to take care of cluster operations.

It would be great if we could keep things aligned across all providers. For example, we would have similar group(s) on AWS.

## Suggestions
* `gcp-gs@giantswarm.io` - We are our own customer;
* ...

## TODOs
* [ ] Decide on group name(s);
* [ ] Create group;
* [ ] Grant access to our GCP projects to the chosen group;
* [ ] Remove all the extra and unnecessary groups;
* [ ] Verify that we still have access;
