### ISSUE TITLE
Cannot connect to cluster nodes via SSH

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1380]
## Issue

The following works:
```
❯ opsctl ssh gohan bastion1
```

but, I can't ssh to any of the `gohan` cluster nodes (including the control plane nodes):
```
❯ opsctl ssh gohan 10.164.0.24
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
Error: Exit status 255
        /home/alex/work/giantswarm/opsctl/service/ssh/service.go:152
        /home/alex/work/giantswarm/opsctl/command/ssh/command.go:210
        /home/alex/work/giantswarm/opsctl/command/ssh/command.go:111
        /home/alex/work/giantswarm/opsctl/main.go:57

To increase verbosity, re-run with --level=debug
```

## Task

Ensure that SSH works on GCP for both management and workload clusters (bastion hosts, control plane nodes and workload nodes).

## Outcome

- [x] opsctl ssh works for MC bastion hosts;
- [x] opsctl ssh works for MC control plane nodes;
- [x] opsctl ssh works for MC worker nodes;
- [x] opsctl ssh works for WC bastion hosts;
- [x] opsctl ssh works for WC control plane nodes;
- [x] opsctl ssh works for WC worker nodes;

**Comment by alex-dabija** [comment]
@calvix You mentioned in one of our standups that changes to `opsctl` are required to make SSH work for cluster nodes. Could explain what those changes are? Thanks!

**Comment by calvix** [comment]
new opsctl PR allow commands like this
```
# ssh into MC bastion
opsctl ssh golem bastion1

# ssh into MC node
opsctl ssh golem ip-10-0-82-249.eu-west-2.compute.internal

# ssh into WC bastion created by golem MC
opsctl ssh golem bastion1 --cluster=vac04

# ssh into WC node created by golem MC
opsctl ssh golem 10.0.215.136 --cluster=vac04
```
But changes in `cluster-aws` and `cluster-gcp` are also necessary in order to ssh directly into nodes, this is now fixed manually on existing MCs, but we should bump `cluster-XXX` version once the changes are releases

**Comment by calvix** [comment]
done
