### ISSUE TITLE
make mc-bootstrap executable in a pod/container so that we can use it in CI

### ISSUE THREAD

**Issue by ericgraf** [giantswarm/roadmap#1383]
Below are files/values that `generate-mc` make target uses and needs to change in order to run isolated from cli and lastpass access. The below changes need to be made .

- [x] #1392
- [x] #1409
   - Store in MCF
 - [x] #1407
 - [x] #1408
   - global when running as a ci job ( maybe only read access to private MCF )
   - local user github token when run as cli
 - [x] #1391
 - [x] #1390

Follow up tasks:
- [ ] https://github.com/giantswarm/giantswarm/issues/23904
- [ ] https://github.com/giantswarm/giantswarm/issues/23927
- [ ] #1488
- [x] Move scripts/setup-capo-testing-secrets.sh to MCF 

 
 
 # After the above is done change the below commands in generate-mc in mc-bootstrap  
 - [x] Remove lpass usage from generate-mc make target
     - [x] lpass-update-kubeconfig.sh
     - [x] deploy-sops-key-to-cluster.sh
     - [x] setup-fleet.sh
     - [x] adopt-apps.sh
     - [x] setup-capo-testing-secrets.sh 
- [x] Remove requirement on lpass-pull-secrets.sh in generate-mc
  - [x]  https://github.com/giantswarm/mc-bootstrap/pull/272
- [x] Create docker image with dependencies built in.
- [x] Remove docker sub commands from make generate-mc make target ex: docker run yq ... 
- [x] Manage giantswarm-openrc.sh vsphere-credentials.sh cluster-values.yaml in a way that can be passed between make targets.

**Comment by ericgraf** [comment]
Here is a not well formatted todo list of things that needs to be change 
```
#TODO generate-mc needs
# - cluster-<provider>-values.yaml file 
#   - Stored in MCF 
#   - required MCF to be private
#   - requires kuba refactor of MCF

# - openrc/vsphere-credentials/capg/capa credentials
#   - moved to cluster-<provider>-app 
#   - aka cluster-<provider> and default-apps-<provider> values file

# - taylor bot token for installation
#   - Stored in MCF

# - generate-mc github access token
#   - global when running as a ci job ( maybe only read access to private MCF )
#   - local user github token when run as cli

# - sops keys
#   - Must be passed into job as environment variable
#   - make pass into other make job 
#     create-mc:
#	    $(MAKE) create-config
#	    $(MAKE) AGE_KEY=$(shell lpass show -notes path/to/the/$(INSTALLATION)/key) generate-mc

# - previous/handling/storing kubeconfigs
#   - store pki in MCF in cluster-<provider>-values.yaml file 
#   - optional to use in cluster-<provider>-app 
```

**Comment by ericgraf** [comment]
Proof of concept works. Just needs a number of PRs merged.
- https://github.com/giantswarm/mc-bootstrap/pull/323
- https://github.com/giantswarm/mc-bootstrap/pull/332
- https://github.com/giantswarm/mc-bootstrap/pull/331

Once those are merged. Adding the below comment to any PR will start a build. 
```
/test generate-mc

git_ref: <git refference>
INSTALLATION: gs-eric
PROVIDER: openstack
```

Currently only gs-eric is supported .

**Comment by ericgraf** [comment]
To test your own PR merge the above changes by running.

```bash
git merge use-mcf-openrc
git merge add-vcluster-support
git merge add-dockerfile
```

**Comment by ericgraf** [comment]
Main branch of mc-bootstrap can now be tested using the above comment in a PR.
