### ISSUE TITLE
Better release crafting & testing. 

### ISSUE THREAD

**Issue by J-K-C** [giantswarm/roadmap#14]
## Epic Story

- As a Swarmie struggling with the constant battle of releasing via a manual, laborious and time consuming process, I would like our release process to be as automated, pain free and delightful as possible so that I can spend my time on other worthwhile value generating activities. 

## Epic Acceptance Criteria

Iteration 1: Quick fixes whilst we are waiting for VOO (see UserStories 1-6)
Iteration 2. The full end to end release process is automated (see UserStories 7-8)

## Linked User Stories in priority order:

Iteration 1. 

- [x] 1. Improve the reliability of E2E tests giantswarm/giantswarm#5965
- [x] 2. Automate slack channels for release notes giantswarm/giantswarm#5966
- [x] 3. Step by step guide to release notes giantswarm/giantswarm#5967
- [x] 4. Automate slack channel for K8s releases (not needed?) 
- [x] 5. Re-tagger should automatically retag images for k8s releases giantswarm/giantswarm#5968
- [x] 6. Move release info into separate repository giantswarm/giantswarm#5969
- [ ] 10. Automate China E2E tests giantswarm/giantswarm#6052

Iteration 2. stories which are dependent on the completion of VOO giantswarm/giantswarm#5021 

- [ ] 7. Add support to devctl to automatically list PRs since the last release giantswarm/giantswarm#5970 
- [ ] 8. Do a full installation E2E tests from installations giantswarm/giantswarm#5971
- [ ] 9. Add official conformance tests to our E2E tests giantswarm/giantswarm#5972

## Dependencies

- VOO giantswarm/giantswarm#5021 !!

## Other Tasks (non userstories)

- Add k8s next release to calendar and code freeze (Jessica)
- Start preparing new release before new k8s is out by checking upcoming e.g. 1.14.2 (collect updates from components to include etc)
- Write more e3e tests

Aha! Link: https://giantswarm.aha.io/features/L-2
