### ISSUE TITLE
Automation for identity provider management and dex configuration

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#1432]
Coming from the [RFC regarding management cluster access](https://github.com/giantswarm/roadmap/issues/1384) and the [plan to use azure active directory as our default identity provider](https://github.com/giantswarm/giantswarm/issues/21627)

We need automation in order to scale the management of dex connectors and the required application setup as well as rotation of client secrets.

### requirements
- manage a list of identity providers with credentials that should be used in the automation
- manage an application on each configured identity provider for each dex app we run
- manage connector config for each of these dex apps with the data from the identity providers

### Tasks
- [ ] implementation
  - [x] implement app controller
  - [x] implement idp resource
  - [x] implement provider interface
  - [x] add test suite
  - [x] add helm chart and ensure dex operator can be deployed
  - [x] implement azure provider
  - [x] #1593
  - [x] Add README to dex-operator
  - [x] https://github.com/giantswarm/giantswarm/issues/21627
  - [x] #1629
  - [x] https://github.com/giantswarm/giantswarm/issues/24386
  - [ ] https://github.com/giantswarm/roadmap/issues/603
    - [x] #1592 
    - [x] #1845
  - [x] https://github.com/giantswarm/giantswarm/issues/25153
- [ ] initial roll out
  - [x] #1596
  - [x] #1809
  - [x] https://github.com/giantswarm/roadmap/issues/1718
  - [ ] #1856
  - [ ] consider unified design for dex login page across services
- [x] secret mamagement
  - [x] https://github.com/giantswarm/roadmap/issues/1764
  - [x] Either manage existing github apps via dex-operator or clean them up somehow
- [ ] alignment
  - [x] https://github.com/giantswarm/giantswarm/issues/24931
  - [ ] https://github.com/giantswarm/giantswarm/issues/23694
  - [ ] Align all our apps (prometheus, grafana, happa, kgs... etc) to use automated dex for logging in
- [ ] next steps
  - [ ] https://github.com/giantswarm/roadmap/issues/1810
  - [ ] #2486
  - [x] https://github.com/giantswarm/roadmap/issues/1914
  - [ ] https://github.com/giantswarm/giantswarm/issues/24888
  - [ ] Revisit default SSO for all WCs

**Comment by anvddriesch** [comment]
![Screenshot from 2022-09-22 21-05-35](https://user-images.githubusercontent.com/56017655/191750070-2da5072d-73a0-4972-9c23-f5d54060bfd1.png)
sketch from today

**Comment by anvddriesch** [comment]
New operator lives here https://github.com/giantswarm/dex-operator
still WIP

**Comment by gawertm** [comment]
everything is in the epic already.
