### ISSUE TITLE
CAPI Docs

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#1435]
We need to describe how the new CAPI interface works.

 * [x] Overview over CAPI
 * [x] Architecture of CAPI 
   * [x] Management Clusters
   * [x] Workload clusters
 * [ ] Working with the API
   * [x] Cluster API CRDs
   * [ ] Using kubectl gs
 * [ ] https://github.com/giantswarm/roadmap/issues/1624
 * [ ] Providers
   * [ ] CAPO
   * [ ] CAPG
   * [ ] CAPA
   * [ ] CAPZ
   * [ ] CAPVCD
   * [ ] CAPV

We also need to make sure that the [gitops template repository](https://github.com/giantswarm/gitops-template) contains examples for all providers.

**Comment by teemow** [comment]
First docs are here: https://github.com/giantswarm/docs/pull/1291/files

**Comment by teemow** [comment]
More docs:

 * https://docs.giantswarm.io/ui-api/kubectl-gs/gitops/
 * https://github.com/giantswarm/gitops-template/tree/main/docs
 * https://docs.giantswarm.io/ui-api/kubectl-gs/template-cluster/

**Comment by teemow** [comment]
This is outdated: 
https://docs.giantswarm.io/advanced/gitops/

**Comment by teemow** [comment]
Next steps:
 * [ ] Explain kubectl gs template cluster for CAPA - @silenteh 
 * [ ] Make gitops commands work for CAPA - @mproffitt 
 * [ ] How to create a cluster with CAPA - Incl. the transition from adhoc cluster creation (kuibectl gs template cluster) to gitops managed clusters (kubectl gs gitops add workload-cluster) - @carillan81

**Comment by marians** [comment]
Please also consider whether https://docs.giantswarm.io/ui-api/kubectl-gs/template-nodepool/ can/must be updated for CAPA. In my opinion it should be, as a cluster without node pool isn't much help.

**Comment by teemow** [comment]
@pipo02mix your CAPI docs are much more than just CAPI! Thanks for such a big chunk of documentation. This is important documentation that should not be "hidden" under Architecture / Cluster API. Also many other pages need updates to not have contradicting and old information in our docs.

Imo we could split this doc into this (with a bit of extension and updating of the other pages):

 * General
   * Overview
 * Architecture
   * Overview
   * Cluster API
 * Management Clusters
   * Authentication
   * Observability
   * Security
   * CI/CD

**Comment by teemow** [comment]
@pipo02mix how would we best sort out this content? Does it make sense to just go over it together and push it through? Happy to pair with you.

**Comment by teemow** [comment]
@carillan81 I don't have access to the hack.md file

**Comment by teemow** [comment]
@carillan81 nice! Looks good to me. Maybe you can add a section at the end with 'describe cluster' to show how you can see the status/events of the cluster.

**Comment by pipo02mix** [comment]
> @pipo02mix how would we best sort out this content? Does it make sense to just go over it together and push it through? Happy to pair with you.

yeah that would help. I will program it for when you are back

**Comment by muemich** [comment]
@pipo02mix is this done? What is missing?

**Comment by pipo02mix** [comment]
yeah we can close this one. The structural change is something is happening as part of the sig docs action we are working on

**Comment by teemow** [comment]
@carillan81 is still working on the gitops guide.

**Comment by teemow** [comment]
Related issue: https://github.com/giantswarm/roadmap/issues/1624

**Comment by teemow** [comment]
I think we can close this one and just use the new epic: https://github.com/giantswarm/roadmap/issues/1624
