### ISSUE TITLE
Add support for cluster resources namespaced by organization 

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#148]
Towards #90 Migrate GS API to Kubernetes API 

## User Story

- _As a Giant Swarm engineer, I want to be able to move cluster resources into namespaces and use organization CR to allow access to those namespaces so that the basic access can be provided using RBAC._

## Tasks

- [x] Create `Organization` CRD in `apiextensions`
- [x] Create `organization-operator`
- [x] Update `opsctl ensure` to handle `Organization` CRD
- [x] Add `organization-operator` to `opsctl` app list
- [x] Make `organization-operator` reconcile Organization CRs
- [x] Make `rbac-operator` watch `org-` namespaces
- [x] Release `organization-operator`
- [x] Release `rbac-operator`
- [x] Ensure CRDs on all installations

## Details

Current organizations design is implemented as microservice without the context of the Kubernetes platform. It allows cluster-admin to restrict Giant Swarm API access based on user’s membership in the organization. As we are moving towards providing customers access to the Control Plane Kubernetes, new access design architecture is based on RBAC.

Therefore, organizations will be extended with Organization CRD. Organization CRs will be managed by new organization-operator. Organization CR can become a single point of truth for role-based access (RBAC) and cloud-provider credentials.

This will allow to move cluster/machinedeployment/appcatalog CRs into namespaces #103 and use organization CR to allow access to those namespaces.

## Specification
- https://intranet.giantswarm.io/docs/architecture-specs-adrs/specs/namespaced-crs/
