### ISSUE TITLE
Upgrades (more graceful, more flexible, less aggressive, more robust)

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#15]
User Story: 

- As a customer, I would like Giant Swarm to issue less aggressive upgrades so that it does not interrupt my SDLC. 
- As a customer, I would like Giant Swarm to offer more upgrade options to adapt to the idiosyncrasy of my applications. 

Testing Acceptance:

* GS upgrades are scheduled around:
  * my clusters schedule such as a pause
  * batch size of termination period can be configured (allowing single swap upgrade)
  * my SDLCs environment such as dev first, stage and production later
  * a code freeze (out of scope)
* GS upgrades are almost invisible 

We collected lots of feedback with the first version of our upgrades. We reached a state we can work with on all providers. Now we need to think about improvements to finally reach a state that allows us to activate them automatically.

The goal of this story is not to activate upgrades automatically. We would need to schedule them and we need to allow customers to influence this based on individual clusters (pause), based on environment (dev first, stage and production later), based on a freeze (pause everything). This is a separate story.

But this story here should bring upgrades into a state where they become almost invisible for our customers. 

Upgrades should be less aggressive:

## General

 * [ ] Lockdown a cluster for upgrades https://github.com/giantswarm/roadmap/issues/186
 * [ ] Using the node-operator for draining on all providers (implement this independent from the actual provider)
 * [ ] Determine node readiness correctly
 * [ ] Mark old nodes unschedulable so pods do not get moved twice (or tainted like `kubectl taint nodes node_name key=value:NoSchedule`)

## AWS

 * [ ] Ensure TCPN(s) stack are not updated till master(s) TCPN stack is in update complete (it is recommended practice in community and it will avoid problems when master stack fails and leave the cluster in an inconsistent state)
 * [ ] Be able to select batch size (slow - 10%, regular - 33%, fast - 50%, single swap - 100% nodes) https://github.com/giantswarm/roadmap/issues/216
 * [ ] Time between node rolling https://github.com/giantswarm/roadmap/issues/217
 * [ ] Consider the possibility to disable `DisableRollback` option on Cloud Formation stack to avoid larger impact in big clusters 
 * [ ] Be able to pause an upgrade (it could be achieved by letting customer upgrade each node pool separately) 
 * [ ] [Dont trigger new batch upgrade till the last node batch runs fine](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#aws-properties-as-group--examples--Batch_Update_Policy_with_Wait_Condition)
  * [ ] Rollback option for GS version patches https://github.com/giantswarm/roadmap/issues/221

## Azure

 * [ ] Starting new nodes first 

Related issues:
 * https://github.com/giantswarm/giantswarm/issues/3160
 * https://github.com/giantswarm/giantswarm/issues/4324
 * https://github.com/giantswarm/giantswarm/issues/4186
* https://github.com/giantswarm/giantswarm/issues/4664

**Comment by sslavic** [comment]
When reviewing tenant cluster upgrade process, please take into consideration PMs and upgrade process related suggestions in them:
- https://github.com/giantswarm/giantswarm/issues/9705
- https://github.com/giantswarm/giantswarm/issues/9760 (also related closed PM and comment from Timo https://github.com/giantswarm/giantswarm/issues/4880#issuecomment-447850799 )

**Comment by pipo02mix** [comment]
I added some points in the main description after the experience we had with customers and some feedback on how it would help the to upgrade

**Comment by pipo02mix** [comment]
From Marcel's comment "We should IMO check what kubernetes sig multicluster is doing in the area. They are at least thinking/implementing cluster grouping and unique cluster IDs currently. See https://github.com/kubernetes/enhancements/tree/master/keps/sig-multicluster"

**Comment by pipo02mix** [comment]
This is handled now by Team Celestial as part of CAPI migration. We have created an [RFC](https://github.com/giantswarm/rfc/pull/17/files?short_path=f178d70#diff-f178d708b2485064934b4f154794509caf8082fdf536a2154751920a2979bf5e) proposal.

**Comment by teemow** [comment]
@giantswarm/team-celestial I'll close this one. Reopen if you need it.
