### ISSUE TITLE
`kubectl gs get nodepools` should support all CAPI providers

### ISSUE THREAD

**Issue by vvondruska** [giantswarm/roadmap#1519]
## User story

- _As a user, I want to find out which node pools exist in a workload cluster, via the CLI._
- _As a user, I want to fetch details about a specific node pool, via the CLI._

## Details

We want the [`kuebctl gs get nodepools`](https://docs.giantswarm.io/ui-api/kubectl-gs/get-nodepools/) command to work with all the CAPI providers Giant Swarm supports.

The syntax is provider-independent:

```nohighlight
kubectl gs get nodepools --cluster-name c68pn [FLAGS]
```

The implementation should detect which provider is used by the selected installation or workload cluster, and fetch the relevant resources (e. g. MachineDeployment, MachinePool).

## Tasks

- [x] Support `kubectl gs get nodepools` on Cluster API provider AWS (CAPA)
- [ ] Support `kubectl gs get nodepools` on Cluster API provider GCP (CAPG)
- [ ] #1523
- [x] #1555
- [x] Support `kubectl gs get nodepools` on Cluster API provider Azure (CAPZ)

As a product owner, please convert your line item into a provider-specific issue to track in your team.

**Comment by gawertm** [comment]
Hi @marians will take it over to our backlog then. Can you quickly explain whats it is used & needed for?

**Comment by marians** [comment]
It's the CLI command to

- list node pools
- get details on a particular node pool

Docs are here: https://docs.giantswarm.io/ui-api/kubectl-gs/get-nodepools/

In theory, this is possible via `kubectl get RESOURCENAME`, but detecting which is the right resource name (MachineDeployment, MachinePool, AzureMachineDeployment, ...) would be a burden on the user. In addition, our node pools usually consist of more than one resource.

The idea is that the provider specific implementation fetches the correct resources, regardless whether it is machine deployments or machine pools.

**Comment by nprokopic** [comment]
> The implementation should detect which provider is used by the selected installation or workload cluster, and fetch the relevant resources (e. g. MachineDeployment, MachinePool).

@Rotfuks I think this should be in our team now, as it's provider-independent (checking and fetching CAPI resources).

**Comment by Rotfuks** [comment]
Relevant discussion in slack around this isse: [https://gigantic.slack.com/archives/C01F7T2MNRL/p1705568597595229](https://gigantic.slack.com/archives/C01F7T2MNRL/p1705568597595229)

Guess you're right nikola! Makes sense to have a look at the kubectl gs plugin in turtles

**Comment by njuettner** [comment]
- [ ] Support EKS

**Comment by vxav** [comment]
FYI The issue in the description appears as completed but it was closed because superseded by another one
https://github.com/giantswarm/roadmap/issues/1554
