### ISSUE TITLE
MVP: App Configurations Overview in CLI

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#152]
Towards https://github.com/giantswarm/giantswarm/issues/10925

## User Story

**As an App Developer**,
**I want to** easily see customers’ deprecated configuration options,
**so I can** take appropriate action (either warn customer or migrate for customers) before doing an app upgrade that includes config changes.

aka `kubectl gs validate apps`

## Tasks

- [x] Investigate Open API or other tool to see if it satisfied our three criteria (validation, defaulting, "properties metadata") https://github.com/giantswarm/roadmap/issues/155
- [x] Sync to discuss findings
- [x] Write a spec: https://github.com/giantswarm/giantswarm/blob/d3cad9cb965317d3ff9d02200dca3b4bfba3b58b/content/docs/architecture-specs-adrs/specs/kubectl-gs/validate-apps.md
- [x] Get feedback on spec
- [x] Make changes and merge the spec
- [x] Add command to kubectl gs (https://github.com/giantswarm/kubectl-gs/pull/196)
  - [x] Usage instructions
  - [x] Core logic grabs all the apps, and supporting info (catalog crs and schema files) based on the matched namespace or selectors
      - [x] By namespace. (-n / --namespace)
      - [x] All Namespaces (-A / --all-namespaces)
      - [x] ~By field-selector (--field-selector)~ Implemented label-selector instead, field-selector doesn't give us much to work with in CRDs.
  - [x] Report mode (-o)
  - [x] Allow supplying your own schema file (--values-schema-file=values.schema.json)

- [x] Add values.schema.json to some commonly used apps
  - [x] nginx
  - [x] Hello world app
  - [x] others?
- [x] Figure out what to do about the label selector and the fact that actually no App CR's will have the `app` label set by default.

## Notes
* Discussion on outcomes w @oponder [Outcomes] (https://docs.google.com/document/d/1_KpFRIf3HcjAhSyUBs5nGv_ZlPQu8Dj2Z16yom8-gnc/edit) Mon, 19. Oct 2020
* In future stories, it would also serve as a place to show information about (1) configuration deprecations, (2) possible migrations, and (3) possible dangerous app configurations
* ​​The ideal would be that we design a solution that makes easy to also implement something in the Web UI, but starts with the CLI.

**Comment by cokiengchiara** [comment]
@giantswarm/team-batman  I moved this as candidate for next cycle.

**Comment by cokiengchiara** [comment]
@oponder @piontec , @rossf7 said using admission controller should be one of the options https://github.com/giantswarm/giantswarm/issues/11656

**Comment by oponder** [comment]
I think the admission controller (or validating/defaulting serverside) is something for a follow up story, this one is just about getting that overview of configuration and being able to mark things as deprecated.

**Comment by rossf7** [comment]
> I think the admission controller (or validating/defaulting serverside) is something for a follow up story, this one is just about getting that overview of configuration and being able to mark things as deprecated.

Agree an admission controller is not needed for this. 👍

**Comment by cokiengchiara** [comment]
@oponder will share spec on Wednesday, Jul 29.

**Comment by cokiengchiara** [comment]
@oponder , would it help if you update the "tasks" in the main body of the issue with the main things already done and still to do? we could have a call if it will help :)

**Comment by oponder** [comment]
@cokiengchiara yup! breaking it down and finding those next steps is always helpful. I was going off the spec as my guide, but sharing the actual progress in todo list form makes sense. Updated the original post.

**Comment by cokiengchiara** [comment]
> [ ] Add values.schema.json to some commonly used apps

@piontec is this what we discussed w @giantswarm/team-halo yesterday? If yes, then EFK is a good candidate because that's Halo's current cycle focus, right?

**Comment by piontec** [comment]
Yes, exactly. I pinged Oli in https://github.com/giantswarm/giantswarm/issues/13706

**Comment by cokiengchiara** [comment]
Good progress, still needs some work. @oponder is fixing.

**Comment by oponder** [comment]
Just discovered that apps do not get their `app` label set automatically. I was taking that for granted because it was something that pre-installed apps got set from cluster-operator.

I discussed with @rossf7 here about potentially having this label set by the `app-admission-controller`: https://gigantic.slack.com/archives/C76JX6YLQ/p1603892935053400

However, this won't add the labels retroactively to existing App CRs. 

That means we'll need some migration or script we can run sets this label for existing App CR's.

**Comment by cokiengchiara** [comment]
@oponder I know this is almost done... Can you write down what's absolutely critical to do still, in order to call this done soon? :)

**Comment by cokiengchiara** [comment]
@oponder I think the core functionality for this is done, right? We can create follow up issues for improvements. Close this one?

**Comment by oponder** [comment]
Yes! 🎉

**Comment by cokiengchiara** [comment]
Nice. Can you link me existing docs and issue for creating docs (if any)?

**Comment by cokiengchiara** [comment]
**Communication**

* Communicate that we're doing these schemas -- so that your values will be validated, and might be the reason an app doesn't install
* news post

**Documentation**
* Needs to be written
