### ISSUE TITLE
`kubectl gs template cluster` should support setting the service priority label on all CAPI providers

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1574]
## User story

- _As a cluster admin, I want to indicate the service priority of a workload cluster when generating it via the `kubectl gs template cluster` command._

## Details

Giant Swarm encourages customers to assign a [service priority label](https://docs.giantswarm.io/advanced/labelling-workload-clusters/#service-priority) to all workload clusters, to help determine the relative importance of a cluster.

The [`kubectl gs template cluster`](https://docs.giantswarm.io/ui-api/kubectl-gs/template-cluster/) command offers two ways to add this label:

1. The `--service-priority` flag, which can be used once only with the command.
2. The `--label` flag, which can be used several times in order to set arbitrary flags.

### Examples:

```bash
# Using method 1
$ kubectl gs template cluster ... --service-priority lowest

# Using method 2
$ kubectl gs template cluster ... --label "giantswarm.io/service-priority=lowest"
```

## Tasks

- [ ] `kubectl gs template cluster` should support setting the service priority label on CAPA
- [ ] `kubectl gs template cluster` should support setting the service priority label on CAPG
- [ ] `kubectl gs template cluster` should support setting the service priority label on CAPO
- [ ] `kubectl gs template cluster` should support setting the service priority label on CAPV
- [ ] `kubectl gs template cluster` should support setting the service priority label on CAPVCD
- [ ] `kubectl gs template cluster` should support setting the service priority label on CAPZ

As a product owner, please convert your line item into a provider-specific issue to track in your team.

**Comment by marians** [comment]
With Cloud Director we have a reference for the schema to be used. The values attribute should be

```nohighlight
servicePriority
```

Source: https://github.com/giantswarm/cluster-cloud-director/blob/41bedf1e3792e27288d3e4ee2e38be8e85c534b8/helm/cluster-cloud-director/values.yaml#L5

As of now, none of the other provider's cluster apps implements this.
