### ISSUE TITLE
Changes and releases in docs should aggregate all CAPI provider cluster apps

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1579]
## User story

- _As a cluster admin, I want to follow the changes between cluster app releases, via the docs [changes and releases](page)._

## Details

The changelog items for the `cluster-PROVIDER` and `defaults-apps-PROVIDER` apps should appear in the [changes and releases] section in docs.

### Category naming

We should decide which new categorie(s) to create for this purpose.

![image](https://user-images.githubusercontent.com/273727/198255688-3531a543-a852-4115-ad98-87ad1ab6d38a.png)

Suggestions:

- `Cluster apps`
- `Cluster and default apps`

The mapping from repositories to aggregation category/categories is done in the [config file](https://github.com/giantswarm/docs/blob/main/scripts/aggregate-changelogs/config.yaml).

## Tasks

- [ ] Changes and releases in docs should aggregate CAPA
- [ ] Changes and releases in docs should aggregate CAPG
- [ ] Changes and releases in docs should aggregate CAPO
- [ ] Changes and releases in docs should aggregate CAPV
- [ ] Changes and releases in docs should aggregate CAPVCD
- [ ] Changes and releases in docs should aggregate CAPZ

As a product owner, please convert your line item into a provider-specific issue to track in your team.

**Comment by marians** [comment]
The repo https://github.com/giantswarm/cluster-shared, which is shared among providers, also provides significant information on changes in release notes. I wonder how we could best include this one. It would require another category which is not provider specific.

Suggestions:

- `Cluster apps`
