### ISSUE TITLE
`cluster-cleaner` for CAPI test MCs

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#1598]
## Task

Update `cluster-cleaner` to work for CAPI clusters.

Note: Need to make sure its updated to NOT delete the MCs own cluster app. ⚠ 

TODOs:
- [x] Update `cluster-cleaner` to work for CAPI clusters. It needs to lookup the cluster App CRs: cluster-${provider} & default-apps-${provider};
- [x] Deploy `cluster-cleaner` to:
  - [x] `golem`
  - [x] `goat`
- [x] Ensure the MC is not removed

## Links
- [cluster-cleaner](https://github.com/giantswarm/cluster-cleaner).

**Comment by fiunchinho** [comment]
As it currently stands, it won't work. [The `cluster-cleaner` tries to filter apps labeled with the cluster label](https://github.com/giantswarm/cluster-cleaner/blob/main/controllers/cluster_controller.go#L120) but that label is not present on CAPI clusters by design, due to some logic in cluster-apps-operator.

**Comment by alex-dabija** [comment]
We agreed today to update and deploy the `cluster-cleaner` to our CAPA & CAPG MCs.

**Comment by alex-dabija** [comment]
I removed the CAPG installations.

**Comment by tuladhar** [comment]
NOTE: `thor` will be decommissioned.

**Comment by T-Kukawka** [comment]
@tuladhar should we do a handover to Phoenix?

**Comment by tuladhar** [comment]
@T-Kukawka Yes, we can do that. Jose will be peering on this, so would love to get this to finish line along with Phoenix.
