### ISSUE TITLE
Fix Quay being a single point of failure

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#164]
## User story

 - _As a GS customer I want to be able to scale/reschedule clusters when the remote registry (quay) is down so that I can operate normally and not be affected by outages._

## Details, Background

Main issue is that quay is currently a single point of failure. Although we feel like the current outages are a limited incident, we need to reorganise our image distribution to handle this better in the future.

After evaluating multiple solutions we've decided to use [ACR](https://azure.microsoft.com/en-us/services/container-registry/) as a private registry and configure the mirror to it. Since there is no ACR in China region and no other good alternative, we won't provide a mirroring solution on China installations.

### Milestone 1 - Enable scaling an AWS cluster while Quay is down

- [x] Verify that we can use Quay as a mirror for dockerhub
- [x] Verify that we can use Aliyun as a mirror for dockerhub
- [x] Move all `rkt` units to use Docker
- [x] Workout a way to disable a Quay to test cluster scaling
- [x] Make all the images for node bootstrap available in dockerhub (move them manually) 
- [x] Set registry mirrors to use Quay
- [x] Move pause out of gcr.io
- [x] Set short-form names for node bootstrap images 

### Milestone 1. Plan Update
- [x] Setup private registry
- [x] Sync images to a private registry
- [x] Release all images used in operators
- [x] Support short and long images names
- [x] Configure the mirror for the registry
- [x] Test cluster scaling with Dockerhub disabled
- [x] Make a release 

### Milestone 2. Synchronize images for node bootstrap on other providers ( KVM, Azure)

- [x] Replace `docker pull` for checking image existence 
- [x] Add support for synchronising images between registries
- [x] Add support for CRsync to expose metrics 
- [x] Alert if we are missing an image in a registry
- [x] Add registry mirror support for `azure` tenant clusters 
- [x] Add registry mirror support for `kvm` tenant clusters 
- [x] Provision giantswarm-acr on merge to master 
- [x] Build CI/CD pipeline for getting CRsync deployed
- [x] Find out how registry mirrors work with multiple pull secrets 
- [x] Build a dashboard for image sync between registries 

### Milestone 3. Go back to using registry settings set in installations

- [x] Provide dockerhub images for private repositories
- [ ] Support setting registry mirrors in installations
- [ ] Switch EU/US test installations to use dockerhub and mirrors configured in installations repo
- [ ] Remove fixed registry domains from provider operators helm templates

### Out of scope 
- Support for China
- add registry mirror support for control planes
- move control plane applications to use registry mirrors
- remove quay, use dockerhub as a source of truth

**Comment by snizhana-dynnyk** [comment]
@brinker211 @pipo02mix this is a new roadmap issue for the registry, we are on it. 
Will post updates here.

**Comment by snizhana-dynnyk** [comment]
The feature has been released for all providers except aws China - **AWS** -  `11.5.0`, **Azure** -  `12.0.0`,  **KVM** - `12.1.0`.

There are few cleanup tasks left in Milestone 3.
