### ISSUE TITLE
Introduce hardened Flatcar Images for CAPZ

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1659]
### Motivation
Currently we use Ubuntu images for our cluster nodes. But those are not specially hardened and thus not really secure. We have a more secure alternative with the hardened flatcar images. We therefor need to replace the ubuntu images with flatcar ones.

### Todo

* [x] Test creation of WC Flatcar using reference images
  * Ignition
    * [x] Validate Generated Ignition Template
    * [x] Review ignition boot logs 
  * Validate created nodes
    * [x] Check `kubeadm.service` and `kubeadm.sh` generated files
    * [x] Disk Setup
    * [x] Users
    * [x] NTP Settings - Uses flatcar ntp servers , Azure does not expose ntp servers
    * [x] Kube Reservation Script 
    * [x] prepeare-var-lib-kubelet-dir
    * [x] Check node for any failed units  
    * [x] Check /etc/kubeadm.yaml hostname replacement
    * [x] ssh through bastion
    * [x] Check cilium 
  * [x] cgroup version 2 on system
  * [x] cgroup version 2 on k8s
  * [x] App and Charts deployed successfully
* [x] Test rolling restart / upgrade of cluster 
* [x] Setup build of our own images - https://github.com/giantswarm/capi-image-builder
  * [x] Check what `customization` to base flatcar does upstream apply
  * [x] Gallery ? We should still have the Gallery we created a while ago while looking into building Ubuntu Images
  * [x] Is there any of the `Licencing issues` we saw with Ubuntu to handle ?
  * [x] Image replication to all regions ?
* [x] Define `Hardened` 
  * [x] API Audit Logs check - https://github.com/giantswarm/k8scloudconfig/blob/master/files/policies/audit-policy.yaml
  * [x] audit.d config
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/pkg/template/master_template.go#LL784C14-L784C33
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/99-default.rules
    * [x] docker / containerd
  * [x] Review `vintage os-hardening.service` - https://github.com/giantswarm/k8scloudconfig/blob/master/pkg/template/master_template.go#L69 https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/hardening.conf
  * [x] Replicate all settings that make sense for capi from https://github.com/giantswarm/k8scloudconfig
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/containerd-config.toml
    * [x]  https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/setup-apiserver-environment
      * We run with both SYSTEM and KUBELET reserved in vintage and also have a dedicated slice 
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/sshd_config
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/files/conf/etcd-alias
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/files/config/kubelet-master.yaml.tmpl
    * [x] https://github.com/giantswarm/k8scloudconfig/blob/master/files/config/kubelet-worker.yaml.tmpl
* [x] Define what the `Update schedule` for flatcar images should be ( i am _quite sure_ on ubuntu we are getting auto security updates at the moment ) 
* [x] Review cluster-azure template
  * [x] Do we want to be able to specify image settings on a per NodePool basis with default values ?  
* [x] Use Flatcar for Bastion node ( Capa does already )
* [ ] Test Converting running cluster from ubuntu to flatcar ( i don't think we want to support both with a flag )   
* [x] Build Clusters with our images
* [x] Create Follow Up Issues
  * [x] Issues on flatcar ignition when defining mounts and disks currently need workaround - https://github.com/kubernetes-sigs/cluster-api/issues/7679
  * [x] Cilium Connectivity Tests - https://github.com/giantswarm/roadmap/issues/1659#issuecomment-1438188450 
  * [x] On the Azure Console `serial console` we get automatically logged in `fctest1-control-plane-e95df458-786z4 login: core (automatic login)` 
  * [x] Vintage runs an `etcd3-defrag service` - https://github.com/giantswarm/k8scloudconfig/blob/master/pkg/template/master_template.go#L250
  * [x] Vintage has `bigger reservations for kube-reserved and system-reserved` and `dedicated slices` ( but no enforcement ) 
  * [x] audit-rules.service reports one error on one rule i cna't identify
  * [x] Support OVERWRITE for capz images
    * might need to create images with a temporary version and rename and delete 

### Open Upstream Issues

* https://github.com/kubernetes-sigs/cluster-api/issues/8242
* https://github.com/kubernetes-sigs/cluster-api/issues/7679

### Outcome
- We have systems that are a lot more secure through hardened base images for the nodes. 

### Technical Hint
- There is an upstream Issue for it: https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/629
- https://github.com/giantswarm/roadmap/issues/778
- https://github.com/giantswarm/roadmap/issues/1264
- https://github.com/giantswarm/roadmap/issues/1256
- https://github.com/giantswarm/cluster-openstack/blob/main/helm/cluster-openstack/templates/_helpers.tpl - cluster-openstack was actually using flatcar already ?

**Comment by Rotfuks** [comment]
Dependent on https://github.com/giantswarm/giantswarm/issues/24566

**Comment by primeroz** [comment]
something to keep an eye on https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/2890 is adding a template for using flatcar on capz

**Comment by Rotfuks** [comment]
Flatcar now officially in the docs: https://capz.sigs.k8s.io/topics/flatcar.html

**Comment by primeroz** [comment]
> Flatcar now officially in the docs: https://capz.sigs.k8s.io/topics/flatcar.html

I am getting a 404 here now :shrug: :)

**Comment by primeroz** [comment]
## TODO

* [ ] Test creation using reference images
  * Validate created nodes
    * [ ] Check `kubeadm.service` and `kubeadm.sh` generated files
    * [ ] Disk Setup
    * [ ] Users
    * [ ] NTP Settings
    * [ ] Kube Reservation Script 
  * Image replication to all regions ?
* [ ] Setup build of our own images
  * We should still have the Gallery we created a while ago while looking into building Ubuntu Images
  * Is there any of the `Licencing issues` we saw with Ubuntu to handle ?
* [ ] Define `Hardened`

**Comment by primeroz** [comment]
First test at least nodes joined :+1: 
```
NAME                                                                             READY  SEVERITY  REASON  SINCE  MESSAGE                              
Cluster/fctest1                                                                  True                     6m25s                                                                                                    
├─ClusterInfrastructure - AzureCluster/fctest1                                   True                     8m53s                                                           
├─ControlPlane - KubeadmControlPlane/fctest1                                     True                     6m25s                                                                                    
│ └─Machine/fctest1-zzrhf                                                        True                     6m26s                                                                                    
│   ├─BootstrapConfig - KubeadmConfig/fctest1-jnd99                              True                     8m49s                                                                                    
│   └─MachineInfrastructure - AzureMachine/fctest1-control-plane-c17c01d5-zzxbh  True                     6m26s                                                                                                    
└─Workers                                                                                                                                                                                          
  ├─MachineDeployment/fctest1-bastion                                            True                     10m                                                                                      
  │ └─Machine/fctest1-bastion-868b7dcb67-tz7rc                                   True                     4s                                                                                                       
  │   ├─BootstrapConfig - KubeadmConfig/fctest1-bastion-973fd873-fkttq           True                     6m22s                                                                                                    
  │   └─MachineInfrastructure - AzureMachine/fctest1-bastion-836b66f0-hf7kl      True                     4s                                                                                                       
  └─MachineDeployment/fctest1-md00                                               True                     19s                                                                                                      
    ├─Machine/fctest1-md00-77c9d6f645-68l7m                                      True                     114s                                                                                                     
    │ ├─BootstrapConfig - KubeadmConfig/fctest1-md00-ad5e9669-qlxdd              True                     6m22s                                                                                                    
    │ └─MachineInfrastructure - AzureMachine/fctest1-md00-bcb876fb-l69vx         True                     114s                                                                                                     
    ├─Machine/fctest1-md00-77c9d6f645-8pn6k                                      True                     4m12s                                                                                                    
    │ ├─BootstrapConfig - KubeadmConfig/fctest1-md00-ad5e9669-v6m92              True                     6m21s                                                                                                    
    │ └─MachineInfrastructure - AzureMachine/fctest1-md00-bcb876fb-r2fc9         True                     4m12s                                                                                                    
    └─Machine/fctest1-md00-77c9d6f645-dcdlx                                      True                     3m25s                                                                                                    
      ├─BootstrapConfig - KubeadmConfig/fctest1-md00-ad5e9669-4jbmz              True                     6m21s                                                                                                    
      └─MachineInfrastructure - AzureMachine/fctest1-md00-bcb876fb-xlm6q         True                     3m25s                                                                                                    
                                                                                                                    
```

```
NAME                                   STATUS   ROLES           AGE     VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                             KERNEL-VERSION      CONTAINER-RUNTIME
fctest1-control-plane-c17c01d5-zzxbh   Ready    control-plane   7m19s   v1.24.9   10.0.0.4      <none>        Ubuntu 20.04.5 LTS                                   5.15.0-1029-azure   containerd://1.6.2
fctest1-md00-bcb876fb-l69vx            Ready    <none>          2m46s   v1.24.9   10.0.16.4     <none>        Flatcar Container Linux by Kinvolk 3374.2.1 (Oklo)   5.15.77-flatcar     containerd://1.6.14
fctest1-md00-bcb876fb-r2fc9            Ready    <none>          4m59s   v1.24.9   10.0.16.6     <none>        Flatcar Container Linux by Kinvolk 3374.2.1 (Oklo)   5.15.77-flatcar     containerd://1.6.14
fctest1-md00-bcb876fb-xlm6q            Ready    <none>          4m29s   v1.24.9   10.0.16.5     <none>        Flatcar Container Linux by Kinvolk 3374.2.1 (Oklo)   5.15.77-flatcar     containerd://1.6.14

```

**Comment by primeroz** [comment]
### Machine Review

* the `Hostname` placeholder for the `joinConfiguration` could be similar to openstack, but it works with the template 
* `WARNING  : files: createResultFile: Ignition has already run on this system. Unexpected behavior may occur. Ignition is not designed to run more than once per system.` cleanup of image-builder not complete ? 
* this flatcar version is supposed to have `containerd 1.6.8` according to flatcar release notes ... but it seems we are running `1.6.14` - image-builder upgrading this ?

**Comment by primeroz** [comment]
License for flatcar is `Apache License 2.0` which , to my understanding, let us free to modify and redistribute the images as long as 

* we don't change the license
* we keep reference of attributoin to Flatcar project

**Comment by primeroz** [comment]
Cilium looks ok but 4 tests are failing from the `connectivty test suite` 

```
📋 Test Report
❌ 4/29 tests failed (6/230 actions), 2 tests skipped, 1 scenarios skipped:
Test [to-entities-world]:
  ❌ to-entities-world/pod-to-world/http-to-one-one-one-one-0: cilium-test/client-755fb678bd-4r6pg (192.168.2.121) -> one-one-one-one-http (one.one.one.one:80)
  ❌ to-entities-world/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-5b97d7bc66-nxl76 (192.168.2.210) -> one-one-one-one-http (one.one.one.one:80)
Test [client-egress-l7]:
  ❌ client-egress-l7/pod-to-world/http-to-one-one-one-one-0: cilium-test/client2-5b97d7bc66-nxl76 (192.168.2.210) -> one-one-one-one-http (one.one.one.one:80)
Test [client-egress-l7-named-port]:
  ❌ client-egress-l7-named-port/pod-to-world/http-to-one-one-one-one-0: cilium-test/client2-5b97d7bc66-nxl76 (192.168.2.210) -> one-one-one-one-http (one.one.one.one:80)
Test [to-fqdns]:
  ❌ to-fqdns/pod-to-world/http-to-one-one-one-one-0: cilium-test/client-755fb678bd-4r6pg (192.168.2.121) -> one-one-one-one-http (one.one.one.one:80)
  ❌ to-fqdns/pod-to-world/http-to-one-one-one-one-1: cilium-test/client2-5b97d7bc66-nxl76 (192.168.2.210) -> one-one-one-one-http (one.one.one.one:80)
connectivity test failed: 4 tests failed
```

**Comment by primeroz** [comment]
## Control Plane nodes review

* etcd disk did not get mounted on `/var/lib/etcddisk`

**Comment by primeroz** [comment]
To build images from the `flatcar` offer in azure i had to accept the following license

```
License: Flatcar Container Linux is a 100% open source product and licensed under the applicable licenses of its constituent components, as described here: https://kinvolk.io/legal/open-source/
Warranty: Kinvolk provides this software "as is", without warranty or support of any kind. Support subscriptions are available separately from Kinvolk - please contact us for information at https://www.kinvolk.io/contact-us
```

by running

* az vm image accept-terms --publisher kinvolk --offer flatcar-container-linux-free --plan stable-gen2 
* az vm image accept-terms --publisher kinvolk --offer flatcar-container-linux-free --plan stable

**Comment by primeroz** [comment]
Initial Image building pipeline is working using the `Compute Gallery` that we created before 

next steps in order for me to actually test those images

* Understand how to share the gallery publicly ( the current images are not available to be used in ghost subscription ) 
* Regions and replication, the gallery service is not global and azure recommends at least 2 regions with replication 
  * Update pipeline for this ?

**Comment by primeroz** [comment]
After lots of trial and error i think i got the right spec to use our images

```

```

BUT , since azure keeps a link between our build images and the parent flatcar one we are getting this error

```
capz-controller-manager-68c6664879-lmzfc manager I0227 15:45:36.440634       1 recorder.go:103] events "msg"="Warning"  "message"="failed to reconcile AzureMachine: failed to reconcile AzureMachine service virtualmachine: failed to create resource fctest1/fctest1-control-plane-cdd30d8e-lq5wk (service: virtualmachine): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code=\"ResourcePurchaseValidationFailed\" Message=\"User failed validation to purchase resources. Error message: 'You have not accepted the legal terms on this subscription: '6b1f6e4a-6d0e-4aa4-9a5a-fbaca65a23b3' for this plan. Before the subscription can be used, you need to accept the legal terms of the image. To read and accept legal terms, use the Azure CLI commands described at https://go.microsoft.com/fwlink/?linkid=2110637 or the PowerShell commands available at https://go.microsoft.com/fwlink/?linkid=862451. Alternatively, deploying via the Azure portal provides a UI experience for reading and accepting the legal terms. Offer details: publisher='kinvolk' offer = 'flatcar-container-linux-free', sku = 'stable-gen2', Correlation Id: '0b436d96-21c6-4e41-9ed9-daac49507cde'.'\"" "object"={"kind":"AzureMachine","namespace":"org-multi-project","name":"fctest1-control-plane-cdd30d8e-lq5wk","uid":"ae16afdd-7c1f-430d-89d1-37540c38f074","apiVersion":"infrastructure.cluster.x-k8s.io/v1beta1","resourceVersion":"6315646"} "reason"="ReconcileError"
```

I will accept the terms in `ghost` subscription but this means we will need every customer to also do that in every subscription where we want to use those images.

I can't explain how we are using the `flatcar4capi` images without having accepted the same  terms ... unless they were already accepted

**Comment by primeroz** [comment]
The fact that `only` latest is available from an image-definition is not true apparently

```
➜ kubectl get azuremachinetemplate fctest1-control-plane-9e46fb4a -o yaml | yq .spec.template.spec.image
computeGallery:
  gallery: gsCAPITest1-5cb24dcf-a2d0-4aba-820f-b52ca78f96e6
  name: capi-flatcar-stable-1.24.10-gen2
  version: 3374.2.3

➜ kubectl get azuremachinetemplate fctest1-md00-4e69b84e-2 -o yaml | yq .spec.template.spec.image       
computeGallery:
  gallery: gsCAPITest1-5cb24dcf-a2d0-4aba-820f-b52ca78f96e6
  name: capi-flatcar-stable-1.24.10-gen2
  version: latest
```
```
➜ kubectl --kubeconfig /dev/shm/fctest1.kubeconfig get node -o wide      
NAME                                   STATUS   ROLES           AGE     VERSION    INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                             KERNEL-VERSION    CONTAINER-RUNTIME
fctest1-control-plane-9e46fb4a-8zrtk   Ready    control-plane   14m     v1.24.10   10.0.0.4      <none>        Flatcar Container Linux by Kinvolk 3374.2.3 (Oklo)   5.15.86-flatcar   containerd://1.6.15
fctest1-md00-4e69b84e-2-68tt6          Ready    <none>          2m26s   v1.24.10   10.0.16.6     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.15
fctest1-md00-4e69b84e-2-j9g97          Ready    <none>          6m3s    v1.24.10   10.0.16.7     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.15
fctest1-md00-4e69b84e-zcg6l            Ready    <none>          10m     v1.24.10   10.0.16.5     <none>        Flatcar Container Linux by Kinvolk 3374.2.3 (Oklo)   5.15.86-flatcar   containerd://1.6.15

```

**Comment by Rotfuks** [comment]
We can use the following information for the legal statement in the Azure Image Gallery: 
```
Community gallery prefix: giantswarm-
Publisher support email: dev@giantswarm.io
Publisher URL: giantswarm.io
Legal agreement URL: https://www.giantswarm.io/privacy-policy
```

**Comment by primeroz** [comment]
since last upgrade i noticed something strange 

```
build-capz-image-1.24.11-6xb7532313faaf96cac2bcaa780286a09f-pod step-build-image ==> azure-arm.sig-{{user `build_name`}}: + [[ flatcar-gen2 != \f\l\a\t\c\a\r* ]]                                                                      
build-capz-image-1.24.11-6xb7532313faaf96cac2bcaa780286a09f-pod step-build-image ==> azure-arm.sig-{{user `build_name`}}: + sudo bash -c '/usr/share/oem/python/bin/python /usr/share/oem/bin/waagent -force -deprovision+user && sync'        
```

the name is `azure-arm.sig-{{user \`build_name\`}}` - why is build name not rendering ? is the actual `build_name` working in the rest of the ansible run ? 

```
. /home/imagebuilder/packer/azure/scripts/init-sig.sh flatcar-gen2 && packer build -var-file="/home/imagebuilder/packer/config/kubernetes.json"  -var-file="/home/imagebuilder/packer/config/cni.json"  -var-file="/home/imagebuilder/packer/config/containerd.json"  -var-file="/home/imagebuilder/packer/config/wasm-shims.json"  -var-file="/home/imagebuilder/packer/config/ansible-args.json"  -var-file="/home/imagebuilder/packer/config/goss-args.json"  -var-file="/home/imagebuilder/packer/config/common.json"  -var-file="/home/imagebuilder/packer/config/additional_components.json"  -color=true -var-file="/home/imagebuilder/packer/azure/azure-config.json" -var-file="/home/imagebuilder/packer/azure/azure-sig-gen2.json" -var-file="/home/imagebuilder/packer/azure/flatcar-gen2.json" -only="sig-flatcar-gen2" -var-file="/workspace/vars/vars.json"  packer/azure/packer.json

Executing Ansible: ansible-playbook -e packer_build_name="sig-flatcar-gen2"

```

**Comment by primeroz** [comment]
### Review of Hardening and other tuning

#### protect-kernel-defaults

* Currently not enabled on CAPZ ( CAPI ) kubelets
* values are already set to what's expected https://github.com/kubernetes-sigs/image-builder/blob/master/images/capi/ansible/roles/node/tasks/main.yml#L62 

Outcome: **Enable**

#####

**Comment by primeroz** [comment]
comparing containerd config.toml

* `oom_score = -999` - default is 0 , we don't set it on flatcar capz ( but i thought i saw it in the ansible code ? ) 
* # set containerd as a subreaper on linux when it is not running as PID 1 `subreaper = true` we don't set it and i can't see it in the docs 
* `[plugins."containerd.runtime.v1.linux"]` - we don't have it set in the capz config 
* `registry mirror and credentials` - we don't have it but can add as a snippet in `/etc/containerd/conf.d/*.toml` import

**Comment by primeroz** [comment]
#### Reservations

in vintage we do

**on master nodes**
```
kubeReserved:
  cpu: 350m
  memory: 1280Mi
  ephemeral-storage: 1024Mi
kubeReservedCgroup: /kubereserved.slice
protectKernelDefaults: true
systemReserved:
  cpu: 250m
  memory: 384Mi
systemReservedCgroup: /system.slice
```

**on worker nodes**
```
kubeReserved:
  cpu: 250m
  memory: 768Mi
  ephemeral-storage: 1024Mi
kubeReservedCgroup: /kubereserved.slice
protectKernelDefaults: true
systemReserved:
  cpu: 250m
  memory: 384Mi
systemReservedCgroup: /system.slice
```

on CAPZ we 
* calculate `kubeReserved` based on instance size
* we do not set dedicated slices
* we do not set any system reserved 
* we do not set the `protectKernelDefaults` 

I wlil

* Enable `protectKernelDefaults`

**Comment by primeroz** [comment]
Upgrading from `ubuntu` `0.13` to `flatcar` currently fails with

```
 reason: 'Upgrade "fctest2" failed: cannot patch "fctest2" with kind KubeadmControlPlane:
    admission webhook "validation.kubeadmcontrolplane.controlplane.cluster.x-k8s.io"
    denied the request: KubeadmControlPlane.controlplane.cluster.x-k8s.io "fctest2"
    is invalid: [spec.kubeadmConfigSpec.format: Forbidden: cannot be modified, spec.kubeadmConfigSpec.mounts:
    Forbidden: cannot be modified]'
```

**Comment by primeroz** [comment]
Chaing the `control-plane` name and object does not seem to work 

during rollout it gets stuck with

```
org-multi-project  ├─KubeadmControlPlane/fctest2                                False  Deleting                                             45m  
org-multi-project  │ ├─Machine/fctest2-95sxz                                    True                                                        41m  
org-multi-project  │ │ ├─AzureMachine/fctest2-control-plane-c17c01d5-gd6m4      True                                                        41m  
org-multi-project  │ │ └─KubeadmConfig/fctest2-7ps9h                            True                                                        41m  
org-multi-project  │ │   └─Secret/fctest2-7ps9h                                 -                                                           40m  
org-multi-project  │ ├─Machine/fctest2-d8xxd                                    True                                                        44m  
org-multi-project  │ │ ├─AzureMachine/fctest2-control-plane-c17c01d5-qxwn5      True                                                        44m  
org-multi-project  │ │ └─KubeadmConfig/fctest2-zz6vq                            True                                                        44m  
org-multi-project  │ │   └─Secret/fctest2-zz6vq                                 -                                                           44m  
org-multi-project  │ ├─Machine/fctest2-hlh7h                                    True                                                        38m  
org-multi-project  │ │ ├─AzureMachine/fctest2-control-plane-c17c01d5-brfwp      True                                                        38m  
org-multi-project  │ │ └─KubeadmConfig/fctest2-8dzwh                            True                                                        38m  
org-multi-project  │ │   └─Secret/fctest2-8dzwh                                 -                                                           38m  
org-multi-project  │ └─Secret/fctest2-kubeconfig                                -                                                           44m  
org-multi-project  ├─KubeadmControlPlane/fctest2-changed                        False  ScalingUp                                            8m10s
org-multi-project  │ ├─Secret/fctest2-ca                                        -                                                           44m  
org-multi-project  │ ├─Secret/fctest2-etcd                                      -                                                           44m  
org-multi-project  │ ├─Secret/fctest2-proxy                                     -                                                           44m  
org-multi-project  │ └─Secret/fctest2-sa                                        -                                                           44m  
```

```
Cluster/fctest2                                                                  False  Warning   ScalingUp  8m25s  Scaling up control plane to 3 replicas (actual 0)                         
├─ClusterInfrastructure - AzureCluster/fctest2                                   True                        44m                                                               
├─ControlPlane - KubeadmControlPlane/fctest2-changed                             False  Warning   ScalingUp  8m25s  Scaling up control plane to 3 replicas (actual 0)                      
│ ├─Machine/fctest2-95sxz                                                        True                        39m                                          
│ │ ├─BootstrapConfig - KubeadmConfig/fctest2-7ps9h                              True                        41m                         
│ │ └─MachineInfrastructure - AzureMachine/fctest2-control-plane-c17c01d5-gd6m4  True                        39m                                                             
│ ├─Machine/fctest2-d8xxd                                                        True                        42m                         


│ │ ├─BootstrapConfig - KubeadmConfig/fctest2-zz6vq                              True                        44m                         
│ │ └─MachineInfrastructure - AzureMachine/fctest2-control-plane-c17c01d5-qxwn5  True                        42m                                                                                   
│ └─Machine/fctest2-hlh7h                                                        True                        37m                                                                                                   
│   ├─BootstrapConfig - KubeadmConfig/fctest2-8dzwh                              True                        39m                                                         
│   └─MachineInfrastructure - AzureMachine/fctest2-control-plane-c17c01d5-brfwp  True                        37m       
```

I will reach out upstrema to see what they think since _most_ fields can be modified and i can't see why those 2 cannot ( https://github.com/kubernetes-sigs/cluster-api/blob/main/controlplane/kubeadm/api/v1beta1/kubeadm_control_plane_webhook.go#L137 )  but right now we cna't update the CP from ubuntu to flatcar

**Comment by primeroz** [comment]
glippy is now converted to flatcar

```
➜ k get node -o wide
NAME                                  STATUS   ROLES           AGE     VERSION    INTERNAL-IP    EXTERNAL-IP   OS-IMAGE                                             KERNEL-VERSION    CONTAINER-RUNTIME
glippy-control-plane-aae7f116-jqtcd   Ready    control-plane   23m     v1.24.11   10.223.0.132   <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-control-plane-aae7f116-vpk8s   Ready    control-plane   30m     v1.24.11   10.223.0.137   <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-control-plane-aae7f116-wclks   Ready    control-plane   16m     v1.24.11   10.223.0.133   <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-md00-e6ebd75a-9br9p            Ready    <none>          21m     v1.24.11   10.223.0.4     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-md00-e6ebd75a-fvjtj            Ready    <none>          31m     v1.24.11   10.223.0.10    <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-md00-e6ebd75a-lt6zc            Ready    <none>          15m     v1.24.11   10.223.0.7     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-md00-e6ebd75a-q28jz            Ready    <none>          4m37s   v1.24.11   10.223.0.8     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-md00-e6ebd75a-vbrzq            Ready    <none>          25m     v1.24.11   10.223.0.9     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
glippy-md00-e6ebd75a-xnnq7            Ready    <none>          9m22s   v1.24.11   10.223.0.6     <none>        Flatcar Container Linux by Kinvolk 3374.2.4 (Oklo)   5.15.89-flatcar   containerd://1.6.18
```

**Comment by primeroz** [comment]
this is now done
