### ISSUE TITLE
Automated workload cluster certificates rotation

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#166]
## User Story

As a customer, I want my clusters' certificates to be regularly rotated automatically to comply with security guidelines

As a SE within Giant Swarm, I want to have automated way of rotating customer certificates to free up my time for other responsibilities and so that it's not missed or forgotten which leads to expired certification situation that is more difficult to handle.

## Background

Currently, the Solution Engineer must monitor the certificates for his own customers (cf. #alert-customers channel) to see the clusters with certificates about to expire.

When a workload cluster is about to expire, the Solution Engineer of the customer must:

- Find a time slot to rotate certificates (depends on the customer can be at any time, at night, ...)
- Roll all the nodes one by one (manually or by using a script)
- For Azure, the Solution Engineer must also reimage the nodes manually

This process is time-consuming especially for large clusters and error-prone (it is easy to miss certs about to expire when we have a lot of them or it happens over the weekend) and it should be automated.

## To Do
- [ ] during cluster creation cert-operator creates intermediate CAs #167 
- [ ] get cert-manager onto the CP (skip if it's already there) #168 
- [ ] cert-manager handles the creation of the keys #169
    - [ ] create an issuer to create certificates
- [ ] getting CA key onto the master of the workload cluster #170
- [ ] edit k8scc #171
    - [ ] change kubelet flag to --rotate
    - [ ] change certificate to be bootstrap certificate
    - [ ] add flags on the controller manager
- [ ] update clients to use intermediate CAs #172
    - [ ] gsctl/Happa/API
    - [ ] operators using it
    - [ ] microservices (cluster service?...)
    - [ ] Prometheus config controller?
- [ ] use bootstrap token(temporary RBAC access) instead of bootstrap certificates #173
- [ ] Invalidate old service accounts (SPIKE needed) #174
    - [ ] handle transition period, might help: https://github.com/kubernetes/kubernetes/issues/91070#issuecomment-628709708
