### ISSUE TITLE
Test Apps on new CAPVCD Cluster

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#1707]
once the first installation is ready (https://github.com/giantswarm/roadmap/issues/1655):

# User Story
As a GS Admin, I want all the apps used by customers to be tested on the new Cluster API Provider CAPVCD, so that the customers wont experience issues once migrating their workloads

# Tasks

- [x] collect list of apps required by first customer. Use this as starting point for testing
- [x] verify with customer if thats the required apps or if more are there
- [ ] coordinate with Platform Teams to perform their App testing

# Tracking issues

```[tasklist]
### Platform Teams
- [ ] https://github.com/giantswarm/giantswarm/issues/25205
- [ ] https://github.com/giantswarm/giantswarm/issues/25219
```

**Comment by erkanerol** [comment]
This is what we have tested for CAPO before beta release. https://github.com/giantswarm/giantswarm/issues/21491

**Comment by vxav** [comment]
Asked customer what apps they will use here => https://gigantic.slack.com/archives/CE92C4BST/p1672823996783849

**Comment by gawertm** [comment]
have customer specific issues in here: https://github.com/giantswarm/telekom-panamax/issues/192
