### ISSUE TITLE
CAPA Multi-tenancy

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1708]
## Stories

_-As a cluster operator, I want to create clusters in different AWS accounts in order to provide clusters for systems running in different AWS accounts._

_-As a cluster operator, I want to create clusters in different AWS accounts in order to have strictly separate systems running in multiple environments: production, staging, testing, development, etc._

## Background

Giant Swarm CAPA clusters are created in the same account as the management cluster. CAPA does have support for multi-tenancy. More details are available in the [upstream documentation](https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html).

## TODOs

- [x] Evaluate current state of CAPA multi-tenancy;
- [x] Expose settings in `cluster-aws` to create clusters in a different account;
- [x] #1769
- [x] https://github.com/giantswarm/roadmap/issues/1801
- [x] https://github.com/giantswarm/roadmap/issues/2002

## Resources

- [CAPA multi-tenancy documentation](https://cluster-api-aws.sigs.k8s.io/topics/multitenancy.html).
