### ISSUE TITLE
Make changes in k8scc

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#171]
towards #166 

## Tasks
- [ ] change kubelet flag to --rotate
- [ ] change certificate to be bootstrap certificate
- [ ] add flags on the controller manager

**Comment by MarcelMue** [comment]
Do we think this is still necessary? If anything we will need this with CAPI and not k8scc. What do you think @giantswarm/team-ludacris ?

**Comment by MarcelMue** [comment]
I was under the assumption that `k8scc` will not be used in the future and we will use a different codebase for CAPI clusters.

Maybe I am wrong with this assumption, but let's not close here until we are certain :)
