### ISSUE TITLE
Merge SIG Product and Roadmap Board

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#1710]
* [x] change PM automation to roadmap board
 * [x] make sure that all meta topics are actually in the roadmap board (most probably easy to see from horizon board and old product board)
 * [x] change SIG Product meetings notes to not mention the old board anymore
 * [x] announce that we only use roadmap board going forward
 * [x] might be some places in intranet that need adjusting
 * [x] delete sig product board

**Comment by puja108** [comment]
closing as PR to change intranet is up
