### ISSUE TITLE
Update clients to use intermediate CAs 

### ISSUE THREAD

**Issue by MartaD** [giantswarm/roadmap#172]
Towards #166 

## Tasks
- [ ] gsctl/Happa/API
- [ ] operators using it
- [ ] microservices (cluster service?...)
- [ ] Prometheus config controller?
