### ISSUE TITLE
Investigate Azure Workload Identity

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1728]
### Motivation
Team Clippy discussed the options for Pod Identities when using CAPZ but we are not yet completely confident with what we know. Therefore we need to investigate a bit more on what's the best way for pod identification with capz.

### Todo
- Investigate what we have to do in order to get the best possible and most secure pod identity with capz
-- the document from the concept meeting in https://github.com/giantswarm/giantswarm/issues/24578#issuecomment-1333982649 might help you

### Outcome
- We are confident on how pod identity has to be done within capz.

**Comment by primeroz** [comment]
Following up from #1729 I don't think most of the core workloads supports using Azure Workload Identity yet 

* [ ] `azuredisk-csi-driver` : tested , not working - https://github.com/kubernetes-sigs/azuredisk-csi-driver/issues/1651
* [ ] `azure-cloud-controller`: 

---
ToDo 
* [ ] Investigate actual requirements for pods to use workload identity
  * from what i read https://learn.microsoft.com/en-us/azure/aks/workload-identity-overview#how-to-migrate-to-workload-identity as long as the code already supports the deprecated pod identity mode then it should work 
  * azuredisk csi driver instead _seems to only support the cloud-config mode_ https://github.com/kubernetes-sigs/azuredisk-csi-driver/blob/b69e47ae76c38ea7a7051a6ea17f4470006488e9/pkg/azureutils/azure_disk_utils.go#L149

**Comment by Rotfuks** [comment]
Would be also interesting to see what we have to do in upstream to push this topic further on the upstream side if necessary.

**Comment by primeroz** [comment]
## Summary

### About Current AAD Pod Identity App

* I could not find `anything using` the now deprecated AAD Pod Identity 
  * We install the app in the `giantswarm namespace` of every MC but no azureidentitybindings.aadpodidentity.k8s.io exists in any of them 
  * The only `non-giantswarm namespace` installation of the APP is in `gollum/5jka7` but there as well i could not find any bindings 
  * All the core app ( csi drivers, cloud controller, ... ) don't support it so that's fine 
  * `external-dns` consumes the VM Identity - https://github.com/giantswarm/external-dns-app/blob/master/helm/external-dns-app/templates/deployment.yaml#L67 
  * `dns-operator-azure` uses a clientId/ClientSecret  - https://github.com/giantswarm/dns-operator-azure/blob/main/helm/dns-operator-azure/templates/deployment.yaml#L45

### About Azure Workload Identity
* In this situation `moving to AWI` will be painless :) 
* For each cluster some _prep work_ is required , likely done by a custom operator 
  * OIDC Public Documents **must be published public** for Azure AD to query , this is implemented by [irsa-operator](https://github.com/giantswarm/irsa-operator) for CAPA / Vintage AWS - [docs](https://intranet.giantswarm.io/docs/dev-and-releng/irsa/)
  * Issuer set to the public URL of the oidc discovery document for the cluster and signing keys set to the secret generated - see [CAPA](https://github.com/giantswarm/cluster-aws/blob/master/helm/cluster-aws/templates/_helpers.tpl#L145) example and [capz](https://github.com/giantswarm/cluster-azure/pull/6/files#diff-89953cc6f68ecb2458c26ea9af45c03b11f68f3424c8379fff1d340dff126ccfR44)
  * `UA Identities` or `APP` for each Workload to authenticate needs to be created and configured with 
    * `federated credentials` connection between the `Identity` and the `k8s service account` to allow using it
    *  `Kubernetes Service Accounts` for the given workload will require an annotation with the `clientID` of the `Identity` ... which we will need to figure out how to inject into an APP ( or looked up at runtime using an helm hook ) 
  * `AWI mutating webhook` needs to be installed as an app
* Customer's workloads will be able to use the same functionality to grant cloud permissions to their workloads ... given the same requirements as above are fulfilled ( create Identity with right configuration and push info into SA annotation ) 

**Open Issues**
* With the current implementation of `AZWI` nothing blocks any pod from accessing the metadata endpoint and assume the identity of the Host is running on. 
  * The only solution i could come up with is 
    * Run a privileged VM Identity only on control plane nodes
    * Ensure all `privileged controllers` like `csi drivers` and `external cloud controller` runs on control plane nodes
    * Reduce permissions of worker nodes to the bare minimum ( only what is required by kubelet ) 
  * See  https://kubernetes.slack.com/archives/C5HJXTT9Q/p1670855471261069

**Comment by primeroz** [comment]
Added proposal to parent issue
