### ISSUE TITLE
Offering Managed External Secrets Operator (ESO)

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1749]
Objective: enable customers to deploy externally managed secrets into K8s MCs

Tentative implementation plan for ESO:

```[tasklist]
### Tasks
- [x] https://github.com/giantswarm/roadmap/issues/1767
- [ ] https://github.com/giantswarm/roadmap/issues/1768
- [ ] https://github.com/giantswarm/giantswarm/issues/25132
- [ ] https://github.com/giantswarm/roadmap/issues/1952
```
