### ISSUE TITLE
CAPZ VPN Investigation

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1751]
### Motivation
Usually within Giant Swarm we restrict access to Management Clusters through a Virtual Private Network configuration. This is a good security measure that will also be a relevant requirement for potential customers for capz. In order to implement it, we first should find out, what capi/capz already delivers upstream and what we have to do.

### Todo

- [ ] investigate what the default approach for capi cloud provider would be in GS to establish VPN connections
-- talk to team hydra for this
- [ ] investigate if there are any upstream features/recommendations around securing MC access through VPNs
- [ ] Investigate what we have to do in clippy in order to have the option to secure capz MCs through VPNs

### Outcome
- Clippy knows what to do in order to secure MC Access with VPNs in CAPZ and are confident to implement it in the next step.

**Comment by Rotfuks** [comment]
Output from Refinement
- This should be a general GS topic for CAPI, not just CAPZ
-- CAPA/CAPO still have no solution for this yet as well
- Have to specifically clearify with GS Architecture and Continental if this is a strong requirement we directly should implement.

**Comment by gawertm** [comment]
lets just close this one. its about finding the vpn solution. which is in place for onprem anyways and also we are going with teleport. CAPZ will be handled in teleport migrationa anyways
