### ISSUE TITLE
CAPZ Machine Pools

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1752]
### Motivation
As discussed in our Future CAPZ Opportunities Meeting, we see the machine pools, the abstraction to the cloud provider specific machines as the future of CAPI machine definition. As we expect this feature that is yet in alpha state to become the defacto standard over all CAPI providers we should change our machine deployments to machine pools to get more familiar with the concept 

### Todo

- [x] Change the machine deployments in our CAPZ Clusters to machine pools
- [x] Verify and test that everything still works as expected
- [x] check the `resourceGroup` name lower/upper case topic (xref: comment on [issue 24562](https://github.com/giantswarm/giantswarm/issues/24562#issuecomment-1327148343))

### Outcome
- Our capz clusters use a higher abstraction layer that sends more responsibility of machine management to the cloud providers and thus can be used as a standard across all GS capi provides.

**Comment by primeroz** [comment]
something to test out for on machinepools , kubeadm token freshness 

 https://github.com/giantswarm/roadmap/issues/1720#issuecomment-1342855971

**Comment by bavarianbidi** [comment]
as giantswarm/cluster-azure#6 got merged, we now have `machinePools` when creating new azure based workload clusters
