### ISSUE TITLE
[SPIKE] Private DNS resolver rules

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1758]
## Task

Investigate how the resolver rules for private DNS will be implemented. The customer provided an example script which shows the expected behavior of the operator.

## Questions

- What AWS resources need to be created by the operator?
- What's the AWS policy required by this feature?
- How can multiple people work on developing the operator?

## Outcome

- [ ] **list of task or user stories** in order to develop the operator incrementally to enable the team to work in parallel;
- [x] **list of AWS resources** which need to be created by the operator;
- [x] **the AWS policy** required by this feature.

No actual code is needed.

## Resources

- https://github.com/giantswarm/roadmap/issues/1709;
- [Example Terraform script with AWS resolver rules for private DNS](https://github.com/giantswarm/talanx/files/10121647/resolver-rule-terraform-stack.md).

**Comment by calvix** [comment]
```
# thunder VPC ID
vpc-0d35bc02d0fe39e9a

## thunder subnet IDs
subnet-00608029a8fdc4586
subnet-0687cbee901bdd73a
subnet-0bcea31b9854fc197

# thunder hosted zone ID
Z00105772URQM1433AZX9

# TODO
associate-resolver-rule

## EXECUTE
export CLUSTER=thunder
export NOC_AWS_ACCOUNT_ID=496192190985

# create Security group for the resolver endpoints
SECURITY_GROUP_ID=$(aws ec2 create-security-group --description "Security group for resolver rule endpoints" --group-name ${CLUSTER}-rr-endpoints2 --vpc-id vpc-0d35bc02d0fe39e9a | jq -r .GroupId)

# create ingress rule for the security group
aws ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol udp --port 53
aws ec2 authorize-security-group-ingress --group-id ${SECURITY_GROUP_ID} --protocol tcp --port 53

# create INBOUND resolver endpoint
RR_INBOUND_ID=$(aws route53resolver create-resolver-endpoint --name ${CLUSTER}-inbound --direction INBOUND --security-group-ids $SECURITY_GROUP_ID --ip-addresses SubnetId=subnet-00608029a8fdc4586 SubnetId=subnet-0687cbee901bdd73a SubnetId=subnet-0bcea31b9854fc197 --creator-request-id "$(date)" | jq -r .ResolverEndpoint.Id)

# create OUTBOUND resolver endpoint
RR_OUTBOUND_ID=$(aws route53resolver create-resolver-endpoint --name ${CLUSTER}-outbound --direction OUTBOUND --security-group-ids $SECURITY_GROUP_ID --ip-addresses SubnetId=subnet-00608029a8fdc4586 SubnetId=subnet-0687cbee901bdd73a SubnetId=subnet-0bcea31b9854fc197 --creator-request-id "$(date)" | jq -r .ResolverEndpoint.Id)

# get resolver rule inbound IPs,
RR_INBOUND_IP_ADDRESES=$(aws route53resolver list-resolver-endpoint-ip-addresses --resolver-endpoint-id ${RR_INBOUND_ID} | jq -r .IpAddresses[].Ip |awk '{print "Ip="$1}')

# create Resolver rule
RR_ID=$(aws route53resolver create-resolver-rule  --creator-request-id "$(date)" --name giantswarm-${CLUSTER} --rule-type FORWARD --domain-name ${CLUSTER}.eu-central-1.aws.tkp.hdi.cloud --resolver-endpoint-id ${RR_OUTBOUND_ID} --target-ips $RR_INBOUND_IP_ADDRESES | jq -r .ResolverRule.Id)

RR_ARN=${aws route53resolver get-resolver-rule --resolver-rule-id ${RR_ID} | jq -r .ResolverRule.Arn}

# create resource share item
# in aws go SDK this might be 3 separate operations - create RAM share resource, associate resolver rule ARN with the RAM share resource, associate AWS NOC account principal with the RAM share resource

aws ram create-resource-share --name giantswarm-${CLUSTER}-rr --resource-arns ${RR_ARN} --principals ${NOC_AWS_ACCOUNT_ID} --allow-external-principals


# asociate resolver rule with NOC VPC in the NOC account
# execute with NOC role indicated by other AWS profile - `thunder-noc`
# aws sts assume-role --role-session-name giantswarm-cli-test-vaclav --role-arn arn:aws:iam::496192190985:role/TKP_Assoc_Route53_ResolverRule --external-id SECRET_FILL
aws --profile thunder-noc route53resolver associate-resolver-rule --resolver-rule-id $RR_ID --name giantswarm-${CLUSTER}-rr-asociation --vpc-id vpc-0ffbf3d2258f96ba4

```

**Comment by fiunchinho** [comment]
I have an initial implementation here https://github.com/giantswarm/aws-resolver-rules-operator/pull/6

I have not tested it yet, only through automated testing. Also, the logic when a Cluster is deleted is not implemented yet. If no one picks it up in the next two weeks, I can resume my work when I'm back from holidays.

**Comment by alex-dabija** [comment]
Blocked until @fiunchinho is back.

**Comment by fiunchinho** [comment]
We continue here https://github.com/giantswarm/roadmap/issues/1709
