### ISSUE TITLE
Setup Usage of Kyverno App in CAPZ Clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1774]
### Motivation
In order to set policies and with that increase the security in our management clusters, we are using Kyverno throughout all providers in Giant Swarm. Team Shield already created Kyverno and Kyverno Policy Apps that in best case just need to be included to our app collection.

### Todo

- [ ] Introduce kyverno app to our capz app collection
- [ ] Introduce the kyverno policy apps to our capz app collection
-- we at least need the [kyverno-policies app](https://github.com/giantswarm/capa-app-collection/blob/master/flux-manifests/kyverno-policies.yaml), but could also need the other ones, depending on the touchpoints we already integrated.
- [ ] Verify that everything works as expected

### Technical
- We can checkout the kyverno policy apps in capas app collection: https://github.com/giantswarm/capa-app-collection/tree/master/flux-manifests

### Outcome
- We have policies in place that check requests to our Management Clusters against a set of policies increasing the safety and stability of our clusters.

**Comment by Rotfuks** [comment]
- This is in responsibility of team shield
- PodSecurity should be enough for us now as long as we use <1.25 of k8s

**Comment by primeroz** [comment]
I just noticed in the comments that this is `team-shield` responsability so i am putting this back into the backlog

**Comment by Rotfuks** [comment]
As discussed with Shield, we're responsible to introduce the kyverno and kyverno-policy apps into our app collection. They should work out of the box, but as soon as trouble arise, we can get in touch with them. 
Changed the scope of this ticket to Management Clusters only. In a more general direction regarding Kyverno Policies on Workload Clusters we will setup a meeting with Shield in the next weeks to get an update on the roadmap for this on shield side. 
So this ticket can be worked on in the above listed scope.

**Comment by primeroz** [comment]
:+1:

**Comment by primeroz** [comment]
looks to be working fine 

![Screenshot from 2023-02-08 16-18-56](https://user-images.githubusercontent.com/2085772/217571938-2a63cbfd-081b-4411-8eca-18374cbb1e18.png)


I will wait for the linked PR to be approved and merged before closing this
