### ISSUE TITLE
CAPA cluster upgrades stability

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1777]
## Story

_-As a cluster admin, I want CAPA cluster upgrades to be seamless in order to provide the a good user experience to my customers._

## Background

CAPA cluster upgrade have been an ongoing struggle.

## Current problems

- https://github.com/giantswarm/roadmap/issues/1720;
- Pods become unauthorized during rolling of control plane nodes;
- Control plane nodes have no health checks configured;
- Machine pools have no health checks configured;
- Proxy environment variables are not injected if Kyverno is down, but the pods still start;

## Tasks

- [x] https://github.com/giantswarm/roadmap/issues/1766;
- [x] https://github.com/giantswarm/roadmap/issues/1742;
- [x] https://github.com/giantswarm/roadmap/issues/1753;
- [x] https://github.com/giantswarm/roadmap/issues/1755;
- [x] https://github.com/giantswarm/roadmap/issues/1770;
- [x] https://github.com/giantswarm/roadmap/issues/1756;
- [x] https://github.com/giantswarm/roadmap/issues/1757;
- [x] https://github.com/giantswarm/roadmap/issues/1978;
- [x] https://github.com/giantswarm/roadmap/issues/1825;
- [x] https://github.com/giantswarm/giantswarm/issues/25159;
- [x] https://github.com/giantswarm/roadmap/issues/1827;
- [x] https://github.com/giantswarm/roadmap/issues/2170;
- [x] https://github.com/giantswarm/roadmap/issues/2217;
- [x] https://github.com/giantswarm/roadmap/issues/2111;
