### ISSUE TITLE
CAPA granular network

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1782]
## Story

_-As a cluster admin, I want to create a CAPA cluster with a granular network layout (separate subnets for the control plane nodes, worker nodes, Kubernetes API loadbalancer, ingress controller, bastion hosts), in order improve the security by configuring CIDR & subnet purpose based firewall rules on the transit gateway._

## Background

Some customers want their inter-VPC network traffic to be routed by a transit gateway in order to have control over which systems talk to each other.

## Tasks

- [x] https://github.com/giantswarm/roadmap/issues/491;
- [x] https://github.com/giantswarm/roadmap/issues/1532;
- [x] https://github.com/giantswarm/roadmap/issues/1535;
- [x] https://github.com/giantswarm/roadmap/issues/1784.
- [x] https://github.com/giantswarm/roadmap/issues/1533;
- [x] https://github.com/giantswarm/roadmap/issues/1534;
- [x] https://github.com/giantswarm/roadmap/issues/1838

**Comment by freudl** [comment]
It would be great to understand how existing assets are placed once there is more than one subnet per AZ.

Also, it would help to understand how we will exchange configuration of VPC internals, e.g. CIDRs and Tags.

**Comment by alex-dabija** [comment]
> It would be great to understand how existing assets are placed once there is more than one subnet per AZ.

We are currently investigating the implications of putting the machine pools and the control plane nodes on separate subnets. I'll let you know as soon as I have more information.

For the moment, I know that as soon as we have multiple subnets on per AZ we'll have to decide where the different types of machines / loadbalancers / VPC endpoints go.

> Also, it would help to understand how we will exchange configuration of VPC internals, e.g. CIDRs and Tags.

We are evaluating a few options and we have to draft PRs:
- https://github.com/giantswarm/cluster-aws/pull/195/files (look for helm/cluster-aws/values.yaml);
- https://github.com/giantswarm/cluster-aws/pull/196/files (look for helm/cluster-aws/values.yaml)).

The basic idea is to have a list of subnets with CIDRs and tags. The different sub-systems (control plane, machine pools, ingress LB, etc.) will use tag filters to lookup the subnets to use.

**Comment by alex-dabija** [comment]
There are a few aspects left to take care of:
- the API LB subnets need to be the first ones in the list because CAPA just picks the first subnet for a given AZ;
- CAPA overwrites the subnet names, which means that it doesn't let us set custom names. This is prevents us from starting the ingress on a specific subnet because all the subnets have the same name for a given AZ;
- the trasit gateway operarator needs to be updated in order to choose the correct subnet (currently, in progress).

**Comment by alex-dabija** [comment]
Tested with `thor` when it was recreated last week.
