### ISSUE TITLE
AWS vintage migration to CAPA implementation (Phase 1)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1787]
## Story

_-As a cluster admin for vintage AWS clusers, I want to migrate existing clusters to Cluster API for AWS (CAPA) in order to benefit from all the new features Giant Swarm is developing as part of Cluster API (CAPI)._

## Background

Giant Swarm is moving all it's product AWS development to Cluster API (CAPI) and it has a lot of Vintage clusters which need to be migrated.

```[tasklist]
## Scope
- [ ] https://github.com/giantswarm/roadmap/issues/2726
- [ ] https://github.com/giantswarm/giantswarm/issues/27910
- [ ] https://github.com/giantswarm/giantswarm/issues/28148
- [ ] [Features required to migrate first customer](https://github.com/giantswarm/giantswarm/issues/28652)
```

```[tasklist]
## Hard dependencies
- [ ] https://github.com/giantswarm/roadmap/issues/2925
- [ ] https://github.com/giantswarm/roadmap/issues/2862
- [ ] https://github.com/giantswarm/giantswarm/issues/28500
- [ ] https://github.com/giantswarm/roadmap/issues/3005
```

**Comment by puja108** [comment]
dupe of https://github.com/giantswarm/roadmap/issues/309 ?

**Comment by alex-dabija** [comment]
Yes, it's a duplicate of https://github.com/giantswarm/roadmap/issues/309, but I'll keep this one.

**Comment by alex-dabija** [comment]
We don't have much information at the moment on who we are going to approach the migration. We need to first talk about it in Phoenix and Hydra do decide on how to move forward.

We might need to also split the work:
- Customer Work for migration
- Technical Work for migration
