### ISSUE TITLE
Teleport for SSH & cluster access

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1796]
## Epic

Replace current SSH, VPN and cluster access with Teleport.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2463
- [x] Drop bastions from CAPA
- [x] Drop bastions from CAPZ
- [ ] Drop bastions from CAPV
- [ ] Drop bastions from CAPVCD
```
