### ISSUE TITLE
Make workload cluster k8s CIS compliant

### ISSUE THREAD

**Issue by jgsqware** [giantswarm/roadmap#18]
Priority: No customer asked for specific items in here, it is more a question of if we want to be CIS compliant.

Regarding last CIS benchmark report on our latest version of Guest cluster (4.2.0), here is the currently open points:

## Part Of RoadMap item

- [ ] [Enable Kubelet-ApiServer authz/authn, with specific node certificates](https://github.com/giantswarm/giantswarm/issues/3374)
- [ ] [Enable event Rate limitation](https://github.com/giantswarm/giantswarm/issues/3397)

## Can be Part of Sig-Security or Sig-Customer

- [x] [Ensure that the --profiling argument is set to false in scheduler and controller](https://github.com/giantswarm/giantswarm/issues/4813)
- [x] [1.2.2 Ensure that the --address argument is set to 127.0.0.1 in scheduler and controller](https://github.com/giantswarm/giantswarm/issues/4814)
- [x] [Enable Kernel Default protection](https://github.com/giantswarm/giantswarm/issues/2102)
- [x] [Set a default value for streaming-connection-idle-timeout](https://github.com/giantswarm/giantswarm/issues/3418)
- [x] [Disable the `Read Only` port on kubelet](https://github.com/giantswarm/giantswarm/issues/3416)
- [x] [Set the default value for `Api Server Request Timeout`](https://github.com/giantswarm/giantswarm/issues/3398)
- [x] [Ensure that the API Server only makes use of Strong Cryptographic Ciphers](https://github.com/giantswarm/giantswarm/issues/4812)

## Need more info

- [x] [Make sure CAdvisor port is not on a specific port](https://github.com/giantswarm/giantswarm/issues/2104)
- [ ] [Remove k8s event limit](https://github.com/giantswarm/giantswarm/issues/3420)
- [ ] [Change the default WAL directory from ETCD](https://github.com/giantswarm/giantswarm/issues/3403)

ref:
- [Wiki page](https://github.com/giantswarm/giantswarm/wiki/CIS-Benchmark)
- Sig Security Issues: [Go to the board](https://github.com/orgs/giantswarm/projects/14?card_filter_query=label%3Acis-benchmark%2Fk8s)
- Report: [Google Docs](https://docs.google.com/spreadsheets/d/1EfWeMMjOSH-zIdPAGjZBu8cHnt-_GNtXLngpRwtUG3M)

Aha! Link: https://giantswarm.aha.io/features/L-6

**Comment by corest** [comment]
Removing from sig-security board as it goes into team

**Comment by stone-z** [comment]
Set `read-only-port`, `protect-kernel-defaults`, and `address` flags in https://github.com/giantswarm/k8scloudconfig/pull/807

**Comment by puja108** [comment]
closing this as todos were done, might need a follow-up once we're on CAPI
