### ISSUE TITLE
Automatically update the AWS account id in `amazon-eks-pod-identity-webhook`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1804]
## Task

Automatically update the AWS account id in `amazon-eks-pod-identity-webhook` by calling the [AWS metadata instance service](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html) if it's not specified in the ServiceAccount IRSA annotation.

## TODOs

- [x] Fork `amazon-eks-pod-identity-webhook`;
- [x] Determine current AWS account id and update the service account annotation;
- [ ] Create upstream PR;
- [x] Test on a workload cluster and on a management cluster;
- [x] Release & deploy to all management clusters (except for `thunder`);

## Resources

- [amazon-eks-pod-identity-webhook](https://github.com/aws/amazon-eks-pod-identity-webhook);
- [IMDSv2 documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-instance-metadata-service.html);

**Comment by alex-dabija** [comment]
This solution was suggested by @AverageMarcus & @njuettner . See [Slack thread](https://gigantic.slack.com/archives/C02JTRT152L/p1670939074614899?thread_ts=1670933701.813749&cid=C02JTRT152L).

**Comment by zewolfe** [comment]
Release is currently blocked on clusters < `v18.1.0` by `kiam-agent`. 
This causes 
````
caused by: EC2MetadataError: failed to make EC2Metadata request
request blocked by allow-route-regexp "/latest/meta-data/placement/availability-zone": /latest/dynamic/instance-identity/document

	status code: 404,
````
the pod then crash loops and the deployment isn't satisfied.

**Comment by zewolfe** [comment]
PR upstream - https://github.com/aws/amazon-eks-pod-identity-webhook/pull/169

**Comment by alex-dabija** [comment]
I had a quick look over the PR and I was very surprised by the amount of changes. Why so many? Most of them didn't seem to be related to our change (I might be wrong about this).

**Comment by zewolfe** [comment]
`go mod vendor` and we added a dependency

**Comment by alex-dabija** [comment]
> `go mod vendor` and we added a dependency

Yes, I saw, but I was surprised by the amount of changes. Also, strange that `aws-sdk-go` was not a dependency.
