### ISSUE TITLE
Resolver rules API calls are throttled

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1805]
## Issue

Resolver rules API calls made by `dns-operator-aws` on `thunder` are being throttled by AWS.

There are a lot of resolver rules in the AWS account used by `thunder` and the operator is probably doing too many requests.

## TODOs

- [ ] Investigate why the operator is making too many requests;
- [ ] Update the `dns-operator-aws` to be mindful of the amount of requests it makes;
- [ ] Test in the customer's account on `thor`. (`thor` is / will be a new management cluster. See [issue](https://github.com/giantswarm/giantswarm/issues/25079));
- [ ] Release and deploy to all management clusters (except for `thuder`).

## Background

@calvix encountered this problem while creating the resolver rules for the cluster's private hosted zone.

**Comment by tuladhar** [comment]
We can utilize CloudTrial to determine the volume of AWS API calls to get a sense of which Route53 or other API calls are being requested the most.

**Comment by mnitchev** [comment]
The operator creates a single request per reconciliation request. This at the time of me investigating is - 1 request every 5 mins on `thor` and about 3 requests every 5 mins on `thunder`. This is currently because of https://github.com/giantswarm/giantswarm/issues/25196 , causing errors and the reconcilers going into exponential backoff for the errors. 
Looking at the cloud console network requests, the ones that fail are requests to `ListResolverRuleAssociations`. This should fall under the [API Limits for the Route53 Resolver API](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html#limits-api-requests-route-53-resolver) which are 5 requests per second.
With this I looked at the requests made by the cloud console and I think the problem is that we just have too many associations and the cloud console is only listing 50 associations per request. In my experiments the requests were around 25 made in a short amount of time (including the failed ones).

Provided the above information, I think this is a problem specific to the cloud console and not something we're doing wrong in our operators. I'm going to go ahead and close this. Feel free to reopen if you think I'm wrong.
