### ISSUE TITLE
Monitoring infrastructure next level with Mimir :rocket: 

### ISSUE THREAD

**Issue by mcbenjemaa** [giantswarm/roadmap#1817]
### Context

In order to solve limitations of our current monitoring setup, we need to try new tools that will basically help us for long term storage metrics, and HA, as well as Global view Querying...

One of the best tools in the market is Grafana Mimir.
We need to Try it, and find the best way to integrate it in our setup.

## User Story

As a Giant Swarm engineer, I want to be able to access a history of metrics for components managing our platform in order to be to both investigate ongoing operational issues and provide details for incident reports.

Ideally a month of metrics history should be available.

### Tasks

```[tasklist]
### Tasks
- [x] https://github.com/giantswarm/roadmap/issues/2263
- [x] https://github.com/giantswarm/roadmap/issues/2264
- [x] https://github.com/giantswarm/roadmap/issues/2265
- [x] https://github.com/giantswarm/roadmap/issues/2266
- [x] https://github.com/giantswarm/roadmap/issues/2267
- [ ] https://github.com/giantswarm/roadmap/issues/2430
- [ ] https://github.com/giantswarm/roadmap/issues/2521
- [ ] https://github.com/giantswarm/giantswarm/issues/26707
- [ ] https://github.com/giantswarm/dashboards/pull/305
- [ ] https://github.com/giantswarm/roadmap/issues/2565
- [ ] https://github.com/giantswarm/roadmap/issues/2566
- [ ] https://github.com/giantswarm/roadmap/issues/3039
```

- [ ] https://github.com/giantswarm/giantswarm/issues/26707

### Later

- Define cost dashboard
  - current prometheus cost
  - mimir cost
  - prometheus-agent transfer cost
- How to migrate
- Try-it mixins dashboards
- Define/migrate alerting rules
- What happens to SLOs

## Related issues

- https://github.com/giantswarm/giantswarm/issues/25272
- https://github.com/giantswarm/roadmap/issues/2027
- https://github.com/giantswarm/giantswarm/issues/27140

**Comment by mcbenjemaa** [comment]
helm configuration: https://grafana.com/docs/mimir/v2.5.x/operators-guide/run-production-environment-with-helm/configuration-with-helm/#example-of-configuration-managed-with-helm

**Comment by mcbenjemaa** [comment]
Configure Prometheus to write to Mimir: https://grafana.com/docs/mimir/v2.5.x/operators-guide/deploy-grafana-mimir/getting-started-helm-charts/#configure-prometheus-to-write-to-grafana-mimir

**Comment by mcbenjemaa** [comment]
Monitor Mimir: https://grafana.com/docs/mimir/v2.5.x/operators-guide/run-production-environment-with-helm/#monitor-the-health-of-your-grafana-mimir-cluster

**Comment by TheoBrigitte** [comment]
### Goal

Run Mimir on `gauss` to play & learn

### Tasks

- Create S3 bucket manually
- Package Mimir into an app
- Deploy Mimir
- Ingesting metrics from (current) Prometheus via RemoteWrite CR
- Add Mimir as Grafana datasource

### Later

- Define cost dashboard
  - current prometheus cost
  - mimir cost
  - prometheus-agent transfer cost
- How to migrate
- Try-it mixins dashboards
- Define/migrate alerting rules
- What happens to SLOs

**Comment by hervenicol** [comment]
The "Kubernetes / Compute Resources / Namespace (Pods)" dashboard shows nice info about CPU/RAM usage for the whole `mimir` namespace. 👍

**Comment by TheoBrigitte** [comment]
We want to compare Mimir vs Prometheus at installation level

- Build dashboard for Prometheus cost
  - CPU/Memory usage
  - Storage cost
  - Network transfer
  - Number of timeseries

- Build dashboard for Mimir cost
  - CPU/Memory usage
  - Storage cost
  - Network transfer
  - Number of timeseries
  - Try-it mixins dashboards

Let's aim for something similar as Loki cost dashboard from https://github.com/giantswarm/roadmap/issues/2182

**Comment by carillan81** [comment]
From the hackaton:

- In grafana running in gauss (using prometheus as a data source) I created a dashboard called Mimir cost Estimate  similar to Prometheus Cost Estimate . Currently there is no way to get S3 metrics for storage. A posibble follow up would be install YACE from here: https://promcat.io/apps/aws-s3
https://grafana.g8s.gauss.eu-west-1.aws.gigantic.io/d/d37ffc71-9200-4f0b-8f9a-9e2af9f6b3232/mimir-cost-estimate?orgId=1

- There is another dashboard with less info that puts together Prom and mimir one in front of the other. Prometheus - Mimir comparative   https://grafana.g8s.gauss.eu-west-1.aws.gigantic.io/d/dc39e0c1-d4f1-4c8e-b0ab-e1455621f64c/prometheus-mimir-comparative?orgId=1&var-cluster=gauss

- I have changed several panels in the Prometheus Cost Estimate to be more useful:
  - different aggregations
  - using max_over_time so we get the worst number inside the current range
  - fix some typos in descriptions

- Tested some of the mixin dashboards but they will require some tweaking.

**Comment by carillan81** [comment]
https://github.com/giantswarm/dashboards/pull/305

**Comment by TheoBrigitte** [comment]
### Status update

* Mimir deployed via GitOps giantswarm/management-cluster
* Prometheus send metrics via remote write
* Grafana Agent configure rule to Mimir
* Mimir Alertmanager deployed
* Alert available in Grafana via datasource
* Alertmanager config deployed via mimir tool manual
* Prometheus for rule evaluation and remote write to Grafana Cloud (currently duplicated in Mimir ruler)
* Mimir ruler evaluate rules for alerting
* aggregation recording rules splitted for better performances
* No multi-tenancy: anonymous
* Silence-operator: add support for multi-tenancy

Monitoring
* Mimir monitoring: component down
* Grafana Agent: monitoring ?
* Prometheus remote read: not monitored

TODO
* ruler & alertmanager store data on S3 in same bucket
* source link in alert
* 

* How to keep external labels ? Add labels in all recording rules
