### ISSUE TITLE
Give customers access to Grafana

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#182]
**Is your feature request related to a problem? Please describe.**

Provide customers access to Grafana per cluster

**Describe the solution you'd like**

Giant Swarm is working to have a Grafana deployment per cluster. There we have already developed several Dashboards that show the state of the cluster. To avoid customers to have to create their own monitoring stack for the cluster health and take advantage of our work we can implement an access view for them.

**Describe alternatives you've considered**

Prepared a Grafana managed app recipe that contains our dashboard and is ready to work in workload clusters.

**Additional context**

### Milestone 1. Setup the infrastructure and add first dashboards

- [x] #349 Investigate if we can use Grafana Enterprise - not an option for us, a lot of features we don’t need
- [x] https://github.com/giantswarm/giantswarm/issues/17157 
- [x] #362 Use a separate public repo for dashboards
- [x] #364 Gather analytics of dashboards usage
