### ISSUE TITLE
[Spike] Weave GitOps UI

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1821]
As an outcome of [this conversation](https://github.com/giantswarm/roadmap/issues/1745), we want to explore the potentialities of providing Weave GitOps UI to our customers.

## TODO

- [x] prepare
- [x] deploy
- [x] test
- [ ] demo with customers

**Comment by gianfranco-l** [comment]
Related: https://www.infoq.com/news/2023/01/google-gitops-observability/

**Comment by ljakimczuk** [comment]
## Weave GitOps UI Summary

### Sources and Installation

[Here](https://github.com/weaveworks/weave-gitops) is the Weave GitOps Github repository. Inside, there is a Helm Chart for [GitOps Server](https://github.com/weaveworks/weave-gitops/tree/main/charts/gitops-server) that provides the UI. The Weave GitOps documentation can be found [here](https://docs.gitops.weave.works/docs/intro). As stated by this documentation [here](https://docs.gitops.weave.works/docs/installation/weave-gitops/#deploying-weave-gitops), the GitOps Server may be installed with the help of GitOps CLI, which actually generates the `HelmRepository` and `HelmRelease` Flux CRs, a natural choice in the Flux environment.

### Configuration

I split the configuration into categories to make it more readable. The last section carries the `HelmRelease` CR that I used to install the dashboard. 

#### Access

The upstream Helm Chart provides [Ingress CR](https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/ingress.yaml) that can be used to provide outside-originated access to the Dashboard. Configuring TLS requires certificate which can be provided by Cert Manager, by annotating the Ingress CR with the `cert-manager.io/cluster-issuer: <issuer_name>`. Our clusters seem to have at least two issuers configured, the `selfsigned-giantswarm` and the `letsencrypt-giantswarm`, and for the tests I've choosen the former one. 

Note however, I am not sure of how the issuers get created, nor if their existence is the case for every installation, yet I expect it to be. Both carry the `last-applied-configuration` annotation that suggests both were created manually, probably as part of the bootstrapping process.

The relevant `values.yaml` part that must be configured is [here](https://github.com/weaveworks/weave-gitops/blob/fb54af42bddc355d881284569c7e44b782077fb4/charts/gitops-server/values.yaml#L108), for example:

```yaml
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-giantswarm
  hosts:
    - host: gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn
      secretName: gitops-tls
```

#### Login

As stated in [here](https://docs.gitops.weave.works/docs/configuration/securing-access-to-the-dashboard/), there are two ways to login to the Dashboard, either by using a static user account, or by using the OIDC provider. The recommended way is the latter, see:

> The recommended method is to integrate with an OIDC provider, as this will let you control permissions for existing users and groups that have already been configured to use OIDC.

The obvious downside of using the static account is, it seems it must be shared accross all the parties that require access for I see no way to configure the Dashboard with multiple of such accounts. And this in turn means there is no way to make the permissions granular, either all parties can do what the static account can do, or none of them.

The static account however seems helpful as a fallback login method for the admin users, in case the IdP provider or ingress are down, for example. For the PoC I configured the OIDC method only.

The login method can be decided with [this flag](https://github.com/weaveworks/weave-gitops/blob/fb54af42bddc355d881284569c7e44b782077fb4/cmd/gitops-server/cmd/cmd.go#L100), both methods can be used at the same time. This is the relevant [`values.yaml`](https://github.com/weaveworks/weave-gitops/blob/fb54af42bddc355d881284569c7e44b782077fb4/charts/gitops-server/values.yaml#L21) part that allows to configure the flags.

For the OIDC provider [this](https://github.com/weaveworks/weave-gitops/blob/fb54af42bddc355d881284569c7e44b782077fb4/charts/gitops-server/values.yaml#L32) part of the `values.yaml` must be configured, for example:

```yaml
oidcSecret:
  create: true
  clientID: fakeclient
  clientSecret: fakesecret
  issuerURL: https://dex.g8s.giraffe.pek.aws.k8s.adidas.com.cn
  redirectURL: https://gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn/oauth2/callback
```

For this to work, Dex or any other IdP must be configured with a new client for a Dashboard, see an example for Dex:

```yaml
web:
  allowedOrigins:
  - ...
  - https://gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn
...
staticClients:
- id: fakeclient
  redirectURIs:
  - https://gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn/oauth2/callback
  name: fakeclient
  secret: fakesecret 
```

#### Permissions

For the RBAC configuration the Weave GitOps states the following:

> The general recommendation is to use OIDC and a small number of groups that are Weave GitOps can impersonate. 
OIDC is the recommended method for managing authentication as it decouples the need to manage user lists from the application, allowing it to be managed via a central system designed for that purpose (i.e. the OIDC provider).

This makes sense, using the OIDC and impersonation relieves the Dashboard from necessity of configuring the RBAC, and instead makes it possible to rely on already established architecture. In such case the only permissions the Dashboard must configure are:

* rights to impersonate users and groups, this can be limited by the Kubernetes RBAC `resourceNames` list.
* rights to read both, the `oidc-auth` and the `cluster-user-auth` Kubernetes Secrets.
* read namespaces.
* list CRDs.

Which are minimal. The rest, i.e. what user can see and act upon, is determined by his permissions, and can be configured outside the Dashboard app. 

An exception to this is naturally the static admin account. When its creation is being requested, the Dashboard app creates [extra roles](https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/admin-user-roles.yaml) that grants it extended permissions  to read all the resources in the cluster-scope, and to in addition patch the Flux resources.

As stated by the documentation, see [this](https://docs.gitops.weave.works/docs/configuration/service-account-permissions/#the-helm-values), it should be further possible to limit which groups and users can be impersonated by the Dashboard, however in my opinion what is stated there is not entirely correct. It would be correct if the Helm Chart was configured differently. Let me elaborate of what I mean. 

Currently the document encourages to limit users and groups the application can impersonate, and gives example of this: 

```yaml
rbac:
  impersonationResources: ["groups"]
  impersonationResourceNames:
    - admin
    - dev-team
    - qa-team
```

However, this configuration alone will result in an error, because impersonating a group requires specifying a user as well, the [Kubernetes document](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation), hence the `users` must also be specified under the `impersonationResources`.

But when the `users` resource is added, the [Helm template](https://github.com/weaveworks/weave-gitops/blob/main/charts/gitops-server/templates/role.yaml) that uses these fields generates the below `ClusterRole` on installation:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-system-gitops-ui-weave-gitops
rules:
- apiGroups:
  - ""
  resourceNames:
  - admin
  - dev-team
  - qa-team
  resources:
  - groups
  - users
  verbs:
  - impersonate
```

It looked ok to me at the first glance, but the access didn't work, so I checked that up and it turns out it is a bad idea to put > 1 resources on the `resources` list and use the `resourceNames` at the same time. This was not immediately obvious to me, but now when I think of it, it makes total sense. In such scenario, the `resourceNames` limits apply to all the resources of a given rule, so it actually says:

```text
impersonation to these users - none - and these groups - [admin, dev-team, qa-team] - is allowed
```
where I thought of it saying:

```
impersonation to these users - all - and these groups - [admin, dev-team, qa-team] is allowed
```

To make it work the intended way, the `ClusterRole` must be changed to:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flux-system-gitops-ui-weave-gitops
rules:
- apiGroups:
  - ""
  resources:
  - users
  verbs:
  - impersonate
- apiGroups:
  - ""
  resourceNames:
  - admin
  - dev-team
  - qa-team
  resources:
  - groups
  verbs:
  - impersonate
```

But this is no supported by the upstream Helm Chart as of now. It can easily be done for Management Clusters, for if we decide to deploy it, it will be done with Flux that can patch the resources accordingly. If we are to offer Dashboard as an app, the upstream Helm Chart has to be either fixed there, or extended on our side.

#### `HelmRelease` CR

```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gitops-server
  namespace: flux-giantswarm
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: gitops-server
  interval: 1h0m0s
  targetNamespace: flux-system
  values:
    additionalArgs:
      - "--auth-methods=oidc"
    nodeSelector:
      kubernetes.io/hostname: ip-10-0-5-47.cn-north-1.compute.internal
    logLevel: debug
    oidcSecret:
      create: true
      clientID: fakeclient
      clientSecret: fakesecret
      issuerURL: https://dex.g8s.giraffe.pek.aws.k8s.adidas.com.cn
      redirectURL: https://gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn/oauth2/callback
    rbac:
      impersonationResourceNames:
        - 'customer:giantswarm:Employees'
        - 'giantswarm:giantswarm:giantswarm-admins'
        - 'giantswarm-ad:giantswarm-admins'
      impersonationResources:
        - 'groups'
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: selfsigned-giantswarm
      hosts:
        - host: gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - hosts:
            - gitops.g8s.giraffe.pek.aws.k8s.adidas.com.cn
          secretName: gitops-tls
      limits:
        cpu: 200m
        memory: 256Mi
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              version: v1
              group: rbac.authorization.k8s.io
              kind: ClusterRole
              name: flux-system-gitops-ui-weave-gitops
            patch:
              - op: add
                path: /rules/-
                value:
                  apiGroups:
                    - ""
                  resources:
                    - users
                  verbs:
                    - impersonate
```

### Conclusions

- Helm Chart is fairly easy and well maintained, with one exception mentioned above. But this should be fairly easy to fix in the upstream, or on our side. To be honest, I'm not sure of why it hasn't been patched already there, since it clearly cannot work the way it is configured now, but well, maybe no one has ever tried to limit the impersonation, or did it with patches like us or by some other means and has never mentioned this in the issues.
- the impersonation idea is nice, we already have the well-settled RBAC thanks to RBACOp mostly, so not being force to configure something extra for the Dashboard is huge adventage for me. The only problem with the impersonation is the lack of flexibility, see the next point.
- limiting impersonation, what users are encouraged to do when configuring the Dashboard, is not that flexible, what makes it useless in some scenarios. This is because it seems the the application tries to impersonate all the groups that are provided by the token, and fails when some of them are not listed in the `resourceNames` of `ClusterRole`. This is not a problem for us, because we already know which groups we are in, in both Github and Azure AD, but I am not sure how limiting process should be conducted for the customers, for I am not sure how many groups the customers tokens carry. For sure we know of some of the groups that are configured in both RBACOp and MCF, but if tokens contain more of them, then the authorization process will fail. But since we do not have many GitOps customers, maybe we could deal with them one-by-one, check of how they login, and if the groups we already know and use are complete set. If not then maybe we could check with them of how many more groups are included in the tokens.
- the `Flux Runtime` part of the Dashboard requires some tricks for displaying `flux-giantswarm` resources. Namely, the namespace has to be labeld with the `app.kubernetes.io/part-of: flux` label. Otherwise, only the default namespace of `flux-system` is displayed, see [here](https://github.com/weaveworks/weave-gitops/blob/dec828db8883283d65f24e92df8be2e939e0f8f7/core/server/fluxruntime.go#L187). I haven't seen it documented in any way, and this is already a second thing that is documented in a poor manner what makes me think of how many other things are yet to be discovered.
- the overall security model is a bit worrying, I mean, I still think the impersonation idea is grate, but lack of flexibility makes me think of what is the right way to configure the application. We already have apps in our cluster that run under elevated privileges, and thus are able to impersonate other subjects, and we are fine with that because customer users cannot abuse these apps. So maybe we shouldn't be worried in this case neither, and instead allow the Dashboard to impersonate any user, without limitations, and only make sure we deploy it into a secured namespace. But I must admit that I don't feel overly confidend that someone may accidently impersonate me and delete the `flux` Kustomization 😄 On the other hand, if we decide to limit the groups the application can impersonate, then there is still a question opened of how to deploy such application then. For having a single instance of the application with Giantswarm's and customer's groups mixed together in the `ClusterRole` works more or less like users are still allowed to impersonate any group, aka no limitations. To limit the impersonation when the customer logs in, and do not limit it when Giantswarm employees login, it would require having two instances of the application.
- Related to the above, Dex gives possibility to limit the groups that put into the token, I think, so maybe that is the way forward, i.e. limit the groups added to the token to the ones we already use within the cluster.

### ToDos to make it part of GS offering

- [ ] setup the Github repository for an app, and configure synchronization with the upstream Helm Chart
- [ ] re-tag the GitOps Server image to make it available in our registries
- [ ] configure Dex with a new client for GitOps Server, with possibility to limit the groups returned in the token
- [ ] add Helm-related Flux resources into the MCF, and decide the overal deployment scenario, like single vs two Dashboard instances
- [ ] add extra configuration to make sure `flux-giantswarm` resources are displayed, and impersonation is handled the right way, if needed
