### ISSUE TITLE
Upgrade CAPA to `v2.x` including `v1beta2` CRDs

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#1832]
## Task

Upgrade CAPA to `v2.x` including `v1beta2` CRDs.

## Background

CAPA is currently installed from a [custom version](https://github.com/giantswarm/cluster-api-provider-aws/commit/1ce7bb92c1bff8d9a3250940ba94b166b1d9f3db) ([PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/3871)). Once that fix landed upstream, we can go ahead upgrading CAPA. Since that involves upgrading to `v1beta2` CRDs, we must be careful since a rollback is not easy.

This is required so that operators can be upgraded to use new CRDs as well. In https://github.com/giantswarm/roadmap/issues/1469, we only upgraded until v1.5.2 because of this prerequisite.

Hint:

- [Changelog](https://github.com/kubernetes-sigs/cluster-api-provider-aws/releases/tag/v2.0.0) for CAPA v2.0.0
- https://github.com/giantswarm/cluster-api-provider-aws-app – `make generate` in that repo may create all the CRD files for the Helm chart
- Check if operators can only be upgraded after CAPA was deployed on the respective MC. If so, be careful with the order of releases.

## TODOs

- [x] Upgrade CAPA together with CAPI on one MC;
- [x] Check if everything is working fine;
- [x] Create issues for any problems found;
- [x] Ensure that the next steps are discussed in the team if too many problems are found;
- [x] Check which CRD CAPI versions are used by our operators and upgrade where needed (e.g. https://github.com/giantswarm/roadmap/issues/1328).

**Comment by AndiDog** [comment]
This took much more effort than expected, and we're not done yet. Progress:

- New CAPA controller (~ v2.0.2) was logging reconciliation like crazy. I fixed the busy loop in https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4025 and https://github.com/giantswarm/dns-operator-aws/pull/180.
- CAPA wrongly assumed network load balancer type and therefore failed to reconcile existing `AWSMachine` objects such as those of `AWSCluster/golem` (the MC on which I'm testing). It's because of missing field value defaulting. Writing the test took ages since I'm new to the code base and simulating non-defaulted values is not easy. Fix pending in upstream PR https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4029.
- Other, already merged fixes to work locally with CAPA code and tests: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4024, https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4023
- We cannot really upgrade CAPA to v2.x anywhere yet: hard blocker https://github.com/giantswarm/roadmap/issues/1932. I therefore need to keep our management cluster `golem` in limbo state. Or we roll back, but that would be nasty.

**Comment by AndiDog** [comment]
We decided to try a workaround for https://github.com/giantswarm/roadmap/issues/1932 – only in our fork – as short-time solution. Basically make the subnet ID optional again and test if it works. We will nevertheless get strongly involved in the draft and real solution for re-adding "generate the subnets instead of bring-your-own" in CAPA (will follow up in the other ticket).

**Comment by AndiDog** [comment]
Another blocker: https://github.com/giantswarm/giantswarm/issues/22689 must be finished, since only then we can release `irsa-operator` including the switch to CAPA v1beta1 types

**Comment by AndiDog** [comment]
CAPA v2 was well tested incl. on MCs for private cluster support, so we decided to roll out the change (https://github.com/giantswarm/cluster-api-provider-aws-app/pull/154).
