### ISSUE TITLE
Deploy Loki on AWS vintage installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1840]
Towards: https://github.com/giantswarm/roadmap/issues/311

In order to comply with new requirements (see [rfc](https://github.com/giantswarm/rfc/tree/main/logging-infrastructure#conclusion)) we need to setup Loki on a per installation basis.

This is an experiment that we will run for 1 week, in order to :

- make sure our solution works as expected
- gain customer trust
- gather cost data

After 1st week we make a conclusion and re-evaluate.

**This should be deployed on all AWS vintage installation but `flamingo`, `fox` and `bandicoot`.**

### How to validate
- [ ] I can access every Loki instance on each AWS installation

### Tasks
```[tasklist]
### Loki
- [x] Tell teddyfriends we are live
- [ ] Deploy to all AWS installations
```

**Comment by hervenicol** [comment]
Specifications:
* per-installation deployment (at least now). Let's start with `gauss`.
* with `flux` (setup in `config` repo)?
* how to define credentials (`.global.multitenantAuth.credentials`)?
    * read user to be used by Grafana on the MC
    * write user to be used by promtail on all WCs
* `global.clusterDomain` changes from an installation to another, how to dynamically set it?
* no ingress

**Comment by QuantumEnigmaa** [comment]
Example for gauss : 
```
apiVersion: v1
data:
  values: |
    global:
      dnsService: coredns
      clusterDomain: cluster.local
    multiTenantAuth:
      enabled: true
      replicas: 3
      credentials: |-
        users:
          - username: Tenant1
            password: 1tnaneT
            orgid: tenant-1
          - username: Tenant2
            password: 2tnaneT
            orgid: tenant-2 
    loki:
      loki:
        schemaConfig:
          configs:
            - from: '2020-09-07'
              store: boltdb-shipper
              object_store: s3
              schema: v11
              index:
                prefix: loki_index_
                period: 24h
            - from: '2023-01-24'
              store: boltdb-shipper
              object_store: s3
              schema: v12
              index:
                prefix: loki_index_
                period: 24h
        storage:
          type: s3
          bucketNames:
            chunks: gauss-g8s-loki-logs
            ruler: gauss-g8s-loki-logs
            admin: gauss-g8s-loki-logs
          s3:
            region: eu-west-1
      gateway:
        replicas: 3
        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-giantswarm
          hosts:
            - host: loki.g8s.gauss.eu-west-1.aws.gigantic.io
              paths:
                - path: /loki/api/v1/push
                  pathType: ImplementationSpecific
          tls:
            - hosts:
                - loki.g8s.gauss.eu-west-1.aws.gigantic.io
              secretName: loki-ingress-cert
        nginxConfig:
          file: |
            worker_processes  5;  ## Default: 1
            error_log  /dev/stderr;
            pid        /tmp/nginx.pid;
            worker_rlimit_nofile 8192;

            events {
              worker_connections  4096;  ## Default: 1024
            }

            http {
              client_body_temp_path /tmp/client_temp;
              proxy_temp_path       /tmp/proxy_temp_path;
              fastcgi_temp_path     /tmp/fastcgi_temp;
              uwsgi_temp_path       /tmp/uwsgi_temp;
              scgi_temp_path        /tmp/scgi_temp;

              default_type application/octet-stream;
              log_format   {{ .Values.gateway.nginxConfig.logFormat }}

              {{- if .Values.gateway.verboseLogging }}
              access_log   /dev/stderr  main;
              {{- else }}

              map $status $loggable {
                ~^[23]  0;
                default 1;
              }
              access_log   /dev/stderr  main  if=$loggable;
              {{- end }}

              sendfile     on;
              tcp_nopush   on;
              resolver {{ .Values.global.dnsService }}.{{ .Values.global.dnsNamespace }}.svc.{{ .Values.global.clusterDomain }};

              {{- with .Values.gateway.nginxConfig.httpSnippet }}
              {{ . | nindent 2 }}
              {{- end }}

              server {
                listen             8080;

                {{- if .Values.gateway.basicAuth.enabled }}
                auth_basic           "Loki";
                auth_basic_user_file /etc/nginx/secrets/.htpasswd;
                {{- end }}

                location = / {
                  return 200 'OK';
                  auth_basic off;
                }

                location = /api/prom/push {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3101$request_uri;
                }

                location = /api/prom/tail {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                }

                location ~ /api/prom/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                location ~ /prometheus/api/v1/alerts.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                location ~ /prometheus/api/v1/rules.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                location = /loki/api/v1/push {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3101$request_uri;
                }

                location = /loki/api/v1/tail {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection "upgrade";
                }

                location ~ /loki/api/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                location ~ /admin/api/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3101$request_uri;
                }

                location ~ /compactor/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                location ~ /distributor/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3101$request_uri;
                }

                location ~ /ring {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3101$request_uri;
                }

                location ~ /ingester/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3101$request_uri;
                }

                location ~ /ruler/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                location ~ /scheduler/.* {
                  proxy_pass       http://loki-multi-tenant-proxy.{{ .Release.Namespace }}.svc.{{ .Values.global.clusterDomain }}:3100$request_uri;
                }

                {{- with .Values.gateway.nginxConfig.serverSnippet }}
                {{ . | nindent 4 }}
                {{- end }}
              }
            }
kind: ConfigMap
metadata:
  labels:
    app-operator.giantswarm.io/watching: "true"
  name: loki-user-values
  namespace: giantswarm
```

**Comment by TheoBrigitte** [comment]
Moving this back into backlog as we are now blocked by this https://github.com/giantswarm/giantswarm/issues/26035

**Comment by TheoBrigitte** [comment]
We got a go from teddyfriends. We can run our Loki trial on customer aws installation, except for `flamingo` and `bandicoot`).

**Comment by QuantumEnigmaa** [comment]
Nice ! :D

**Comment by TheoBrigitte** [comment]
### Loki

- Deploy it via a collection and config repo
- Add support to disable top chart in Loki chart

## Promtail

- Deploy it via observability-bundle
- Add support for extraObject in observability-bundle chart
- Set config per installation config via extraObject

**Comment by TheoBrigitte** [comment]
- Learn how to deploy with [MCB](https://github.com/giantswarm/management-cluster-bases) (ask team-honeybadger)
- Test deploy on `gauss`
- Test disabled setting on testing installation
- Set disabled setting on `flamingo` and `bandicoot`
- Tell teddyfriends we are going live
- Deploy to all AWS installations

**Comment by hervenicol** [comment]
# Status 2023-06-13:

- loki is in aws collection
- config disables it by default
- yet we have a default config that should work on aws installs. To be tested.

**Comment by QuentinBisson** [comment]
Tested enabling on gaia, working fine:

```
k get pods -n loki
NAME                                       READY   STATUS    RESTARTS   AGE
loki-backend-0                             1/1     Running   0          28m
loki-backend-1                             0/1     Pending   0          28m
loki-gateway-596988897-m5rb5               1/1     Running   0          28m
loki-gateway-596988897-q6v5l               1/1     Running   0          28m
loki-multi-tenant-proxy-6db5459444-5kd8v   3/3     Running   0          28m
loki-multi-tenant-proxy-6db5459444-stflm   3/3     Running   0          28m
loki-read-788d8b757b-bsjbt                 1/1     Running   0          28m
loki-read-788d8b757b-r2zk8                 1/1     Running   0          28m
loki-write-0                               1/1     Running   0          28m
loki-write-1                               1/1     Running   0          28m
```

Pending pod is due to the MC itself and not loki

**Comment by QuentinBisson** [comment]
Pending pod fixed now that loki-backend can only be deployed on worker nodes because control-plane nodes do not have CSI enabled

**Comment by hervenicol** [comment]
Running on the following installations:
* akita - tested :green_circle:
* alpaca - tested :orange_circle: can't access log labels
* anaconda - tested :green_circle:
* anchovy - tested :green_circle:
* anteater - tested :green_circle:
* antelope - tested :green_circle:
* argali - :red_circle: `ImagePullBackOff` - "You have reached your pull rate limit" (China, should use Aliyun)
* eagle - tested :green_circle:
* gaia - tested :green_circle:
* gauss - tested :green_circle:
* giraffe - tested :green_circle:
* gorilla - need to be cleaned up from old setup :orange_circle: 
* kudu - tested :green_circle:
* potato - tested :green_circle:
* valkyrie - tested :green_circle:
* viking - tested :green_circle:
* viper - tested :green_circle:
* visitor - tested :green_circle:

Disabled on these:
* bandicoot 
* flamingo 
* fox

**Comment by TheoBrigitte** [comment]
Announced :heavy_check_mark: 

- to teddyfriends https://github.com/giantswarm/giantswarm/issues/26035#issuecomment-1695898865
- to all giantswarm https://gigantic.slack.com/archives/C90BZMUJ1/p1693236232175229

**Comment by TheoBrigitte** [comment]
Blocked until we figure out if we can deploy it to `fox`

**Comment by TheoBrigitte** [comment]
We can complete deployment and deploy logging onto the 3 missing installations :

- `bandicoot`
- `flamingo`
- `fox`

**Comment by hervenicol** [comment]
Loki deployed and working on the last 3 installations:
* `bandicoot`
* `flamingo`
* `fox`
