### ISSUE TITLE
Run a JSON Schema introduction session

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#1846]
To enable everyone (specifically: KaaS teams) to work with schema for app values directly, we want to provide introduction knowledge quickly and conveniently.

## Tasks

- [x] Prepare JSON Schema introduction session content ([Slides](https://docs.google.com/presentation/d/1IIaBEUIyUTDWVzTwE7EH2yWuge36ht3UAiaioDV_6vs/edit#slide=id.gcb9a0b074_1_0))
- [x] Schedule and invite to the talk: Thu 26 Jan, 13:00 CET
- [x] Spread talk recording

**Comment by marians** [comment]
First slide deck draft is available: https://docs.google.com/presentation/d/1IIaBEUIyUTDWVzTwE7EH2yWuge36ht3UAiaioDV_6vs/edit#slide=id.gcb9a0b074_1_0

@kuosandys @mogottsch @gusevda Could you please take a look and give me feedback?

(In case you wonder why it's not using a Giant Swarm template: I don't like the Giant Swarm template for educational purposes. It's hard to work with it.)

**Comment by mogottsch** [comment]
> @kuosandys @mogottsch @gusevda Could you please take a look and give me feedback?
Great presentation! :+1:
I actually didn't know that CRDs also use JSON schema.

**Suggestions**:
It would be interesting and motivating to show a Screenshot of the form for cluster app creation in happa. Then people see another reason why this is useful.

**Comment by marians** [comment]
@mogottsch Thanks for the feedback! For the UX vision part I want to show a few slides [from this slide deck](https://docs.google.com/presentation/d/16McEeTiDPyVPglnvqguC3K98LxDB-R-S8mk2uhmAzkg/edit#slide=id.g1bc82b6f56f_0_140) to make sure that the motivation can be understood.

**Comment by marians** [comment]
FYI The internal talk is scheduled for this Thursday, Jan 26, 13:00 CET.

**Comment by kuosandys** [comment]
Slide deck looks great! I think the high-energy colour theme is a nice variation from the standard template and fitting for the intro session 👍 

I noticed that the slide containing the example for reusing JSON schema (slide 27) comes before the slide explaining how to reuse schema (slide 28). From a reader's perspective, I would've expect the example to come after the explanation, though the existing order might be more fitting for the presentation. Just thought I'd make a note here 🙂

**Comment by marians** [comment]
Thanks for the deep feedback! I'm thinking that an example make this sort of info more accessible and engaging. You can actually invite people to figure out what's going on. And then recap it in a "classical" info slide.

**Comment by marians** [comment]
Recording is in https://drive.google.com/file/d/1pBaCsfHK9srOZbp-YBB6ND3XRtg1Xrf5/view (currently still processing)

**Comment by marians** [comment]
I asked @Mircohelle as the owner of the recording to put it into a place where everyone has access. Apart from that, the issue is done.
