### ISSUE TITLE
AWS Release v18.2.0

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#1860]
ℹ️ Team Phoenix is drafting AWS v18.2.0 with Kubernetes v1.23 support.
Target release date: 2023-02-03.
Release PR: ...

## Scope
- [x] Ensure monitoring of k8s components (latest prometheus operator)
- [x] upgrade of all components
- [x] https://github.com/giantswarm/giantswarm/issues/24615
- [x] latest node-exporter v1.15.x
- [x] bump to lates k8scc in aws operator for CPU allocation fixes
- [x] [registry mirrors support for containerd](https://github.com/giantswarm/giantswarm/issues/24615)
- [x] [Add IAM role for aws-lb-app](https://github.com/giantswarm/roadmap/issues/1836)
- [x] https://github.com/giantswarm/roadmap/issues/1875
- [x] https://github.com/giantswarm/roadmap/issues/1487 - new default set to 15GB
- [x] [IP/pods calculations - for prefix subnet mode we fall back to 110 pod limit](https://github.com/giantswarm/roadmap/issues/1925)
- [x] https://github.com/giantswarm/giantswarm/issues/25420
- [x] https://github.com/giantswarm/giantswarm/issues/25481
- [x] https://github.com/giantswarm/giantswarm/issues/25628
- [x] https://github.com/giantswarm/roadmap/issues/1938
 

## Pre-Release
- [ ] Create release ticket on [Releases board](https://github.com/orgs/giantswarm/projects/136)
- [ ] Make an announcement on #sig-product that team is doing a release. Include a link to the ticket from the release board.
- [ ] Make sure release was tested by creating new cluster, upgrading from older version and with HelloWorld app.
- [ ] Aggregate release notes from all changed components and add to `README.md` in the release directory.
- [ ] Send draft release announcement to #sig-product for review ASAP.
- [ ] Verify documentation is up to date.

## Releasing
- [ ] Create release PR
[Instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/)
    - [ ] Define new release in `release.yaml` file.
    - [ ] Activate new release by setting `state` to `active`.
    - [ ] Deactivate old release if it's within same major version (`state: deprecated`). Verify with PO if you have doubts.
    - [ ] Check versions of all components included. They shouldn't be lower than those in the previous release unless there was a rollback.

[Example PR](https://github.com/giantswarm/releases/pull/318)
- [ ] Release relevant operators.
    - [ ] Tag release branch.
    - [ ] Bump operator version in draft release.
- [ ] Make sure that WIP releases in releases repo branch are removed and not merged to master since the master branch is deployed automatically after merging PR and that would make WIP releases visible in customers’ installations which should generally not happen.

## Post-Release
- [ ] Update front-end cluster with the new release.
- [ ] Verify release is available on all installations. You can use [this script](https://github.com/giantswarm/azure-operator/blob/25bf788946c5405532b3b4b76c54b8e685ee291b/scripts/list-releases.sh).
- [ ] Send out release announcement to all customers according to [these instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/#release-notes).
- [ ] PO subscribes to release posts on Slack to get notifications if there are follow-up messages.
- [ ] Close release task on Releases board.

**Comment by T-Kukawka** [comment]
@whites11 is there a need to bump Flatcar to latest here? or we can skip it untill v19?

**Comment by whites11** [comment]
> @whites11 is there a need to bump Flatcar to latest here? or we can skip it untill v19?

Need? no, but security wise is always a good idea I think

**Comment by T-Kukawka** [comment]
@njuettner can we do it? As actually v19 release date is undefined

**Comment by njuettner** [comment]
We need to make a decision for the ALBController Role
Unfortunately we are only allowed to create IAM roles with a specific naming, see https://github.com/giantswarm/aws-operator/pull/3477.

So either we need to create ALBController IAM role starting with `gs-` or we need to update all IAM Policies for `aws-operator`

**Comment by whites11** [comment]
the new role for ALB controller is in place (aws operator 14.6.0) and another change needed by the app was released in cluster-operator 5.4.0.

Unfortunately the app still does not seem to work, with kiam logging this

```
Error processing request: error fetching credentials: rpc error: code = Unknown desc = AccessDenied: User: arn:aws:sts::107744613923:assumed-role/t7cn2-IAMManager-Role/1675097169250832001 is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::107744613923:role/gs-t7cn2-ALBController-Role
```

**Comment by whites11** [comment]
alb controller confirmed working.
now testing number of pods

**Comment by whites11** [comment]
all good with pods count and aws cni prefix mode. handing over to @njuettner for release finalization
