### ISSUE TITLE
Deploy promtail to WCs

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1872]
Towards: https://github.com/giantswarm/roadmap/issues/311

### Context

In order to scrape logs from clusters (MCs and WCs) we need to deploy [Promtail](https://github.com/giantswarm/promtail-app) there.
Deployment to WCs usually takes time as this goes through WC upgrades (which is a manual process and requires customer approval); so in favor of time we rather start doing this early.
Deploying to MCs also needs to happen, but this is easier as we control the process there.

The main idea is to ship Promtail but keeping it disabled for now; therefore we can later enable it and adjust its configuration independently from releases.

### TODOs

- [ ] Define how we handle Promtail configuration
  - [ ] How to enable Promtail on each cluster
  - [ ] How to update Promtail configuration
- [ ] Create default Promtail config to scrape nothing
- [ ] Deploy Promtail; disabled by default
  - [ ] Deploy Promtail to vintage MCs
  - [ ] Deploy Promtail to vintage WCs
  - [ ] Deploy Promtail to CAPI

**Comment by TheoBrigitte** [comment]
Closing this, as I copied the TODOs into the main epic.
