### ISSUE TITLE
Update cluster-vsphere chart

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#1889]
prerequisite for this is to have a healthy `cluster-api-provider-vsphere-app` to be able to test the infra capv resources against the working and properly deployed provider

so creating a sub-task:

```[tasklist]
### Tasks
- [x] https://github.com/giantswarm/giantswarm/issues/25783
- [x] https://github.com/giantswarm/roadmap/issues/2015
- [ ] https://github.com/giantswarm/roadmap/issues/2106 (partially, CNI part got merged and cpi&csi pr is waiting, but I feel we should close this issue)
```

**Comment by jkremser** [comment]
draft pr: https://github.com/giantswarm/cluster-vsphere/pull/23

**Comment by erkanerol** [comment]
@erkanerol Please review this PR. 

Reminder: You can use @jkremser's mc-bootstrap hacks to test.
