### ISSUE TITLE
CAPG maintenance release (1)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1899]
## Task

Prepare, test, release and rollout the first CAPG maintenance release.

## Scope

- [ ] Update the default apps;
- [ ] [Remove organization label from CRs](https://github.com/giantswarm/roadmap/issues/1312);
- [ ] [Update Kubernetes to `v1.23.16`](https://github.com/giantswarm/roadmap/issues/1886);

## Other TODOs

- [ ] Test the new release;
- [ ] Upgrade `gohan` to this release;
- [ ] Upgrade `gunther` to this release;
- [ ] Upgrade `falcon` to this release;
- [ ] Notify customers about the new release and it's impact;
- [ ] Work with customers to upgrade their clusters.

**Comment by fiunchinho** [comment]
Can we close this one? We don't have any customers in GCP.

**Comment by alex-dabija** [comment]
> Can we close this one? We don't have any customers in GCP.

Yes, it can be closed because CAPG development is frozen.
