### ISSUE TITLE
Kubernetes  Release v1.16

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/roadmap#19]
Kubernetes 1.16

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1-16.md

### Provide a new release with the kubernetes version

* [x] Check with the teams about wip changes within k8scloudconfig and the provider-specific operators. Decide with version folder to use.
* [x] Retag new image in retagger
* [x] Check [upstream changelogs](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md).
  * [x] Check urgent upgrade notices.
  * [x] Check deprecation notices.
  * [x] Check component upgrades.
    * [x] Calico
    * [x] ETCD
    * [x] Container Linux
* [x] Create a PR in k8scloudconfig with the new kubernetes version
  * [x] Update k8s version in the different template files
  * [x] Use k8s version for `k8s-addons` (e.g. https://github.com/giantswarm/k8scloudconfig/blob/4695b7d6eb35eae234d0ce0c0c09f4b412525a68/v_4_7_0/files/conf/k8s-addons#L5)
  * [x] Include the systemd unit for kubelets https://github.com/giantswarm/giantswarm/issues/6498
* [x] Update cluster-autoscaler https://github.com/giantswarm/cluster-autoscaler-app/pull/9 
* [x] Vendor k8scloudconfig in the provider-specific operators
* [x] Create a wip release (major version change if it is a minor kubernetes upgrade)
* [x] Do this for each provider
* [x] Check Prometheus rules for deprecated metrics and fix them if necessary @tfussell 
* [x] [Upgrade helm to 2.16.1](https://github.com/giantswarm/giantswarm/issues/7675)

### Check migration recommendations

Check migration recommendations from kubernetes and decide what we need to document for the customer and what we should migrate automatically for them

* [x] Do we need to change our own resources within the tenant clusters?
* [x] What do we need to communicate to our customers?
* [x] Anything else that would be better automated for the upgrade?

### Run e2e and conformance tests

* [x] Start a new cluster and run conformance tests against it
  * [x] AWS legacy @tfussell / @stone-z 
  * [x] AWS nodepools @tfussell 
  * [x] KVM @omegas27 
  * [x] Azure @MarcelMue 
* [x] Start a new cluster and run e2e tests against it

### Check Core Components

* [x] Check core components for updates and include them in cluster-operator [PR giantswarm/giantswarm#788](https://github.com/giantswarm/cluster-operator/pull/788)
  * [x] Cert-exporter (already at 1.2.0, only change since is the README)
  * [x] Chart-operator (1 commit, 2 open PRs. Asked in PRs if they want released) @stone-z  
  * [x] Cluster-autoscaler [PR giantswarm/giantswarm#9](https://github.com/giantswarm/cluster-autoscaler-app/pull/9)
  * [x] CoreDNS [PR giantswarm/giantswarm#8](https://github.com/giantswarm/coredns-app/pull/8)
  * [x] Kube-state-metrics (no change)
  * [x] Net-exporter [PR giantswarm/giantswarm#67](https://github.com/giantswarm/net-exporter/pull/67)
  * [x] Nginx ingress controller (no change)
  * [x] Node-exporter [PR giantswarm/giantswarm#6](https://github.com/giantswarm/node-exporter-app/pull/6)
* [x] All helm releases in the giantswarm namespace should be in status deployed
* [x] Core components are runnning without errors
  * [x] Cert-exporter
  * [x] Chart-operator
  * [x] Cluster-autoscaler
  * [x] CoreDNS
  * [x] Kube-state-metrics
  * [x] Net-exporter
  * [x] Nginx ingress controller
  * [x] Node-exporter
* [x] Cluster-operator is running without errors
* [x] Cluster-operator is able to create chart-configs in the tenant

### Test migration (both cluster functionality itself and workloads)

* [x] Start a cluster with an older version and upgrade the cluster to the new release
* [x] Upgrade a cluster that is not critical but has some more real workloads (eg giantswarm website, dev cluster of customer)
* [x] All Providers
  * [x] aws nodepools @tfussell 
  * [x] aws legacy @tfussell / @stone-z 
  * [x] azure @MarcelMue 
  * [x] kvm @omegas27 

### Write summary for the release and update docs

* [x] Write some release notes
  * [x] Mention breaking change from https://github.com/giantswarm/giantswarm/issues/6413 in changelog.
* [x] Check if our docs need to be updated
* [x] Announce the release internally (SEs are important here)
* [x] Announce the release to the customers

Aha! Link: https://giantswarm.aha.io/features/L-7
