### ISSUE TITLE
Deploy Promtail

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#1908]
Towards: https://github.com/giantswarm/roadmap/issues/311

We want to start shipping Promtail as early as possible to all AWS clusters (MCs and WCs).
In order to achieve this we want to ship Promtail disabled by default with a dummy configuration to scrape nothing.

- [x] Add Promtail to the [observability-bundle](https://github.com/giantswarm/observability-bundle/)
- [x] Create default Promtail config to scrape nothing (logging-operator will update the config)
- [x] Deploy Promtail to AWS vintage MCs
- [x] Deploy Promtail to AWS vintage WCs

**Comment by TheoBrigitte** [comment]
duplicate from https://github.com/giantswarm/roadmap/issues/2054
