### ISSUE TITLE
Reduce latency of App Platform (app and chart CR events)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#191]
## User Story

* As an App Developer, I want app configuration changes to be applied faster, so that we can iterate faster. 
* As an oncaller, I want app configuration changes to be applied faster, so that I can roll out changes faster during incidents (where every second is precious, e.g. during flash sales). 

Note: App Developer applies to both customers and GS developers.

## Details, Background

There are two main factors that delay the application of configuration changes.

**1. App and Chart CR design**

The App Platform design involves 2 CRDs (app and chart) so we are less coupled to Helm in case we want to replace later. We use the standard resync periods of 5 mins.

**2. Configmaps and Secrets not watched by app-operator**

Again, there can be a delay of up to 5 mins. This means the total time can be up to 10 mins.

## Milestone 1

- [x] https://github.com/giantswarm/giantswarm/issues/13196 Trigger chart CR update when linked configmap or secret is updated

## Later / TBD

- [x] https://github.com/giantswarm/giantswarm/issues/13201 Trigger updating app CR status when chart CR status changes, to reduce latency of updating app CR status
- [x] https://github.com/giantswarm/giantswarm/issues/13202 Add controllers to app-operator to watch user values configmaps and secrets

**Comment by tomahawk28** [comment]
All subtasks are done. I'm closing this.

**Comment by cokiengchiara** [comment]
Not available in tenant clusters yet.

**Comment by cokiengchiara** [comment]
Let's include in releases.yaml https://intranet.giantswarm.io/docs/product/releases/requesting-changes-in-next-platform-release/
