### ISSUE TITLE
Test MC Creation Workflow for Customers

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#1919]
### Motivation
We have a [documented process](https://docs.giantswarm.io/getting-started/cloud-provider-accounts/azure/) how customers should prepare their azure subscriptions to get a Management Cluster installed in there. We need to check if that documentation is still valid for our CAPZ Product, or if we need to update it.

### Todo
- Follow the documentation in https://docs.giantswarm.io/getting-started/cloud-provider-accounts/azure/  and https://intranet.giantswarm.io/docs/customers/azure-tech-onboarding/
- [x] prepare a new azure subscription (like gremlin) according to that document
- [x] install a management cluster into that subscription
- [x] document any additional requirements we have to preprepared resources from customers 
- [x] derive action items if needed for any change in the process

### Outcome
- We know and documented what difference - if there are any - we have between the process of onboarding customers to CAPZ compared to the already publicly documented process.

**Comment by primeroz** [comment]
https://docs.giantswarm.io/getting-started/cloud-provider-accounts/azure/ is old and not 100% correct for vintage either as far as i understand for the first part about setting up Service Principals. thisis more update https://intranet.giantswarm.io/docs/support-and-ops/installation-setup-guide/azure-iam/ 

For CAPZ I added new docs in 
* https://github.com/giantswarm/giantswarm/pull/26231 

But there is more to creating a cluster than just those docs , i will try and put all the links in this comment 

*

**Comment by Rotfuks** [comment]
It sounds like it's definitely helpful to create a "CAPZ MC Installation" operations recipe and document it under [CAPZ Provider Overview in the Intranet](https://intranet.giantswarm.io/docs/product/providers/capz/) just like we did with setting up the [VPN for CAPZ Clusters](https://intranet.giantswarm.io/docs/product/providers/capz/vpn-for-capz-clusters/)

**Comment by primeroz** [comment]
@Rotfuks then i think i might need to move the docs in https://github.com/giantswarm/giantswarm/pull/26231 ( at least the `setup-guide` into this one you pointed up above

**Comment by Rotfuks** [comment]
> @Rotfuks then i think i might need to move the docs in https://github.com/giantswarm/giantswarm/pull/26231 ,at least the setup-guide, into this one you pointed up above

Not necessarily - If other locations make more sense then we can do the same as with the VPN doc and just create a list of documentations and links to where to find them. At the end all I care about is a nice entrypoint from where to find all information I need.

**Comment by Rotfuks** [comment]
Follow Up Stories from the Test: 
- https://github.com/giantswarm/roadmap/issues/2171
- https://github.com/giantswarm/roadmap/issues/2175

**Comment by primeroz** [comment]
Reminders 

* cluster-api-provider azure needs to be changed to 1.8.1-40d66716b0184c6f527ac29eb81240f701bfc33f in the capz-app-collection branch
* dns-operator-azure needs to fix version and check why is crashing with  `environment variable AZURE_SUBSCRIPTION_ID not set`

**Comment by primeroz** [comment]
this is the env i used to install garlic

```
OPSCTL_GITHUB_TOKEN=xxxx
INSTALLATION=garlic
CUSTOMER=GS-GREMLIN
PROVIDER=capz
NONINTERACTIVE=0
NEW_TEST_INSTALLATION=1
CLUSTER_API_PROVIDER_APP_CATALOG=control-plane-test
CLUSTER_API_PROVIDER_APP_VERSION=1.8.1-40d66716b0184c6f527ac29eb81240f701bfc33f
CILIUM_APP_VERSION=0.6.1
```

**Comment by primeroz** [comment]
notes to create the `dex-operator` secret credentials

```

* `opsctl secret decrypt --in installations/gremlin/apps/dex-operator/secret-values.yaml.patch --out installations/gremlin/apps/dex-operator/secret-values.yaml.patch.decrypt -i gremlin`
  * THIS is `gremlin` on purpose, the credentials are used to login into azure , don't change it 
* `opsctl create dexconfig -i <MC_NAME> --action create --in installations/gremlin/apps/dex-operator/secret-values.yaml.patch.decrypt installations/<MC_NAME>/apps/dex-operator/secret-values.yaml.patch.decrypt`
  * keep GREMLIN but change the output 
* `opsctl secret encrypt --in installations/<MC_NAME>/apps/dex-operator/secret-values.yaml.patch.decrypt --out installations/<MC_NAME>/apps/dex-operator/secret-values.yaml.patch -i <MC_NAME>`
  * this does not work on capi clusters due to the command expecting `vault/ca.pem` - manage the ecnryption yourself with sops
* Make sure to remove any plain text secret before committing

**Comment by primeroz** [comment]
There are no Targets in `prometheus` being scraped on garlic :(

**Comment by primeroz** [comment]
This is all done, i will delete the cluster and the VPN Connection once we are done with tests to the `dns-operator-azure` @bavarianbidi

**Comment by primeroz** [comment]
we are done with `garlic` , i will start deleting it now

**Comment by primeroz** [comment]
## Deletion Checklist

* [ ] Delete `garlic` resource group from Gremlin subscription
* [ ] Delete branches in `config` , `MCF` , `installations` and `capz-app-colleciton` repos 
* [ ] Delete the `garlic-dns-operator-azure` Role assignment from `azuretest.gigantic.io` dns zone in `gollum-prod`

**Comment by primeroz** [comment]
garlic is no more
