### ISSUE TITLE
`falcon` kube-api down didn't page

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1940]
## Task

Investigate why falcon kube-api was down and we didn't get paged.

## TODOs

- [ ] Investigate way the alert didn't page;
- [ ] Check CAPA MCs;
- [ ] Check CAPG MCs;

## Questions

- Do we have the same problem with CAPA installations?

## Links

- [Atlas investigation results](https://gigantic.slack.com/archives/C02EVLE9W/p1675246930533609?thread_ts=1675165993.575529&cid=C02EVLE9W);

**Comment by mnitchev** [comment]
Close with https://github.com/giantswarm/giantswarm/issues/25676
