### ISSUE TITLE
Prepare Weave Gitops UI app chart

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1942]
This is follow up/ outcome of [this spike](https://github.com/giantswarm/roadmap/issues/1821) 

Spike findings are [here](https://github.com/giantswarm/roadmap/issues/1821#issuecomment-1412390456)

Possible options:

a) deploy weave-gitops UI to all MCs (having Flux)

### ToDos to make it part of GS offering

- [x] setup the Github repository for an app, and configure synchronization with the upstream Helm Chart
- [x] re-tag the GitOps Server image to make it available in our registries
- [x] configure Dex with a new client for GitOps Server, with possibility to limit the groups returned in the token
- [x] add Helm-related Flux resources into the MCF, and decide the overal deployment scenario, like single vs two Dashboard instances
- [x] add extra configuration to make sure `flux-giantswarm` resources are displayed, and impersonation is handled the right way, if needed

b) having a demo with customers using Flux and/or having a demo with customers not using Flux

c) park this feature temporarily
