### ISSUE TITLE
App Platform / Flux: discovery for working with non-GS clusters 

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1948]
Product strategy 2023

Platform teams priorities

 Q1: 

- finish what we are working on;
- discovery for building the golden path;
- discovery for working with non-GS clusters (EKS first). 

Q2:
- cluster independent app platform (running on adopted cluster)
- cluster independent dev platform (running on adopted cluster)
        - bulding the golden path

golden path --> more about providing a supported path rather than building blocks for them to try and combine and expect us to support them

## Scope 

Within the scope of this discovery, we will test drive the app platform alternative (HelmReleases+Flux) in 1-2 places with lower impact to be more sure and have initial experience with it around the larger thought about going all in with Flux (and maybe sunsetting App Platform)

## TODO
- [ ] let’s write a post about the general vision we have around this to gather feedback from company at large (mostly around if App CRs still make sense as main interface for our releng platform)
- [ ] https://github.com/giantswarm/roadmap/issues/1989
- [x] write down ideas about how to proceed with app platform

**Comment by gianfranco-l** [comment]
@piontec pls define scope and next steps as we agreed during preplanning

**Comment by gianfranco-l** [comment]
in scope for this, we will (partially) go through [App Platform review](https://github.com/giantswarm/giantswarm/issues/20611)

**Comment by gianfranco-l** [comment]
let’s write a post about the general vision we have around this to gather feedback from company at large (mostly around if App CRs still make sense as main interface for our releng platform) @piontec. We can link this ticket in the post and ask to leave feedback in this ticket

**Comment by gianfranco-l** [comment]
side related to this discovery, also this https://github.com/giantswarm/roadmap/issues/1989

**Comment by gianfranco-l** [comment]
https://github.com/giantswarm/giantswarm/issues/26051#issuecomment-1455993306

**Comment by gianfranco-l** [comment]
related to https://github.com/giantswarm/giantswarm/issues/24791

**Comment by gianfranco-l** [comment]
related to app-bundle discovery --> https://github.com/giantswarm/giantswarm/issues/26406

**Comment by piontec** [comment]
Write up about possible solutions here: https://hackmd.io/KZtXpAJ-Qu215NNAVY0BxQ?view

**Comment by piontec** [comment]
More high-level info: https://hackmd.io/BPXcLYvzTNaQzr2sPpqfFg

**Comment by piontec** [comment]
Research is done, we have some ideas, they were discussed with Timo and Puja. Closing this one and will create more specific implementation epics.
