### ISSUE TITLE
Default deny all network policy in CAPV and CAPVCD

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#1949]
## Links

* Parent issue https://github.com/giantswarm/giantswarm/issues/23014
* List of apps to migrate https://github.com/giantswarm/giantswarm/issues/23014#issuecomment-1476131626

## TODO

```[tasklist]
### Gneral
- [x] UX, default values ([comment below](https://github.com/giantswarm/roadmap/issues/1949#issuecomment-1550232491))
- [x] Installations migration ([comment below](https://github.com/giantswarm/roadmap/issues/1949#issuecomment-1550270379))
```

```[tasklist]
### CAPI + mc-bootstrap
- [ ] https://github.com/giantswarm/cluster-api-app/pull/132
- [ ] https://github.com/giantswarm/cluster-api-app/pull/133
- [ ] https://github.com/giantswarm/cluster-api-app/pull/140
- [ ] https://github.com/giantswarm/cluster-api-app/pull/141
- [ ] https://github.com/giantswarm/cluster-api-app/pull/148
- [ ] https://github.com/giantswarm/config/pull/1791
- [ ] https://github.com/giantswarm/mc-bootstrap/pull/536
- [ ] https://github.com/giantswarm/mc-bootstrap/pull/555
```

```[tasklist]
### Other
- [ ] https://github.com/giantswarm/rbac-operator/pull/429
- [ ] https://github.com/giantswarm/config/pull/1876
- [ ] https://github.com/giantswarm/kyverno-app/pull/265
- [ ] https://github.com/giantswarm/config/pull/1866
```

```[tasklist]
### CAPVCD
- [ ] https://github.com/giantswarm/cloud-director-app-collection/pull/48
- [ ] https://github.com/giantswarm/cluster-api-app/pull/134
- [ ] https://github.com/giantswarm/cluster-api-app/pull/147
- [ ] https://github.com/giantswarm/cluster-api-provider-cloud-director-app/pull/57
- [ ] https://github.com/giantswarm/cluster-api-provider-cloud-director-app/pull/66
- [ ] https://github.com/giantswarm/config/pull/1807
- [ ] https://github.com/giantswarm/default-apps-cloud-director/pull/127
- [ ] https://github.com/giantswarm/default-apps-cloud-director/pull/128
- [ ] https://github.com/giantswarm/default-apps-cloud-director/pull/145
- [ ] https://github.com/giantswarm/cluster-cloud-director/pull/146
- [ ] https://github.com/giantswarm/cluster-cloud-director/pull/202
- [x] https://github.com/giantswarm/giantswarm/issues/27941
```

```[tasklist]
### CAPV
- [ ] https://github.com/giantswarm/vsphere-app-collection/pull/46
- [ ] https://github.com/giantswarm/cluster-api-provider-vsphere-app/pull/56
- [ ] https://github.com/giantswarm/cluster-api-provider-vsphere-app/pull/58
- [ ] https://github.com/giantswarm/config/pull/1792
- [ ] https://github.com/giantswarm/vsphere-app-collection/pull/40
- [ ] https://github.com/giantswarm/default-apps-vsphere/pull/85
- [ ] https://github.com/giantswarm/default-apps-vsphere/pull/84
- [ ] https://github.com/giantswarm/cluster-vsphere/pull/58
- [ ] https://github.com/giantswarm/cluster-api-provider-vsphere-app/pull/72
```

For CAPV: `cluster-vsphere@v0.5.0` + `default-apps-vsphere@v0.9.2`

## 🚧  Notes 🚧

```
Towards https://github.com/giantswarm/giantswarm/issues/23014
Towards https://github.com/giantswarm/roadmap/issues/1949
```

**Comment by gawertm** [comment]
should wait until we have a stable test MC running in Panamax environment

**Comment by kopiczko** [comment]
I've read trough the linked issue and it seems to me that this is more involved than I initially though. IIUC we'll need to prepare all apps running in WCs and MCs to be equipped with `CiliumNetworkPolicy` CRs with a switch value `.Values.ciliumNetworkPolicy.enabled`.

When all apps are ready we'll need to to set `.ciliumNetworkPolicy.enabled` for each of those apps in `giantswarm/config`, `default-apps-<provider>` and finally `cluster-<provider>` (but I guess for the provider specific apps we don't need on/off switch).

When all apps are ready we'll need to set `.Values.defaultPolicies.enabled: false` for `cilium-app` in `cluster-provider`.

**Comment by kopiczko** [comment]
Small correction: we only need to add a `CiliumNetworkPolicy` to the chart if it needs `NetworkPoilicy` with `ipBlock.cidr` set to the cluster network.

**Comment by kopiczko** [comment]
I created a locked CAPV WC and it looks ok (draft PR here https://github.com/giantswarm/cluster-vsphere/pull/58)

**Comment by kopiczko** [comment]
Check this comment https://github.com/giantswarm/giantswarm/issues/23014#issuecomment-1542637599

**Comment by kopiczko** [comment]
I was able to successfully run mc-bootstrap with those PRs:

- https://github.com/giantswarm/cluster-api-app/pull/132
- https://github.com/giantswarm/cluster-api-provider-vsphere-app/pull/56
- https://github.com/giantswarm/mc-bootstrap/pull/536

**Comment by kopiczko** [comment]
Those are the pods that still have issues on the MC:

```
giantswarm          dex-77f858b47f-89qmb                                              0/1     CrashLoopBackOff        171 (2m46s ago)   14h
giantswarm          dex-77f858b47f-8g6mx                                              0/1     CrashLoopBackOff        171 (87s ago)     14h
giantswarm          trivy-0                                                           0/1     CrashLoopBackOff        202 (2m20s ago)   14h
kube-system         cert-manager-cainjector-5bc656c896-jjqpv                          0/1     CrashLoopBackOff        154 (2m24s ago)   14h
kube-system         metrics-server-56994fccc6-shx59                                   0/1     CrashLoopBackOff        277 (4m45s ago)   14h
kube-system         net-exporter-5q8cs                                                0/1     Init:CrashLoopBackOff   113 (3m51s ago)   14h
kube-system         net-exporter-chrtp                                                0/1     Init:CrashLoopBackOff   113 (5m8s ago)    14h
kube-system         net-exporter-vnpj8                                                0/1     Init:CrashLoopBackOff   113 (3m54s ago)   14h
kube-system         net-exporter-wl5rq                                                0/1     Init:0/1                114 (5m49s ago)   14h
kube-system         net-exporter-x9jjg                                                0/1     Init:CrashLoopBackOff   113 (3m50s ago)   14h
kube-system         net-exporter-xk7c8                                                0/1     Init:CrashLoopBackOff   113 (4m29s ago)   14h
kube-system         vpa-remove-crd-ownership--1-n9k5k                                 0/2     Error                   0                 3m36s
```

**Comment by kopiczko** [comment]
cluster-api-app PR in review: https://github.com/giantswarm/cluster-api-app/pull/132

**Comment by kopiczko** [comment]
default-apps-vpshere PR also in review: https://github.com/giantswarm/default-apps-vsphere/pull/84

**Comment by kopiczko** [comment]
cluster-api-provider-vsphere-app PR in review: https://github.com/giantswarm/cluster-api-provider-vsphere-app/pull/56

I think that are all app PRs for CAPV. I'll need to think how to deal with mc-bootstrap and config management.

**Comment by kopiczko** [comment]
I forgot about cluster-vsphere, also in reiview: https://github.com/giantswarm/cluster-vsphere/pull/58

**Comment by kopiczko** [comment]
I started a little discussion on the UX side of things:

Github: https://github.com/giantswarm/giantswarm/issues/23014#issuecomment-1550221327
Slack: https://gigantic.slack.com/archives/C01F7T2MNRL/p1684264630519339

**Comment by kopiczko** [comment]
**Installations migration**

At some point we'll have to enable CiliumNetworkPolicy CRs in `cluster-api-app` and `cluster-api-provider-<provider>` like this:

```yaml
ciliumNetworkPolicy:
  enabled: true
```

This has to be set in the `config` repository.

For `cluster-api-provider-<provider>` we can simply add that in `default/apps/cluster-api-provider-<provider>/configmap-values.yaml.template`.

For `cluster-api` we'll need to introduce it gradually, provider by provider guarded by `{{- if eq .provider.kind "<provider>" }}` statements.

During the migration if necessary we can overwrite those settings for the existing clusters. E.g. for `cluster-api` in `guppy` it would be overwrite in `installations/guppy/apps/cluster-api/configmap-values.yaml.patch`.

**Comment by kopiczko** [comment]
Done for CAPV in `cluster-vsphere@v0.5.0` and `default-apps-vsphere@v0.9.2` (+ the latest `mc-bootstrap`).

**Comment by kopiczko** [comment]
While working on CAVCD I'm thinking that clouid-provider-vsphere-app may be silently not working. I'll need to check that. I added this to the list of tasks.

**Comment by kopiczko** [comment]
I started to run into strange cases, and figured this is because of mixture of default cilium policy enforcement mode and lack of deny-all policies, more details in Slack: https://gigantic.slack.com/archives/C01F7T2MNRL/p1686312565475639

**Comment by kopiczko** [comment]
Last week I was still fighting aftermath of CMC repo split and got kyverno to work on locked down clusters (this was blocking everything because of failing webhook) + some minor tweaks to mc-bootstrap.

**Comment by kopiczko** [comment]
This is all tested for CAPVCD and released in cluster-cloud-director@0.13.0 + default-apps-cloud-director@0.5.4.

I opened a PR to upgrade `leopard`.

**Comment by glitchcrab** [comment]
@kopiczko once you've upgraded leopard, can you delete this please? https://github.com/giantswarm/silences/pull/1160

**Comment by kopiczko** [comment]
I realised leopard is quite a production cluster so everything needs to work. So I added CNPs to falco and cluster-api-monitoring apps and configured and released them. I'm still fighting with cert-manager v3. The major blocker now is proxy variables. See https://gigantic.slack.com/archives/C02GLN41UP2/p1691577989607199

**Comment by kopiczko** [comment]
Finally.

**Comment by kopiczko** [comment]
Issue about default-deny-all policies in WCs https://github.com/giantswarm/roadmap/issues/2815

**Comment by kopiczko** [comment]
>  Do you have any concerns for changing mc-bootstrap and cluster-* repos to set .Values.defaultPolicies.enabled: false?

Let's do that.
