### ISSUE TITLE
Update mc-bootstrap cleanup script to remove leftover AWS resources

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#1951]
## Task

Update `mc-bootstrap` cleanup script to remove leftover AWS resources.

The following resources were not removed by the cleanup script:
- [ ] Route53 hosted zones for thor;
- [x] RAM resource for resolver rule shared with NOC;
- [x] Resolver rule associations;
- [x] EBS volumes from StatefulSets such as prometheus, alert-manager;
- [x] ASG group - def00b;
- [x] TGW attachments;

## Links

- [thor MC recreation wiki](https://github.com/giantswarm/mc-bootstrap/wiki/Feb,-2023:-Recreate-thor).

**Comment by fiunchinho** [comment]
RAM resources https://github.com/giantswarm/mc-bootstrap/pull/417

**Comment by fiunchinho** [comment]
Resolver rule associations https://github.com/giantswarm/mc-bootstrap/pull/418/files

**Comment by fiunchinho** [comment]
I don't think we have to do anything else for ASGs, I believe it worked fine last time.

**Comment by fiunchinho** [comment]
Transit Gateway attachments https://github.com/giantswarm/mc-bootstrap/pull/419

**Comment by tuladhar** [comment]
EBS volumes https://github.com/giantswarm/mc-bootstrap/pull/420

**Comment by tuladhar** [comment]
#### Route53 cleanup can be achieved as such, but it's overly complicated as I see it.

Step 1. Get hosted zone ID based on $installation name
```
$ aws route53 list-hosted-zones --query "HostedZones[?starts_with(Name, `thor`)]"
```
Output:
```
[
    {
        "Id": "/hostedzone/Z03601371521LQZXLPWLJ",
        "Name": "thor.eu-central-1.aws.tkp.hdi.cloud.",
        "CallerReference": "2023-02-07 08:41:50.817967383 +0000 UTC",
        "Config": {
            "PrivateZone": true
        },
        "ResourceRecordSetCount": 7
    }
]
```

Step 2. Generate DELETE change set for all the resources for the hosted zone ID (exclude NS and SOA record)
```
aws route53 list-resource-record-sets \
                                      --hosted-zone-id "/hostedzone/Z05593223OZF1J4ODY8KY" \
                                      --max-items 10000 \
                                      --output json | jq --compact-output '[.ResourceRecordSets[] |
                                  {Action: "DELETE", ResourceRecordSet: {Name: .Name, Type: .Type, AliasTarget: .AliasTarget}}] |
                                  _nwise(1) |
                                  {Changes: .}' | grep -Ev '"Type":"NS|SOA"'
```
Output:
```
{"Changes":[{"Action":"DELETE","ResourceRecordSet":{"Name":"puru-example.com.","Type":"NS","AliasTarget":null}}]}
{"Changes":[{"Action":"DELETE","ResourceRecordSet":{"Name":"puru-example.com.","Type":"SOA","AliasTarget":null}}]}
{"Changes":[{"Action":"DELETE","ResourceRecordSet":{"Name":"www.puru-example.com.","Type":"A","AliasTarget":null}}]}
```

Step 3. Split each change-set line into individual file using `split -l 1`
```
echo "Step 3. Output" | split -l 1
```
Output
```
$ cat xaa xab xac
{"Changes":[{"Action":"DELETE","ResourceRecordSet":{"Name":"puru-example.com.","Type":"NS","AliasTarget":null}}]}
{"Changes":[{"Action":"DELETE","ResourceRecordSet":{"Name":"puru-example.com.","Type":"SOA","AliasTarget":null}}]}
{"Changes":[{"Action":"DELETE","ResourceRecordSet":{"Name":"www.puru-example.com.","Type":"A","AliasTarget":null}}]}
```

Step 4. Delete the record using the change-set file:
```
for file in x*; do
  aws route53 change-resource-record-sets \
  --hosted-zone-id=${hostedzoneid} \
  --change-batch=file://${file}
done
```

**Comment by fiunchinho** [comment]
I'd leave it out of the clean script and call this done.
