### ISSUE TITLE
Offering Managed Crossplane

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1971]
Status quo: deployed Crossplane on MCs for interested customer in early (experimental) access.

## TODO

Objective: enable customers to deploy externally managed secrets into K8s MCs

Tentative implementation plan:

```[tasklist]
### Tasks
- [x] deployed Crossplane on MCs for interested customer in early (experimental) access
- [ ] https://github.com/giantswarm/giantswarm/issues/25356
- [ ] https://github.com/giantswarm/giantswarm/issues/25156
- [x] Create an official issue in cp's repo about performance issues
- [ ] https://github.com/giantswarm/roadmap/issues/1946
- [ ] https://github.com/giantswarm/roadmap/issues/1906
- [ ] https://github.com/giantswarm/roadmap/issues/2056
- [ ] https://github.com/giantswarm/roadmap/issues/2061
- [ ] https://github.com/giantswarm/roadmap/issues/1929
- [ ] https://github.com/giantswarm/roadmap/issues/1947
- [ ] https://github.com/giantswarm/roadmap/issues/1972
- [x] clean up encryption secrets in MCF so it's easier to add new Secret data
- [x] disable leader election in crossplane
- [x] add `projected` to allowed volumes types in PSP
- [ ] https://github.com/giantswarm/roadmap/issues/2087
- [ ] https://github.com/giantswarm/roadmap/issues/2097
- [ ] https://github.com/giantswarm/roadmap/issues/2101
```

**Comment by piontec** [comment]
We need to wrap up our crossplane effort. We decided to go with the opt-in approach, with appropriate disclaimers. 

Continuation ticket is managed here: https://github.com/giantswarm/roadmap/issues/1905
