### ISSUE TITLE
Offering Managed Weave GitOps UI

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#1973]
```[tasklist]
### Tasks
- [x] https://github.com/giantswarm/roadmap/issues/1821
- [ ] https://github.com/giantswarm/roadmap/issues/1942
- [x] Define and implement Weave GitOps UI app deployment
- [ ] https://github.com/giantswarm/roadmap/issues/2241
- [ ] Weave GitOps UI - first iteration on docs
- [ ] Weave GitOps UI announcement
```

**Comment by piontec** [comment]
Ping @weatherhog , once we confirm the RBAC issue is fixed, let's announce availability to our customers.

**Comment by mproffitt** [comment]
This can be closed as not achievable
