### ISSUE TITLE
SPIKE: explorate external-dns for MC specific ingress services

### ISSUE THREAD

**Issue by bavarianbidi** [giantswarm/roadmap#1974]
### Motivation

To use as many upstream solutions as possible we should concider if `external-dns` could take over the dns-record creation for all servicces which got covered by the `*` CNAME record pointing to `ingress.<clusterName>.<baseDomain>`.

This could help to limit the scope of `dns-operator-azure` and could be a blue-print for other providers as well as we could remove a bunch of LoCs we have done by our own.

### Todos

- [x] configure and deploy `external-dns`
- [x] configure the relevant ingress services that `external-dns` take over dns record creation
- [x] get in contact with cabbage
- [ ] share result within KaaS

### Outcome

We've prepared a list of Pros and Cons about that implementation and could argue the impact of that implementation to other KaaS-Teams.

**Comment by bavarianbidi** [comment]
* the current state is documented [here](https://github.com/giantswarm/roadmap/issues/1037#issuecomment-1431037446)
* a list of possible follow up tasks is defined [here](https://github.com/giantswarm/roadmap/issues/1037#issuecomment-1431431676)
* the slack discussion is [here](https://gigantic.slack.com/archives/C01F7T2MNRL/p1676471096489559?thread_ts=1676300937.018959&cid=C01F7T2MNRL)

With that i will close this issue for now and once we get clearance we can decide how to continue.
