### ISSUE TITLE
metrics endpoint for dns-operator-azure

### ISSUE THREAD

**Issue by bavarianbidi** [giantswarm/roadmap#1976]
### Motivation

To improve day-2 operation we should expose a metrics-endpoint for `dns-operator-azure` and provide useful metrics for daily business. 

### Todo

```[tasklist]
- [x] define some business functional metrics
- [x] enable `/metrics` endpoint
- [x] configure prometheus for metrics scraping
- [ ] if needed/possible, create some alerts to get known about issues with the operator
```

#### possible business functional metrics
- `info` metric per cluster and record kind
- expiration date of the client-secret
- Error count

### Outcome

`dns-operator-azure` provides a `/metric` endpoint and metrics got scraped by the corresponding prometheus instance.
Beside the generic go metrics (memory, fd, ...) and the out-of-the box kubebuilder relevant metrics we also expose metrics about the business functionality in general

**Comment by bavarianbidi** [comment]
The service principal expiration date will be covered by https://github.com/giantswarm/azure-collector

```
azure_operator_service_principal_token_expiration{application_name=~".*dns-operator-azure"}
```

https://gigantic.slack.com/archives/C04887ZSU20/p1681807641800669

**Comment by bavarianbidi** [comment]
all PRs got merged and will be released soon
