### ISSUE TITLE
Setup new internal testing infrastructure

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#1986]
## Details, Background

We need to setup a new testing infrastructure and define the processes required for teams to be able to run tests on it.

```[tasklist]
- [ ] https://github.com/giantswarm/giantswarm/issues/25492
- [ ] https://github.com/giantswarm/giantswarm/issues/25499
- [ ] https://github.com/giantswarm/giantswarm/issues/25598
- [ ] https://github.com/giantswarm/giantswarm/issues/25599
- [ ] https://github.com/giantswarm/giantswarm/issues/25494
- [ ] https://github.com/giantswarm/giantswarm/issues/25639
- [ ] https://github.com/giantswarm/giantswarm/issues/25551
- [ ] https://github.com/giantswarm/giantswarm/issues/25503
- [ ] https://github.com/giantswarm/giantswarm/issues/25531
- [ ] https://github.com/giantswarm/giantswarm/issues/25613
- [ ] https://github.com/giantswarm/giantswarm/issues/25546
- [ ] https://github.com/giantswarm/giantswarm/issues/25547
- [ ] https://github.com/giantswarm/giantswarm/issues/25548
- [ ] https://github.com/giantswarm/roadmap/issues/2079
- [ ] https://github.com/giantswarm/giantswarm/issues/25537
- [ ] https://github.com/giantswarm/giantswarm/issues/25539
- [ ] https://github.com/giantswarm/giantswarm/issues/25497
- [ ] https://github.com/giantswarm/giantswarm/issues/25533
- [ ] https://github.com/giantswarm/giantswarm/issues/25595
- [ ] https://github.com/giantswarm/giantswarm/issues/25596
- [ ] https://github.com/giantswarm/giantswarm/issues/25536
- [ ] https://github.com/giantswarm/giantswarm/issues/25543
- [ ] https://github.com/giantswarm/giantswarm/issues/25550
- [ ] https://github.com/giantswarm/giantswarm/issues/25549
- [ ] https://github.com/giantswarm/giantswarm/issues/25552
- [ ] https://github.com/giantswarm/giantswarm/issues/25554
- [ ] https://github.com/giantswarm/giantswarm/issues/25555
- [ ] https://github.com/giantswarm/giantswarm/issues/25570
- [ ] https://github.com/giantswarm/giantswarm/issues/25569
```

**Comment by yulianedyalkova** [comment]
Closing this one as the initial work has been done, new features will come on demand.
