### ISSUE TITLE
cert-manager: Align to upstream

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2000]
Attention: This is a default app!

Our version of cert-manager distinguishes from upstream cert-manager. We should get this back on track and align cert-manager to upstream. 
This will help with features and updates in the future.

-----------------

### Decisions

- Installation of cluster issuer required by giantswarm infrastructure will be installed as a post install hook
- What happens with Configuration.md - probably needs to be newly created
- there are significant differences in the values.yaml
  - make sure the default config is somehow kept the same
  - check existing user-values and maintain compatibility or provide an upgrade path (possibly automated)

----------------

```[tasklist]
### Tasks
- [x] Setup vendir in new branch
- [x] Diff vendir branch and current main
- [ ] Make a list of GS requirements for cert-manager as a default app
- [ ] For each item on the GS requirements list document how it's implemented
- [x] Align Selector Labels
```

---------------
### GS requirements
- How Handle CRDs? - Currently we're using a pre install job to install CRDs outside of the helm lifecycle. Upstream handles this with `installCRDs` for which the template is built when packaging the app. So it's not available in upstream fork. Possibly change upstream fork sync to get upstream master form chart instead of git repo.
-

**Comment by ced0ps** [comment]
### List of GS requirements
- [ ] Cilium network policies [PR](https://github.com/giantswarm/cert-manager-app/pull/301)
- [ ] control-plane toleration [PR](https://github.com/giantswarm/cert-manager-app/pull/302)
- [ ] default irsa role for cert-manager-controller [PR](https://github.com/giantswarm/cert-manager-app/pull/295)

**Comment by ced0ps** [comment]
Create a sub-chart for any changes that are giantswarm specific and will never be contributed upstream.
This is limited to discrete resources as existing templates can't be replaced by ones from a sub-chart.

**Comment by ced0ps** [comment]
We would like to remove business logic from the cert-manager chart to have it as close to upstream as possible.
For CAPI clusters we can use `default-app-*` to configure the provider specific values.

What can we do for vintage clusters, that use `cert-manager` and currently rely on business logic inside the cluster to e.g. ServiceAccounts with the correct AWS-roles annotation?
RCF @giantswarm/team-phoenix 

For reference:
> As we're currently aligning cert-manager with upstream, we're trying to get rid of business logic inside the app chart. I learned about the default-app-* repos which we can use to configure the required serviceAccount annotation (e.g. for configuring IRSA) for capi clusters so that is probably fine.
For vintage context: How do we handle backwards compatibility in these cases?
The version of cert-manager is fixed for a given release.
I can think of two scenarios where this could become an issue:
Customer needs to upgrade cert-manager because they require a feature or bug fix
this could be mitigated by just supplying the required config as user-config
We're releasing a new version of a vintage cluster which uses the newest version of cert-manager
Theoretically this could be mitigated by providing the required config params with the cluster-operater provided values. (Not sure if it's even possible to update a default app. How does cluster-operator reconcile that?)
if a different app by chance uses the same .Values.config.path this could cause issues

[From slack thread](https://gigantic.slack.com/archives/C01F7T2MNRL/p1685622370093739)

**Comment by ced0ps** [comment]
cert-manager-app v3.0.0 will be a CAPI first app. Business logic will be removed from the core chart.

**Comment by ubergesundheit** [comment]
Regarding CRDs:

Current release family v2.x.x contains a pre-install/pre-upgrade hook which uses a Job to install CRDs. This means
- CRDs are installed without helm ownership annotations 
- Removing the cert-manager chart does not remove the CRDs
- CRs are not removed because CRDs are not removed

The upstream chart includes CRDs as part of regular templates which means on uninstall all CRs are removed because CRDs are removed.

For now (as of https://github.com/giantswarm/cert-manager-app/pull/316/commits/acfffffad5d96c284a00b952bd21bcac00d1acca) upgrading from v2.x.x to v3.x.x is not possible because the new chart does not recognize the old CRDs and cannot apply/update them)

```
Deployment failed for `2.22.0-acfffffad5d96c284a00b952bd21bcac00d1acca`
    with `already-exists`: `resource already exists: (rendered manifests contain a
    resource that already exists. Unable to continue with update: CustomResourceDefinition
    "certificaterequests.cert-manager.io" in namespace "" exists and cannot be imported
    into the current release: invalid ownership metadata; annotation validation error:
    missing key "meta.helm.sh/release-name": must be set to "cert-manager"; annotation
    validation error: missing key "meta.helm.sh/release-namespace": must be set to
    "kube-system")
```

We have to decide:

- Do we want the CR deletion behaviour of upstream

We have to solve:

- How to adopt existing CRDs based on the strategy decided above. Removing CRDs during upgrade should not happen IMO

**Comment by ubergesundheit** [comment]
Next problem seem to be resource names and labels. Our chart uses name `cert-manager-controller` for the main Deployment while upstream simply uses `cert-manager`. 

Upstream also defines different `spec.selector` labels. This is an immutable field in many resources. So either we try to bend labels to match previous ones, don't offer an upgrade path at all (requiring uninstall + reinstall) or try to hack something with a pre-upgrade hook job.

**Comment by ubergesundheit** [comment]
CRDs:

We decided to release another v2.x.x chart version with the required helm adoption labels. This allows installation of v3

Selector Labels:

 We were able to bend upstream selector labels to match ours


Next steps:

- Test and Merge https://github.com/giantswarm/cert-manager-app/pull/316 This will ensure v3.x.x chart can be installed.
- Release a new v2 cert-manager-app version and request it in upcoming platform release

**Comment by ubergesundheit** [comment]
[Released](https://github.com/giantswarm/cert-manager-app/releases/tag/v2.24.0) and [requested](https://github.com/giantswarm/releases/pull/1137) changes in https://github.com/giantswarm/cert-manager-app/pull/331

**Comment by ubergesundheit** [comment]
closing this, v3.0.0 has been released 🎉
