### ISSUE TITLE
SLO alerting

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2006]
## User Story

As a Giant Swarm engineer I want to to be able to express my Service Level Objectives into some alert definition and therefore benefit from reliable alerting on components I am responsible for.

```[tasklist]
### Tasks
- [x] https://github.com/giantswarm/roadmap/issues/1478
- [x] https://github.com/giantswarm/roadmap/issues/1966
- [x] https://github.com/giantswarm/roadmap/issues/1959
- [ ] https://github.com/giantswarm/roadmap/issues/2154
- [ ] https://github.com/giantswarm/giantswarm/issues/26771
- [ ] https://github.com/giantswarm/roadmap/issues/2394
- [ ] https://github.com/giantswarm/giantswarm/issues/26931
- [ ] https://github.com/giantswarm/roadmap/issues/2558
- [ ] https://github.com/giantswarm/roadmap/issues/2570
- [ ] https://github.com/giantswarm/roadmap/issues/2579
- [ ] https://github.com/giantswarm/giantswarm/issues/27936
- [ ] https://github.com/giantswarm/giantswarm/issues/28987
- [ ] https://github.com/giantswarm/giantswarm/issues/28988
- [ ] https://github.com/giantswarm/giantswarm/issues/28990
- [ ] https://github.com/giantswarm/giantswarm/issues/28989
```

### Related issues

- https://github.com/giantswarm/giantswarm/issues/22643
- https://github.com/giantswarm/giantswarm/issues/28751

**Comment by TheoBrigitte** [comment]
Source of truth for services managed by `ServiceLevelBurnRateTooHigh`
[`sum(raw_slo_requests)by(service,label_application_giantswarm_io_team)`](https://prometheus.g8s.anteater.dub.aws.k8s.3stripes.net/anteater/graph?g0.expr=sum(raw_slo_requests)by(service%2Clabel_application_giantswarm_io_team)&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h)

![image](https://github.com/giantswarm/giantswarm/assets/6536819/a0bd68ae-b764-453a-8d45-26745db54646)


TODO: check on WC

**Comment by QuentinBisson** [comment]
This issue should be handled as part of https://github.com/giantswarm/roadmap/issues/3312
