### ISSUE TITLE
CAPZ Private Network Configuration for Clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2012]
### Motivation
Our customers want to be able to create clusters secured with a private network configuration. This makes sure, that there is at least no public ip available, so that there would be no public internet ingress/egress traffic on those clusters. 

### Todo

```[tasklist]
### Investigation
- [x] https://github.com/giantswarm/roadmap/issues/864
- [ ] https://github.com/giantswarm/giantswarm/issues/24762
- [ ] https://github.com/giantswarm/giantswarm/issues/25773
```

```[tasklist]
### Implementation
- [ ] https://github.com/giantswarm/roadmap/issues/2039
- [ ] https://github.com/giantswarm/roadmap/issues/2040
- [ ] https://github.com/giantswarm/roadmap/issues/2041
- [ ] https://github.com/giantswarm/roadmap/issues/2021
- [ ] https://github.com/giantswarm/roadmap/issues/1620
- [ ] https://github.com/giantswarm/roadmap/issues/1927
- [ ] https://github.com/giantswarm/roadmap/issues/1740
- [ ] https://github.com/giantswarm/roadmap/issues/2376
- [ ] https://github.com/giantswarm/roadmap/issues/2403
- [ ] https://github.com/giantswarm/roadmap/issues/2528
- [ ] https://github.com/giantswarm/roadmap/issues/2722
- [ ] https://github.com/giantswarm/roadmap/issues/2675
```

```[tasklist]
### Customer Related
- [ ] https://github.com/giantswarm/continental/issues/34
```

### Outcome
The outcome of this epic is to have the option to create clusters with a network configuration preset that they are publicly available but also completely privately protected with our capz-management cluster.
