### ISSUE TITLE
Update Customer Documentation with CAPZ

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2013]
### Motivation
Customers should know how to work with our clusters not just from asking. CAPA has a short [getting-started with capa workload clusters](https://docs.giantswarm.io/getting-started/capa-wlcluster-creation/) document in the public GS documentation space. This can also be pretty helpful for customers interested in CAPZ Installations, especially with the specific private network first setup we have in mind. 

### Todo

- [x] Create a new Getting Started Documentation with the topic "Create a cluster using cluster API in Azure (CAPZ)"
- [x] Explain how to create an example workload cluster.
- [x] Shortly explain the difference between a public and private workload cluster mode and how to configure it.

### Outcome
- Customers can read up how to create a workload cluster in their CAPZ Installations in our public GS Getting Started Documentation.
- Customers can read up what the different configurations between private and public network clusters are.

**Comment by bavarianbidi** [comment]
Documentation got merged and published:
https://docs.giantswarm.io/getting-started/capz-cluster-creation/
