### ISSUE TITLE
Make Loki chart deploy a usable High Availability (HA) setup

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#202]
**Is your feature request related to a problem? Please describe.**

Customer has 2 instances of Loki running, each with its own PV (because they need to use `ReadWriteOnce` due to Azure restrictions). When customer executes a query in Grafana, **the results differ depending on which instance of Loki is used**.

Customer wants to use HA, but the current helm chart only supports one Loki and no HA.

**Describe the solution you'd like**

Make Loki chart deploy a usable High Availability (HA) setup

**Describe alternatives you've considered**

* Best if customer can cope with just one Loki for now
* Customer will try to set the retry policy of promtail

**Additional context**

[Slack Discussion](https://gigantic.slack.com/archives/CR99LSZ1N/p1601631850113600)

## Tasks list
- [ ] Loki
  - [ ] must-do
    - [x] setup repo
    - [x] adjust upstream chart to work on our cluster
    - [x] describe how to setup and prepare AWS infra
    - [x] clean and merge upstream patches
    - [x] retagger - copy images
    - [x] add docs
    - [x] create build files for chart to be pushed into catalog
    - [x] `compactor` config complains about something - doesn't work
    - [x] test: receive logs from promtail
    - [x] test: use from grafana
    - [ ] setup monitoring
    - [x] switch to HTTPS
    - [x] enable at least basic auth
    - [x] do first official release
    - [x] create public domain alias like `loki.giantswarm.io`
    - [ ] define and configure resource limits
  - [ ] nice-to-have
      - [ ] generate values.schema.yaml
      - [ ] check ingress setup - security for external customers
        From Manuel:
        > you could use the auth-url annotation to authenticate the user against "some" service under your control and also auth- 
     response-headers to pass any additional header to the backend (X-Scope-OrgID) that is returned by your auth service
    https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#external-authentication
        > you could also use oauth2-proxy and add some additional logic, like this example (is an issue, but you can get an idea) https://github.com/oauth2-proxy/oauth2-proxy/issues/969
- [ ] Promtail
  - [ ] must-do
    - [x] setup repo
    - [x] adjust config for a reasonable index
    - [x] retag images
    - [x] add docs
    - [x] adjust chart and make it work with pure helm
    - [x] create build files for chart to be pushed into catalog
    - [ ] define and configure resource limits
  - [ ] nice-to-have
    - [ ] generate values.schema.yaml
- [x] grafana
  - [x] nice-to-have
    - [x] switch the chart update method to git-subtree
    - [x] update to recent version

**Comment by piontec** [comment]
Updated status as for 15.01.2021

**Comment by piontec** [comment]
status updated: 2021.01.22

**Comment by piontec** [comment]
status updated: 2021.01.27

**Comment by cokiengchiara** [comment]
@giantswarm/app-squad-loki How does the Loki cycle issue https://github.com/giantswarm/roadmap/issues/266 relate to this one?

Ideally, we can move info from this one to that one, and then close this one.

**Comment by piontec** [comment]
We can call id done, our setup is HA, we might need to smooth out some rough edges.

**Comment by cokiengchiara** [comment]
Moving to archive. Docs and comms should be done in https://github.com/giantswarm/roadmap/issues/266
