### ISSUE TITLE
Recreate Glippy CAPZ MC 

### ISSUE THREAD

**Issue by primeroz** [giantswarm/roadmap#2021]
### Motivation
Related to https://github.com/giantswarm/roadmap/issues/2011

Recreate Glippy MC so we can proceed with the private WC implementation

### TODO
- [x] Check the `glippy` auto branches for any change that might need to go in Main before recreating glippy
- [x] Delete `all Workload clusters` on glippy
- [x] Delete `glippy` resource group from Azure console
- [x] Delete all the `glippy auto branches`, `lastpass secrets` 
- [x] Update the `default secrets` in lastpass to match changes that were done to the `values.yaml` of cluster Azure
- [x] Deploy _new_ glippy
  - [x] Add custom ranges for network CIDRs at `make create-config` step 
- [x] Check Network Ranges 
- [x] Test Bastion 
- [x] Test create WC Cluster 
- [ ] Create FollowUp Issues - https://github.com/giantswarm/roadmap/issues/2021#issuecomment-1431527912
- [x] Merge MC-BOOTSTRAP changes - https://github.com/giantswarm/mc-bootstrap/pull/410
### Outcome

**For Clippy**
- glippy is running with the required spec to proceed with the WC private cluster implementation

**Comment by primeroz** [comment]
### config repo changes to push 

The following need to be added to `mc-bootstrap` since they cannot be moved to the default since that would affect vintage clusters 

* azure-ad-pod-identity config - https://github.com/giantswarm/config/compare/main...glippy_auto_config#diff-c02b3d326d62298d1be6c712f6eaaabe09020ef825551d03512ba829dd8c4a8f
* cluster-api-provider-azure - https://github.com/giantswarm/config/compare/main...glippy_auto_config#diff-7a38e4e91e01ad49782f7890d66706b6bc2d8e574b7ef6d44818fe581b662af9

**Comment by nprokopic** [comment]
Coming from this comment https://github.com/giantswarm/roadmap/issues/2011#issuecomment-1430034809

I would like that we "reserve" `10.223.0.0/16` in our VPN for CAPZ MCs (+WCs), which is /16 range that comes before CAPA goat. That should give us 16 MCs (+WCs) with 10.223.x.0/20 shared range, which I hope we won't have to use and that we will sooner move to a more scalable solution with private endpoints (or similar).

That being said, for glippy and its MCs, we would use:
- `10.223.0.0/20` as a shared range for glippy VPN connection (this should accommodate glippy MC and all glippy WCs)
- `10.223.0.0/24` for glippy VNet, which would then break down into
  - `10.223.0.0/25` for workers subnet

**Comment by primeroz** [comment]
Ok, once the PR is merged we will create a new release for cluster-azure and , on glippy recreation, set 

* .Values.connectivity.network.hostCidr = 10.233.0.0/24
* .Values.connectivity.network.controlPlane.cidr = 10.233.0.128/26
* .Values.connectivity.network.workers.cidr = 10.223.0.0/25

We currently don't support creating extra subnets in the network spec https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/templates/_azure_cluster.tpl#L16 

so for now we'll stick to this and get the bastion on the control plane subnet

**Comment by nprokopic** [comment]
Slightly updated comment above, added missing calculation (I hit ctrl-enter accidentally :grimacing:)

**Comment by primeroz** [comment]
### Follow Up Issues

* webhook is not validating , at lest, CAPI resources
* during bootstrap the `wait for` on the bastion host fails
```
kubectl --kubeconfig=./kubeconfigs/kind-mc-initial-glippy.kubeconfig wait --timeout=20m '--for=jsonpath={.status.phase}=Running' -n org-giantswarm [machine.cluster.x-k8s.io/glippy-bastion-86cb948f85-h9lgk](http://machine.cluster.x-k8s.io/glippy-bastion-86cb948f85-h9lgk)

➜ kubectl --kubeconfig=./kubeconfigs/kind-mc-initial-glippy.kubeconfig get -n org-giantswarm [machine.cluster.x-k8s.io/glippy-bastion-86cb948f85-h9lgk](http://machine.cluster.x-k8s.io/glippy-bastion-86cb948f85-h9lgk) -o yaml | yq .status.phase
Provisioned

While for MD machines it is indeed Running
```

**Comment by primeroz** [comment]
### Test Create WC Cluster
```

```

```
NAME                                     INSTALLED VERSION   CREATED AT   LAST DEPLOYED   STATUS
fctest1                                  0.0.11              7m11s        7m11s           deployed
fctest1-app-operator                     6.4.2               7m7s         6m48s           deployed
fctest1-azure-cloud-controller-manager   1.24.6-gs1          3m31s        2m42s           deployed
fctest1-azure-cloud-node-manager         1.24.6-gs1          3m31s        3m22s           deployed
fctest1-azuredisk-csi-driver             1.26.2-gs1          3m31s        3m24s           deployed
fctest1-cert-exporter                    2.3.1               3m31s        2m44s           deployed
fctest1-chart-operator                   2.33.0              7m6s         3m29s           deployed
fctest1-cilium                           0.6.1               3m31s        3m20s           deployed
fctest1-coredns                          1.13.0              3m31s        2m43s           deployed
fctest1-default-apps                     0.0.11              7m11s        3m31s           deployed
fctest1-kube-state-metrics               1.14.2              3m31s        43s             deployed
fctest1-metrics-server                   2.0.0               3m31s        3m21s           deployed
fctest1-net-exporter                     1.13.0              3m31s        2m42s           deployed
fctest1-node-exporter                    1.15.0              3m31s        43s             deployed
fctest1-observability-bundle             0.1.9               3m31s        3m29s           deployed
fctest1-prometheus-agent                                     3m29s                        secret-merge-failed
fctest1-prometheus-operator-app          3.0.0               3m29s        40s             deployed
fctest1-prometheus-operator-crd          3.0.0               3m29s        42s             deployed
fctest1-vertical-pod-autoscaler          2.5.3               3m31s        2m39s           deployed
fctest1-vertical-pod-autoscaler-crd      1.0.1               3m31s        2m43s           deployed
```

```
➜ kubectl --kubeconfig /dev/shm/fctest1 get node    
NAME                                   STATUS   ROLES           AGE   VERSION
fctest1-control-plane-c17c01d5-strjq   Ready    control-plane   2m    v1.24.10
fctest1-md00-22b81e6f-5bjt9            Ready    <none>          54s   v1.24.10
fctest1-md00-22b81e6f-5xfmr            Ready    <none>          55s   v1.24.10
fctest1-md00-22b81e6f-bzr8z            Ready    <none>          58s   v1.24.10

➜ kubectl --kubeconfig /dev/shm/fctest1 get pod -A | grep -v Running | grep -v Completed
NAMESPACE     NAME                                                            READY   STATUS    RESTARTS   AGE

```

**Comment by primeroz** [comment]
* PMO needs some work to handle when the `node allocatable` is not an integer ( like in our case is `3880` ) which is causing the prometheus OOMING ( because vpa for prometheus fails to install) and possibly also the lack of heartbeat

**Comment by primeroz** [comment]
* vpa patch pod failing
this is happening because the name of the chart is `wrong` compared to what the job expects 

https://gigantic.slack.com/archives/C02GDJJ68Q1/p1676555870369069

**Comment by primeroz** [comment]
Had to fix VPA CRD APP by hand
* remove label from the app to let the cluster specific app-operator pick it up
* edit the CRDs `helm-release/name` annotations to match the new chart

We need to change the way we install vpa-crd in mc-bootstrap to do a `helm install` rather than the APP install to avoid this problems

**Comment by primeroz** [comment]
I will close this one once the PMO is released and i have updated CAPZ-APP-COLLECTION

**Comment by primeroz** [comment]
Re-Re created glippy with right `10.223` network cidrs

**Comment by primeroz** [comment]
this is all done an dPMO was released
