### ISSUE TITLE
Azure VPN Gateway for Workload Clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2039]
### Motivation
We learned in https://github.com/giantswarm/roadmap/issues/2011 that In order to access workload clusters in a closed internal network, we need to setup an Azure VPN Gateway to peer the VNet of the workload and management cluster in a secure way. This enables us to access to workload cluster API over the Management Cluster.

### Todo

- [ ] Deploy Azure VPN gateway to glippy as a first test
- [ ] Add the Azure VPN Gateway configuration to MC Bootstrap

### Outcome
- Every Management Cluster has a Azure VPN Gateway configuration for the workload clusters. 
- Workload Cluster APIs can be accessed securely over the Azure VPN Gateway through the Management Cluster.

**Comment by nprokopic** [comment]
I pulled this into In Progress, as I already did it before we recreated glippy. Will do it now again, with few improvements.

**Comment by nprokopic** [comment]
The following resources are created with same configuration as we have in vintage production Azure MCs:
- New subnet where VPN gateway is deployed. It's named `GatewaySubnet` (mandatory name for gateway subnets) and has network range of 10.233.0.192/27.
- Public IP that is used by the VPN gateway. Few details - Standard SKU, Regional tier, non-zonal (random AZ), static IP allocation.
- Azure VPN gateway - gateway type VPN, route based, VpnGw1 SKU, non-zonal, generation 1, using the above public IP.
- 2 local network gateways that represent our VPN servers for routing purposes.

Next steps would be to add VPN connection to our VPN servers (see #2040) and to create VPN connections in Azure.

**Comment by nprokopic** [comment]
> Next steps would be to create VPN connections in Azure, and add VPN connections to our VPN servers

Update:

- [x] create VPN connections in Azure
- [ ] add VPN connections to our VPN servers (see https://github.com/giantswarm/roadmap/issues/2040)

**Comment by nprokopic** [comment]
Bash code used to create Azure resources. It requires Azure CLI to be installed.

I did not run the code below as a script in one go. Command `az network vnet-gateway create` in "Create the VPN gateway" step will return immediately (see `--no-wait` flag) and VPN gateway creation can take up to 45 minutes, so this below is just a guideline for what we need in MC bootstrap. In a production-ready scenario we would have this code to be idempotent, and check if existing resources exist, and create them only when they are not already there.

```
#!/usr/bin/env bash

#
# Managment cluster
#
MC_SUBSCRIPTION="<insert MC subscription ID here>"
MC_LOCATION=westeurope
MC_NAME="<insert MC name here>" # e.g. "glippy"
MC_GATEWAY_SUBNET_RANGE="10.233.0.192/27" # GatewaySubnet network range. /29 in the minimum, /27 is recommended by Azure.

#
# Set default subscription
#
az account set -s "$MC_SUBSCRIPTION"

#
# Set default location
#
az configure --defaults location="$MC_LOCATION"

#
# Request a Public IP address
#
# A VPN gateway must have a Public IP address. You first request
# the IP address resource, and then refer to it when creating your
# virtual network gateway.
#
GATEWAY_NAME="$MC_NAME-vpn-gateway"
GATEWAY_IP_NAME="$MC_NAME-vpn-public-ip"
az network public-ip create \
  --resource-group "$MC_NAME" \
  --name "$GATEWAY_IP_NAME" \
  --sku Standard \
  --tier Regional \
  --allocation-method Static

#
# Create the gateway subnet
#
az network vnet subnet create \
  --resource-group "$MC_NAME" \
  --vnet-name "$MC_NAME-vnet" \
  --name GatewaySubnet \
  --address-prefix "$MC_GATEWAY_SUBNET_RANGE"

#
# Create the VPN gateway
#
az network vnet-gateway create \
  --resource-group "$MC_NAME" \
  --vnet "$MC_NAME-vnet" \
  --name "$GATEWAY_NAME" \
  --public-ip-address "$GATEWAY_IP_NAME" \
  --gateway-type Vpn \
  --vpn-type RouteBased \
  --sku VpnGw1 \
  --vpn-gateway-generation Generation1 \
  --no-wait

#
# Giant Swarm VPN
#
GRIDSCALE_NAME="gridscale"
GRIDSCALE_LOCAL_GATEWAY_NAME="$MC_NAME-vpn-right-gateway-$GRIDSCALE_NAME"
GRIDSCALE_IP="185.102.95.187"
GRIDSCALE_NETWORK_RANGE="172.18.0.1/32"
VULTR_NAME="vultr"
VULTR_LOCAL_GATEWAY_NAME="$MC_NAME-vpn-right-gateway-$VULTR_NAME"
VULTR_IP="95.179.153.65"
VULTR_NETWORK_RANGE="172.18.0.5/32"

#
# Create the local network gateways.
#
# These local network gateway refers to the on-premises location, in our case
# those are gridscale and vultr VPN servers.
#
az network local-gateway create \
  --resource-group "$MC_NAME" \
  --name "$GRIDSCALE_LOCAL_GATEWAY_NAME" \
  --gateway-ip-address "$GRIDSCALE_IP" \
  --local-address-prefixes "$GRIDSCALE_NETWORK_RANGE"

az network local-gateway create \
  --resource-group "$MC_NAME" \
  --name "$VULTR_LOCAL_GATEWAY_NAME" \
  --gateway-ip-address "$VULTR_IP" \
  --local-address-prefixes "$VULTR_NETWORK_RANGE"

#
# Create gridscale VPN connection
#
CONNECTION_NAME="$MC_NAME-vpn-connection-$GRIDSCALE_NAME"
SHARED_KEY="$GRIDSCALE_SHARED_KEY" # set ouside of the script
az network vpn-connection create \
  --resource-group "$MC_NAME" \
  --name "$CONNECTION_NAME" \
  --vnet-gateway1 "$GATEWAY_NAME" \
  --local-gateway2 "$GRIDSCALE_LOCAL_GATEWAY_NAME" \
  --shared-key "$SHARED_KEY"

#
# Create vultr VPN connection
#
CONNECTION_NAME="$MC_NAME-vpn-connection-$VULTR_NAME"
SHARED_KEY="$VULTR_SHARED_KEY" # set ouside of the script
az network vpn-connection create \
  --resource-group "$MC_NAME" \
  --name "$CONNECTION_NAME" \
  --vnet-gateway1 "$GATEWAY_NAME" \
  --local-gateway2 "$VULTR_LOCAL_GATEWAY_NAME" \
  --shared-key "$SHARED_KEY"

```
