### ISSUE TITLE
Create Test Installations on demand (aka TIA)

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#204]
## Background

The current process of testing is not efficient. 
The number of testing installations is limited and multiple people often can't test their changes on the same installation.

They have to wait for available installation, reserve it in the slack channel, cleanup after testing. With the growing number of engineers, this is not scalable and impacts the speed of development.

How we can improve this process? How we can spin up installations when they are needed and kill when they are not used?

## User Story

_- As a GS engineer, I want to be able to automatically spin-up a new test installation when I need it so that I don't depend on test installations availability and I don't need to cleanup test installations manually._

_-As a GS Engineer, I can run test installation on spot instances, so that it will save costs for the company and be more sustainable._

**_The outcome of this epic should be having only 1 test installation per cloud provider - AWS, AWS China, Azure. The solution for on-prem is out of scope for now._**

## Definitions

**TIA** - Test Installations Automation
**Primary CP - 1CP** - existing CP
**Secondary CP - 2CP** - CP started on a TC
**Secondary TC - 2TC** - TC started on a 2CP

## [Done] Milestone 0. Kickoff the story, work out the next steps.

- [x] Kickoff  - https://docs.google.com/document/d/1KcJUiCyxbc1PbQd-6kunsywtg183UiEgH4Rx0zPeLe4/edit#

## [Done] Milestone 1. Create a 2CP on a TC and create a 2TC on 2CP.

- [x] Start a TC and try to convert it to 2CP following the Installation guide.
- [x] Write down to this issue what has failed.

## [WIP] Milestone 2. Be able to create a 2TC on a 2CP automatically in a reproducible way - get the hackmd automated

- [x] giantswarm/giantswarm#12943 Automate 2CP creation / hackmd to bash script 
  - [x] giantswarm/giantswarm#12940 Fix routing tables name collision in `aws-operator` 
  - [x] giantswarm/giantswarm#12944 Solve the issue with the hosted zone
  - [x] giantswarm/giantswarm#12945 Resolve `aws-operator` credentials issue 
  - [x] giantswarm/giantswarm#12935 Automate running `cert-manager` on 2CP
  - [x] giantswarm/giantswarm#13063 Create the CLI tool skelethon / bash script ‘make’
  - [x] giantswarm/giantswarm#13064 Create CRDs (opsctl ensure CRDs)
  - [x] giantswarm/giantswarm#13065 Prepare configurations
  - [x] giantswarm/giantswarm#13066 Create CP catalog (opsctl ensure appcatalog) 
  - [x] giantswarm/giantswarm#13068 Install `app-operator` / `chart-operator` / `release-operator` via helm install
  - [x] giantswarm/giantswarm#13069 Install Vault 
  - [x] giantswarm/giantswarm#13071 Install aws app-collection
  - [x] giantswarm/giantswarm#13070 Ensure the 11.X.X Releases

## Milestone 2.5. Having automatically created 2CP usable for testing. 

- [x] giantswarm/giantswarm#13236 Monitoring stack on 2CP
- [x] giantswarm/giantswarm#12941 Automate Auth0 / OIDC approach 
- [x] giantswarm/giantswarm#12938 Add support to `opsctl deploy` to deploy to a TC 
- [x] giantswarm/giantswarm#13237 Ensure all Apps on 2CP are in deployed state
- [x] giantswarm/giantswarm#13238 Test that cluster created on 2CP is working

## Milestone 3. Having only 1 test CP on AWS (get rid of gauss and gaia)

- [ ] Add support for SSH into 2TC
- [ ] vault in dev mode
- [ ] giantswarm/giantswarm#13702 Add support for Apps on 2TCs 
- [ ] 2TC cluster CR is kept on deletion because of finalized "operatorkit.giantswarm.io/prometheus-meta-operator-cluster-api-controller"

## [Later Later] Milestone X

- [ ] giantswarm/giantswarm#12942 Automate subnets for 2CP and AWS CNI 
- [ ] giantswarm/giantswarm#13114 Provision test AWS CP/TC accounts with giantswarm-aws-account-prerequisites 
- [ ] giantswarm/giantswarm#13126 Setup aws-operator roles on all CP AWS accounts 
- [ ] giantswarm/giantswarm#12803 Start using publicly trusted CA for vault PKI giantswarm/giantswarm#12803
- [ ] giantswarm/giantswarm#13021 Remove `routeTables` flag from aws-operator and installations 
- [ ] sync back vault changes into tc2cp (changes for secret encryption)
