### ISSUE TITLE
VPN Configuration for Clippy

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2040]
### Motivation
We learned in https://github.com/giantswarm/roadmap/issues/2011 that we have to add Glippy to our GS VPN Configuration in order to secure and access it over our GS VPN.

### Todo

- [x] Add Glippy to our GS VPN Config
- [ ] Document the process on how to add a new Management Cluster to our VPN
- [ ] Store the document of the process in our intranet as subsite under https://intranet.giantswarm.io/docs/product/providers/capz/

### Outcome
- We have Glippy secured via GS VPN access.
- We have a document with a recipe to add new installations to our GS VPN configuration.

**Comment by Rotfuks** [comment]
From @nprokopic in https://github.com/giantswarm/roadmap/issues/2011

========
Here we configure shared network range to include glippy MC network range as well as a larger network range that will accommodate all WCs created in glippy.

The suggestion is to use `10.x.y.0/20` range for glippy shared IP network range via the VPN connection (MC and all WCs).

This will enable us to deploy, for example, 16 clusters in total (counting all MCs and WCs) with `10.x.y.0/24` network range (256 addresses in total), where cluster network is split in the following way:
- `10.x.y.0/25` for workers subnet. This is 128 addresses in total, where 5 are reserved by Azure, which gives us 123 addresses for worker nodes.
- `10.x.y.128/25` divided into:
    - `10.x.y.128/26` for control plane subnet
    - `10.x.y.192/26` for bastion and other subnets that we will possibly need.

The smallest possible WC that we can create with the current WC setup would be `10.x.y.z/27`, where:
- `10.x.y.z/28` is for workers subnet, which gives us 16 addresses (11 for nodes, 5 reserved by Azure)
- `10.x.y.z/29` is for control plane, which gives us 8 addresses, so 3 usable, where 1 is required for the internal load balancer, so we get 2 for control plane nodes, meaning we can have only 1 control plane node.

To expand a bit there, by using `10.x.y.0/20` network range for an MC (and its WCs), we get the following possibilities and constraints (max addresses, workers and CP nodes):

| Total WCs | WC mask | Addresses | Workers | CP nodes |
| --------- | ------- | --------- | ------- | -------- |
| 8         | /23     | 512       | 251     | 123      |
| 16        | /24     | 256       | 123     | 59       |
| 32        | /25     | 128       | 59      | 27       |
| 64        | /26     | 64        | 27      | 11       |
| 128       | /27     | 32        | 11      | 1        |

The above examples show that this should be more than enough for testing purposes.

=====

**Comment by bavarianbidi** [comment]
We should also check if we can use the private DNS zones for WCs/MCs via the VPN or if we have to use a public DNS zone for WCs/MCs.
