### ISSUE TITLE
Improve CAPZ upstream VNet Peering

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2041]
### Motivation
In https://github.com/giantswarm/roadmap/issues/2011 we found out, that we can improve the VNet Peering in upstream CAPZ by enabling transit gateway. 

### Todo
- [x] Implement change in our CAPZ fork https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3183
- [x] Submit a [pull request to upstream CAPZ with the same change](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3340)
- [x] Release new CAPZ version from our fork (based on the latest CAPZ v1.8.2 and our VNet peering improvement)
- [x] Release CAPZ app based on our fork

### Outcome
- We can easily and securely access the protected private network workload clusters through the management cluster. 
- We enabled to do this in an upstream CAPZ Release

**Comment by nprokopic** [comment]
Created upstream CAPZ issue here https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3183

**Comment by nprokopic** [comment]
CAPZ app released from our fork, upstream PR merged and added to v1.9 milestone.
