### ISSUE TITLE
Private Link for upstream CAPZ

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2042]
### Motivation
In https://github.com/giantswarm/roadmap/issues/2011 we learned that we can improve the security and stability of our private network workload clusters by introducing private links to upstream capz. With that we can easily connect to workload clusters private endpoints and don't have to care too much about overlapping IP addresses.

### Todo

```[tasklist]
- [x] Investigate the state of private endpoints / private link in upstream
- [x] Create an issue to propose and discuss private link as a new feature in upstream https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3400
- [x] Implement private link in our CAPZ fork https://github.com/giantswarm/cluster-api-provider-azure/pull/17
- [ ] Update CAPZ app https://github.com/giantswarm/cluster-api-provider-azure-app/pull/104
- [ ] Update cluster-azure app https://github.com/giantswarm/cluster-azure/pull/115
```

### Outcome
- We can easily and securely connect management clusters with workload clusters in a private network configuration

**Comment by primeroz** [comment]
As discussed in Refinement we might need to think how we will access WC nodes over ssh if we use PrivateLinks 

From an AZURE architecture point of view we might just a `bastion private link` exposed in the `MC Vnet` where

```
[Bastion PrivateLink EndPont in MC Vnet] -> [ Bastion LB in WC Vnet ] -> [ Bastion Node LB Member ]
``` 

like



![Image](https://user-images.githubusercontent.com/2085772/220080969-a1531bab-f62a-4c60-adb0-0c26b1f3a7b9.png)


The only issue here would be how do we automate creation and mantainance of he LB and the PrivateLink Endpoint 

* How do we update members of the LB Backend when the bastion node is recycled ? 
*

**Comment by Rotfuks** [comment]
We removed the private link upstream work out of the scope of this epic since it's blocked by upstream and will be moved to team phoenix. The Epic here can be closed in the reduced scope then.

**Comment by Rotfuks** [comment]
Sorry, closed the wrong ticket! :D

**Comment by robinkb** [comment]
Resubmitted in https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/6274.

**Comment by robinkb** [comment]
Review comments have been addressed, and another review has been requested.

**Comment by robinkb** [comment]
More comments were posted soon after my previous update. Those are resolved (with some bigger changes this time), and I'm waiting for the next review.

**Comment by T-Kukawka** [comment]
merged upstream
