### ISSUE TITLE
Ensure appropriate scalability for all managed apps

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2066]
## User Story

- As a customer, I want Managed Apps to scale according to the most appropriate metrics so that they are always able to properly ensure performance and reliability without overcommitting resources, hence not overpaying for unused resources 
- As a Giant Swarm engineer, I want Managed Apps to scale according to the most appropriate metric so that they lead to fewer pages and do not require manual tuning

## Details, Background

Pod Autoscaling generally happens based on CPU/RAM usage. While this is generally a sensible default, some applications' scaling behaviour might be better related to other metrics. For instance, for nginx a metric such as `requests per second` could be more useful than just looking at CPU and RAM. 

In the end, as part of the "Managed" experience we should be able to have all applications scale based on the most impactful metrics to ensure smooth operations, happier customers, and fewer pages. _Scaling_ is intended as both **Vertical** and **Horizontal** pod autoscaling.

Finally, having PDBs defined as percentages would also go in this direction, especially as far as stability at all scales is concerned.

```[tasklist]
### Team Atlas
- [ ] https://github.com/giantswarm/roadmap/issues/2285
- [ ] https://github.com/giantswarm/roadmap/issues/2286
- [ ] https://github.com/giantswarm/roadmap/issues/2287
- [ ] https://github.com/giantswarm/roadmap/issues/2289
- [ ] https://github.com/giantswarm/roadmap/issues/2290
- [ ] https://github.com/giantswarm/roadmap/issues/2291
- [ ] https://github.com/giantswarm/roadmap/issues/2292
- [ ] https://github.com/giantswarm/roadmap/issues/2293
- [ ] https://github.com/giantswarm/roadmap/issues/2294
- [ ] https://github.com/giantswarm/roadmap/issues/3341
```

```[tasklist]
### Team Cabbage
- [ ] https://github.com/giantswarm/roadmap/issues/2310
- [ ] https://github.com/giantswarm/roadmap/issues/2313
- [ ] https://github.com/giantswarm/roadmap/issues/2311
- [ ] https://github.com/giantswarm/roadmap/issues/2314
- [ ] https://github.com/giantswarm/roadmap/issues/2315
- [ ] https://github.com/giantswarm/roadmap/issues/2316
- [ ] https://github.com/giantswarm/roadmap/issues/2317
- [ ] https://github.com/giantswarm/roadmap/issues/2318
- [ ] https://github.com/giantswarm/roadmap/issues/2319
- [ ] https://github.com/giantswarm/roadmap/issues/2320
- [ ] https://github.com/giantswarm/roadmap/issues/2321
- [ ] https://github.com/giantswarm/roadmap/issues/2322
- [ ] https://github.com/giantswarm/roadmap/issues/2323
- [ ] https://github.com/giantswarm/roadmap/issues/2324
- [ ] https://github.com/giantswarm/roadmap/issues/2325
- [ ] https://github.com/giantswarm/roadmap/issues/2326
- [ ] https://github.com/giantswarm/roadmap/issues/2327
```

```[tasklist]
### Team Honeybadger
- [ ] https://github.com/giantswarm/roadmap/issues/2307
- [ ] https://github.com/giantswarm/roadmap/issues/2308
- [ ] https://github.com/giantswarm/roadmap/issues/2309
```

```[tasklist]
### Team Hydra
- [ ] https://github.com/giantswarm/roadmap/issues/2306
```

```[tasklist]
### Team Phoenix
- [ ] https://github.com/giantswarm/roadmap/issues/2302
- [ ] https://github.com/giantswarm/roadmap/issues/2303
- [ ] https://github.com/giantswarm/roadmap/issues/2304
- [ ] https://github.com/giantswarm/roadmap/issues/2305
```

```[tasklist]
### Team Rainbow
- [ ] https://github.com/giantswarm/roadmap/issues/2298
- [ ] https://github.com/giantswarm/roadmap/issues/2299
- [ ] https://github.com/giantswarm/roadmap/issues/2301
```

```[tasklist]
### Team Shield
- [ ] https://github.com/giantswarm/roadmap/issues/2273
- [ ] https://github.com/giantswarm/roadmap/issues/2274
- [ ] https://github.com/giantswarm/roadmap/issues/2281
- [ ] https://github.com/giantswarm/roadmap/issues/2276
- [ ] https://github.com/giantswarm/roadmap/issues/2280
- [ ] https://github.com/giantswarm/roadmap/issues/2278
- [ ] https://github.com/giantswarm/roadmap/issues/2279
- [ ] https://github.com/giantswarm/roadmap/issues/2282
- [ ] https://github.com/giantswarm/roadmap/issues/2283
- [ ] https://github.com/giantswarm/roadmap/issues/2284
```

```[tasklist]
### Team Turtle
- [ ] https://github.com/giantswarm/roadmap/issues/2288
```

## Blocked by / depends on

- https://github.com/giantswarm/prometheus-adapter-app would probably be needed for custom metrics

**Comment by QuentinBisson** [comment]
@Rotfuks should you be assigned here? It feels weird to have an issue in wip without any assignee?

**Comment by Rotfuks** [comment]
Done for Team Atlas.

**Comment by teemow** [comment]
ping to ping @JosephSalisbury

**Comment by JosephSalisbury** [comment]
pinged POs on outstanding issues, will check progress shortly

**Comment by JosephSalisbury** [comment]
nice, all linked issues closed, closing here
