### ISSUE TITLE
Update PSP volume permissions for CAPA-related operators

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2074]
## Tasks

Update the PSP definitions to allow volumes (secret, projected, etc.) of all the components owned by Hydra in order to prevent future issues like this one [here](https://github.com/giantswarm/roadmap/issues/2073).

Only update the apps that require the additional permissions.

## TODO

- [ ] Review all components owned by Hydra and create a list with their status;
- [ ] Update the components with the additional PSP permissions;
- [ ] Deploy changes to management and workload clusters.

### Operators fully owned or co-owned

| Name | Status |
|---|---|
| ✅ aws-network-topology-operator | Fixed in 1.4.3 |
| ✅ aws-resolver-rules-operator | Fixed in 0.4.1 |
| ✅ aws-vpc-operator | Fixed |
| ✅ capa-iam-operator | Fixed in 0.7.0 |
| capg-firewall-rule-operator | TBD |
| ✅ deletion-blocker-operator | Fixed in 0.1.3 |
| ✅ dns-operator-aws | Fixed |
| dns-operator-gcp | TBD |
| ✅ encryption-provider-operator | Fixed in 0.3.1 |
| ✅ irsa-operator | Fixed |
| fleet-membership-operator-gcp | TBD |
| workload-identity-operator-gcp | TBD |

## Links

- [Example PR](https://github.com/giantswarm/aws-vpc-operator/pull/38);
- See [issue](https://github.com/giantswarm/roadmap/issues/2073).
