### ISSUE TITLE
Silence management

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#2077]
## User Story

- As a Giant Swarm engineer, I want to be able to manage silences using Silence CRD only (without having to access to alertmanager)
- As a Giant Swarm customer, I want to be able to see the silences on my installation, maybe create them for temporary test clusters as to not page Giant Swarm engineers

### Tasks

- [ ] Reflect status of silences in Alertmanager in Silence CRs (list of silenced alerts), maybe add an annotation on the cluster to know that it is affected by silences (kinda like what VPA does)
- [ ] Have a read-only alertmanager (not able to create silences)
- [ ] Make alertmanager private if possible (port-forward only)?
- [ ] Create silence CR through opsctl
- [ ] Push silence operator into prometheus-operator

**Comment by QuentinBisson** [comment]
cc @giantswarm/sig-opsprocess did I miss anything?

**Comment by JosephSalisbury** [comment]
looks good to me - i think the main thrust of the discussion was that we should have only one way to create silences, and that should be via silence CR, and i think this covers that
