### ISSUE TITLE
Have a working CPI and CSI for Vsphere

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#2090]
- [x] Update https://github.com/giantswarm/cloud-provider-vsphere-app and ensure it works with the latest cluster app.

***Notes***

- In the `cluster-api-provider-vsphere` repository, CPI and CSI are deployed as ClusterResourceSet. See [CPI](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/templates/cluster-template.yaml#L928) and [CSI](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/templates/cluster-template.yaml#L615)

- The source of truth for these manifests are Go code in the repo. See [CPI](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/packaging/flavorgen/cloudprovider/cloud-controller-manager.go#L32) and [CSI](https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/main/packaging/flavorgen/cloudprovider/csi.go#L30).

- The Go code fills k8s objects based on the manifests in the CPI and CSI repositories. We will rely on these files.
   - CSI Repo: https://github.com/kubernetes-sigs/vsphere-csi-driver
   - CPI Repo: https://github.com/kubernetes/cloud-provider-vsphere
   
***Roadmap*** 
- [x] https://github.com/giantswarm/cloud-provider-vsphere-app/pull/28
- [x] [Add CSI as sub chart.](https://github.com/giantswarm/cloud-provider-vsphere-app/pull/30)
- [x] [Improve UX (including schema.json) and security (we put passwords into a config map 🤦 ).](https://github.com/giantswarm/cloud-provider-vsphere-app/pull/31)
- [x] [Improve README files](https://github.com/giantswarm/cloud-provider-vsphere-app/pull/38).

Follow-up task https://github.com/giantswarm/roadmap/issues/2184

**Comment by erkanerol** [comment]
***Open Points***
- Do we want to have a single app for CPI and CSI? We have single app for OpenStack and Cloud Director.
- Do we want to rely on manifests in cluster-api-provider-vsphere or the manifests in the real repositories?
- What will we do regarding csi-external-snapshotter-app?

**Comment by erkanerol** [comment]
PRs are merged and verified. Closing.
