### ISSUE TITLE
Implement recommendations to normalize cluster-azure schema

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2103]
### Motivation

Currently when I try to run `make schema-normalize` in `cluster-azure` repo I get 189 recommendations. This is on my branch, so on `main` it would be slightly less.

```
❯ make schema-normalize 
go install github.com/giantswarm/schemalint@latest
schemalint verify ./helm/cluster-azure/values.schema.json --rule-set=cluster-app

Recommendations (189)

- Numeric property '/controlPlane/etcdVolumeSizeGB' should be constrained through 'minimum', 'maximum', 'exclusiveMinimum' or 'exclusiveMaximum'
- Numeric property '/controlPlane/replicas' should be constrained through 'minimum', 'maximum', 'exclusiveMinimum' or 'exclusiveMaximum'
- Numeric property '/controlPlane/rootVolumeSizeGB' should be constrained through 'minimum', 'maximum', 'exclusiveMinimum' or 'exclusiveMaximum'
- Numeric property '/nodePools/items/replicas' should be constrained through 'minimum', 'maximum', 'exclusiveMinimum' or 'exclusiveMaximum'
- Numeric property '/nodePools/items/rootVolumeSizeGB' should be constrained through 'minimum', 'maximum', 'exclusiveMinimum' or 'exclusiveMaximum'
- Object '/cluster-shared' should disable additional properties.
- Object '/connectivity' should disable additional properties.
- Object '/connectivity/bastion' should disable additional properties.
- Object '/connectivity/network' should disable additional properties.
- Object '/connectivity/network/controlPlane' should disable additional properties.
- Object '/connectivity/network/workers' should disable additional properties.
- Object '/controlPlane' should disable additional properties.
- Object '/controlPlane/oidc' should disable additional properties.
- Object '/internal' should disable additional properties.
- Object '/internal/defaults' should disable additional properties.
- Object '/internal/identity' should disable additional properties.
- Object '/metadata' should disable additional properties.
- Object '/nodePools/items' should disable additional properties.
- Object '/nodePools/items/customNodeTaints/items' should disable additional properties.
- Object '/providerSpecific' should disable additional properties.
- Object '/providerSpecific/azureClusterIdentity' should disable additional properties.
- Object '/providerSpecific/network' should disable additional properties.
- Object '/providerSpecific/network/peerings/items' should disable additional properties.
- Property '/baseDomain' should have a description.
- Property '/baseDomain' should provide one or more examples.
- Property '/cluster-shared' should have a description.
- Property '/cluster-shared' should provide one or more examples.
- Property '/connectivity' should have a description.
- Property '/connectivity' should provide one or more examples.
- Property '/connectivity/bastion' should have a description.
- Property '/connectivity/bastion' should provide one or more examples.
- Property '/connectivity/bastion/enabled' should have a description.
- Property '/connectivity/bastion/enabled' title should not contain the parent's title 'Bastion host'.
- Property '/connectivity/bastion/instanceType' should provide one or more examples.
- Property '/connectivity/network' should have a description.
- Property '/connectivity/network' should provide one or more examples.
- Property '/connectivity/network/controlPlane' should have a description.
- Property '/connectivity/network/controlPlane' should provide one or more examples.
- Property '/connectivity/network/controlPlane/apiServerLbIp' description should be more than 50 characters.
- Property '/connectivity/network/controlPlane/apiServerLbIp' should provide one or more examples.
- Property '/connectivity/network/controlPlane/cidr' should have a description.
- Property '/connectivity/network/controlPlane/cidr' should provide one or more examples.
- Property '/connectivity/network/hostCidr' description should be more than 50 characters.
- Property '/connectivity/network/hostCidr' should provide one or more examples.
- Property '/connectivity/network/mode' should have a description.
- Property '/connectivity/network/mode' should provide one or more examples.
- Property '/connectivity/network/mode' title should not contain the parent's title 'Network'.
- Property '/connectivity/network/podCidr' description should be more than 50 characters.
- Property '/connectivity/network/podCidr' should provide one or more examples.
- Property '/connectivity/network/serviceCidr' should provide one or more examples.
- Property '/connectivity/network/workers' should have a description.
- Property '/connectivity/network/workers' should provide one or more examples.
- Property '/connectivity/network/workers/cidr' should have a description.
- Property '/connectivity/network/workers/cidr' should provide one or more examples.
- Property '/connectivity/sshSSOPublicKey' should have a description.
- Property '/connectivity/sshSSOPublicKey' should provide one or more examples.
- Property '/controlPlane' should have a description.
- Property '/controlPlane' should provide one or more examples.
- Property '/controlPlane/etcdVolumeSizeGB' should have a description.
- Property '/controlPlane/etcdVolumeSizeGB' should provide one or more examples.
- Property '/controlPlane/instanceType' should have a description.
- Property '/controlPlane/instanceType' should provide one or more examples.
- Property '/controlPlane/oidc' should have a description.
- Property '/controlPlane/oidc' should provide one or more examples.
- Property '/controlPlane/oidc/caPem' description should be more than 50 characters.
- Property '/controlPlane/oidc/caPem' should provide one or more examples.
- Property '/controlPlane/oidc/clientId' should have a description.
- Property '/controlPlane/oidc/clientId' should provide one or more examples.
- Property '/controlPlane/oidc/groupsClaim' should have a description.
- Property '/controlPlane/oidc/groupsClaim' should provide one or more examples.
- Property '/controlPlane/oidc/issuerUrl' should have a description.
- Property '/controlPlane/oidc/issuerUrl' should provide one or more examples.
- Property '/controlPlane/oidc/usernameClaim' should have a description.
- Property '/controlPlane/oidc/usernameClaim' should provide one or more examples.
- Property '/controlPlane/replicas' should have a description.
- Property '/controlPlane/replicas' should provide one or more examples.
- Property '/controlPlane/rootVolumeSizeGB' should have a description.
- Property '/controlPlane/rootVolumeSizeGB' should provide one or more examples.
- Property '/internal' should have a description.
- Property '/internal' should provide one or more examples.
- Property '/internal/defaults' should have a description.
- Property '/internal/defaults' should provide one or more examples.
- Property '/internal/defaults/evictionMinimumReclaim' should have a description.
- Property '/internal/defaults/evictionMinimumReclaim' should provide one or more examples.
- Property '/internal/defaults/evictionMinimumReclaim' title should not contain the parent's title 'Default settings'.
- Property '/internal/defaults/hardEvictionThresholds' should have a description.
- Property '/internal/defaults/hardEvictionThresholds' should provide one or more examples.
- Property '/internal/defaults/hardEvictionThresholds' title should not contain the parent's title 'Default settings'.
- Property '/internal/defaults/softEvictionGracePeriod' should have a description.
- Property '/internal/defaults/softEvictionGracePeriod' should provide one or more examples.
- Property '/internal/defaults/softEvictionGracePeriod' title should not contain the parent's title 'Default settings'.
- Property '/internal/defaults/softEvictionThresholds' should have a description.
- Property '/internal/defaults/softEvictionThresholds' should provide one or more examples.
- Property '/internal/defaults/softEvictionThresholds' title should not contain the parent's title 'Default settings'.
- Property '/internal/identity' should have a description.
- Property '/internal/identity' should provide one or more examples.
- Property '/internal/identity/attachCapzControllerIdentity' should have a description.
- Property '/internal/identity/attachCapzControllerIdentity' title should not contain the parent's title 'Identity'.
- Property '/internal/identity/enablePerClusterIdentity' should have a description.
- Property '/internal/identity/enablePerClusterIdentity' title should not contain the parent's title 'Identity'.
- Property '/internal/kubernetesVersion' should have a description.
- Property '/internal/kubernetesVersion' should provide one or more examples.
- Property '/managementCluster' should have a description.
- Property '/managementCluster' should provide one or more examples.
- Property '/metadata' should have a description.
- Property '/metadata' should provide one or more examples.
- Property '/metadata/description' should provide one or more examples.
- Property '/metadata/name' should provide one or more examples.
- Property '/metadata/organization' should have a description.
- Property '/metadata/organization' should provide one or more examples.
- Property '/metadata/servicePriority' description should be more than 50 characters.
- Property '/metadata/servicePriority' should provide one or more examples.
- Property '/nodePools' should have a description.
- Property '/nodePools' should provide one or more examples.
- Property '/nodePools/items/customNodeLabels' should have a description.
- Property '/nodePools/items/customNodeLabels' should provide one or more examples.
- Property '/nodePools/items/customNodeTaints' should have a description.
- Property '/nodePools/items/customNodeTaints' should provide one or more examples.
- Property '/nodePools/items/customNodeTaints/items/effect' should have a description.
- Property '/nodePools/items/customNodeTaints/items/effect' should provide one or more examples.
- Property '/nodePools/items/customNodeTaints/items/key' should have a description.
- Property '/nodePools/items/customNodeTaints/items/key' should provide one or more examples.
- Property '/nodePools/items/customNodeTaints/items/value' should have a description.
- Property '/nodePools/items/customNodeTaints/items/value' should provide one or more examples.
- Property '/nodePools/items/disableHealthCheck' should have a description.
- Property '/nodePools/items/disableHealthCheck' should provide one or more examples.
- Property '/nodePools/items/instanceType' should have a description.
- Property '/nodePools/items/instanceType' should provide one or more examples.
- Property '/nodePools/items/name' should provide one or more examples.
- Property '/nodePools/items/replicas' should have a description.
- Property '/nodePools/items/replicas' should provide one or more examples.
- Property '/nodePools/items/rootVolumeSizeGB' should have a description.
- Property '/nodePools/items/rootVolumeSizeGB' should provide one or more examples.
- Property '/provider' should have a description.
- Property '/provider' should provide one or more examples.
- Property '/providerSpecific' should have a description.
- Property '/providerSpecific' should provide one or more examples.
- Property '/providerSpecific/azureClusterIdentity' description should not repeat the title.
- Property '/providerSpecific/azureClusterIdentity' should provide one or more examples.
- Property '/providerSpecific/azureClusterIdentity/name' should have a description.
- Property '/providerSpecific/azureClusterIdentity/name' should provide one or more examples.
- Property '/providerSpecific/azureClusterIdentity/namespace' should have a description.
- Property '/providerSpecific/azureClusterIdentity/namespace' should provide one or more examples.
- Property '/providerSpecific/location' should have a description.
- Property '/providerSpecific/location' should provide one or more examples.
- Property '/providerSpecific/network' should provide one or more examples.
- Property '/providerSpecific/network/peerings' should have a description.
- Property '/providerSpecific/network/peerings' should provide one or more examples.
- Property '/providerSpecific/network/peerings/items/remoteVnetName' should provide one or more examples.
- Property '/providerSpecific/network/peerings/items/resourceGroup' description should be more than 50 characters.
- Property '/providerSpecific/network/peerings/items/resourceGroup' should provide one or more examples.
- Property '/providerSpecific/subscriptionId' should have a description.
- Property '/providerSpecific/subscriptionId' should provide one or more examples.
- String property '/baseDomain' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/bastion/instanceType' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/network/controlPlane/apiServerLbIp' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/network/controlPlane/cidr' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/network/hostCidr' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/network/podCidr' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/network/serviceCidr' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/network/workers/cidr' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/connectivity/sshSSOPublicKey' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/controlPlane/instanceType' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/controlPlane/oidc/caPem' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/controlPlane/oidc/clientId' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/controlPlane/oidc/groupsClaim' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/controlPlane/oidc/issuerUrl' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/controlPlane/oidc/usernameClaim' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/internal/defaults/evictionMinimumReclaim' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/internal/defaults/hardEvictionThresholds' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/internal/defaults/softEvictionGracePeriod' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/internal/defaults/softEvictionThresholds' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/internal/kubernetesVersion' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/managementCluster' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/metadata/description' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/metadata/name' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/metadata/organization' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/nodePools/items/customNodeLabels/items' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/nodePools/items/customNodeTaints/items/key' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/nodePools/items/customNodeTaints/items/value' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/nodePools/items/instanceType' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/nodePools/items/name' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/provider' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/providerSpecific/azureClusterIdentity/name' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/providerSpecific/azureClusterIdentity/namespace' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/providerSpecific/location' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/providerSpecific/network/peerings/items/remoteVnetName' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/providerSpecific/network/peerings/items/resourceGroup' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.
- String property '/providerSpecific/subscriptionId' should be constrained through 'pattern', 'minLength', 'maxLength', 'enum', 'constant' or 'format'.

Errors (1)

- Schema is not normalized.

Verification result

[SUCCESS] Input is valid JSON Schema.
[ERROR] Input is not normalized.
[SUCCESS] Input is valid according to rule set 'cluster-app'.
```

### Tasks

Let's try to split the work into few categories.

```[tasklist]
- [ ] Implement recommendations for all except internal and provider-specific properties.
- [ ] Implement recommendations for all provider-specific properties.
- [ ] Implement recommendations for all internal properties.
```

### Outcome

- Running `make schema-normalize` is successful without errors and without recommendations.

**Comment by bavarianbidi** [comment]
It might make also sense to add a `pattern` for all the `CIDR` validation (e.g. `connectivity.allowedCIDRs`, `connectivity.network.controlPlane.cidr`, ...)

**Comment by marians** [comment]
In terms of UX, I would suggest to prioritize setting constraints to prevent likely user errors (e. g. accidental or based on missing knowledge), like

- Missing a required property
- Using a bad character, e. g. a blank space to a string value
- Setting a numeric field to an illogical value (e. g. zero)

The idea is to catch these in schema so that the cluster app cannot even be deployed. In the case of the web UI it means that the form cannot even be submitted before this mistake gets fixed.

---

Just some detail nitpick: The command `make normalize-schema` only formats the schema. It is `make validate-schema` that provides the checks and recommendations.

**Comment by marians** [comment]
https://github.com/giantswarm/cluster-azure/pull/130 is a proposal for adding some constraints to the numeric fields.

**Comment by marians** [comment]
OK, so with https://github.com/giantswarm/cluster-azure/pull/130 we have some constraints on numerical values. That's some progress.
