### ISSUE TITLE
Investigate for GPU Nodes in CAPZ Clusters

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2104]
### Motivation
Our customers are interested in using our CAPZ clusters for data science related application that have a need for machines based on GPU instead of CPU power. We need to make sure, that we can either support GPUs or make transparent, that we currently can not without additional effort onboard teams with a need for GPUs.

### Todo
- [ ] Investigate if CAPZ can support GPU based machines on Azure.
- [ ] if it's not supported document in this ticket what needs to be done in order to enable GPU nodes on CAPZ

### Outcome
- We know if we can already use GPU based machines in our CAPZ Clusters or what we have to do in order to achieve this.

**Comment by primeroz** [comment]
There is a `nvidia.service` already on the flatcar images

```
cluster01-gpu00-98e9fb48-jzsrk / # systemctl cat nvidia
# /etc/systemd/system/nvidia.service
[Unit]
Description=NVIDIA Configure Service
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
Restart=no
Environment=PATH=/opt/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
ExecStart=/usr/share/oem/bin/setup-nvidia

[Install]
WantedBy=multi-user.target
```

I think is part of the `CAPZ bootstrap extension` from Azure ( To be verified ) 

it does have an error with the URL to download the dirvers though which results in a 404 

```
#NVIDIA_DOWNLOAD_BASEURL="https://us.download.nvidia.com/${NVIDIA_PRODUCT_TYPE}/"
NVIDIA_DOWNLOAD_BASEURL="https://us.download.nvidia.com/XFree86/Linux-x86_64/"
```

unfortunately we canno change `NVIDIA_PRODUCT_TYPE` ( which is `tesla` in this case ) because is used by the script to check for the presence of the GPU 

I did fix the url in the scrip by hand and it run successfully

```
+ verify_installation
+ nvidia-smi
Wed Mar 15 16:56:41 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  Off  | 00000001:00:00.0 Off |                  Off |
| N/A   30C    P0    30W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
+ nvidia-modprobe -u -m -c 0
+ exit 0
``` 

#### TODO

* Check how to fix the script properly
* Check driver version
* Verify the GPU and all drivers are correctly working
* We should probably add `labels` and `taint` to GPU nodePools
  * Single flat to enalble them or specify in the values.yaml ?

**Comment by primeroz** [comment]
### Test downgrade version 

```
cluster01-gpu00-98e9fb48-k6g78 / # cat /etc/flatcar/nvidia-metadata 
NVIDIA_DRIVER_VERSION=460.106.00
```

```
cluster01-gpu00-98e9fb48-k6g78 / # systemctl start nvidia.service && journalctl -u nvidia.service -f

```
```

**Comment by primeroz** [comment]
## Testing other instance types

### Standard_NC4as_T4_v3
```
Operation could not be completed as it results in exceeding approved Standard NCASv3_T4 Family Cores quota. Additiona
l details - Deployment Model: Resource Manager, Location: westeurope, Current Limit: 0, Current Usage: 0, Additional Required: 4, (Minimum) New Limit Required: 4.
```

**Comment by primeroz** [comment]
### Instances and Drivers to Test 

* [ ] Standard_NC6s_v3 - Tesla v100
  * [ ] CUDA - 510.73.05 
  * [ ] CUDA - 460.106.00
  * [ ] GRID
* [ ]   Standard_NC4as_T4_v3 - Tesla T4
  * [ ] CUDA - 510.73.05 
  * [ ] GRID

**Comment by primeroz** [comment]
### Installing nvidia container-toolkit on flatcar

https://gitlab.com/nvidia/container-images/driver/-/tree/master/flatcar#getting-started
```
docker run -v /opt/nvidia-runtime:/opt/nvidia-runtime -v /run/nvidia:/run/nvidia -v /run/containerd/containerd.sock:/run/containerd/containerd.sock -v /tmp/containerd:/etc/containerd  -e RUNTIME=containerd --rm nvcr.io/nvidia/k8s/container-toolkit:v1.9.0  /opt/nvidia-runtime
```

**Comment by primeroz** [comment]
## Testing with NVIDIA OPERATOR

* https://capz.sigs.k8s.io/topics/gpu.html#install-nvidia-gpu-operator-helm-chart
* ` λ helm install --repo https://helm.ngc.nvidia.com/nvidia gpu-operator --generate-name --set psp.enabled=true`

### On Ubuntu 20.04

It worked 

```
➜ k get pod 
NAME                                                              READY   STATUS      RESTARTS   AGE
gpu-feature-discovery-tsvn2                                       1/1     Running     0          8m43s
gpu-operator-1679568587-node-feature-discovery-master-fbff68hbn   1/1     Running     0          28m
gpu-operator-1679568587-node-feature-discovery-worker-8gpqq       1/1     Running     0          25m
gpu-operator-1679568587-node-feature-discovery-worker-bj7cp       1/1     Running     0          25m
gpu-operator-1679568587-node-feature-discovery-worker-bz9r6       1/1     Running     0          25m
gpu-operator-1679568587-node-feature-discovery-worker-xswd4       1/1     Running     0          25m
gpu-operator-5d6ddf6c7b-7snhk                                     1/1     Running     0          9m29s
nsenter-ovwic2                                                    1/1     Running     0          4m53s
nvidia-container-toolkit-daemonset-mpmns                          1/1     Running     0          8m43s
nvidia-cuda-validator-l9qcm                                       0/1     Completed   0          5m32s
nvidia-dcgm-exporter-ch8h2                                        1/1     Running     0          8m43s
nvidia-device-plugin-daemonset-cl6ht                              1/1     Running     0          8m43s
nvidia-device-plugin-validator-7dwzx                              0/1     Completed   0          4m31s
nvidia-driver-daemonset-5xp9s                                     1/1     Running     0          9m2s
nvidia-operator-validator-bchqm                                   1/1     Running     0          8m43s
```

```
 λ kubectl exec -t -i nvidia-device-plugin-daemonset-cl6ht nvidia-smi
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
Defaulted container "nvidia-device-plugin" out of: nvidia-device-plugin, toolkit-validation (init)
Thu Mar 23 11:18:23 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.60.13    Driver Version: 525.60.13    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-PCIE...  On   | 00000001:00:00.0 Off |                  Off |
| N/A   23C    P0    23W / 250W |      0MiB / 16384MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

```
➜ k get node cluster01-gpu00-4ba2f03f-tgcb7 -o yaml | yq .metadata.labels | grep nvidia
nvidia.com/cuda.driver.major: "525"
nvidia.com/cuda.driver.minor: "60"
nvidia.com/cuda.driver.rev: "13"
nvidia.com/cuda.runtime.major: "12"
nvidia.com/cuda.runtime.minor: "0"
nvidia.com/gfd.timestamp: "1679570003"
nvidia.com/gpu-driver-upgrade-state: upgrade-done
nvidia.com/gpu.compute.major: "7"
nvidia.com/gpu.compute.minor: "0"
nvidia.com/gpu.count: "1"
nvidia.com/gpu.deploy.container-toolkit: "true"
nvidia.com/gpu.deploy.dcgm: "true"
nvidia.com/gpu.deploy.dcgm-exporter: "true"
nvidia.com/gpu.deploy.device-plugin: "true"
nvidia.com/gpu.deploy.driver: "true"
nvidia.com/gpu.deploy.gpu-feature-discovery: "true"
nvidia.com/gpu.deploy.node-status-exporter: "true"
nvidia.com/gpu.deploy.nvsm: ""
nvidia.com/gpu.deploy.operator-validator: "true"
nvidia.com/gpu.family: volta
nvidia.com/gpu.machine: Virtual-Machine
nvidia.com/gpu.memory: "16384"
nvidia.com/gpu.present: "true"
nvidia.com/gpu.product: Tesla-V100-PCIE-16GB
nvidia.com/gpu.replicas: "1"
nvidia.com/mig.capable: "false"
nvidia.com/mig.strategy: single
```

```
➜ k get node cluster01-gpu00-4ba2f03f-tgcb7 -o yaml | yq .status.allocatable | grep nvidia
nvidia.com/gpu: "1"
```

**Comment by primeroz** [comment]
the `nvidia-gpu-device-plugin` image we are using is from 2019 and not really sure what / who is building it 

*crane ls k8s.gcr.io/nvidia-gpu-device-plugin* 
```
    "sha256:4b036e8844920336fa48f36edeb7d4398f426d6a934ba022848deed2edbf09aa": {
      "imageSizeBytes": "6816709",
      "layerId": "",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "tag": [
        "4baa941d8df91e5dc1736adea74ce54e564dd782"
      ],
      "timeCreatedMs": "1559171865074",
      "timeUploadedMs": "1583461642018"
    },

```

the newest image in that repo is from `2020` 
```
    "sha256:ebd0d26fb21ae9c7d11da156737006ceff085029c697a3a163774188c3328dbe": {
      "imageSizeBytes": "6920214",
      "layerId": "",
      "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
      "tag": [
        "97dad60fbfc0feab9784d2ce1f2578e8fd1050aa"
      ],
      "timeCreatedMs": "1584385789523",
      "timeUploadedMs": "1585357393362"
    },
```

* using the `nvidia` https://github.com/NVIDIA/k8s-device-plugin/tree/main#deployment-via-helm requires enabling the `container toolkit`
*

**Comment by primeroz** [comment]
The investigation is finished, i explored the different possible solutions and created a follow up issue to decide and implement a solution https://github.com/giantswarm/roadmap/issues/2212
