### ISSUE TITLE
Automated testing of CAPI management clusters

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#2119]
## User Story

- As a Giant Swarm Engineer I want to run tests on Giant Swarm management clusters so that I can ensure their quality and reliability.

## Details, Background

Previous efforts from team Rocket around this topic can be tracked [here](https://github.com/giantswarm/roadmap/issues/685).

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2118
- [ ] https://github.com/giantswarm/roadmap/issues/2219
- [ ] https://github.com/giantswarm/roadmap/issues/2220
- [ ] https://github.com/giantswarm/roadmap/issues/2255
- [ ] https://github.com/giantswarm/giantswarm/issues/28840
- [ ] https://github.com/giantswarm/roadmap/issues/2930
```
