### ISSUE TITLE
Align CAPA schema with RFC55

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2144]
## Story

Align CAPA schema with [RFC55](https://github.com/giantswarm/rfc/pull/55).

## TODOs

- [x] https://github.com/giantswarm/roadmap/issues/2225;
- [x] https://github.com/giantswarm/roadmap/issues/2236;
- [ ] https://github.com/giantswarm/talanx/issues/132;

**Comment by alex-dabija** [comment]
This is done.
