### ISSUE TITLE
Migrate to the new monitoring infrastructure 

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#215]
## User Story

_- As a Giant Swarm engineer, I want to use new sharded Prometheus servers to monitor my components, so that we can get rid of the existing monitoring._

## Blocked by / depends on

- [ ] #10 Setup Control Plane Prometheus

## TODO

- [x] https://github.com/giantswarm/giantswarm/issues/13763 Transfer alerts to a new Monitoring infra
- [x] https://github.com/giantswarm/giantswarm/issues/13725 Fix Grafana dashboards taking into account the new labeling schema of metrics
- [x] https://github.com/giantswarm/giantswarm/issues/13092 Add support for Cortex in TC and CP Prometheus 
- [x] https://github.com/giantswarm/giantswarm/issues/13007 check if all CPs from the list were upgraded
- [x] Check and adjust sizes of all CPs afyer migration
