### ISSUE TITLE
Teleport Preparation for PoC

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2193]
```[tasklist]
### Tasks
- [x] where and how to deploy teleport server, especially for PoC setup
- [x] how to generate and use tokens to access central teleport from the nodes/clusters
- [x] prepare and scope a PoC to prove the setup working
- [x] start to write apps for teleport agents and potentially server
- [x] potentially start to write the controller for token generation / rotation
```

**Comment by tuladhar** [comment]
`kube-node-agent` is deprecated, so we need to rely on Teleport SSH server.

Below is the conversation with Teleport engineer.

![Image](https://github.com/giantswarm/roadmap/assets/5674762/015ed215-3d63-4df2-9144-52db7a1ae1e2)

**Comment by tuladhar** [comment]
Tasks details mentioned in [this document](https://docs.google.com/document/d/1Ogvv36Urv8iq-slV0DpdvNShb0tU-04t-GK1Hq3cFkc/edit#)

**Comment by gawertm** [comment]
nice, maybe you can walk the team through it in tomorrows refinement?

**Comment by tuladhar** [comment]
yeah, sounds good.

**Comment by tuladhar** [comment]
Teleport walkthrough [slides](https://docs.google.com/presentation/d/1DYUaGhFWKkBhN1YSoqN6RO-_bVbJu6GvD3w2PPhi9vI/edit#slide=id.g24ed69a7753_0_292) presented to team.

**Comment by tuladhar** [comment]
Teleport cluster (standalone) for PoC - https://teleport.demo.gaws.gigantic.io (GitHub SSO enabled)

**Comment by gawertm** [comment]
![image](https://github.com/giantswarm/roadmap/assets/56695351/a8992c0b-21d5-4fd4-b6c3-7e28bbc693ae)

If I want to login with Github, it asks me to authorize "tuladhar"

**Comment by gawertm** [comment]
also there is this warning: "Teleport v13.1.0 is now available, please consider upgrading your Cluster."
any reason we didnt test with latest teleport version?

**Comment by tuladhar** [comment]
> also there is this warning: "Teleport v13.1.0 is now available, please consider upgrading your Cluster." any reason we didn't test with latest teleport version?

Wow, Teleport v13.1.0 was just released few days ago. I'll test it and upgrade.

**Comment by tuladhar** [comment]
@gawertm Authorized issue fixed now.

![Screen Shot 2023-06-08 at 7 21 46 PM](https://github.com/giantswarm/roadmap/assets/5674762/b6e8562f-0e3b-4d03-a994-2b7d993cdb12)

**Comment by tuladhar** [comment]
Upgraded to Teleport v13.1.0

**Comment by gawertm** [comment]
side note on join token for ssh. with flatcar, we might need to do it with ignition

**Comment by tuladhar** [comment]
As discussed in the standup, here’s a rough diagram around `teleport-kube-agent-app` deployment architecture. Initially, for Kubernetes API access, the plan was on having `teleport-kube-agent-app` in `default-apps` collection, but with this approach, we saw a challenge of injecting teleport join token as secret on workload cluster specially. As such, to get around this, we need to deploy `teleport-kube-agent-app` from the `teleport-operator` which is running in management cluster, similar to I believe how we do it with dex app.


![Image](https://github.com/giantswarm/roadmap/assets/5674762/2d772218-9f72-4fa2-a907-4f4a12e17faf)

**Comment by tuladhar** [comment]
## Summary

### where and how to deploy teleport server, especially for PoC setup
- **where** 👉  AWS Giantswarm Account (frankfurt region)
- **how** 👉  Using official Teleport HA setup on AWS using Terraform. https://github.com/giantswarm/teleport-ha-autoscale-cluster/

**UI Access**
You can access the Teleport cluster via WebUI: test.teleport.giantswarm.io via GitHub integration.
- Click on "Other sign-in options" -> "GitHub"


**Terminal Access**
You can access the Teleport via CLI using `tsh` client.
1. Install Teleport `tsh` client
2. Login to cluster
`tsh login --proxy test.teleport.giantswarm.io --auth github`


### how to generate and use tokens to access central teleport from the nodes/clusters
- how 👉 `teleport-operator` deployed on MC which authenticated to teleport cluster via long-lived identity certificate file generated the short-lived tokens for registering nodes/cluster to teleport. `teleport-operator` will be deployed via MC bootstrap where identity file is supplied from LastPass. 
- `use tokens` 👉 there are two ways tokens are used. 1) SSH - `teleport-operator` creates a secret called `$CLUSTER-teleport-join-token` in cluster namespace by re-conciling Cluster CRs, then `cluster-aws` uses the secret to install teleport daemon and join the node for SSH access. 2) Kubernetes - `teleport-operator` creates short-lived token on demand and deploys `teleport-kube-agent-app` on management cluster as well as workload clusters by reconciling Cluster CRs.


### prepare and scope a PoC to prove the setup working
- Scope:
1. Kubernetes Access for Management / Workload Cluster
2. SSH Access for Management / Workload Cluster Nodes

### start to write apps for teleport agents and potentially server
- [teleport-kube-agent-app](https://github.com/giantswarm/teleport-kube-agent-app)
- [cluster-aws](https://github.com/giantswarm/cluster-aws/pull/334)

### potentially start to write the controller for token generation / rotation
- [teleport-operator](https://github.com/giantswarm/teleport-operator)

**Comment by gawertm** [comment]
this looks like an amazing milestone towards teleport. 
I also checked the UI and on top I can see a drop-down for the cluster. Is this where we can potentially switch to other teleport "leaf servers" e.g. for customers that want their own instance? or how would we handle this?

**Comment by tuladhar** [comment]
Yes @gawertm, in the drop-down for the cluster is where we can potentially switch to other teleport "leaf servers" clusters.
