### ISSUE TITLE
Kubernetes Release v1.17

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#22]
### Preparation steps
* [ ] Read [upstream changelogs](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.17.md#v1172) for any important changes.
* [ ] Establish component upgrade targets
  * [ ] Calico v3.11/v3.12
  * [ ] etcd v3.3.18/v3.4.3
  * [ ] Container Linux v2303.3.0
* [ ] Ensure that `retagger` has correctly tagged all targeted component versions during automatic nightly retagginig in Quay and Aliyun
* [ ] Create a PR in `k8scloudconfig`/`ignition-operatoor` with the new components versions and any other required changes
* [ ] Check Prometheus rules for deprecated metrics and fix them if necessary
* [ ] Establish common release notes and create WIP releases for each platform
* [ ] Do we need to change our own resources within the tenant clusters?
* [ ] What do we need to communicate to our customers?
* [ ] Anything else that would be better automated for the upgrade?

### Child issues

* [ ] Create WIP platform operator branches for 1.17 testing including component updates only
* [x] [Release cluster-operator with 1.17 compatible apps](https://github.com/giantswarm/giantswarm/issues/8559)
* [x] [Release kvm-operator with 1.17](https://github.com/giantswarm/giantswarm/issues/8561)
* [ ] [Release aws-operator with 1.17](https://github.com/giantswarm/giantswarm/issues/8560)
* [ ] [Release azure-operator with 1.17](https://github.com/giantswarm/giantswarm/issues/8562)
