### ISSUE TITLE
CAPZ: Enable caching on Premium Disks

### ISSUE THREAD

**Issue by primeroz** [giantswarm/roadmap#2203]
### Motivation
CAPZ Supports, and recommends, enabling either RO or RW caching on premium disks to improve performances 
* https://learn.microsoft.com/en-us/azure/virtual-machines/premium-storage-performance#disk-caching 
* https://azure.microsoft.com/en-gb/blog/azure-premium-storage-now-generally-available-2/

This is done by using the `local disk` to the VM to cache data written to the underlying Network disk connected to the instance.

We should at least enable the Read cache but we might consider enabling the RW since the data stored on the OS disk is sort of ephemeral anyway and OS disks are recycled when the node gets recycled 

**Interesingly** and probably wrong, we are using R/W Caching on the etcd disks 

**CP DISKs**
![Screenshot from 2023-03-22 12-29-08](https://user-images.githubusercontent.com/2085772/226891047-ac7ac3f8-4c87-493b-8f4e-b917883ac28d.png)

### TODO

- [ ] Decide what type of cache to enable for OS Disk
- [ ] Decide what type of cache to enable for ETCD DISK 
- [ ] Enable the Cache

### Outcome

**For Customer**
- we have the best performances on disks

**Comment by Rotfuks** [comment]
As this is a pure azure feature, I move it to @giantswarm/team-phoenix - this also might need a review, because of the age of the ticket.
