### ISSUE TITLE
Release AWS v19-beta1

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2205]
ℹ️ Team Phoenix is drafting AWS v19.0.0-beta1 with Kubernetes v1.24 support.
Target release date: 2023-03-31.
Release PR: https://github.com/giantswarm/releases/pull/1099

## Scope
- [x] https://github.com/giantswarm/roadmap/issues/1362
- [x] https://github.com/giantswarm/roadmap/issues/1102
- [x] Ensure monitoring of k8s components
- [x] upgrade of all components
- [x] [node-local-dns-cache for Cilium#1582](https://github.com/giantswarm/roadmap/issues/1582) - add to release notes
- [x] https://github.com/giantswarm/roadmap/issues/2072
- [x] https://github.com/giantswarm/roadmap/issues/2130
- [x] https://github.com/giantswarm/roadmap/issues/2131
- [x] Fix scraping of k8s node local DNS cache app https://github.com/giantswarm/roadmap/issues/2145#issuecomment-1468143074
- [x] fix cncf test failing due to irsa https://github.com/giantswarm/roadmap/issues/2145#issuecomment-1468111820
- [x] VPA 0.13.0
- [ ] https://github.com/giantswarm/giantswarm/issues/23014
- [ ] https://github.com/giantswarm/roadmap/issues/2180
- [x] https://github.com/giantswarm/giantswarm/issues/26243

## Testing Tasks
- [x] https://github.com/giantswarm/giantswarm/issues/25501
- [ ] https://github.com/giantswarm/giantswarm/issues/26139
- [x] https://github.com/giantswarm/giantswarm/issues/26149
- [ ] https://github.com/giantswarm/roadmap/issues/2128
- [ ] Document improvement in pods time to come up ( kubeproxy refresh of iptables vs cilium endpoint refresh)
- [ ] IP space comparison between v18 and v19 - full range instead of 25%

## Pre-Release
- [x] Create release ticket on [Releases board](https://github.com/orgs/giantswarm/projects/136)
- [x] Make an announcement on #sig-product that team is doing a release. Include a link to the ticket from the release board.
- [x] Make sure release was tested by creating new cluster, upgrading from older version and with HelloWorld app.
- [x] Aggregate release notes from all changed components and add to `README.md` in the release directory.
- [x] Send draft release announcement to #sig-product for review ASAP.
- [ ] Verify documentation is up to date.

## Releasing
- [x] Create release PR
[Instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/)
    - [x] Define new release in `release.yaml` file.
    - [x] Activate new release by setting `state` to `active`.
    - [x] Deactivate old release if it's within same major version (`state: deprecated`). Verify with PO if you have doubts.
    - [x] Check versions of all components included. They shouldn't be lower than those in the previous release unless there was a rollback.

[Example PR](https://github.com/giantswarm/releases/pull/318)
- [x] Release relevant operators.
    - [x] Tag release branch.
    - [x] Bump operator version in draft release.
- [x] Make sure that WIP releases in releases repo branch are removed and not merged to master since the master branch is deployed automatically after merging PR and that would make WIP releases visible in customers’ installations which should generally not happen.

## Post-Release
- [ ] Update front-end cluster with the new release.
- [ ] Verify release is available on all installations. You can use [this script](https://github.com/giantswarm/azure-operator/blob/25bf788946c5405532b3b4b76c54b8e685ee291b/scripts/list-releases.sh).
- [ ] Send out release announcement to all customers according to [these instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/#release-notes).
- [ ] PO subscribes to release posts on Slack to get notifications if there are follow-up messages.
- [ ] Close release task on Releases board.

**Comment by ashwaq06** [comment]
I am new to the open source contribution and I have knowledge on various AWS services. I have potential to work on this issue it would be great if this issue is assigned to me

**Comment by whites11** [comment]
> I am new to the open source contribution and I have knowledge on various AWS services. I have potential to work on this issue it would be great if this issue is assigned to me

Thanks for offering to help! This repository is public and this issue is publicly visible because we want to give our customers visibility over our processes and product. Unfortunately, this is not a repository where we can accept contributions from the open source community.
