### ISSUE TITLE
Weave GitOps UI - Engage customers and define access

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#2241]
```[tasklist]
### Tasks
- [ ] Weave GitOps UI - engage with interested customers
- [ ] Weave GitOps UI - Rollout for interested customers
- [ ] Weave GitOps UI - decision to be taken over: roll out for all customers using Flux or opt-in only for interested customers
```

**Comment by mproffitt** [comment]
This can be closed as not achievable
