### ISSUE TITLE
Convert MC-bootstrap test to using webhook triggers

### ISSUE THREAD

**Issue by AverageMarcus** [giantswarm/roadmap#2248]
Currently there is a CronJob that triggers a Tekton TaskRun every 1 minute to look for new comments in mc-bootstrap PRs. This causes 2 new pods to be created and completed every 1 minute meaning that old pods from test runs are cleaned up very quickly. 
Kubernetes seems to keep a max of 10 completed pods around and once there is a new one it cleans up the oldest, including the logs. This generally means that unless watching the E2E tests as they run you'll rarely see the logs in the Tekton Dashboard making it largely irrelevant.

Acceptance criteria:
- [ ] mc-bootstrap uses webhook triggers
- [ ] all cron jobs that are not needed anymore are cleaned up

**Comment by AverageMarcus** [comment]
Alternatively (or more as a temp workaround) we could attempt to override the GC value specified here: https://github.com/giantswarm/k8scloudconfig/blob/fa079ab63b283ea892006206b83a18cec7f4a713/files/manifests/k8s-controller-manager.yaml#LL37C20-L37C20

We'd need to use k8s-initiator-app to modify that manifest on the control plane nodes.

**Comment by ericgraf** [comment]
The mc-bootstrap-ci daily builds trigger should also be updated to use this.

**Comment by AverageMarcus** [comment]
**ToDo:**
- [ ] Trigger `cleanup-installations` from `/run` command - https://github.com/giantswarm/mc-bootstrap/pull/574
- [ ] Trigger `generate-mc` from `/run` command - https://github.com/giantswarm/mc-bootstrap/pull/574
- [ ] Trigger `all-provider` from `/run` command
- [ ] Remove `process-pr-comments` task
- [ ] Remove detect comment TriggerTemplate and EventListener 
- [ ] Remove detect comments CronJob
- [ ] Rename `build-image-generate-mc` to `generate-mc` or maybe `test-create-mc` or similar
