### ISSUE TITLE
Move CPI/CNI/CSI to cluster-azure app

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2271]
### Motivation
With the motivation to create one common default-apps chart for all Giant Swarm Providers, we need to move all CAPZ specific apps that we need to our cluster-azure chart, so that we have no requirement for provider specific apps in our default-apps chart anymore and can reduce the multiple individual provider specific default-apps-<provider> charts to one single default-apps chart.

### Status
The actual migration is currently blocked by https://github.com/giantswarm/giantswarm/issues/26735

Instructions are in this comment - https://github.com/giantswarm/roadmap/issues/2271#issuecomment-1542349551 

### Todo
- [x] Move all CAPZ specific resources from default-apps-capz to cluster-azure. 
  - Take https://github.com/giantswarm/giantswarm/issues/23449 in consideration for reference what needs to move
- [x] Cleanup the default-apps-capz chart by removing the capz specifics and test that everything still works.
- [x] Check with Rocket and Hydra on how we can migrate existing Cluster
- [x] Test MC Creation
- [x] Test WC Creation
- [x] Test Exisiting Cluster Migration - https://github.com/giantswarm/roadmap/issues/2271#issuecomment-1538429945
- [x] Review issue described in https://github.com/giantswarm/roadmap/issues/2271#issuecomment-1538533679
- [ ] wait for https://github.com/giantswarm/giantswarm/issues/26735 to be solved
- [ ] Sync this change with https://github.com/giantswarm/giantswarm/issues/25360 - if the `kube-proxy-replacement` is done before this then some changes to this will be required 

### Outcome
- We no longer need to maintain the default-apps-capz chart but can rely on Giant Swarms general default-apps chart to get giant swarm context specific apps installed.

**Comment by primeroz** [comment]
### Notes to Self

* depending on when the https://github.com/giantswarm/giantswarm/issues/25360 is merged we will need to update / change the Cilium CNI kube-proxy-replacement settings condition in mc-bootstrap - see https://github.com/giantswarm/mc-bootstrap/pull/514#discussion_r1180761706

**Comment by primeroz** [comment]
### Diff and review

#### azure cloud controller manager ( 1.24.5 vs 1.24.18 ) 
* Missing VPA in Helmrelease one 

#### azure cloud node manager ( 1.24.5 vs 1.24.18 )
*  Missing VPA in Helmrelease one 

#### azuredisk csi driver
* Missing Storage Class `managed-premium` in the helmrelease one
* Missing VPA in helmrelease one 

#### cilium
* Can't compare due to upgrade ( COnsider not upgrading ) 

#### Coredns
* looks ok

**Comment by primeroz** [comment]
### Potential risk 

With the `cilium cni` being moved to `helmrelease` if something goes wrong during the rollout helmrelease will do a rollback of the chart 

in the case of cilium if the update was of a version like `0.6.1` -> `0.9.3` a rollback will break the cluster networking making the cluster completely unavailable 

In the case of azure when 
* the master node rolls there are brief moments in which the nodes are `not ready` and the `apiserver endpoint` returns an error because of the master nodes being drained still receiving requests - see https://github.com/giantswarm/roadmap/issues/1934
  * this is normally not a big issue since the errors are brief and clients will reconnect and reconcile
* with the `chart-operator` managing the helm installations this won't happen since the operator runs in cluster and it does not use the load balancer to talk to the control plane 
* with `helmreleases` the MC cluster does use the load balancer to reach the control plane , this means it can experience brief moments of failed connectivity during a release
* **IF the release** is marked as failed a rollback is initiated. 
* **IF this happens to cilium** during an upgrade from `0.6.1` to `0.9.3` the cluster will break  , so far i have not found any good way to fix it ( i suspect with ciliumctl installed on the node it might be possible )

**Comment by primeroz** [comment]
### MC Creation test

```
export OPSCTL_GITHUB_TOKEN=`gopass cat giantswarm/opsctl/OPSCTL_GITHUB_TOKEN`
export INSTALLATION=gs-francesco-cxi
export CUSTOMER=GS
export PROVIDER=capz
export NONINTERACTIVE=0
export NEW_TEST_INSTALLATION=1
export CLUSTER_APP_CATALOG=cluster-test
export CLUSTER_APP_VERSION=0.0.20-dc4ee77d601e4efdf06c7ab89c1b3c85af5278fe
export DEFAULT_APPS_APP_CATALOG=cluster-test
export DEFAULT_APPS_APP_VERSION=0.0.16-478ecaa52e75a9ea53a61fe90bfd3c39d889c17f

make create-config
export AGE_KEY=$( lpass show "Shared-Dev Common/Installations/gs-francesco-cxi.agekey" --notes)
make generate-mc
```

**Comment by primeroz** [comment]
### Upgrade Instructions 

#### Prep

The Migration is blocked until https://github.com/giantswarm/giantswarm/issues/26735 is solved

Also, if by the time this is unblocked https://github.com/giantswarm/giantswarm/issues/25360 has been merged, some updates will be required 

* mc-bootstrap
  * https://github.com/giantswarm/mc-bootstrap/blob/main/scripts/deploy-mc.sh#L182 - Add support for `kube-proxy-replacement` 
* cluster-azure
  * https://github.com/giantswarm/cluster-azure/pull/124/files#diff-0139bd500c04e420b6f6a91e15af54ded8c6a26312968b6127d36518bf37685bR35 - Add support for `kube-proxy-replacement` 

#### PRs to Merge for this change

* https://github.com/giantswarm/mc-bootstrap/pull/529
* https://github.com/giantswarm/default-apps-azure/pull/78
* https://github.com/giantswarm/cluster-azure/pull/124

#### Migration 

based on https://github.com/giantswarm/giantswarm/issues/26755

0. Do a release of default-apps and cluster-azure 
1. Pause and delete all APPS to be migrated into helmreleases - **MC Cluster Kube Context**
```
org="multi-project"
cluster="cluster1"
for app in azure-cloud-controller-manager azure-cloud-node-manager azuredisk-csi-driver cilium coredns; do
    kubectl annotate app -n "org-${org}" "${cluster}-${app}" "app-operator.giantswarm.io/paused=true"
    kubectl patch app -n "org-${org}" "${cluster}-${app}" --type=merge -p '{"metadata":{"finalizers":[]}}'
    kubectl delete app -n "org-${org}" "${cluster}-${app}"
done 
```

2. Pause and delete all the CHART CRs on the WC - **WC Cluster Kube Context**
```
cluster="cluster1"
for app in azure-cloud-controller-manager azure-cloud-node-manager azuredisk-csi-driver cilium coredns; do
    kubectl annotate chart -n giantswarm "${app}" "chart-operator.giantswarm.io/paused=true"
    kubectl patch chart -n giantswarm "${app}" --type=merge -p '{"metadata":{"finalizers":[]}}'
    kubectl delete chart -n giantswarm "${app}"
done
```

3. This will leave your cluster with the pods running but App anc Chelm CRs gone
4. Deploy `cluster-azure` upgraded with HelmReleases
5. Deploy `default-apps version` without the migrated apps
6. Wait , a full restart of all pods involved
7. Wait, all helm releases must be reconciled
8. Wait, all nodes will be replaced
9. Finished
10. Repeat for all clusters

**Comment by primeroz** [comment]
The fix this change require is `months away` so i am unassigning this from myself

**Comment by primeroz** [comment]
all capz clusters ( other than cuckoo/wc1 which is broken ) are migrated to helmreleases.
