### ISSUE TITLE
Revamp Ingress Controller setup (Optional NGINX Ingress Controller)

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#23]
## User Story

As a customer, I would like to have the option to not have Nginx Ingress Controller installed in all my clusters by default, so we don't waste resources in cases where we don't need to expose any endpoints.

As a customer, I would like to have the option to not have Nginx Ingress Controller, so I can run a different Ingress Controller that we need. For example, I need an API Gateway, or I use a service mesh and it contains an ingress controller.

As a customer, I would like to have the option to install the Nginx Ingress Controller only internally, so my service can use it to communicate internally without exposing endpoints to the Internet.

## TODO

- [x] Move LB/DNS logic out of the aws operator
  - [x] Remove DNS/ELB set up logic from aws operator 
  - [x] Modify IC to provide LB annotation to provision the ELB
  - [x] Add cert-manager as default managed application
    - [x] monitor for not satisfied
  - [x] Add kiam as a default managed application
    - [x] Precreate kiam role / reuse master role
    - [x] monitor for not satisfied
  - [x] Add external DNS with the proper configuration
    - [x] Precreate external-dns role with proper policy in operator
    - [x] Add cleanup resource for hosted zones which will ensure all the records except SOA and NS are cleaned up from hosted zone so that CF can delete it
    - [X] Set proper IAM policies for the service for Fer's customer
    - [x] Add external dns as managed service
    - [x] monitor for not satisfied
- [x] Make possible to select nginx class for nginx controller ingress
- [x] Make possible to select between internal or external ingress controller (i.e. add annotation option of service of type LB to IC user config)
- [x] migrate nginx ic to App CR and make default everywhere except clusterapi
- [ ] update docs on hello-world app with examples on installing IC from catalog
- [x] Stretch Goal: Ingress Controller should be completely optional (this depends on us being able to add apps to clusters on creation time)

## Details, Background

Right now our ingress controller (IC) is installed by default in all clusters. We have customers that have different ingress controller and they waste resources. Also, some customers will like to not expose ingress endpoints by default. Currently, in AWS and Azure, we provision an LB pointing to the workers for the default ingress controller (exposed as nodePort). 

On the other hand, we have moved the ingress controller to be run by the chart operator. The configuration of the IC chart is managed in cluster operator. This is moving to app catalog operators. Ideally, ingress controller will be part of the catalog and users will choose to install which IC is deployed and which flavor (external/internal). At the same time, it will allow us to offer more than one IC solution (out of scope right now).

## Customers driving/requiring this

I think all customer have one or other interest in this development

## **UPDATE 17.10.19**

- For full optionality of IC with a similar simple setup like now (i.e. not requiring customer to set up custom things in AWS) we would additionally need ‘kiam’,‘external-dns’, and ‘cert-manager’
- ‘external-dns’ is already a default app on Azure
- ‘kiam’ would increase overall security of our setup, especially making customer workloads that needs access to AWS resources more secure
- ‘cert-manager’ is an app that most customers are anyway running and would welcome us taking over its management
- Having those apps in AWS clusters would mean we could get rid of a lot of hard coding in aws-operator
- It would also mean that the load balancer would be configurable, e.g. to set it to internal
- It would mean we do not need to take care of it when we add node pools and stuff
- It would mean that even the default DNS entry for ingress is configurable
- based the above we decided to make those 3 apps new default apps for AWS clusters
- the actual Ingress Controller then is fully replaceable, so a customer could use our default components to run Traefik and at some point we would also be able to run other ICs like for service meshes or if there’s clsuters that will only have Kong
