### ISSUE TITLE
Implement best practices for `coredns` app

### ISSUE THREAD

**Issue by LolloneS** [giantswarm/roadmap#2311]
Coming from [here](https://github.com/giantswarm/roadmap/issues/2066).

The goal of this issue is to have the App eventually adhere to standard cloud-native best-practices. The points below are to be considered non-exhaustive. Feel free to add some that make sense and remove some that don't. If this issue does not make sense (e.g. is a duplicate or covers a deprecated app) please close it.

Expected outcome:
- [x] the app has properly set PDBs (as percentages)
- [x] the app can scale horizontally based on Custom Metrics (if it makes sense)
- [x] the app runs with more than 1 replica by default (if it needs HA)
- [x] the app does not use `emptyDir` volumes if not strictly necessary

**Comment by mcharriere** [comment]
- the app has properly set PDBs (as percentages)
This app already has PDB as percentages. Reviewing the chart I noticed that the PDB and the updateStrategy are using the same values for its configuration.

This is not really desired and could potentially cause problems. I created a PR to decouple the values, leaving PDB maxUnavailable in 25%.

**Comment by mcharriere** [comment]
I also added the option to use custom metrics for scaling in a new PR. Also created this issue https://github.com/giantswarm/giantswarm/issues/26942 for research, because scaling based on cluster size rather than usage might make more sense.

**Comment by mcharriere** [comment]
> the app runs with more than 1 replica by default (if it needs HA)

It does already.

> the app does not use emptyDir volumes if not strictly necessary

It does use emptyDir, and it seems to be well justified
