### ISSUE TITLE
Add display columns to appcatalog, app, and chart CRD to show more info

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#235]
Add display columns to appcatalog, app, and chart crd, to show more info such as which namespace, version, etc.

## User Story

- As a ROLE, I would like FEATURE so that REASON

## Tasks

- [x] Update apiextensions with new columns definitions
  - [ ] appcatalog
  - [x] app
  - [x] chart

- [x] Release new apiextensions

- [x] Ensure CRDs in all CPs

**Comment by tomahawk28** [comment]
I would take this issue for the next week.

**Comment by rossf7** [comment]
The extra columns for app and chart CRDs are deployed to all CPs.

Only CRD missing is appcatalog but it's not that useful IMO.
