### ISSUE TITLE
create privateEndpoint DNS records in the MC

### ISSUE THREAD

**Issue by bavarianbidi** [giantswarm/roadmap#2376]
### Motivation

To get "private Azure Clusters" working by doing `privateEndpoints`, a DNS-Record for the private Endpoint must be created in the management Cluster.

### Todo

```[tasklist]
### open
```

```[tasklist]
### in review
- [x] add some documentation to our public handbook
```

```[tasklist]
### done
- [x] create alerts
- [x] create an opsrecipe
- [x] document the private-endpoint solution
- [x] implement business logic
- [x] introduce new metrics
- [x] create unit-tests
```

### Outcome

ManagementCluster is able to resolve `apiserver.WC.azuretest.gigantic.io` and `bastion.WC.azuretest.gigantic.io` to the IP of the private Endpoint which is linked in the MC itself.

**Comment by bavarianbidi** [comment]
all open tasks got closed by merging all remaining open PRs. close the issue for now.

Some notable links:
* intranet documentation: https://intranet.giantswarm.io/docs/product/providers/capz/capz-cluster/
* opsrecipe for private capz cluster: https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/capi-cluster/#capz
* dns-operator-azure docs: https://github.com/giantswarm/dns-operator-azure/blob/main/README.md
