### ISSUE TITLE
Deprecation of node-role.kubernetes.io/master taint

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2389]
from slack:  https://gigantic.slack.com/archives/C2MS2VB37/p1678272890100239
The [node-role.kubernetes.io/master](http://node-role.kubernetes.io/master) taint is deprecated and will be removed in kubeadm version 1.25
([source](https://kubernetes.io/docs/reference/setup-tools/kubeadm/implementation-details/))

But we still use it as toleration to run certain applications on control plane nodes. We should migrate. From a very short look on the repos I have cloned, quite a few important apps are affected.

also mentioned here: https://gigantic.slack.com/archives/C01F7T2MNRL/p1680682638680759

```[tasklist]
### Sub-Tasks for Teams
- [ ] https://github.com/giantswarm/roadmap/issues/2468
- [ ] https://github.com/giantswarm/roadmap/issues/2471
- [x] Honeybadger: Deprecation of node-role.kubernetes.io/master taint
- [x] Shield: Deprecation of node-role.kubernetes.io/master taint
- [x] Atlas: Deprecation of node-role.kubernetes.io/master taint
- [ ] https://github.com/giantswarm/roadmap/issues/2435
- [ ] https://github.com/giantswarm/roadmap/issues/2500
- [ ] https://github.com/giantswarm/roadmap/issues/2396
- [x] Hydra: Deprecation of node-role.kubernetes.io/master taint
```

**Comment by gawertm** [comment]
to be moved into new Lifecycle Management Team soon and tracked further in their backlog cc @Rotfuks

**Comment by fiunchinho** [comment]
@giantswarm/team-hydra already took care of this here https://github.com/giantswarm/roadmap/issues/2135

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas work is done. We have only one app left that will not be changed because it is deprecated:
https://github.com/giantswarm/efk-stack-app/commit/ec23f9f45d6ccf493cb4acfbbb118f539f02d596

**Comment by fhielpos** [comment]
@giantswarm/team-shield is done 🚀

**Comment by uvegla** [comment]
HoneyBadger is done 🚀 (https://github.com/giantswarm/roadmap/issues/2424)

**Comment by mcharriere** [comment]
Cabbage is done 🚀

**Comment by primeroz** [comment]
in capz we started with version 1.24 which means our control plane nodes have both taints on them

Apps running on capz MC still using the `master`
* [ ] capi-XXX controllers - both master and control-plane tolerations
* [ ] capz-controller - both master and control-plane tolerations
* [ ] etcd-backup-operator - both master and control-plane tolerations
* [ ] promtail - both master and control-plane tolerations
* [ ] azure-cloud-controller-manager - both master and control-plane tolerations
* [ ] cert-manager-cainjector - **only master toleration**
* [ ] cert-manager-controller - **only master toleration**
* [ ] cert-manager-webhook - **only master toleration**
* [ ] coredns-controlplane - both master and control-plane tolerations
* [ ] csi-azuredisk-controller - both master and control-plane tolerations
* [ ] csu-snapshot-controller - both master and control-plane tolerations

**Comment by mogottsch** [comment]
@primeroz I already worked on this migration for the repos of phoenix, rocket and rainbow.
If you want I can also work on yours from clippy/turtles.

**Comment by mogottsch** [comment]
Regarding

> * [ ]  cert-manager-cainjector - **only master toleration**
> * [ ]  cert-manager-controller - **only master toleration**
> * [ ]  cert-manager-webhook - **only master toleration**

This depends on the chart version of the `cert-manager-app`.
`glippy` uses version `2.19.0`, which does not have a toleration for the new taint.
`gaggle` uses version `2.21.0`, which has the new toleration.

@primeroz will get  `gaggle` up-to-date.

**Comment by primeroz** [comment]
@mogottsch all cert-managers for capz are now addressed.

I don't think there was anything else on capz left to do right ?

**Comment by mogottsch** [comment]
@primeroz That was all for capz, I closed the clippy issue :+1:

**Comment by primeroz** [comment]
@mogottsch thanks

i see we only have some of the `phoenix` issues . Are you working on those or need support with it ? otherwise i will remove myself from the issue and just leave it in `in progress` on the turtles board

**Comment by mogottsch** [comment]
@primeroz I'm not working on the phoenix issues anymore. Those that are still open need manual testing and I don't have to knowledge to do that. AFAIK phoenix is on it, though. cc @whites11

**Comment by T-Kukawka** [comment]
there are PRs to be reviewed and i can keep track of Phoenix issue so u could close this one
