### ISSUE TITLE
FluxCD app: Deploy and run for gitops config management (internal)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#239]
Towards https://github.com/giantswarm/roadmap/issues/175

## User Story

As an App Developer, I would like FluxCD so that it can synchronize the App, ConfigMap, and Secrets from a Github repo with the CP cluster for a specific namespace (so it applies to a specific TC).

## Tasks

- [x] research: how to make it work
- [ ] prepare fluxcd app in playground https://github.com/giantswarm/flux-app
- [ ] deploy to CP
- [ ] test if we can use it to deploy App CRs to selected TC

**Comment by cokiengchiara** [comment]
Mon, 07. December 2020

From @webwurst : Experimental stuff did work. We have one page to follow along and try out.

**Comment by cokiengchiara** [comment]
Mon, 11. Jan 2021 Gerald has something cooked up w Kustomize. Go forward and try with App Platform. @webwurst will have call w @ubergesundheit to sync.

**Comment by cokiengchiara** [comment]
@ubergesundheit , @webwurst is it done? 

If yes, could we maybe create some documentation on how to use it, its value, etc.? :) (create new issue)

Then, can we close this issue?

**Comment by ubergesundheit** [comment]
There are some issues to solve for flux

- Installation of flux CRs through does not work all the time
- Upgrading at this point is not possible because kustomize fiddles with selectors.matchLabels too much
- We're on 0.5.9 of flux while upstream is at 0.7.3

**Comment by cokiengchiara** [comment]
@ubergesundheit the unreleased stuff in Flux addresses and closes this issue? 😀  https://github.com/giantswarm/flux-app/blob/master/CHANGELOG.md#unreleased

**Comment by ubergesundheit** [comment]
[Release v0.1.0](https://github.com/giantswarm/flux-app/releases/tag/v0.1.0) at least adresses the issue with the matchLabels. For version upgrades I prepared https://github.com/giantswarm/flux-app/pull/15 and https://github.com/giantswarm/flux-app/pull/16.

while testing https://github.com/giantswarm/flux-app/pull/15, the issue with CR installation did not appear for me again. 

While the current changes need to be released, I think this issue can be closed.
