### ISSUE TITLE
Improve VPA alerting

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2394]
We are currently alerted about VPA via the ServiceLevelBurnRateTooHigh

It oftenly happens those are non critical alerts; e.g. vpa recommender stopped working

We do not want to be alert by such issue at night or outside working hours.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/26922
- [ ] Remove VPA from the actual ServiceLevelBurnRateTooHigh alert
- [x] Define VPA availability alert
```

**Comment by QuentinBisson** [comment]
Will be closed by https://github.com/giantswarm/prometheus-rules/pull/805

**Comment by QuantumEnigmaa** [comment]
Updates concerning this issue : 
- The VPA query used for the Sloth SLO will be moved to the `prometheus-rules` repo as a plajn prometheus rule to avoid it from paging all the time and still be useful. The corresponding alert will take over the name of the current SLO --> https://github.com/giantswarm/prometheus-rules/pull/833
- The Sloth SLO will be updated to match the SLO requirements and will evaluate the availability of the VPA's components (whereas the alerting rule from above will page when one of those component has been crashlooping/restarting too much in the past 10min)

**Comment by QuantumEnigmaa** [comment]
All merged now. Only remaining task to do is enhancing the SLO query and/or objective
