### ISSUE TITLE
Enable App Updates

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#24]
Right now, you can update by choosing the version in the version picker. However, things will break if things are not configured correctly. There is no migration path for configuration values. 

As an app user, I want to be able to update apps.

## Related Stories
- [x] UX for Updates (version picker)
- [ ] Notification about Updates (As an end user developer, I want to get notified where there is a new version of an app I have installed.)
- [ ] Automated updates through "update-operator" (As an end user developer, I want to be able to specify how updated I want my app to be within a certain major / minor boundaries and have the app be automatically updated according to those specifications.) - but don't encourage until configurations are safe

**Comment by cokiengchiara** [comment]
Close this issue as you updating apps are now enabled. Create issues for two other tasks.

**Comment by cokiengchiara** [comment]
Closing this as one can already update an app using the version picker in Happa. See: https://share.getcloudapp.com/NQuDewn1

Created separate issues to track the other two https://github.com/giantswarm/roadmap/issues/124 and https://github.com/giantswarm/roadmap/issues/123. They are not a priority.
