### ISSUE TITLE
Linkerd app is running in Operations and Frontend clusters

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#240]
Towards https://github.com/giantswarm/roadmap/issues/175

## Outcome
* Figure out if we can bypass the problem of changing PSPs of existing deployments. Test if we can use Linkerd's CNI for this.

(Context: We think we can. But if we cannot, it would be too much work to change PSPs for existing clusters. It is still viable for new clusters because we change how we do PSPs moving forward to accommodate this.)

* If yes, deploy to and run in our target TCs (frontend, operations, and maybe also Loki)

## Tasks

- [x] test if we can use linkerd's CNI driver to bypass the problem of changing PSPs of existing deployments https://github.com/giantswarm/giantswarm/issues/14500
- [x] upgrade chart to 2.9 https://github.com/giantswarm/giantswarm/issues/14190
- [x] investigate using cert-manager for the trust anchor (this should be easier in 2.9)
- [x] test what disruption switching CNI on a live cluster will cause
- [x] assuming CNI driver works, prepare a new app for it or include as an option in the existing linkerd chart
- [x] prefer to keep it as a separate chart for less complexity
- [x] deploy to our target TCs: frontend, operations and maybe also loki https://github.com/giantswarm/giantswarm/issues/13762

**Comment by cokiengchiara** [comment]
@glitchcrab can you share the progress you made w Linkerd? 😁

**Comment by glitchcrab** [comment]
yes!

disruption:

- no disruption caused. this is because the deployment of the chart does not replace the existing CNI config, it only extends it. the additions to the config are only used by k8s pods which have opted into routing via the service mesh (via annotations).

- cni app:

this is implemented under a separate chart (https://github.com/giantswarm/linkerd2-cni-app)

**Comment by glitchcrab** [comment]
regarding the PSP situation - I talked with upstream and they need to keep the emptyDir permission because the proxy sidecars have a read-only filesystem so they cannot store the certs in the container's filesystem. **Therefore any app deployed on top of Linkerd+CNI must allow emptyDirs.**

Whilst this isn't perfect, it's relatively minor change from a security perspective.

**Comment by cokiengchiara** [comment]
@glitchcrab nice <3 what is left in order to deploy to and run in our target TCs (frontend, operations, and maybe also Loki)? :D

**Comment by glitchcrab** [comment]
nothing as far as i'm aware! just to change the PSPs of the apps which will run in the mesh, but linkerd+cni are ready to go.

**Comment by cokiengchiara** [comment]
> nothing as far as i'm aware! just to change the PSPs of the apps which will run in the mesh, but linkerd+cni are ready to go.

Nice! I saw there are some slack chats about something fishy 🤷‍♀️  what are they? Maybe write it down here?

Then, should we ping sig-opsprocess and sig-frontend about deploying in their clusters?

**Comment by glitchcrab** [comment]
We've deployed it to the Loki cluster so I've marked that as done.

Regarding using cert-manager as the trust-anchor, the idea works fine in 2.9 but some work needs to be done to support the changes because of the need for a custom linkerd controller image (see giantswarm/giantswarm/issues/15380). I've been working on this in the background.

**Comment by cokiengchiara** [comment]
thanks @glitchcrab then this issue is done and I am closing it, is that ok? Please reopen if not.
