### ISSUE TITLE
Operator for adding private endpoints for private WCs

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2403]
### Motivation

Workload clusters with private networking have private VNets and Internal load balancers for API server, so API server is not accessible from the outside of the workload cluster VNet.

In our latest iteration of CAPZ work, we are working on deploying private workload clusters with API server Internal load balancer being accessible via Azure Private Link.

In order for the MC to access private WC API server via the Private Link, we need to deploy Azure Private Endpoint to the MC VNet. CAPZ already supports this, so all we have to do is to update MC AzureCluster CR and add a private endpoint for every private workload cluster. We decided to do this in a custom operator.

### Todo

```[tasklist]
- [x] GitHub repo for the new operator
- [x] Quay repo for the new operator
- [x] CircleCI config for the new operator
- [x] Add new operator to giantswarm/config repo
- [x] Add new operator to giantswarm/github repo
- [x] Add new operator to the capz-app-collection
- [x] Implementation: For every private workload cluster, ensure there is a private endpoint in the management cluster
- [x] Implementation: Let Azure assign private endpoints automatically and then set the private IP value in the CR
- [x] Implementation: When a private workload cluster is deleted, delete the private endpoint
- [ ] https://github.com/giantswarm/roadmap/issues/2620
- [x] Tests: Unit tests for the above logic
- [ ] ~Tests: E2E test coverage for the new logic (check it out with Tinkerers)~ we will cover e2e scenario with e2e tests for private clusters
- [x] Make sure that the new operator is successfully running in the CAPZ MCs
```

### Outcome

- For every private workload cluster, a private endpoint is deployed in the MC VNet and the MC can access the WC api server.
- When a private WC is deleted, the private endpoint created in the MC VNet is deleted.
- The above functionality is covered with unit tests and E2E tests.

**Comment by nprokopic** [comment]
Both implementation and are tests done, v0.1.0 released https://github.com/giantswarm/azure-private-endpoint-operator/releases/tag/v0.1.0 :tada: 

The bug issue is from CAPZ, not related to this operator, fix is here https://github.com/giantswarm/cluster-api-provider-azure/pull/19
