### ISSUE TITLE
Bonus objectives for Crazy Cycle (Observability Apps)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#242]
Towards https://github.com/giantswarm/roadmap/issues/175

- [ ] Do some PoC allowing us to stream logs from nginx IC in real customers' TCs to our loki
- [ ] jaeger - deploy and collect traces (as optional, as we don't have explicit tracing instrumentation, so it won't be that useful)
- [ ] move apps that we're happy with after the cycle from playground to giantswarm

**Comment by cokiengchiara** [comment]
Didn't manage to do this. Closing.
