### ISSUE TITLE
Use fixed alias domain for IRSA

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2420]
## Task

Use fixed alias domain for IRSA in order to remove the circular dependency between `capa-iam-operator` and `irsa-operator`. More details are available [here](https://github.com/giantswarm/roadmap/issues/996#issuecomment-1491929235).

Blocks the following [issue](https://github.com/giantswarm/roadmap/issues/996).

## Links

- [CAPA Flatcar issue](https://github.com/giantswarm/roadmap/issues/996).

**Comment by tuladhar** [comment]
References:
- https://github.com/giantswarm/irsa-operator/pull/126

**Comment by tuladhar** [comment]
**What needs to be done**
- [ ] [Remove dependency from `cluster-aws` PR](https://github.com/giantswarm/cluster-aws/pull/298)
- [ ] Remove dependency from `capa-iam-operator` by using control plane endpoint host from Cluster CR and prefix with `irsa.`; [similar to this](https://github.com/giantswarm/irsa-operator/blob/9225c52593172e176ee1989d4e540efb2e33d0cc/pkg/key/key.go#L104C6-L117).

**Unknown**
- [ ] We are not sure how API server will behave if `service-account-issuer` gets the IRSA cloudfront alias domain when it's still being provisioned by `irsa-operator`.

**Comment by tuladhar** [comment]
[Tested this PR](https://github.com/giantswarm/cluster-aws/pull/298)
- As Vaclav noted, IAM operator  still waits on secret, and doesn't create IAM instance profile for control plane, as such even though `service-account-issuer` is configured to use fixed alias, control plane instance will not get provisioned. Thus, for testing we need to decouple IAM operator creating roles logc vs waiting for IRSA secret.

**Comment by tuladhar** [comment]
Along with cloud front domain, capa-iam-operator also needs AWS account ID to configure the trusted identity policy for IRSA, [see here](https://github.com/giantswarm/capa-iam-operator/blob/master/pkg/iam/route53_template.go#L16).

**Comment by AndiDog** [comment]
Does the solution work for China / private clusters, where irsa-operator does not create the alias domain?

**Comment by T-Kukawka** [comment]
@bdehri can u chime in here?

**Comment by bdehri** [comment]
we decided to exclude private clusters?

**Comment by T-Kukawka** [comment]
@bdehri @AndiDog for China we will have to implement the split as there is no alias domain

**Comment by T-Kukawka** [comment]
Closing, China will be a separate topic
