### ISSUE TITLE
Document how we generate the helm chart in cluster-api-app

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2440]
### Motivation

It should be clear how the Helm chart in the cluster-api-app is generated. This is especially important when the Helm chart generation should be updated or fixed.

### Todo

In a nutshell, we use kustomize in `config/helm` directory to generate Helm templates in the `helm/cluster-api-app` directory, with some scripts before/after that remove/move/modify templates. We want to document all these steps.

```[tasklist]
- [x] Document what kustomize files we have and why.
- [ ] Document which kustomize files are auto-generated and why.
- [x] Document how we use kustomize, what is the input, what is the output.
- [ ] Document which templates we remove from the kustomize output and why.
- [x] Document which templates we move from the kustomize output to some other directory and why.
- [x] Document which templates we modify in the kustomize output and why.
```

### Outcome

- It is documented which kustomize files we use and why.
- It is documented how and why we remove, move and modify Helm templates that are generated with kustomize.

**Comment by pipo02mix** [comment]
Reviewing doc tasks, I found this one, I was thinking if it will not be more a blog post than actual documentation. WDYT?

**Comment by bavarianbidi** [comment]
I've already started with that to address our own engineers to make it more clear what happens within all the `make` targets without reading the bash-scripts.

But there is at least one topic which might fit well as a blog post (as we do this on multiple capi-app-repos):
**how we transfer a raw Kubernetes-Manfest into a helm-chart via `kustomize` (to easier keep in sync with upstream changes)**

**Comment by bavarianbidi** [comment]
https://github.com/giantswarm/cluster-api-app/pull/143 got merged, so closing this issue
