### ISSUE TITLE
App-platform rework

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2454]
As a company, we have now (spring 2023) agreed on 2 major objectives:

1. Enhance our "managed apps" offering into a full-fledged "internal developer portal"
2. Allow installation of our apps, especially the full "developer portal" tooling into non-giant-swarm customers: so customers that run and manage their clusters with 3rd party providers, like EKS or AKS, but still want to use our apps (like "security stack" or full "developer platform") offering. To make it possible, we will use our concept of Management Clusters (MCs) and App Platform to make it possible to offer the apps for a fleet of clusters.

To make these goals achievable, we, as team honey badger, see the following problems and challenges:
1. Complex setup of App Platforms on MCs
    - So far, we never let customers (even "customer admins") to have full access permissions on MCs, even though we allow them to install their own apps there (this feature has become very important for some customers). This means, that for any new app or any new feature we implement on MCs, we have to make sure that there's no escalation path that can be used by customers to escalate their permissions to full cluster level admin. 
    - As a result of above, we run 2 flux deployments for each installation: one that handles customer's apps and one that handles giant swarm apps. This setup is complex, requires complex RBAC setup, makes flux management hard and RBAC management even more complex.
2. Very custom solution for app platform and app delivery.
    - To fulfill our needs, we use a combination of in-house projects, mainly `app-operator` and `chart-operator` to deliver applications and `config` and `konfigure` to deliver them.
    - Functionality of `app-operator` and `chart-operator` is now offered natively by very good tools like Flux (that wasn't the case when these tools were created).
    - Current setup of `config`+`konfigure` is no longer acceptable, as it forces us to share the same `config` repo across all the MCs and additionally forces us to maintain our fork of how `flux` is distributed, where we can inject our own configuration tools.

As we expect that enhancing the product in these directions will create more configuration and deployment cases, more problems with RBAC management, we want to start this with a set of simplification efforts, that will make the setup much easier to manager, handle more cases and maintain.

As such, we see the follwing as important simplification steps that will make enhancing the product scope easier:

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2455
- [ ] https://github.com/giantswarm/roadmap/issues/2456
- [ ] https://github.com/giantswarm/roadmap/issues/2457
- [ ] https://github.com/giantswarm/giantswarm/issues/26980
- [ ] https://github.com/giantswarm/roadmap/issues/2490
- [ ] https://github.com/giantswarm/giantswarm/issues/24784
```

**Comment by weatherhog** [comment]
@piontec this issue has been in watching for over a year now. Is there a way forward or can this issue be closed?

**Comment by piontec** [comment]
This is still in progress, but with low priority. Let's keep it as it is.
