### ISSUE TITLE
Replace chart-operator with helmcontroller

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2455]
Replace `chart-operator` with `helm-controller` for CAPI releases.

```[tasklist]
### Sub-tasks
- [x] figuring out if the workload clusters' kubeconfig Kubernetes Secrets are compatible with the Flux specification. If not, then figuring out of how to make them compatible is necessary. Seems the Kubernetes Secret data key is being configured [here](https://github.com/kubernetes-sigs/cluster-api/blob/a0f25680152719cbcab33c8ac94b559fc7110645/util/kubeconfig/kubeconfig.go#L146C22-L146C22).
- [x] figuring out a way to convert [HelmRelease status](https://fluxcd.io/flux/components/helm/helmreleases/#status-specification) into an App CR status, and verifying if it is necessary to rely on the [HelmChart conditions](https://fluxcd.io/flux/components/source/helmcharts/#conditions). It is not only required to get statuses from HelmRelease CRs, but to also to possibly transform them into so far [known statuses](https://github.com/giantswarm/helmclient/blob/master/pkg/helmclient/spec.go).
- [x] updating the `flux-multi-tenancy` ClusterPolicy to allow cross-namespace references to HelmRepository CRs for HelmRelease CRs. References to other kinds should not be allowed.
- [x] updating App Operator with a feature flag / configuration options that requests translation to the Helm Controller compatible resources.
- [x] updatin App Operator with a new [catalog resource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L309), that runs only when App Operator is unique, that translates Catalog CRs to HelmRepository CRs. This is allowed to executed regardless the feature flag.
- [x] updating App Operator's [Chart CR status watcher](https://github.com/giantswarm/app-operator/tree/master/service/watcher/chartstatus) by re-configuring it to watch HelmRelease CR status.
- [x] updating App Operator's [tcNamespaceResource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L322C3-L322C22) by disabling it when the feature flag is enabled.
- [x] updating App Operator's [chartCRDResource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L323) by disabling it when the feature flag is enabled.
- [x] updating App Operator's [chartOperatorResource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L324C5-L324C5) by disabling it when the feature flag is enabled.
- [x] updating App Operator's [chartResource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L329C4-L329C4) by disabling it when the feature flag is enabled.
- [x] updating App Operator with a new [helmrelease resource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L309),  that runs only when feature flag is enabled, and translates App CR to HelmRelease CR.
- [x] updating App Operator's [statusResource](https://github.com/giantswarm/app-operator/blob/25e07d70d6cf73ff96f2cf543fb5529554d76006/service/controller/app/resources.go#L330C4-L330C4) by making it compatible with both Chart CR and HelmRelease CR (and HelmChart CR if needed), and making the decision conditional on the feature flag.
- [x] updating App Operator by adding a new, temporary, resource that makes sure the Chart Operator is gone (its removal could be triggered by removal of its App CR by the Cluster Apps Operator), removes Chart CRs and Chart CRD from a workload cluster, when the feature flag is enabled. This resource is to be removed when the migration is fully conducted across all the installations.
- [x] updating integrations tests of App Operator so that both setups, that is App Operator coupled with Chart Operator and App Operator coupled with Flux, are tested.
- [ ] potentially updating App Admission Controller, so that creation of ConfigMaps and Secrets, by a user, of names reserved by App Operator for the results of config layer merges, is prohibited.
- [ ] updating [apptestctl](https://github.com/giantswarm/apptestctl) project so that is it capable of bootstraping App Platform with Flux.
- [x] updating Prometheus rules, and other components, with new conditions, if there is no way to match Flux statuses to the current set of [statuses](https://github.com/giantswarm/helmclient/blob/139c579ea9faa8398bd717fc13fab8ec1a1c79b3/pkg/helmclient/spec.go#L18), see the second sub-task.
- [x] introducing a label to be used in Cluster CRs that, when present, is going to tell to Cluster Apps Operator to use a new setup for a workload cluster.
- [x] updating Cluster Apps Operator's [appResource](https://github.com/giantswarm/cluster-apps-operator/blob/master/service/controller/cluster.go#L196C6-L196C6) by making Chart Operator installation conditional on the Cluster CR label.
- [x] updating Cluster Apps Operator's [appResource](https://github.com/giantswarm/cluster-apps-operator/blob/master/service/controller/cluster.go#L196C6-L196C6) by adding the feature flag discussed to the App Operator configuration, whenever a label  is present on Cluster CR.
- [ ] updating MC Bootstrap if necessary, so that for CAPI clusters, the Chart Operator is no longer deployed as part of the cluster bootstrapping, same goes for its related resources, and that at least minimal Flux resources the App Platform is coupled with, are present.
```

**Comment by weatherhog** [comment]
wont do it in this form
