### ISSUE TITLE
Prepare app platform to handle EKS/AKS

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2458]
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2483
- [ ] https://github.com/giantswarm/giantswarm/issues/27377
- [ ] https://github.com/giantswarm/roadmap/issues/2484
- [x] Announce and explain to other teams how they can use the CD pipeline to deliver stuff to clusters
```

```[tasklist]
### Related
- [ ] https://github.com/giantswarm/roadmap/issues/2454
- [ ] https://github.com/giantswarm/giantswarm/issues/25009
```

```[tasklist]
### On hold
- [ ] https://github.com/giantswarm/roadmap/issues/2459
- [ ] https://github.com/giantswarm/roadmap/issues/2464
- [ ] Prepare MCF to handle external AKS clusters
```

**Comment by piontec** [comment]
Today, I had a call with @alex-dabija (pinging in case you want to track our epic here). We discussed how can this be done. My notes are below:

1. Assumptions
- we want to create a fresh (empty) MC in EKS/AKS for an existing fleet, then we import the fleet clusters
- we want to keep the bootstrap process as simple as possible:
    - we create a vanilla EKS cluster
    - put cluster definition itself into git repo
    - we bootstrap flux ASAP and hand over further provisioning there

2. Questions
- Q: How to provision a new EKS/AKS MC cluster for the PoC?
- A: This can be done by CAPA controllers. They can provision a new cluster, either in an existing VPC/networking setup or they can create a new one. You can use something like a `kind` cluster to deploy the CAPA controllers, then create CRs that describe a new cluster, then transfer the controller and the CRs to the new cluster, so it can manage itself (`clusterctl move` command). In a bit more details and going step-by-step:
    - create a new `kind` cluster
    - deploy our distribution of CAPA controllers there
        - cluster-api-provider-app
        - cluster-api-provider-aws-app
    - create CRs defining a new cluster
    - commit the resulting controller Deployments and CRs into flux repo (hint: it might be useful to provision/bootstrap Flux right after creating the `kind` cluster and deploying the CAPA controllers already with flux)
    - do the 'transfer of management' with `clusterctl move`
    - delete `kind` cluster
    - bootstrap flux on the newly create MC and point it to CAPA controller Deployments and CRs created on the `kind` cluster

- Q: how do we 'import' existing EKS WCs into our new MC?
- A: We don't know yet, requires research.

Other notes:
- We have to check `mc-bootstrap` in more details. It basically covers the process mentioned above, but for master nodes that we create and manage and handles much more complexity. We might get some inspiration and ideas from there, but let's try to use as little as possible and handle provisioning with Flux as soon in the bootstrap process as possible.
- If in doubt about `mc-bootstrap` and friends, ask in #area-kaas. Eric is our `mc-bootstrap` expert.
- CAPI docs reference: https://cluster-api-aws.sigs.k8s.io/topics/eks/creating-a-cluster.html
- invite Alex to discussions about `mc-bootstrap` and this provisioning

**Comment by weatherhog** [comment]
@piontec we are watching this issue in honeybadger since august 2023. Can this issue be closed as there is no EKS / AKS PoC plan at the moment?

**Comment by piontec** [comment]
I think this is still being discussed. To me this is "on hold", but not close.
