### ISSUE TITLE
[EPIC] new VPN / Access Solution with Teleport

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2463]
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/25895
- [ ] https://github.com/giantswarm/giantswarm/issues/25399
- [ ] https://github.com/giantswarm/roadmap/issues/2193
- [ ] https://github.com/giantswarm/roadmap/issues/2494
- [ ] https://github.com/giantswarm/roadmap/issues/2700
- [ ] https://github.com/giantswarm/roadmap/issues/2699
- [ ] https://github.com/giantswarm/roadmap/issues/2786
- [ ] https://github.com/giantswarm/roadmap/issues/2697
- [ ] https://github.com/giantswarm/roadmap/issues/2712
- [ ] https://github.com/giantswarm/roadmap/issues/2698
- [ ] https://github.com/giantswarm/roadmap/issues/2689
- [ ] https://github.com/giantswarm/roadmap/issues/2845
- [ ] https://github.com/giantswarm/roadmap/issues/2733
- [ ] https://github.com/giantswarm/roadmap/issues/2779
- [ ] https://github.com/giantswarm/roadmap/issues/2991
- [ ] https://github.com/giantswarm/roadmap/issues/2995
- [ ] https://github.com/giantswarm/roadmap/issues/3014
- [ ] https://github.com/giantswarm/roadmap/issues/3004
- [ ] https://github.com/giantswarm/roadmap/issues/3035
- [ ] https://github.com/giantswarm/roadmap/issues/3036
- [ ] https://github.com/giantswarm/roadmap/issues/3094
- [ ] https://github.com/giantswarm/roadmap/issues/3156
- [ ] https://github.com/giantswarm/roadmap/issues/3175
- [ ] https://github.com/giantswarm/roadmap/issues/3201
- [ ] https://github.com/giantswarm/giantswarm/issues/29709
```

**Comment by gawertm** [comment]
need another meeting with @alex-dabija to clarify the final architecture, location of Installation, etc.

**Comment by gawertm** [comment]
how to generate token to access central teleport instance, when customer creates a cluster and needs to inject that to the nodes.
token per installation. potentially run a controller on the MCs that would generate the tokens every e.g. 3 months and revoke the old one

**Comment by gawertm** [comment]
one concern that got raised during customer talks: where will audit logs be stored, in case we setup a "dedicated" leaf server for a customer? what kind of storage backends are supported? also where does that leaf server live? in our AWs account? what about Azure customers?

**Comment by stone-z** [comment]
This is done and waiting on provider chart releases, except for private on-prem installations. Waiting for feedback from Rocket on the real need for that. Will close this once provider charts are released
