### ISSUE TITLE
Add PSS exceptions for CAPA policy warnings

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2466]
## Task

Add PSS exceptions for the CAPA policy warnings listed [here](https://giantswarm.grafana.net/d/e5SZJRo4z/security-teams-overview?orgId=1&var-team=hydra&var-app=All&var-deployment=All&var-category=All&var-policy=All).

Components:
- [x] `aws-network-topology-operator`
- [x] `aws-resolver-rules-operator`
- [x] `aws-vpc-operator`
- [x] `capa-iam-operator`
- [x] `cluster-api-provider-aws`
- [x] `dns-operator-aws`
- [x] `squid-proxy`

## Links

- [PSP deprecation announcement](https://gigantic.slack.com/archives/C04TGHDEF/p1683554133927389);
- [Security enforcement documentation](https://docs.giantswarm.io/advanced/security-policy-enforcement/).
