### ISSUE TITLE
rainbow: get rid of k8s authenticator

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2472]
we need to remove this from dex app, api flags, kgs if possible

### Tasks
- [x] https://github.com/giantswarm/roadmap/issues/1228
- [ ] Remove dex-k8s-authenticator giantswarm deployment since it's not used anymore
- [ ] Remove dex-k8s-authenticator customer deployment
- [ ] Find out how to change oidc client name from dex-k8s-authenticor to something more fitting
- [ ] https://github.com/giantswarm/roadmap/issues/1654

**Comment by stone-z** [comment]
There have seemingly been no requests to dex-k8s-authenticator since ~september

<img width="1892" height="828" alt="Image" src="https://github.com/user-attachments/assets/a4fa9c73-aaa9-4730-975f-2bfab59adb41" />
