### ISSUE TITLE
Prepare MCF to handle external EKS clusters

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2484]
```[tasklist]
### Tasks
- [x] Add examples of deploying apps to the EKS WC, including dir structure and assuming multiple EKS clusters in the future
- [x] Add docs, in particular explainig how to use `HelmRelease` instead of `App` CR
- [x] script to covert App CR to HelmRelease
```

**Comment by piontec** [comment]
@mproffitt , once you're back, can you please confirm all your changes/docs are already in and we can close it?

**Comment by piontec** [comment]
done
