### ISSUE TITLE
Teleport PoC

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2494]
prerequisite: https://github.com/giantswarm/roadmap/issues/2193

```[tasklist]
### Tasks
- [x] deploy the prepared components
- [x] adapt mc-bootstrap to configure the token rotation controller credentials
- [x] security review of teleport terraform code
- [x] teleport-kube-agent app - inject teleport token from MC to WC via default apps (avoid deploying App CR from operator)
- [x] Teleport operator Tests
```
