### ISSUE TITLE
Managed App Catalog - Phase II

### ISSUE THREAD

**Issue by rossf7** [giantswarm/roadmap#25]
## User Story

This phase is about getting more apps into the catalog, the automation around that, and the release process.

1. Move existing Managed Services (CoreDNS, Ingress Controller etc) to apps using the new release process
2. Versions of required Managed Services are linked to Giant Swarm releases
3. cluster-operator creates/updates app CRs, the rest is moved to app-operator
4. UX lets you manage and update app CRs

- See tech spec for more details
https://github.com/giantswarm/giantswarm/blob/master/areas/managed-services/specs/app-catalog-phase-2.md
- This is the 2nd 6-week release cycle from 16th Sep to 28th Oct 2019 and continues from https://github.com/giantswarm/giantswarm/issues/6078.

### UX @oponder 

Tracked here: https://github.com/giantswarm/giantswarm/issues/6659

#### cluster-operator

- [x] Add appmigration resource @rossf7 https://github.com/giantswarm/giantswarm/issues/6800
- [x] Add configmapmigration resource @rossf7

#### e2e

- [x] Create basicapp e2e test to replace managedservices @tomahawk28 

#### Migrate Charts

- [x] kube-state-metrics @rossf7 https://github.com/giantswarm/giantswarm/issues/6800
- [x] cluster-autoscaler @rossf7
- [x] metrics-server 
- [x] coredns @rossf7
- [x] node-exporter 
- [x] net-exporter @sslavic 
- [x] cert-exporter @sslavic 
- [x] legacy Ingress Controller
- [x] Removal of chartconfig CRD and resources

### Spec

- [ ] App Updates including version validation (https://github.com/giantswarm/giantswarm/issues/7070)
- [ ] Monitoring of Apps (https://github.com/giantswarm/giantswarm/issues/7259)

## Related Issues

- Revamp of Ingress Controller https://github.com/giantswarm/giantswarm/issues/4795
- Add HPA to tenant ingress controllers https://github.com/giantswarm/giantswarm/issues/5264

Aha! Link: https://giantswarm.aha.io/features/M-14
