### ISSUE TITLE
Announce kustomize 5.0 breaking changes that come with flux 2.0 to the AEs

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2519]
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/adidas/issues/1171
- [ ] https://github.com/giantswarm/flexshopper/issues/381
- [ ] https://github.com/giantswarm/telekom-panamax/issues/244
- [ ] https://github.com/giantswarm/babymarkt/issues/1219
- [ ] https://github.com/giantswarm/egger/issues/71
- [ ] https://github.com/giantswarm/fashion-digital/issues/165
```

**Comment by mproffitt** [comment]
Some notes about this.

- `patchesStrategicMerge` and `patchesJson6902` are both deprecated in `v1beta1` for removal in `v1`
- Whilst you can use `kustomize edit fix`, this is known to break `kustomize build` when updating `patchesStrategicMerge`
  - This is because `patchesStrategicMerge` allows multiple patches to exist in a single file whilst `patches` does not. See https://github.com/kubernetes-sigs/kustomize/issues/5049
  - See PR https://github.com/kubernetes-sigs/kustomize/pull/5059 for future automatic splitting of `patchesStrategicMerge` files

- Customers are to be advised to review the release notes for both kustomize/v5.0.0 https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.0.0 and flux/v2.0.0-rc1 through to flux/v2.0.0-rcX https://github.com/fluxcd/flux2/releases and validate this against their current implementation. If they are unsure whether a particular feature will impact them, they should reach out through support with examples of areas of concern where we can best advise them on whether a change will introduce any failings or side-effects into their build.

@piontec @ljakimczuk Is there anything else that specifically needs calling out for customers?

**Comment by mproffitt** [comment]
@brinker211 will prepare customer focused tracking for this and take it to Teddyfriends planning on Friday to be pushed out next week to customers using GitOps.

- Once Flux 2.0.0 Stable is out, we will provide a 2 week window whereby all customers must complete changes to their codebase before we roll the upgrade.
- Honeybadger will continue to monitor for last minute changes to Flux/Kustomize and support customers migration where and when appropriate.
- Per customer Tracking tickets will be available for visibility on which customers are still to migrate. This will help mitigate breaking customer deployments via the upgrade.

**Comment by brinker211** [comment]
Status update:

- Handbook entry was created and merged
- Tasklist created for individual customer tickets
- Teddyfriends informed in meetings to take to customers in the syncs in upcoming weeks

Next steps, we will start working with customers to check and @mproffitt and honeybadger can make sure the tasklist is closed before upgrading.

**Comment by brinker211** [comment]
We are done here. Angel will confirm from adidas and reopen if there is anything left. All set!
