### ISSUE TITLE
Clear Release Expectations

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2522]
### Motivation

We have many components that have regular releases of new versions. For this we have many different release processes throughout the many giantswarm teams - and in some occasions even a different approach to what a release even is. 
In order for us to really own and improve the kubernetes lifecycle and new releases, we first have to understand and define a common approach and vocabulary around releases.

```[tasklist]
### Stories
- [ ] https://github.com/giantswarm/roadmap/issues/2523
- [ ] https://github.com/giantswarm/roadmap/issues/2524
- [ ] https://github.com/giantswarm/roadmap/issues/2525
- [ ] https://github.com/giantswarm/roadmap/issues/2773
- [ ] https://github.com/giantswarm/roadmap/issues/2866
- [ ] https://github.com/giantswarm/roadmap/issues/2867
- [ ] https://github.com/giantswarm/roadmap/issues/2909
```

### Outcome
Once this epic is done we have a clear definition and model of the current state of our release processes that can be used for further discussions and improvements of the status quo.

### Context
- https://github.com/giantswarm/giantswarm/issues/25443

**Comment by Rotfuks** [comment]
Outcome achieved with the documented release framework here: https://intranet.giantswarm.io/docs/product/releases/capi-release-framework/
