### ISSUE TITLE
Existing Release Process Investigation

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2524]
### Motviation
Currently we do not have a common release process, but many individual approaches how different teams release new versions of components. 
We have to create a common release process model that can work as a base for further discussions around how we want to improve the status quo.

### Todo

- [ ] Investigate what release processes we already have in giantswarm and document your findings
- [ ] Document the different release processes we have in place in a miro-board visualisation (boxes and arrows :))
- [ ] Setup a short meeting to present your process-model of the existing release process to the rest of the team

### Outcome
- We have models that visualise existing release processes within the different giantswarm teams.

**Comment by nprokopic** [comment]
Please check out this [RFC](https://github.com/giantswarm/rfc/pull/68). It includes a part about the existing release processes under, it's the section [_1. What and when we release and deploy today?_](https://github.com/giantswarm/rfc/blob/8725142e93ad2c5a8b4dec4a794f47768c9a12f2/release-channels-and-staged-deployments/README.md#1-what-and-when-we-release-and-deploy-today), so it should be helpful and even a good starting point here.

The RFC was written before we wrote specific issues for our team (this one and others), but when we already knew that we want to work towards something like that.

Then [_1.2. When and how often are we deploying?_](https://github.com/giantswarm/rfc/blob/8725142e93ad2c5a8b4dec4a794f47768c9a12f2/release-channels-and-staged-deployments/README.md#12-when-and-how-often-are-we-deploying) talks about how we deploy in few different ways (due to different use cases and needs on MC vs WC).

Finally (out of scope of this issue here), it takes above learnings and it restructures release processes around proposed [release channels and staged deployments](https://github.com/giantswarm/rfc/blob/8725142e93ad2c5a8b4dec4a794f47768c9a12f2/release-channels-and-staged-deployments/README.md#2-next-step-release-channels-and-staged-deployments).

The RFC is not finished yet, comments should be addressed and RFC should be updated. Will get back to that after the vacation.

**Comment by Rotfuks** [comment]
Outcome is documented here: https://miro.com/app/board/uXjVM0oMunQ=/
