### ISSUE TITLE
Cluster name to be derived from App resource name, not from chart value

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#2526]
Some cluster apps (CAPA, CAPZ) have a values property for setting the cluster name, which is technically a repetition.

CAPVCD and CAPV use the App's name as the cluster name. Supposedly this has been decided as the preferred way [in KaaS sync in August 2022](https://docs.google.com/document/d/15fBIUmv5pPvCF1DLwR6_XOaFLNHeVex8YNrVtgm83ME/edit#bookmark=id.shat53wx6wnj).

Currently our web UI only deals with the first way.

We should also check `kubectl gs template cluster` for the current implementation, per provider.

## Tasks

- Adapt CAPA and CAPZ cluster apps to remove .metadata.name and use Release.Name instead in templates
- Adapt web UI to set the cluster name via the App CR name. Including strategy for backward-compatibility.

```[tasklist]
### Tasks
- [ ] Adapt CAPA cluster app to remove .metadata.name and use Release.Name instead in templates
- [ ] Adapt CAPZ cluster app to remove .metadata.name and use Release.Name instead in templates
- [ ] Adapt web UI to set the cluster name via the App CR name, including strategy for backward-compatibility
```

**Comment by weatherhog** [comment]
@marians is this happa related and can be closed?

**Comment by marians** [comment]
Don't know. I asked in [area-kaas](https://gigantic.slack.com/archives/C01F7T2MNRL/p1727855561235639).

**Comment by marians** [comment]
Jose confirmed this is still a thing. Now I wonder about the impact. I think this info is missing here. @gusevda can you explain this?

**Comment by weatherhog** [comment]
@gusevda any news here?

**Comment by gusevda** [comment]
Checked with Marian, let's close this one as stale.
