### ISSUE TITLE
Fix private endpoint deletion in CAPZ

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2528]
### Motivation

Private endpoint deletion in CAPZ is broken (or the deletion implementation is incomplete). When a private endpoint is deleted in AzureCluster CR, the private endpoint resource in Azure is not deleted.

### TODO

- [x] When a private endpoint is deleted in AzureCluster CR, delete that private endpoint resource in Azure.
- [x] Test the outcome. Write needed unit/integration tests in CAPZ, verify in Giant Swarm test clusters.
- [ ] Check with CAPZ community if this fix should be contributed to CAPZ upstream, considering that [private endpoint implementation will soon switch to use ASO](https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/3530).
- [ ] Communicate to Team Phoenix if the fix will be contributed to upstream or not, and explain the reasoning.

### Outcome

- When a private endpoint is deleted in AzureCluster CR, the private endpoint resource is deleted in Azure.

**Comment by nprokopic** [comment]
Fixed here https://github.com/giantswarm/cluster-api-provider-azure/pull/19.

We don't want to contribute this to upstream CAPZ, as CAPZ will start using azure-service-operator which will change the underlying implementation, which would make our fix obsolete.
