### ISSUE TITLE
PSP Deprecation on Vintage

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2533]
### Motivation
With the upgrade to Kubernetes 1.25.0 PodSecurityPolicy is being deprecated and we need to replace it. For the replacement we already decided to go for Kyverno which is owned by shield. Here we need to clarify and moderate that this is already rolled out everywhere and we are safe to get rid of PSP with the upgrade.

### Todo

- [ ] Check with Shield on the state of their kyverno rollout
  - [ ] Add Kyverno and policies to Workload Clusters ( default-apps ? ) 
- [ ] Investigate and document what effect this deprecation and new component will have for our V1.25.0 rollout 
  - especially important: what do we have to keep in mind in the update process?
- [ ]  Investigate what would be a good test case to test for a successful rollout of the new PSS on 1.25.0

### Related Issues
- https://github.com/giantswarm/roadmap/issues/2493

### Outcome
- We are prepared for the PSP Deprecation done with the upgrade
- We are confident our upgrade process does not break stuff because of the psp deprecation

**Comment by primeroz** [comment]
## Overview of Apps Turtles need to fix

Based on [This Dashboard](https://giantswarm.grafana.net/d/e5SZJRo4z/security-teams-overview?orgId=1&var-team=All&var-app=All&var-deployment=All&var-category=All&var-policy=All&var-daemonset=All)

**Comment by primeroz** [comment]
## Investigate and document what effect this deprecation and new component will have for our V1.25.0 rollout

* We currently only deploy `kyverno` in the MC Clusters ( this is true for both CAPI and Vintage ) 
  * We **need to install it on WC** , alongside the policies, to replace PSP with it 
*

**Comment by primeroz** [comment]
## PSP Conditional in helm charts 

- [ ] [aws-operator](https://github.com/giantswarm/aws-operator/blob/3ed700c5b800c9e781b2064efd69213c77d34ec0/service/internal/cloudconfig/template/aws_cni.go#L8)
- [ ] cluster-shared - used as a dependency from cluster-XXX 
- [ ] [kyverno-app](https://github.com/giantswarm/kyverno-app/blob/63724bd617a2c01f5b1f852e6178a8c38bbe60ae/helm/kyverno/templates/policyreporter-psp/policyreporter-psp-rbac.yaml#L4)
- [ ] [babymarkt harbor](https://github.com/giantswarm/babymarkt/blob/0c26bda5be65fe2254c28665aa8d0dd143dbc0fe/management-clusters/potato/organizations/prod/workload-clusters/prod/manifests/harbor/psp.yaml#L4)
- [ ] [kubectl-apply-job](https://github.com/giantswarm/kubectl-apply-job/blob/92b4ca7a0e4041c9008d9e4699f92fc50f073199/helm/kubectl-apply-job/templates/_psp.yaml#L4)
- [ ]

**Comment by primeroz** [comment]
## Check that the `capabilities check` is actually working

Before moving on i wanted to check that `{{- if .Capabilities.APIVersions.Has "policy/v1beta1/PodSecurityPolicy" }}` https://github.com/giantswarm/node-exporter-app/pull/202/files is working 

so i 

* Created a WC cluster on glippy with 1.24.13 - all apps were installed including node-exporter
* Upgraded the cluster to 1.25.10 
* Removed the checksum for `node-exporter` to trigger a reinstall 

It is still rendering the PSP ... so the check is failing for some reason 

```
➜ kubectl --kubeconfig /dev/shm/cluster05.kubeconfig get node | grep control-plane
cluster05-control-plane-4f2a33d4-bfzmv   Ready    control-plane   28m   v1.25.10
cluster05-control-plane-4f2a33d4-jf5pb   Ready    control-plane   33m   v1.25.10
cluster05-control-plane-4f2a33d4-qtzwg   Ready    control-plane   38m   v1.25.10

➜ kubectl --kubeconfig /dev/shm/cluster05.kubeconfig get chart -n giantswarm node-exporter -o yaml | yq .status.reason
Deployment failed for `1.16.1` with `unknown-error`: "unable to build kubernetes objects from current release manifest: resource mapping not found for name: \"node-exporter-node-exporter\" namespace: \"kube-system\" from \"\": no matches for kind \"PodSecurityPolicy\" in version \"policy/v1beta1\"\nensure CRDs are installed first"

```

**Comment by primeroz** [comment]
I am moving this to blocked since 

* we need to wait for Kyverno to be installed and enforced in all WC Clusters 

Once that is done and deployed everywhere we can proceed with the removal of PSP in 1.24 clusters and then start testing upgrade to 1.25

**Comment by primeroz** [comment]
As discussed in [slack](https://gigantic.slack.com/archives/C02HLSDH3DZ/p1686840323285529) we will focus on vintage and don't worry about CAPI for now , this means the task is easier and can be summarized in

for Vintage MC and WC
* We have release with kyerno in 'audit' mode first
* We have release with kyverno in 'enforce' mode secondly
  * In this release we also remove the PSP from the app that are part of the release
* We handle the APPS that are not installed as part of the release  
* We upgrade to 1.25

I will put this in backlog until we are ready to start removing PSPs

**Comment by stone-z** [comment]
The compatibility matrix lays out the current understanding of when to use PSP vs Kyverno: https://github.com/giantswarm/security-bundle#compatibility-matrix

Basically, GS v20 == k8s v1.25 == kyverno in enforce mode, use security bundle v1.0.0 or above
GS <v20 == k8s <v1.25 == kyverno in audit mode, use security bundle v0.X.X whenever the team is ready

**Comment by Rotfuks** [comment]
@stone-z, @alex-dabija, @T-Kukawka and me had a meeting about the PSP Migration Plan and here's the notes for it: 
> - We need to put PSS to enforce mode, before we remove PSP
> - We need to remove PSP before we upgrade to K8SV1.25.0
> - We have a Grafana dashboard to see if PSP resources are removed and PSS is in right mode, so this can be a “are you K8SV1.25.0 ready?”-Dashboard
>   - But there are some extra apps, that we’re not really seeing in that dashboard
>   - It’s not the nicest way to get there, because it’s through port forwarding in the WC where it’s installed - @stone-z will have a look in how we can improve here
> - We could block the V20 release rollout based on the requirements, that PSP has to be removed and PSS has to be in enforce mode without open issues. @stone-z will have a look, how we could do that.
> - We either need to break our rule to have K8S Version changes in major versions (and K8SV1.25.0 in V20) or not having breaking changes in minor versions.
> - We coordinated the following approach
>   - V19.1.0 with kyverno in audit mode
>   - V19.2.0 with kyverno in enforce mode, we drop PSP from our (default) apps, customers should drop PSP in this version, Kyverno is auditing PSPs, education of customers to not create new PSPs needed.
>   - V20 will be blocked until PSPs are completely removed and roll out K8SV1.25.0
>   - We can use the MC to test the “No-PSP” Policy and directly upgrade them to K8SV1.25.0

**Comment by njuettner** [comment]
Closing the issue for now. From turtles side we updated all apps/components to prepare for PSS
