### ISSUE TITLE
Backup of CAPI Workload Cluster Resources

### ISSUE THREAD

**Issue by primeroz** [giantswarm/roadmap#2556]
## Motivation

We need to be able to restore a Management Cluster in case of disaster without causing issues to the Workload clusters that it was managing. 

On top of the resources stored in GIT ( `cluster-app` Helm Release + values ) there is a bunch of resources that only exist  on the MC and are used to identify the Cloud resources created by CAPI/CAPX 

for example for a CAPZ cluster this includes 
* Machines
* AzureMachines
* Secrets 
  * ca , etcd, sa, proxy
  * kubeadm configs

But others will exist like `MachinePools` and so on 

We need to backup those resources, and in general the whole ownership tree of `Cluster/XXX` , to be able to restore a WC on a different MC with no downtime 

## TODO
* [ ] Is `etcd backups` enough and we are good with it ? 
* [ ] Test the effect of simply `re-applying` the `cluster-app` on a different MC 
* [ ] Test backup  
* [ ] Test restore on different MC 
* [ ] Decide what tool to use for backups 
  * Velero
  * Stash
  * in house tool
* [ ] Define backup strategy and configuration
* [ ] Define how to handle secrets
* [ ] Create APP 
* [ ] Deploy for all CAPI MC
* [ ] Document how to restore 

## Outcome

We can restore the `management` of a workload cluster in case of disaster on the MC with no downtime for the WC
