### ISSUE TITLE
`KubeletStartedPodsErrorRateTooHigh` SLO Rule fires when new nodes join the cluster

### ISSUE THREAD

**Issue by primeroz** [giantswarm/roadmap#2578]
## Context 
The silence was removed for the SLO alerts and a flood happened see https://gigantic.slack.com/archives/C02HLSDH3DZ/p1686822826267189 for reference

Before Silences for new SLO alerts are removed we need to address the issues with the flooding rules. 

#### KubeletStartedPodsErrorRateTooHigh

Reference for one example: https://giantswarm.app.opsgenie.com/alert/detail/50d64fe5-52f9-4166-a2ed-302b734e7341-1686824326212/details 

from `argali/ccn01` 

It would have fired 10 times over the last 2 days 

![Image](https://user-images.githubusercontent.com/2085772/246082541-c32b5575-e6ee-47ee-afd6-057df4d0f4fc.png)

It seems that when a new node join 

![Image](https://user-images.githubusercontent.com/2085772/246082631-cfe8dbb5-9f4d-4094-81b6-7cb35f4ec6c6.png)

the `kubelet_started_pods_errors_total` increases because of issues starting pods until everything is good 

![Image](https://user-images.githubusercontent.com/2085772/246082630-b7bc390c-536d-46ad-8dc4-b613b62be417.png)

## TODO 

- [ ] Identify what causes the issue on `new node joining` causing pods to fail 
- [ ] Identify what are clusters are affected by this 
- [ ] IF is expected find a way to exclude it from the SLO alerts if is a new node
- [ ] Decide if this Alert should actually page overnight ( at the moment it does ) 
- [ ] Fix it 
- [ ] Move it back to the `unsilenced team` folder

**Comment by primeroz** [comment]
@T-Kukawka @QuantumEnigmaa FYI

**Comment by njuettner** [comment]
Things what we discussed:

- Let's have a session for the existing SLO's and drop those if not needed
