### ISSUE TITLE
Management  api for kvm

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#258]
### User Strory

As a giant swarm kvm user, I want kvm installations to implement the giant swarm management  api so that I can use kubectl-gs to manage kvm clusters. 

### Acceptance criteria

kubectl-gs can be used to:
- [ ] list kvm clusters 
- [ ] create a kvm cluster
- [ ] delete a kvm cluster
- [ ] modifiy a kvm cluster

**Comment by cornelius-keller** [comment]
This feature will not come for KVM clusters.
