### ISSUE TITLE
Cluster Autoscaler Investigation

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2618]
### Motivation
Kubernetes is all around scaling. For ideal resource usage specifically on the cloud integration customers expect automation around scaling of clusters. In order to deliver the best solution here we need to investigation what options we have.

### Todo

- [x] Investigate what options we have for Cluster autoscaling on MC and on WC level
  - You can get a lot of information from https://github.com/giantswarm/giantswarm/issues/19313
  - Create a small architecture diagram to model the options we have
- [x] Investigate what the current state is within Giant Swarm for the support of Cluster Autoscaler
- [x] Present the options and current state to the team, that we can derive follow up issues

### Outcome
- We know what our options for cluster autoscaling managed on the MC or the WCs are
- We know what the current state in Giant Swarm for cluster autoscaling on CAPI is.
- We have follow up issues to implement cluster autoscaling on our cloud integration

**Comment by primeroz** [comment]
Current status for Giantswarm cluster-autoscaler

* our app is at version `1.25.1` which supports cluster-api
* support for cluster-api settings is not yet in the `deployment` - https://github.com/giantswarm/cluster-autoscaler-app/blob/master/helm/cluster-autoscaler-app/templates/deployment.yaml#L47
* we might want to review the settings for CA deployment
  * balancing labels 
    * CAPA Extra labels vs AWS Standard
    * CAPZ Extra labels vs AZURE Standard

**Comment by Rotfuks** [comment]
Results presented in the daily and decided to derive the following tickets: 
-> Ticket cluster-api-controller update
-> Ticket for AWS Machinepools 
-> Ticket for Machine Deployments autoscaling
-> Ticket for Documentation (potentially with scale to zero) 
-> Ticket for E2E Testing 

So this ticket is done :) 
Amazing work @primeroz !
