### ISSUE TITLE
Simplify registries architecture

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2619]
Our registries are a mess currently, with quay.io, dockerhub, ACR and aliyun being used across the hole product. On top of that, we keep our helm charts as a separate HTTP based registry.

What we would like to achieve is a very simple regsitry layout, that comes from a numerous evaluation and sub-problems that we had to deal with. The proposed layout is:

- We use only ACR registry. We store everything there: images and charts alike. There are no replicas, if needed we enable HA/geo-replication on the provider side. Everything pushes and pulls from/to ACR.
- The only exception to the rule above is China: if ACR won't support China and replication there in a reasonable way, we will keep 1 instance of `crsync` to replicate everything from ACR to aliyun.

Related ADR: https://github.com/giantswarm/giantswarm/pull/27547

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2361
- [ ] Configure all the CI/CD systems to push container images to ACR only
- [ ] Configure all the CI/CD systems to push helm charts to ACR only
- [ ] Check if we need ACR->aliyun replication or can we use ACR china directly
- [ ] Configure ACR registry to use cache and needed zones/regions
- [ ] Setup traffic and cost monitoring for the ACR registry
- [ ] Configure all container runtimes to login (if needed) to ACR
- [ ] Configure retagger and reevaluate what's needed
- [ ] https://github.com/giantswarm/roadmap/issues/2647
- [ ] https://github.com/giantswarm/giantswarm/issues/22748
- [ ] https://github.com/giantswarm/roadmap/issues/1634
```

**Comment by piontec** [comment]
Related ticket https://github.com/giantswarm/giantswarm/issues/27435

**Comment by weatherhog** [comment]
@piontec as we have a clear plan for this. Do we still need this issue?

**Comment by piontec** [comment]
I think we can close, we have tickets for the remaining tasks
