### ISSUE TITLE
GS OS Decision

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2622]
## Task

Decide which operating system is supported by Giant Swarm with CAPI.

TODOs:
```[tasklist]
- [ ] Evaluate current options
- [ ] Make decision based on the current information
- [ ] Comunicate the decision (Slack, SAs, etc.)
- [ ] Publish ADR
```

## Background

The operating system of choice for Giant Swarm has been Flatcar until now because:
* container support used to required a recent kernel. There were bugs fixed, new features added, different storage drivers, etc.
* the OS was focused on container support, streamlined, etc. Other operating systems had a lot of bloat (package manager, unneeded packages installed by default);
* the OS hardening rules are already implemented. Another OS requires additional work to implement and to valuate with customers.

Some customers started asking for security agents (e.g. MS Defender) to run directly on supported operating system and to have full access to the system (internal security requirements). In the case of MS Defender, Flatcar is not one of the supported operating systems even if both are owned by Microsoft (see [Microsoft's documentation](https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/microsoft-defender-endpoint-linux?view=o365-worldwide#system-requirements)).

Flatcar has very few users with CAPI. We will be among the few to run the Ignition bootstrap code from upstream. This increases the risk of encountering problems which need to be fixed without much help from upstream.

Most upstream clusters are probably running Ubuntu (it's the default). Nowadays the operating system is less important for running containers. Most features are available on most Linux distributions and there aren't cutting edge features required by the workloads or the container runtime.

## Current status

* AWS & Azure Vintage are using Flatcar;
* CAPA is using Flatcar;
* CAPZ is using Flatcar;
* CAPV is using Ubuntu, but it has upstream support for Flatcar (not yet tested by Giant Swarm: [Slack thread](https://gigantic.slack.com/archives/C01BYMF6RN0/p1692687211835009));
* CAPVCD is using Ubuntu, and Giant Swarm is adding Flatcar support upstream (https://github.com/giantswarm/roadmap/issues/2506);

### Flatcar

GS only uses Flatcar as the operating system.

#### Pros
* container native OS. Higher risk that we need to deal with issues on our own;
* hardening already implemented;
* security validated by existing customers;
* GS has experience with it;
* most GS CAPI providers are already using it: CAPA, CAPZ, CAPV, CAPVCD (in progress);
* has an LTS version (but we haven't tried it yet);

#### Cons
* very few actual users;
* secondary OS in CAPI. GS would not benefit from all the testing done by upstream;
* not yet supported for some GS CAPI providers: CAPG (on-hold), CAPVCD (in progress);
* the LTS version wasn't easy to use when we tried (probably, because we weren't building our own images);
* higher risk that we need to deal with issues on our own;
* Microsoft? What's the future of Flatcar?

### Ubuntu

GS only uses Ubuntu as the operating system.

#### Pros
* main OS used by CAPI upstream. GS would benefit from all the testing done by upstream;
* very popular OS. There's a lot of information on the Internet (issues, fixes, workarounds, etc.);
* LTS release with 5 years of support (customers can get a support contract from Canonical);
* GS would be aligned with upstream;

#### Cons
* general purpose OS, not container native. It's less important nowadays;
* GS has less experience with it;
* the OS hardening needs to be implemented;
* the OS needs to be validated by our customers;

### Both (Flatcar & Ubuntu)

GS mainly uses Flatcar as the operating system and keeps the option available to use Ubuntu for customers with additional requirements which can't be met by Flatcar.

#### Pros
* larger customer base;

#### Cons
* maintenance overhead. Supporting 2 operating systems requires additional effort especially if they are configured in a different way (ignition vs cloud-init);

### Other OS

GS switches to a different Linux distribution (not Flatcar or Ubuntu).

#### Pros

None without considering a specific distribution.

#### Cons

* migration effort: build new images, update OS configuration, etc.

**Comment by alex-dabija** [comment]
@Rotfuks I finished adding all the context about the OS decision.

Personally, I'm in favor of sticking with Flatcar for now mostly because:
* the cloud provider are already using it (CAPA, CAPZ);
* we don't have a current customer with a special request;
* we don't need to redo the security validation of the OS with our customers (it's already approved by existing customers);
* CAPV has upstream support;
* CAPVCD work is in progress;
* we build our own images and we can add agents to the os (if needed). We already did it for Teleport;

**Comment by Rotfuks** [comment]
Then let's document it as decision to stick to Flatcar as the target state. 

I think it's a decision fitting to our previous concept decisions in the providers that we just formalize here. So I'll add it to the Turtles decision log and we can close it with that outcome :)

**Comment by Rotfuks** [comment]
PR for decision log: giantswarm/giantswarm#27997
