### ISSUE TITLE
Test logging infrastructure on some GiantSwarm AWS testing installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2639]
Once we have a working logging infrastructure which successfully deployed on 1 GiantSwarm AWS testing installation, we can move on an deploy this to more of our testing installations to collect data and make sure this works in different environments.

```[tasklist]
### Tasks
- [x] Test deploy on some GiantSwarm AWS testing installations
- [ ] No errors in logging-operator logs
- [ ] I can Explore logs using Loki datasource in Grafana
- [ ] Loki cost dashboard shows all data
```

**Comment by QuantumEnigmaa** [comment]
@TheoBrigitte What should be the next step concerning this issue ?

**Comment by TheoBrigitte** [comment]
> @TheoBrigitte What should be the next step concerning this issue ?

If we have completed all points mentioned in the tasks list then we are done here.
