### ISSUE TITLE
Upgrade flux to 2.0 release

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2648]
Flux 2.0 has been released as a stable project. There are some breaking changes, so we have to coordinate with customers and other teams to do the upgrade.

High level plan:

1. We (mostly Martin) need to start shouting warnings to customers, that they need to update their deployment manifests and give some deadline, like 2-4 weeks. Issue remainder every week, so on, and so forth
2. We check our own manifests and ping the rest of the company with the same warning
3. We do the upgrade: this might be pre-single flux-migration or post. We don't think there's much difference.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2519
- [ ] https://github.com/giantswarm/roadmap/issues/2649
- [ ] https://github.com/giantswarm/roadmap/issues/2650
- [ ] https://github.com/giantswarm/roadmap/issues/2651
- [ ] https://github.com/giantswarm/roadmap/issues/2652
```

**Comment by kubasobon** [comment]
Starting work on https://github.com/giantswarm/roadmap/issues/2650 in parallel to announcements.

**Comment by mproffitt** [comment]
@uvegla We're already running Flux 2.1 everywhere - can this be closed?

**Comment by uvegla** [comment]
Yep, closing. 👍🏻
