### ISSUE TITLE
Improve Loki app to be ready for using in production

### ISSUE THREAD

**Issue by webwurst** [giantswarm/roadmap#266]
## User Story

As a customer I want to have direct access to log messages of running pods within my observability stack. So that metrics and logs are aligned when investigating issues on a cluster.

## Details, Background

Currently we provide [Loki](https://grafana.com/docs/loki/latest/) as version [v0.1.0](https://github.com/giantswarm/loki-app) in our `giantswarm` catalog. Loki can process all log messages of a Kubernetes cluster and help to filter and query them while aiming for a low resource usage. It integrates nicely into the open-source [observability](https://grafana.com/oss/) stack by Grafana Labs.

## Depends on

Tasks to focus on for current cycle (until March 19th):

### Most important
- [x] Test Loki on Azure
- [x] Forward logs from test management clusters and gorilla (to check if multi tenant thing is working)
- [x] Have authorization that matches users to tenants (workload clusters?) @ubergesundheit https://github.com/giantswarm/loki-app/pull/14
- [ ] Configure prometheus to scrape Loki in order for Grafana to provide dashboards for metrics based on log messages @webwurst 
  - [ ] Focus on https://github.com/giantswarm/g8s-grafana first to have alerting on our side
  - [ ] After that make monitoring work for the customers. Scraping works the default way by creating `ServiceMonitor` CRs via Helm config. But we need to add annotations for our internal monitoring. Might still be possible via Helm config setting the [`annotations`](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L561) or [`podAnnotations`](https://github.com/grafana/helm-charts/blob/main/charts/loki-distributed/values.yaml#L39) field.
- [ ] Add [alerting](https://grafana.com/docs/loki/latest/alerting/)
- [x] Figure out problem w Journald @piontec  https://github.com/giantswarm/promtail-app/pull/15
 
### Next
- [ ] Check and add support for TableManager (component of Loki)
- [ ] Documentation @ced0ps will do while doing https://github.com/giantswarm/giantswarm/issues/15622
- [ ] Documentation @ced0ps will do while doing https://github.com/giantswarm/giantswarm/issues/15622
  - [ ] connecting from Grafana for both cases: when auth-proxy is used and not (@ced0ps @ubergesundheit)
  - [ ] (optional) try to use `podAffinity` to run `authProxy` and `gateway` on the same node
  - [ ] better examples for Azure - placeholders instead of values
  - [ ] add a warning that if you use in-cluster Service instead of Ingress, people can bypass Gateway service, which does auth; and hit microservices endpoints directly. Use netpols to resolve
- [ ] Add tests
- [ ] Add values.schema.json

Harder than it seems
* Add [Loki Canary](https://grafana.com/docs/loki/latest/operations/loki-canary/) once it works for distributed mode. Canary upstream needs to be enhanced (doesn't support multi-tenant setups)

Planned outcome:
- We know what's missing for customers to use in production. 
- We implement stuff s.t. customers would be willing to use it in production.

**Comment by cokiengchiara** [comment]
1. @T-Kukawka and @ced0ps 's customer is already using Loki, right? Would it make sense for us to get on a call w them to understand their use case, how it's going, and what we could improve technically?
2. For said customer, in a note, Cedric wrote, "Have DB backend Loki to enable running multiple Loki instances." - Are they still interested?

**Comment by T-Kukawka** [comment]
1. We have a sync with the team every week so not sure if additional call will be needed - maybe u can join?
2. AFAIK: definitely yes 😄

**Comment by cokiengchiara** [comment]
Wed, 17. Feb 2021 @ced0ps from standup
* Current setup: They are in "airplane mode" - all the services are in one monolithic thing. More suited for testing. They want to run distributed to scale separate services. Can check the goku management cluster for their Loki configuration
* How we can help - Move data from persistent storage to some data backend, which we still have to figure out for Azure
* Figure out data backend for Azure

**Comment by ced0ps** [comment]
Sync with GK-Software:
- They would like to maintain data persistence
- 2 week log retention, would be fine with running two parallel setups to have data persistence for their users
- No real insight in to label an stream configuration. At least not in ops team. Could probably get on a call with some of their "developer loki power users" ?

@T-Kukawka any additions?

**Comment by cokiengchiara** [comment]
Mon, 22. Feb 2021 from @webwurst 
* last week was about learning, etc. Prepared tests. 
* This week, preparing list of tests and start writing tests so we can be more confident in upgrades

**Comment by cokiengchiara** [comment]
> * [ ]  Test Loki on Azure

For https://github.com/giantswarm/giantswarm/issues/15694#issuecomment-785127149, we scheduled @piontec demo for next week Mar 4 or 5. Some of the customers is on Azure. Could we test on Azure sooner rather than later? Maybe by Tue or Wed? So we have concrete answer if customers asks.

> Some customers are on Azure. We haven't tested on Azure.

**Comment by cokiengchiara** [comment]
@ubergesundheit or @webwurst please by tomorrow or Wednesday if possible re: test on Azure.

**Comment by ubergesundheit** [comment]
I'll start today

**Comment by cokiengchiara** [comment]
Mon, 01. Mar 2021 Was not able to work last week. EFK upgrade. Aqua upgrade. Tobi can go back to Loki tomorrow. Gerald is now testing on Azure.

**Comment by ubergesundheit** [comment]
preliminary Azure support is incoming in giantswarm/loki-app#12

**Comment by piontec** [comment]
We now have logs from 5 clusters incoming, it should be good enough for testing:

- loki0 itself
- gorilla
- gauss
- ginger
- giraffe

**Comment by ubergesundheit** [comment]
In a multitenancy setup (multiple tenants sending logs into a single loki instance), tenants are differentiated by an "X-Scope-OrgID" http header.

It seems there is no mechanism in loki to authorize the usage of this http header against the used authentication (which is also external). 

This authorization validation is required for both shipping logs into loki as well as when querying logs.

At this point we're using basic authentication (username, password) enforced by nginx ingress controller.

I'll now check if https://github.com/k8spin/loki-multi-tenant-proxy could work for this use case

**Comment by cokiengchiara** [comment]
> * [ ]  Have authorization that matches users to tenants (workload clusters?) @ubergesundheit
> *

Kind of blocked by broken test installations. @JosephSalisbury said on [slack](https://gigantic.slack.com/archives/CLPMFRVU6/p1615811551089600?thread_ts=1615810838.086700&cid=CLPMFRVU6) he will try to fix. In the meantime, Gerald will try on kind cluster.

**Comment by ubergesundheit** [comment]
giantswarm/promtail-app#15 should solve the journald issue. I think setting `max_age` in the promtail config for journald prevents the `out of order` errors

https://github.com/giantswarm/loki-app/pull/14 introduces https://github.com/k8spin/loki-multi-tenant-proxy into the loki helm chart. It allows users to configure credentials for different tenants which are then enforced by the app. The configuration could be prettier. I've already opened an issue in the upstream repository asking if they would accept a change to the gateway config.

**Comment by cokiengchiara** [comment]
@webwurst and @ubergesundheit please update the todos in the main body of this issue before planning 🙏

**Comment by ubergesundheit** [comment]
There was also something you've mentioned regarding a prometheus annotation, do you have more information about that?

**Comment by cokiengchiara** [comment]
Closing this.
