### ISSUE TITLE
Developer Platform PoC using EKS clusters

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2665]
## Summary

We want to be able to onboard existing EKS clusters without taking control over them. On these clusters, we want to be able to deploy our applications and connect them to our Developer Platform.

The scope of this ticket, which is multi-team scoped, is to plan for a PoC stage with 2 main objectives:

1. Be able to deploy and test potential components that we can use to build the dev platform.
2. Test the above in a more restrictive and new environment, where workload clusters can be based on vanilla EKS and not managed by us.

## Tasks

Current effort around that is summarized below.

```[tasklist]
### General tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2666
- [ ] https://github.com/giantswarm/roadmap/issues/2454
```

```[tasklist]
### Dev Platform components evaluation
- [ ] https://github.com/giantswarm/giantswarm/issues/27638
- [ ] https://github.com/giantswarm/giantswarm/issues/27673
- [ ] https://github.com/giantswarm/roadmap/issues/2667
- [ ] deploy and test kratix
```

```[tasklist]
### EKS workload clusters setup
- [ ] https://github.com/giantswarm/roadmap/issues/2458
- [ ] https://github.com/giantswarm/roadmap/issues/2668
- [ ] https://github.com/giantswarm/roadmap/issues/2669
- [ ] https://github.com/giantswarm/roadmap/issues/2670
- [ ] https://github.com/giantswarm/roadmap/issues/2671
- [ ] https://github.com/giantswarm/roadmap/issues/2672
- [ ] https://github.com/giantswarm/roadmap/issues/2673
- [ ] https://github.com/giantswarm/roadmap/issues/2893
- [ ] Evaluate https://akuity.io/blog/introducing-kargo/
- [ ] How do we monitor existing addons like AWS CNI? (aws-node containers are not monitored on the snail WC)
```

## References

- [how to access `snail` PoC MC and deploy stuff to our test EKS cluster](https://github.com/giantswarm/giantswarm/issues/27377#issuecomment-1634311893)

## Related work

```[tasklist]
### Related
- [ ] https://github.com/giantswarm/giantswarm/issues/25009
- [ ] https://github.com/giantswarm/giantswarm/issues/27664
```

**Comment by puja108** [comment]
To keep scope limited I'd not include the App Platform rework inside this PoC. Similarly, I would backstage and port out of it, so the PoC scope is more or less: "be able to do what we already have for GS-WCs but on non-GS WCs".

That said, if PoC and customer/sales talks continue positively, we should keep the "non-GS WC" support also for any future changes (App Platform rework) and additions (backstage, port,...) to the platform. We would need to think about including it somehow in our testing pipeline then (cc @alex-dabija @yulianedyalkova for early awareness, nothing to act on now)

**Comment by henninglange** [comment]
Do we need a GS management cluster within the customer domain to deploy our developer platform and apps on third party clusters such as EKS (non-managed by us) or do we look at a different deployment model?

**Comment by weatherhog** [comment]
there is no PoC any more. closing this issue for now
