### ISSUE TITLE
Make sure that our components deployed to imported EKS clusters are monitored and alerted

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2670]
We want our product to be able to deliver managed apps to workload clusters that are not of Giant Swarm flavor. We have created a CAPA MC to test stuff around the idea of importing vanilla EKS clusters and delivering our apps there. This setup is available as `snail` MC. The scope of this ticket is to check what needs to be done in order to have our managed apps that are deployed to customers' EKS workload clusters (where we don't manage WCs themselves) properly monitored with our tools from the `snail` MC.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2809
- [ ] https://github.com/giantswarm/roadmap/issues/2810
- [ ] https://github.com/giantswarm/roadmap/issues/2811
- [ ] https://github.com/giantswarm/roadmap/issues/2812
- [ ] https://github.com/giantswarm/roadmap/issues/2813
- [ ] https://github.com/giantswarm/roadmap/issues/2814
- [ ] https://github.com/giantswarm/giantswarm/issues/28252
```

**Comment by TheoBrigitte** [comment]
@piontec how do we deploy our components on `snail` MC ?

I see some informations in https://github.com/giantswarm/giantswarm/issues/27377 but nothing regarding app deployment on MC.

**Comment by QuentinBisson** [comment]
@piontec do we have some ways to differenciate flux managed clusters vs Giant Swarm managed clusters?

**Comment by QuentinBisson** [comment]
Regarding the existing containers, we will most likely need to know  which servicemonitors to disable:

```sh
k get pods -A --kubeconfig=snail-wc.kubeconfig.yaml
NAMESPACE     NAME                      READY   STATUS    RESTARTS   AGE
kube-system   aws-node-zktpz            1/1     Running   0          57d
kube-system   coredns-cbbbbb9cb-cx67h   1/1     Running   0          75d
kube-system   coredns-cbbbbb9cb-pc4b2   1/1     Running   0          75d
kube-system   kube-proxy-b9sb9          1/1     Running   0          57d
```

**Comment by QuentinBisson** [comment]
Prometheus meta operator is now creating the WC prometheus with this branch deployed: https://github.com/giantswarm/prometheus-meta-operator/pull/1364

**Comment by QuentinBisson** [comment]
All that's left is for us to deploy the observability-bundle

**Comment by QuentinBisson** [comment]
Oh I just figured we cannot use bundles here

**Comment by QuentinBisson** [comment]
Unless the app platform can actually create helmreleases instead of App CR which would actually make sense

**Comment by QuentinBisson** [comment]
Aside from the fact that we cannot use bundles, the current example installed on the snail WC is not working:

```
org-sample        flux-management-base   30d   False   HelmRelease/org-sample/podinfo dry-run failed, reason: Forbidden, error: helmreleases.helm.toolkit.fluxcd.io "podinfo" is forbidden: User "system:serviceaccount:org-sample:automation" cannot patch resource "helmreleases" in API group "helm.toolkit.fluxcd.io" in the namespace "org-sample"...
```

Could you please have a working example before you push this issues to teams?

**Comment by TheoBrigitte** [comment]
### Test
- [x] PMO deployed to MC (via app-operator)
- [ ] Grafana
- [ ] Aletmanager
- [ ] Opsgenie alerting
- [ ] Silences

### Actions
- [ ] PMO need to support k8s api token authentication
- [ ] observability-bundle deploy to WC via MCB
- [ ] PMO fix for target selection based on app versions
- [ ] Update ServiceMonitor for compatibility

**Comment by QuentinBisson** [comment]
Observability bundle is deployed missing a few adjustments (no alertmanagers and so on) with  https://github.com/giantswarm/management-cluster-bases/tree/snail_eks_adoption/bases/provider/eks/helmrelease/observability-bundle

![image](https://github.com/giantswarm/roadmap/assets/2787548/b9953d52-8313-4a83-9721-7ed5099fedc5)

**Comment by QuentinBisson** [comment]
@piontec I managed to deploy our observability bundle on the snail WC using the custom MCB branch. One important thing to note is that we are missing Giantswarm priority class that we are now using for the Prometheus Agent and i guess a lot of other components we manage in our clusters. Where should we track this regarding EKS adopted clusters?

**Comment by QuentinBisson** [comment]
@marieroque is taking care of the last one

**Comment by QuentinBisson** [comment]
@TheoBrigitte all tasks are done, I'm closing, feel free to repoen if needed :)

**Comment by TheoBrigitte** [comment]
Re-opening as we are missing metrics-server to ensure stability for our components.

**Comment by QuentinBisson** [comment]
Metric-server is working using hostNetwork on EKS, closing...
