### ISSUE TITLE
Team Atlas - Test managed apps on `snail`+ EKS

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#2673]
For our general approach to adopt EKS Cluster we need to test all our managed apps  and our monitoring stack on `snail` + EKS. 
You can find the instructions to access the EKS cluster [here](https://github.com/giantswarm/giantswarm/issues/27377#issuecomment-1634311893)

- Imported EKS:
  - [x] prometheus operator and kube-state-metrics
  - [x] metrics-server 
  - [x] Loki
  - [x] Promtail
  - [x] fluent-logshipping-app
  - [x] grafana

- CAPA EKS
  - [x] prometheus operator and kube-state-metrics
  - [x] metrics-server
  - [x] Loki
  - [x] Promtail
  - [x] fluent-logshipping-app
  - [x] grafana

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2886
- [ ] https://github.com/giantswarm/roadmap/issues/2887
- [ ] https://github.com/giantswarm/roadmap/issues/2888
```

**Comment by TheoBrigitte** [comment]
Closing as duplicated as we are currently handling this as part of this issue https://github.com/giantswarm/roadmap/issues/2670

**Comment by QuentinBisson** [comment]
@TheoBrigitte What apps do we want to test here?
- [x] `prometheus operator` and `kube-state-metrics`
- [ ] Loki and Promtail?
- [x] `vertical-pod-autoscaler`
- [x] `metrics-server`

Do we have other apps I am missing?

**Comment by QuentinBisson** [comment]
If yes, we probably want to have a bigger than 1 node cluster because pods will be stuck in pending state:

kube-system   vertical-pod-autoscaler-admission-controller-5956865464-czxml   0/1     Pending   0               22s
kube-system   vertical-pod-autoscaler-admission-controller-5956865464-hd2td   0/1     Pending   0               22s
kube-system   vertical-pod-autoscaler-recommender-84c966d4b4-tbs5s            0/1     Running   0               22s
kube-system   vertical-pod-autoscaler-updater-6f578b5f7-h9tr6                 0/1     Running   0               22s

**Comment by QuantumEnigmaa** [comment]
I guess that with the successful `fluent-logshipping` tests ran by @QuentinBisson we can now close this issue.

**Comment by TheoBrigitte** [comment]
Alright, we are done here then.
