### ISSUE TITLE
Update CAPZ app to use the latest CAPZ from fork

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2675]
### Motivation

We want to update the CAPZ app to use the latest version of CAPZ from our fork, so we can transfer CAPZ app to Phoenix with CAPZ being on the latest version.

Also we need the latest CAPZ version in our fork in order to rebase our custom private links implementation onto the latest CAPZ version, so we can more easily contribute private links to upstream CAPZ.

### Todo

```[tasklist]
- [ ] Update CAPZ main branch to the latest CAPZ
- [ ] Push the latest CAPZ release branch `release-1.10` to our fork
- [ ] Cherry pick Giant Swarm custom changes from release branch `release-1.8` to the latest release branch `release-1.10` in our fork
- [ ] Publish new pre-release in our CAPZ fork that is using the latest CAPZ (v1.10.0) from branch `release-1.10` plus custom Giant Swarm changes. https://github.com/giantswarm/cluster-api-provider-azure/releases/tag/v1.11.0-gs.alpha.0
- [ ] Update CAPZ app to use the latest CAPZ pre-release from our fork.
```

### Outcome

- CAPZ app is using the latest CAPZ version with custom Giant Swarm changes (private links and private endpoint deletion fixes) added on top of it.
- Our CAPZ fork is updated to the latest CAPZ version and our private links implementation is rebased on top of latest CAPZ, so we can more easily contribute private links to the upstream CAPZ.
