### ISSUE TITLE
Private clusters with HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2682]
Private clusters with HTTP/HTTPS proxy support.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/1650
- [ ] CAPZ private clusters with HTTP/HTTPS proxy
- [ ] CAPV private clusters with HTTP/HTTPS proxy
- [ ] CAPVCD private clusters with HTTP/HTTPS proxy
```
