### ISSUE TITLE
Private clusters without HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2683]
Private clusters without HTTP/HTTPS proxy support.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2070
- [ ] CAPZ private clusters without HTTP/HTTPS proxy
- [ ] CAPV private clusters without HTTP/HTTPS proxy
- [ ] CAPVCD private clusters without HTTP/HTTPS proxy
```
