### ISSUE TITLE
CAPI initial public documentation

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2685]
CAPI Giant Swarm public documentation for all supported providers. It should include:
- getting started guide;
- architecture diagrams;
- description of configuration options;
- ...

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2393
- [ ] CAPZ public documentation
- [ ] CAPV public documentation
- [ ] CAPVCD public documentation
- [ ] https://github.com/giantswarm/giantswarm/issues/25348
```

**Comment by teemow** [comment]
Closing in favor of https://github.com/giantswarm/giantswarm/issues/29503
