### ISSUE TITLE
CAPI test environments

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2686]
CAPI test environments for:
- teams to tests their changes;
- CI to run automated tests;

Every major supported cluster configuration (public, private, with proxy, without proxy) for each supported provider should have test environments.

The test environments must be documented and their purpose should be clearly highlighted.

```[tasklist]
- [ ] CAPA test environments;
- [ ] CAPZ test environments;
- [ ] CAPV test environments;
- [ ] CAPVCD test environments;
```
