### ISSUE TITLE
CAPI cluster stability

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2687]
## Wishes

* Workload cluster creation should be done without manual intervention for all supporter cluster configurations;
* Workload cluster upgrades are manually triggered;
* Workload cluster upgrades are without manual intervention once they are triggered;

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/298
- [ ] Run GS test suite for CAPA clusters
- [ ] Run GS test suite for CAPZ clusters
- [ ] Run GS test suite for CAPV clusters
- [ ] Run GS test suite for CAPVCD clusters
```

**Comment by teemow** [comment]
@alex-dabija I'm cleaning up old issue and I think this can be closed. Please re-open if you still need this epic.
