### ISSUE TITLE
Drop support for private clusters with private DNS

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#2690]
We have decided that for the CAPI SR/GA scope we will be dropping support for private clusters with private DNS. This setup has proven to be overcomplicated, bringing overhead to Giant Swarm as well as to customers. We do not see any real requirements for this setup to be continued. 

We will continue with ONLY public DNS for private clusters.

```[tasklist]
### Tasks
- [x] Spin up new private Goat-v2 with Public DNS
- [x] Clean up private DNS setup, MCs, tests, irsa-operator, remove the last irsa/iam operators dependency
- [x] Constrain the CRs not allowing to set private DNS zone
```

**Comment by calvix** [comment]
done
