### ISSUE TITLE
Implement cluster autoscaling in capa machine pools

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2692]
### Motivation
In order to have a dynamic scaling platform that is most reliable we identified in https://github.com/giantswarm/roadmap/issues/2618 the need to implement cluster autoscaling in our biggest provider: capa. 

### Todo

- [x] Set cluster.x-k8s.io/replicas-managed-by: "external-autoscaler" annotation on machinepool
  - What to set as initial replicas ?
- [x] Set min / max value on awsmachinepool
- [x] install cluster-autoscaler inside the workload cluster with standard Cloud and Kubernetes RBAC for cluster-autoscaler to work

Notes
This setup runs in the workload cluster and manages that specific workload cluster.
Main advantage of this solution is that the autoscaling feature for the workload cluster is completely decoupled from the CAPI management cluster

### Outcome
- We have cluster autoscaler in capa in place making running workload on capa more reliable.

**Comment by njuettner** [comment]
By using cluster-aws v0.47.0 and default-apps-aws v0.36.0 we do use cluster-autoscaler for CAPA MachinePools
