### ISSUE TITLE
Test first CAPZ installation with Teleport

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2697]
Installations:
- [x] glippy
```[tasklist]
### Tasks (Public WC)
- [x] Secure Kubernetes access via Teleport
- [x] Secure SSH access via Teleport
```

```[tasklist]
### Tasks (Private WC)
- [x] Secure Kubernetes access via Teleport
- [x] Secure SSH access via Teleport
```
