### ISSUE TITLE
Extend capi-image-builder to bake teleport binary

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#2699]
Discussion:
- https://github.com/giantswarm/cluster-aws/pull/334#discussion_r1259590497
- https://gigantic.slack.com/archives/C04KA9DBMB2/p1690790585949089

```[tasklist]
### Tasks
- [x] Prepare PR with proposed solution - https://github.com/giantswarm/capi-image-builder/pull/95
- [x] Ensure teleport ansible role works on Flatcar and Ubuntu
- [x] Verify teleport binary is present in AMI
```

**Comment by tuladhar** [comment]
Related - https://github.com/giantswarm/giantswarm/issues/27994

**Comment by tuladhar** [comment]
Discussion to test manually - https://gigantic.slack.com/archives/C02HLSDH3DZ/p1693299124826849
