### ISSUE TITLE
Loki customers, sales, marketing, partnership

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#271]
## Goals

**1. Current customers know without ambiguity that they can use a Managed Loki from us. Those who want to use our Managed Loki get the support they need in order to start using it.**

- [x] Loki + friends demo for customers https://github.com/giantswarm/giantswarm/issues/15694 - Potentially, live event to maximize attendants. Recording so SEs and customers can access even after the live event. @piontec and @brinker211 (sig-customer-happiness)
- [ ] Work with SEs to work w customers https://github.com/giantswarm/giantswarm/issues/15622 @ced0ps 

**2. Sales Enablement. Franz, Henning, and everyone in Giant Swarm know how to talk about our Managed Loki.** 
Ref: [Managed Apps Unique Value Proposition](https://docs.google.com/document/d/1AtRJpHB7051X_7Qv3ex4RhrGnv-zZpTaoU-oFfi04JQ/edit)
Issue: https://github.com/giantswarm/giantswarm/issues/15857

**When talking to prospective customers (esp. buyers, not just users)**
* For whom is our Managed Loki best for?
* What are their alternatives?
* When should they use our Managed Loki vs an alternative? (e.g. when security, owning your logs, etc. are important)

- [x] Confirm w @foschubert and @henninglange that this would be valuable.
- [x] Edit simple Managed Loki sales enablement doc https://github.com/giantswarm/roadmap/issues/271#issuecomment-781443190
- [x] Waiting for feedback https://github.com/giantswarm/giantswarm/pull/16338

**3. Marketing. Provide logging guidance for prospective users (not buyers) in Room 2.**

- [ ] Why we are bullish on Loki https://github.com/giantswarm/giantswarm/issues/14031 -- waiting for feedback
- [x] Repackage and push the stuff we've created about Loki. https://www.google.com/search?q=site:giantswarm.io+loki&ei=4z02YIi-Noe6gAbP4ryADQ&start=0&sa=N&ved=2ahUKEwjIu_rOuoLvAhUHHcAKHU8xD9A4ChDx0wN6BAgLEDI&biw=1420&bih=946 
w @Oshratn , cc @HelloHeatherC -- I'll do this.

**4. Partnership - Our offering, including this Managed Loki, is completely open source. This is because we don't believe in any form of crippleware, enterprise edition etc.**

We want to prevent customers from getting locked in. We want to contribute to our open source partners. What can we do? e.g.
* When we talk to customers who we think are better off using (1) DIY open source,  (2) Grafana Cloud, (3) Grafana Enterprise, we want to send these customers to them.
* If they encounter customers who fit our offering better, we would appreciate a chance to talk to them.

- [x] Brainstorm w @Jul85 
- [x] @Jul85 will talk to community manager

* With the experience, customers, and knowledge we have, what can we contribute to Grafana (company)?
* What can we propose to do together?
* As @HelloHeatherC shared in this [issue](https://github.com/giantswarm/giantswarm/issues/15480), Linkerd tweeted about @glitchcrab adding us as contributor. Maybe we can get on a call w Linkerd to brainstorm, apply the learnings to Grafana? 

@giantswarm/team-halo FYI

## Later
- [ ] On broader Managed Apps value I want to work on this https://github.com/giantswarm/rfc/pull/16 (can't be completed in this cycle)

**Comment by Oshratn** [comment]
Per point #2 I suggest adding this into sales enablement. I will add it to the next round for now.

**Comment by puja108** [comment]
Sidenote: We've been pushing and talking about and even contributing to Loki from day 1. The upstream Helm chart was written by Julien over night at KubeCon Seattle. We also in general have a good relationship with Grafana (Tom Wilkie is a friend of many ppl at GS and we also know others) .

**Comment by cokiengchiara** [comment]
Wed, 17. Feb 2021 call w @Oshratn and @Jul85 [meeting notes](https://docs.google.com/document/d/1f6i1oLa6TG11kQMq30aFATw7mNHN69BRNgmmH1duRCU/edit)

- [ ] Write down next actions
- [ ] Summarize and share

**Comment by cokiengchiara** [comment]
@JosephSalisbury said he can reach out

**Comment by Jul85** [comment]
Hi @cokiengchiara ,

I reached out to Grafana yesterday and got a reply by a guy named Simeon Yep, who is responsible for business development. I will settle an appointment with him and loop @piontec in also (anyone else. Will keep you updated :-)

**Comment by cokiengchiara** [comment]
> **2. Sales Enablement. Franz, Henning, and everyone in Giant Swarm know how to talk about our Managed Loki.**

Just to share progress - I got started on this. My goal is a one-pager.

**As Franz, I want to know enough about Loki, so I can be a good counterpart in 5mins of conversation with a management in customer org.**

**What is Loki?**

**Loki is a logging management app.** 5 main use cases for logs are: Debugging and troubleshooting (why did my application crash?), monitoring, cybersecurity, compliance, and business intelligence.

**Why use Loki vs other tools for logging?**

When choosing a logging solution, you can choose between proprietary or open source. Within open source, the top two options are EFK and Loki (w Promtail and Grafana). Once you decide on Loki, you can choose between DIY, SaaS (? Grafana Cloud), Managed Upstream (Grafana Enterprise Stack), or Independently Managed (e.g. Giant Swarm, Metric Fire).


- **Option 1: Proprietary (e.g. DataDog, SolarWinds)**
	- I will not dwell on this and assume our target customers are more interested in open source tools.
	- Advantages
		- Easier and faster to set up than DIY
		- No need to devote a team of engineers to run
	- Disadvantages
		- Lack of flexibility
		- Priced for large enterprises. Too expensive for most.
		- Vendor lock in.
- **Option 2: Open source**
	- In general, “logging management” has 3 parts: You **collect and forward** the logging data, **store** it somewhere, and finally, **do something useful** with it, such as visualize, query, and create alerts from it. Two most popular options are Elasticsearch (EFK) and Loki (w Promtail and Grafana).
	- Option 2a: Elasticsearch. With Fluentd and Kibana. (EFK)
		- Parts

			- Collect and forward data - Fluentd

			- Store it - Elasticsearch

			- Do something useful (visualize, query, and create alerts) - Kibana


		- Why EFK?

			- Collects lots of data from logs and stores them in a big index.

				- Advantages

					- Execute complex queries very fast

				- Disadvantages

					- Index can be bigger then original data. Means

					- Expensive to store. Aside from cost, you have to be mindful about what you log.

					- Complex


	- Option 2b: Loki. With Promtail and Grafana.
		- Parts

			- Collect and forward data - Promtail

			- Store it - Loki

			- Do something useful (visualize, query, and create alerts) - Grafana


		- Why Loki?
- Which of our customers are using it?
	- Why Loki?
	- What are they using Loki for?

**Comment by teemow** [comment]
@cokiengchiara another dimensions on eg Datadog and also MetricFire is that they store data outside of the customers datacenter and control. This is an issue for some of our customers.

**Comment by cokiengchiara** [comment]
> @cokiengchiara another dimensions on eg Datadog and also MetricFire is that they store data outside of the customers datacenter and control. This is an issue for some of our customers.

thank you! Would it be the same w Grafana Cloud?

**Comment by teemow** [comment]
Yes

**Comment by piontec** [comment]
In the Open Source + commercial space we should include - IMHO - https://www.graylog.org/products/open-source

**Comment by cokiengchiara** [comment]
RFC 0014 - Giant Swarm Managed Apps UVP is the transition between DIY and Upstream Enterprise https://github.com/giantswarm/rfc/pull/16/files

**Comment by Jul85** [comment]
@piontec and I had a chat with Grafana Labs today:
- we met up with Simeon (he is responsible for partners and business development, but more for their enterprise offering)
- Grafana recently had a deal with AWS and AWS is offering Grafana now
- during the call we came to the conclusion that he is not the perfect contact for us at the moment, but he will connect us to the community team ( which seems to be more suitable for us to talk since we don't want to sell any licenses or offer their enterprise solution)
- he mentioned their upcoming _Observability con_ - I will talk to their community manager about it, maybe there is an opportunity for a talk if we want to do that.

**Comment by puja108** [comment]
> another dimensions on eg Datadog and also MetricFire is that they store data outside of the customers datacenter and control. This is an issue for some of our customers.

In the above context, it might be interesting to also look at opstrace, as they offer Loki (or rather a whole open source observability stack containing it) and their approach is to always host it in a (separate) k8s cluster inside the customer account (they spin up a standard EKS or GKE currently). They do the management somehow, but also have automation AFAIR. Their spin on it is that they do not go with Grafana, but replace it with their own product (also open source).

**Comment by cokiengchiara** [comment]
Tue, 09. Mar 2021
I will work on this week

- [ ] 📝Edit and publish: Why we are bullish on Loki
- [ ] 🙇‍♀️RFC 0014 - Giant Swarm Managed Apps UVP https://github.com/giantswarm/rfc/pull/16

**Comment by cokiengchiara** [comment]
Mon, 15. Mar 2021

* Edited and prepared for publishing https://github.com/giantswarm/giantswarm/issues/14031#issuecomment-797628460 -- waiting for feedback

For this cycle:
- [ ] Repackage and push the stuff we’ve created about Loki. https://www.google.com/search?q=site:giantswarm.io+loki&ei=4z02YIi-Noe6gAbP4ryADQ&start=0&sa=N&ved=2ahUKEwjIu_rOuoLvAhUHHcAKHU8xD9A4ChDx0wN6BAgLEDI&biw=1420&bih=946
- [ ] 16.03.2021 Edit simple Managed Loki sales enablement doc https://github.com/giantswarm/roadmap/issues/271#issuecomment-781443190

RFC will not be done this cycle. But want to work on it next after this cycle.

> * he mentioned their upcoming _Observability con_ - I will talk to their community manager about it, maybe there is an opportunity for a talk if we want to do that.

@Jul85 were you able to talk w the community manager? :)

**Comment by Jul85** [comment]
Hi @cokiengchiara: I reached out to them again yesterday but still got ne feedback yet. I will try again via linkedIn. Maybe that works better. Will keep you updated.

**Comment by Jul85** [comment]
Update: Lukasz and I will have a meeting with the Loki community manager next week.  @cokiengchiara

**Comment by cokiengchiara** [comment]
1. Finally merged this one: https://intranet.giantswarm.io/docs/product/managed-apps/loki/

Feedback from Henning
> Like the format! Very useful. If we create this for other building blocks/apps a central place eg on our wiki would be good, so we know where to turn to and read things up again...

Asking if anything that’s missing from the format? And, based on recent sales conversations — for which building blocks / apps would sth like this be most useful right now?

2. Issues waiting other people have own tickets

* https://github.com/giantswarm/giantswarm/issues/15622
* https://github.com/giantswarm/giantswarm/issues/14031

3. Longer term will work on maybe this week https://github.com/giantswarm/rfc/pull/16

So closing this. 

@Jul85 please share Loki community manager notes in slack or sth 😀
