### ISSUE TITLE
Private links creation fails when the cluster is deployed to a VNet from another resource group

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2722]
### Motivation

See https://gigantic.slack.com/archives/C0559SH3RJ4/p1690814206741659 for reference

Our code in the CAPZ controller that creates private links on the private clusters always assumes that the VNET is part of the same resource group as the cluster.

This is not true for environments where the VNETs are pre-created and where cluster is using a VNet from a resource group that is different than the "main" cluster resource group.

### TODO

- [x] Find where the incorrect resource group is used.
- [x] Fix the bug and use the correct resource group. https://github.com/giantswarm/cluster-api-provider-azure/pull/20
- [x] Test the outcome. 
- [x] Create new cluster-api-provider-azure fork release on [branch `release-1.8`](https://github.com/giantswarm/cluster-api-provider-azure/tree/release-1.8).
- [x] Create new cluster-api-provider-azure-app release that is using the above cluster-api-provider-azure fork release.
  - [x] https://github.com/giantswarm/cluster-api-provider-azure-app/pull/119
  - [x] https://github.com/giantswarm/cluster-api-provider-azure-app/pull/120
  - [x] https://github.com/giantswarm/capz-app-collection/pull/52
  - [x] Make sure the new release is running in CAPZ MCs
- [x] In Giant Swarm cluster-api-provider-azure fork, cherry pick the fix from [branch `release-1.8`](https://github.com/giantswarm/cluster-api-provider-azure/tree/release-1.8) to [branch `release-1.10`](https://github.com/giantswarm/cluster-api-provider-azure/tree/release-1.10).
- [x] Finally, in Giant Swarm cluster-api-provider-azure fork cherry pick the fix to [`add-privatelink-support-clean` branch](https://github.com/giantswarm/cluster-api-provider-azure/tree/add-privatelink-support-clean) (this branch is used [in the upstream PR](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/3747)).

### Outcome

- Private links are correctly deployed when the cluster is using an existing resource group that is different than the cluster resource group.

**Comment by nprokopic** [comment]
Bug has been fixed and tested with pre-created VNets on multiple management clusters.
