### ISSUE TITLE
CAPA SR release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2726]
## Epic

First CAPA release.

```[tasklist]
### Scope
- [ ] https://github.com/giantswarm/roadmap/issues/1650
- [ ] https://github.com/giantswarm/roadmap/issues/2522
- [ ] https://github.com/giantswarm/roadmap/issues/3057
- [ ] https://github.com/giantswarm/roadmap/issues/2739
- [ ] https://github.com/giantswarm/roadmap/issues/3007
- [ ] https://github.com/giantswarm/roadmap/issues/2733
- [ ] https://github.com/giantswarm/roadmap/issues/2393
- [ ] https://github.com/giantswarm/roadmap/issues/2351
- [ ] https://github.com/giantswarm/roadmap/issues/1798
- [ ] https://github.com/giantswarm/roadmap/issues/2735
- [ ] https://github.com/giantswarm/roadmap/issues/1995
- [ ] https://github.com/giantswarm/roadmap/issues/2736
- [ ] https://github.com/giantswarm/roadmap/issues/2737
- [ ] https://github.com/giantswarm/roadmap/issues/2949
- [ ] https://github.com/giantswarm/giantswarm/issues/29254
```

## Links
- [Scope document](https://docs.google.com/document/d/1oYXIs_Zj-eFVDGxFEILodEygC8-rK7cbTkzCtWVJOj4/edit#);

**Comment by alex-dabija** [comment]
I removed https://github.com/giantswarm/roadmap/issues/2734 from the scope of this issues because all the changes required for CAPA are already implemented.

**Comment by alex-dabija** [comment]
All the subissues have been addressed.
