### ISSUE TITLE
Add additional labels to all alerts for Team Turtles components

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#2728]
### Motivation

Team Turtles wants to more easily get insights about all alerts and pages related to Team Turtles components.

So we want to add additional labels to alerts (and tags in Opsgenie pages).

### TODO

- [ ] Come up with a list of alerts that we want to label.
- [ ] Come up with a list of labels/tags that we want to add.
- [ ] Label all alerts.
- [ ] Come up with ideas how we can use newly added labels/tags in order to get more insights and even directly improve alerting (e.g. inhibitions).

### Outcome

**For Team Turtles**

- Better (more precise, more concrete) insights into alerts related to Team Turtles components.
- Ability to use new insights to improve alerts and better prioritize operational work in our regular daily/weekly team work.
- Overall better alerting.
- Overall better on-call experience (e.g. less "false positive" alerts).

**For other teams**
- For Team Phoenix (as we do business hours on-call together): Overall better alerting for components owned by Team Turtles.
- For Team Phoenix (as we do business hours on-call together): Overall better on-call experience for components owned by Team Turtles (e.g. less "false positive" alerts).

**For customers**

- Improving alerting will enable the team to better solve operational issues, which leads to overall better and more stable product for our customers.

**Comment by weseven** [comment]
There have been a lot of reviews and alert rewrites/refactoring since this issue was originally opened, so most of the issues that were there (e.g., with inhibitions, false positive alerts) seems to have already been solved.
I've opened a PR to expand the descriptions of a few alerts, but it's nothing major: https://github.com/giantswarm/prometheus-rules/pull/1320

**Comment by weseven** [comment]
Regarding preparing the alert for team split: we can of course do this using the `team` label.
In prometheus-rules, that means updating the value of the label directly in the alert manifest.

Some alerts have that label defined as `team: {{ include "providerTeam" . }}`, with the actual value being `rocket` or `phoenix` depending on the cluster provider (helm expanded the macro to `team: {{ if or (eq .Labels.provider "cloud-director") (eq .Labels.provider "vsphere") }}rocket{{ else }}phoenix{{ end }}`). 
For some of these, the alert refers to standard components (e.g. the APIServer) which falls under turtles in any case.

For sloth-rules, the team label is added when the `PrometheusRule` manifest is generated depending on the directory on the repo; to change owners we will simply need to move the relevant alerts to the turtles directory and regenerate the manifests.

**Comment by weseven** [comment]
I think we'll need to further clarify if we want to keep the cloud/onprem provider distinction (so phoenix still gets apiserver/etcd/kubelet alerts for cloud, rocket for onprem, turtles gets alerts for their components like cluster-autoscaler and vpa), or if apiserver/etcd/kubelet generically belong to turtles.

First one is the current status of prometheus rule, second one would be the status of [this PR](https://github.com/giantswarm/sloth-rules/pull/221) in sloth-rules (for cloud alerts, onprem are excluded due to the filter in the rule), with apiserver/etcd/containerd/scheduler alerts all belonging to turtles and only cloud provider specific alerts to phoenix.

**Comment by weseven** [comment]
PRs: 
https://github.com/giantswarm/sloth-rules/pull/221
https://github.com/giantswarm/prometheus-rules/pull/1328

**Comment by weseven** [comment]
PRs merged, only thing needed for the actual split is changing OpsGenie configuration.
