### ISSUE TITLE
CAPA certificate management

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2731]
## Epic

CAPA workload clusters certificate management.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2474
- [ ] https://github.com/giantswarm/roadmap/issues/2476
- [ ] https://github.com/giantswarm/roadmap/issues/2502
- [ ] https://github.com/giantswarm/giantswarm/issues/15981
- [ ] https://github.com/giantswarm/giantswarm/issues/15976
- [ ] Deploy certificate management changes to all CAPA clusters
```

**Comment by gawertm** [comment]
@alex-dabija not sure we need this ticket specifically for CAPA, as the cert management wont be provider specific as far as I can see atm. maybe its enough to link https://github.com/giantswarm/roadmap/issues/2474 in the CAPA SR ticket

**Comment by alex-dabija** [comment]
> @alex-dabija not sure we need this ticket specifically for CAPA, as the cert management wont be provider specific as far as I can see atm. maybe its enough to link #2474 in the CAPA SR ticket

I think it's still needed because you still have to do the integration work on CAPA (cluster-aws), rollout to CAPA MCs, testing and validation on CAPA, delete the keys from CAPA workload clusters, etc.

The general issue https://github.com/giantswarm/roadmap/issues/2474 would still be open (I assume) until the feature is deployed to all providers (including CAPV, etc.).

The purpose of this issue is to have it closed as soon as the work is done for CAPA, without waiting on the other providers, in order to have clear status of CAPA.

All of this being said, feel free to close this issue and link the general one to CAPA SR instead if you think the feature can be delivered at the same time for all providers.

**Comment by gawertm** [comment]
closing this one, open issues ares till tracked here https://github.com/giantswarm/roadmap/issues/2474
