### ISSUE TITLE
CAPA Teleport for SSH & cluster access

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2733]
## Epic

Replace the Giant Swarm VPN with Teleport for SSH and Kubernetes API access to CAPA clusters.

```[tasklist]
- [x] Enable Teleport Kubernetes Access for all CAPA clusters (MC)
- [x] Enable Teleport Kubernetes Access on all CAPA clusters (WC)
- [x] Build AMI for Kubernetes v1.24.16 with Teleport binary and release cluster-aws
- [x] Enable Teleport SSH Access for all CAPA clusters (MC)
- [x] Enable Teleport SSH Access for all CAPA clusters (WC)
```

## Links
- [Teleport investigation and POC issue](https://github.com/giantswarm/roadmap/issues/2463);
- [Teleport documentation](https://goteleport.com/docs/);

**Comment by tuladhar** [comment]
MCs:
- [ ] gazelle
- [ ] golem
- [ ] snail
- [ ] goat
- [ ] grizzly
