### ISSUE TITLE
CAPA default network policies

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2734]
## Epic

Configure default network policies with the same behavior as Vintage clusters for CAPA clusters.

```[tasklist]
- [ ] https://github.com/giantswarm/giantswarm/issues/23014
- [ ] https://github.com/giantswarm/giantswarm/issues/27266
- [ ] Ensure all CAPA clusters have the default network policies configured (cluster upgrades)
- [ ] https://github.com/giantswarm/giantswarm/issues/29976
```

## Links
- [Default network policies implementation issue](https://github.com/giantswarm/giantswarm/issues/23014).

**Comment by alex-dabija** [comment]
Waiting on the next Cilium release v1.15.0.

**Comment by teemow** [comment]
ping @alex-dabija

**Comment by alex-dabija** [comment]
The network policies are now aligned between AWS Vintage & CAPA.
