### ISSUE TITLE
CNCF conformance tests for CAPA clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2735]
## Epic

Run on CI the CNCF conformance test suite for CAPA clusters. Fix any failed tests.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2423
- [ ] https://github.com/giantswarm/roadmap/issues/3086
- [x] CAPA fix CNCF conformance tests
```
