### ISSUE TITLE
CAPA test environments

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2736]
## Epic

CAPA test environments for:
- teams to tests their changes;
- CI to run automated tests;

Every major supported cluster configuration (public, private, with proxy, without proxy) for each supported provider should have test environments.

The test environments must be documented and their purpose should be clearly highlighted.

```[tasklist]
- [x] CAPA public cluster test environment
- [ ] CAPA private cluster with HTTP/HTTPS proxy test environment
- [ ] CAPA private cluster witout HTTP/HTTPS proxy test environment
```

**Comment by alex-dabija** [comment]
We do have a test environments for public and private with proxy CAPA MCs.
