### ISSUE TITLE
CAPZ SR release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2738]
## Rock

First Giant Swarm CAPZ release.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2012
- [ ] https://github.com/giantswarm/roadmap/issues/2740
- [ ] https://github.com/giantswarm/roadmap/issues/2741
- [ ] https://github.com/giantswarm/roadmap/issues/2745
- [ ] https://github.com/giantswarm/roadmap/issues/2748
- [ ] https://github.com/giantswarm/roadmap/issues/2749
- [ ] https://github.com/giantswarm/roadmap/issues/1376
- [ ] https://github.com/giantswarm/roadmap/issues/2750
- [ ] https://github.com/giantswarm/roadmap/issues/1659
- [ ] https://github.com/giantswarm/roadmap/issues/2751
- [ ] https://github.com/giantswarm/roadmap/issues/2042
```

## Links
- [Scope document](https://docs.google.com/document/d/1oYXIs_Zj-eFVDGxFEILodEygC8-rK7cbTkzCtWVJOj4/edit#);

**Comment by teemow** [comment]
@alex-dabija is this epic still needed?

**Comment by alex-dabija** [comment]
> @alex-dabija is this epic still needed?

Yes, it's still needed because on CAPZ we still don't have autoscaling.

**Comment by alex-dabija** [comment]
Closing for now. We'll focus on CAPZ autoscalling in a separate issue.
