### ISSUE TITLE
CAPZ release process

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2740]
## Epic

Define and implement the release process of CAPA workload clusters.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2522
- [ ] Implement the release process
- [ ] Update the public documentation
```

## Links
- [Release process issue](https://github.com/giantswarm/roadmap/issues/2522);

**Comment by alex-dabija** [comment]
CAPZ is now using the new release mechanism (see [Azure releases](https://github.com/giantswarm/releases/tree/master/azure/v25.0.0)).
