### ISSUE TITLE
CAPZ certificate management

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2741]
## Epic

CAPZ workload clusters certificate management.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2474
- [ ] https://github.com/giantswarm/roadmap/issues/2476
- [ ] https://github.com/giantswarm/roadmap/issues/2502
- [ ] https://github.com/giantswarm/giantswarm/issues/15981
- [ ] https://github.com/giantswarm/giantswarm/issues/15976
- [ ] Deploy certificate management changes to all CAPZ clusters

**Comment by gawertm** [comment]
https://github.com/giantswarm/roadmap/issues/2474
