### ISSUE TITLE
Implementing Phase 1: extract Cluster API resources

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2742]
### Motivation
As we learned in https://github.com/giantswarm/giantswarm/issues/27020 we can improve the general code organisation of our systems for higher efficiency with better engineering workflows. In this issue we want to implement the changes in phase 1 of the investigated concept and extract the cluster api resources into a cross-provider layer.

### Todo

Implement the results from https://github.com/giantswarm/giantswarm/issues/27020 phase 1 and extract the cluster api resources from the cluster-aws app into its own provider independent cluster chart.

- [x] Cluster resource https://github.com/giantswarm/cluster/pull/3
- [x] KubeadmControlPlane resource https://github.com/giantswarm/cluster/pull/11
  - [x] Flatcar Ignition
    - [x] systemd units
    - [x] Storage (filesystems and directories)
  - [x] Cluster configuration
    - [x] API Server
    - [x] Controller manager
    - [x] Scheduler
    - [x] etcd
    - [x] Networking
  - [x] Init configuration
  - [x] Join configuration
  - [x] Pre/Post Kubeadm commands
    - [x] Flatcar
    - [x] SSH
    - [x] Proxy
    - [x] kubelet
    - [x] custom commands (e.g. provider-specific commands set in `cluster-<provider>` app)
  - [x] Files
    - [x] OIDC
    - [x] SSH
    - [x] kubelet config
    - [x] timesyncd
    - [x] sysctl
    - [x] proxy
    - [x] Kubernetes (policies, encryption)
    - [x] containerd
  - [x] Users
- [x] Machine pools resources https://github.com/giantswarm/cluster/pull/13
  - [x] MachinePool resource
  - [x] KubeadmConfig resource
    - [x] Flatcar Ignition
      - [x] systemd units
      - [x] Storage (filesystems and directories)
    - [x] Init configuration
    - [x] Join configuration
    - [x] Pre/Post Kubeadm commands
      - [x] Flatcar
      - [x] SSH
      - [x] Proxy
      - [x] kubelet
      - [x] custom commands (e.g. provider-specific commands set in `cluster-<provider>` app)
    - [x] Files
      - [x] SSH
      - [x] kubelet config
      - [x] timesyncd
      - [x] sysctl
      - [x] proxy
      - [x] containerd
- [x] Bastion resources https://github.com/giantswarm/cluster/pull/15
  - [x] MachineDeployment
  - [x] KubeadmConfigTemplate
- [x] MachineHealthCheck resource https://github.com/giantswarm/cluster/pull/14

The initial implementation above is done. Now few additional tasks  :play_or_pause_button: in progress
- [x] Add needed changes that were recently added in `cluster-aws` after commit `Release v0.42.0 (#381)`
- [x] Address few issues that were found in `cluster` chart PRs. 

### Outcome
- We have a better code organisation leading to more efficient engineering workflows

**Comment by nprokopic** [comment]
This has been completed, provider-independet resources have been ported to cluster chart, see repo https://github.com/giantswarm/cluster for more details.
