### ISSUE TITLE
CNCF conformance tests for CAPZ clusters

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2750]
## Epic

Run on CI the CNCF conformance test suite for CAPZ clusters. Fix any failed tests.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2423
- [ ] Submit CNCF conformance test results for CAPZ clusters
- [ ] CAPZ fix CNCF conformance tests
```
