### ISSUE TITLE
CAPZ test environments

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2751]
## Epic

CAPZ test environments for:
- teams to tests their changes;
- CI to run automated tests;

Every major supported cluster configuration (public, private, with proxy, without proxy) for each supported provider should have test environments.

The test environments must be documented and their purpose should be clearly highlighted.

```[tasklist]
- [ ] CAPZ public cluster test environment
- [ ] CAPZ private cluster with HTTP/HTTPS proxy test environment
- [ ] CAPZ private cluster witout HTTP/HTTPS proxy test environment
```

**Comment by teemow** [comment]
@alex-dabija I'm cleaning up old issue and I think this can be closed. Please re-open if you still need this epic.
