### ISSUE TITLE
CAPV release process

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2754]
## Epic

Define and implement the release process of CAPV workload clusters.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2522
- [ ] Implement the release process
- [ ] Update the public documentation
```

## Links
- [Release process issue](https://github.com/giantswarm/roadmap/issues/2522);

**Comment by teemow** [comment]
@alex-dabija I'm cleaning up old issue and I think this can be closed. Please re-open if you still need this epic.
