### ISSUE TITLE
CAPA SR2 release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2755]
## Rock

Second CAPA release.

```[tasklist]
### Scope
- [ ] https://github.com/giantswarm/giantswarm/issues/25395
- [ ] https://github.com/giantswarm/roadmap/issues/1843
- [ ] https://github.com/giantswarm/giantswarm/issues/25443
- [ ] https://github.com/giantswarm/roadmap/issues/1661
```
