### ISSUE TITLE
Ingest logs from workload clusters

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2756]
### User story

* As a Giant Swarm engineer, I want to be able to access a history of logs for system components running on workload clusters in order to both investigate ongoing operational issues and provide details for incident reports

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2761
- [ ] https://github.com/giantswarm/roadmap/issues/2758
- [ ] https://github.com/giantswarm/roadmap/issues/2834
- [ ] https://github.com/giantswarm/roadmap/issues/2765
- [ ] https://github.com/giantswarm/roadmap/issues/2763
- [ ] https://github.com/giantswarm/giantswarm/issues/27859
- [ ] https://github.com/giantswarm/giantswarm/issues/28445
- [ ] https://github.com/giantswarm/giantswarm/issues/28446
- [ ] https://github.com/giantswarm/giantswarm/issues/28842
- [ ] https://github.com/giantswarm/roadmap/issues/2835
```

**Comment by QuentinBisson** [comment]
I think we're done here
