### ISSUE TITLE
Switch CAPV to Flatcar

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2757]
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2793
- [ ] https://github.com/giantswarm/roadmap/issues/2805
- [x] Ensure default-apps-vsphere is OK with Flatcar
- [ ] Design distribution of images to customer environments
```
