### ISSUE TITLE
Dev platform PoC: create sample repo cloning workflow

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2769]
Let's try to use a new crossplane XRD to create a `Project` type object, that results in cloning an example of go project github repo into a new one.
```[tasklist]
### Tasks
- [ ] prepare a golang template github repo
- [ ] define a `Project` type XRD in crossplane
- [ ] include a `Job` in the crossplane XRD that will actually run repo cloning logic
- [ ] hook up this process in backstage
```

**Comment by weatherhog** [comment]
closing this issue as the PoC was not done
