### ISSUE TITLE
Multitenant logging infrastructure for customer workloads

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2771]
### User story

* As an engineer I want to be able to access a history of logs for my components in order to investigate ongoing operational issues
* As an admin I want my logs to only be readable by a specific list of people
* As an engineer I want to be able to scrape logs per namespace 

```[tasklist]
### Step 0: Proof Of Concept
- [ ]  https://github.com/giantswarm/roadmap/issues/1131
```

```[tasklist]
### Step 1: Read path: OAuth support
- [ ] https://github.com/giantswarm/roadmap/issues/3226
- [ ] https://github.com/giantswarm/giantswarm/issues/29750
- [ ] Figure out how to get tenants from the oauth groups
```

```[tasklist]
### Step 2: Ingest per tenant logs (Write path)
- [ ] https://github.com/giantswarm/giantswarm/issues/28022
```

```[tasklist]
### Final steps
- [ ] https://github.com/giantswarm/giantswarm/issues/25198
- [ ] https://github.com/giantswarm/giantswarm/issues/29580
- [ ] https://github.com/giantswarm/roadmap/issues/1572
```

**Comment by TheoBrigitte** [comment]
CNCF sandbox logging operator might be interesting, https://kube-logging.dev/ https://github.com/kube-logging/logging-operator

**Comment by QuentinBisson** [comment]
We are blocked waiting for the RFC to be merged

**Comment by Rotfuks** [comment]
Closed as Duplication of #3558
