### ISSUE TITLE
setup go code with tests for devplatform-template-go-repo

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2775]
```[tasklist]
### Tasks
- [x] simple go web service that responds 'hello world'
- [x] sample promethues metrics endpoint
- [x] unit tests for the above
- [x] changelog
- [x] docs
- [ ] runbooks
```

**Comment by weatherhog** [comment]
@piontec is this issue still needed?

**Comment by piontec** [comment]
done actually
