### ISSUE TITLE
setup helm chart for devplatform-template-go-repo

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2776]
```[tasklist]
### Tasks
- [x] proper deployment and service
- [x] incoming traffic: cert, ingress
- [x] deployment pattern: affinity
- [x] monitoring CR: ServiceMonitor
- [x] helm-docs
- [x] DNS registration
- [x] disruption budget
- [x] JSON schema
- [x] grafana dashboard?
- [x] alertmanager rules?
```

**Comment by weatherhog** [comment]
@piontec is this issue still needed?
