### ISSUE TITLE
setup validation and scan tools for devplatform-template-go-repo

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2777]
```[tasklist]
### Tasks
- [x] go vet for devplatform-template-go-repo
- [x] pre-commit for
- [x] gitleaks for devplatform-template-go-repo
- [ ] https://github.com/ossf/scorecard ?
```

**Comment by weatherhog** [comment]
@piontec is this issue still needed?

**Comment by piontec** [comment]
`scorecard` would be a nice addition, very short task to do
