### ISSUE TITLE
setup build and upgrade processes for devplatform-template-go-repo

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2778]
```[tasklist]
### Tasks
- [x] goreleaser
- [x] renovate: dockerfile
- [x] some security scans
- [x] github actions
- [x] helm chart build
- [x] renovate: go
- [x] renovate: github actions
```

**Comment by weatherhog** [comment]
@piontec is this issue still needed?

**Comment by piontec** [comment]
done
