### ISSUE TITLE
Test first CAPA private installation with Teleport

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#2786]
## Motivation

Integrate teleport for private cluster.

```[tasklist]
### Tasks
- [x] Deploy teleport-operator in `goat` with private proxy setting
- [x] Create workload cluster in goat with private proxy settings
- [x] Update `teleport-kube-agent` app to use private proxy setting
- [x] Update `cluster-aws` to support private proxy for teleport.service
- [x] Verify cluster and ssh access to workload cluster
```

**Comment by tuladhar** [comment]
1. Install teleport client

Linux:
```
$ curl https://goteleport.com/static/install.sh | bash -s 13.3.8
```
Mac:
```
$ curl -O https://cdn.teleport.dev/teleport-13.3.8.pkg
$ sudo installer -pkg teleport-13.3.8.pkg -target /
$ which teleport
```

2. Login to teleport via GitHub
```
$ tsh login --proxy test.teleport.giantswarm.io:443 --auth github
```
Click on “Other sign-in options” and GitHub.

3. Access workload cluster
```
$ tsh kube login goat-bigmac
$ tsh kubectl get nodes -o wide
```

4. SSH into workload cluster control-plane and worker nodes
```
# ssh into control-plane
$ tsh ssh giantswarm@mc=goat,cluster=bigmac,role=control-plane

# ssh into worker
$ tsh ssh giantswarm@mc=goat,cluster=bigmac,role=worker
```
