### ISSUE TITLE
Web UI for organization access control via the Management API

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#281]
Towards https://github.com/giantswarm/roadmap/issues/218

## User Story

- _As a customer admin, I want to create organizations to keep my cluster and app related resources in the management API tidy and systematic and isolated by team/project/concern._
- _As a customer admin, I want to assign user or user groups from my identity provider to organizations in the Giant Swarm Management API, so that each user has the right permissions to fulfil their needs only._

## Background

Once happa users use SSO (OIDC, Dex) for authentication, we want to also replace the organization management UI within our web UI (happa), in order to allow users to manage organizations and assignment of users to those organizations within the management API.

Users currently (in the REST API) can:

- Create organizations, delete organizations
- Add users and remove users
- Create clusters in organizations

Wit the new UI, admins should be able to

- Create organizations, delete organizations
- Assign users and user groups (from their identity provider) to organizations, using roles (or ClusterRoles) available in the Management API

We provide a few default roles (one with full access to everything in the organization, one with read-only access) and customers can add their own, more specific roles or cluster roles. So this new organization assignment provides more flexibility towards permission management.

## Tasks

- [x] Draft UI spec
- [x] Get customer feedback
- [x] Implementation
- [x] Documentation changes/additions

**Comment by marians** [comment]
## UI spec

Our approach for the UI will be focused on a single organization. It will be also focused on adding/removing bindings for subjects (users, groups, service accounts) to roles (resulting in creation, removal, change of `RoleBinding` resources in the org namespace).

We are currently not aiming to support the creation, editing or removal of roles or cluster roles.

**Context:** An organization details page is going to provide two top level tabs. The default tab will provide aggregated information on the organizatio's clusters etc., the second one will be titled **Access control** and is the one we describe here in detail.

### Screens

Screen 1: Cluster role `read-all` is selected, with details on the right hand side showing the subjects (users, groups, service accounts) bound to this role.

![Organization details – Access control – read-all Subjects](https://user-images.githubusercontent.com/273727/110773973-977c3080-825d-11eb-86be-8ce951f1c84c.png)

Screen 2: Namespaced role `read-apps` is selected. On the right hand side, the Permissions tab has been selected.

![Organization details – Access control – read-apps Permissions](https://user-images.githubusercontent.com/273727/110780426-f72a0a00-8264-11eb-9566-48dbdfe9bba4.png)

### Detail explanations

The roles list on the left shows all roles and cluster roles which are accessible to the current user and can be bound in the organizations namespace via a `RoleBinding`. The role/clusterrole name is shown, plus some summary. CLuster roles are indicated via a 🌐   icon.

The search functions allows to filter the list down to matching roles as the user types in a search query. Here we want to cover not only role names, but also resources and subject names (user names, group names).

<details>

![image](https://user-images.githubusercontent.com/273727/110778501-b8935000-8262-11eb-9eda-88107a127a15.png)

</details>

The right hand side details panel shows a header with the name of the selected role, the type (cluster role or namespaced) and information regarding who manages the role. Based on labels, some roles may be managed by Giant Swarm, others may be managed by Helm. And some may not have any managed-by labels – in this case we show "Managed by you".

<details>

![image](https://user-images.githubusercontent.com/273727/110779053-64d53680-8263-11eb-901b-62f0c6c5aabd.png)

![image](https://user-images.githubusercontent.com/273727/110779121-761e4300-8263-11eb-9a57-6e01148c385c.png)

</details>

The **Subjects** tab shows which groups, users, service accounts are bound to the selected role. Here, we collect subjects from all role bindings in the organization's namespace and display them groped by subject type.

<details>

![image](https://user-images.githubusercontent.com/273727/110779405-c85f6400-8263-11eb-8b56-fc2336d7e210.png)

</details>

**Removing subjects** will be done via the `×` icon on each item. Some items, which are assigned through role bindings managed by Giant Swarm's operators, will not be removable via this UI and won't have a `×` icon.

<details>

![image](https://user-images.githubusercontent.com/273727/110782063-f7c3a000-8266-11eb-9e6b-7f361919bebe.png)

</details>

**Adding subjects** is done by hitting the `Add` button next to the group, user, service account items. This will reveal an input field where users can enter a single identifier or multiple identifiers. White space (includign line breaks) and commas can be used as separator when entering multiple identifiers. After hitting Enter/Return or clicking OK, the Management API calls to edit/create role bindings will be made. An activity indicator will the identifiers will be added t

<details>

![image](https://user-images.githubusercontent.com/273727/110783834-39554a80-8269-11eb-8f9e-5a173aa565df.png)

</details>

The **Permissions** tab shows a table of resources and verbs. Verbs are abbreviated to the first letter for the seven standard verbs `get`, `watch`, `list`, `create`, `update`, `patch`, `delete`. Other verbs will be indicated via the eighth ellipsis icon being highlighted. On mouse-over the full verbs will be displayed.

<details>

![image](https://user-images.githubusercontent.com/273727/110780360-e7122a80-8264-11eb-980b-3efddc578352.png)

![image](https://user-images.githubusercontent.com/273727/110780949-92bb7a80-8265-11eb-82b6-3ccf4fc82aa9.png)

</details>

**Comment by marians** [comment]
For the listing of roles in our UI we have to decide which role to show and which not.

On an Azure example installation, there are currently 194 cluster roles. In a real world scenario, a customer admin might have additional cluster roles and namespace specific roles they created in that list, so the total could be well beyond 200.

To make finding a role as easy as possible, we want to list only relevant entries.

## Option (A): Filter out based on existing metadata

After some research it seems as if we can filter out (do not show) the following:

- (cluster) roles where the name starts with `system:`. This applies to ~60 entries of the 194 mentioned.
- (cluster) roles that are created specifically for an app owned/managed by Giant Swarm. These usually carry a combination of labels like `app`, `app.giantswarm.io/branch`, `app.giantswarm.io/commit`, `app.kubernetes.io/managed-by` and `app`.
  - Caveat: the default cluster roles as we currently create them via rbac-operator also contain these labels (see below).

<details>
<summary>
Current view-all ClusterRole metadata
</summary>

```yaml
  metadata:
    annotations:
      meta.helm.sh/release-name: rbac-operator-unique
      meta.helm.sh/release-namespace: giantswarm
    labels:
      app: rbac-operator
      app.giantswarm.io/branch: HEAD
      app.giantswarm.io/commit: 4b97411945bbffa4febb91f480118dc6e1b52b06
      app.kubernetes.io/instance: rbac-operator-unique
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: rbac-operator
      app.kubernetes.io/version: 0.8.0
      giantswarm.io/service-type: managed
      helm.sh/chart: rbac-operator-0.8.0
```

</details>

## Option (B): Introduce specific label

An alternative would be to introduce a new label specifically to inform the web UI whether or not to show a cluster role.

Examples:

```nohighlight
ui.giantswarm.io/display: false
```

A `false` value would explicitly hide the role in the web UI and potentially also in an opinionated CLI.

## Combination of (A) and (B)

Option (A) will be the quickest to implement, as it requires no changes in existing resources (coming from a variety of apps), however it will not allow us full control.

We can combine the filtering based on existing labels (A) with the explicit label from (B). Here the explicit label should take precedence. Meaning e. g. if a `system:...` cluster role is labeled with `ui.giantswarm.io/display: true`, then the web UI will display it.

**Comment by corest** [comment]
I’d go with B and show only roles which are explicitly labeled by that label.
The reason is that most of existing roles/clusterroles are useless for customer as they allow super specific things. Also some of those like cluster-admin or system:masters can’t be used by customer admin as they allow more power that customer admin has.

therefore I’d start with us precreating most commonly used clusterroles, labeling them with display:true label and showing those few roles to customer

**Comment by puja108** [comment]
I had a thought about this over night and I tend to agree with Vol there. The default ones are not of much use as system:masters won't be usable and the others miss all the CRDs we expose to the customers. 

However, then I would only use `ui.giantswarm.io/display: true` and not `false` as relabeling the ones that get created by the API for example or by other installations (e.g. CNI, CoreDNS,...) will be a neverending task almost, as those might change with every version.

Minor downside: if a customer creates a role they need to add that label.
Mitigation: Have admission control add that label for customer created roles.

**Comment by marians** [comment]
Documentation for the UI described in this story is being added in https://github.com/giantswarm/docs/pull/907

**Comment by snizhana-dynnyk** [comment]
This is implemented and will become available per installation/customer, once the web interface is switched to using OIDC/single sign-on
