### ISSUE TITLE
Create a CAPA migration timeline

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#2824]
Create a CAPA migration timeline.

```[tasklist]
## TODOs
- [x] Propose roadmap
- [x] Discuss the roadmap proposal in WG Migration Sync
- [x] Discuss the roadmap proposal in KaaS Product Sync
- [x] Discuss the roadmap proposal in SIG Product Sync
- [x] Publish announcement on Slack
- [x] Get feedback from teams
```
## Links
- [Roadmap proposal](https://github.com/orgs/giantswarm/projects/273/views/28?filterQuery=-Availability%3A%22Rejected+%F0%9F%9B%91%22+working-group%3A%22CAPA+Migration%22+)

**Comment by JosephSalisbury** [comment]
migration sync discussion:

- sec components are in 19.1.1
- PSP updates for apps still need to be added
- once all apps are compliant, we can cut 19.3.0 (different security bundle sets enforce mode via configuration)
- flatcar SSH CVE fix (for vodafone) in 19.2.0 (which will roll nodes)

to be considered for timeline:

- all team PSP updates
- honeybadger: how we handle migrations of apps from vintage to CAPI
- phoenix: when is CAPA stable

**Comment by alex-dabija** [comment]
An initial proposal for the timeline is available on our public roadmap: https://github.com/orgs/giantswarm/projects/273/views/28?filterQuery=-Availability%3A%22Rejected+%F0%9F%9B%91%22+working-group%3A%22CAPA+Migration%22+ .

It's probably wrong and it needs to be discussed in the workgroup and with the POs / teams.
