### ISSUE TITLE
Document CAPI releases/upgrades

### ISSUE THREAD

**Issue by teemow** [giantswarm/roadmap#2825]
### Motivation
As we heavily investigated a clear, formalised release flow for CAPI, we now have to document our outcome so that everyone can be onboarded to this new release process. 

### Todo

- [ ] Create internal documentation for our intranet with the details of the new release flow
- [ ] Derive a public documentation for our customers from the internal documentation 
- [ ] Look through the intranet and public docs for existing release documentation and if they are still up to date with the new information

### Outcome
- We have a clear documentation of the release flow for internal use in the intranet
- We have a clear documentation for our customers in the public doc
- All existing documentations around releases are either up to date or we have follow up tickets to update them.

**Comment by teemow** [comment]
@Rotfuks can you fill in the existing issues from turtles here please.

**Comment by JosephSalisbury** [comment]
@Rotfuks what's the state here? "investigation" feels less ready to get going than "backlog"

**Comment by JosephSalisbury** [comment]
from migration sync: we think a lot has happened, it'd be helpful to have a lil' update here

**Comment by Rotfuks** [comment]
As we're currently still in the investigation phase of the future Release process we have no customer ready documentation yet. But internal documentation of the progress is here: [https://miro.com/app/board/uXjVM0oMunQ=/?share_link_id=61564219597](https://miro.com/app/board/uXjVM0oMunQ=/?share_link_id=61564219597)

This story will be done as a closure of the investigation so to say :)

**Comment by Rotfuks** [comment]
For the internal use case we now have the document describing our release framework. 
The most relevant part in there for customers is the part about applying the cluster-<provider> chart to create and update clusters. Since we will have a follow up ticket to implement the documented target state, we will create public customer facing documentation on that updated state once we reach it and customers can actually use it. 
So at this stage I'm rescoping this issue to focus on the public customer facing documentation only and move it to the epic for the implementation of the framework.

**Comment by Rotfuks** [comment]
Story will be done in the scope of these user stories: https://github.com/giantswarm/roadmap/issues/3140
Additional we will work on a workbook documenting a list of How-Tos around the document of the release process here: https://github.com/giantswarm/roadmap/issues/3143

Currently we don't have additional public documents from the release framework yet.

**Comment by teemow** [comment]
@Rotfuks just fyi. We are planning to do a bigger effort on the docs to reflect all the changes with CAPI. Upgrades and releases need to be part of this as well and your teams help is needed there. I'll coordinate this with @pipo02mix

**Comment by Rotfuks** [comment]
Makes sense! As we already split this ticket in a documentation (or extension of the documentation) per provider we have already some work planned in, but we sure can improve the docs on some other positions as well :)

**Comment by pipo02mix** [comment]
The plan is next week work on the layout of the docs to be CAPI-ready. We have a SIG docs in 2 weeks, I would recommend you (or another turtle) to attend so I can present you the plan and we can discuss your ideas
