### ISSUE TITLE
[EPIC] Multi-Provider MCs

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#2840]
We want to enable a truly hybrid Installation where the MC is on Azure (CAPZ) and Workload clusters are Azure as well as on-prem vSphere (CAPZ & CAPV)

Acceptance Criteria: Create a GS Installation on Azur that is able to create 1 CAPZ WC and 1 CAPV WC on IONOS

User Story
As a GiantSwarm Customer & Platform Engineer I want to centralize as much of my applications and Administration as possible onto Azure, while still using some compute power available in the Factories with vSphere
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2961
- [ ] https://github.com/giantswarm/giantswarm/issues/28740
- [ ] https://github.com/giantswarm/giantswarm/issues/29126
```
