### ISSUE TITLE
Support per workload cluster alerting rules

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#2843]
Towards https://github.com/giantswarm/roadmap/issues/2832

### Description

As we are starting our journey towards providing/managing EKS and other cloud provider managed clusters, we need to be able to enable/disable some alerting rules based on the type of workload cluster.

The reason being that we have some specific alerts (eg. WorkloadClusterEtcdMetricsMissing) that targets components that we have no access to in Managed clusters like `etcd`, `kube-controller-manager` or the `kubernetes-scheduler`

### TODO

- [x] Support enabling/disabling alerting rules based on the workload cluster
- [x] Disable relevant alerts for EKS
- [ ] Update relevant docs.

cc @TheoBrigitte

**Comment by QuentinBisson** [comment]
3 possible solutions:

1. We update the PrometheusRule selector as done here https://github.com/giantswarm/prometheus-meta-operator/blob/a0dca186882dffa6ddb6777dd1873ad9faf81a61/service/controller/resource/monitoring/prometheus/resource.go#L286. This will not work with mimir because we will have only 1 ruler
2. We add a new label to metrics (via external labels) to define whether a cluster is a managed service or not (CAPA EKS vs CAPA) and we do not page when the service is managed `my_metric{managed_cluster="false"}`
3. We create an inhibition on the MC prometheus for managed clusters (based on CAPI Metrics) and add the inhibition to relevant alerts

**Comment by marieroque** [comment]
Third solution can creates the inhibition based on this metric `capi_cluster_info`:

![Image](https://github.com/giantswarm/roadmap/assets/9134338/270382bb-1e4a-4755-86df-1b2149d11323)

**Comment by TheoBrigitte** [comment]
We go with solution ii.

solution iii, feels fragile as we seen issues with inhibitions
solution i, won't hold when we move to Mimir

**Comment by QuentinBisson** [comment]
Label added to PMO and ignoring alerts for EKS
