### ISSUE TITLE
Support Object Storage on CAPV

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#2873]
To be able to provider proper observability on CAPV, we need to be able to create S3 compatible buckets.

Possible ideas:

- [ ] Customer has a cloud account that can be used with AWS S3 or Azure Blob Storage and we can use Crossplane
- [ ] Customer has a S3 compatible endpoint
- [ ] We support and manage CEPH
- [ ] We support and manage MinIO

We should strive to use the same tool for https://github.com/giantswarm/roadmap/issues/2874

**Comment by QuentinBisson** [comment]
cc @vxav

**Comment by vxav** [comment]
thread https://gigantic.slack.com/archives/C02521EC0/p1697019719140539

**Comment by gawertm** [comment]
for the Logging stack we need an S3 compatible storage. but for now all customers can provide this on-prem so we do not need to manage a S3 compatible storage for them. this means for our test installation we will just just AWs S3 storage for now. If there will be other use cases or customers who cannot provide S3 storage onprem, then we will re-evaluatea

**Comment by QuentinBisson** [comment]
I think we can close this one and reopen if the customer cannot provide  object storage ?
