### ISSUE TITLE
Simplify observability-bundle config overrides

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2879]
### Tasks

- [x] Implement new config structure in observability-bundle
- [x] Write migration doc (how to setup old and new config) https://github.com/giantswarm/observability-bundle/pull/153
- [x] Release observability-bundle new major version v1.0.0
- [x] Add observability-bundle into v20.0.0 cluster release https://github.com/giantswarm/releases/pull/1201

### Problems

* config overrides: current `observability-bundle` helm values structure make it difficult to override specific app config directives as each bundled app config is treated as a multi-line string and therefore need to be copied as a whole in order to be able to override specific app config directives.
* unified process: [`observability-bundle`](https://github.com/giantswarm/observability-bundle) and [`security-bundle`](https://github.com/giantswarm/security-bundle) helm values structure are different which make it complex to handle config override across different bundles, as different solutions for config overrides need to be implemented for each bundle.

### Goal

As a customer I want to be able to override specific config directives across different GiantSwarm bundle in a similar fashion, in order to reduce complexity in config management.

Therefore we should align `observability-bundle` helm values structure with `security-bundle` in order to remove the multiline string values and instead provide an object with directly accessible and overridable fields.

### Details

When referring to observability-bundle helm values here it means the `values.yaml` file provided to the observability-bundle app; you should be able to find this from any installation by using the following command:

```bash
kubectl get configmap $(kubectl get app observability-bundle -oyaml | yq -r .spec.userConfig.configMap.name) -oyaml | yq -r .data.values
```

### Current config example

This is an example of what the values for observability-bundle would currently look like when one tries to enable kubelet monitoring and overrides docker images registries.

```yaml
# values.yaml
apps:
  prometheus-operator-app:
    namespace: monitoring
    userConfig:
      configMap:
        values: |
          global:
            imageRegistry: "docker.io"
          prometheus-operator-app:
            kubelet:
              enabled: true
```

### Expected config example

This is an example of what the values for observability-bundle should look like once we re-structured the helm values.

```yaml
# values.yaml
apps:
  prometheus-operator-app:
    namespace: monitoring
userConfig:
  prometheus-operator-app:
    global:
      imageRegistry: "docker.io"
    prometheus-operator-app:
      kubelet:
        enabled: true
```

### References

- https://gigantic.slack.com/archives/C6L8J93N0/p1696431514807099
- https://github.com/giantswarm/security-bundle/pull/84

**Comment by QuentinBisson** [comment]
Should we take this opportunity to rename from prometheus-operator-app to kube-prometheus-stack-app? Or at least remove the app suffix in the helm chart?

**Comment by TheoBrigitte** [comment]
I tried with and failed, as the reference to this configmap within the App CR kept being reverted.

```yaml
apiVersion: v1
data:
  values: |
    userConfig:
      kubePrometheusStack:
        configMap:
          values:
            kube-prometheus-stack:
              grafana:
                enabled: true
kind: ConfigMap
metadata:
  name: observability-bundle-with-grafana
```

**Comment by TheoBrigitte** [comment]
The configmap should be named `<cluster id>-observability-bundle-user-values`.

**Comment by marieroque** [comment]
OLD Config + OLD o11y-bundle
`gaia/iy7a6` - `release 19.2.0` - `observability-bundle 0.10.0`

User Config specified:
```
data:
  values: |
    apps:
      prometheus-agent:
        namespace: kube-system
        userConfig:
          configMap:
            values: |
              prometheus-agent:
                serviceMonitor:
                  enabled: false
```

=> `prometheus-agent` ServiceMonitor correctly deleted on WC

**Comment by marieroque** [comment]
✅ Test the new config values files 

### Test plan
`gaia/iy7a6` - `release 19.2.0-marie` - `observability-bundle 0.10.0-9476a6dee6da39bdecca469c7b332d71097d8dc3`

UserConfig specified `iy7a6-observability-bundle-user-values`:
```
data:
  values: |
    apps:
      prometheusAgent:
        namespace: kube-system
    userConfig:
      prometheusAgent:
        configMap:
          values:
            prometheus-agent:
              serviceMonitor:
                enabled: true
```

`o11y-bundle` deployed with success.

```
[logging-operator]$ k get app -n iy7a6
NAME                                       INSTALLED VERSION                                 CREATED AT   LAST DEPLOYED   STATUS
iy7a6-observability-bundle                 0.10.0-9476a6dee6da39bdecca469c7b332d71097d8dc3   4m35s     
kube-prometheus-stack                      7.0.0                                             4m5s         110s            deployed
prometheus-agent                           0.6.6                                             4m5s         100s            deployed
prometheus-operator-crd                    6.1.0                                             4m5s         4m3s            deployed
```

**Comment by TheoBrigitte** [comment]
:warning: This breaking change must be part of our v20.0.0 release :warning: 

We should not introduce this change in any v19.x release, as those are minor and patch releases only.
We introduce a breaking change here which need to land into a major version. Please beware.

**Comment by TheoBrigitte** [comment]
We do not need to wait for v20.0.0 release, we can already prepare our request PR with an entry similar to this into https://github.com/giantswarm/releases/blob/master/aws/requests.yaml

```yaml
- name: ">= 20.0.0"
  requests:
  - name: observability-bundle
    version: ">= 1.0.0"
```

**Comment by QuentinBisson** [comment]
We're still waiting for customers feedback :)

**Comment by QuentinBisson** [comment]
@TheoBrigitte do you know where we should write the migration doc ? In the observability-bundle documentation ?

**Comment by TheoBrigitte** [comment]
Migration doc should go in observability-bundle README, maybe create a separate file for it and link it within the README.

**Comment by QuentinBisson** [comment]
Upgrade doc is here https://github.com/giantswarm/observability-bundle/pull/153

**Comment by angelbarrera92** [comment]
Any ETA for this?

**Comment by QuentinBisson** [comment]
@angelbarrera92 yes it will bé available with release 20.0.0, we're finishing thé migration doc

**Comment by QuentinBisson** [comment]
Observability-bundle 1.0.0 released. We will be good to go once 20.0.0 is out
