### ISSUE TITLE
EKS Import MVP

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#2890]
The goal is to get EKS import to a level that it feels as part of the product and we feel comfortable to onboard customers.

```[tasklist]
### Tasks
- [ ] EKS Import Crossplane Implementation with upcoming crossplane version
- [ ] Bring docs into public
- [ ] https://github.com/giantswarm/roadmap/issues/2928
- [ ] https://github.com/giantswarm/giantswarm/issues/27781
- [ ] App support in Happa
```

**Comment by mproffitt** [comment]
Happa support wasn't part of the original PoC but appeared in it as by-product of the import. 

I'd move this here to close out the PoC without being impacted by this requirement.

**Comment by marians** [comment]
I'm undecided how we should handle this topic in docs in general.

The easiest for getting docs out there would be to have a single page or section dedicated to the topic, potentially under https://docs.giantswarm.io/platform-overview/cluster-management/ . The implication would be that none of our other docs (at least when it comes to cluster management) applies to imported EKS.

On the other end of the spectrum, we could imply that every page and topic (apart from those that are specific to non-AWS providers) also applies to imported EKS. This would mean that we only add a few notes whenever something is not available or different on imported EKS.

We might be able to start with the first approach while the feature isn't matured yet and then switch to the latter.

Opinions welcome!

**Comment by puja108** [comment]
For now the goal/assumption is that indeed none of our cluster management should apply and checking what is in there right now that assumption holds.

**Comment by weatherhog** [comment]
@mproffitt what do you think? Shall we close this ?
