### ISSUE TITLE
EKS Adoption Spike

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#2891]
As a short few day spike we want to explore the possibility of a shortcut if a transition from imported to adopted cluster would "just work".

**Comment by mproffitt** [comment]
To define the scope of what constitutes an adopted cluster, the following tasks must be discovered

```[tasklist]
### Tasks
- [ ] How do we disengage crossplane from the cluster CRs
- [ ] What happens when the `clusters.x-k8s.io/managed-by` annotation is removed from CAPA CRs
- [ ] What happens when the restrictive R/O IAM policy applied to CAPA CRs is expanded to full R/W?
- [ ] What happens if we change the cluster scaling config on the CR
- [ ] What happens if we add / remove managed machine pools
- [ ] What happens if we change the instance size
- [ ] What happens if we delete the cluster CR
```
Is there anything else that needs to be added to this scope?

**Comment by puja108** [comment]
One use cases we could test would be updating the EKS CP to the next patch/minor version

**Comment by mproffitt** [comment]
Cluster created:

```bash
eksctl create cluster -n adopttest --tags owner=honeybadger,project=cluster-import,task=adoption-spike --with-oidc -t 'm5.large' -m 1 -M 3 --vpc-cidr 10.9.0.0/16 -p localsnail
```

**Comment by mproffitt** [comment]
Spike day one intensive

### How do we disengage crossplane

In the claim there are two fields available. The first is `cloudProviderConfigRef` - This must be set to the name of a Crossplane providerconfig carrying the WRITE role arn for the cluster adoption - The ProviderConfig name in the cluster is `aws-adopt`

The second field is `objectDeletionPolicy` and this must be set to `Orphan`. This must not be confused with `deletionPolicy` which by default is `Delete` - `objectDeletionPolicy` only applies to the CAPI objects created as part of the crossplane apply.

### What happens when the clusters.x-k8s.io/managed-by annotation is removed from CAPA CRs

At the moment this annotation is not having an effect but this would normally block the cluster from being taken over.

The first thing we see is the cluster moving through its status checks until it becomes fully ready, after which, `status.conditions` should read as:

```yaml
  - lastTransitionTime: "2023-11-09T13:20:42Z"
    status: "True"
    type: Ready
  - lastTransitionTime: "2023-11-09T13:20:39Z"
    status: "True"
    type: ClusterSecurityGroupsReady
  - lastTransitionTime: "2023-11-09T13:20:40Z"
    status: "True"
    type: EKSAddonsConfigured
  - lastTransitionTime: "2023-11-09T13:20:40Z"
    status: "True"
    type: EKSControlPlaneReady
  - lastTransitionTime: "2023-11-09T13:20:40Z"
    status: "True"
    type: EKSIdentityProviderConfigured
  - lastTransitionTime: "2023-11-09T13:20:42Z"
    status: "True"
    type: IAMAuthenticatorConfigured
  - lastTransitionTime: "2023-11-09T13:20:40Z"
    status: "True"
    type: IAMControlPlaneRolesReady
  - lastTransitionTime: "2023-11-09T13:20:39Z"
    status: "True"
    type: SubnetsReady
  - lastTransitionTime: "2023-11-09T13:20:39Z"
    status: "True"
    type: VpcReady
```

General preconditions to this are:

- everything needs to be tagged correctly with `kubernetes.io/cluster/CLUSTER_NAME` set to one of `owned` or `shared` depending on the resource
- There will be a new "adoption" IAM role & policy to deploy. This is slightly more extensive than the one used by CAPI for EKS but is largely an amalgamation of that + the read-only import policy
- Because we'll change roles, the new role must be injected into the `aws-auth` configmap as:

  ```yaml
    - groups:
      - system:masters
      rolearn: arn:aws:iam::242036376510:role/eks-adoption-crossplane-role
      username: <CLUSTER_NAME>
  ```
  Without this, the cluster will lose access
- It takes a while to adopt and once started, the process cannot be interrupted. Mostly we're waiting on kubernetes reconciliation

### What happens when the restrictive R/O IAM policy applied to CAPA CRs is expanded to full R/W?

- See above

### Next

Before I can continue with the remaining tasks there is an issue of tracing the correct AWS LaunchTemplate used to create the cluster. Once this is complete, I can verify the remaining tasks on this vein.

**Comment by mproffitt** [comment]
During testing today it became necessary to delete an `AWSManagedMachinepool` resource in order to change the name on the CR. This correctly caused CAPA to delete the related nodegroup from AWS. 

Delete is possible from the adoption path.

**Comment by mproffitt** [comment]
This cluster started life as 1.27 - updating the version in the `AWSManagedControlPlane` started the ugprade to 1.28

```yaml
region: eu-central-1
roleName: eksctl-adopttest-cluster-ServiceRole-v1SNaitx3Wep
tokenMethod: iam-authenticator
version: "1.28"
vpcCni:
  disable: false
```

![image](https://github.com/giantswarm/roadmap/assets/1852919/fde4969a-7ca5-4f83-9eef-3f8ec8a5a7bb)

Setting deletion policy `Orphan` on the kubernetes provider objects allows the XR to be cleaned up with the claim however the objects are left behind.

As these are no longer controlled by an XR object, they should never reconcile and can be considered harmless. Whilst it would be nice if crossplane could clean these up, I think may be a price worth paying.

```nohighlight
adopttest-awsclusterroleidentity             AWSClusterRoleIdentity   kubernetes-provider   True     True    21m
adopttest-awsmanagedcluster                  AWSManagedCluster        kubernetes-provider   True     True    21m
adopttest-awsmanagedcontrolplane             AWSManagedControlPlane   kubernetes-provider   True     True    21m
adopttest-awsmanagedmachinepool-ng-12345     AWSManagedMachinePool    kubernetes-provider   True     True    20m
adopttest-cluster                            Cluster                  kubernetes-provider   True     True    21m
adopttest-machinepool-ng-12345               MachinePool              kubernetes-provider   True     True    20m
```

### Scaling Single nodepool

Changing the number of replicas in the Machinepool quite happily moved the cluster from 1 to 3 replicas
 
![image](https://github.com/giantswarm/roadmap/assets/1852919/1ca032e7-fa59-4416-a67c-691a5d17b007)

Moving this back to 2 replicas mirrored this into the console

![image](https://github.com/giantswarm/roadmap/assets/1852919/c00f2aec-f595-40e2-a730-fee0ebe65576)

and terminated the node.
![image](https://github.com/giantswarm/roadmap/assets/1852919/6063213b-802a-407e-bd69-4ac612ffea4f)

### Adding and deleting nodepools

Adding a new nodepool required an additional permission `iam:ListAttachedRolePolicies` but then brought the nodepool online

![image](https://github.com/giantswarm/roadmap/assets/1852919/f03de400-0a37-4229-b46f-4fb0890b240d)

The machines were named funny but I guess that was me...
![image](https://github.com/giantswarm/roadmap/assets/1852919/cbe27236-99f3-4b32-986c-747f0a4d95f1)

I did not see these nodes join the cluster - either I've not left this long enough or it's because I didn't specify anything for the bootstrap. I also re-used a launch template from the primary nodepool and this may have been a factor.

### Instance size

You cannot change the instance size when a launch template is used. Attempting to do so will add the following error to the status of the `AWSManagedMachinePool` object:

```nohighlight
      failed to reconcile nodegroup version: failed to update EKS nodegroup: InvalidParameterException: You must specify the same launch template that the nodegroup was created with.
      {
        RespMetadata: {
          StatusCode: 400,
          RequestID: "4f205e69-8e16-421a-b24e-202770c6da80"
        },
        Message_: "You must specify the same launch template that the nodegroup was created with."
      }
```

### Overall

We have CAPA adoption from Crossplane. Additional testing around nodepool creation / deletion will be helpful but not showstopping. I am fairly certain that the failure I saw here was related to how I applied the new nodepool.

### Summary:

- :sunny: Crossplane disengage
- :sunny: Upgrades
- :sunny: Nodepool scaling
- :partly_sunny: Multiple nodepools
- :sunny: Deletion
- :partly_sunny: instance size - This should work without a launch template as per CAPA EKS
