### ISSUE TITLE
Fleet management UX

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#2892]
In the context of Cluster Import, but also in general we want to re-evaluate what a focus on Fleet Management means for our UI. Currently, fleet management is mainly covered by GitOps and our tooling and templates as well as best-practices around that. Our UI, however, does not reflect that.
After some discovery and use case gathering we want to choose a use case (or a few) that we will then implement to improve the user experience of our Fleet Management offering.
```[tasklist]
### Tasks
- [ ] Gather fleet management use cases
- [ ] Group and prioritize use cases
- [ ] Implement first use case(s
- [ ] https://github.com/giantswarm/roadmap/issues/3519
```

**Comment by puja108** [comment]
cc @marians

**Comment by marians** [comment]
We had a conversation about use cases in SIG UX last week. I have tried to prevent any questioning of the term/concept "fleet", and just wanted us to collect examples for "things I want to do for multiple clusters at once".

It turns out that it's not easy to avoid any assumptions regarding what makes up a fleet. Here is a collection of the assumptions that leaked into the use cases we collected, plus some other definition I just com up with for the sake of argument.

- a fleet is defined by some common selection criteria, e. g. all clusters that match a label or a combination of labels
- a fleet defines an environment stage, e. g. "development" vs. "production"
- a fleet is a group of clusters I someone created and put a name/identifier on
- a fleet is all the clusters owned by a certain group
- a fleet is all the clusters we have / all the cluster I can see
- a fleet is just several clusters which I select ad-hoc, item by item, for a certain task

I'm certain that it will be beneficial to narrow down the fleet concept we aim for.

**Comment by puja108** [comment]
Forgot to summarise what we talked about.

The general Fleet Management story and its understanding of "fleet" is about the whole fleet of clusters a customer owns. This can be multi-provider and multi-region. There's use cases of governance (mainly overviews) that are on that level, e.g. getting an overview over all your clusters and the version they are on, as well as if there's updates for them.

However, in many actions / active use cases, the user might rather want to work with sub-groups of such a fleet, e.g. upgrades of clusters will usually be rolled out in stages, so to a stage-related group.
Defining such groups can only be flexible as it will be very different per customer, but even different between use cases of a single customer.

That said, in an ideal solution for some use cases (not all of them) the two levels could be inter-connected, e.g. define a staged rollout that automatically rolls through the stages until the whole company-wide fleet is upgraded.

**Comment by marians** [comment]
For reference: The SIG UX user story gathering notes are in [this Miro board](https://miro.com/app/board/uXjVNXZcNCg=)

**Comment by puja108** [comment]
Hmm, I think we need to consider this when thinking about replacing current Happa functionality with Backstage things. Our new UI should be more focused on Fleet management than single-cluster or single-app focused.

**Comment by marians** [comment]
The title change for this issue to "Platform Portal" puzzles me

**Comment by teemow** [comment]
My first intention was to rewrite this issue to roll out backstage. But there is already another issue: https://github.com/giantswarm/giantswarm/issues/31704

**Comment by teemow** [comment]
@weatherhog we still have this in our backlog in planeteers. Question came up if you already have issues in honey badger that would replace this issue?

**Comment by weatherhog** [comment]
we have this https://github.com/giantswarm/roadmap/issues/3519 umbrella issue for cluster creation in Backstage but nothin more at the moment. We could expand cluster creation to cluster management.

**Comment by teemow** [comment]
@weatherhog yes I think the goal here was more to think about what would make it easier to manage more than one cluster not just a plain CRUD for clusters.

**Comment by weatherhog** [comment]
@marians lets take this tour our next Backstage sync

**Comment by teemow** [comment]
For the headlamp spikes - a list of hopefully useful links:

 * https://headlamp.dev/
 * https://artifacthub.io/packages/helm/headlamp/headlamp
 * https://github.com/headlamp-k8s/plugins?tab=readme-ov-file#current-plugins
 * https://github.com/headlamp-k8s/plugins/tree/main/flux#installing-the-flux-headlamp-plugin-in-a-headlamp-deployment
 * https://github.com/headlamp-k8s/backstage-plugin

**Comment by marians** [comment]
Yesterday in a discussion, some relevant use cases came up:

- As a cluster admin, I want to apply some re-usable configuration module (a GitOps base) to one ore several workload clusters.
- As a cluster admin, I want to have an overview which workload clusters make use of which bases

Probably, removing a base from a cluster's config would also be a valid thing to do. WDYT @mproffitt ?

**Comment by mproffitt** [comment]
That's actually an interesting question - Removing the base wasn't something I'd considered but I think having the capability of removing a given resource from one or more clusters as a single PR would be ideal.

I'd be hesitant to target the base directly unless you could be absolutely sure that base was unused across the fleet as this would result in broken deployments, however it brings to mind another feature of a potentially listing available GitOps bases, and maybe having a usage count for each base. Bases could then be removable if and only if the usage count is 0.

**Comment by puja108** [comment]
I would move this into Q1 for now, depending also on what we discuss wrt roadmap on today's call cc @teemow

**Comment by marians** [comment]
FYI: removed the `Choose implementation (i.e. backstage vs Happa)` task

**Comment by weatherhog** [comment]
@marians I think we should revisit this issue

**Comment by marians** [comment]
Moved to Bumblebee
