### ISSUE TITLE
configure a new instance of retagger to replicate public images to the new ACR registry

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2895]
```[tasklist]
### Tasks
- [ ] review the current retagger/skopeo lists for images copied *from* our other public registries
- [ ] https://github.com/giantswarm/roadmap/issues/2913
- [ ] https://github.com/giantswarm/roadmap/issues/2917
- [ ] https://github.com/giantswarm/roadmap/issues/2918
- [ ] https://github.com/giantswarm/roadmap/issues/2919
- [ ] https://github.com/giantswarm/roadmap/issues/2920
- [ ] https://github.com/giantswarm/roadmap/issues/2921
- [ ] https://github.com/giantswarm/roadmap/issues/2922
- [ ] https://github.com/giantswarm/roadmap/issues/2923
- [ ] https://github.com/giantswarm/roadmap/issues/2912
- [ ] https://github.com/giantswarm/roadmap/issues/2969
```

**Comment by QuentinBisson** [comment]
This will not cover everything but it should help teams https://github.com/giantswarm/prometheus-rules/pull/959
