### ISSUE TITLE
Managed Linkerd

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#290]
1. Current customers know w/o ambiguity they can use a Managed Linkerd from us. Those who want to use get the support they need in order to start using it.

- [ ] Responsible person create separate issue
- [ ] Ping every SE re: interested customers
- [ ] Work w them and customer to use

2. Prepare Linkerd for 'productive use'

- [ ] Discuss and link what goes here
- [ ] Docs about mTLS https://github.com/giantswarm/giantswarm/issues/16741

3. Sales enablement.

- [ ] Responsible person create separate issue
- [ ] Talk to Franz if doing the same as Loki would be valuable, how to adjust

4. Partnership

- [x] @cokiengchiara reach out to Linkerd for technical partnership. Outcome: [Linkerd doc](https://docs.google.com/document/d/1O9AhHPu0IOpEeRmQIpHuDOyYOV3ACJsbf6cxsR8Rv34/edit). tl;dr Just join Linkerd Slack - they are happy to answer our questions and requests with priority
- [x] Julia reach out to Linkerd for business partnership (Catherine Paganini) - notes in same doc.

This is an iteration of https://github.com/giantswarm/roadmap/issues/271

**Comment by cokiengchiara** [comment]
Released: https://github.com/giantswarm/linkerd2-app/#linkerd2-app-chart

**Comment by cokiengchiara** [comment]
Will be announced on Friday announcement this week.
