### ISSUE TITLE
Transfer images from old registries to gsoci.azurecr.io

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2912]
The new Giant Swarm registry is empty for the moment. The goal is to populate it. Old registries contain a great number of non-release tags (testing and development) and historical releases (going back to the beginning of GS). It would be smart to move only relevant images - production releases being used today.

## TODO
- [x] Compile a list of images in use today based on [the container image aggregation in Cortex](https://giantswarm.grafana.net/explore?panes=%7B%22-6v%22:%7B%22datasource%22:%22000000006%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22count%28aggregation:container:images%29%20by%20%28image%29%22,%22range%22:true,%22instant%22:true,%22datasource%22:%7B%22type%22:%22prometheus%22,%22uid%22:%22000000006%22%7D,%22editorMode%22:%22code%22,%22legendFormat%22:%22__auto%22%7D%5D,%22range%22:%7B%22from%22:%22now-15m%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)
- [x] Filter out potential dev/test tags present
- [x] Build a `skopeo` input file, using `>={LOWEST_TAG_FOUND}` semver rules
- [x] Run `skopeo` in a Job in `gorilla/rfjh2` using the file
- [x] Add a note in `WorkloadClusterAppFailed/NotDeployed` with:
    - How to log in to ACR (credentials in LastPass)
    - `skopeo` command to quickly copy missing image
