### ISSUE TITLE
AWS vintage migration to CAPA implementation (Phase 2)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#2914]
```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2911
- [ ] https://github.com/giantswarm/roadmap/issues/2705
- [ ] https://github.com/giantswarm/giantswarm/issues/28559
- [ ] https://github.com/giantswarm/giantswarm/issues/28560
- [ ] https://github.com/giantswarm/giantswarm/issues/28561
```

**Comment by alex-dabija** [comment]
> Can this be closed now [@alex-dabija](https://github.com/alex-dabija) ?

Yes, very old issue.
