### ISSUE TITLE
reconfigure all the CI/CD pipelines to push new builds to the new repository

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#2915]
Currently, apps are mostly configured to use `push-to-docker` `architect-orb` action to upload their image from CI/CD to a registry ([example](https://github.com/giantswarm/app-operator/blob/6dff02d96c57885f4fe24c479f67ab1c0eaf6f15/.circleci/config.yml#L16)).

This means that every app has individual knowledge about where to upload its images. This seems wrong.
We should update `architect-orb` to have the configuration of registries in the orb and to make it independent of app's config. App should just `upload-to-registry` and `architect-orb` knows itself what it means. That way we can reconfigure (in the future) the used registry with a single `architect` release.

Still, when `architect` changes are done, we still have to reconfigure all the repos to use the new build action and remove the old ones.

We can also start singing these images with `cosign`

```[tasklist]
### Tasks
- [x] do architect-orb changes
- [x] write a `config.yml` conversion tool
- [x] send announcement about incoming changes
- [x] run the conversion tool
- [x] Q: do we need to handle dev-stage builds differently and upload only to some catalogs?
- [x] check the PR acceptance ratio
- [x] for projects that don't accept the PR: change the PR to directly use `push-to-docker` with `gsoci`
```

**Comment by marians** [comment]
As far as I can tell we are done here.
