### ISSUE TITLE
Investigate Machine Pool Autoscaling App Compatibility

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#2927]
### Motivation
We need the autoscaling app for machine pool autoscaling on capa. Issue here is, that the autoscaling for machine pools is only available in >1.27.x version Autoscaling app dependent on k8s verison 1.27.x

### Todo

- [x] Test if the 1.27 autoscaling app is working with our current Kubernetes 1.24.x Version
- [ ] If it is not possible find out what we need to change to backport the app to 1.24.x

### Outcome
- We know that the autoscaling app is working on 1.24 or what we need to change.

**Comment by njuettner** [comment]
## IAM for cluster-autoscaler

In Vintage we use the IAM instance profile of master nodes for IAM permissions for cluster-autscaler, CAPA is more or less the same.

We need to check if the following IAM permissions are present in `https://github.com/giantswarm/capa-iam-operator/blob/master/pkg/iam/control_plane_template.go`:

```json
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "autoscaling:DescribeAutoScalingGroups",
        "autoscaling:DescribeAutoScalingInstances",
        "autoscaling:DescribeLaunchConfigurations",
        "autoscaling:DescribeTags",
        "ec2:DescribeInstanceTypes",
        "ec2:DescribeLaunchTemplateVersions"
      ],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": [
        "autoscaling:SetDesiredCapacity",
        "autoscaling:TerminateInstanceInAutoScalingGroup"
      ],
      "Resource": ["*"]
    }
  ]
}
```

- [ ] Adjust IAM settings for cluster-autoscaler if neccessary

## Cluster Autoscaler Settings

For CAPI we need to set `--cloud-provider=clusterapi` 

Which we have to transform in `_helper.tpl`:

```
{{- define "cloud-provider" -}}
{{- if eq .Values.provider "gcp" -}}
gce
{{- else if .Values.provider "capa" -}}
cluster-api
{{- else -}}
{{ .Values.provider }}
{{- end -}}
{{- end -}}
{{- end -}}
```


In order to allow cluster-autoscaler finding the right ASG's for Cluster MachinePools we use auto discovery via tags, we need to adjust it a bit because it differs from Vintage:


Example ASG: 
![Image](https://github.com/giantswarm/roadmap/assets/1936982/e07d5d7a-c263-44c3-ba74-d91d30259cb6)



- [ ] Check cloud provider (capa) to change `--node-group-auto-discovery` field
    - [ ] Use `sigs.k8s.io/cluster-api-provider-aws/cluster/{{ Values.clusterid }}` to discover MachinePool ASGs

## MachinePool Changes

MachinePool CR's need to have a annotation to let CAPA controller know it should not scale because it is externally managed (cluster-autoscaler, Karpenter, ...)

`cluster.x-k8s.io/replicas-managed-by: "external-autoscaler"`

**Comment by njuettner** [comment]
I added an overview how scaling works with cluster-autoscaler for MachinePools in Miro: https://miro.com/app/board/uXjVNTY0TTs

<img width="956" alt="image" src="https://github.com/giantswarm/roadmap/assets/1936982/c2ddee5f-c4ba-470f-8ee3-4dfd9fe7bfef">

**Comment by njuettner** [comment]
By using cluster-aws v0.47.0 and default-apps-aws v0.36.0 we do use cluster-autoscaler for CAPA MachinePools
