### ISSUE TITLE
Setup logging on CAPZ installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2942]
Towards: https://github.com/giantswarm/roadmap/issues/311

In order to expand our logging infrastructure coverage we should extend support to CAPZ installations.

As for object storage Loki does support Azure blob storage.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2967
- [x] Configure Loki to use Azure object storage
- [x] Deploy logging on CAPZ installations
- [x] Enable logging on giantswarm CAPZ installations
- [ ] Enable logging on customer CAPZ installations
```

**Comment by hervenicol** [comment]
:green_circle:  Loki config should be ready (https://github.com/giantswarm/config/pull/2114)
:green_circle:  it has been tested with a dev version of object-storage-operator (https://github.com/giantswarm/object-storage-operator/pull/46)
:orange_circle: unfortunately we don't receive promtail logs, looks like it can't resolve the ingress address

**Comment by marieroque** [comment]
Logging enabled on CAPZ giantswarm testing installations only: 
- `gaggle`: actually disabled because not enough resources
- `glippy` ✅ 
- `goose`: impossible to log into (ephemeral installation!?!)

**Comment by marieroque** [comment]
To have a `grafana-agent` working well on CAPZ WC, we need to edit the daemon set and change the `listen-port` from 80 to 8080.
That issue is fixed here

**Comment by QuentinBisson** [comment]
Is it now fixed @marieroque ? Do we have logging on capz?

**Comment by QuentinBisson** [comment]
https://gigantic.slack.com/archives/C01176DKNP4/p1704804603915389 Might be worth checking

**Comment by marieroque** [comment]
✅ Tested on a WC on glippy


![Image](https://github.com/giantswarm/roadmap/assets/9134338/853557d1-304d-4080-9783-ea31ba96b48c)

**Comment by marieroque** [comment]
Discussion about CAPZ upgrade: https://gigantic.slack.com/archives/C02HLSDH3DZ/p1705400551622879

**Comment by QuentinBisson** [comment]
Putting it back to backlog

**Comment by QuentinBisson** [comment]
All capz MCs run 1.25, let's proceed

**Comment by QuentinBisson** [comment]
Logging is enabled on capz
