### ISSUE TITLE
Setup logging on CAPVCD installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2944]
Towards: https://github.com/giantswarm/roadmap/issues/311

In order to expand our logging infrastructure coverage we should extend support to CAPVCD installations.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/telekom-panamax/issues/281
- [ ] https://github.com/giantswarm/giantswarm/issues/29177
- [ ] https://github.com/giantswarm/roadmap/issues/3189
- [ ] https://github.com/giantswarm/giantswarm/issues/29959
- [ ] https://github.com/giantswarm/giantswarm/issues/29385
- [ ] https://github.com/giantswarm/roadmap/issues/3166
- [x] Enable Loki on Leopard
- [ ] https://github.com/giantswarm/roadmap/issues/3010
```

**Comment by QuentinBisson** [comment]
Promtail is currently having issues on CAPVCD https://github.com/giantswarm/giantswarm/issues/29385

**Comment by QuentinBisson** [comment]
We can access object storage with loki configured https://github.com/giantswarm/panamax-configs/tree/main/installations/leopard/apps/loki.

It looks like they are using minio as the minio style configuration we have defined https://github.com/giantswarm/loki-app/blob/869e6f207d75e737745320157b6b6d895ee4c3e3/sample_configs/values-eks-testing.yaml#L24 does the trick.

Now we are waiting for the bucket to be created by our customers

**Comment by QuentinBisson** [comment]
Loki is running fine on leopard, closing
