### ISSUE TITLE
Setup logging on AWS installations

### ISSUE THREAD

**Issue by TheoBrigitte** [giantswarm/roadmap#2952]
### User story

* As a user with access to Grafana I want to be able to access logs for any AWS management cluster.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/23432
- [ ] https://github.com/giantswarm/giantswarm/issues/26035
- [ ] https://github.com/giantswarm/roadmap/issues/2554
- [ ] https://github.com/giantswarm/roadmap/issues/1839
- [ ] https://github.com/giantswarm/roadmap/issues/1849
- [ ] https://github.com/giantswarm/giantswarm/issues/24118
- [ ] https://github.com/giantswarm/roadmap/issues/2182
- [ ] https://github.com/giantswarm/roadmap/issues/1903
- [ ] https://github.com/giantswarm/roadmap/issues/2054
- [ ] https://github.com/giantswarm/roadmap/issues/2150
- [ ] https://github.com/giantswarm/giantswarm/issues/27146
- [ ] https://github.com/giantswarm/roadmap/issues/2639
- [ ] https://github.com/giantswarm/giantswarm/issues/26964
- [ ] https://github.com/giantswarm/roadmap/issues/1840
```
