### ISSUE TITLE
Automated testing of CAPI workload clusters

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#298]
## User Story

- As a Giant Swarm Engineer I want to run tests on Workload Clusters provisioned by upstream Cluster API (CAPI) controllers so that I can ensure our future CAPI releases are working correctly.

## Details, Background

We are currently using automated tests to ensure reliability and functionality of Giant Swarm Workload Cluster releases. We aim to enable the same testing functionality for clusters created through upstream CAPI controllers, so we can continue using our tooling for testing and releasing vanilla CAPI releases.

This is essential for upcoming stories to make CAPI clusters as reliable (and [repeatable](https://github.com/giantswarm/roadmap/issues/299)) as our current production setups as well as [align with current defaults](https://github.com/giantswarm/roadmap/issues/300) that our customers are used to get out of the box.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/2055
- [ ] https://github.com/giantswarm/roadmap/issues/2067
- [ ] https://github.com/giantswarm/roadmap/issues/2078
- [ ] https://github.com/giantswarm/roadmap/issues/2080
- [ ] https://github.com/giantswarm/roadmap/issues/2081
- [ ] https://github.com/giantswarm/giantswarm/issues/26378
- [ ] https://github.com/giantswarm/roadmap/issues/2679
- [ ] https://github.com/giantswarm/roadmap/issues/2623
- [ ] https://github.com/giantswarm/roadmap/issues/2767
```

**Comment by gawertm** [comment]
topic for new Releng Team in Kaas. Will still keep in backlog to track and see what we can already do until then

**Comment by gawertm** [comment]
@puja108 In regards to automation we agreed on these next steps for Rockets and the current mc-bootstrap epic. Having it for all providers with basic smoke tests, is already a huge improvement. Other Follow-ups (e.g. the automatic workload cluster testing) I consider out of scope for Rocket. So I would also unassign Rocket from this Issue here. Do you agree?

**Comment by teemow** [comment]
A higher level brainstorming of release engineering is here atm: https://github.com/giantswarm/giantswarm/issues/24704

**Comment by JosephSalisbury** [comment]
@yulianedyalkova do you know what's left here? the todo list in the description looks done done

**Comment by yulianedyalkova** [comment]
@JosephSalisbury I somehow missed your ping, sorry!

We have the basic functionality in place (incl. framework and tests), there will be more follow-up stories to fix and expand the features but they can be separate from the epic so closing.
