### ISSUE TITLE
Install teleport-kube-agent-app on CAPA MCs

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#3004]
## Motivation

Kubernetes API access for CAPA MCs via Teleport - [teleport-kube-agent-app](https://github.com/giantswarm/teleport-kube-agent-app).

## MCs

- [x] anzu
- [x] gazelle
- [x] goat
- [x] golem
- [ ] goten (ephemeral)
- [x] grizzly
- [x] snail
- [x] velvet

```[tasklist]
### Tasks
- [x] Deploy and test app on all MCs
- [x] Intranet access document
- [x] Annoucement to the team on how to access
```
