### ISSUE TITLE
Turtles Feature Parity of CAPA with Vintage

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3007]
### Motivation
In order to not break expectations of our customers in their migration from vintage to capi we have to make sure that all of the features in vintage are also available in capi. Especially in CAPA for this we have to work on some features to reach feature parity with vintage on aws. 

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2977
- [ ] https://github.com/giantswarm/roadmap/issues/3002
- [ ] https://github.com/giantswarm/roadmap/issues/3003
- [ ] https://github.com/giantswarm/giantswarm/issues/27441
- [ ] https://github.com/giantswarm/giantswarm/issues/29347
- [ ] https://github.com/giantswarm/giantswarm/issues/27954
``` 

### Outcome
- We have reached feature parity with vintage on capa regarding the components managed by turtles
