### ISSUE TITLE
CAPA in China

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3012]
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/29322
- [ ] https://github.com/giantswarm/roadmap/issues/3251
- [ ] https://github.com/giantswarm/roadmap/issues/3252
- [ ] https://github.com/giantswarm/roadmap/issues/3253
- [ ] https://github.com/giantswarm/roadmap/issues/3254
- [ ] https://github.com/giantswarm/roadmap/issues/3255
- [ ] https://github.com/giantswarm/roadmap/issues/3256
- [ ] https://github.com/giantswarm/roadmap/issues/3257
- [ ] https://github.com/giantswarm/roadmap/issues/3481
- [ ] https://github.com/giantswarm/roadmap/issues/3482
- [ ] https://github.com/giantswarm/roadmap/issues/3480
```
## Links
- [CAPA China Spike results](https://github.com/giantswarm/giantswarm/issues/29322#issuecomment-1926776372).
