### ISSUE TITLE
circleci config change prs

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3023]
also to check here https://gigantic.slack.com/archives/C04TGHDEF/p1701696574042449?thread_ts=1701170353.580999&cid=C04TGHDEF
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/rbac-operator/pull/513
- [ ] https://github.com/giantswarm/teleport-operator/pull/43
- [ ] https://github.com/giantswarm/organization-operator/pull/351
- [ ] https://github.com/giantswarm/dex-app/pull/311
- [ ] https://github.com/giantswarm/athena/pull/295
- [ ] https://github.com/giantswarm/api/pull/1458
- [ ] https://github.com/giantswarm/api/pull/1459
```
