### ISSUE TITLE
Move ops recipes into handbook

### ISSUE THREAD

**Issue by pipo02mix** [giantswarm/roadmap#3024]
## User Story

- As an operation engineer, I would like to find the debugging information in a public site where search engines (like our AI bot) can access and offer quick results when trying to find solutions during an incident

## Acceptance Criteria

- [ ] The content published does not contain any sensible data
- [ ] Ops recipes are curated so only meaningful information is displayed

## Tasks

- [ ] Create a PR in intranet repo with the `confidentiality: public` added in the frontmatter and ask for approval for SIG security and ISMS owner
- [ ] When approved create a PR in handbook with the content curated and ping sig-opsprocesses and sig docs
- [ ] When the latter PR is merged, create new PR in intranet removing the content from recipe and adding a link to handbook new recipe
