### ISSUE TITLE
Update the docs about newly created registries and their features

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3027]
```[tasklist]
### Tasks
- [x] Copy and paste the architecture from RFC, update it.
- [x] Describe setup of the public registry: enabled options, authentication modes.
- [x] Describe setup of the private registry
  - [ ] Where is it and what's the name and URL.
  - [ ] How to generate access keys.
  - [ ] Security: how to distribute private image in case it's rapidly needed
```

**Comment by marians** [comment]
Some notes after I worked on the docs:

- Access to Aliyun private images is currently unclear (not documented)
- Unclear whether private images should be accessed from Docker Hub or Quay. It's possible, but I guess it's not desired.
- For ACR credentials (scope map plus token), a naming convention seems to be a must-have. Otherwise it will become impossible to track ownership and clean up.
- For creating ACR image pull secrets, I think that the CLI method is far superior to the GUI method. We should only document that one, especially to enforce a naming convention.

**Comment by marians** [comment]
We merged our intranet PRs and have these pages updated now:

- https://intranet.giantswarm.io/docs/product/architecture-specs-adrs/specs/registries/
- https://intranet.giantswarm.io/docs/dev-and-releng/container-registry/

**Comment by piontec** [comment]
done
