### ISSUE TITLE
CAPZ Teleport for SSH & cluster access

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#3036]
Replace the Giant Swarm VPN with Teleport for SSH and Kubernetes API access to CAPZ clusters.

```[tasklist]
### Tasks
- [x] Enable teleport by default on cluster-azure
- [x] cluster-azure `v0.0.32` released with teleport support
- [x] Upgrade default-apps-azure for all MCs for K8s API access
- [x] Upgrade cluster-azure for all MCs for SSH access
```
```[tasklist]
### MCs
- [x] gaggle (GS - stable-testing)
- [x] glippy (GS - testing)
- [x] wombat (WEPA - testing)
- [x] cuckoo (Continental - testing)
```

**Comment by tuladhar** [comment]
Cluster access for `gaggle` now works, other MC will be upgraded while upgrading to 1.25 by Erkan.

**Comment by tuladhar** [comment]
Since, v1.25 is still blocked due to [flux PSP/PSS](https://gigantic.slack.com/archives/C01F7T2MNRL/p1704793620724459), we're moving ahead with v1.24.17 as part of cluster-azure v0.0.32.

**Comment by tuladhar** [comment]
Done for `gaggle` and `glippy`. Asked Phoenix for approval if we should continue `wombat` and `cuckcoo` upgrade.
