### ISSUE TITLE
Implementing Phase 1, part 3/5: Use cluster chart in cluster-aws and remove Cluster API resource from cluster-aws

### ISSUE THREAD

**Issue by njuettner** [giantswarm/roadmap#3047]
### Motivation

Coming from https://github.com/giantswarm/roadmap/issues/2739.

We have ported all provider-independent Cluster API resources to `cluster` chart, which was phase 1 of restructuring of cluster-<provider> apps, see https://github.com/giantswarm/roadmap/issues/2742 for more details.

We have also refactored `cluster-aws` Helm values, so that `cluster` chart can read provider-independent values it needs. Here we have to move current top-level properties to be under `Values.global`.

Now we want to use `cluster` chart in `cluster-aws` and remove all provider-independent Cluster API resources from `cluster-aws`.

### Todo

Fix issues and implement changes that were recently made in cluster-aws (changes made after cluster chart was initially written and updated last time). Most of the changes are in [this PR](https://github.com/giantswarm/cluster/pull/43/files):

```[tasklist]
- [x] Fix cluster chart Helm values schema and add missing Helm values so that Cluster resource can be rendered for CAPA https://github.com/giantswarm/cluster/pull/29
- [x] Add CHANGELOG in cluster chart https://github.com/giantswarm/cluster/pull/35
- [x] Release cluster chart v0.1.0 https://github.com/giantswarm/cluster/pull/36
- [ ] https://github.com/giantswarm/cluster/pull/37
- [x] Enable using cgroupv1
- [x] Support longer node pool names and allow dashes
- [x] Use KubeletConfiguration file instead of a bash script
- [x] Update kubernetes version to v1.24.16
- [x] Update Teleport version to 14.1.3 and enable it by default
- [x] Add systemd unit for OS hardening (ported from cluster-aws)
- [x] Add systemd units for preventing in-place Flatcar OS updates (ported from cluster-aws)
- [x] Add systemd unit for configuring kubeadm service (ported from cluster-aws)
- [x] Add systemd unit for configuring containerd service (ported from cluster-aws)
- [x] Add systemd unit for configuring audit-rules service (ported from cluster-aws)
- [x] Add missing kubelet configuration to align it with vintage config (ported from https://github.com/giantswarm/cluster-aws/pull/468)
- [x] Add /var/lib/kubelet as a default directory on all nodes
- [x] Add missing API server service-cluster-ip-range CLI argument
- [x] Change JSON schema for systemd unit contents from string to object with explicitly defined fields
- [x] Add missing API server extra volumes
- [x] Render all SSH config conditionally behind a bastion flag
- [x] Fixed rendering of timesyncd configuration
```

Use cluster chart in cluster-aws:

```[tasklist]
- [x] https://github.com/giantswarm/cluster-aws/pull/460
- [x] https://github.com/giantswarm/cluster-aws/pull/479
- [ ] https://github.com/giantswarm/cluster-aws/pull/497
```

schemalint fixes and new releases that we need for all above changes in cluster and cluster-aws:

```[tasklist]
- [x] https://github.com/giantswarm/schemalint/pull/137
- [x] https://github.com/giantswarm/schemalint/pull/138
- [x] https://github.com/giantswarm/schemalint/pull/140
- [x] https://github.com/giantswarm/schemalint/pull/141
```

### Outcome

- cluster-aws is restructured and it is using provider-independent cluster chart
- Team Turtles can finally properly own our team topics for CAPA, like Kubernetes and other provider-independent topics like etcd, containerd, and almost everything else configured via kubeadm in CAPI
- Team Turtles will also probably partly own provider-independent topics for AWS vintage migration (as part of the work involve cluster chart)
- cluster chart is being used, it's tested more, more polished, documented, and we can a lot more easily start using it in other providers
