### ISSUE TITLE
teleport-kube-agent-app should be evictable by cluster-autoscaler in order to scale down nodes

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3061]
```
cluster-autoscaler 2023-12-21T12:53:50.957115967+01:00 I1221 11:53:50.957076       1 cluster.go:164] node ip-10-0-66-124.eu-west-2.compute.internal cannot be removed: non-daemonset, non-mirrored, non-pdb-assigned kube-system pod present: teleport-kube-agent-0
```
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/teleport-kube-agent-app/pull/30
- [x] Test and release v0.7.0
- [x] Report back to Phoenix and apply the fix
```

**Comment by tuladhar** [comment]
### Problem
By default, `kube-system` pods prevent cluster-autoscaler from removing nodes unless:
- A. Pod has annotation `cluster-autoscaler.kubernetes.io/safe-to-evict: "true"` 
- B. Pod has PDB
