### ISSUE TITLE
Single OCI registry: Stage 2 - registry cache

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3065]
## Related epics
- Stage 1: #2882 
- Stage 3: https://github.com/giantswarm/roadmap/issues/3411
- Retagger changes: https://github.com/giantswarm/roadmap/issues/3068

## Tasks
After research and evaluation, we decided to implement per-MC OCI registry cache that will be based on the https://github.com/project-zot/zot
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3066
- [ ] https://github.com/giantswarm/roadmap/issues/3067
- [ ] https://github.com/giantswarm/roadmap/issues/3068
- [ ] https://github.com/giantswarm/roadmap/issues/3069
- [ ] https://github.com/giantswarm/roadmap/issues/3070
- [ ] https://github.com/giantswarm/roadmap/issues/3071
- [ ] https://github.com/giantswarm/roadmap/issues/3116
- [ ] https://github.com/giantswarm/roadmap/issues/3369
- [ ] https://github.com/giantswarm/roadmap/issues/3370
- [ ] https://github.com/giantswarm/roadmap/issues/3436
- [ ] https://github.com/giantswarm/giantswarm/issues/30596
- [ ] https://github.com/giantswarm/roadmap/issues/3460
```

**Comment by weatherhog** [comment]
@piontec does this issue still needs to be watched or can it be closed if there is no way forward?

**Comment by piontec** [comment]
All tasks completed, closing
