### ISSUE TITLE
Do PoC test of some of `zot`'s properties

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3067]
We have to check how `zot` behaves in the following cases

```[tasklist]
### Tasks
- [x] Running out of disk space for cache data
- [x] disconnection/unavailability of the upstream cache - will it still serve from the local storage
- [x] moving a tag in upstream cache, like assigning `latest` to a newer image
```

**Comment by piontec** [comment]
Testing on zot 2.0.1 with the following config file
[config.json](https://github.com/giantswarm/roadmap/files/14085006/config.json)

**Comment by piontec** [comment]
## Test 1 - running out of disk space

- it has to have at least 1.5 GB to start and download trivy images (if scans are enabled)
- when it runs out of space during operation, starts returning errors and `containerd` is handling this properly and asking upstream

**Comment by piontec** [comment]
## Test 2 - zot going down

With the above containerd's config, the containerd runtime first tries cache, if it's not available, it hits upstream registry directly.

**Comment by piontec** [comment]
## Test 3 - multiarch

Caches all architectures it finds even if a single one is pulled

**Comment by piontec** [comment]
## Test 4 - cache works when upstream is unavailable

There are 2 subcases: when the replication is proactive (option `onDemand` is set to `false`, there's a set of images that are to be fetched and synchronized without waiting for any requests needing them) and pull through (`onDemand: true`).

### Proactive

When I tried to test it, I hit and reported [this bug](https://github.com/project-zot/zot/issues/2212). This won't work until the bug is fixed.

### Pull through

Tested, doesn't work.

**Comment by piontec** [comment]
## Test 5 - `zot` refreshes upstream tag when it's moved

According to devs:
> If the remote is down, it will serve the local image synced earlier, when the remote was up. with a slight overhead because of the http calls it makes to remote.

**Comment by piontec** [comment]
Yeah, I thought that too. Plot twist: I found no option to disable it :D

**Comment by piontec** [comment]
OK, I build and tested the current main branch - bugs I reported are fixed and everything seems to be working as expected!

**Comment by piontec** [comment]
OK, fixes should be included in the stable `2.0.2`, closing this one
