### ISSUE TITLE
CAPVCD Teleport for SSH & cluster access

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#3101]
Replace the Giant Swarm VPN with Teleport for SSH and Kubernetes API access to CAPVCD clusters.

MCs:
- leopard (panamax)
- gerbil (giantswarm)
- goshawk (ephemeral)

```[tasklist]
### Tasks
- [x] Upgrade default-apps-cloud-director MCs for K8s API access
- [ ] https://github.com/giantswarm/cluster-cloud-director/pull/218
- [x] Mention to use teleport for SSH https://intranet.giantswarm.io/docs/product/providers/capvcd/testing_infrastructure/
```

**Comment by tuladhar** [comment]
Discussed with Rocket, that Flatcar support for CAPVCD is still in the works.

**Comment by tuladhar** [comment]
## Teleport SSH works on Flatcar

![Screenshot 2024-04-04 at 11 31 32 PM](https://github.com/giantswarm/cluster-cloud-director/assets/5674762/55895727-3bd0-4584-9378-b76afe4e1d94)
