### ISSUE TITLE
PoC: Karpenter and Crossplane for managing IAM resources

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3102]
As discussed during sig-architecture, we would like to test deployment of Crossplane in one of our CAPA MCs (`golem`) in order to prove the presented concept. The concept includes enabling IAM, S3 and SQS in crossplane aws provider.

The availability of mentioned crossplane features will enable Phoenix to deploy Karpenter as an app-bundle that besides the actual app-required deployment will also include the needed IAM Roles to be deployed on the AWS provider.

If this proves to be successful over time, especially taking into account crossplane performance based on the number of CRDs, we will continue the journey of managing provider resources via crossplane. This apporach will allow us to couple the needed cloud provider resources with the actual apps, instead of managing e.g. IAM Roles in a separate operators that has proven to be harder to manage over time.
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3103
- [ ] Create app-bundle with Karpenter and Crossplane Manifests
- [ ] Test and validate the successful deployments of the setup
- [ ] Monitor crossplane performance over time
```

**Comment by T-Kukawka** [comment]
that part is done, we have a follow up
