### ISSUE TITLE
Use of shared cluster chart in CAPA

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3118]
### Motivation
In order to match the target state of our defined release framework we need to use the shared cluster chart in CAPA and extract all provider independent apps from cluster-aws as well as introduce the use of the cluster chart into the cluster-aws chart. 

As this work was mainly done in the initial introduction of https://github.com/giantswarm/roadmap/issues/2739 we have to adapt this ticket according to the restructure epic outcome.

### Todo

- [x] Introduce the use of the cluster chart in cluster-aws.
- [x] Remove all apps in cluster-aws that are now managed in the cluster chart.
- [x] Clearify with Team Phoenix how to roll out the change on all CAPA Installations

### Outcome
- CAPA now has the expected structure that will be aligned with the release framework across all providers.

**Comment by nprokopic** [comment]
IMO this is basically completed and we can close it ([this](https://github.com/giantswarm/roadmap/issues/2852) is the last issue for cluster-aws restructuring).

@Rotfuks did you have something else in mind here? If not, we can close this.

**Comment by Rotfuks** [comment]
The only thing I was thinking about was how we could maybe verify and introduce some more CI tests that can help us to make sure the cluster chart works for capa, even when we adapt it to the other providers. But it's up to @yulianedyalkova how she wants to handle that :)

**Comment by yulianedyalkova** [comment]
I think we're good for now since the `cluster` chart still gets indirectly tested through `cluster-aws`. But it will probably make sense to extract its own tests in the future when we adapt other providers so we don't duplicate the same set of tests for all of them.
