### ISSUE TITLE
Migrate apps from default-apps-aws to cluster chart

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3119]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [x] Move all relevant, provider-independent, shared apps from default-apps-aws into the cluster chart
- [x] Prepare the tests for this change - the change might/will be a breaking change for the test environment
- [ ] Remove all migrated apps from default-apps-aws so that they are only used from cluster chart
- [x] Clearify with Team Phoenix how to roll out the change on all CAPA Installations
- [ ] Document the design decision / process in cluster chart / cluster-aws chart

### Outcome
- The complexity of where and how apps are managed is reduced since we now have all provider independent apps in just the cluster chart

**Comment by nprokopic** [comment]
Done!
