### ISSUE TITLE
Use of shared cluster chart in CAPZ

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3121]
### Motivation
In order to match the target state of our defined release framework we need to use the shared cluster chart in CAPZ and extract all provider independent apps from cluster-azure as well as introduce the use of the cluster chart into the cluster-azure chart. 

### Todo

- [ ] Introduce the use of the cluster chart in cluster-azure.
- [ ] Remove all apps in cluster-azure that are now managed in the cluster chart.
- [ ] Clearify with Team Phoenix how to roll out the change on all CAPZ Installations

### Outcome
- CAPZ now has the expected structure that will be aligned with the release framework across all providers.
