### ISSUE TITLE
Migrate apps from default-apps-azure

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3122]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [x] #3461
- [x] #3462
- [ ] Adapt mc-bootstrap to the removal of default apps
- [ ] Adapt happa to the removal of default apps
- [x] Adapt e2e tests to the removal of default apps
- [x] Adapt kubectl-gs to the removal of default apps
- [x] #3123
- [ ] Clearify with Team Phoenix how to roll out the change on all CAPZ Installations
- [ ] Support migration of apps from default-apps-azure to cluster-azure
- [ ] Remove the default-apps-azure chart

### Outcome
- The complexity of where and how apps are managed is reduced since we now only have cluster-azure and cluster chart
- There is only one chart to apply for creating and updating clusters reducing complexity
