### ISSUE TITLE
Use of shared cluster chart in CAPV

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3124]
### Motivation
In order to match the target state of our defined release framework we need to use the shared cluster chart in CAPV and extract all provider independent apps from cluster-vsphere as well as introduce the use of the cluster chart into the cluster-vpshere chart. 

### Todo

- [ ] Introduce the use of the cluster chart in cluster-vsphere.
- [ ] Remove all apps in cluster-vsphere that are now managed in the cluster chart.
- [ ] Clearify with Team Rocket how to roll out the change on all CAPV Installations

### Outcome
- CAPV now has the expected structure that will be aligned with the release framework across all providers.

```[tasklist]
### Tasks
- [x] cluster-vsphere: use cluster chart to render Cluster resource.
- [ ] https://github.com/giantswarm/giantswarm/issues/31415
- [ ] https://github.com/giantswarm/giantswarm/issues/31416
- [ ] https://github.com/giantswarm/giantswarm/issues/31417
```

**Comment by glitchcrab** [comment]
<img src="https://media1.giphy.com/media/YCr75aO2T4ANTn6hS4/giphy.gif"/>
