### ISSUE TITLE
Migrate apps from default-apps-vsphere

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3125]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [x] Migrate apps from default-apps-vsphere to cluster chart
  - [x] capi-node-labeler v0.5.0
  - [x] cert-exporter v2.9.1
  - [x] cert-manager v3.8.1
  - [x] chart-operator-extensions v1.1.2
  - [x] cilium-servicemonitors v0.1.2
  - [x] etcd-k8s-res-count-exporter v1.10.0
  - [x] k8s-dns-node-cache v2.8.1
  - [x] metrics-server v2.4.2
  - [x] net-exporter v1.21.0
  - [x] node-exporter v1.19.0
  - [x] observability-bundle v1.5.2
  - [x] observability-policies v0.0.1
  - [x] security-bundle v1.8.0
  - [x] vertical-pod-autoscaler v5.2.4
  - [x] vertical-pod-autoscaler-crd v3.1.0
  - [x] teleport-kube-agent v0.9.2
- [x] Enable default apps in cluster-vsphere
  - [x] capi-node-labeler
  - [x] cert-exporter
  - [x] cert-manager
  - [x] chart-operator-extensions
  - [x] cilium-servicemonitors
  - [x] etcd-k8s-res-count-exporter
  - [x] k8s-dns-node-cache
  - [x] metrics-server
  - [x] net-exporter
  - [x] node-exporter
  - [x] observability-bundle
  - [x] observability-policies
  - [x] security-bundle
  - [x] vertical-pod-autoscaler
  - [x] vertical-pod-autoscaler-crd
  - [x] teleport-kube-agent
- [x] Check if remaining default apps from cluster chart should be also enabled in cluster-vsphere (those apps that are not currently in default-apps-vshere)
  - [x] cluster-autoscaler
  - [x] external-dns
  - [x] k8s-audit-metrics
  - [x] prometheus-blackbox-exporter
- [x] Migrate apps from default-apps-vsphere to cluster-vsphere chart (there are no vSphere-specific apps in default-apps-vsphere)
- [x] Move vSPhere-specific default apps default config from default-apps-vsphere to cluster-vsphere (or ensure that the needed default config is already present in cluster chart)
  - [x] cert-exporter (added vSphere-specific config to cluster-vsphere)
  - [x] cert-manager (added vSphere-specific config to cluster-vsphere)
  - [x] etcd-k8s-res-count-exporter (uses default config from cluster chart)
  - [x] metrics-server (uses default config from cluster chart)
  - [x] net-exporter (uses default config from cluster chart)
  - [x] node-exporter (added vSphere-specific config to cluster-vsphere)
  - [x] vpa (CNP config from default-apps-vsphere does not exist anymore in the VPA app)
- [x] Remove provider-independent HelmReleases from cluster-vsphere and enable them from the cluster chart. Also add vSphere-specific app config in cluster-vsphere.
  - [x] cilium
  - [x] coredns
  - [x] network-policies
- [x] Adapt mc-bootstrap to the removal of default apps
- [x] Adapt happa to the removal of default apps
- [x] Adapt e2e tests to the removal of default apps
  - [x] https://github.com/giantswarm/clustertest/pull/283
- [x] https://github.com/giantswarm/kubectl-gs/pull/1410
- [ ] Update docs on how to apply CAPV clusters
- [ ] Clearify with Team Rocket how to roll out the change on all CAPV Installations
- [ ] Support migration of apps from default-apps-vsphere to cluster-vsphere
- [ ] Remove the default-apps-vsphere chart

### Outcome
- The complexity of where and how apps are managed is reduced since we now only have cluster-vsphere and cluster chart
- There is only one chart to apply for creating and updating clusters reducing complexity
