### ISSUE TITLE
CAPV Teleport for SSH & cluster access

### ISSUE THREAD

**Issue by tuladhar** [giantswarm/roadmap#3128]
Replace the Giant Swarm VPN with Teleport for SSH and Kubernetes API access to CAPV clusters.

- bamboo (testing - deprecated)
- gcapeverde (stable-testing)
- gmc (ephemeral)
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/cluster-vsphere/pull/91
- [x] Release new version of cluster-vspshere with teleport support
- [x] Upgrade cluster-vsphere MCs for K8s API access
- [x] Upgrade cluster-vsphere MCs for SSH access
```
