### ISSUE TITLE
Monitor Cluster API workload clusters

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/roadmap#313]
## User Story

_- As a Giant Swarm Engineer, I want to collect metrics for Cluster API workload clusters so that I will be aware when something is broken._

_- As a Giant Swarm customer, I want to have my Cluster API workload clusters monitored so that I can rely on their reliability._

### TODO

- [x] https://github.com/giantswarm/giantswarm/issues/16008 Check if PMO works w/ CAPI clusters
- [x] https://github.com/giantswarm/giantswarm/issues/12703
- [ ] Review the rules and monitoring of workload clusters in CAPG and CAPA

**Comment by snizhana-dynnyk** [comment]
let's change the labeling schema in scope of this https://github.com/giantswarm/giantswarm/issues/16734

**Comment by snizhana-dynnyk** [comment]
Diff targets of CAPI and non CAPI cluster, so we can tell what we need to add:
https://prometheus.g8s.godsmack.westeurope.azure.gigantic.io/yz45m/targets and https://prometheus.g8s.godsmack.westeurope.azure.gigantic.io/fz30w/targets

**Comment by teemow** [comment]
fyi @alex-dabija this is the current issue in the CAPI roadmap.

**Comment by TheoBrigitte** [comment]
Feel free to re-open if needed.
