### ISSUE TITLE
Use of shared cluster chart in CAPVCD

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3133]
### Motivation
In order to match the target state of our defined release framework we need to use the shared cluster chart in CAPVCD and extract all provider independent apps from cluster-cloud-director as well as introduce the use of the cluster chart into the cluster-cloud-director chart. 

```[tasklist]
### Tasks
- [ ] Introduce the use of the cluster chart in cluster-cloud-director.
- [ ] Remove all apps in cluster-cloud-director that are now managed in the cluster chart.
- [ ] Clearify with Team Rocket how to roll out the change on all CAPVCD Installations
- [ ] https://github.com/giantswarm/giantswarm/issues/31193
- [ ] https://github.com/giantswarm/giantswarm/issues/31697
- [ ] https://github.com/giantswarm/giantswarm/issues/31698
- [ ] https://github.com/giantswarm/giantswarm/issues/31699
- [ ] https://github.com/giantswarm/giantswarm/issues/31700
- [ ] https://github.com/giantswarm/giantswarm/issues/31701
```

### Outcome
- CAPV now has the expected structure that will be aligned with the release framework across all providers.

**Comment by glitchcrab** [comment]
done 🥳
