### ISSUE TITLE
Migrate apps from default-apps-cloud-director

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3134]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [ ] Move all relevant, provider-independent, shared apps from default-apps-cloud-director into the cluster chart
- [ ] Move all relevant, provider specific apps from default-apps-cloud-director into the cluster-cloud-director chart
- [ ] Clearify with Team Rocket how to roll out the change on all CAPVCD Installations
- [ ] Remove the default-apps-cloud-director chart

### Outcome
- The complexity of where and how apps are managed is reduced since we now only have cluster-cloud-director and cluster chart
- There is only one chart to apply for creating and updating clusters reducing complexity
