### ISSUE TITLE
Prepare CAPVCD for 1.25 - MC todo

### ISSUE THREAD

**Issue by erkanerol** [giantswarm/roadmap#3144]
Similar to https://github.com/giantswarm/roadmap/issues/2970

***FOR ALL CLUSTERS***
- [x] Add security-bundle to default-apps https://github.com/giantswarm/default-apps-azure/pull/179/files
  - **_Xavier_**: https://github.com/giantswarm/default-apps-cloud-director/pull/222 
- [x] Add the PSS flag to the cluster chart. https://github.com/giantswarm/cluster-azure/pull/179/files (set false by default for now)
   - [x] Check cluster-shared and default PSPs (restricted and privileged) Add necessary changes to make them inactive when `global.podSecurityStandards.enforced=true`
      - See https://github.com/giantswarm/cluster-azure/blob/main/helm/cluster-azure/templates/list.yaml#L1C21-L1C31
      - See https://github.com/giantswarm/cluster-shared/commit/f0119bd2d5941558bc787a8a88ebc625fbd99812#diff-99b41a864d78d940e5ffa44fbbd0ad075cf29b05b8bbbb298e88188aecfb849fR252
      - **_Xavier_**: `cluster-shared` was removed from `cluster-cloud-director` a long time ago so I think this doesn't apply as a result. Unless we need it for some reason?
   - [x] Ensure all apps in HelmReleases (e.g.) are up-to-date. And also check they respect the global flag.
     - **_Xavier_**: https://github.com/giantswarm/cloud-provider-cloud-director-app/pull/78)
   - [x] Ensure you have the latest version of pss-operator and app-admission-controller in your MC (These mutate all WC apps according to the label on Cluster CR)
     - **_Xavier_**: `Gerbil / leopard` are ok.
    - [x] When you set `global.podSecurityStandards.enforced=true` for `cluster-chart`, you should observe
         - `policy.giantswarm.io/psp-status: disabled` label on Cluster CR
         - This setting in all apps of WC      
        ```
        extraConfigs:
          - kind: configMap
            name: psp-removal-patch
            namespace: org-giantswarm
            priority: 150
        ```
        
        
***How to test***

- Scenario 1: Install with 1.24
   - ClusterPolicies should be in `enforce` mode by default. 
   - PSPs should exist unless `global.podSecurityStandards.enforced=true`

- Scenario 2: Install with 1.25
   - ClusterPolicies should be in `enforce` mode by default. 
   - You have to use `global.podSecurityStandards.enforced=true`

- Scenario 3: Upgrade from 1.24 to 1.25
   - Ensure PSS are OK in the cluster 
   - Set `global.podSecurityStandards.enforced=true` before the upgrade. You should observe that 
      - PSPs have disappeared and they are inactive.
      - WC apps are mutated.
      - Set k8s version as 1.25 and observe everything is fine.
      
      
 ***FOR MC CLUSTERS***
See https://github.com/giantswarm/giantswarm/issues/29801#issuecomment-1943721644

**Comment by vxav** [comment]
Comments added to issue body.

**Comment by vxav** [comment]
WC cluster on 1.25 confirmed ok.

**Comment by erkanerol** [comment]
Here are the steps for MC upgrades in CAPZ. https://github.com/giantswarm/giantswarm/issues/29801#issuecomment-1943721644

**Comment by vxav** [comment]
@glitchcrab did you want to pick up the MC part?

**Comment by glitchcrab** [comment]
VCD MC upgrade steps:

- upgrade cluster-cloud-director to 0.14.6 for psp flag (last release before PSS was enforced) 
- enable PSS/disable PSPs by setting global.podSecurityStandards.enforced=true on cluster app
- ensure default-apps is at 0.7.4 to enforce PSS
- set PSS to enforced via config repo
- remove flux psps
- update vm image to ubuntu-2004-kube-v1.25.13 in cluster chart values & update cluster chart to 0.15.0 (enforces PSS)

**Comment by glitchcrab** [comment]
testing on glasgow:

- [x] cluster chart already on 0.14.6
- [x] enforce PSS on cluster chart https://github.com/giantswarm/giantswarm-management-clusters/pull/474
- [x] default apps already at 0.7.4
- [x] enforce PSS for all apps https://github.com/giantswarm/giantswarm-configs/pull/24

**Comment by glitchcrab** [comment]
gerbil:

- [ ] update cluster chart to 0.14.6
- [ ] enforce PSS on cluster chart https://github.com/giantswarm/giantswarm-management-clusters/pull/474
- [ ] update default apps to 0.7.4
- [ ] enforce PSS for all apps https://github.com/giantswarm/giantswarm-configs/pull/24
- [ ] remove Flux PSPs https://github.com/giantswarm/giantswarm-management-clusters/pull/475 
  - [ ] delete Flux PSPs `kubectl delete psp flux-app-pvc-psp flux-app-pvc-psp-giantswarm` 
- [ ] update k8s image to `ubuntu-2004-kube-v1.25.13` & cluster chart to 0.15.1 https://github.com/giantswarm/giantswarm-management-clusters/pull/476
- [ ] delete removed kyverno apps `kubectl -n giantswarm delete app kyverno kyverno-policies kyverno-policy-operator`
- [ ] temporarily consume collections branch with updated capi-app https://github.com/giantswarm/giantswarm-management-clusters/blob/main/management-clusters/glasgow/capi-app-custom-branch.yaml

leopard:

- [ ] update cluster chart to 0.14.6
- [ ] enforce PSS on cluster chart https://github.com/giantswarm/giantswarm-management-clusters/pull/474
- [ ] update default apps to 0.7.4
- [ ] enforce PSS for all apps https://github.com/giantswarm/giantswarm-configs/pull/24
- [ ] remove Flux PSPs https://github.com/giantswarm/giantswarm-management-clusters/pull/475 
  - [ ] delete Flux PSPs `kubectl delete psp flux-app-pvc-psp flux-app-pvc-psp-giantswarm` 
- [ ] update k8s image to `ubuntu-2004-kube-v1.25.13` & cluster chart to 0.15.1 https://github.com/giantswarm/giantswarm-management-clusters/pull/476
- [ ] delete removed kyverno apps `kubectl -n giantswarm delete app kyverno kyverno-policies kyverno-policy-operator`
- [ ] temporarily consume collections branch with updated capi-app https://github.com/giantswarm/giantswarm-management-clusters/blob/main/management-clusters/glasgow/capi-app-custom-branch.yaml

**Comment by glitchcrab** [comment]
finito
