### ISSUE TITLE
Gateway API

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#3150]
With the general availability of [gateway api](https://gateway-api.sigs.k8s.io/) as a replacement for ingress api we should evaluate if we can create benefits from migration to gateway api.

### Next steps
- [ ] Design a migration plan for customers
- [ ] Canary deployments with Gateway API
- [ ] Gateway API alerts and ops

**Comment by ubergesundheit** [comment]
Seems we need to take care of making sure cert-manager and external-dns are upgraded

- external-dns supports Gateway API from 0.14.1 or above
- cert-manager needs to be 1.14 or above (gs app 3.7.5)
- cert-manager needs set extraArgs={--feature-gates=ExperimentalGatewayAPISupport=true}

**Comment by mcharriere** [comment]
Bad news:

In v1.14 and earlier versions of cert-manager (Cluster v29) the one flag used to enable the GatewayAPI controlled only if cert-manager would watch over Gateway CRs, but the generation of HTTPRoutes for the Issuers was not affected.

After 1.15 (Cluster v30 has 1.16) this flag now controls everything, meaning that if the flag is disabled, cert-manager ignores Gateway CRs and DOES NOT generate HTTPRoutes for issues that require it failing with:
```
cert-manager-app-7456bfd54f-qsfjw cert-manager-app-controller E0304 08:40:34.849046       1 controller.go:157] "re-queuing item due to error processing" err="couldn't Present challenge envoy-gateway-system/gateway-giantswarm-default-1-1484614847-2309892542: gateway api is not enabled" logger="cert-manager.controller"
```

Then the problem is that setting enableGatewayAPI to true by default requires CRDs to be installed before hand, otherwise cert-manager fails to start.

For now, we need to resort on configuring cert-manager per cluster basis with this snippet:
```
certManager:
  values:
    config:
      apiVersion: controller.config.cert-manager.io/v1alpha1
      kind: ControllerConfiguration
      enableGatewayAPI: true
````
Of course this needs to be done after installing the bundle or CRDs.

In the future, we should consider shipping the CRDs by default.

**Comment by mcharriere** [comment]
As a reference for managing the TLS certs, Google is doing this: https://cloud.google.com/kubernetes-engine/docs/how-to/secure-gateway#create-resources-ssl

**Comment by weatherhog** [comment]
this is done
