### ISSUE TITLE
EKS clusters managed by Cluster API for AWS - Basic Setup

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#316]
As a Customer i would like to have a EKS clusters being deployed with Cluster API AWS provider where EKS is fuilly integrated with GS offering.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/2609
- [ ] https://github.com/giantswarm/roadmap/issues/2816
- [ ] https://github.com/giantswarm/roadmap/issues/2817
- [ ] https://github.com/giantswarm/roadmap/issues/2818
- [ ] https://github.com/giantswarm/roadmap/issues/2819
- [ ] https://github.com/giantswarm/roadmap/issues/2820
- [ ] https://github.com/giantswarm/roadmap/issues/2929
- [ ] https://github.com/giantswarm/giantswarm/issues/29583
- [ ] https://github.com/giantswarm/roadmap/issues/3172
- [ ] https://github.com/giantswarm/roadmap/issues/3174
- [ ] https://github.com/giantswarm/giantswarm/issues/29323
- [ ] https://github.com/giantswarm/giantswarm/issues/28666
- [ ] https://github.com/giantswarm/giantswarm/issues/28646
- [ ] https://github.com/giantswarm/roadmap/issues/3142
```

**Comment by JosephSalisbury** [comment]
alex told me to close this, blam!
