### ISSUE TITLE
Prepare for removal of CAPA v1beta1 API types

### ISSUE THREAD

**Issue by AndiDog** [giantswarm/roadmap#3170]
See https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/4757
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3344
- [ ] Does conversion from v1beta1 to v1beta2 remain in CAPA v2.4.0? If not, we'd have to bump all objects.
- [ ] Is exp/api also affected (machine pools, etc.)?
```

**Comment by AndiDog** [comment]
Some operators reference v1beta1. Here's a short overview, but we should use GitHub search instead of my cloned repos:

```
$ ag -l --go '"sigs.k8s.io/cluster-api-provider-aws/api/v1beta1' | cut -d / -f 1 | sort | uniq
aws-resolver-rules-operator
aws-vpc-operator
capa-iam-operator
opsctl
```

**Comment by T-Kukawka** [comment]
2.5.x is running on all MCs.
