### ISSUE TITLE
[EPIC] Manage Clusters on vmware using CAPV

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#319]
## User Story

As a customer I want to create native vmware clusters so that I can make use of my existing vmware infrastructure without additional virtualization layers.

## Details, Background

Currently Giant Swarm vmware support is done via the kvm operator. While this works well and is a battle tested setup, it has some limitations, for example there is currently no support for Persistent Volume Claims via the vmware CSI and there is an additional virtualization layer that has a small performance impact.
By managing virtual machines directly at the via the vmware operators provided by the Cluster API project we will overcome this limitations and provide a more integrated user experience.

## Blocked by / depends on

Monitor CAPI Workload Clusters https://github.com/giantswarm/roadmap/issues/313
Default apps for CAPI Clusters https://github.com/giantswarm/roadmap/issues/320
Align bootstrap defaults https://github.com/giantswarm/roadmap/issues/300

```[tasklist]
### Tasks
- [x] https://github.com/giantswarm/roadmap/issues/1871
- [x] #1157
- [ ] https://github.com/giantswarm/roadmap/issues/2232
- [ ] https://github.com/giantswarm/giantswarm/issues/25783
- [ ] https://github.com/giantswarm/giantswarm/issues/25518
- [ ] https://github.com/giantswarm/giantswarm/issues/18984
- [ ] https://github.com/giantswarm/roadmap/issues/1892
- [ ] https://github.com/giantswarm/roadmap/issues/1889
- [ ] https://github.com/giantswarm/roadmap/issues/2091
- [x] https://github.com/giantswarm/giantswarm/issues/25257
- [x] https://github.com/giantswarm/roadmap/issues/2151
- [ ] https://github.com/giantswarm/roadmap/issues/2090
- [ ] https://github.com/giantswarm/giantswarm/issues/26358
- [ ] https://github.com/giantswarm/roadmap/issues/2152
- [ ] https://github.com/giantswarm/roadmap/issues/2187
- [ ] https://github.com/giantswarm/roadmap/issues/2015
- [ ] https://github.com/giantswarm/roadmap/issues/2022
- [ ] https://github.com/giantswarm/roadmap/issues/2189
- [ ] https://github.com/giantswarm/roadmap/issues/458
- [ ] https://github.com/giantswarm/roadmap/issues/2216
- [x] https://github.com/giantswarm/roadmap/issues/2231
- [ ] https://github.com/giantswarm/giantswarm/issues/26409
- [ ] https://github.com/giantswarm/roadmap/issues/2188
- [ ] https://github.com/giantswarm/roadmap/issues/2192
- [x] https://github.com/giantswarm/roadmap/issues/2335
- [ ] https://github.com/giantswarm/roadmap/issues/2336
- [ ] https://github.com/giantswarm/roadmap/issues/2332
- [ ] https://github.com/giantswarm/roadmap/issues/2338
- [ ] https://github.com/giantswarm/roadmap/issues/2339
- [ ] https://github.com/giantswarm/roadmap/issues/2340
- [ ] https://github.com/giantswarm/roadmap/issues/2194
- [x] https://github.com/giantswarm/roadmap/issues/2353
- [ ] https://github.com/giantswarm/roadmap/issues/2191
- [ ] https://github.com/giantswarm/roadmap/issues/1553
- [ ] https://github.com/giantswarm/roadmap/issues/2227
- [ ] https://github.com/giantswarm/roadmap/issues/2184
- [ ] https://github.com/giantswarm/roadmap/issues/2228
- [ ] https://github.com/giantswarm/roadmap/issues/2229
- [ ] https://github.com/giantswarm/roadmap/issues/2757
```

**Comment by cornelius-keller** [comment]
Included tasks from https://github.com/giantswarm/giantswarm/issues/22106 for the alpha milestone.

**Comment by gawertm** [comment]
check current test environment on ionos. VPN is broken rn.

first step to update the charts: 
cluster-vsphere
cloud-provider-vsphere
default-apps-vsphere (maybe not needed if we move CPI,CSI,CNI to cluster-vsphere)
app-collection-vsphere
CSI
CAPV

other features done for providers like CAPVCD will have to be done for CAPV as well. To be checked on previous CAPVCD tasks

mc-bootstrap to work with CAPV

notes: flatcar for CAPV supported

**Comment by gawertm** [comment]
cc @jkremser

**Comment by gawertm** [comment]
next steps: 
update default-apps and app-collection
IPAM: we can assume to have 1 subnet per MC
Loadbalancing solution, trying to go with NSX-T ALB

**Comment by gawertm** [comment]
closing as we are done with CAPV. open issues are tracked separately in the backlog
