### ISSUE TITLE
Use node-pool resources from cluster chart

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3194]
### Motivation

In order to have all provider-independent apps and components in the cluster chart as designed in this epic, in cluster-aws we need to render node-pool resources from the cluster chart.

### Todo

```[tasklist]
- [ ] Fix node pool resources in cluster chart https://github.com/giantswarm/cluster/pull/70
- [ ] Use the node-pool resources from the cluster chart in capa
- [ ] Remove the node-pool resources from cluster-aws
- [ ] Test it.
```

### Outcome
- All node-pool resources (and with it mainly all provider-independent apps and components) are moved to cluster chart and in use on capa through the cluster chart.
