### ISSUE TITLE
App Catalog Partner Integration

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#32]
## User Story

As a Giant Swarm partner company, I want to enable my user/customers to install my software easily to their clusters.

As Giant Swarm partner company, I want to be featured and have a special position (compared to community apps) in the App Catalog section.

## TODO

- [ ] Find a way to do easy release management for a separate partner catalog
  - [ ] evaluate options
  - [ ] talk with partners if options will work out 
  - [ ] build tooling
- [ ] Expand on UX for partners
- [ ] Documentation
  - [ ] Document/explain what the partner catalog is for and what support level can be expected as a customer
  - [ ] Document how to add new partners

## Details, Background

We started our first partnership with Instana, which is installed through their chart in the Helm upstream community catalog. However, the community catalog is full of apps and it is hard to find our partners among them.

The current list of planned partner integrations is tracked in https://github.com/orgs/giantswarm/projects/74 and can be found by the label [growth/partners](https://github.com/issues?q=is%3Aissue+is%3Aopen+archived%3Afalse+sort%3Aupdated-desc+label%3Agrowth%2Fpartners).

There would be the option to have prioritized displaying of certain charts in the community catalog, but it is still in the community catalog, which will say sth along the lines of "apps in here are not supported by Giant Swarm, all support is purely open source".

Another option would be having partners provide their own catalogs, but that would mean we have tons of single app catalogs which are bad UX too.

Third option and currently favored would be a general partner catalog where we include some differing release tooling to our own. Basic thought around is a similar tool to https://github.com/giantswarm/retagger, i.e. a tool that we can point to a chart repository and that syncs the chart to our partner catalog. This option was suggested by @rossf7

Aha! Link: https://giantswarm.aha.io/features/B-9
