### ISSUE TITLE
auth-bundle ux improvements

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3202]
We have received feedback for improving auth-bundle installation UX since it's still cumbersome for the customer/AE to configure.

> - not have to configure external dns separately (gerald took it to cabbage)
>- be able to provide values in a single place and without worrying about labels etc (I got errors because of labels/annotations missing)
>- have something that automatically patches the WC CR in the MC so that we don't need to do it manually but rather only need to terminate the node getting rid of copy-paste errors, indentation errors, ...
>- be able to infer the MC name in athena without having to pass an additional configmap
>- have the two values specified in dex being the default (not sure if it already is)
>- in other words, I think we should ask customers to only provide the real configuration without having to deal with all the underlying shenanigans (cluster CR, annotations for app-operator, ...) that our platform uses under the hood. as a managed service we should take care of the shenanigans and they should just consume the platform 

Also @LolloneS provided a writeup of the installation process he had to go through which we should add to the auth-bundle `README.md`. It can be found here: https://gigantic.slack.com/files/U02NXQHQUMB/F06GP6SHS1H/instructions.md

```[tasklist]
### Tasks
- [x] Automate the configuration of external DNS
- [ ] https://github.com/giantswarm/roadmap/issues/3549
- [ ] https://github.com/giantswarm/roadmap/issues/3550
- [ ] https://github.com/giantswarm/roadmap/issues/3551
```

**Comment by vvondruska** [comment]
In its current state the auth bundle apps need to be configured individually - in separate sections of the values.yaml file. This seems to be the default way to configure app bundles.

We are thinking to introduce an additional section for common configuration values in `values.yaml`, where the users could provide the usual configuration for the auth apps like e.g. Dex connector setup, admin groups for RBAC, etc. We will also explore other existing configurations in the MC and re-use them as much as possible to ensure that the users are not required to provide details that we already have. Values from the new section of the `values.yaml` file and the external configs will be distributed to the individual apps within the bundle as needed.

The default, app-specific configuration sections will be kept as they are, and they will be treated with higher priority than the newly introduced common section.

So, the user will be able to either provide a basic configuration for the auth bundle in the common section, or an advanced, fine-grained and detailed configuration in the app-specific sections.

In case conflicting values exist in the common and the app-specific sections, the app-specific configuration will prevail.

FYI @LolloneS

**Comment by vvondruska** [comment]
Patching WC CR in the MC can be implemented in the Dex operator.

Control plane nodes in the WC should not be rolled automatically after changing the OIDC flags because it is not desirable for some customers.

However, we can try to make it configurable. We could for example add a boolean flag to the Auth bundle values, and if the flag is set to true, the CP nodes would be rolled automatically. By default the flag would be set to false. TBD whether or not it is a good idea.

**Comment by vvondruska** [comment]
We discussed the option to roll the nodes within the team, and the outcome is that we can try to roll the nodes in case an annotation is present in the Dex app. The annotation will be handled by the Dex operator. The Auth bundle will also have an option to set the annotation in the Dex app - it will be disabled by default. So, this will be an opt-in feature.

**Comment by vvondruska** [comment]
The simplified auth bundle configuration needs to be merged with the full configuration in case both of them are provided. The full configuration can be specified both in configmaps and secrets, whereas the default configuration will always be provided in a specific resource (either a configmap or a secret). In case the default and full configurations both contain the same properties (it can happen because in the default configuration many properties are generated) and they are contained in different resource types (e.g. the default configuration has them in a secret, whereas the full configuration has them in a configmap), then merging these values can have unpredictable results.
After discussing this issue with the team it was decided to document it and advice the users to use the same type of resource in the full configuration to override properties from the default configuration.

**Comment by gawertm** [comment]
@vvondruska is there any way we can have only 1 set of configuration? not exactly sure how, but one place would be nicer where most values are defaulted and user just override with their config. not sure how it will work with the individual app configs.. how is it done in the security bundle?

**Comment by vvondruska** [comment]
This is what I am aiming for. It will work like that. 
The above comment is about the fact that the app platform allows defining the configuration either in a configmap or in a secret or in both. There was a suggestion that we could force providing the configuration is a secret for Dex, but during the team discussion it was decided that we should keep support for both configmaps and secrets.

**Comment by vvondruska** [comment]
This PR contains the changes needed to support the required functionality: https://github.com/giantswarm/auth-bundle/pull/64
Testing is in progress.
JSON schema will be updated once the initial tests are concluded.

**Comment by vvondruska** [comment]
Initial tests look good. Auth bundle apps created with `defaultConfig` values work correctly.
Tested with 2 connectors:
- `microsoft` connector with an unexpected extra [roperty (added for testing purposes) works aas expected
- `keystore` connector, which does not expect the `redirectURI` property in its config, It was recognized and accepted by Dex even with the injected `redirectURI` property in the config

**Comment by vvondruska** [comment]
Testing is still in progress, but the [PR](https://github.com/giantswarm/auth-bundle/pull/64) has been marked as ready for review to collect feedback about the structure of the new simple config section in values.yaml.

**Comment by vvondruska** [comment]
A new version of the Auth bundle v0.2.0 with simplified configuration has been released.

**Comment by vvondruska** [comment]
Work in the Auth bundle has been completed. The last part - OIDC flag handling cannot be safely automated in the Auth bundle or Dex operator.

If it's possible at all, it needs to be done on the Cluster App level. This approach will be explored as a separate work stream. Improvements in the Auth bundle can be considered closed.
