### ISSUE TITLE
General testing of AWS v20 together with Vintage-CAPA migration

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3204]
The time has come to start testing final releases as well as migration from Vintage `v20` to CAPA. We have created a dedicated Vintage MC `garfish` to perform any vintage or migration testing for stability purposes. The dedicated CAPA cluster for migration will be the CAPA Stable-testing MC `grizzly`.

We would kindly ask all teams to perform comprehensive tests for 3 use-cases, ordered in terms of priorities if they can't be performed all at once.

### 1. Vintage [`AWS v20`](https://github.com/giantswarm/releases/pull/1204) 
***Cluster creation on `grizzly` - `giantswarm` Organization***

This is the last release of Vintage containing `1.25 k8s`. The `1.25` kubernetes introduces a breaking change in terms of removal `PSPs` from its API, meaning that all workloads will have to comply with the `global` toggle disabling` PSPs` as in `19.3.x` release. Prior to making `v20` release available to customers, we need to validate that all applications are running smoothly. The Vintage tests are standard as always - you just create the `v20` release and validate your applications. Separate stable MC in this case will guarantee no manual changes in the release and stability.

- [x] Phoenix finished with Vintage `v20` testing
- [x] Turtles finished with Vintage `v20` testing
- [x] Shield finished with Vintage `v20` testing
- [x] Atlas finished with Vintage `v20` testing
- [x] Honeybadger finished with Vintage `v20` testing
- [x] BigMac finished with Vintage `v20` testing
- [x] Cabbage finished with Vintage `v20` testing

### 2. CAPA [`0.60.0`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md#0600---2024-01-29) 
***Cluster creation on `grizzly` - `giantswarm` Organization - be aware that this is production MC, so it will page everyone. In practice any CAPA MC should work for this test.***

Starting with `cluster-aws`-`v0.60.0` and `default-apps-aws`-`v0.45.1` onwards CAPA supports Kubernetes 1.25 with all needed features to run our workloads in the same manner as on VIntage clusters. Please for testing use always latest [`cluster-aws`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md) as well as [`default-apps-aws`](https://github.com/giantswarm/default-apps-aws/blob/master/CHANGELOG.md) releases.

- [x] Phoenix finished with CAPA 1.25 testing
- [x] Turtles finished with CAPA 1.25 testing
- [x] Shield finished with CAPA 1.25 testing
- [x] Atlas finished with CAPA 1.25 testing 
- [x] Honeybadger finished with CAPA 1.25 testing
- [x] BigMac finished with CAPA 1.25 testing
- [x] Cabbage finished with CAPA 1.25 testing

### 3. Vintage to CAPA migration 
***Cluster creation for migration on `grizzly` - `capa-migration-testing` Organization. Clusters will be migrated to `grizzly` - `capa-migration-testing` Organization.***

Phoenix and Honeybadger worked extensively on making the migration as smooth as possible. The [`migration-cli`](https://github.com/giantswarm/capi-migration-cli) has been introduced that orchestrates migration of apps as well as infrastructure. Here the main point is to discover if your application and any custom configurations that could be applied by customers are migrated properly.

The `migration-cli` has been extended to facilitate easy testing for all teams ad Giant Swarm. Please follow the requirements as well as the procedure that is described in the [`tests` section](https://github.com/giantswarm/capi-migration-cli/tree/main/tests) of the tool. In case of any issue with infrastructure - ping Phoenix, if the app/configmap migration will face any issues or inconsistencies - ping Honeybadger.

- [x] Phoenix finished with Vintage to CAPA migration testing
- [x] Turtles finished with Vintage to CAPA migration testing
- [x] Shield finished with Vintage to CAPA migration testing
- [x] Atlas finished with Vintage to CAPA migration testing
- [x] Honeybadger finished with Vintage to CAPA migration testing
- [x] BigMac finished with Vintage to CAPA migration testing
- [x] Cabbage finished with Vintage to CAPA migration testing
```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3206
- [ ] https://github.com/giantswarm/roadmap/issues/3207
- [ ] https://github.com/giantswarm/roadmap/issues/3208
- [ ] https://github.com/giantswarm/roadmap/issues/3209
- [ ] https://github.com/giantswarm/roadmap/issues/3210
- [ ] https://github.com/giantswarm/roadmap/issues/3211
- [ ] https://github.com/giantswarm/roadmap/issues/3212
```

**Comment by teemow** [comment]
@T-Kukawka @weatherhog Cabbage testing of the migration is still open. But we've done the first migration. Can we close the cabbage issue and this one here?

**Comment by mcharriere** [comment]
Sorry we missed the to tick the checkbox in this issue. From Cabbage side we are done and ok.
