### ISSUE TITLE
Atlas testing of AWS v20 together with Vintage-CAPA migration

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3209]
The time has come to start testing final releases as well as migration from Vintage `v20` to CAPA. We have created a dedicated Vintage MC `garfish` to perform any vintage or migration testing for stability purposes. The dedicated CAPA cluster for migration will be the CAPA stable-testing MC `grizzly`.

We would kindly ask all teams to perform comprehensive tests for 3 use-cases, ordered in terms of priorities if they can't be performed all at once.

### 1. Vintage [`AWS v20`](https://github.com/giantswarm/releases/pull/1204) 
***Cluster creation on `garfish` - `giantswarm` Organization***

This is the last release of Vintage containing `1.25 k8s`. The `1.25` kubernetes introduces a breaking change in terms of removal `PSPs` from its API, meaning that all workloads will have to comply with the `global` toggle disabling` PSPs` as in `19.3.x` release. Prior to making `v20` release available to customers, we need to validate that all applications are running smoothly. The Vintage tests are standard as always - you just create the `v20` release and validate your applications. Separate stable MC in this case will guarantee no manual changes in the release and stability.

- [x] Atlas finished with Vintage `v20` testing (please mark it in main issue as well)

### 2. CAPA [`0.60.0`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md#0600---2024-01-29) 
***Cluster creation on `grizzly` - `giantswarm` Organization - be aware that this is production MC, so it will page everyone. In practice any CAPA MC should work for this test.***

Starting with `cluster-aws`-`v0.60.0` and `default-apps-aws`-`v0.45.1` onwards CAPA supports Kubernetes 1.25 with all needed features to run our workloads in the same manner as on VIntage clusters. Please for testing use always latest [`cluster-aws`](https://github.com/giantswarm/cluster-aws/blob/master/CHANGELOG.md) as well as [`default-apps-aws`](https://github.com/giantswarm/default-apps-aws/blob/master/CHANGELOG.md) releases.

- [x] Atlas finished with CAPA 1.25 testing (please mark it in main issue as well)

### 3. Vintage to CAPA migration 
***Cluster creation for migration on `garfish` - `capa-migration-testing` Organization. Clusters will be migrated to `grizzly` - `capa-migration-testing` Organization.***

Phoenix and Honeybadger worked extensively on making the migration as smooth as possible. The [`migration-cli`](https://github.com/giantswarm/capi-migration-cli) has been introduced that orchestrates migration of apps as well as infrastructure. Here the main point is to discover if your application and any custom configurations that could be applied by customers are migrated properly.

The `migration-cli` has been extended to facilitate easy testing for all teams ad Giant Swarm. Please follow the requirements as well as the procedure that is described in the [`tests` section](https://github.com/giantswarm/capi-migration-cli/tree/main/tests) of the tool. In case of any issue with infrastructure - ping Phoenix, if the app/configmap migration will face any issues or inconsistencies - ping Honeybadger.

- [ ] Atlas finished with Vintage to CAPA migration testing (please mark it in main issue as well)

```[tasklist]
### Tasks
- [x] prometheus operator and kube-state-metrics
- [x] metrics-server
- [x] loki (with s3 backed storage)
- [x] promtail
- [x] grafana-agent
- [x] fluent-logshipping-app
- [x] grafana
- [x] Test prometheus operator with a different namespace as it appears this is getting set to kube-system automatically
- [ ] https://github.com/giantswarm/roadmap/issues/3249
- [ ] https://github.com/giantswarm/giantswarm/issues/29861
```

**Comment by QuentinBisson** [comment]
Regarding vintage 20.0.0, I've tested both creation of v20 and an upgrade from v19.3.1 to v20 on garfish and it is working.

I have a bit of concern regarding the grafana-agent and the logging operator creating it's config as I noticed that the secret was not created during my initial tests but it will solve itself after 12 hours or a restart of the logging operator so it is not blocking. @marieroque I recall that you faced something similar in an incident (grafana-agent secret missing or smth). Could you take a quick look ?


@T-Kukawka as a remainder, we still need to discuss the release notes as the observability-bundle in release 20.0.0 has a few breaking changes :)

**Comment by QuentinBisson** [comment]
So for confirmation, the part 3 is about all our managed apps and possible customer configs :(

**Comment by QuentinBisson** [comment]
For sure, we will try to have as much different configs as possible for that

**Comment by QuentinBisson** [comment]
@giantswarm/team-atlas to make sure we test the migration properly, I would like if we could deploy all apps we have (i know this will be painful) on a 19.3.0 WC on garfish, then upgrade to v20 and then run the migration-cli tool.

In an effort to not have to redo all this again, maybe we can setup a template to set as much as possible up?

I'm pretty confident the migration will break apps that use irsa like Loki so that's all the more intesting to test it

**Comment by QuentinBisson** [comment]
```[tasklist]
### Tasks
- [ ] prometheus operator and kube-state-metrics
- [ ] metrics-server
- [ ] loki (with s3 backed storage)
- [ ] promtail
- [ ] grafana-agent
- [ ] fluent-logshipping-app
- [ ] grafana
```

**Comment by QuentinBisson** [comment]
This is the issue that is happening for the chart-operator-externsions:
    reason: 'object already exists: (rendered manifests contain a resource that already
      exists. Unable to continue with install: ServiceMonitor "chart-operator" in
      namespace "giantswarm" exists and cannot be imported into the current release:
      invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace"
      must equal "giantswarm": current value is "kube-system")'
    status: already-exists

**Comment by QuentinBisson** [comment]
@T-Kukawka once the loki -> oki issue is fixed on honeybadger side, then I think atlas would only have to redo the tests with Loki and those 2 items:



![Image](https://github.com/giantswarm/roadmap/assets/2787548/1c5c4e54-33a9-4a05-90b0-b0add5542285)

The fluent-logshipping-app change will be the main issue I think

**Comment by QuentinBisson** [comment]
Second issue for @giantswarm/team-honeybadger but user-values configmap are not transfered;

on my garfish WC, I have this set by the cluster-operator using the app.kubernetes.io/name=observability-bundle

```
  userConfig:
    configMap:
      name: atlastest-observability-bundle-user-values
      namespace: atlastest
```

But on the gazelle MC, this is rendered without the uservalues configmap

```
spec:
  catalog: default
  config:
    configMap:
      name: atlastest-cluster-values
      namespace: org-capa-migration-testing
    secret:
      name: ""
      namespace: ""
  extraConfigs:
  - kind: configMap
    name: psp-removal-patch
    namespace: org-capa-migration-testing
    priority: 150
  - kind: configMap
    name: atlastest-observability-bundle-logging-extraconfig
    namespace: org-capa-migration-testing
    priority: 25
  - kind: configMap
    name: psp-removal-patch
    namespace: org-capa-migration-testing
    priority: 150
  install: {}
  kubeConfig:
    context:
      name: ""
    inCluster: true
    secret:
      name: ""
      namespace: ""
  name: observability-bundle
  namespace: org-capa-migration-testing
  namespaceConfig: {}
  rollback: {}
  uninstall: {}
  upgrade: {}
  userConfig:
    configMap:
      name: ""
      namespace: ""
    secret:
      name: ""
      namespace: ""
  version: 1.2.1
```

**Comment by ljakimczuk** [comment]
Hey @QuentinBisson. @nce who dealt with migration is on vacations, but according to my knowledge the migration of default apps is no on us. If I get it right, the Observability Bundle, as part of the Default Apps app, should get configured by the [CAPI migration CLI](https://github.com/giantswarm/capi-migration-cli/blob/main/pkg/migrator/capi_app.go#L35).

**Comment by QuentinBisson** [comment]
Loki migration works fine but I could not test user values. I will run it tomorrow.

User-values for default apps have been successfully migrated. Once loki test have been run, then all that;s left is to release a new Keda app version to support kubernetes 1.25 and add irsa support to fluent-logshipping-app

**Comment by T-Kukawka** [comment]
I have made adjustments in the tracking ticket as well as the teams tickets regarding the CAPA and migration testing instructions.

TL;DR: Testing of CAPA/Migration is moved from `gazelle` to `grizzly`

Initially `gazelle` has been chosen to test the CAPA migration as it is a Production MC, meaning most stable one. However this has resulted in unforeseen pages towards kaas-cloud oncall that we would like to limit.

We do recognise the pages and also actively work on testing, hence such pages are just a distraction away from the operations clusters that most of the teams have migrated the GS production workloads on.

Taking all the facts into consideration we have decided that it would be best to move the testing to `grizzly` which is stable-testing installation. Installation is primarily running e2e test and is treated as stable (no changes on the MCs).
Thanks for understanding and let us know if something is not working

**Comment by QuentinBisson** [comment]
All our apps have been tested. Now we need to close https://github.com/giantswarm/roadmap/issues/3249 and https://github.com/giantswarm/giantswarm/issues/29861 and we are done

**Comment by QuentinBisson** [comment]
Prometheus-operator with a PV and changed namespace have been tested
Loki with s3 backed storage have been tested

**Comment by QuentinBisson** [comment]
All we have left is about keda

**Comment by QuentinBisson** [comment]
So Keda also supports up to 1.25, let's discuss when we need 1.26 support
