### ISSUE TITLE
SLA reporting per SPOF component

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3228]
## User Story

- As a customer,  I want to be able to see the availability of the important kubernetes components and check if they are respecting the agreed SLAs.

## Dependencies

- [x] SLA reporting dashboard is available - https://github.com/giantswarm/giantswarm/issues/22643

## Tasks

```[tasklist]
### Team cabbage
- [ ] https://github.com/giantswarm/roadmap/issues/3229
- [ ] https://github.com/giantswarm/roadmap/issues/3230
- [ ] https://github.com/giantswarm/roadmap/issues/3231
```

cc @LolloneS I'm adding this to both teddyfriends and cabbage board as I think the dashboard is mostly missing cabbage related components now but maybe you have others in mind that we need to take care

**Comment by QuentinBisson** [comment]
cc @weatherhog I'm adding that to your board but I'll create stories out of this

**Comment by LolloneS** [comment]
I think the three issues have been created, so now it's a matter of evaluating priority in the backlog and delivering. For context, we'd like to have this for the next adidas QBR, let's say in 1.5 months.

**Comment by Rotfuks** [comment]
No todos here anymore from Atlas side. Closing the issue for now, because the todos lie with the other teams. Feel free to open up follow up tickets if you have any further questions.
