### ISSUE TITLE
Kubernetes `v1.25`

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#3241]
## Epic

Upgrade all Giant Swarm clusters to Kubernetes v1.25.

```[tasklist]
- [ ] https://github.com/giantswarm/roadmap/issues/1994
- [ ] https://github.com/giantswarm/roadmap/issues/2925
- [ ] https://github.com/giantswarm/roadmap/issues/2970
- [ ] https://github.com/giantswarm/roadmap/issues/1344
- [ ] https://github.com/giantswarm/roadmap/issues/3144
- [ ] https://github.com/giantswarm/roadmap/issues/2716
- [ ] https://github.com/giantswarm/giantswarm/issues/29944
- [ ] https://github.com/giantswarm/giantswarm/issues/28607
- [ ] https://github.com/giantswarm/giantswarm/issues/29808
```

### Status

| Provider | WC support | MC  support  | MC-Bootstrap support |     MC&WC Migration |
|----------|-------------|--------------| ---------------------- | ------------------|
| CAPZ      |      DONE      |        DONE      |    DONE    |  DONE    |
| CAPVCD      |      DONE       |         DONE       |    DONE     |     DONE     |
| CAPV      |      DONE      |         DONE       |    DONE     |     DONE     |
| CAPA      |      DONE      |         IN PROGRESS       |    DONE     |     IN PROGRESS     |
| AWS Vintage      |      IN PROGRESS      |        NOT STARTED       |    N/A     |    NOT STARTED     |

**Comment by JosephSalisbury** [comment]
@alex-dabija we should be doable now with the REST API being removed on Vodafone MCs

**Comment by alex-dabija** [comment]
> @alex-dabija we should be doable now with the REST API being removed on remaining customer MCs

There's just one MC which needs to be upgraded to Kubernetes v1.25.
