### ISSUE TITLE
CAPA China: mc-bootstrap work

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3251]
## User Story

- As a CAPA China consumer i want to have a systematic and automatic Management Clusters creation in the AWS China environment by running the mc-bootstrap

## Acceptance Criteria

- [x] mc-boostrap script creates china MC successfully

## Dependencies (optional)

- [x] https://github.com/giantswarm/roadmap/issues/3257
- [x] https://github.com/giantswarm/giantswarm/issues/30131

## Tasks (optional)

Work need for mc-bootstrap to enable CAPA China:

- [x] adjust deployed catalogs  generated for CMC repo for China to override the default registry
- [x] set config value for `registry.domains=giantswarm-registry.cn-shanghai.cr.aliyuncs.com` and `registry.mirrors: []`  in create config branch script
- [x] aws-cluster-role-identity default needs `aws-cn` in ARN for china regions
- [x] any app deployed to MC via mc bootstrap must also have configured china image registry 
  - ./scripts/create-kyverno.sh, ./scripts/setup-capi.sh, ./scripts/deploy-cert-manager-app.sh, ./scripts/capa/deploy-capa-iam-operator-app.sh, ./scripts/capa/deploy-irsa-operator-app.sh, ./scripts/setup-etcd-certs-secret.sh,  ./scripts/install-giantswarm-crds.sh, ./scripts/setup-app-chart-operator.sh, ./scripts/install-vpa-crds.sh,  be careful that many different repos uses differetn values
- [x] setup-cmc.sh resulting flux needs proper china registry - flux-system did not had it, but (BUT WHAT)

## Implementation details

- work started at: https://github.com/giantswarm/mc-bootstrap/pull/798
- implemetation info to be filled by engineer

**Comment by calvix** [comment]
done
