### ISSUE TITLE
Automated testing of bundle apps

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3270]
- [ ] Bundle apps can get tested both standalone (via https://github.com/giantswarm/roadmap/issues/3271) and as part of a bundle.
- [ ] Bundle tests live in the bundle repo (this is the first point of integration and also how we deploy for customers).
- [ ] A command on the app repo PR should be able to automatically bump the app version in the bundle and run bundle tests.

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3340
- [ ] Trigger apps on bundle repo: same structure as app testing; can get triggered by a PR
```

**Comment by yulianedyalkova** [comment]
Current bundle repos and codeowners:
- https://github.com/giantswarm/security-bundle -> Shield
- https://github.com/giantswarm/service-mesh-bundle -> Cabbage
- https://github.com/giantswarm/auth-bundle -> BigMac
- https://github.com/giantswarm/karpenter-bundle -> Phoenix
- https://github.com/giantswarm/observability-bundle -> Atlas
- https://github.com/giantswarm/external-dns-bundle -> Phoenix
