### ISSUE TITLE
Migrate Apps functionality in Happa to Management API

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#328]
Towards ***https://github.com/giantswarm/roadmap/issues/310 Let web UI communicate directly with the Management API***

### Description

- All existing functionality in Happa has to be moved to Management API
- ~All existing functionality in `gsctl` has to be moved to `kubectl gs`~
- Remove rest API after replacing all existing functionality in rest API with Management API (only when all customers are using SSO, tracked here - giantswarm/giantswarm#16250)

### TODO

- [x] Migrate all functionality in Happa to Management API
  - [x] Apps tab in cluster details (https://github.com/giantswarm/happa/pull/2417, https://github.com/giantswarm/happa/pull/2421)
    - [x] Listing apps
  - [x] Apps page (https://github.com/giantswarm/happa/pull/2441)
    - [x] Listing app catalogs
    - [x] Listing apps in all catalogs
  - [x] App details page (https://github.com/giantswarm/happa/pull/2454)
    - [x] Displaying app details (:
  - [x] Installing an app (https://github.com/giantswarm/happa/pull/2413)
    - [x] Creating ConfigMaps
    - [x] Creating Secrets
    - [x] Creating apps
    - [x] Fetching catalog entries via MAPI
  - [x] Cluster getting started guide and cluster detail ingress tab (https://github.com/giantswarm/happa/pull/2425)
    - [x] Install ingress app
  - [x] Configuring an app (https://github.com/giantswarm/happa/pull/2416)
    - [x] Changing the name/namespace
    - [x] Changing the version
    - [x] Updating the ConfigMap/Secret
    - [x] Deleting an app
  - [x] Don't execute REST API app-specific requests (https://github.com/giantswarm/happa/pull/2456)

**Comment by snizhana-dynnyk** [comment]
FYI @giantswarm/team-batman @cokiengchiara we are starting with the migration of Apps-related functionality to Management API.
Please make sure you are not adding any new functionality to rest API.

After migration we will remove the rest API so we need to make sure that nobody from customers is using rest API endpoints to work with apps. Could you please help with this?

Of course we won’t start with removing rest API until all customers have SSO which is tracked here - ***https://github.com/giantswarm/giantswarm/issues/16250 Get all customers to use SSO in Happa***

**Comment by axbarsan** [comment]
`gsctl` doesn't have any app-related functionality, I cut that off the list.
Also, can the `kubectl gs` app-related functionality be tracked in a separate issue? It's unrelated to `happa` or the REST API.

**Comment by snizhana-dynnyk** [comment]
sure, makes sense

**Comment by QuentinBisson** [comment]
@snizhana-dynnyk Do we have an ETA for the sso feature? I will check with orange so we can configure it

**Comment by axbarsan** [comment]
This is done ✅
