### ISSUE TITLE
Publish minimal default catalog for customer Backstage instances

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3291]
Part of

- https://github.com/giantswarm/giantswarm/issues/29552

One important building block for Backstage provided to customers is the catalog. The goal of this issue is to provide a common base catalog that can be published to all customers.

Roughly, the catalog should contain

- All apps we publish
- Additional open source software components by Giant Swarm that may be relevant to customers
- Team information
- Team member (user) information

We must decide whether the catalog data can be publicly accessible. If yes, this could help keep configuration simple. However, if required, the catalog should be pulled from a non-public place, using authentication.

The catalog data could also be modular and provided either publicly or privately, based on the sensitivity of the content.
```[tasklist]
### Tasks
- [x] Enhance backstage-catalog-importer to export customer catalogs
- [x] Decide how to publish and inject users into catalogs
- [x] Create automation for publishing the catalogs
```

**Comment by marians** [comment]
## Some aftermath

- All apps should have an owner team annotation
- All apps should have the "Home" URL pointing to our Github repository, not upstream

**Comment by marians** [comment]
@gusevda I just checked our internal users catalog https://github.com/giantswarm/github/blob/main/catalog/users.yaml and found that it indeed contains email adresses. Do you know whether they are required for authentication/authorization? Could access work without them?

**Comment by marians** [comment]
Found more things to improve:

- apps should have kubernetes annotations so related resources can be found (if possible)

**Comment by marians** [comment]
Done
