### ISSUE TITLE
Publish reference documentation on Kubernetes resource labels and annotations

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3295]
## User story

_As an engineer working with Kubernetes resources in Giant Swarm clusters, I want to understand why a label exists on a resource and what effect it has._

_As an engineer creating charts for deployment in a Giant Swarm cluster, I want to know which labels resources are expected to have and why, and which values these should have._

## Details

I propose creation of a single reference page where all labels we care about can be found. For each label, a description should be given. If possible, a link to further information should be added, pointing to the authoritative source for this item.

The page should be structured by label namespace (prefix).

For annotations, a very similar but separate page could be published.

This should be part of our reference docs at docs.giantswarm.io.

## Status quo

Mistakes are being made already. Some examples:

- https://github.com/giantswarm/giantswarm/issues/22473
- `app.giantswarm.io/*` was changed to `application.giantswarm.io/*`, but the former is still more common.
- https://github.com/giantswarm/giantswarm/issues/30178
- While many resources have `application.giantswarm.io/team`, some have [`app.giantswarm.io/team`](https://github.com/search?q=org%3Agiantswarm%20%22app.giantswarm.io%2Fteam%22&type=code)
- One app uses [`app.kubernetes.io/app`](https://github.com/search?q=org%3Agiantswarm+%22app.kubernetes.io%2Fapp%22&type=code), which is not documented upstream

## Material we have

Previously we have gathered some info in this page:

https://github.com/giantswarm/fmt/blob/main/kubernetes/annotations_and_labels.md

Also we maintain a library https://github.com/giantswarm/k8smetadata

## Tasks

- [x] Create labels and annotations stub pages in docs
- [ ] Collect data about labels in use, focused on CAPI
- [ ] Discuss whether we can consolidate the source of truth and remove [the fmt page](https://github.com/giantswarm/fmt/blob/main/kubernetes/annotations_and_labels.md)
- [ ] Promote knowledge about this effort in KaaS and Platform area, discuss how maintenance can work

**Comment by pipo02mix** [comment]
I really like the idea. It will perfectly fit in new `reference` doc section :)

**Comment by marians** [comment]
We have discussed this topic in [SIG Dev on April 4](https://docs.google.com/document/d/1KF0XNrEOXOiLw8tJcapiFRgPWLpIQWjDaA5gn-GG2yI/edit#heading=h.um28gepqurkp).

I'm going to work on a suggestion how we can make the k8smetadata library the source of the generated documentation.

We may need a custom tag format, or structured comments, so that we can capture structured data regarding the label "consumers".

**Comment by marians** [comment]
We have documentation for labels and annotations meanwhile.
