### ISSUE TITLE
Design Helm values for App CRs in cluster and cluster-aws

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3299]
### Motivation
Now that we want to get rid of the default-apps-aws we have to mix helm release resources and App CRs the cluster and cluster-aws chart. That means that we have to handle helm values there as well.

### Todo

- [x] Investigate how we can handle helm values for App CRs in cluster chart
- [ ] Investigate how we can handle helm values for App CRs in cluster-aws chart
  - Check with team-phoenix for the solution 
  - How will this change effect the automated testing (check with tinkerers)
- [ ] Document the design decision / process in cluster chart / cluster-aws chart

### Outcome 
- We know how to handle helm values in the cluster chart and cluster-aws chart and have nothing blocking us migrating all resources from default-apps-aws.
