### ISSUE TITLE
Migrate apps from default-apps-aws to cluster-aws chart

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3300]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [ ] Move all relevant, provider specific apps from default-apps-aws into the cluster-aws chart
- [ ] Prepare the tests for this change - the change might/will be a breaking change for the test environment
- [ ] Remove all migrated apps from default-apps-aws so that they are only used from cluster-aws chart
- [ ] Clearify with Team Phoenix how to roll out the change on all CAPA Installations

### Outcome
- The complexity of where and how apps are managed is reduced since we now have all provider specific apps in just the cluster-aws chart

**Comment by Gacko** [comment]
Closing this as we made it part of the "provider-independent apps in `cluster-aws`" PR, so this will get merged and releases together with the provider-independent part.
