### ISSUE TITLE
Deploy grafana-agent for PrometheusRules and monitor it

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3301]
The grafana agent on the MC used to send prometheus rules to mimir was deployed by hand. Let's deploy it via a collection and make sure we deploy it as a deployment instead of a daemonset to reduce usage
```[tasklist]
### Tasks
- [x] Deploy Grafana-Agent to send PormetheusRules to Mimir ruler
- [ ] https://github.com/giantswarm/giantswarm/issues/30281
- [x] Add rule to monitor PrometheusRules are sent to mimir ruler
```

**Comment by marieroque** [comment]
- Adding mimir-grafana-agent to `shared-config` repo
- Push mimir-grafana-agent to `CAPA collection` in grafana-agent repo

**Comment by QuentinBisson** [comment]
Let's deploy the app in the prometheus rules repo

**Comment by marieroque** [comment]
Regarding a rules to check PrometheusRules are properly sent to mimir, we have those metrics available:
https://grafana.com/docs/agent/latest/flow/reference/components/mimir.rules.kubernetes/#debug-metrics

We can make a rules based on `mimir_rules_events_failed_total` > 0 for a period.
WDYT @giantswarm/team-atlas ?

**Comment by QuentinBisson** [comment]
Makes sense yes but do we have a grafana agent down alert as well? And I think if rules fail for 1h during business hours we can page. WDYT?

Aldo have you checked the mixins https://github.com/grafana/agent/tree/main/operations/agent-flow-mixin ?

**Comment by marieroque** [comment]
Wait monday to release prometheus-rules...

I open a new ticket to handle alert and dashboard

**Comment by QuentinBisson** [comment]
Why do we need a separate issue though? This makes it really hard to track what happened, especially as it is not related to the epic. I would rather we rename the issue and add the alert in as a subtack of this issue

**Comment by marieroque** [comment]
We currently don't have any rules on `grafana-agent` down.
We should have one for the agent responsible to scrape k8s events.
Maybe it should be addressed in an other ticket, right ?

**Comment by QuentinBisson** [comment]
I would think so yes but you can still add the alert today :)
