### ISSUE TITLE
Review silence for CiliumEndpointRegenerationLatencyTooHigh

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3310]
### Motivation
Part of https://github.com/giantswarm/giantswarm/issues/30028. Currently we have `CiliumEndpointRegenerationLatencyTooHigh` [silenced](https://github.com/giantswarm/sloth-rules/blob/456600195ff6347f4b9d2046750df3109cfa63d8/helm/sloth-rules/templates/kaas-phoenix-cni-latency-endpoint.yaml). Let's see how we can improve the state of the metric so we can remove the silence.
...

### TODO

- [ ] Investigate why the silence got added in the first place and if the issue is still present
- [ ] Review if we can improve or replace the alert with something more useful
- [ ] Remove the silence
