### ISSUE TITLE
Investigate Requirements for Patch/Minor/Major

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3313]
### Motivation
As discussed in our initial brainstorming session we need to find a clear guideline to define when a change is a Patch/Minor/Major release. For this we need to cover cases like what is a breaking change - like is rolling a node already breaking, because it breaks single node CPs? 

### Todo

- [ ] Create some initial draft for the different use cases we need to cover
- [ ] Create a meeting to discuss the different use cases
- [ ] Derive some guideline rules that can be transformed into a checklist used when versioning changes

### Outcome
- We have a clear guideline what change is which versioning level and some use cases to back it up.

**Comment by yulianedyalkova** [comment]
Document is published [here](https://intranet.giantswarm.io/docs/product/releases/capi/capi-versioning-scope/).
