### ISSUE TITLE
Add additionalTags to cluster Azure

### ISSUE THREAD

**Issue by vxav** [giantswarm/roadmap#3329]
## User Story

As a customer would like to add additional Azure tags to the GS created resources, such that i can easier track the costs as well as the resources deployed in the Azure Environment.

## Acceptance Criteria

- [x] If the Additional Tags are specified in the `cluster-azure` - they should be populated in Azure resources
- [ ] Any change or removal of the tags should result in the updates on the cloud provider side
- [x] add default tag same as in CAPA `giantswarm-cluster: {{ include "resource.default.name" $ }}`

## Tasks (optional)

- [x] check existing feature for Additional tags in the CAPZ provider https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_azuremachines.yaml#L9
- [x] match the feature with the CAPA implementation that is already present

## Implementation details

- Implementation info to be added by engineer

**Comment by T-Kukawka** [comment]
can be related: https://github.com/giantswarm/giantswarm/issues/29080

**Comment by whites11** [comment]
with cluster-azure 0.4.0 it is possible to set `providerSpecific.additionalResourceTags` field and those tags will be added to the resources.

TBD: check if changing of such tags is supported.

**Comment by whites11** [comment]
The following resources got the updated tag after it was changed:

- control plane VMs
- node VMs
- resource group

**Comment by T-Kukawka** [comment]
Provided feedback to customer on the state of the feature

**Comment by T-Kukawka** [comment]
Customer is fine with tags on the resources that are available in CAPZ

**Comment by T-Kukawka** [comment]
changes implemented in https://github.com/giantswarm/cluster-azure/blob/main/CHANGELOG.md#050---2024-03-26
