### ISSUE TITLE
kubectl-gs support on Windows

### ISSUE THREAD

**Issue by brinker211** [giantswarm/roadmap#333]
**Is your feature request related to a problem? Please describe.**

As a user on windows, there is not a clean way to get CRD schemas into IDE.

**Describe the solution you'd like**

Build client for Windows.

**Describe alternatives you've considered**

Can use manually steps copying certs and needed config from WSL kube.config but need to do this everytime login expires. 

## Tasks

- [ ] Update CLI build automation to create signed Windows binaries
- [ ] Include Windows binary in Krew updates
- [ ] Add Windows to our [installation instructions](https://docs.giantswarm.io/ui-api/kubectl-gs/installation/)

**Comment by marians** [comment]
@brinker211 We have a test version of kubectl-gs for Windows. See [my comment here](https://github.com/giantswarm/kubectl-gs/pull/352#issuecomment-843279890) for details. Please point any interested Windows users to it and also invite them to share their feedback.

*Note:* the binary is not signed. I'd like to know in particular whether this poses any problems to users.

**Comment by brinker211** [comment]
Hi @marians I let the Windows user know last week who will be giving a try and we will report feedback :)

**Comment by brinker211** [comment]
+1 for this ticket as another team of primarily windows users are looking to use it on windows.

**Comment by mteubner** [comment]
+1 for this ticket as another team of primarily windows users are looking to use it on windows.

**Comment by marians** [comment]
Update: our latest release https://github.com/giantswarm/kubectl-gs/releases/tag/v2.7.5 includes a Windows binary. Please try at your own risk.

We don't provide installation instructions yet. Also managing via Krew is not supported yet on Windows.

**Comment by marians** [comment]
After 2.7.5 included a windows binary that was not signed, we removed the release again.

With [2.7.10](https://github.com/giantswarm/kubectl-gs/releases/tag/v2.7.10) we now have a first Windows build of kubbectl-gs. Please try it out and give feedback here.

FYI: Installing via Krew will be possible once https://github.com/kubernetes-sigs/krew-index/pull/2197 is merged.
