### ISSUE TITLE
API Server: Feature Gate configuration.

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3333]
## User Story

- As a cluster operator, I would like configure Kubernetes feature gates so that I can enable Kubernetes alpha or beta features that are disabled by default.

## Acceptance Criteria

- [ ] Given I need a specific Kubernetes feature that is behind a feature gate that is disabled by default, when I create a cluster, then I should be able to enable the desired feature gate for my cluster.

## Tasks

- [ ] Add Helm values for enabling API server feature gates
- [ ] Add Helm values for enabling controller manager feature gates

**Comment by nprokopic** [comment]
Currently feature gates are configurable only for the provider integration here in the cluster chart:

```yaml
internal:
  providerIntegration:
    controlPlane:
      kubeadmConfig:
        clusterConfiguration:
          apiServer:
            featureGates: []
```

The above field can be set by cluster-aws, which means that it is then used by all clusters by default.

Now we should enable setting specific feature gates for specific clusters, so that cluster operators can enable customer feature gates they need for their use cases.

We should add the following new Helm values to the cluster chart:

```yaml
internal:
  advancedConfiguration:
    controlPlane:
      apiServer:
        featureGates: []
      controllerManager:
        featureGates: []
```

Features gates specified per-cluster in `.Values.internal.advancedConfiguration` here should either:
- override provider-wide feature gates from `.Values.internal.providerIntegration`, or
- it should not be allowed to override provider-wide feature gates from `.Values.internal.providerIntegration` (if some providers really need some feature gates to be enabled/disabled for whatever reason).

The first option above is probably simpler and good enough for now, especially if we add it to `.Values.internal.advancedConfiguration`.

(Ideally we add a new property for feature gates in `.Values.internal.providerIntegration` where we can specify if a feature gate can be overridden or not, but we can do that later.)

**Comment by QuantumEnigmaa** [comment]
This is linked to the following issue : https://github.com/giantswarm/giantswarm/issues/29575
