### ISSUE TITLE
Mimir alerting pipeline

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3337]
To be able to provide alerting to our customers, we need ot start to use Mimir's alertmanager

Blocked by 

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/30293
- [ ] https://github.com/giantswarm/giantswarm/issues/28269
- [ ] https://github.com/giantswarm/giantswarm/issues/28273
- [ ] https://github.com/giantswarm/giantswarm/issues/27603
- [ ] https://github.com/giantswarm/roadmap/issues/1964
- [ ] https://github.com/giantswarm/roadmap/issues/3091
```
