### ISSUE TITLE
Expand apptest-framework to be able to deal with bundles

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3340]
Related: https://github.com/giantswarm/giantswarm/issues/30638

(Tasks taken from [comment below](https://github.com/giantswarm/roadmap/issues/3340#issuecomment-2076630136))

```[tasklist]
### Tasks
- [ ] Introduce a new `InBundleApp` function to `suite`
- [ ] Include some hardcoded logic that, based on which bundle is selected, decides how to override the sub-app version. See the [above comment](https://github.com/giantswarm/roadmap/issues/3340#issuecomment-2069049824) for the possible variations that need to be handled.
- [ ] If the selected bundle App is also a default app we'd also need the changes from https://github.com/giantswarm/roadmap/issues/3095 implemented first
```

**Comment by AverageMarcus** [comment]
Some issues discovered already:

* The naming of the map keys in the bundle app values is inconsistent. For example, [security-bundle](https://github.com/giantswarm/security-bundle/blob/main/helm/security-bundle/values.yaml) and [observability-bundle](https://github.com/giantswarm/observability-bundle/blob/main/helm/observability-bundle/values.yaml) use **camel case names for the apps** but [service-mesh-bundle](https://github.com/giantswarm/service-mesh-bundle/blob/main/helm/service-mesh-bundle/values.yaml) and [auth-bundle](https://github.com/giantswarm/auth-bundle/blob/main/helm/auth-bundle/values.yaml) make use of the **chart name as-is with the hyphens included**. But, to make things even worse, [karpenter-bundle](https://github.com/giantswarm/karpenter-bundle/blob/main/helm/karpenter-bundle/templates/apps.yaml) and [external-dns-bundle](https://github.com/giantswarm/external-dns-bundle/blob/main/helm/external-dns-bundle/templates/apps.yaml) don't follow the same approach as the others and don't have a `.Values.apps` map to work with. 😞 For this to work as is we would need to have the App tests know what values property to override which then creates a hard dependency between the two and means that refactor to the values format (e.g. to harmonize across the bundles) would end up breaking the tests.
* Things get complicated when it comes to bundles that are part of default-apps (e.g. security-bundle and observability-bundle) as those are already installed before the apptest suites are run. This means that we can only ever do tests that upgrade from the previous version of the app and not clean installs of the app with the version being tested. (This is currently the case and might change based on what comes out of https://github.com/giantswarm/roadmap/issues/3095)

---

Some thoughts on roughly how to approach writing in-bundle App tests (assuming we can solve the above):

* Introducing a new property to `Suite` to define the bundle that the App is part of (e.g. `InBundleApp(bundleName string)`
* We might need to first uninstall the bundle if it already exists. Not sure how this might negatively effect things though. Removing CRDs will likely cause problems for other apps.
* Instead of installing the App we update the values of the bundle app to set the version and catalog of the App being tested. 
* Similarly for upgrade tests we update the value ConfigMap of the bundle instead of the version of the App. (We might need to manually kick off the reconciliation loop of the bundle app with a dummy label or similar to speed things up.)

**Comment by AverageMarcus** [comment]
Changes to make based on proposal here: https://github.com/giantswarm/giantswarm/issues/30638

- [ ] Introduce a new `InBundleApp` function to `suite`
- [ ] Include some hardcoded logic that, based on which bundle is selected, decides how to override the sub-app version. See the [above comment](https://github.com/giantswarm/roadmap/issues/3340#issuecomment-2069049824) for the possible variations that need to be handled.
- [ ] If the selected bundle App is also a default app we'd also need the changes from https://github.com/giantswarm/roadmap/issues/3095 implemented first
