### ISSUE TITLE
Add a log receiver on CAPI MCs to be able to receive teleport audit logs and send them to Loki and customers SIEMs

### ISSUE THREAD

**Issue by QuentinBisson** [giantswarm/roadmap#3343]
Towards https://github.com/giantswarm/roadmap/issues/3250

## Motivation

As Giant Swarm employees will not be able to ssh onto nodes and clusters using bastions hosts but teleport, we need to be able to collect and store the teleport logs in Loki and potentiall in customer's SIEMs.

To that end and after some discussions with @giantswarm/team-bigmac https://github.com/giantswarm/roadmap/issues/3250#issuecomment-2007447350 we decided that we would add a fluent-bit log receiver on the Management clusters that would receive the teleport logs and send the data wheever is needed (loki and SIEM if needed)

## Acceptance Criteria

- [ ] Given input logs getting received by teleport, the logs are ingested in Loki

## Dependencies
```[tasklist]
### Dependencies
- [ ] https://github.com/giantswarm/giantswarm/issues/29312 - I would like if we could do that before to know if would not prefer to deprecate the fluent-logshipping-app which is getter harder and harder to maintain in favor of something like the logging-operator
```

```[tasklist]
### Tasks
- [ ] Deploy a fluent-bit receiver
- [ ] Send logs to Loki
```

**Comment by Rotfuks** [comment]
From @TheoBrigitte  in the epic level: 

Regarding Teleport audit events, there is a way to export events from our Teleport cloud and ship then into Fluentd (or probably any other JSON compatible log ingester ... Alloy 👀), but exported events are from all installations and I haven't found a way to filter events from the teleport side.

 I did follow the Export Events with Fluentd guide, and used the identity file from kg get secret abc-identity-output -oyaml|yq -r .data.identity|base64 -d> identity.
We use Teleport cloud, meaning our Auth service is hosted at teleport.giantswarm.io, so events are produced at the cloud level. The teleport-event-handler would then connect to the Auth service and retrieve the events it contains.

Useful links:

https://goteleport.com/docs/admin-guides/management/export-audit-events/fluentd/
https://goteleport.com/docs/reference/monitoring/audit/#events
https://goteleport.com/docs/reference/access-controls/roles/#filter-fields

**Comment by Rotfuks** [comment]
- We can already receive teleport audit logs with the log receiver we created, we just need to configure it
- We can already send data to any customer SIEM that supports OLTP 

So in the scope of this ticket what's missing is: 

- [ ] Ingest Teleport audit logs
- Check with spyros he can help here :)

**Comment by TheoBrigitte** [comment]
I have some concerns towards security regarding this, as the current solution would expose all Audit Events in our Teleport account to every installation, meaning that any customer could potentially get access to any other customer's Audit Events. The filtering we can do in fluentd, alloy, or whatever we use would happen to late and could easily be worked around to get access to all Audit Events.
I opened an issue at Teleport to see if they have an idea on this topic: https://github.com/gravitational/teleport/discussions/49582

**Comment by QuentinBisson** [comment]
@TheoBrigitte I think there's a confusion here. The goal of this story is to enable the log receiving endpoint, but the export to the correct installation (filtering of correct logs) will be done in the teleport cluster by @giantswarm/team-shield . We only need to provide a secure endpoint for access from the teleport cluster. This will most likely require cooperation from @ssyno as we should be able to restrict tihs ingress only to the teleport VNET?

**Comment by TheoBrigitte** [comment]
The teleport event handler basically spits out JSON, anything that understand JSON should be able to ingest the data coming from the event handler.

I see this a bit differently, shield sets up the teleport event handler which then talk to "something" atlas provide which might be Alloy or Fluentd we have to verify this. So this would be

teleport event handler -> alloy or fluentd -> loki

I think the alloy/fluentd config is then on us (atlas).

**Comment by QuentinBisson** [comment]
Yes the event handler would communicate with the observability gateway, but the event handler does not support loki yet only fluentd and it should run on the teleport cluster to filter per installation

**Comment by ssyno** [comment]
I think that we can skip the step of the `teleport-event-handler`, we should be able to scrape and ship logs directly from `teleport-cluster` with alloy or `promtail` and ship them to the right `loki`

**Comment by QuentinBisson** [comment]
Do you have the handler running on the teleport cluster yet?

**Comment by ssyno** [comment]
nope, I think we should try doing it without the event-handler

**Comment by QuentinBisson** [comment]
Do you want us to have a quick meet on thursday to figure out what we can do?

**Comment by QuentinBisson** [comment]
@ssyno and I had a talk. We plan to:
- Shield will output audit events / logs in a file on the teleport cluster
- Shield will create a teleport VNET to open connection from teleport cluster to all observability gateways (certificate authentication is managed by teleport so we do not need api keys on loki)
- Atlas will deploy alloy on the teleport cluster through terraform
  - Alloy will filter out logs per installation and send the logs to the endpoints based on the log content

Open questions:
- How can we handle alloy config dynamically (loki.write section per MC). Do we add a proxy? Do we have a static list of MCs in the teleport cluster to use? What is the source of MCs in the teleport cluster?
- ~How can we access the teleport cluster?~ Yes we can
- How do we handle monitoring of this?

Investigation:
- Let's try to run this on golem (have audit events in a file and vnet) with a manual alloy deployment

@giantswarm/team-shield and @giantswarm/team-atlas what are your thoughts on this solution?

**Comment by stone-z** [comment]
This sounds good to me 👍 

It would be nice to dogfood and use the same route that customers use (including ingress), but the vnet approach also makes sense and would handle private environments as well, so no blocker from me.

Some suggestions / considerations:
- We must have very high confidence that we are sending only the correct logs to each MC. Ideally there are some tests for that.
- The log volume for only teleport logs is likely not that high, but each service that runs through the VNET adds to the demand on those components. This would be a good time to double check that there is observability of the performance to make sure teleport or MC components don't fall over and lock us out.

**Comment by QuentinBisson** [comment]
We were mostly concerned about private MCs when we talked about the vent and i'm not sure we could provide oidc for the log shipper without spire anyway :)
I'm considering whether our agent should not also use the vnet route but that's a whole other discussion

I'm totally aligned with your other points

**Comment by ssyno** [comment]
I did some research the previous days:
Audit logs are there inside the Teleport-auth pods, in this format:
```
2025-01-07T14:55:32Z INFO [AUDIT]     kube.request addr.remote:10.0.3.115:43858 cluster_name:teleport.giantswarm.io code:T3009I ei:0 event:kube.request kubernetes_cluster:golem kubernetes_groups:[system:masters system:authenticated] kubernetes_users:[system:serviceaccount:default:automation] login:ssyno namespace:default proto:kube request_path:/apis/apiextensions.k8s.io/v1/customresourcedefinitions resource_api_group:apiextensions.k8s.io/v1 resource_kind:customresourcedefinitions response_code:200 server_hostname:teleport.giantswarm.io server_id:6ea64372-dd29-4018-b61b-2c343ee714d6 server_version:16.1.7 sid: time:2025-01-07T14:55:32.936Z uid:3e4f8dee-f5ed-463d-a9d7-a2d2c05c5efc user:ssyno user_kind:1 verb:GET events/emitter.go:288
```
I have enabled **Teleport VNet** for `loki-write` in Golem at `loki-golem.teleport.giantswarm.io` 
https://github.com/giantswarm/giantswarm-management-clusters/commit/e8443989981bb69b58a05da7706cf345762dcd27

I think we are ready to move forward

**Comment by QuentinBisson** [comment]
Awesome so as long as we only restrict log collection to the teleport pods and filter based on the kubernetes cluster then we should be good to go :) I'll do some testing on the teleport cluster

**Comment by QuentinBisson** [comment]
I've been doing some testing with those values for alloy deployment on the teleport cluster:

```
networkPolicy:
  flavor: kubernetes
alloy:
  alloy:
    configMap:
      create: true
      content: |
        logging {
          level  = "debug"
          format = "logfmt"
        }
        discovery.kubernetes "kubernetes_pods" {
          role = "pod"
          selectors {
            role = "pod"
            label = "app.kubernetes.io/component=auth"
          }

          namespaces {
            names = ["teleport"]
          }
        }

        loki.source.kubernetes "kubernetes_pods" {
          targets    = discovery.kubernetes.kubernetes_pods.targets
          forward_to = [loki.process.tenant.receiver]
        }

        // We configure the giantswarm tenant
        loki.process "tenant" {
          stage.tenant {
            value = "giantswarm"
          }

          forward_to = [
            loki.write.loki.receiver,
            loki.echo.echo.receiver,
          ]
        }

        loki.echo "echo" {
        }

        loki.write "loki" {
          endpoint {
            url = "<redacted>"
          }

          external_labels = {
            cluster_id   = "teleport",
            installation = "none",
            job = "teleport",
            scrape_job = "teleport",
          }
        }
  controller:
    type: deployment
```

We do get the logs in stdout with the loki.echo receiver and alloy is supposedly sending the logs (seeing metrics and no errors in the logs) but the metrics are not received

@ssyno is doing some connectivity tests

**Comment by QuentinBisson** [comment]
VNET does not work without a sidecar,  @ssyno is coming up with a new plan 🚀

**Comment by ssyno** [comment]
> VNET does not work without a sidecar,  @ssyno is coming up with a new plan 🚀 

After discussing about it, in teleport slack they notified me that this is not supposed to be used for app connections the way it is built right now, they got this as an idea to implement it in the future.
My plan for now is to deploy a machineID deployment maybe tbot chart and create a sidecar in the alloy deployment that connects the pod to the VNet.

**Comment by ssyno** [comment]
I made all the things ready, it work locally, but now when I try to deploy it seems that I missed that the `tsh` binary is not able to use `vnet` option in linux 🤦

**Comment by QuentinBisson** [comment]
🍿 so we need a proxy per installation ?

**Comment by ssyno** [comment]
A sidecar container like this will be needed in the `alloy-exporter` pod then the logs will have to be shipped through it 
```
      - name: teleport-sidecar
        image: public.ecr.aws/gravitational/teleport-distroless-debug:16.4.13
        command: ["/busybox/sh", "-c"]
        args:
        - |
          mkdir -p /tmp/tsh && chmod 700 /tmp/tsh
          HOME=/tmp/tsh tsh login --proxy=teleport.giantswarm.io --identity=/etc/teleport/identity
          HOME=/tmp/tsh tsh proxy app --port=3100 loki-gateway-golem &
          while true; do sleep 30; done
        env:
        - name: HOME
          value: "/home/teleport"
        volumeMounts:
        - name: teleport-identity
          mountPath: /etc/teleport
          readOnly: true
        - name: tmp-dir
          mountPath: /tmp
        - name: tsh-home
          mountPath: /home/teleport

      volumes:
      - name: tsh-home
        emptyDir: {}
      - configMap:
          defaultMode: 420
          name: log-export-alloy
        name: config
      - emptyDir: {}
        name: alloy-tmp
      - name: teleport-identity
        secret:
          secretName: alloy-tbot-identity
      - name: tmp-dir
        emptyDir: {}

      serviceAccountName: log-export-alloy
```

**Comment by QuentinBisson** [comment]
@ssyno thanks for the work we're getting there :D 

```
networkPolicy:
  flavor: kubernetes
alloy:
  alloy:
    configMap:
      create: true
      content: |
        logging {
          level  = "debug"
          format = "logfmt"
        }
        discovery.kubernetes "kubernetes_pods" {
          role = "pod"
          selectors {
            role = "pod"
            label = "app.kubernetes.io/component=auth"
          }

          namespaces {
            names = ["teleport"]
          }
        }

        loki.source.kubernetes "kubernetes_pods" {
          targets    = discovery.kubernetes.kubernetes_pods.targets
          forward_to = [loki.process.tenant.receiver]
        }

        // We configure the giantswarm tenant
        loki.process "tenant" {
          stage.tenant {
            value = "giantswarm"
          }

          forward_to = [
            loki.write.loki.receiver,
          ]
        }

        loki.write "loki" {
          endpoint {
            url = "http://localhost:3100"
          }

          external_labels = {
            cluster_id   = "teleport",
            installation = "none",
            job = "teleport",
            scrape_job = "teleport",
          }
        }
  controller:
    type: deployment
    extraContainers:
      - name: teleport-sidecar
        image: public.ecr.aws/gravitational/teleport-distroless-debug:16.4.13
        command: ["/busybox/sh", "-c"]
        args:
        - |
          mkdir -p /tmp/tsh && chmod 700 /tmp/tsh
          HOME=/tmp/tsh tsh login --proxy=teleport.giantswarm.io --identity=/etc/teleport/identity
          HOME=/tmp/tsh tsh proxy app --port=3100 loki-gateway-golem &
          while true; do sleep 30; done
        env:
        - name: HOME
          value: "/home/teleport"
        volumeMounts:
        - name: teleport-home
          mountPath: /home/teleport
        - name: teleport-identity
          mountPath: /etc/teleport
          readOnly: true
        - name: teleport-tmp
          mountPath: /tmp
    volumes:
      # -- Extra volumes to be able to run the teleport sidecar
      extra:
      - name: alloy-tmp
        emptyDir: {}
      - name: teleport-home
        emptyDir: {}
      - name: teleport-identity
        secret:
          secretName: alloy-tbot-identity
      - name: teleport-tmp
        emptyDir: {}
```

Here is the current alloy config

But alloy complains about refused connections:

```
ts=2025-01-29T14:56:56.719648569Z level=warn msg="error sending batch, will retry" component_path=/ component_id=loki.write.loki component=client host=localhost:3100 status=-1 tenant=giantswarm error="Post \"http://localhost:3100\": dial tcp [::1]:3100: connect: connection refused"
ts=2025-01-29T14:58:15.682749338Z level=warn msg="error sending batch, will retry" component_path=/ component_id=loki.write.loki component=client host=localhost:3100 status=-1 tenant=giantswarm error="Post \"http://localhost:3100\": dial tcp [::1]:3100: connect: connection refused"
```

**Comment by QuentinBisson** [comment]
We now have golem logs on golem

![Image](https://github.com/user-attachments/assets/50e526c5-abdf-477a-a874-bea90d523d7d)

We need to figure out how to manage all instalaltions now but it's waiting till @ssyno is back from holiday :)

**Comment by ssyno** [comment]
In [this PR](https://github.com/giantswarm/teleport-fleet/pull/339) `terraform` scans all the existing bot-tokens(one for each cluster) and it deploys the required resourses(`alloy-app` with `teleport-proxy` & `tbot.yaml secret`) for each one of them.

To move forward and merge it:
- [ ] First of all we should clean up the teleport-bots directory from the not valid tokens(decommissioned clusters).
https://github.com/giantswarm/teleport-fleet/pull/344
- [ ] Then we have to enable Loki Teleport App to every CAPI MC.
https://github.com/giantswarm/adidas-management-clusters/pull/215
https://github.com/giantswarm/wepa-management-clusters/pull/63
https://github.com/giantswarm/vodafone-management-clusters/pull/119
https://github.com/giantswarm/straumann-management-clusters/pull/27
https://github.com/giantswarm/panamax-management-clusters/pull/182
https://github.com/giantswarm/flexshopper-management-clusters/pull/63
https://github.com/giantswarm/egger-management-clusters/pull/90
https://github.com/giantswarm/cyta-management-clusters/pull/72

**Comment by QuentinBisson** [comment]
@ssyno do you have any news on those app merging?

**Comment by ssyno** [comment]
> @ssyno do you have any news on those app merging?

I can merge them today, after hackathon end

**Comment by ssyno** [comment]
This is mostly done! We can close it once we verify logs are received in all Loki's

**Comment by ssyno** [comment]
I think yes, only documentation remains to be updated

**Comment by ssyno** [comment]
Closing this one, as its done, the documentation update is another [issue](https://github.com/giantswarm/giantswarm/issues/33246) already
