### ISSUE TITLE
Skip migration of k8s-initiator-app

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3346]
## User Story

As a cluster-admin i want to prevent the `k8s-initiator-app` to be migrated to CAPA clusters. The application should be running only on Vintage nodes and will be decomissioned together with the cluster. The migration CLI should skip the application configmap migration as well as the App CR itself, restricting it only to Vintage clusters, enabling the seemless experience during the migration and used features.

## Acceptance Criteria

- [ ] The configmap as well as App CR of the `k8s-initiator-app` is not migrated towards CAPA cluster in the CLI
- [ ] The application is still running on the Vintage nodes alongside CAPA

## Dependencies (optional)

- The migration of managed-applications is handled by following CLI: https://github.com/giantswarm/app-migration-cli/

## Tasks (optional)

- [ ] Adjust migration of the `k8s-initiator-app` in https://github.com/giantswarm/app-migration-cli/

## Implementation details

- implemetation info

**Comment by bdehri** [comment]
https://github.com/giantswarm/app-migration-cli/blob/40d59e3ecd760d6cde5713383fbe74336841bb74/pkg/apps/apps.go#L50
It is already implemented here
