### ISSUE TITLE
Kong Improvements

### ISSUE THREAD

**Issue by weatherhog** [giantswarm/roadmap#3351]
This Epic is the general overview for tasks around improving Kong

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/30377
- [ ] https://github.com/giantswarm/giantswarm/issues/30376
- [ ] https://github.com/giantswarm/giantswarm/issues/30378
- [ ] https://github.com/giantswarm/roadmap/issues/3231
- [ ] https://github.com/giantswarm/giantswarm/issues/30380
- [ ] https://github.com/giantswarm/giantswarm/issues/30382
- [ ] https://github.com/giantswarm/giantswarm/issues/30468
- [ ] https://github.com/giantswarm/giantswarm/issues/30620
- [ ] https://github.com/giantswarm/kong-app/pull/380
- [ ] https://github.com/giantswarm/giantswarm/issues/30546
- [ ] https://github.com/giantswarm/giantswarm/issues/29769
- [ ] https://github.com/giantswarm/giantswarm/issues/23691
- [ ] https://github.com/giantswarm/giantswarm/issues/30656
```

**Comment by ced0ps** [comment]
[Kong enterprise features that can be solved with open source projects](https://github.com/giantswarm/giantswarm/issues/30377) was prioritized due to  [QBR for Kong](https://github.com/giantswarm/giantswarm/issues/30394)

**Comment by weatherhog** [comment]
done
