### ISSUE TITLE
Make Kubernetes EOL info available via the Management API

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#336]
## User story

- _As an admin, I want to know when Kubernetes ends their support for a minor version used by Giant Swarm._

## Background

The Kubernetes project sets end of life (EOL) dates for each minor version. Once a minor version has passed the EOL date, no more patch releases are delivered for this version.

The [REST API](https://docs.giantswarm.io/api/#tag/info) makes Kubernetes EOL dates available via the info endpoint. Our web UI and gsctl display that information in the context of a workload cluster release. Example:

![image](https://user-images.githubusercontent.com/273727/117935311-e00aa580-b303-11eb-80a8-47e08a168b45.png)

With the move to the Management API and deprecation of the REST API, we need a new way to store and access this type of information.

### TODO
- [x] Expose k8s version EOL info from a common place and inject it into `happa` and `api`
- [x] Display k8s version info on MAPI features
- [x] Remove leftover happa `info` endpoint madness

**Comment by marians** [comment]
Part of this story should be to bring the EOL info to basically every place where we show the Kubernetes version of a release or a workload cluster.

**Comment by axbarsan** [comment]
All done ✅
