### ISSUE TITLE
Refactor cluster-azure Helm values to use global Helm values

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3371]
### Motivation

Towards https://github.com/giantswarm/roadmap/issues/3350

### TODO

```[tasklist]
- [ ] https://github.com/giantswarm/cluster-azure/pull/240
- [ ] https://github.com/giantswarm/cluster-azure/pull/241
- [ ] https://github.com/giantswarm/cluster-azure/pull/242
- [ ] https://github.com/giantswarm/cluster-azure/pull/243
- [ ] https://github.com/giantswarm/cluster-azure/pull/244
- [ ] https://github.com/giantswarm/cluster-azure/pull/245
- [ ] Make sure that all Helm values that are required in cluster chart are correctly added to cluster-azure Helm values.
- [ ] https://github.com/giantswarm/cluster-test-suites/pull/262
- [ ] Update kubectl-gs if needed.
- [ ] Update happa if needed.
- [ ] Update relevant public docs (component-specific docs, where applicaable, should be updated while working on the above tasks).
- [ ] Update all Giant Swarm CAPZ clusters to the new cluster-azure version (first MCs then WCs).
```

### Outcome

**For Customer**
- CAPZ workload clusters are configured with the new Helm values schema that is aligned with other providers and that is a stable long-term solution.
- cluster-azure is compatible with cluster chart Helm values, which will enable integration of cluster chart into cluster-azure (without affecting the customer), which will bring multiple new provider-independent features to CAPZ workload clusters.

**Internal**
- Team Phoenix can continue working on cluster-azure with Helm values that will be compatible with cluster chart.
- Team Turtles can integrate cluster chart into cluster-azure, without causing breaking changes to customers.
