### ISSUE TITLE
Refactor cluster-vsphere Helm values to use global Helm values

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3372]
### Motivation

Towards https://github.com/giantswarm/roadmap/issues/3350

### TODO

```[tasklist]
- [x] Move `.Values.metadata` to `.Values.global.metadata`.
- [x] Move `.Values.connectivity` to `.Values.global.connectivity`.
- [x] Move `.Values.baseDomain` to `.Values.global.connectivity.baseDomain`.
- [x] Move `.Values.controlPlane` (and other control plane properties) to `.Values.global.controlPlane`.
- [x] Move `.Values.nodePools` to `.Values.global.nodePools`.
- [x] Move remaining provider-specific Helm values to `.Values.global.providerSpecific`.
- [x] Make sure that all Helm values that are required in cluster chart are correctly added to cluster-vsphere Helm values.
- [x] Update cluster-vsphere e2e tests in cluster-test-suites.
- [x] Update kubectl-gs if needed.
- [x] Update happa if needed.
- [x] Update relevant public docs (component-specific docs, where applicable, should be updated while working on the above tasks).
- [x] Update all Giant Swarm CAPV clusters to the new cluster-vsphere version (first MCs then WCs).
```

### Outcome

**For Customer**
- CAPV workload clusters are configured with the new Helm values schema that is aligned with other providers and that is a stable long-term solution.
- cluster-vsphere is compatible with cluster chart Helm values, which will enable integration of cluster chart into cluster-vsphere (without affecting the customer), which will bring multiple new provider-independent features to CAPV workload clusters.

**Internal**
- Team Rocket can continue working on cluster-vsphere with Helm values that will be compatible with cluster chart.
- Team Turtles can integrate cluster chart into cluster-vsphere, without causing breaking changes to customers.

**Comment by vxav** [comment]
Not sure if that's relevant but FYI for vSphere, the schema had not been updated when all the providers were being aligned (by Rainbow I think?). Meaning we can't use `helm-values-gen` here so the values are updated by hand.
I'll try and take care of these

**Comment by glitchcrab** [comment]
vsphere mcs will need updating: https://github.com/giantswarm/giantswarm-management-clusters/pull/606

**Comment by glitchcrab** [comment]
need to update https://docs.giantswarm.io/vintage/use-the-api/kubectl-gs/template-cluster/

**Comment by glitchcrab** [comment]
<img src="https://media3.giphy.com/media/26u4lOMA8JKSnL9Uk/giphy.gif"/>
