### ISSUE TITLE
Refactor cluster-cloud-director Helm values to use global Helm values

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3373]
### Motivation

Towards https://github.com/giantswarm/roadmap/issues/3350

### TODO

```[tasklist]
- [x] Move `.Values.metadata` to `.Values.global.metadata`.
- [x] Move `.Values.connectivity` to `.Values.global.connectivity`.
- [x] Move `.Values.baseDomain` to `.Values.global.connectivity.baseDomain`.
- [x] Move `.Values.controlPlane` (and other control plane properties) to `.Values.global.controlPlane`.
- [x] Move `.Values.nodePools` to `.Values.global.nodePools`.
- [x] Move remaining provider-specific Helm values to `.Values.global.providerSpecific`.
- [x] Make sure that all Helm values that are required in cluster chart are correctly added to cluster-cloud-director Helm values.
- [x] Update cluster-cloud-director e2e tests in cluster-test-suites.
- [x] Update kubectl-gs if needed.
- [x] Update happa if needed.
- [x] Update relevant public docs (component-specific docs, where applicable, should be updated while working on the above tasks).
- [x] Update all Giant Swarm CAPVCD clusters to the new cluster-cloud-director version (first MCs then WCs).
```

### Outcome

**For Customer**
- CAPVCD workload clusters are configured with the new Helm values schema that is aligned with other providers and that is a stable long-term solution.
- cluster-cloud-director is compatible with cluster chart Helm values, which will enable integration of cluster chart into cluster-cloud-director (without affecting the customer), which will bring multiple new provider-independent features to CAPVCD workload clusters.

**Internal**
- Team Rocket can continue working on cluster-cloud-director with Helm values that will be compatible with cluster chart.
- Team Turtles can integrate cluster chart into cluster-cloud-director, without causing breaking changes to customers.

**Comment by glitchcrab** [comment]
vcd mcs will need updating to match this: https://github.com/giantswarm/giantswarm-management-clusters/pull/605

additionalProperties will need disabling again: https://github.com/giantswarm/cluster-cloud-director/pull/297

**Comment by glitchcrab** [comment]
done :muscle:
