### ISSUE TITLE
Zot app/chart improvements

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#3380]
```[tasklist]
### Tasks
- [ ] Avoid using Docker Hub images like [here](https://github.com/giantswarm/zot/blob/main/.github/workflows/zz_generated.check_values_schema.yaml)
- [ ] Verify resource requests (0.5 CPU cores and 0.5 GB RAM seems like a lot)
- [ ] Add proper icon for dark background (https://s.giantswarm.io/app-icons/zot/1/dark.svg does not work)
```

**Comment by marians** [comment]
Closing as obsolete
