### ISSUE TITLE
Improved cluster recovery - CAPA

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3387]
## User Story

During CAPA disaster recovery experiments we have been applying existing ETCD recovery ops-recipes. It was found that the recipes at hand can be improved for quicker and easier ETCD recvery from both, GS and customer side. We have also found an issue with cluster 'disaster' where the CRs are removed but apps are stuck in deleting.

## Acceptance Criteria

In the scenario of disaster recovery, which involves deletion and re-creation of the cluster together with bringing back the ETCD backup, there are following points to document or retest: 

1. Prepare instructions for running MC ETCD backup locally with docker without decrypting by etcdcl get/etcdctl put in order to fetch/recover following details:

- [x] Recover EncryptionConfig once the new cluster is created in order to be able to read secrets in the WC
- [x] Recover CA so all existing kubeconfigs can be used  on the new cluster (we did not test this)

2. Further points for instructions improvements:
- [x] When recovering ETCD, the peerl-url should be the private IP, not localhost to allow master2 and master3 to join the cluster
- [x] Master1 kubelet has to be restarted after ETCD restore in order to register in the API
- [x] Master1 [cluster.x-k8s.io](http://cluster.x-k8s.io/) annotations need to be present in order to allow CAPA to identify it as a master
- [x] Update the loadbalancer DNS in the ConfigMaps kube-public/cluster-info and kube-system/kubeadm-config

3. (Not critical) We have discovered an issue where:
- [ ] workload cluster apps remained stuck after cluster and cluster app was deleted - we have to reproduce and follow up in internal ticket: https://github.com/giantswarm/giantswarm/issues/30432

## Tasks (optional)

- [x] add new instructions to the existing ops recipes such as: https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/capa-control-plane-node-recovery/#recovering-a-broken-etcd-cluster or https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/recover-etcd-data-capi/
- [ ] restest the disaster recovery scenario with improved recipes
