### ISSUE TITLE
Karpenter documentation for public availability and default usage

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3402]
## User Story

As the Karpenter GA is reaching the end goal, the last step is to prepare documentation for internal as well as customer use such that the feature can be utilized with full potential.

Moreover we have to create instructions, or default behaviour for internal manual testing, such that we can lower the costs of manually created clusters with the use of Karpenter.

## Acceptance Criteria

Prepare public documentation about the Karpenter implementation:
- [ ] use-cases for EKS and CAPA clusters
- [ ] configuration to be applied by customers for utilizing Karpenter
- [ ] diagram describing the flow with Crossplane and Karpenter resources, together with aws-crossplane-config-operator

## Implementation details

- Implementation info to be filled out by engineer
