### ISSUE TITLE
Migrate Azure cluster functionality to Management API

### ISSUE THREAD

**Issue by axbarsan** [giantswarm/roadmap#341]
Towards https://github.com/giantswarm/roadmap/issues/310

### Description

* All existing functionality in Happa has to be moved to Management API
* As part of the migration, this is a good opportunity to update the design of the cluster detail page

### TODO

- [x] Be able to try out WIP features hidden behind feature flags (https://github.com/giantswarm/happa/pull/2473)
- [x] Cluster list on the homepage (https://github.com/giantswarm/happa/pull/2479)
    - [x] Display the list of active clusters
    - [x] Display additional information about nodes and whatnot
- [x] Cluster details `Overview` tab (https://github.com/giantswarm/giantswarm/issues/9077)
    - [x] Rename cluster
    - [x] Show stats about worker nodes
    - [x] Show stats about apps
    - [x] Show stats about keypairs
    - [x] Show release information (k8s version, if there's an upgrade available)
    - [x] Add/Edit/Delete labels
    - [x] Show master node info
    - [x] Show the K8s API URL
    - [x] Display BYOC info
    - [x] Display creation date
    - [x] Delete cluster
- [x] Cluster creation
    - [x] Change estimated creation duration to `15 minutes`
    - [x] Configure cluster and control plane node
- [x] Cluster upgrade
    - [x] Display supported upgrade versions in the release details modal
    - [x] Display updated components
    - [x] Execute the upgrade
- [x] Keypair management
    - [x] List all keypairs in read-only mode
- [x] Node pool management
    - [x] List
    - [x] Create
    - [x] Update name
    - [x] Update scaling
    - [x] Delete
- [x] Getting started guide
    - [x] Remove key pair creation function https://github.com/giantswarm/giantswarm/issues/17531
- [x] Ingress management
- [x] App management

**Comment by marians** [comment]
FYI: I just created https://github.com/giantswarm/giantswarm/issues/17531 and linked it in the list above

**Comment by axbarsan** [comment]
We can already release this internally ✅
