### ISSUE TITLE
Single OCI registry: Stage 3 - charts

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3411]
As a continuation of our single registry efforts, we want to also migrate our charts to be kept in the same OCI registry in azure as container images. This will also enable enhanced security features, like signing with `cosign`.

## Related epics
- Stage 1: #2882 
- Stage 2: #3065
- Retagger changes: https://github.com/giantswarm/roadmap/issues/3068

### OCI native app-platform

- [x] https://github.com/giantswarm/roadmap/issues/3413
- [x] https://github.com/giantswarm/roadmap/issues/3412
- [ ] Configure caching with zot

**Comment by weatherhog** [comment]
@piontec is the Zot part really left? Or is this done ?

**Comment by piontec** [comment]
Really. Working on it now.

**Comment by weatherhog** [comment]
@piontec 3 weeks ago, you said you are working on it. Is this still in progress or done ?

**Comment by piontec** [comment]
everything except of `zot` is done. Now, with zot we have another problem: `flux` can't switch between different sources of the same chart the same way `containerd` can. This means, that when we point clusters to `zot` for charts, `zot` becomes SPOF, instead of ACR, which is the SPOF (well, hardly) now. As such, benefits of using zot here are negligable: we would need something else first to work as a HA-proxy for multiple OCI repos. Closing for now, as we have never seen this as a problem.
