### ISSUE TITLE
Adapt GS tooling to the removal of default-apps-aws

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3419]
### Motivation
After the removal of `default-apps-aws` we need to update our tooling to handle that.

### Todo
Adapt the following tools to deploy defaults apps only through using the `cluster-aws` chart:
- [x] https://github.com/giantswarm/roadmap/issues/3445
- [x] https://github.com/giantswarm/roadmap/issues/3446
- [x] https://github.com/giantswarm/roadmap/issues/3443
- [x] https://github.com/giantswarm/roadmap/issues/3444
- [x] https://github.com/giantswarm/roadmap/issues/3447

### Outcome 
- Customers can directly migrate to the one app setup.
