### ISSUE TITLE
Kratix application build and deploy scenario

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#3429]
## Intro

Kratix will be our user-facing interface for driving the dev platform demo. An architecture schema of how it interacts with different components is available [here](https://docs.google.com/presentation/d/1FhnClfxY9mqVKIJAs6eYIS601mM-YB570_Th-DarIEU/edit#slide=id.g2e5803b21bb_0_0).

```[tasklist]
### Tasks
- [x] create a kratix promise that creates a new github repository based on a template one
- [x] extend githubrepo action with registry configuration
- [x] bootstrap a new repo for the gitops structure of demotech customer
- [x] create a repo for building docker images for the platform
- [x] create a kratix promise that deploys an application to an existing cluster using flux
- [ ] https://github.com/giantswarm/roadmap/issues/3604
- [ ] https://github.com/giantswarm/roadmap/issues/3605
- [ ] https://github.com/giantswarm/roadmap/issues/3609
```

**Comment by mproffitt** [comment]
Crossplane statuses

In progress
```nohighlight
  conditions:
  - lastTransitionTime: "2024-07-23T10:50:58Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-07-23T10:50:58Z"
    message: 'Unready resources: cidrassoc-0, cidrassoc-1, cidrassoc-2, and 4 more'
    reason: Creating
    status: "False"
    type: Ready
```

Ready
```nohighlight
  conditions:
  - lastTransitionTime: "2024-07-21T07:17:49Z"
    reason: ReconcileSuccess
    status: "True"
    type: Synced
  - lastTransitionTime: "2024-07-21T07:20:04Z"
    reason: Available
    status: "True"
    type: Ready
```

**Comment by piontec** [comment]
Done for stage 1 of the demo
