### ISSUE TITLE
Managed Spark

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#343]
Towards EPIC_URL

## User Story

- As a ROLE, I would like FEATURE so that REASON

## Acceptance Criteria

- [ ] Given PRECONDITION when I do ACTION then I should get RESULT

## Dependencies

- [ ] URL - TITLE

## Tasks

- [ ] URL - TITLE

**Comment by cokiengchiara** [comment]
Created this issue but Timo confirmed we don't need to do this yet until customer confirms they are signing on with us. 

From @ubergesundheit ,I would say we work on @pipo02mix 's app in playground and apply

- [ ] subtree sync
- [ ] building with abs
- [ ] move to giantswarm catalog
