### ISSUE TITLE
Migrate apps from default-apps-azure to cluster chart

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3461]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [ ] Move all relevant, provider-independent, shared apps from default-apps-azure into the cluster chart
- [ ] Prepare the tests for this change - the change might/will be a breaking change for the test environment
- [ ] Remove all migrated apps from default-apps-azure so that they are only used from cluster chart
- [ ] Clearify with Team Phoenix how to roll out the change on all CAPZ Installations
- [ ] Document the design decision / process in cluster chart / cluster-azure chart

### Outcome
- The complexity of where and how apps are managed is reduced since we now have all provider independent apps in just the cluster chart
