### ISSUE TITLE
Migrate apps from default-apps-azure to cluster-azure chart

### ISSUE THREAD

**Issue by yulianedyalkova** [giantswarm/roadmap#3462]
### Motivation
In order to match the target state of our defined release framework we need to remove the use of the default-apps charts from all providers. Only then can we realise the single entrypoint to apply changes to a cluster for customers and reduce complexity in how and where our apps are managed.

### Todo

- [ ] Move all relevant, provider specific apps from default-apps-azure into the cluster-azure chart
- [ ] Prepare the tests for this change - the change might/will be a breaking change for the test environment
- [ ] Remove all migrated apps from default-apps-azure so that they are only used from cluster-aws chart
- [ ] Clearify with Team Phoenix how to roll out the change on all CAPA Installations

### Outcome
- The complexity of where and how apps are managed is reduced since we now have all provider specific apps in just the cluster-aws chart

**Comment by njuettner** [comment]
I prepared almost everything on last Friday but I need to do a lot of testing now.
