### ISSUE TITLE
Migrate from aws sdk for go v1 to v2

### ISSUE THREAD

**Issue by fiunchinho** [giantswarm/roadmap#3497]
## Chore description

[AWS has announced the end of life of the AWS sdk for go v1](https://aws.amazon.com/es/blogs/developer/announcing-end-of-support-for-aws-sdk-for-go-v1-on-july-31-2025/) that we use extensively in our controllers. We should migrate to v2.

## Chore context

When our controllers use AWS services and APIs they rely on the [AWS SDK for go v1](https://github.com/aws/aws-sdk-go). The v2 is a different package / repo entirely https://github.com/aws/aws-sdk-go-v2.

## Tasks

- [x] Migrate `aws-resolver-rules-operator`
- [ ] Migrate `irsa-operator`
- [x] Migrate `capa-iam-operator`
- [ ] [Migrate other controllers that use the SDK in our organization](https://github.com/search?q=aws-sdk-go++org%3Agiantswarm+language%3A%22Go+Module%22++NOT+aws-sdk-go-v2&type=code).
