### ISSUE TITLE
Rollout of Mimir to `goat` and `galaxy`

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3505]
### Motivation
We rolled out Mimir nearly everywhere on CAPA and CAPZ - besides the installations with a special setup. There we have goat with a private network setup and galacy which is our installation in china. 

### Todo

- [x] Test the rollout of mimir on a private network setup
- [x] Roll Mimir on goat and verify that it runs as expected
  - [ ] Fix any upcoming issues
    - [ ] https://github.com/giantswarm/giantswarm/issues/31110 
- [x] Test the rollout of mimir on a chinese installation
- [x] Rollout Mimir on galaxy and verify that it runs as expected
  - [x] Fix any upcoming issues

### Outcome
- Mimir is rolled out to all cloud providers on capa

**Comment by QuentinBisson** [comment]
I rolled out galaxy:
- Enabled mimir on galaxy: https://github.com/giantswarm/giantswarm-configs/pull/105
- Configured missing grafana cloud url in China https://github.com/giantswarm/giantswarm-configs/commit/2599b5966d8238dc57d83c71f46d8b7598216265

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa rolled out mimir on Goat and is trying to fix the only issue we have (https://github.com/giantswarm/giantswarm/issues/31110)

**Comment by QuentinBisson** [comment]
Follow up issue for phoenix https://github.com/giantswarm/giantswarm/issues/31127

**Comment by QuentinBisson** [comment]
Mimir is rolled out on both goat and galaxy.
- Non blocking bootstrap issue in China will be addressed by phoenix: https://github.com/giantswarm/giantswarm/issues/31127
- Communication issue between goat and grafana cloud is covered by https://github.com/giantswarm/giantswarm/issues/31110 which is currently blocked by https://github.com/giantswarm/giantswarm/issues/31136

Closing this one
