### ISSUE TITLE
Mimir disabled configuration

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3513]
### Motivation

The whole monitoring stack can be disabled with the configuration variable on the management cluster level

```
monitoring.enabled
```

This needs to be also the case for Mimir.

### Todo

*   [x] Make sure Mimir is not deployed when the monitoring is disabled: this is already the case
*   [x] Make sure Prometheus is not deployed when the monitoring is disabled on capi MCs https://github.com/giantswarm/shared-configs/pull/101 this needs to wait till old capi MCs have been rolled out with  mimir
*   [x] Make sure mimir-to-grafana-cloud exporter is not deployed when monitoring is disabled: already the case with https://github.com/giantswarm/shared-configs/blob/e307274e60128b5ee5100238de717c917a714d7b/default/apps/prometheus-remotewrite/configmap-values.yaml.template#L3 and https://github.com/giantswarm/prometheus-remotewrite/blob/2e873186ae32305947ca7879b74fbff4ca985f96/helm/prometheus-remotewrite/templates/mimir/mimir-prometheus.yaml#L1
*   [x] Make sure grafana-agents rules is not deployed when the monitoring is disabled: already possible with https://github.com/giantswarm/shared-configs/blob/e307274e60128b5ee5100238de717c917a714d7b/default/apps/prometheus-rules/configmap-values.yaml.template#L14
*   [ ] Make sure the prometheus-agents are not deployed when the monitoring is disabled https://github.com/giantswarm/observability-operator/pull/48
*   [x] Make sure the alertmanager is not deployed when the monitoring is disabled https://github.com/giantswarm/shared-configs/pull/101 and https://github.com/giantswarm/prometheus-meta-operator/pull/1673

### Outcome

*   Mimir and all relevant components for it can be simply disabled on the MC level

**Comment by QuentinBisson** [comment]
@Rotfuks I'm guessing we also want to remove alertmanager and alerts right?

**Comment by Rotfuks** [comment]
Yes, makes sense if we don't have that yet. Thought since it's not changing we already have that in place. But yes, I'll add it.

**Comment by QuentinBisson** [comment]
All PRs are ready but the prometheus agent PRs
