### ISSUE TITLE
Investigate and optimize Mimir Resource Usage

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3514]
### Motivation

With our [Dashboards](https://giantswarm.grafana.net/d/edpqololp1ibkc/prometheus-and-mimir-resource-usage) and [discussions](https://gigantic.slack.com/archives/C01176DKNP4/p1718892033072889) we have identified that Mimir uses roughly 2 times as much RAM as our previous prometheus setup used. Since we want to have as low of an impact on our customers resources as possible we should investigate if we can't reduce this huge usage of costly RAM a bit more.

### Todo

*   [x] Investigate how we can reduce resource usage from mimir (you might find some tips [in this thread](https://gigantic.slack.com/archives/C01176DKNP4/p1719228323568469))
*   [x] Optimise the resource usage of mimir
*   [ ] Find out what's the comparison between our previous prometheus setup and our new mimir setup exactly for the memory usage and how we can explain the bigger resource consumption

### Outcome

One of the two options:

*   Mimir uses less or the same amount of resources than our previous setup.
*   We know and can advertise why Mimir has a higher resource consumption than prometheus.

**Comment by Rotfuks** [comment]
One of the potential ideas on what we can do is done here: giantswarm/giantswarm#31132

**Comment by QuantumEnigmaa** [comment]
I agree

**Comment by QuentinBisson** [comment]
For instance, on grizzly, here is what we had/have now and sure there are differences because we deleted the old setups when clusters were deleted so used memory with prometheus was not over time but over 1h only. With mimir, we keep the data longer, even for deleted clsuters. As our automation create sa lot of new clusters on grizzly, the numbers will be difficult to compare but I would roughly guess that we are quite close

![Image](https://github.com/user-attachments/assets/28eaf9a1-8ec1-4676-a9f5-b8e14a9278aa)

**Comment by QuentinBisson** [comment]
@hervenicol and @QuantumEnigmaa I'm assigning you because you did most of the investigation work on this and I don't think this needs more work but let's discuss it during standup

**Comment by hervenicol** [comment]
Grizzly is not the right installation to look at, because as you said it creates lots of ephemeral WCs.
We should look at more stable installations.
Unfortunately, we don't have big stable CAPI installations yet.

Let's have a look at `gazelle`: it went from 16GB (prometheus) to 20GB (Mimir).
![image](https://github.com/user-attachments/assets/6a016c90-10c9-436e-8aad-44e841f463c8)

Alba had new clusters, so its number of series grew, and comparison is difficult.
![image](https://github.com/user-attachments/assets/edaefd9b-2c74-4498-8825-54f2f54be2db)

glippy went from very few (max 4GB) to 20GB.
![image](https://github.com/user-attachments/assets/7618d51f-c23e-443e-acc7-d8b765077409)

velvet went from 5 to 8:
![image](https://github.com/user-attachments/assets/3d548686-5b71-41d2-a968-5a56a1ea884e)

Feel free to explore the dashboard here: https://giantswarm.grafana.net/d/edpqololp1ibkc/prometheus-and-mimir-resource-usage

While decreasing replication factor reduced mimir memory usage, Mimir is still using more RAM than Prometheus. I didn't find an installation where it's not the case.

**Comment by QuentinBisson** [comment]
So I agree and I was looking at this dashboard definitely l'ESS thoroughly.  Now if we only look at gazelle, I would think that going from 16GB to 20 GB would be around the same ballpark.

Thé issue , as you mentionned is that it's almost impossible to compare because of migrations and other clusters. We could theoreticslly compare eagle with Enigma once Eagle was fully migrated though but we don't know when this will happen

**Comment by QuentinBisson** [comment]
It could also be that some of that différence is due to new components in capi mcs 😅

**Comment by QuentinBisson** [comment]
Oh I stand corrected, we cab use leopard as a baseline for that but communication to grafana cloud is broken

**Comment by QuentinBisson** [comment]
Here is the leopard one after I've manually set the proxy url on the buddy:


![Image](https://github.com/user-attachments/assets/8a1dddad-b663-4dc2-a406-cad81bd45be0)

So it looks like we are using roughly 4GB more to run mimir as opposed to running prometheus but do we want to investigate this?

**Comment by Rotfuks** [comment]
We're happy with the resource usage at this point. so this is done, thanks everybody!
