### ISSUE TITLE
Self-Service Data Ingestion

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3515]
### Motivation
We want customers to be fully self-service empowered when working with the observability platform. For this we also need to make sure customers can create new data ingestions for metrics and logs in a self service way for the observability platform in their installations. 

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/23411
- [ ] https://github.com/giantswarm/roadmap/issues/3517
- [ ] https://github.com/giantswarm/giantswarm/issues/29072
- [ ] https://github.com/giantswarm/roadmap/issues/3518
```

### Outcome
- Customers can in a self-service way monitor whatever app or component they like.
