### ISSUE TITLE
Documentation and examples for Service Monitors

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3517]
### Motivation

For metrics it's already possible to ingest new sources of data in self service for our customers. All they have to do is to create a new service monitor, which is a default prometheus/kubernetes thing you can find a lot of resources about online. What's missing now is to educate them about the possbilities there. 

### Todo

*   [ ] Create a draft for a documentation helping customers to be able to create their own service monitors to ingest new sources of metrics.   
    \- You can use any good material you find on the official grafana documentation and just link to it, but customers need a good entry point and overview first in our docs.  
    \- We can reuse [https://intranet.giantswarm.io/docs/monitoring/monitoring_of_apps/](https://intranet.giantswarm.io/docs/monitoring/monitoring_of_apps/) and then cleanup this internal doc afterwards
*   [ ] Get some feedback on the documentation from Account Engineering
*   [ ] Make sure the docs are published in the new Observability Platform documentation

### Outcome

*   Customers now know how to ingest new sources of metrics on their own.
