### ISSUE TITLE
Update front-end tooling to support v25 (and newer) CAPA releases

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3536]
### Motivation

We have started using new CAPI releases for AWS (CAPA) which are using Release resources. Now we should adapt our front-end tooling to support v25 and newer releases.

### TODO

```[tasklist]
#### kubectl-gs
- [x] https://github.com/giantswarm/kubectl-gs/pull/1352
- [ ] https://github.com/giantswarm/kubectl-gs/pull/1359
- [ ] https://github.com/giantswarm/kubectl-gs/pull/1361
```

```[tasklist]
#### Happa
- [x] Update Happa to support v25 and newer releases for AWS (CAPA)
- [x] Release new version of Happa
```

### Outcome

You can use kubectl-gs and Happa to create v25 AWS (CAPA) clusters.

**Comment by mproffitt** [comment]
Done from Honeybadgers side

**Comment by nprokopic** [comment]
Closing as Hppa support got implemented here https://github.com/giantswarm/happa/pull/4618
