### ISSUE TITLE
Add a test for the status of the ingress loadbalancer service

### ISSUE THREAD

**Issue by weseven** [giantswarm/roadmap#3560]
### Motivation

In the cluster-test-suites, [in the "hello world" suite](https://github.com/giantswarm/cluster-test-suites/blob/8845583420b2e91c112f1b5d2a09b16f10c940a2/internal/common/hello.go#L91), we test the wildcard DNS after deploying the ingress controller and external dns.

We should however test the status of the loadbalancer service created by the ingress controller (`ingress-nginx-controller` in the `kube-system` namespace): in case this has issues the DNS record the wildcard CNAME is pointing to (`ingress.<clusterdomain>`) is not created, and the DNS failure might pass for a temporary issue.

Checking that service status until it's ready (not Pending), for a maximum of 5 minutes should be enough.
If it's still pending after 5 minutes, we should print the status and the events related to the service: there we can find details about the issue ([e.g., missing permissions on aws control-plane policy](https://gigantic.slack.com/archives/C0559SH3RJ4/p1720453207971019?thread_ts=1720452458.039729&cid=C0559SH3RJ4)).

### TODO
- [ ] Add a test for the `ingress-nginx-controller` loadbalancer service before testing wildcard DNS
- [ ] Test the outcome. 
- [ ] Update relevant docs.

### Outcome

We catch possible errors easier and earlier :)
