### ISSUE TITLE
Mimir testing

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3578]
### Motivation

n order to raise our confidence in the stability of our observability platform and be sure that our ongoing work and releases won't negatively impact our observability platform operations we need to create extensive tests giving us early feedback loops. As mimir is one of our core components, we should make sure it's thoroughly tested. 

### Todo

- [ ] Investigate some good initial test cases to give us feedback on the stability of a release on mimir on CI. This can be:  
  - Validate Helm chart templating
  - Deploy chart on Kind (single instance)
- [ ] Implement those CI test cases

- [ ] Investigate some good initial test cases to give us feedback on the stability of a release before releasing. This can be:
  - Deploy chart on AWS, Azure, CAPI (later)
  - Integration test; Verify all component work together
  - Using canary to generate traffic
- [ ] Implement those test cases

Make sure to stay with a set of minimal but valuable test cases, nothing to detailed and fancy.

### Outcome
- We have early, automatic feedback about the impact of a release of Mimir before releasing.

**Comment by QuentinBisson** [comment]
I think it would be nice to run mimir continous testing (similar to loki canary) for e2e tests

**Comment by QuantumEnigmaa** [comment]
Yeah that's a nice idea :)

**Comment by QuentinBisson** [comment]
I am running mimir continuous_test on grizzly with the following config:

```
mimir:
  continuous_test:
    enabled: true
    auth:
      tenant: anonymous
```

and this renders the following metrics:



![Image](https://github.com/user-attachments/assets/fdde4ed8-638e-4801-b032-b1d41656543f)

and we could just use those alerts https://github.com/grafana/mimir/blob/f52911d917c8c52e0da6a59348a64dd7f7622072/operations/mimir-mixin-compiled/alerts.yaml#L1097

The only downside is that we need to wait for the next minor helm chart release or use a weekly version because this https://github.com/grafana/mimir/pull/8654 is not yet released

**Comment by QuantumEnigmaa** [comment]
So what's the best plan of action IMO is to wait for the continuous testing to be a default config for our mimir before doing anything else. 
In the meantime, I'll create a dashboard using the metrics from the rules' mixins and if it's good enough, I'll think about pushing it upstream as a mixins dashboard.

**Comment by QuentinBisson** [comment]
I think so yes, maybe we can have a pr ready with the alerts? The mixins contains some that could be useful

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa we decided in retro to use the chart version rc0 for now but keep the old image of mimir 2.13

**Comment by QuentinBisson** [comment]
We can start this again once we're done with multi-tenancy :)

**Comment by QuentinBisson** [comment]
Taken over the dashboard PR https://github.com/giantswarm/dashboards/pull/624 to close the epic

**Comment by QuentinBisson** [comment]
Blocked waiting for reviews

**Comment by QuentinBisson** [comment]
Continuous test is enabled:
- 

Dashboard PR has been merged: 
- https://github.com/giantswarm/dashboards/pull/624

Alert based on failures under review:
- https://github.com/giantswarm/prometheus-rules/pull/1355

**Comment by QuentinBisson** [comment]
All is done. Thanks @hervenicol for the reviews
