### ISSUE TITLE
Observability Platform Blog Post

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3580]
### Motivation
Our Giant Swarm Blog is quite a nice source of information for customers and prospects. Additionally every article we write there we can share over social media channels or just generally share the link whenever needed. Thus having a Blog Article about our Observability Platform would be a nice resource we can use to publicly showcase our platform and strategy. 

### Todo

- [ ] Come up with a good outline for an observability platform blog post
  - It should include a general intro to the platform 
  - It should include a general product overview / architecture overview
  - It should discuss the benefits and value of our platform (business stuff!) 
- [ ] Write the blog post
- [ ] check with sig-content and sig-revenue for feedback on that blogpost

### Outcome
- We have a good public resource to introduce the concept of the observability platform with customers and prospects

**Comment by Rotfuks** [comment]
Text for the Draft is going in here: https://docs.google.com/document/d/1-8TU6c7LgfUxzzZF8R3Y3dPU7xImcT6W5K9CLaiDxiQ/edit?usp=sharing

**Comment by HelloHeatherC** [comment]
Thanks @Rotfuks, very well executed! 🥇 

I left some minor suggestions, but job well done!

**Comment by Rotfuks** [comment]
Alright @HelloHeatherC - we need some header graphics. I guess that's @morotki then? Or do we just reuse one like the one of https://www.giantswarm.io/blog/maximizing-value-with-kubernetes-as-a-product-fulfilling-the-promise-of-the-cloud which could fit as well? 
But it would be somehow great if we could sneak the observability bant in :D

**Comment by HelloHeatherC** [comment]
Hi hi @morotki, please could you help with the above? I love Mr Observability Bant, please could he make an appearance?

**Comment by Rotfuks** [comment]
I'm fine with it as a final version, we have reviews from different areas of the company, I guess there's a diverse perspective in it now, that's fine :) As this is just the start of a series of blog posts I'd say we're fine, wdyt?

**Comment by morotki** [comment]
@HelloHeatherC here's the blog image:

https://app.hubspot.com/files/430224/?folderId=54106966129&sortDirection=descending&orderBy=updated&archived=false&showDetails=177401371036

**Comment by HelloHeatherC** [comment]
Amazing, @morotki! Thank you.

**Comment by Rotfuks** [comment]
I feel the shared responsibliity image needs some sort of a caption like "Shared Responsiblity in the Observability Platform, orange = managed by Giant Swarm, blue = managed by you" or something, you know? 
In the last section of the Observability Platform Journey chapter there is a character missing from a link (useful alerting rules).

But besides those two points it looks good for me. 
The image is amazing. Thanks!

**Comment by HelloHeatherC** [comment]
Updated, thanks for catching that. We can launch next week. 🚀

**Comment by Rotfuks** [comment]
Looks Lovely, thanks!
