### ISSUE TITLE
CAPA WC `cluster_id` migration `origin_MC`/`target_MC` - checklist

### ISSUE THREAD

**Issue by T-Kukawka** [giantswarm/roadmap#3582]
As Giant Swarm manages the cloud infrastructure, there are no actions needed from customers for the migration itself. We have aimed to match the Vintage features as closely as possible, introducing improvements where needed. One of the improvements is actually deprecation of the `k8s-initiator` application, which was allowing to customize some parts of the kubernetes environment, catering customer needs. This tool however was bringing a lot of freedom in terms of `bash` implementation that was ran in the tool itself. We have reviewed the use-cases that customers have implemented, exposed certain settings in CAPA and prepared a migration plan for those features as well as allowing any future customization. The most important part for each customer is to prepare the `{cluster_name}-migration-configuration` yaml file, representing the `k8s-initiator` app features used, which will be consumed then by the migration CLI and be populated in Cluster charts for future needs. 

We have prepared a following checklist to make sure that the migration goes as smoothly as possible.

## Checklist for WC migration:
- [ ] Cluster migration date has scheduled -> DATE_HERE
- [ ] Internal GS slack channel is created
- [ ] Cluster is currently on 20.1.x release
- [ ] Cluster's masters are HA
- [ ] AWS limits for account that cluster is located in are adjusted and big enough for the cluster to be doubled in instance size 
- [ ] `k8s-initiator-app` features in use are prepared for migration in a single `yaml` accordingly to the specification
    - [ ] audit policies [configuration](https://github.com/giantswarm/k8s-initiator-app/blob/main/capa-migration/audit-policies.md)
    - [ ] node taints and labels [configuration](https://github.com/giantswarm/k8s-initiator-app/blob/main/capa-migration/node-taints-and-labels.md)  
    - [ ] admission controllers [configuration](https://github.com/giantswarm/k8s-initiator-app/blob/main/capa-migration/admission-controllers.md)
    - [ ] container logs [configuration](https://github.com/giantswarm/k8s-initiator-app/blob/main/capa-migration/container-logs.md)
    - [ ] auditd kernel (disabled by default) [configuration](https://github.com/giantswarm/k8s-initiator-app/blob/main/capa-migration/auditd-toggle.md)
- [ ] In case of Karpenter usage - it is removed from the cluster
- [ ] Customer automation/gitops is stopped for the migrated cluster
- [ ] the Organization of the targeted Vintage WC is created on the CAPA MC
- [ ] If cluster is in Organization that did not have any migrations yet, we need the basic configuration upfront: https://docs.giantswarm.io/vintage/getting-started/cloud-provider-accounts/cluster-api/aws/
- [ ] Ask customer for the draining timeout (by default 15') if there are any critical/slow workloads to start up
- [ ] Make sure to perform ETCD backup before the start of migration following [guide](https://intranet.giantswarm.io/docs/support-and-ops/ops-recipes/etcd-backup-failed/#case-a-there-is-no-recent-etcdbackup-object) or running `opsctl create etcdbackup -i THE_VINTAGE_INSTALLATION --workloadcluster THE_WORKLOAD_CLUSTER` 
- [ ] Make sure there are no internet gateway routetable entries in private/pod subnets which could make CAPA treat the subnets as 'public'
- [ ] GS creates the MC OIDC provider on the WC aws account

## GS Checklist post WC migration:
 - [ ] Remove the CRs from the `vintage` Management Cluster. This should be done only after the customer has checked that everything is running fine on the new CAPI cluster and there is no requirement from customer to create new kubeconfigs for the `vintage` cluster.
- [ ] Migrate the ingress DNS entries following the [guide](https://github.com/giantswarm/capi-migration-cli/?tab=readme-ov-file#ingress-dns-migration)
- [ ] Migrate DEX in workload cluster following this [guide](https://github.com/giantswarm/capi-migration-cli/?tab=readme-ov-file#dex-migration) to ensure all functionalities (if in use)
