### ISSUE TITLE
[EPIC] Multi-Provider MCs - CAPV on CAPA

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3585]
Based on CAPZ & CAPV epic https://github.com/giantswarm/roadmap/issues/2840

We want to enable a truly hybrid Installation where the MC is on AWS (CAPA) and Workload clusters are AWS as well as on-prem vSphere (CAPA & CAPV)

Acceptance Criteria: Create a GS Installation on AWS that is able to create 1 CAPA WC and 1 CAPV WC on IONOS

User Story
As a GiantSwarm Customer & Platform Engineer I want to centralize as much of my applications and Administration as possible onto AWS, while still using some compute power available in the Factories with vSphere

Assumptions
Based on [CAPZ hybrid documentation](https://intranet.giantswarm.io/docs/product/providers/capz/multi-provider/):

Our MC is on CAPA. It is capable of provisioning CAPV and CAPA workload clusters.
CAPA MC is able to access the vSphere API.
CAPA MC is able to access all CAPV WCs.
CAPV WCs are able to access endpoints (k8s API and ingresses) of the MC.
There is a single base domain for all clusters and it is managed on AWS via dns-operator-route53. See https://github.com/giantswarm/dns-operator-route53/blob/main/README.md

```[tasklist]
### Tasks
- [x] challenge assumptions above and refine tasks
- [ ] https://github.com/giantswarm/roadmap/issues/3586
- [ ] https://github.com/giantswarm/roadmap/issues/3587
- [ ] https://github.com/giantswarm/roadmap/issues/3619
- [ ] https://github.com/giantswarm/roadmap/issues/3624
- [ ] https://github.com/giantswarm/roadmap/issues/3627
- [ ] https://github.com/giantswarm/roadmap/issues/3642
```

**Comment by anvddriesch** [comment]
Closing this since the hybrid environment is functional, e2e tests are present and we have the documentation. We can open another issue once we have more specific requirements from customers.
