### ISSUE TITLE
CAPA MC as CAPV hybrid dev environment

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3586]
We need a CAPA MC for our CAPA/CAPV hybrid dev environment.
First task list is based on https://intranet.giantswarm.io/docs/product/providers/capz/multi-provider/

```[tasklist]
### Tasks
- [x] Create a new CAPA MC or select an old one as CAPV hybrid environment
- [x] Add vsphere-addons-app-collection to CAPA hybric MC
- [x] Configure cluster-api-ipam-provider-in-cluster app for the CAPA hybrid MC
- [x] Provide vSphere credentials for CAPV orgs in CAPA hybrid MC
- [x] add org and container configuration for e2e tests
```

**Comment by anvddriesch** [comment]
CAPV controller is running on goat. It reconciles the clusters but does not seem to interfere with them at all since they are managed by CAPA.
I want to try to create a vsphere cluster and see how it shakes out.

**Comment by anvddriesch** [comment]
closing this now since controllers and stuff are present.
We don't have working cluster creation yet but we can open more tickets
