### ISSUE TITLE
Sunset Fluentbit

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3599]
### Motivation

Now that we are using a new log-receiver to receive and forward logs we can sunset the old fluentbit component we used until now for log forwarding using less components and resources.

### Todo

*   [ ] Make sure that the fluentbit log forwarding is now replicated in and done by the new log receiver
*   [ ] Get rid of fluentbit and remove it everywhere
*   [ ] Make sure fluentbit is removed from the catalogs and devportal

### Outcome

*   We own one less component reducing our operational effort and amount of stuff we need to know.

**Comment by Rotfuks** [comment]
Since we are not focusing on export right now, this is out of scope for now.
