### ISSUE TITLE
Automatically forward-port changes from older to newer major releases

### ISSUE THREAD

**Issue by nprokopic** [giantswarm/roadmap#3620]
### Motivation

When we create a new minor or patch release for an older major, we always have to forward-port those same changes to all newer major releases.

Today this is manual work, a work that is unfortunately not being done always. If a change is not forward-ported from an older to a newer major release, then the app/component that was updated in an older major release will get downgraded when a cluster is upgraded to a newer major release.

We should automate forward-porting of changes to all newer major releases.

<details>
<summary>Example of a problem when changes are not forward-ported</summary>

Since this forward-porting of a change is not done consistently, here is a real-world example from today (31st of July) that describes a problem here:
- We had CAPA releases v25.0.0, v26.0.0, v27.0.0, v28.0.0.
- CAPA v25.1.0 has been released with app and component changes.
  - All these changes should have been also released as v26.1.0, v27.1.0 and v28.1.0, but they weren't.
- Now we have to release v25.2.0 with some new changes that we need in v25.
  - Instead of just forward-porting this specific change to v26, v27 and v28, now the person/team that does v25.2.0 also has coordinate the effort to forward-port all changes from v25.1.0 as well (a work that should have been done already).

The above example is perhaps not a default one, as we have 4-5 major CAPA releases ATM, but again, in the soon-to-be future we will have probably 2 majors for every provider, so that gives us 8 major releases, all of which should be updated in some cases, so even more work compared to updating 4 major CAPA releases from the above example.
</details>

### TODO

- [ ] Get feedback on this issue.
- [ ] If we agree that we want to implement the automation:
  - [ ] Discuss and agree how it should work. e.g. should it automatically update PRs in the releases repo (so we add missing releases in every PR), or should it open new PRs in the releases repo (to add missing releases in separate PRs), etc. 
  - [ ] Since an automation like this would most probably rely on Releases SDK (like e2e tests for example), see if we miss some functionality in the Releases SDK for this.
  - [ ] Implement this new releases automation. Ideally do this in Golang as much as possible, maybe as a CLI tool alongside Releases SDK, and then just make use of this CLI in CI (GitHub action, CircleCI, Tekton, or wherever is the most suitable place).

### Outcome

**For Customer**
- Customers get changes delivered across all major releases more quickly, so if a customer has a cluster on the latest minor+patch of some old major, they can upgrade to a newer major without downgrading any app/component.

**Internal**
- Every team that is making releases of their apps/components takes care of updating all major releases that needs to be updated, and while the responsible team is driving the effort, the releases forward-porting automation ensures that this is done consistently and reliably.
