### ISSUE TITLE
Sort out dns for CAPA/CAPV hybrid MC (likely via dns-operator-route53)

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3624]
```[tasklist]
### Tasks
- [x] try dns-operator-route53 in hybrid setting and confirm it works
- [x] adjust reconcillation so that other infra providers do not cause errors
- [x] add dns-operator-route53 to collection
- [x] add collection containing the dns-operator to goat
- [x] add credentials
```

**Comment by anvddriesch** [comment]
The open PR disables AWSCluster infrastructure in the operator and also pushes it to a new collection that we can apply to the MC https://github.com/giantswarm/vsphere-aws-addons-app-collection

**Comment by anvddriesch** [comment]
So because `dns-operator-route53` is not used on capz hybrid and therefore not present in the existing addons collection I have added a new collection specifically for aws/vsphere hybrid. (The one linked above)
We have decided that adding both collections is tedious and so I have also added all the other needed addon apps there and it's enough now to only deploy `vsphere-aws-addons-app-collection` on a capa MC. (you won't need the `vsphere-addons-app-collection`)
