### ISSUE TITLE
Gather analytics of dashboards usage

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#364]
Towards **https://github.com/giantswarm/roadmap/issues/182 Give customers access to Grafana**

### Description

We'd like to know if customers are using Grafana, and if so, how long are they on pages, which pages are they going to. It'd be cool also to have similar data for Giant Swarm employees.

### TODO

- [x] Check if we can use the GA plugin for Grafana to collect usage data
- [x] check Grafana analytics panel plugin
- [x] check other potential sources of data
  - [x] nginx-IC metrics
  - [x] dex metrics
  - [x] Grafana logs
- [x] #380
- [x] #378
- [x] #379
- [x] #381
- [x] #382
- [x] #398
- [x] clean-up _ghost_ (@mig4 was testing analytics plugin stuff there)
- [x] clean-up Google Analytics if not used (@mig4 tell @marians he can delete the properties/sites)
- [x] https://github.com/giantswarm/giantswarm/issues/18571
- [x] #383
- [x] https://github.com/giantswarm/giantswarm/issues/18574
- [x] #446
- [x] #448

**Comment by mig4** [comment]
Hi @marians, Joe mentioned you may have already looked into this? Just picking this up and wanted to check.

**Comment by mig4** [comment]
First thing I came across is [macropower-analytics-panel](https://grafana.com/grafana/plugins/macropower-analytics-panel/), it's not Google, but allows feeding analytics data from Grafana back into Grafana! More privacy friendly, but requires running a service to store the data.

**Comment by mig4** [comment]
OK, I did a rather extensive search and I cannot see an easy/documented/useful way to hook Google Analytics into Grafana. In the end it's all HTML so maybe injecting a `<script>` would somehow be possible, but I'm not sure what context we'd get that way and so if it would be very useful.

BTW most info out there is about feeding data from Google Analytics into Grafana so it can be visualised and analysed there. There is pretty much nothing about analysing Grafana usage. There is [this issue at GitLab](https://gitlab.com/gitlab-com/gl-infra/infrastructure/-/issues/9716) where they looked into that but eventually went a different route (user research, aka talking to SRE team to ask how they use the dashboards, and possibly using logs).

I'm inclined to try this _analytics-panel_ plugin and see how it works first, before getting into hacky solutions.

**Comment by mig4** [comment]
I experimented with the [macropower-analytics-panel](https://grafana.com/grafana/plugins/macropower-analytics-panel/) plugin and here are the results, for reference.

I deployed [the simple backend service](https://github.com/MacroPower/macropower-analytics-panel/tree/master/server) that acts as a receiver for the frontend plugin to send data to and as temporary storage for that data to _ghost_ MC in `grafana-analytics-panel-server` namespace. This is a simple `Deployment` + `Service` + `Ingress` that can be turned into an app.

The `Ingress` hooks into the Grafana subdomain and exposes the service via an additional path and uses URL rewriting so the backend is unaware it's not running under `/`. For ref, this looks like:

<details>
<summary>Ingress definition</summary>

``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
    app: grafana-analytics-panel-server
  name: grafana-analytics-panel-server
  namespace: grafana-analytics-panel-server
spec:
  rules:
  - host: grafana.g...o
    http:
      paths:
        - backend:
            service:
              name: grafana-analytics-panel-server
              port:
                number: 8080
          path: /grafana-analytics-panel-server(/|$)(.*)
          pathType: ImplementationSpecific
```

</details>

Once that's running, we need to configure the frontend. Unfortunately the way it works is that the plugin adds a _panel_ that has to be added to every dashboard that we want to track. But this can be done programmatically if we use Jsonnet to generate/modify the dashboard JSON files.

<details>
<summary>For ref, manual setup</summary>

1. open a dashboard, add a panel

![grafana analytics-panel-config-1 add-panel 2021-07-05--12-24-11](https://user-images.githubusercontent.com/42101611/124467907-65548880-dd90-11eb-85da-f0343b7d1f79.png)

2. configure the endpoint, in case of _ghost_ this is `https://grafana..../grafana-analytics-panel-server/write`

![grafana analytics-panel-config-2 configure-endpoint 2021-07-05--12-26-14](https://user-images.githubusercontent.com/42101611/124467991-7b624900-dd90-11eb-8295-e4155baca4b0.png)

3. panel should now be working (no error)

![grafana analytics-panel-config-3 panel-working 2021-07-05--12-33-08](https://user-images.githubusercontent.com/42101611/124468050-8cab5580-dd90-11eb-8393-73f86e12025e.png)

4. and metrics should start appearing when browsing the metrics endpoint: `https://grafana..../grafana-analytics-panel-server/metrics`

![grafana analytics-panel-config-4 metrics 2021-07-05--12-35-24](https://user-images.githubusercontent.com/42101611/124468071-93d26380-dd90-11eb-9016-bebad37b14ef.png)

</details>

**Comment by mig4** [comment]
Joe found there's a somewhat briefly documented built-in option in Grafana config to supply details for Google Analytics after all, and thanks to Marian I now have access to https://analytics.google.com/ sorted, so I'm going to be trying this out now.

**Comment by mig4** [comment]
I got the Google Analytics integration sort of working. Well, it seems to be working fine on our end and on GA end as when loading up Grafana I can see requests to google-analytics.com, and I can see data appearing in GA in the realtime section (and eventually in the main section as well).

The problem is the call to GA only happens on full page load (whether it's to the `/` or directly to some dashboard). It doesn't happen when navigating between components in the app (e.g. if I go to `/` I'll get a hit then, but when I navigate to some dashboard from there, nothing is sent to GA).

Full page load (`/`):

![grafana ghost net-req full-page-load-root redacted 2021-07-07--13-43-54](https://user-images.githubusercontent.com/42101611/124763546-fdd34000-df2b-11eb-9fbd-a2d2b796f715.png)

Full page load (Alerts dashboard):

![grafana ghost net-req full-page-load-alerts-dashboard 2021-07-07--13-50-49](https://user-images.githubusercontent.com/42101611/124763649-1e02ff00-df2c-11eb-9bdc-dc51d0033889.png)

Navigating from `/` to Alerts dashboard:

![grafana ghost net-req navingating-from-root-to-alerts-dashboard redacted 2021-07-07--13-37-52](https://user-images.githubusercontent.com/42101611/124763736-3410bf80-df2c-11eb-96db-616095d02fe7.png)

**Comment by marians** [comment]
Bummer.

I'd say the general "user hits dashboards" info is better than nothing.

Can we actually distinguish customer users from Giant Swarms staff?

**Comment by mig4** [comment]
That's a good point, I'll check that.

**Comment by mig4** [comment]
In the meantime I opened a topic in Grafana Community: https://community.grafana.com/t/grafana-google-analytics-integration/50114

**Comment by mig4** [comment]
Hmm, customer login doesn't work for me, I'm getting an error page with: `login.OAuthLogin(get info from generic_oauth)`.

**Comment by marians** [comment]
In which installation?

**Comment by mig4** [comment]
> In which installation?

Sorry, this is on _ghost_.

**Comment by marians** [comment]
Works for me

**Comment by mig4** [comment]
> Can we actually distinguish customer users from Giant Swarms staff?

OK, I think the answer here is _no_.

I can see you logging in on 9th ~1:45 PM, but the only way I can tell is because there's a new session from Germany. It seems it only knows about location, browser, browser language and OS, so that's not enough to distinguish customers / staff.

I still got no responses on the community forum regarding in-app navigation, so given that and the fact this doesn't even provide enough info, I don't think using Google Analytics makes much sense.

It seems the [analytics-panel plugin requires more setup but it does provide the data we need](https://github.com/giantswarm/roadmap/issues/364#issuecomment-874056670), so we just need to make a decision on if it's worth the effort.

**Comment by marians** [comment]
Let's brainstorm™ if there is another way to get what we want.

Can we use any of our metrics? Maybe from NGINX ingress controller, from dex? Or isn't there an Oauth proxy involved when accessing grafana? (I still wouldn't know how to distinguish customers from GS staff.)

Does Grafana log access somehow?

**Comment by mig4** [comment]
With dex / OAuth, I'm guessing that will depend on whether the access is direct or through Happa as the user would've been already authenticated then, right?

I can check NGINX. Logs may be a potential avenue as I think Grafana logs something on access and I know folks from GitLab were exploring that route. But we'd need a solution to ingest logs to take advantage of that.

**Comment by marians** [comment]
> With dex / OAuth, I'm guessing that will depend on whether the access is direct or through Happa as the user would've been already authenticated then, right?

No, a user coming from happa would technically be the same as one entering the URL manually or clicking a bookmark etc.

**Comment by mig4** [comment]
I checked the options you mentioned.

## Logs

Logs definitely contain enough info to distinguish users as you get a message like this on login:

```
t=2021-07-14T13:05:26+0000 lvl=info msg="Successful Login" logger=http.server User=mig4@...
```

As for which dashboards are accessed, it seems to log a message only the first time a dashboard is loaded:

```
t=2021-07-15T08:59:00+0000 lvl=info msg="Initialized channel handler" logger=live channel=grafana/dashboard/uid/be7wLwgnk address=grafana/dashboard/uid/be7wLwgnk
t=2021-07-15T09:00:20+0000 lvl=info msg="Initialized channel handler" logger=live channel=grafana/dashboard/uid/qMN01qkWz address=grafana/dashboard/uid/qMN01qkWz
```

i.e. if I open a dashboard _"Alerts"_ it logs that message, but when I navigate away and navigate back to the _"Alerts"_ dashboard, or even if I navigate to it from a completely separate session / different user, there are no subsequent messages.

So it would tell us which dashboards are completely unused, but it wouldn't tell us how much a dashboard is used. Note that this means that even if a dashboard is open even once during its entire lifetime you wouldn't be able to distinguish it from one that's used every day.

## nginx

I checked NGINX-IC metrics.

None of them contain user info:

``` sh
 mig-debug  ~  curl --silent --globoff --request GET 'http://prometheus-operated:9090/ghost/api/v1/query?query={ingress="grafana"}' | jq '.data.result[].metric' | grep -c 'mig4'
0
```

None of them contain path info (`qMN01qkWz` is the ID of the nodes overview dashboard which is part of the URL when viewing it in browser):

``` sh
 mig-debug  ~  curl --silent --globoff --request GET 'http://prometheus-operated:9090/ghost/api/v1/query?query={ingress="grafana"}' | jq '.data.result[].metric' | grep -c 'qMN01qkWz' 
0
```

## dex

We run dex without the telemetry endpoint enabled, but I tested things with it enabled (https://github.com/giantswarm/dex-app/pull/92) and the only metrics it exposes are:

```
http_requests_total{code="200",handler="/.well-known/openid-configuration",method="GET"} 2
http_requests_total{code="200",handler="/auth",method="GET"} 1
http_requests_total{code="200",handler="/healthz",method="GET"} 76
http_requests_total{code="200",handler="/token",method="POST"} 1
http_requests_total{code="200",handler="/userinfo",method="GET"} 1
http_requests_total{code="302",handler="/auth/{connector}",method="GET"} 1
http_requests_total{code="303",handler="/approval",method="GET"} 1
```

So not useful here.

## OAuth Proxy

Not used with Grafana.

**Comment by marians** [comment]
Could be that the logs info would be enough already. I think it's not important to know how often a dashboard has been opened by one user during one session. If a dashboard access is counted once, that would suffice. As long as a session ends at some point...

On dex:

Is this actually the metric? `http_requests_total{code="302",handler="/auth/{connector}",method="GET"} 1` and is the actual connector name not visible there?

**Comment by mig4** [comment]
> As long as a session ends at some point...

To clarify, that message in the logs mentioning specific dashboards is something I've only seen once during the lifetime of the backend instance. So it's not related to user session, it seems to be related to just the backend loading the dashboard. It doesn't get repeated on any subsequent new sessions, etc.

> On dex:
> 
> Is this actually the metric? `http_requests_total{code="302",handler="/auth/{connector}",method="GET"} 1` and is the actual connector name not visible there?

Yip, exactly, connector name is not visible.

**Comment by marians** [comment]
Dang. That's not cool.

Next thing we can evaluate is including an arbitrary image src (e. g. invisible PNG) via a HTML panel per dashboard.

Currently we don't have the service for that in place. However we need something like this for happa, too ([biscuit story](https://github.com/giantswarm/giantswarm/issues/18033)).

**Comment by mig4** [comment]
> Next thing we can evaluate is including an arbitrary image src (e. g. invisible PNG) via a HTML panel per dashboard.

That sounds more or less like what the analytics-panel plugin does. Have you seen my [message about the proof of concept I deployed](https://github.com/giantswarm/roadmap/issues/364#issuecomment-874056670)?

**Comment by marians** [comment]
Yes, but not processed. Let's do a call soon, maybe I understand it then.

**Comment by mig4** [comment]
Sure, good idea, I'll talk to Joe and we can organise something maybe tomorrow to hash this out and decide.

**Comment by JosephSalisbury** [comment]
refinement 20/07/21, @marians @mig4 @JosephSalisbury 

- agreement on existing requirements:
   - see which dashboards people have checked out
   - distinguish between GS staff and customers
- not too fussed about advanced features: e.g: time on page, want at least 'number of times person hit page'
- @mig4 demoed analytics panel
- discussed disappointment w/ google analytics integration
- continue w/ analytics panel
- make sure to drop `user_login` and `user_name` labels from ingestion
- check if users can access lists of user data
- don't even send the user details to the backend server / add upstream contribution to make user details configurable
- add analytics panel to dashboards, use giantswarm/dashboards
- build dashboard in cortex to show fancy data for our dashboard usage

**Comment by mig4** [comment]
Some thoughts on splitting tasks:

- create an app for `analytics-panel-server`

  - ensure the service is scraped by Prometheus

- check if customer users can access the `analytics-panel-server` endpoint

  - if no; ensure Prometheus drops `user_login` and `user_email` labels when scraping

- add recording rules to send Grafana analytics data to cortex / Grafana Cloud

- add option to upstream analytics-panel plugin to filter out PII

- add analytics-panel plugin to g8s-grafana deployment

- add analytics-panel to public dashboards

- build a dashboard usage dashboard in GC/cortex

**Comment by mig4** [comment]
@marians I think I have the permissions to delete the Google Analytics properties for Grafana. Let me know if you want me to leave them for now, otherwise I'll clean up later on this week.

**Comment by marians** [comment]
I already deleted the unused one. Feel free to delete the other one, too.

**Comment by mig4** [comment]
Opened an issue upstream to discuss adding an option to avoid including PII in collected data - https://github.com/MacroPower/macropower-analytics-panel/issues/22

**Comment by mig4** [comment]
We discussed an alternative architecture where instead of having the backend app on each installation, we'd have a single global one on the operations cluster, which is similar to how GA works. There are some risks associated with that, but we'll be looking into it as it would simplify deployment and authentication.

**Comment by mig4** [comment]
How do we want to expose the distinction between GS staff and customers on the _dashboard usage_ dashboard?

**Comment by mig4** [comment]
I cleaned up all test artifacts from _ghost_ 🧹

**Comment by JosephSalisbury** [comment]
@snizhana-dynnyk do we wanna move the 'add analytics plugin to private dashboards' to a follow up issue? i think it'd be cool to close out here, and we can prioritise that separately

**Comment by snizhana-dynnyk** [comment]
yes!

**Comment by mig4** [comment]
Well, I started poking around and found some problems. I'll add them to the list + open issues for them.
