### ISSUE TITLE
Offer csi driver nfs as a managed App

### ISSUE THREAD

**Issue by gawertm** [giantswarm/roadmap#3662]
```[tasklist]
### Tasks
- [x] Create app repo
- [x] Setup vendir to sync with upstream charts
- [ ] https://github.com/giantswarm/roadmap/issues/3737
- [x] Retag upstream images to gsoci to pull from cached registry
- [x] add policy exception to allow needed settings
- [x] look into alerting / monitoring
- [x] Adding to managed apps catalog
- [x] providing regular patches (renovate?)
- [x] release
- [x] prevent snapshotter from erroring
```

**Comment by anvddriesch** [comment]
There is a PR with a polex which allows deploying the app to clusters.
I have also looked into metrics. Some components of the app do include metrics. However, the chart does not come with a service monitor or anything so I don't think they would be scraped. We would need to add it if there is a need. Obviously we get basic app monitoring.
It appears that renovate updates vendir by default (since this optional setting exists https://github.com/giantswarm/renovate-presets/blob/main/disable-vendir.json5 ) but we need to try this
