### ISSUE TITLE
Implementation of log-based alerting

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3679]
### Motivation

Based on our initial investigation in [roadmap#3178](https://github.com/giantswarm/roadmap/issues/3178), introducing Multi tenancy [roadmap#3448](https://github.com/giantswarm/roadmap/issues/3558) and storing logs in the right tenants will also allow us to create alerts within those tenants based on logs. This allows customers to not just include metrics but also log information in their alerting rules.

### Todo

*   [ ] Implement log-based alerting for logs
    *   [ ] It should be able to create alerts for logs on the MC and the WCs
    *   [ ] Customers should be able to define alerting rules the same way they do it for metrics
    *   [ ] We need to clarify if we want to/need to handle log-based compared to metric-based alerting rules (different folder structure in prometheus-rules?) 

### Outcome

*   Customers are able to create log-based alerts.

**Comment by QuantumEnigmaa** [comment]
I'm gonna enable the `loki-ruler` component on `golem` and give it a dedicated bucket to try out creating alerting rules in the MC.

**Comment by QuantumEnigmaa** [comment]
After discussing with @hervenicol we can close this issue as the log-based alerting is already implemented everywhere and working. What remains to be done is the implementation of log-based alerting rules in a repo.

**Comment by hervenicol** [comment]
|What remains to be done is the implementation of log-based alerting rules in a repo.

Yes, that's what I assumed this issue would be about 😅

**Comment by Rotfuks** [comment]
Hahah yeah, the outcome here is "Customers are able to create log-based alerts." - is this already achieved? Can I just tell Panamax to create an alert? :D
