### ISSUE TITLE
Log-based alert rules for internal customers

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3680]
### Motivation

Now that it is possible within this epic to create log-based alerts we also should create some of these alerting rules to gain experience and dog-food this new functionality. This will also bring value to teams. 

### Todo

*   [ ] Create an initial set of log-based alerts for us (atlas) and internal customers (like shield or tenet) 
    *   [ ] Check the investigation in [roadmap#3178](https://github.com/giantswarm/roadmap/issues/3178), which lists a set of alerts that might be interesting for internal customers
    *   [ ] Check with the teams first if they still would gain value from those alerts 
*   [ ] Test and learn from the alerting, create follow up stories if there are any issues. 

- The experience for log alerts should be the same as the experience for metric alerts.

### Outcome

*   We collected first experience with log-based alerts and created follow up issues if we ran into issues.

**Comment by fiunchinho** [comment]
[We have a use case for this](https://github.com/giantswarm/giantswarm/issues/32463). We'd like to fire an alert when the `CIDRNotAvailable` event is happening in a cluster. This is an event in the `default` namespace, associated with kubernetes `Nodes`. When this event happens, it means that the cluster can't add more nodes because it ran out of IPs, splitting the pod CIDR between all the nodes. So we want to get alerted when this happens.

**Comment by hervenicol** [comment]
@njuettner also has a use case, described here: https://github.com/giantswarm/roadmap/issues/3857

**Comment by QuentinBisson** [comment]
Tring out an alert with Phoenix here https://github.com/giantswarm/prometheus-rules/pull/1519

**Comment by QuentinBisson** [comment]
First alert is there, closing
