### ISSUE TITLE
Observability Platform: Cost Comparison

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3686]
### Motivation

We sell our platform as cheaper then other solutions - and we believe that it is the cheaper option. It might not have the feature set that other providers have, but do you always need that big feature set? Now we just need to prove that our solution is actually cheaper than other providers by creating a comparison of the estimated cost of our solution compared to competition.

### Todo

*   [x] Create a cost comparison between the GS Observability Platform and other observability solutions
    *   [x] Compare a relative small and a big use case
    *   [x] calculate the cost for both cases for the GS solution
    *   [x] create a dashboard for the cost calculation 
    *   [x] calculate the cost for both cases for the grafana cloud solution
    *   [x] calculate the cost for both cases for datadog
    *   [x] calculate the cost for both cases for dynatrace
    *   [x] calculate the cost for both cases for instana
    *   [ ] calculate the cost for both cases for honeycomb
*   [x] Document the comparison in an easy to use format for sales

### Outcome

*   We have numbers supporting our claim, that we are cheaper (and how much cheaper we are) then typical competition.

**Comment by Rotfuks** [comment]
On going calculations and reasoning behind costs can be found in https://miro.com/app/board/uXjVLbk4oqc=/

**Comment by Rotfuks** [comment]
Documentation of the cost comparison summary in this PR: https://github.com/giantswarm/giantswarm/pull/32129

**Comment by Rotfuks** [comment]
Cost comparison now available here: https://intranet.giantswarm.io/docs/observability/o11yp-product/o11yp-cost-comparison/
