### ISSUE TITLE
Investigate OrganisationCR

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3693]
### Motivation

From our investigation in #3559 we know that we want to organise our tenants based on Grafana organizations with a CR. Now we need to agree on how that CR looks like.

### Todo

*   [ ] Create a CR Draft for the Organization CR
    *   This is a great opportunity to pair!
*   [ ] Play around with it a bit with different potential scenarios and test it out
*   [ ] Present and review the draft with the team

### Outcome

*   We know how an organization cr will look like.

**Comment by QuentinBisson** [comment]
We agreed on the CRD 🥳
