### ISSUE TITLE
Extend O11yOp with Org-Controller

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3695]
### Motivation

With the concept of the multi-tenancy done and documented in #3694 we now need to implement it. 

### Todo

*   [x] Implement the organization management according to the concept in #3694 
*   [x] Create giant swarm organizations through a CR https://github.com/giantswarm/observability-operator/pull/132
*   [x] Create loki and mimir datasources https://github.com/giantswarm/observability-operator/pull/144
*   [x] Configure org\_mapping (do we want to investigate if the settings api works without restarts)? Force a restart?

### Outcome

*   We know can manage multi-tenancy in our observability platform with the grafana organisation crd.

**Comment by QuentinBisson** [comment]
Blocked waiting for reviews
