### ISSUE TITLE
Present the Organisation CR to Grafana Community

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3697]
### Motivation

In our concept we discussed if we want to place the management of organisations within the O11yOp or the Grafana Operator. In general it would be good to have Grafana Resources managed by the Grafana Operator, but we are not sure how happy they will be with the functionality to manage Organisations via Operator. We now decided to go for the O11yOp because there is a smaller risk of getting blocked. But once we are done we should showcase how our multi-tenancy works to the Grafana Community and see if they want the functionality added to the Grafana Operator.

### Todo

* [ ] Present the concept and implementation to the Grafana Community
  * [ ] Reach out in the Grafana Partnership Slack Channel to find out what is the right channel for this
* [ ] Get some feedback if they want it in the Grafana Operator
* [ ] Implement the changes and open a PR if yes

### Outcome

*   We have fewer maintenance effort and gifted a nice functionality back to the oss community.

**Comment by hervenicol** [comment]
We should probalby wait for Grafana 12, which will redefine how it manages config-as-code.

**Comment by QuentinBisson** [comment]
Yes so I woud probably close this issue for now then :)

That means the epic is only down to Dominik rewriting our docs https://github.com/giantswarm/roadmap/issues/3873 now  and we could close 2 epics in the next sprint 👍🏻

**Comment by Rotfuks** [comment]
Alright, we talked to GrafanaLabs about it, good enough of an outcome :D
