### ISSUE TITLE
setup patches for csi-driver-nfs-app

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#3737]
```[tasklist]
### Tasks
- [x] add sync script
- [x] add patches for values and chart
- [ ] add patches to comply with gs rules
```
