### ISSUE TITLE
Deploy and test the Mimir Alert Manager

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3744]
### Motivation
In order to migrate to the new Mimir alertmanager we need to deploy and test an insdtance of the alert manager first.

### Todo

- [x] Deploy and test the mimir alertmanager on a test installation
  - [x] Configure the Ruler to the new Alert Manager 
  - [x] Configure the notification template

### Outcome
- We know how to deploy the mimir alertmanager in the right way

**Comment by QuantumEnigmaa** [comment]
We are currently doing tests on `golem` together with Theo. See https://github.com/giantswarm/roadmap/issues/3746#issuecomment-2497949177

**Comment by QuantumEnigmaa** [comment]
As @TheoBrigitte managed to make the ruler communicate with alertmanager, we are now able to deploy and use mimir-alertmanager as our main alertmanager. There is still work to do concerning the automatic loading of its config using the observability-operator but at least we can close this issue.
