### ISSUE TITLE
Release the new Mimir Alertmanager

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3752]
### Motivation
We know how to roll out the Mimir Alertmanager - now we need to announce and do it. 

### Todo
- [ ] Migration
  - [x] Deploy Mimir Alertmanager on giantswarm installations
  - [x] Create custom object storage on customer installations where needed
  - [x] Deploy Mimir Alertmanager on customer installations
  - [x] Switch alerting to Mimir Alertmanager on giantswarm installations
  - [x] Switch alerting to Mimir Alertmanager on customer installations
  - [x] Ensure everything runs smooth
    - [x] Alerts are received on OpsGenie and Slack
    - [x] Grafana Alerting shows rules, notifications policies, and active notifications
  - [ ] Disable old Alertmanager
- [x] Add automation in mc-bootstrap
- [x] Document the change in the architecture in the intranet
- [x] Annonuce the change to the mimir alert manager
  - [ ] ~Check if customers have alerts in place (Dominik can help :))~

### Outcome 
We use the mimir alertmanager everywhere.

**Comment by TheoBrigitte** [comment]
Giantswarm installations deployment

- [ ] gaggle: error giantswarm-gaggle-mimir-alertmanager secret not found
- [x] galaxy
- [x] gazelle
- [ ] gerbil: pod has unbound immediate PersistentVolumeClaims
- [ ] glasgow: AttachVolume.Attach failed for volume "pvc-ae8f6708-6080-4f7a-ae90-77e0f056bea4"
- [ ] glean: not there
- [x] glippy
- [ ] gmc: can't login
- [x] goat
- [x] golem
- [ ] goose: can't login
- [ ] goshawk: can't login
- [ ] goten: can't login
- [x] grizzly
- [ ] grouse: CreateContainerConfigError
- [x] mammoth

Asked Panamax for object storage creation on `tamarin` and `leopard` https://gigantic.slack.com/archives/CE92C4BST/p1737368033954959:

**Comment by TheoBrigitte** [comment]
Customer installations deployment

- [x] alba
- [x] alligator
- [x] armadillo
- [x] avocet
- [x] cedar
- [x] enigma
- [ ] leopard: crashloopbackoff
- [x] sardine
- [ ] tamarin: crashloobbackoff
- [x] violet
- [x] wallaby
- [x] whale

**Comment by TheoBrigitte** [comment]
I checked manually OpsGenie and Slack and alerts are being received from giantswarm installations.
Releasing Mimir Alertmanager to all installations.

**Comment by TheoBrigitte** [comment]
Alerts are received on Slack and OpsGenie

![Image](https://github.com/user-attachments/assets/3b0b1bbf-931c-40fc-be04-33ee11823704)
https://giantswarm.app.opsgenie.com/reports/main
