### ISSUE TITLE
Default Cluster Dashboard for Backstage Integration

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3757]
### Motivation
In backstage we want to link from the list of clusters to the interesting observability insights of that cluster - for this it's worth to think about what dashboard we want to link to from the cluster overview in backstage to land on a meaningful place in Grafana.

### Todo

- [x] Investigate which dashboards we already have in Grafana for cluster overviews
- [x] Investigate what a good dashboard for a cluster overview would be
  - [x] Ask the internet
  - [x] Ask KaaS 
- [x] Create a dashboard if needed with the required info
- [ ] Plan with Honeybadger how to link to that dashboard from backstage
  - selecting the cluster via URI parameter from cluster variable maybe? 

### Outcome
- We have a nice integration from the cluster overview in the portal to the observability platform

**Comment by Rotfuks** [comment]
Here's a list of nice dashboards and metrics we already have around the cluster overview: 
From our already existing Dashboards: 
- https://grafana.grizzly.gaws.gigantic.io/d/sB2wuKu4z/capi-overview?orgId=1&from=now-3h&to=now&var-datasource=default&var-cluster_name=$__all
    - Amount of Clusters and Cluster where state not ready 
    - Number of Nodes

- https://grafana.grizzly.gaws.gigantic.io/d/k8s-apiserver/kubernetes-api-server?orgId=1&from=now-1h&to=now&timezone=UTC&var-datasource=default&var-cluster=grizzly&var-instance=$__all&refresh=1m
    - API Server Availability SLO

- https://grafana.grizzly.gaws.gigantic.io/d/qMN01qkWz/nodes-overview?orgId=1&from=now-15m&to=now&timezone=UTC&var-datasource=default&var-organization=giantswarm&var-cluster=grizzly&refresh=1m
    - Amount of Nodes and more details around nodes

- https://grafana.grizzly.gaws.gigantic.io/d/efa86fd1d0c121a26444b636a3f509a8/kubernetes-compute-resources-cluster?orgId=1&from=now-1h&to=now&timezone=UTC&var-datasource=default&var-cluster=grizzly&refresh=1m
    - Compute Resource usage in cluster (with nice headlines) 

- https://grafana.grizzly.gaws.gigantic.io/d/ff635a025bcfea7bc3dd4f508990a3e9/kubernetes-networking-cluster?var-resolution=5m&var-interval=4h&orgId=1&from=now-1h&to=now&timezone=UTC&var-datasource=default&var-cluster=grizzly&refresh=1m
    - Network information about Cluster

- https://grafana.grizzly.gaws.gigantic.io/d/HuYOZ89mk/management-cluster-overview?orgId=1&from=now-6h&to=now&timezone=UTC&var-datasource=default&var-Applications=label_app%7C%21%3D%7Cvault-exporter&var-Applications=label_app%7C%21%3D%7Cnode-exporter&var-Applications=label_app%7C%21%3D%7Ckube-state-metrics
    - Number of applications
    - Pods deployed per app
    - CPU and Memory Requested, Limits and Allocatable
    - Memory Utilisation per app
    - Throttled CPU per container

**Comment by Rotfuks** [comment]
Here is the survey to find out which metrics are the right one for the cluster dashboard: 
https://docs.google.com/forms/d/14_wW0PBHMqO34wkOe0hepoIl25WZSnEc6xIyYlOy6y0/edit

Here is the survey link to share: 
https://forms.gle/pmnQKdgS4ykKSfmq7

**Comment by Rotfuks** [comment]
And the Survey is closed, here's the results of the relevant questions: 

**General Cluster Info**

- 76,4% for importance 

- Cluster Name - 100%
- Kubernetes Version - 90.9% 
- Cluster Status (Error Rate) - 90.9%

- Cluster Criticality  - 54.5%
- Control Plane Status - 54.5%
- Cluster Age - 18.2%

CPU/Memory
- Usage over Time - 72.7%
- Utilisation in % - 63.6%
- Current Usage - 54.5%

Network Usage
- Network Status - 63.6%
- Bandwidth History - 54.5%

Disc Space 
- Usage over Time - 63.6%
- Current Usage - 54.5%
- Utilisation in % - 45.5%

Running Failed State 
- Pods, Daemon Sets, Stateful Sets - 45.5%
- Not interesting - 27.3%

**Nodes Information**

- 64.7 % for importance

- Node Status (colour coded) - 63.6% 
- Count of nodes - 54.5%
- Count of healthy/unhealthy nodes  - 54.5%

**Per Node**
- Memory/CPU Usage - 90.9%
- Readiness - 63.6%
- Count of Alerts - 45.5%

**Namespaces**

- 64.7% against importance

- Count of applications per namespace - 57.1%

**Deployments / Workloads**

- 45.5% against importance

- Count of alerts per workload - 50%
- Top 5 CPU/Memory intensive workloads - 50%

**Pods**

- 36.4% for importance

- Count of waiting Pods - 54.5%
- Total Count of Pods - 45.5%
- Count of pod per status - 45.5%
- Count of failure reasons - 45.5%

Per Pod
- Node the pod is on - 66.7%
- Name of the pod - 55.6%
- Status of the pod - 55.6%

**Other**

- List of Alerts Names with Status - 90.9%
- Count of Open Alerts - 72.7%

- API Server Availability SLO - 70%
- API Server Request Latency - 70%
- API Server Request Rate - 60%
- Count of API Server Request Codes - 50%

- PVCs not interesting - 85.7%

Recommendations: 
- Events Summary
- Blocking Webhooks, health of (external/upstream) dependencies
- Upgrade Status and history
- Policy complience heuristic

**Comment by Rotfuks** [comment]
Cluster Overview Dashboard can be found on all Installations in the Shared Org under the name "Cluster Overview"
