### ISSUE TITLE
Investigation on Observability Platform API

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3783]
### Motivation
In order to open up our observability platform to be accessible via API we need to find out how to do it :) We already have a managed API-Gateway (Kong) in Giant Swarm or we could just have an ingress, what's best? 

### Todo 

- [x] Investigate how we could open the observability platform api in a secure way
  - [ ] Is Kong a good option? 
  - [x] Is just an ingress the better one? 
  - [x] how does authentication work? 
- [x] Discuss the options in the team and decide for a concept
- [x] Document and share the concept in sig-product/sig-arch 
- [x] Create Follow Up Stories :) 

### Outcome
- We have a concept and know how to open up the observability platform API in a secure way.

**Comment by QuantumEnigmaa** [comment]
So we discussed together with @QuentinBisson and this is the very high-level graph that I made out of this : 

![Image](https://github.com/user-attachments/assets/e1ea85a5-0789-4285-884a-613c98be1a70)

So basically, we would give access to our observability-platform through an "endpoint" which would in fact just redirect requests from the customer's requests (here Adidas) to their own SSO (in Adidas case, it could be their own Kong) before forwarding the requests directly to our Loki or Mimir depending on the nature of the request.

This endpoint could thus be a simple reverse proxy but we'll need to talk with Adidas to see how to handle authentication on their side.

**Comment by QuantumEnigmaa** [comment]
Updated graph after discussion with the whole team : 

![Image](https://github.com/user-attachments/assets/04d69c84-6e04-46f7-9157-c9b6093dd1d0)

**Comment by Rotfuks** [comment]
Lovely, thanks for the work so far @QuantumEnigmaa ! 
What I need from you now to continue getting feedback from the customer is the following: 
1.) Short technical summary of the concept
2.) Short summary of the user experience using the API - what do you need to do, what do we need from you in order for a customer to be able to use the API
3.) Still open questions we need to ask the customer

Thanks!

**Comment by QuantumEnigmaa** [comment]
Ok so : 

- 1 : The observability team will provide an endpoint to grant access to its observability platform. This endpoint will be a simple ingress managed by our nginx controllers on our MC which will redirect incoming requests towards either Mimir or Loki. before forwarding the requests, this ingress will authenticate those against the customer's SSO which should be an OIDC sever.
- 2 : As a user, you will need to add the required headers that the observability team will ask to the requests being forwarded towards the observability platform endpoint. You will also need to provide access to your SSO to this endpoint so that the requests can be authenticated.
- 3 : Not sure yet.

@giantswarm/team-atlas could you help me improving those so that we have the perfect proposals + questions to ask the customer ? 🙏

**Comment by QuentinBisson** [comment]
@QuantumEnigmaa I would maybe propose 1 valie for the ingress. Something like observability.installationbasedomain/loki/read

**Comment by TheoBrigitte** [comment]
I would love to have an example of what this ingress would look like especially for the different routes that will be in there.

**Comment by QuantumEnigmaa** [comment]
I guess using a basic ingress backed by our already running nginx controllers we could use the following for authentication : https://kubernetes.github.io/ingress-nginx/examples/auth/oauth-external-auth/ (once we'll have settled with adidas the authentication part)

**Comment by QuantumEnigmaa** [comment]
I guess this would be a good template : 
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$customer_url/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$customer_url//oauth2/start?rd=$escaped_request_uri"
  labels:
  name: observability-platform-endpoint
  namespace: monitoring
spec:
  ingressClassName: nginx
  rules:
  - host: mimir.glean.azuretest.gigantic.io
    http:
      paths:
      - backend:
          resource:
            apiGroup: networking.k8s.io/v1
            kind: Ingress
            name: mimir-gateway
            namespace: mimir
        path: /metrics
        pathType: ImplementationSpecific
      - backend:
          resource:
            apiGroup: networking.k8s.io/v1
            kind: Ingress
            name: grafana-multi-tenant-proxy
            namespace: monitoring
        path: /logs
        pathType: ImplementationSpecific
            
  tls:
  - hosts:
    - whatever.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
```

**Comment by QuentinBisson** [comment]
I like the idea and thi is quite close to the observability gateway ingress like so:
https://github.com/giantswarm/shared-configs/blob/2781dddbe87ff20399f1aa9af9cd72c40caa8590/default/apps/alloy-gateway/configmap-values.yaml.template#L51

The only thing we need to figure out is the oidc settings from the customer but it's the same issue with the gateway anyway.

I would change:
- the host to be closer to the observability gateway ingress (maybe the observability gateway ingress needs to be updated as well but the 2 needs to be somewhat related)
- forward /logs to loki-gateway as the multi-tenant-proxy is going away.
- I think the paths should be limited to mimir and loki read paths only because otherwise, why do we even provide a gateway for :D

**Comment by QuantumEnigmaa** [comment]
> I think the paths should be limited to mimir and loki read paths only

Yeah it makes sense, but then your previous comment stating to "_forward /logs to loki-gateway_" might be obsolete. In my understanding, we can either : 

- forward `/logs` to `loki-read` and `/metrics` to `mimir-query-frontend`.
- Keep forwarding to both `mimir-gateway` and `loki-gateway` ingresses but enforce the paths to be `/api/v1/read`.

**Comment by QuentinBisson** [comment]
I would prefer the calling to /api/v1/read  but can we do that with an ingress?

**Comment by QuantumEnigmaa** [comment]
After beginning working on the PoC for this, I ended up having the following template : 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://$customer_url/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$customer_url/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
  name: observability-platform-endpoint
  namespace: loki
spec:
  ingressClassName: nginx
  rules:
  - host: observability.g{{ .domain }}
    http:
      paths:
      - backend:
          service:
            name: loki-gateway
            port:
              number: 80
        path: /logs
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - observability.{{ .domain }}
    secretName: observability-platform-endpoint-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://$customer_url/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$customer_url/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
  name: observability-platform-endpoint
  namespace: mimir
spec:
  ingressClassName: nginx
  rules:
  - host: observability.{{ .domain }}
    http:
      paths:
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /metrics/prometheus
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - observability.{{ .domain }}
    secretName: observability-platform-endpoint-ingress-cert
```

Having 2 different ingresses is required (at least if we don't want to overcomplicate things) as an ingress only forward requests to resources in the same namespace as the one it's deployed. 

So we'll have one ingress in the `mimir` ns and one in the `loki` one but both will share the same host so that on the customer side, they still only have to know 1 url.

Also the `rewrite-target` nginx annotation allows the customer to easily write the target url without having to know the specific path.

**Comment by QuentinBisson** [comment]
What does `rewrite-target` actually brings?
Could you show how those needs to be called?

**Comment by QuentinBisson** [comment]
Nice work :)

**Comment by QuentinBisson** [comment]
I'm wondering if using loki.host and mimir.host instead of paths might not be best though as the protocol behind it is quite specific 🤔 

That way we could limit the paths to the read path only? Because if we use those ingresses then we also provide access to the write path right?

**Comment by QuantumEnigmaa** [comment]
You are right concerning the issue that with the template I proposed above, the write path is also allowed. To solve this, I moved towards the following templates : 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://$customer_url/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$customer_url/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
  name: observability-platform-endpoint
  namespace: loki
spec:
  ingressClassName: nginx
  rules:
  - host: observability.golem.gaws.gigantic.io
    http:
      paths:
      - backend:
          service:
            name: loki-read
            port:
              number: 3100
        path: /logs(/|$)(.*)
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - observability.golem.gaws.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://$customer_url/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$customer_url/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  labels:
  name: observability-platform-endpoint
  namespace: mimir
spec:
  ingressClassName: nginx
  rules:
  - host: observability.golem.gaws.gigantic.io
    http:
      paths:
      - backend:
          service:
            name: mimir-query-frontend
            port:
              number: 8080
        path: /prometheus(/|$)(.*)
        pathType: ImplementationSpecific

  tls:
  - hosts:
    - observability.golem.gaws.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
```

With this, only the requests towards the read components from either loki or mimir are allowed while keeping the simplicity on the customer side.

**Comment by QuentinBisson** [comment]
They still have to call the specific paths of loki right? I would love to discuss that as a team tomorrow :)

**Comment by QuantumEnigmaa** [comment]
It depends how you see it. If one considers that the customers will mostly use this endpoint by going through their own grafana, then they only have to remember the `/prometheus` and `/logs` path as grafana automatically adds the rest of the path.

However, if they use other apps to access the data then yes indeed they'll have to call the full path. 

I decided to go with these templates because I assumed that the main use case for the customers would be the grafana one and also becaused I noticed that when using grafana to access monitoring data, it uses more than 1 path (`/prometheus/api/v1/query`, `/prometheus/api/v1/rule`, `/prometheus/api/v1/healh`...)

**Comment by QuentinBisson** [comment]
Oh right grafana does add the path :(
Then in that case, maybe we should use the hosts to be:

mimir.observability.{domain}
loki.observability.{domain}

and we ditch the /logs and /metrics paths?

Then we can align the ingress we have in say in shared config for loki and mimir.

By the way, in loki, we limit the path to the write path only:

https://github.com/giantswarm/shared-configs/blob/d083dc2ba59c912e0f9e7f6ec85baea978dc7e2c/default/apps/loki/configmap-values.yaml.template#L403

**Comment by QuantumEnigmaa** [comment]
> and we ditch the /logs and /metrics paths?

I already ditched the `/metrics` path to only keep `/prometheus`. 

Concerning your other suggestions, I'm personally not found of having 2 different hosts for our endpoint. To me it doesn't match the image of an observability-platform api, hence I would rather keep the architecture of having 1 host with different paths. 

> By the way, in loki, we limit the path to the write path only

True, but that's for the ingress we're already using internally to allow logging-agents to write to Loki. If I understood correctly, for now the observability-platform API should only allow read access to the customer so that he can access our observability data. That's why it makes more sense to me to have a separate ingress for the write and read path in loki. Even more so since in the customer case, we'll have to use his own oauth provider to authenticate incoming requests.

**Comment by QuentinBisson** [comment]
> > and we ditch the /logs and /metrics paths?
> 
> I already ditched the /metrics path to only keep /prometheus.

> Concerning your other suggestions, I'm personally not found of having 2 different hosts for our endpoint. To me it doesn't match the image of an observability-platform api, hence I would rather keep the architecture of having 1 host with different paths.
> 

Well I also meant the /prometheus but let's discuss that during refinement and make a team decision :)

> By the way, in loki, we limit the path to the write path only
> 
> True, but that's for the ingress we're already using internally to allow logging-agents to write to Loki. If I understood correctly, for now the observability-platform API should only allow read access to the customer so that he can access our observability data. That's why it makes more sense to me to have a separate ingress for the write and read path in loki. Even more so since in the customer case, we'll have to use his own oauth provider to authenticate incoming requests.

I think you misunderstood me :)
By that I meant that you can enforce the loki/v1/read or smth in the ingress path and not use the rewrite target capabilities like so:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://$customer_url/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$customer_url/oauth2/start?rd=$escaped_request_uri
  labels:
  name: observability-platform-endpoint
  namespace: loki
spec:
  ingressClassName: nginx
  rules:
  - host: observability.golem.gaws.gigantic.io
    http:
      paths:
      - backend:
          service:
            name: loki-gateway
            port:
              number: 3100
        path: /loki/v1/api/read                                      # <- See this without the /logs (because we need to put the loki path anyway right? Then the rewrite annotations are not needed because we can only call this path on the gateway as well
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - observability.golem.gaws.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
```

**Comment by QuantumEnigmaa** [comment]
Following today's refinement, we decided to keep a single host for both ingresses but instead of relying on regex paths and forwarding requests to the read components (either the loki's or mimir's ones) the ingresses will now only forward requests to the gateway components with a list of hard-coded paths used for read operations. 

This will give the following templates : 
```yaml
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-giantswarm
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/auth-url: https://$customer_url/oauth2/auth
    nginx.ingress.kubernetes.io/auth-signin: https://$customer_url/oauth2/start?rd=$escaped_request_uri
  labels:
  name: observability-platform-endpoint
  namespace: mimir
spec:
  ingressClassName: nginx
  rules:
  - host: observability.golem.gaws.gigantic.io
    http:
      paths:
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/labels
        pathType: ImplementationSpecific
      - backend:
          service:
            name: mimir-gateway
            port:
              number: 80
        path: /prometheus/api/v1/label
        pathType: ImplementationSpecific
      [...]
  tls:
  - hosts:
    - observability.golem.gaws.gigantic.io
    secretName: observability-platform-endpoint-ingress-cert
```

**Comment by QuentinBisson** [comment]
![Image](https://github.com/user-attachments/assets/6657d559-fb7b-4f06-a27d-235326cba1a3)

**Comment by QuantumEnigmaa** [comment]
Final architecture graph : 

![Image](https://github.com/user-attachments/assets/1a4f5b64-f557-42e6-9aeb-bf898a5febf6)

**Comment by QuantumEnigmaa** [comment]
Last remaining TODO here : presenting the Observability-Platform API concept with the architecture graph to the Atlas office hour. Or maybe @Rotfuks do you still want us to also present this to the Sig-Arch ?

**Comment by QuentinBisson** [comment]
I think we're good to close this one right? 🎉

**Comment by QuantumEnigmaa** [comment]
Yes, presentation done so let's close this
