### ISSUE TITLE
Observability Platform Changelog

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3788]
### Motivation
We have quite a lot of change in configuration and resources in new versions of the components of our observability platform. In order to make it more transparent what configuration to expect in which versions we need to create a changelog that we update for every new version - or every change in configuration for a version. 
This will make sure that we don't have such a big configuration drift between installations - or at least make sure that we realize it earlier. 

### Todo 

- [x] ~Create a observability platform changelog in https://intranet.giantswarm.io/docs/observability/~ Using https://docs.giantswarm.io/changes/
- [x] Update list of watched atlas repositories for changes
- [ ] ~Document the current state of versions in that changelog~
  - [ ] ~At least document the newest version of components~
  - [ ] ~Add any "older" versions and their potential configurations as far as they make sense to the changelog ~
- [x] Present the changelog and discuss potential simplifications for follow up stories 

### Outcome
- We have a better overview on the versions of our components that we release, the functionality that we could encounter in those releases.

**Comment by Rotfuks** [comment]
Here's a list of possible dynamic configuration: https://github.com/giantswarm/roadmap/issues/3758

**Comment by TheoBrigitte** [comment]
The changes and releases at https://docs.giantswarm.io/changes/, are managed via [giantswarm/docs](https://github.com/giantswarm/docs) repository, updates are automatically generated once a week and submitted for review before being automatically merged ([example](https://github.com/giantswarm/docs/pull/2442)).

I updated the list of our repositories being show on this page via this pull request https://github.com/giantswarm/docs/pull/2448

**Comment by QuentinBisson** [comment]
Anything to do on this @TheoBrigitte ?

**Comment by TheoBrigitte** [comment]
Removed the giantswarm/observability-changelog repository. We're good.
