### ISSUE TITLE
Document how mimir alert manager works

### ISSUE THREAD

**Issue by Rotfuks** [giantswarm/roadmap#3789]
### Motivation
In order for others inside and outside our team to understand how the mimir alertmanager works, we need to make sure that we document it in the intranet. 

### Todo

- [x] Create a documentation of the Mimir Alertmanager in https://intranet.giantswarm.io/docs/observability/
  - [x] Make sure this documentation includes a general "how it works", including an architecture diagram in the context of our observabtility platform
  - [x] Make sure the documentation includes a general "how to use it", explaining the basic interactions with the alert manager, maybe linking to the mimir alertmanager docs

### Outcome
- We have documented and shared the knowledge about the mimir alertmanager

**Comment by QuentinBisson** [comment]
@TheoBrigitte I think you solved that with your PR right?

**Comment by TheoBrigitte** [comment]
> [@TheoBrigitte](https://github.com/TheoBrigitte) I think you solved that with your PR right?

My PR at https://github.com/giantswarm/giantswarm/pull/32446 partially respond to this issue, it does answer the `how to use it` but not much the `how it works`. We'll need to write some more details on how it works along with a diagram to complete this issue.

**Comment by TheoBrigitte** [comment]
Added a section on how Mimir Alertmanager integrates within the Observability platform along with a diagram and further explanations. https://github.com/giantswarm/giantswarm/pull/32529
