### ISSUE TITLE
Migrate AWS cluster management to MAPI

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#388]
Towards https://github.com/giantswarm/roadmap/issues/310

### Description

* All existing functionality in Happa has to be moved to Management API
* Adapt all CLI guides for the Management API to work on AWS

### TODO

- [x] Cluster list on the homepage 
    - [x] Display the list of active clusters
    - [x] Display additional information about nodes and whatnot
    - [x] Display the real cluster description
- [x] Cluster details `Overview` tab 
    - [x] Rename cluster
    - [x] Show stats about worker nodes
    - [x] Show stats about apps
    - [x] Show stats about client certificates
    - [x] Show release information (k8s version, if there's an upgrade available)
    - [x] Add/Edit/Delete labels
    - [x] Show control plane nodes info
    - [x] Show the K8s API URL
    - [x] Display AWS account ID
    - [x] Display creation date
    - [x] Delete cluster
    - [x] Switch to HA CP nodes
- [x] Cluster creation
    - [x] Configure cluster and control plane nodes
- [x] Cluster upgrade
    - [x] Display supported upgrade versions in the release details modal
    - [x] Display updated components
    - [x] Display if a cluster is upgrading
    - [x] Execute an upgrade
- [x] Client certificate management
    - [x] List all client certificates in read-only mode
- [x] Node pool management
    - [x] List
    - [x] Create
    - [x] Rename
    - [x] Update scaling
    - [x] Delete
    - [x] Display real descriptions
    - [x] Configure and display the usage of similar instance types
    - [x] Configure and display the usage of spot instances
- [x] App management
	- [x] Display real cluster descriptions in the app installation cluster picker
- [x] Update CLI guides
	- [x] Modify node pool
	- [x] Delete node pool
	- [x] Create client certificates (the guide itself doesn't need updating, we just need to only display the guide if the cluster is on release `v16.0.1` or newer, and if it is in the organization namespace)
	- [x] Delete cluster

**Comment by marians** [comment]
Some differences on AWS compared to the MAPI based Azure UI:

In general, let's assume that all **CLI guides** require adaptation for AWS.

On a high level, these are the functions that are different:

- AZ placement: no "not specified" option
- HA control planes
- Similar instance types
- Spot node pools have different config

Broken down to UIs, here is how these functions surface:

- **Cluster creation form**
  - Single node vs. HA control plane
  - AZ placement does not offer "not specified" option
- **Cluster detail page: Overview**
  - Display: control plane can be either HA or single node
  - Dialog for switching from single node to HA
- **Cluster detail page: Worker nodes**
  - Node pools can use several instance types ("Similar instance types enabled"), while only one on Azure
  - On-demand base capacity is displayed in a tooltip
  - Number of spot instances should be displayed (On Azure we only show a check mark if Spot is enabled, but not the count)
- **Node pool creation form**
  - Checkbox for enabling the use of similar instance types
  - Availability zone selection does not contain "not specified" option
  - Different spot instances options

**Comment by axbarsan** [comment]
Aaaand... done ✅
