### ISSUE TITLE
AWS v16.0.0 release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#394]
ℹ️ Team Firecracker is drafting AWS v16.0.0 release to update to Kubernetes v1.21.
Target release date: 2021-10-08
Release PR: https://github.com/giantswarm/releases/pull/784

## Scope
- [x] Kubernetes v1.21;
- [x] Flatcar 2905.2.3;
- [x] [GS controllers with v1alpha3 support](https://github.com/giantswarm/giantswarm/issues/17870);
- [x] [Ensure clusters are created in the organization's namespace](https://github.com/giantswarm/roadmap/issues/387); 
- [x] [Propagate tag.provider.giantswarm.io labels to AWS CNI](https://github.com/giantswarm/giantswarm/issues/18362);
- [x] [AWS operator does not propagate CR tags to S3 buckets](https://github.com/giantswarm/giantswarm/issues/18887);
- [x] TODO: list of components to update;

## Pre-Release
- [x] Create release ticket on [Releases board](https://github.com/orgs/giantswarm/projects/136)
- [x] Make an announcement on #sig-product that team is doing a release. Include a link to the ticket from the release board.
- [x] Make sure release was tested by creating new cluster, upgrading from older version and with HelloWorld app.
- [x] Aggregate release notes from all changed components and add to `README.md` in the release directory.
- [x] Send draft release announcement to #sig-product for review ASAP.
- [x] Verify documentation is up to date.

## Releasing
- [x] Create release PR
[Instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/)
    - [x] Define new release in `release.yaml` file.
    - [x] Activate new release by setting `state` to `active`.
    - [x] Deactivate old release if it's within same major version (`state: deprecated`). Verify with PO if you have doubts.
    - [x] Check versions of all components included. They shouldn't be lower than those in the previous release unless there was a rollback.

[Example PR](https://github.com/giantswarm/releases/pull/318)
- [x] Release relevant operators.
    - [x] Tag release branch.
    - [x] Bump operator version in draft release.
- [x] Make sure that WIP releases in releases repo branch are removed and not merged to master since the master branch is deployed automatically after merging PR and that would make WIP releases visible in customers’ installations which should generally not happen.

## Post-Release
- [ ] Update front-end cluster with the new release.
- [ ] Verify release is available on all installations. You can use [this script](https://github.com/giantswarm/azure-operator/blob/25bf788946c5405532b3b4b76c54b8e685ee291b/scripts/list-releases.sh).
- [ ] Send out release announcement to all customers according to [these instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/#release-notes).
- [ ] PO subscribes to release posts on Slack to get notifications if there are follow-up messages.
- [ ] Close release task on Releases board.

**Comment by njuettner** [comment]
With the next release we should consider to deploy `kiam-watchdog` in all clusters by default, see https://github.com/giantswarm/giantswarm/issues/18118#issuecomment-900130583

**Comment by calvix** [comment]
the release is ready for further progress, I bumped flatcar version to the latest and k8s to 1.21.5
I wen thru all apps and component and updated them all as well, everything looks green so now we need to just deliver the requested features that are missing

**Comment by calvix** [comment]
What about the kiam-watchdog? I guess it would be nice to have it in the release but it does not work in China so we are kinda screwed
