### ISSUE TITLE
Install AWS CNI on a new CAPI Workload Cluster

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#395]
Towards [Create Cluster API for AWS workload clusters from GS management cluster](https://github.com/giantswarm/roadmap/issues/304).

## User Story

- As a giantswarm user, I would like to have AWS CNI installed and configured when a new workload cluster is created with Cluster API in order to have an AWS network optimized cluster.

## Acceptance Criteria

- [x] All pods (except the ones using host networking) are running on AWS CNI subnets.

## Dependencies

- [x] Should AWS CNI be installed using Giant Swarm's App Platform?
- [ ] Should AWS CNI be installed using [CAPI Cluster Resource Sets](https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-resource-set.html)?
- [ ] Something else?

## Tasks

None

**Comment by calvix** [comment]
notes for me
iam permission we need to add to CAPA role
```
ec2:AssociateVpcCidrBlock
ec2:DescribeSecurityGroupRules
ec2:DeleteNetworkInterface
```

**Comment by calvix** [comment]
done
