### ISSUE TITLE
AWS CNI Prefix Delegation

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#396]
Towards https://github.com/giantswarm/roadmap/issues/394.

## User Story

- As a Giant Swarm user, I would like to create a cluster with AWS CNI Prefix Deletegation enabled by default in order to minimize the IP allocation times with AWS CNI.
- As a Giant Swarm user, I would like to enable AWS CNI Prefix Delegation for an existing cluster in order to minimize the IP allocation times with AWS CNI.
- As a Giant Swarm user, I would like to disable AWS CNI Prefix Delegation for an existing cluster in order to rollback to the previous behavior in case issues are encountered with AWS CNI Prefix Delegation.

## Questions

- [x] Should this feature be enabled by default in v16?
- [x] Can this feature be enabled for existing clusters? Are the nodes going to be rolled? 
- [x] Can this feature be disable? Are the nodes going to be rolled?
- [x] What happens if the existing CIDR is not large enough for each network interface to get a prefix?
- [x] What happens if the IPs for an existing cluster are fragmented when this feature is enabled?

## Acceptance Criteria

None

## Dependencies

None

## Tasks

- [x] Figure out what changes are required in our product in order to enable this feature;
- [x] Decide if this feature is enabled by default. If not enabled, how can it be enabled? An annotation?
- [x] Update aws-cni to v1.9.0. Check if newer version exists;
- [x] Update aws-operator with required changes;
- [x] Test globally;
- [x] Test in China.

**Comment by paurosello** [comment]
I just tested this and the node automatically migrated pods to the new "prefixes"

![image](https://user-images.githubusercontent.com/1133954/129760843-f1c279a4-cfe0-4f72-8c06-0d2cd2722ada.png)

It does not require reboot but I guess it requires some empty /28 to actually make the migration so it would not work on a full subnet or one were it doesn't have 8 free IPs in a row

**Comment by paurosello** [comment]
Another thing I tested is having 4x.large (non-compatible) and it just works fine too without the prefixes.

**Comment by alex-dabija** [comment]
Blocked until @paurosello is back from vacation.

**Comment by paurosello** [comment]
Thread with more info 
https://gigantic.slack.com/archives/C02LWG22H7X/p1636629033017700?thread_ts=1636625630.004000&cid=C02LWG22H7X

**Comment by njuettner** [comment]
Created an upstream issue for China: https://github.com/aws/amazon-vpc-cni-k8s/issues/1769

**Comment by alex-dabija** [comment]
The feature is available in AWS v16.1.0 release with the exception of China (AWS doesn't support it in China).
