### ISSUE TITLE
Add support for managing workload clusters in GitOps way

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#410]
## User Story

_- As a customer, I want to manage clusters and apps in a GitOps way so that I can automate this._

## Details, Background

Customers already have access to the management clusters. With Cluster API and maintaining a big amount of CRDs providing a gitops way for managing clusters becomes even more important.

#### Milestone 1. Get MVP ready
- [x] have a call with a customer to agree on a design and make sure all use cases are covered
- [x] POC
- [x] #435
- [x] Install Flux on the management clusters
- [x] #415
- [x] #475

#### Open questions

- [ ] Think about how to integrate our gitops solution w/ kgs and happa (being able to set up gitops super quick via happa )

**Comment by gianfranco-l** [comment]
this is being worked currently for the whole CAPI releases and GitOps UX wg
