### ISSUE TITLE
external-dns: Align to upstream

### ISSUE THREAD

**Issue by ubergesundheit** [giantswarm/roadmap#411]
`external-dns` just released a helm chart (https://github.com/kubernetes-sigs/external-dns/releases/tag/external-dns-helm-chart-1.2.0)

We should investigate if it's worth contributing stuff we have to upstream and switch to the upstream version.

**Comment by weatherhog** [comment]
Attention: This is a default app!

- [ ] compare charts to see what are the differences 
- [ ] align charts step by step
- [ ] check if business logic is implemented in our chart
- [ ] think a way around the business logic

**Comment by mcharriere** [comment]
I'll slowly start to align the chart with upstream.
Business logic will remain there until we define a solution.

**Comment by mcharriere** [comment]
https://gigantic.slack.com/archives/C02EVLE9W/p1670320792773109

we have a requirement to replace the values `aws_access_key_id` and `aws_secret_access_key` with a secret ref.

that should be possible with `extraVolumes` and `env` from upstream. I'll add next that and document the process.

**Comment by mcharriere** [comment]
Status report:
Most of the work for v3 is done but there a few blockers that need attention:
- https://github.com/giantswarm/giantswarm/issues/26851
- https://github.com/giantswarm/giantswarm/issues/26527
- https://github.com/giantswarm/giantswarm/issues/26852
- https://github.com/giantswarm/giantswarm/issues/25029
- Move CRD job to a subchart
- Move VPA and NPs to a subchart

**Comment by mcharriere** [comment]
I'll hold this into the backlog as v3 comes without PSP already. We can wait until the PSP/PSS migration is done.

**Comment by mcharriere** [comment]
This is back on track.

**Comment by mcharriere** [comment]
v3 has been released 

<img src="https://media1.giphy.com/media/RHBHqdYBUmmkw/giphy.gif"/>
