### ISSUE TITLE
Giant Swarm OS Defaults within Cluster API

### ISSUE THREAD

**Issue by puja108** [giantswarm/roadmap#426]
User Story: As a customer, I want to be able to keep relying on the sensible defaults (for security, reliability, and performance) that Giant Swarm currently provides.

The above user story is split into two issues:
1. Sensible defaults pertaining to Kubernetes and other user-space components Giant Swarm manages https://github.com/giantswarm/roadmap/issues/425
2. Sensible defaults pertaining to Operating System underlying the above-mentioned software (this issue)

The split is based on technical challenges upstream that are currently blocking this issue, but are not present for the other one.

```[tasklist]
### Providers
- [ ] https://github.com/giantswarm/roadmap/issues/1995
- [ ] https://github.com/giantswarm/roadmap/issues/1659
- [ ] https://github.com/giantswarm/giantswarm/issues/25295
- [ ] CAPV
- [ ] https://github.com/giantswarm/roadmap/issues/778
```

**Comment by teemow** [comment]
@puja108 do we need this issue still?

**Comment by puja108** [comment]
Yes, we are still using Ubuntu and need to move our existing OS hardening once we have moved to Flatcar with the CAPI providers.

**Comment by puja108** [comment]
just adding an aka and/or pre-req for this issue: Flatcar support in all providers.

cc @stone-z had some relevant comments on Slack about the priority of this, as all our hardening is done for Flatcar and Ubuntu as base OS for CAPI is creating a lot of overwork like in https://github.com/giantswarm/node-exporter-app/issues/172

cc @alex-dabija @gawertm @Rotfuks

**Comment by Rotfuks** [comment]
Flatcar support for CAPZ was merged this week, so it's also supported. 
Ticket to track for the effort is here: https://github.com/giantswarm/roadmap/issues/1659

**Comment by alex-dabija** [comment]
Separate [epic](https://github.com/giantswarm/roadmap/issues/1995) for the work that needs to be done for CAPA.

**Comment by alex-dabija** [comment]
I removed CAPG from the list.

**Comment by Rotfuks** [comment]
The harmonisation of OS Images over all providers will be done in the scope of https://github.com/giantswarm/roadmap/issues/2544 
This story can therefore be closed
