### ISSUE TITLE
multiple Grafanas are not satisfied

### ISSUE THREAD

**Issue by mig4** [giantswarm/roadmap#433]
#inc-2021-08-19-multiple-grafanas-are-not-satisfied

Local/system certificates got overridden in https://github.com/giantswarm/g8s-grafana/pull/325 to fix https://github.com/giantswarm/giantswarm/issues/18208 which prevents containers from being able to connect to any third party TLS-secured sites.

## TODO

- [ ] find a way to inject custom certs without overriding system certs
- [ ] fix g8s-grafana & test
- [ ] get the fix deployed
- [ ] check and clear out silences:
  - [ ] anubis
  - [ ] puma
  - [ ] buffalo

**Comment by snizhana-dynnyk** [comment]
also happening on viking - #inc-2021-08-24-viking-deployment-monitoringgrafana-is-not-satisfied
