### ISSUE TITLE
Bridge gap between user interfaces and the Management API

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#437]
This is an epic driven by SIG UX.

## Concrete goals

1. **Every use case in happa also points to corresponding CP K8s API methods** (kubctl gs, manifests, …). Example: When creating a cluster, users find out how to create the same cluster via the CP K8s API.

2. **Information shown in happa is explained in Control Plane API terms, somehow** (docs, or directly in the UI). I. e. users should be able to look at something in happa and know where to find this in a Control Plane API resource.

## Background

Currently there is a conceptual gap between information represented in user interfaces like happa and whatever users see via the Control Plane K8s API (CP K8s API).

Example: When in Happa users would see one cluster, in the CP K8s API they see six or more interconnected custom resources.

Also when "doing something" (e. g. creating a cluster) in Happa, there is no information that/how the same thing could be achieved using the CP K8s API.

Users using happa should become aware where they can find according information in the CP K8s API, how they can achieve according transactions via the CP K8s API.

## Related issues

- [Promote gsctl, kubectl-gs and API usage in happa](https://github.com/giantswarm/giantswarm/issues/3851) is kind of a successor issue for this one here. It might be one solution for the things we are trying to address here, however it does not address the whole issue.
- [Alignment of domain concepts and field naming across providers](https://github.com/giantswarm/giantswarm/issues/12206) is about the thoughtful design of CRDs, which also influences how big the conceptual gap between UI and CP K8s actually is

## TODO

- [x] https://github.com/giantswarm/giantswarm/issues/16564
- [x] https://github.com/giantswarm/giantswarm/issues/18344
- [x] https://github.com/giantswarm/giantswarm/issues/18343
