### ISSUE TITLE
Add support for disabling Rest API per installation

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#488]
***Towards https://github.com/giantswarm/giantswarm/issues/16364 REST API Sunset***

### Description

Since some customers will move to use SSO in Happa earlier than others - we will be able to disable Rest API and legacy microservices on some installations earlier. So we need to provide a way to do this per installation.

### TODO

- [x] Check how can we utilise Argo CD for this (talk to team Honeybadger)
- azure
  - [x] Add `rest-api-collection` to azure MC fleet provider
  - [x] Apply `rest-api-collection` in azure MCs
  - [x] Move `api` to `rest-api-collection`
  - [x] Remove `api` from `azure-app-collection`
    - [x] app repo
    - [x] collection repo
- aws
  - [x] Add `rest-api-collection` to aws MC fleet provider
  - [x] Apply `rest-api-collection` in aws MCs
  - [x] Remove `api` from `aws-app-collection`
    - [x] app repo
    - [x] collection repo
- kvm
  - [x] Add `rest-api-collection` to kvm MC fleet provider
  - [x] Apply `rest-api-collection` in kvm MCs
  - [x] Remove `api` from `kvm-app-collection`
    - [x] app repo
    - [x] collection repo

**Comment by anvddriesch** [comment]
note: check companyd needed for organization-operator
