### ISSUE TITLE
AWS VPC Flow Logs

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#502]
## User Stories

_- As a cluster admin, I want to enable AWS VPC flow logs when creating a new cluster in order to diagnose security groups, monitor traffic and verify security constraints._

_- As a cluster admin, I want to enable AWS VPC flow logs for an existing cluster in order to diagnose security groups, monitor traffic and verify security constraints._

_- As a cluster admin, I want to disable AWS VPC flow logs for an existing cluster in order to reduce costs._

## Details, Background

At the moment, we have the ability to run a script to enable VPC flow logs for all workload clusters of a given management cluster. This solution is not user friendly, lacks transparency and is only temporary.

A better option would to enable VPC flow logs via customer Kubernetes resources. Such a solution is user friendly and uses a Kubernetes native API to expose features.

Links:
- [AWS VPC Flow Logs](https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html)

## Acceptance Criteria

- [ ] Flow logs are enabled via custom Kubernetes resources for new and existing clusters;
- [ ] Flow logs can be published to a S3 bucket specified by the user;
- [ ] Flow logs can be published to CloudWatch Logs;
- [ ] Flow logs can be disabled. It this case the logs already published will not be deleted.

## Blocked by / depends on

None
