### ISSUE TITLE
Remove rest-api-components from MAPI MCs

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#515]
***Towards https://github.com/giantswarm/giantswarm/issues/16364 REST API Sunset***

### Description

Since some customers will move to use SSO in Happa earlier than others - we will be able to disable Rest API and legacy microservices on some installations earlier. We will do this by moving components to the `rest-api-collection` and removing this collection from the respective installations.

### TODO

- [x] use a test-installation to see which microservices are active / what happens when they are removed
- [x] sum up findings and add to the to-do list which changes have to be made before deprecation
- [x] add rest-api components that will be deprecated to the `rest-api-collection`
  - [x] api 
  - [x] cluster-service
  - [x] tokend
  - [x] userd
  - [x] passage
  - [x] kubernetesd
  - [x] companyd
    - [x] remove dependency in `organization-operator`
  - credentiald - There is no replacement for it at the moment
- [ ] remove `rest-api-collection` from MCs where it is not needed anymore
  - [ ] ginger
  - [ ] gauss
  - [ ] otter

Doc with detailed observations: https://docs.google.com/document/d/1X8nlf2IT2QEjimS_PpvN5JrT4attr9mBQl0a-zC48mw/edit?usp=sharing

**Comment by snizhana-dynnyk** [comment]
I guess we can close this one. The follow up issues are #549 and #550
