### ISSUE TITLE
Archive g8s-grafana

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#518]
obi: grafana version is outdated, using the one in prometheus-operator
see https://gigantic.slack.com/archives/C01UNMNLZD5/p1634302387176300

### TODO
- [x] update the grafana app to the correct version
- [x] move dashboards from g8s-grafana to dashboards (just make it work)
    - keep mixin dashboards
- [x] move from using `g8s-grafana` to `grafana-app`
    - mount dashboards from `dashboards`
    - keep analytics plugin
    - configure OIDC (allowing customers to login)
    - switch over ingress
    - archive g8s-grafana
    - remove g8s-grafana from collections

### Follow up
- [x] 1 dashboard per configmap
- [x] Edit doc: https://github.com/giantswarm/giantswarm/tree/master/content/docs/monitoring/dashboards)

**Comment by weatherhog** [comment]
- [ ] get rid of `g8s-grafana`

**Comment by JosephSalisbury** [comment]
refined - we reckon this is pretty straightforwards, we just need to get on with it (and find out about what breaks)

**Comment by QuentinBisson** [comment]
Waiting for this https://github.com/giantswarm/grafana-app/pull/52 
then we can start removing g8s-grafana from collection and merge everything
