### ISSUE TITLE
Investigate credentials in org namespace

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#522]
### Description

Some customers asked about having the credentials for their org in the org-namespace. Let's see if this is possible.

### TODO

- [x] Simply try out copying default credentials to org-namespace and using it for an org
- [x] Find out what does not work / what has to be done and possibly bring this into phoenix
- [ ] Update relevant docs.
