### ISSUE TITLE
Marketing plan for the intersection of the roadmap with customer/market interest in features.

### ISSUE THREAD

**Issue by Oshratn** [giantswarm/roadmap#523]
Example: Cluster API for OpenStack

Create a template:
- [ ] Criteria for things we want to communicate (e.g. OpenStack) based on customer requests and refine along the way with additions of cool things from the product (e.g. CAPI)
- [ ] Match activities and content to the funnel
- [ ] Evangelize with product owners
