### ISSUE TITLE
AWS v16.1.0 release

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#526]
ℹ️ Team Phoenix is drafting AWS v16.1.0 release to update to several components .
Target release date: 2021-12-02
Release PR: https://github.com/giantswarm/releases/pull/859

## Scope
- [x] [AWS CNI Prefix Delegation](https://github.com/giantswarm/roadmap/issues/396);
- [x] [aws-ebs-csi with volume snapshots support](https://github.com/giantswarm/giantswarm/issues/19212);
- [x] [flatcar 2905.2.6](https://www.flatcar-linux.org/releases/);
- [x] [kiam-watchdog](https://github.com/giantswarm/giantswarm/issues/18118);
- [x] [Fix for `AWS Subnet Tagging breaks AWS-load-balancer-controller`](https://github.com/giantswarm/giantswarm/issues/19854); 

## Pre-Release
- [x] Create release ticket on [Releases board](https://github.com/orgs/giantswarm/projects/136)
- [x] Make an announcement on #sig-product that team is doing a release. Include a link to the ticket from the release board.
- [x] Make sure release was tested by creating new cluster, upgrading from older version and with HelloWorld app.
- [x] Aggregate release notes from all changed components and add to `README.md` in the release directory.
- [x] Send draft release announcement to #sig-product for review ASAP.
- [ ] Verify documentation is up to date.

## Releasing
- [x] Create release PR
[Instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/)
    - [x] Define new release in `release.yaml` file.
    - [x] Activate new release by setting `state` to `active`.
    - [ ] Deactivate old release if it's within same major version (`state: deprecated`). Verify with PO if you have doubts.
    - [ ] Check versions of all components included. They shouldn't be lower than those in the previous release unless there was a rollback.

[Example PR](https://github.com/giantswarm/releases/pull/318)
- [ ] Release relevant operators.
    - [ ] Tag release branch.
    - [ ] Bump operator version in draft release.
- [ ] Make sure that WIP releases in releases repo branch are removed and not merged to master since the master branch is deployed automatically after merging PR and that would make WIP releases visible in customers’ installations which should generally not happen.

## Post-Release
- [ ] Update front-end cluster with the new release.
- [ ] Verify release is available on all installations. You can use [this script](https://github.com/giantswarm/azure-operator/blob/25bf788946c5405532b3b4b76c54b8e685ee291b/scripts/list-releases.sh).
- [ ] Send out release announcement to all customers according to [these instructions](https://intranet.giantswarm.io/docs/dev-and-releng/releases/#release-notes).
- [ ] PO subscribes to release posts on Slack to get notifications if there are follow-up messages.
- [ ] Close release task on Releases board.

**Comment by alex-dabija** [comment]
The release is out.
