### ISSUE TITLE
Decide how to deal with global flag names in kubectl-gs

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#532]
`kubectl` provides some flags that are used with many commands. Examples:

- `--cluster`: The name of the kubeconfig cluster to use
- `--context`: The name of the kubeconfig context to use
- `-n`, `--namespace`: If present, the namespace scope for this CLI request

See `kubectl options` for more.

We are already using flags with the same name in some of our commands and wonder what the consequence of this is. Specifically:

- If we use a flag (e. g. `--namespace`) for a specific purpose in a plug-in command, will it prevent us from using the flag in the sense of the common options?
- Does the position/order of flags have an impact on the command execution? Ideally it should not.

## Example: `kubectl gs template app`

<details>

```
Template App CR.

Usage:
  kubectl gs template app [flags]

Flags:
      --app-name string                 Optionally set a different name for the App CR.
      --catalog string                  Catalog name where app is stored.
      --cluster string                  Name of the cluster the app will be deployed to.
      --defaulting-enabled              Don't template fields that will be defaulted. (default true)
  -h, --help                            help for app
      --name string                     Name of the app in the Catalog.
      --namespace string                Namespace where the app will be deployed.
      --namespace-annotations strings   Namespace configuration annotations in form key=value.
      --namespace-labels strings        Namespace configuration labels in form key=value.
      --user-configmap string           Path to the user values configmap YAML file.
      --user-secret string              Path to the user secrets YAML file.
      --version string                  App version to be installed.

Global Flags:
      --debug   Toggle debug mode, for seeing full error output.
```

</details>

Here, the flags `--cluster` and `--namespace` clash with the purpose specified by common options.

## Example: `kubectl gs update app`

<details>

```
Update App CR.

Updates given app with the provided values.

Options:
  --name <name>              App CR name to update.
  --namespace <cluster>      Cluster to update the app on.
  --version <version>        New version to update the app to.

Usage:
  kubectl gs update app --name <app-name> --namespace <cluster-namespace> --version <updated-app-version> [flags]

Examples:
  # Display this help
kubectl gs update app --help

# Update app version
kubectl gs update app --name hello-world-app --namespace ab01c --version 0.2.0

Flags:
      --allow-missing-template-keys    If true, ignore any errors in templates when a field or map key is missing in the template. Only applies to golang and jsonpath output formats. (default true)
      --as string                      Username to impersonate for the operation
      --as-group stringArray           Group to impersonate for the operation, this flag can be repeated to specify multiple groups.
      --cache-dir string               Default HTTP cache directory (default "/Users/marian/.kube/http-cache")
      --certificate-authority string   Path to a cert file for the certificate authority
      --client-certificate string      Path to a client certificate file for TLS
      --client-key string              Path to a client key file for TLS
      --cluster string                 The name of the kubeconfig cluster to use
      --context string                 The name of the kubeconfig context to use
  -h, --help                           help for app
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS connections insecure
      --kubeconfig string              Path to the kubeconfig file to use for CLI requests.
  -n, --namespace string               If present, the namespace scope for this CLI request
  -o, --output string                  Output format. One of: json|yaml|name|go-template|go-template-file|template|templatefile|jsonpath|jsonpath-file.
      --request-timeout string         The length of time to wait before giving up on a single server request. Non-zero values should contain a corresponding time unit (e.g. 1s, 2m, 3h). A value of zero means don't timeout requests. (default "0")
  -s, --server string                  The address and port of the Kubernetes API server
      --template string                Template string or path to template file to use when -o=go-template, -o=go-template-file. The template format is golang templates [http://golang.org/pkg/text/template/#pkg-overview].
      --tls-server-name string         Server name to use for server certificate validation. If it is not provided, the hostname used to contact the server is used
      --token string                   Bearer token for authentication to the API server
      --user string                    The name of the kubeconfig user to use

Global Flags:
      --debug   Toggle debug mode, for seeing full error output.
```

</details>

Here the `--namespace` flag is defined both for the command and as a common flag.

## Tasks
- [x] Change the existing conflicting local flag names and update command documentation
- [x] Document global flags
- [x] Investigate whether there is a way to automate and enforce this (e.g. in CI)
- [x] Update CLI guide for installing an app in the web UI

**Comment by kuosandys** [comment]
As of the latest kubectl-gs release (https://github.com/giantswarm/kubectl-gs/releases/tag/v2.19.0), we don't observe the local `--namespace` flag anymore (e.g. in the `template app` command). Has this been overwritten, or has functionality been accidentally removed?

**Comment by marians** [comment]
The `template app` command has several local flags which are in conflict with the global flags. It seems however that local overrides global.

This command

```
kubectl gs template app --catalog=catalog --name=name --namespace=namespace --cluster=cluster --version=1.2.3
```

produces this output:

```yaml
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  name: name
  namespace: cluster
spec:
  catalog: catalog
  kubeConfig:
    inCluster: false
  name: name
  namespace: namespace
  version: 1.2.3
```

So the `--cluster` and `--namespace` flags are interpreted as local, making it impossible to use the global flags with the same name.

Positioning does not change this. The following command produces the same result as the one above:

```
kubectl gs --cluster=cluster template app --catalog=catalog --name=name --namespace=namespace --version=1.2.3
```

**Comment by kuosandys** [comment]
**Refinement August 19th 2022**

Ideas:
- Rename local flags that duplicate global flags (we don't have control over the global/upstream flags, but we can change the local ones)
- We need a way to prevent kubectl-gs developers from introducing conflicting flags without relying on Team Rainbow review on every PR
  - Overriding a persistent flag with a flag is allowed in cobra

Actions:
- [ ] Change the existing conflicting local flag names and update command documentation
- [ ] Document global flags
- [ ] Investigate whether there is a way to automate and enforce this (e.g. in CI)

**Comment by vvondruska** [comment]
Notes from refinement
- Rename `--namespace` to `--target-namespace`
- Rename `--cluster` to `--cluster-name`
- Update usage and documentation
- Warn users in case they use `--cluster` and `--namespace` that hey are deprecated and will be removed in the new major version
- Investigate if it's possible to remove `--cluster` and `--namespace` from the global flags and mark them as deprecated in the local flags
- Investigate which flags are available in the `kubectl-gs update app` command and align the Usage output
