### ISSUE TITLE
ignition operator

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#55]
## User Story

As a giant swarm  PE I want to ship releases faster by writing lesser code and do less PRs.

## Details, Background

To facilitate the creation of releases in an automated way without too many commits necessary we want to create a k8s-cloud-config operator. 
The operators responsibility is to render the cloud / ignition config  for all providers.

### Suggestion: 
Manage all versions in release repository in releases.yaml. Cloud config operator would determine the versions to use by the g8s release defined in the cluster CR.
Currently all versions in releases.yaml are operators (authority key). We can keep this logic if we introduce a new like versionAuthority

Questions:
Do we want to be able to influence the versions by the CloudConfig CR?

## Deliverables

- Deployed software
- Monitoring/alerting
- API changes
- Public documentation
- Internal documentation

## Host/guest cluster

- Host cluster

## Provider

- AWS
- Azure
- KVM / bare metal

## Customers driving/requiring this

All customers will benefit from faster releases.

## Remaining tasks

- [ ] [Add ignition-operator to control plane catalog](https://github.com/giantswarm/giantswarm/issues/8647)
- [ ] [Add ignition-operator to the `authorities` in `releases`](https://github.com/giantswarm/giantswarm/issues/8648)
- [ ] [Wire ignition-operator in provider operators](https://github.com/giantswarm/giantswarm/issues/8650)

**Comment by puja108** [comment]
closing as with CAPI we will not have the current issues around k8scloudconfig anymore
