### ISSUE TITLE
Configure CPI for CAPO clusters

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#585]
We need to install OpenStack CPI. This should allow us:

- Creating Services of type LoadBalancer
- Use CNI

This should probably be installed using the App Platform. It may be tricky as nodes may be tainted after creation so possibly we'll have to add some tollerations to App Platform operators.

- [x] app-creation (cloud-provider-openstack-app)
- [x] deploy with cofiguration 
  - [x] where to get configuration from (subnet id for lb) 
  - [x] decide on which component does it cluster-app-operator?
  - [ ]

**Comment by tfussell** [comment]
Done.
