### ISSUE TITLE
Configure CAPO clusters OIDC access

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#586]
The OIDC access should be configured for both MC and WC in the same way. I guess we want to configure the same GitHub application for both. I'm not sure if we should run dex in each cluster or only in the MC. That should be compatible with AWS/Azure if implemented there already.https://github.com/openstack-exporter/openstack-exporter 

*MVP*

- [x] Add OIDC flags to the cluster-openstack app 
- [x] Add OIDC defaults to the config Repo
- [x] Expose WC cluster CA in the cluster values configmap (needed by dex app to talk to the API) https://github.com/giantswarm/cluster-apps-operator/pull/169
- [x] Add certs SAN for the WC API [like we do for the MC](https://github.com/giantswarm/capo-mc-bootstrap/blob/main/helm/capo/templates/kubeadmcontroleplane.yaml#L15-L17) @pipo02mix https://github.com/giantswarm/cluster-openstack/pull/57 
- [x] Fix DNS operator Openstack to find nginx svc based on label enabling the right creating of the ingress recordset https://github.com/giantswarm/dns-operator-openstack/pull/52
- [x] Add kubectl gs flags to enable OIDC API server flags with customer configuration @pipo02mix https://github.com/giantswarm/kubectl-gs/pull/679
- [x] Specify in the docs how to set up NGINX (`.cluster.profile`) in the case is only used for dex @pipo02mix https://github.com/giantswarm/docs/pull/1315

*Next steps*
 
- [ ] Adapt kgs login to allow us to connect to WC via SSO
- [x] Resolve how GH Oauth App will be created https://github.com/giantswarm/giantswarm/issues/20825 (by now we are not embedding our configuration in dex by default)

**Comment by kopiczko** [comment]
I'm uncertain how we want to deal with that now. Possibly dex should become a core app. I created a card for the KaaS sync.

**Comment by cornelius-keller** [comment]
Question for Kaas sync:
- do we want to make dex a default app for all CAPI clusters and use OIDC to create kubeconfig

**Comment by alex-dabija** [comment]
From KaaS Sync:

We wanted to have this already for some time now. 

@giantswarm/team-rainbow is going to evaluate if we can have Dex as a default app for every CAPI workload cluster.

An alternative way to generate kubeconfig is also required when Dex fails (the default admin kubeconfig can be this alternative).

**Comment by pipo02mix** [comment]
Good catch we need to remove the old bullet point. (done)

**Comment by pipo02mix** [comment]
This is done, the remaining task will be addressed by rainbow here https://github.com/giantswarm/roadmap/issues/489
