### ISSUE TITLE
Install CNI in OpenStack clusters

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#588]
We need to install CNI in the same way in both the MC and WCs.

This should be done using the App Platform. Most likely we'll need to bootstrap in hacky way in the MC but once it's bootstrapped it should be managed exactly the same way.

TODO:

- [x] Create App installing CNI https://github.com/giantswarm/calico-app
- [x] Take ownership of `calico-app` https://github.com/giantswarm/giantswarm/issues/19478
- [x] Add `calico-app` to OpenStack v20 release https://github.com/giantswarm/releases/blob/master/openstack/v20.0.0-alpha1/release.yaml#L7
- [x] Create a WC and ensure Calico starts correctly (i.e. nodes are ready, pods can receive IPs), ~currently blocked on https://github.com/giantswarm/giantswarm/issues/19400~

**Comment by tfussell** [comment]
Done.
