### ISSUE TITLE
Ensure DNS delegations for CAPO Workload Clusters

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#596]
We can probably setup DNS for the Management Cluster manually. But according to https://gigantic.slack.com/archives/C95NTB55M/p1632994043061900 it should be a flat structure from now on.

We also need to ensure this is compatible with what Team Phoenix is doing/going to do.

We also are not bound to OpenStack DNS implementation. We can use any other provider including AWS/Azure/CloudFlare, remembering that `gigantic.io` is mostly configured in our AWS account.

### TODO

- [ ] gather requirements
   - [ ] what do we need dns for (api-server, ingress ...) 
   - [ ] sync with team phenix 
   - [ ] spec for flat dns structure agreed on in croatia

**Comment by yulianedyalkova** [comment]
Closing this one as the main implementation is ready, will create subissues for the improvements/bug fixe.
