### ISSUE TITLE
Build OpenStack images for CAPI

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#597]
#### User Stories
-  As a giant swarm user on CAPO I want the relevant CAPO images to be available in all my Openstack installations so that I can use them to create clusters 
- As a giant swarm employee I want a documented and reliable way to create images so that I know how to build and release them for updates and security fixes
- As a giant swarm user on CAPO I want to know who and how the images in my clusters are build, so that I can be sure that they don't contain any malicious parts and that the OS and software is up to date. 

### TODO

- [x] decide which  gs cluster  to use  for Image creation job to have acceleration
   - We run it on operations cluster `rfjh2`
- [x] check if s3 compatible endpoint is accessible
- [x] Create Tekton job with parameters to build the image and sync to s3
   - [ ] optional: create metal nodepool for acceleration of the process
- [x] find a solution to check if image is correct and not corrupted (checksum)   
- [ ] documentati on how to run the job (maybe github repo containing a template)

### Acceptance Criteria
- [x] We have a documented automated auditable way to build images
- [x] Images are automatically pushed to s3 compatible endpoint after build
- [ ] everyone in team rocket knows how to do it. 
- [ ] image sha / signature is back traceable to a build job

### Open questions
- how do we know which images are already build via the old process?

**Comment by ericgraf** [comment]
There currently are two image types we are building and adding to OpenStack Projects.

# Building images

## Upstream Ubuntu capo image

Qemu support added to upstream docker image: https://github.com/ericgraf/openstack-image-generator/blob/main/build-image/Makefile
- Docker Environment variables are used to set k8s version and Packer accelerator 
- The different packer accelerator options can be found here: https://www.packer.io/plugins/builders/qemu#accelerator

Build configuration changes are set in the entrypoint.sh here: https://github.com/ericgraf/openstack-image-generator/blob/main/build-image/entrypoint.sh

Here is a link to the upstream build script: https://github.com/kubernetes-sigs/image-builder/tree/master/images/capi


## Flatcar bastion image

Script to build bastion image is stored here:
https://github.com/giantswarm/capo-mc-bootstrap/blob/main/scripts/openstack/build-bastion-image.sh

We should convert .img files to qcow2 after building the image by running the below command.  This is currently not being done.
```bash
qemu-img convert -f raw -O qcow2 image.img image.qcow2
```

# sha256sum of images

After the image is done please include the sha256sum file and upload that to the s3 endpoint as well

```bash
image_name=<filename>
sha256sum $image_name > ${image_name}.sha256sums
```

## Verifying sum
This can be done by running the below command
```bash
sha256sum -c ${image_name}.sha256sums
```

# Uploading images to s3

giantswarm bucket is already created and present on remote s3 endpoint.

## initial aws s3 cli profile

s3 secrets can be found in lastpass
```bash
aws configure --profile=ceph
```

## create bucket ( already done )

```bash
aws --profile=ceph --endpoint="<endpoint url>"  s3 mb s3://giantswarm`
```

## upload files

```bash
export image_name=<filename>
aws --profile=ceph --endpoint="<endpoint url>"  s3 cp ${image_name} s3://giantswarm/${image_name}/`
aws --profile=ceph --endpoint="<endpoint url>"  s3 cp ${image_name}.sha256sums s3://giantswarm/${image_name}/`
```

**Comment by ericgraf** [comment]
Initial code can be found here. https://github.com/giantswarm/capi-image-builder/pull/2

**Comment by ericgraf** [comment]
https://github.com/giantswarm/capi-image-builder has been created and automatically builds and publishes the images for capo.
