### ISSUE TITLE
Create an App installing CAPO controllers

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#598]
Tasks:
- [x] delete app
- [x] recreate from template repo
- [x] create pr based on CAPV controller app
- [x] link PR to this issue
- [x] sync with team phoenix
- [x] add crd-install job to CAPO controller app ([example](https://github.com/giantswarm/cluster-api-provider-aws-app/tree/master/helm/cluster-api-provider-aws/templates/crd-install))
   - [x] adopt existing (`clusterctl` based ) deployment
   - [x] fix RBAC
   - [x] create make targets
   - [x] testing

## Rollout

~Prereq: Check if namespaces other than `giantswarm` are ok for CAPI/CAPO resources - [slack thread](https://gigantic.slack.com/archives/C031TNG171N/p1651122229828679)~

### 1. CAPO
1. ensure CAPO-version match with current main branch of capo-app
2. apply labels on existing CAPO objects to make app-operator workable on existing resources
      ```
      kubectl patch mutatingwebhookconfiguration capo-mutating-webhook-configuration --type=json -p='[{"op": "add", "path": "/metadata/labels/app.kubernetes.io~1managed-by", "value": "Helm"},{"op":"add","path":"/metadata/annotations","value":{}},{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-name", "value": "cluster-api-provider-openstack"},{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "giantswarm"}]'
      kubectl patch validatingwebhookconfiguration capo-validating-webhook-configuration --type=json -p='[{"op": "add", "path": "/metadata/labels/app.kubernetes.io~1managed-by", "value": "Helm"},{"op":"add","path":"/metadata/annotations","value":{}},{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-name", "value": "cluster-api-provider-openstack"},{"op": "add", "path": "/metadata/annotations/meta.helm.sh~1release-namespace", "value": "giantswarm"}]'
    ```

3. scale existing CAPO deployment to zero
     ```
      k scale deploy/capo-controller-manager --replicas=0 -n capo-system 
     ```
4. delete webhook (as we rename with prefix `zzz-` capi will still use the old webhook as of alphabetic ordering)
     ```
      k delete mutatingwebhookconfigurations capo-mutating-webhook-configuration         
     ```

5. release CAPO app (will trigger the rollout)
6. cleanup leftover resources
     ```
      k delete clusterrole capo-system-capo-manager-role
      k delete clusterrolebinding capo-system-capo-manager-rolebinding
      k delete namespace capo-system
     ```
7. After all MCs are done modify capo-mc-bootstrap to deploy CAPO via app

**Comment by kopiczko** [comment]
Today we upgraded two clusters with @bavarianbidi 

- [x] gubble
- [x] halley


I'm planning to do 

- [ ] helios
- [ ] hyperion

later today.

Then @bavarianbidi is going to release the `cluster-api-provider-openstack-app` repo to start managing the app (we create manually for now) with flux and adapt `mc-bootstrap` to use the app on fresh MCs.

Currently the app looks like this (halley):

```
$ k --context gs-halley get app -n giantswarm cluster-api-provider-openstack
NAME                             INSTALLED VERSION                                CREATED AT   LAST DEPLOYED   STATUS
cluster-api-provider-openstack   0.0.0-72ae9d9729ad6bb7fd5a09b5920b3c77ff7828a8   25m          25m             deployed
```
