### ISSUE TITLE
[EPIC] Manage Clusters on OpenStack using CAPO

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/roadmap#600]
## User Story
- As a giant swarm customer I want to create kubernetes clusters on openstack so that I can make use of my existing openstack infrastructure.

## Details, Background

When talking to new customers especially in the telecommunication industry, but also in manufacturing and retail we see a demand to manage clusters on existing openstack infrastructure. With our move to Cluster API we will be able to provide this functionality using controllers provided by the upstream community.

## Blocked by / depends on

Monitor CAPI workload Clustes https://github.com/giantswarm/roadmap/issues/313
Default apps for CAPI Clusters https://github.com/giantswarm/roadmap/issues/320

# Tasks / Milestones

🍕 **Milestone: Alpha** 🍕

- [x] https://github.com/giantswarm/roadmap/issues/576
- [x] https://github.com/giantswarm/roadmap/issues/577
- [x] https://github.com/giantswarm/roadmap/issues/578
- [x] https://github.com/giantswarm/roadmap/issues/579
- [x] https://github.com/giantswarm/roadmap/issues/580
- [x] https://github.com/giantswarm/roadmap/issues/581
- [x] https://github.com/giantswarm/roadmap/issues/582
- [x] https://github.com/giantswarm/roadmap/issues/583
- [x] https://github.com/giantswarm/roadmap/issues/584
- [x] https://github.com/giantswarm/roadmap/issues/585
- [x] https://github.com/giantswarm/roadmap/issues/588
- [x] https://github.com/giantswarm/roadmap/issues/587
- [x] https://github.com/giantswarm/roadmap/issues/575

🍕 **Milestone: Beta** 🍕

- [x] #640
- [x] #626
- [x] #642
- [x] #782
- [x] #596
- [x] #634
- [x] https://github.com/giantswarm/roadmap/issues/682
- [x] https://github.com/giantswarm/roadmap/issues/586
- [x] https://github.com/giantswarm/roadmap/issues/595
- [x] #681
- [x] https://github.com/giantswarm/roadmap/issues/594
- [x] #712 
- [x] #752
- [x] #860
- [x] #735
- [x] https://github.com/giantswarm/giantswarm/issues/20527

🍕 **Milestone: GA** 🍕

- [x] https://github.com/giantswarm/roadmap/issues/598
- [x] https://github.com/giantswarm/roadmap/issues/591
- [x] giantswarm/roadmap#710
- [x] https://github.com/giantswarm/roadmap/issues/643
- [x] giantswarm/roadmap#773

🍕 **GA: Security** 🍕 

- [x] giantswarm/roadmap#632
- [x] giantswarm/roadmap#592
- [x] giantswarm/roadmap#790
- [x] https://github.com/giantswarm/roadmap/issues/868
- [x] https://github.com/giantswarm/roadmap/issues/1116
- [x] https://github.com/giantswarm/roadmap/issues/709
- [ ] giantswarm/roadmap#921
- [x] giantswarm/roadmap#778
- [ ] https://github.com/giantswarm/roadmap/issues/1117
- [ ] #1148
- [ ] giantswarm/roadmap#924
- [x] giantswarm/roadmap#687
- [x] #754
- [x] giantswarm/roadmap#675

🍕 **GA: Monitoring** 🍕 

- [x] #1003
- [x] #1002
- [ ] giantswarm/roadmap#930
- [ ] #1030 
- [x] #1001
- [ ] https://github.com/giantswarm/roadmap/issues/1209
- [ ] giantswarm/giantswarm#22875

🍕 **GA: Release Automation & testing** 🍕 
 
- [x] https://github.com/giantswarm/roadmap/issues/597
- [x] giantswarm/roadmap#686

🍕 **GA: Documentation** 🍕 

- [ ] giantswarm/giantswarm#23706
- [x] https://github.com/giantswarm/giantswarm/issues/22193

🍕 **GA: Networking** 🍕 
- [ ] https://github.com/giantswarm/roadmap/issues/1072
- [ ] #1783

🍕 **GA: Operation** 🍕 

- [x] Check if etcd backup operator is working

🍕 **Milestone: Cleanup** 🍕

- [x] https://github.com/giantswarm/roadmap/issues/809
- [ ] #625
- [x] #633
- [x] #649
- [x] #858
- [x] https://github.com/giantswarm/roadmap/issues/837
- [x] https://github.com/giantswarm/roadmap/issues/711
- [x] https://github.com/giantswarm/giantswarm/issues/20778
- [x] https://github.com/giantswarm/roadmap/issues/874
- [ ] https://github.com/giantswarm/giantswarm/issues/22156

**Milestone: Later**
- [x] giantswarm/roadmap#893
