### ISSUE TITLE
Add support for a backup IdP to dex-app

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#603]
### User story

_- As a customer, I want to have a way to use my backup authentication method when my Idp is down so that I can always access the management cluster._

_- As a GS engineer, I want to have a backup authentication method so that I can do operations / on-call when GitHub is down._

### Description

A customer asked for this option to be able to move from using `kube login` to `Dex` managed by us.
There is also an internal use case of GitHub being a SPOF.

### TODO

- [x] https://github.com/giantswarm/roadmap/issues/555 Add support for a backup IdP to Dex
- [x] Adapt a Web UI login page for a multiple options for IdP
- [x] Adapt the kubectl-gs `login` command to allow selection of the connector/IdP
- [x] Decide what to do with k8s-authenticator
- [x] Documentation 
- [x] Set up a backup IdP (Azure AD or Google) for Giant Swarm staff
- [ ] Add customer-facing documentation

**Comment by snizhana-dynnyk** [comment]
@marians will prepare a picture and explain it better :)

**Comment by marians** [comment]
Drawing is here: https://docs.google.com/drawings/d/1OnhApm0wrGKsabEwuDJrc56F-hZoJPX9JxLZSYHVWdo/edit

Let't talk about it.

![2021-12 Dex connectors and UX](https://user-images.githubusercontent.com/273727/144225991-50ba3caa-83ef-40ab-844c-224218c36304.png)

**Comment by PrashantR31** [comment]
Cooool proposals, I like the far right most, which is very friendly.
To be discussed: Maybe not to repeat "Giant Swarm staff" in the Buttons, given in the label already state so.

**Comment by marians** [comment]
That's not a spec BTW, it's there to support explanation in the team.

FYI I just added these two items to the TODO list:

> Adapt the kubectl-gs `login` command to allow selection of the connector/IdP

Currently we assume one connector for the normal user (customer) and one for Giant Swarm, the latter one being selected via the `--cluster-admin` flag of `kubectl gs login`. For arbitrary connectors, this behaviour must be adapted and we have to define how.

> Decide what to do with k8s-authenticator

Currently we deploy exactly two k8s-authenticator Deployments (Pod, Ingress, Service, ...). One for `customer` and one for `giantswarm`. The URL schema under `https://login.g8s.../` currently doesn't allow for growth. We must specify how this should look like with an arbitrary number of connectors.

**Comment by anvddriesch** [comment]
Reopened because while we do support multiple idps in dex now, we did not really document/announce how customers can set it up :)
