### ISSUE TITLE
One commit Releases

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#61]
## User Story

As a Giant Swarm Platform Engineer I want to be able to create a new release with a single PR in the releases repository. 

## TODO

- [ ] Ignition Operator https://github.com/orgs/giantswarm/projects/69
- [x] Moving apps versions to releases https://github.com/giantswarm/giantswarm/issues/8135
- [x] Moving component  versions to releases https://github.com/giantswarm/giantswarm/issues/8436
- [x] Automated release testing ( spec ) https://github.com/giantswarm/giantswarm/pull/8406
## Issues inherited from "Better Release crafting & testing"
- [ ] Add support to devctl to automatically list PRs since the last release https://github.com/giantswarm/giantswarm/issues/5970
- [ ] Add official conformance tests to our E2E tests https://github.com/giantswarm/giantswarm/issues/5972
- [ ]  Do a full installation E2E tests from installations https://github.com/giantswarm/giantswarm/issues/5971

## Details, Background

As the component versions are currently managed in the https://github.com/giantswarm/k8scloudconfig repository changing and releasing a component involves a lot of code changes and pull requests creating inter team dependencies and blockers.
Also a lot of manual testing is involved. We want to speed up this process by making releases with a single commit / PR that can be merged after automated regression tests without the need of manual testing.

## Deliverables
See linked issues.

## Host/guest cluster

- Host cluster

## Provider

- AWS
- Azure
- KVM / bare metal

**Comment by MartaD** [comment]
Test infrastructure was released, ignition operator will be part of a different story. Closing this ticket.
