### ISSUE TITLE
ssh access to CAPO cluster nodes

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#622]
- [ ] setup (central) vault or use operations vault
- [ ] setup bastion hosts
- [ ] Modify CAPO bastions to take certificates instead of keys

**Comment by kopiczko** [comment]
Dupe of https://github.com/giantswarm/roadmap/issues/634
