### ISSUE TITLE
Provide Dex as a managed app

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#628]
### User story

_- As a Giant Swarm customer, I want to have Dex managed by Giant Swarm so that I know it is up-to-date, reliable, and secure._

### Description

Right now we offer (dex-app](https://github.com/giantswarm/dex-app) in `playground` catalog. We want to move it to `giantswarm` catalog to provide it to our customers (including Giant Swarm) as a managed app.

### TODO

- [x] https://github.com/giantswarm/giantswarm/issues/18257
- [x] https://github.com/giantswarm/giantswarm/issues/17038
  - [x] scrape Dex
  - [x] public Grafana dashboard
- [x] #629
- [x] https://github.com/giantswarm/giantswarm/issues/19195
  - [x] #701
  - [x] #787
  - [x] https://github.com/giantswarm/roadmap/issues/797
  - [x] #831
- [x] https://github.com/giantswarm/roadmap/issues/547
Quick retro on this Epic

**Comment by PrashantR31** [comment]
Docs which we can add for customers:

providers we support
what we need for configuring provider X
questions to ask to a customer who asks "can I use AAD/GitHub/...?"
How to monitor your SSO success and failures ?
How to troubleshoot when SSO is not working ?
Can I add a fallback OIDC Provider in case the main one is not accessible ?
How do I login when SSO is not working ?
