### ISSUE TITLE
can we manage capo clusters with helm? 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#642]
Helm looks like an easy way to manage cluster releases. 
Problem is that MachineTemplates are immutable, and that for it might not be possible to do upgrades with helm. 
We want to figure out if there is a workaround that makes it possible. 

# TODO
- [ ] create a workload cluster helmchart from the output of kubectl gs template cluster
- [ ] run it against a management cluster
- [ ] try to upgrade kubernetes version
