### ISSUE TITLE
Optimize requests for Managment Clusters

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#649]
On Managment Clusters that are not in production but used only for testing purposes requests and limits are very high, so we have a lot of idle resources there. 
If we optimize those we can have more test installations with same hardware.

- [ ] investigate resource needs
- [ ] make cluster size and resource requests for MC configurable
- [ ] Optimize resource usage

**Comment by cornelius-keller** [comment]
@ericgraf do we still need this issue?
