### ISSUE TITLE
Autoscaling Ingress Controllers | Add HPA to our tenant ingress controllers

### ISSUE THREAD

**Issue by MarcelMue** [giantswarm/roadmap#65]
## Goals

- Make our ingress controllers more dynamic with autoscaling worker nodes. 
- Consume less resources in tenant clusters where IC is not used or is low traffic.
- Respond better to peaks in traffic to Ingress Controller.
- Have load test coverage for Ingress Controler HPA and cluster-autoscaler.

## Current state:

- When launching a new cluster we set the number of ingresses to the number of nodes in the `workers-array` in `cluster-operator`.
- This causes problems as the `workers-array` is no longer supported as a source of truth for worker counts with `cluster-autoscaling`. 
- A cluster with autoscaling will not change the number ICs running according to the changing number of nodes.

## TODO

- [x] Helm chart with Storm Forger test app - Fer - https://github.com/giantswarm/testapp/pull/1
- [x] Storm Forger test in JavaScript - Fer
- [x] Update outdated cluster-autoscaler PR - Fer https://github.com/giantswarm/kubernetes-nginx-ingress-controller/pull/78
- [x] Use Storm Forger CLI to launch test - Ross
- [ ] Add load test to `e2etests` that creates TC, installs test app and triggers test - Ross
- [ ] Check if thresholds for CPU / Memory make sense in production
- [ ] Check what the min/max number of ICs should be (also consider how many workers an IC is using?)
- [ ] Find a better metric to scale the pods https://github.com/giantswarm/giantswarm/issues/10163

EDIT: Updated checklist with current state.

**Comment by cokiengchiara** [comment]
Plan to ship today, except Azure. Doing everything on our side, so they can take over when they're ready.

**Comment by cokiengchiara** [comment]
Shipped AWS.
Today, shipping KVM. Handing Azure release to Celestial.

Once we ship release, we need to create follow up tickets.
* add specification in design approach
* where else can we use this? for general backlog

**Comment by sslavic** [comment]
HPA was already available for a while, it was disabled by default and no customer used it on their own while we had mix of other solutions (cluster-operator, CronJob) managing number of nginx replicas.

With work in last quarter or so, HPA has been enabled by default for selected clusters, across currently supported channels.

IMO any follow up work can be broken down (evaluated, prioritized) and this epic closed.

**Comment by cokiengchiara** [comment]
This is done. @cokiengchiara create follow up issues. Talk to @sslavic

**Comment by cokiengchiara** [comment]
@sslavic In Slack, you said, "repeatable load test was one of the TODOs in the epic. rest of the TODOs (and more) I think is covered with epic/nginx-tuning."

1. Add load test to e2etests that creates TC, installs test app and triggers test - Ross 

Created this: https://github.com/giantswarm/roadmap/issues/141

2. The rest I added to https://github.com/giantswarm/giantswarm/issues/10163 and not in separate issues since first two are tasks to "check" let me know if this organization makes sense for you.
* Check if thresholds for CPU / Memory make sense in production
* Check what the min/max number of ICs should be (also consider how many workers an IC is using?)
* Find a better metric to scale the pods giantswarm/giantswarm#10163
