### ISSUE TITLE
Update issue: [epic] Managed Kong in Giant Swarm Catalog (Preview Quality)

### ISSUE THREAD

**Issue by cokiengchiara** [giantswarm/roadmap#66]
**Outcome:** Get Kong to the specific managed service it is supposed to be. It’s hanging at 70% there. This means we have decided what it means (what we do and don't do) for Kong to be a Managed App. "Done" means having the answers in written form somewhere (whether in app catalog, a google doc, etc.) and sent to customer.

**By when?** 

**March 31, 2020**, we have provided our Kong to the customer with documentation on (1) how they can use it (2) how they could add their plugins, and (3) how they can go live with it. Not full SLA production ready, but usable w possible bugs.

## People involved
* @othylmann 
* @jgsqware 
* @pipo02mix and @rossf7 -> @webwurst and @yasn77 
* @piontec 
* @cokiengchiara 
* @teemow 

## Related Docs:
* One-pagers Definitions: Managed Apps, Managed Kong, customer-specific things: https://github.com/giantswarm/giantswarm/tree/master/areas/managed-services/managed-optional-apps
* Slack thread discussing who owns metrics https://gigantic.slack.com/archives/CPC3M70UE/p1575969913017800
* Kong Project Board with customer

## Obsolete
* Managed Kong: Definition: https://docs.google.com/document/d/1gyKoe0EAM1ILiwiLH-gNL3Hh0dOvXTHv9Rzk_csD-Mc/edit

## Engineering Todos
- [x] @piontec meet with @yasn77 to list specific things that need to be completed so we can ship Kong by end of Q1
- [ ] Go through Quality Bars checklist https://github.com/giantswarm/giantswarm/issues/8410
- [ ] Monitoring. @glitchcrab  Decide which metrics to monitor, so we can "make sure all pods and main components of the app are running and that the app is working right. We monitor and alert on necessary metrics to ensure our SLA." https://github.com/giantswarm/giantswarm/issues/8410
- [ ] Create documentation @yasn77 https://github.com/giantswarm/giantswarm/issues/8410
- [ ] Document how customer can use it
- [ ] Document how customer can add plug ins
- [ ] Document how customer can go live

## Product Todos

- [x] Create mini team within Managed Services to handle it, handoff from Fer
- [x] Set meeting on what needs to be done
- [x] Meet on what needs to be done https://docs.google.com/document/d/1gyKoe0EAM1ILiwiLH-gNL3Hh0dOvXTHv9Rzk_csD-Mc/edit
- [x] Chiara edits [doc](https://docs.google.com/document/d/1gyKoe0EAM1ILiwiLH-gNL3Hh0dOvXTHv9Rzk_csD-Mc/edit#) to make it more succinct and posts for agreement. Can set a new meeting if necessary. By Thu, Nov 28, '19 
- [x] Chiara clarify handover is happening from @pipo02mix to @webwurst and @yasn77 
- [x] Chiara adds to [Apps Team](https://github.com/giantswarm/giantswarm/issues/7725) issue: For Apps Team, how to track? We can’t have a Project Board for each app? Ping Managed Kong people here
- [x] Chiara clarify pending things to be decided in [doc](https://docs.google.com/document/d/1gyKoe0EAM1ILiwiLH-gNL3Hh0dOvXTHv9Rzk_csD-Mc/edit#) and set meeting to decide
- [x] Set meeting w Kong team to decide on TBD
- [x] Turn into a one pager for Kong
- [x] Turn into a one page for apps in general
- [x] Waiting for monitoring and plugs ins https://gigantic.slack.com/archives/CPC3M70UE/p1575969913017800
- [x] Ask @puja108 : What format, if any, is best to communicate this? Is there KaaS version of this? Add to our docs in GitHub, then send to Oliver and Julien
- [x] Review and make changes to pull requests. Decide on what still needs to be decided
- [x] Waiting for @othylmann  Feedback https://github.com/giantswarm/giantswarm/tree/master/areas/managed-services/managed-optional-apps
- [x] Move PSP stuff from customer doc to Apps in General (Definition) https://gigantic.slack.com/archives/CPC3M70UE/p1576589723004200?thread_ts=1576514030.002100&cid=CPC3M70UE
- [ ] Finalize Definition docs https://github.com/giantswarm/giantswarm/tree/master/areas/managed-services/managed-optional-apps

Waiting for feedback on these docs PRs

- [ ] Edit redis info in Kong https://github.com/giantswarm/giantswarm/pull/8528
- [ ] Update redis info w customer https://github.com/giantswarm/giantswarm/pull/8530/files#diff-dc19aafe90f8230e5b2e6fcdb9d5b1da
- [ ] Add the PSP stuff to managed apps https://github.com/giantswarm/giantswarm/pull/8531
- [ ] Postgres stuff - waiting for Yasser on latest on being DBless in halo channel

1. They will use our Kong. This is clear now. In DBLess mode.

## After first draft of Managed Kong definition
- [x] Document - after deciding where (e.g. in app catalog, in a doc, etc.)
- [ ] Communicate to customer

**Comment by yasn77** [comment]
> 1. What can the app do currently? What is included?
Kong :gorilla: We basically repackage the [upstream](https://github.com/Kong/charts/tree/master/charts/kong) with some minor changes. Any major change I have tried to push upstream. What it does... It's an API gateway

> 2. Is customer in process of testing it? (yes/no)
:heavy_check_mark: Yep, they are testing it

> 3. If no, what is customer waiting for?
>    
>    1. For us to do?
>    2. For them to do?

> 4. What else we want to improve from our side (even if not requested by customer)?
We still need to have some testing in place and monitoring (which I think is less important)

> 5. Are there important dates the customer is looking to hit internally that we need to be aware of? 
Q2

**Comment by cokiengchiara** [comment]
Kong is in Giant Swarm catalog. Customer is using it. Closing this for now.
