### ISSUE TITLE
Install k8s resources currently managed in k8s cloud config

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#675]
Currently we manage some resources inside [k8scloudconfig](https://github.com/giantswarm/k8scloudconfig/tree/master/files/k8s-resource). 

- [x] Pod Security Policies 
- [ ] Network Policies
- [ ] Rbac Rules
- [ ] Priority Classes

# TODO
- [ ] create a new app
- [ ] link it in default apps openstack

**Comment by cornelius-keller** [comment]
@giantswarm/team-phoenix  has a story to rotate encryption keys and will move them out of k8scc. https://github.com/giantswarm/roadmap/issues/677

**Comment by cornelius-keller** [comment]
Questions for planning:
- how to version those
- how is this related to CAPI releases
- Use ClusterResource set, app plattform or both.
- how to install CNI in the future?

Decisions form planning:  
We want to use the app platform. 
We will not change the way we install CNI.

**Comment by calvix** [comment]
> @giantswarm/team-phoenix has a story to rotate encryption keys and will move them out of k8scc. #677


Encryption Keys are not installed into k8s API, it's just a simple configuration file, and the only way how to add a file onto the machine is k8scc so we cannot remove it from the k8ssc in old product

 with CAPI,  it will have to be part of the KubeAdmSpec where files are defined.

**Comment by whites11** [comment]
> * [ ]  Pod Security Policies

Rocket doesn't use those, phoenix's problem only.

> * [ ]  Network Policies

We currently have 2 ways to deploy those:

- separate app with just the policies and app operator sorts out dependency problems
- job within cilium app that creates default policies.

We don't like the fact we have two solutions for this and we want to find agreement.
Rocket can't easily migrate to the new approach without downtimes in WCs.

We will raise the topic hi-level in kaas sync with the goal of setting up a call to sort it out with interested parties.

> * [ ]  Rbac Rules

Phoenix and Rocket will check what rules are there are find ways to deploy.

> * [ ]  Priority Classes

chart operator has a way to create those https://github.com/giantswarm/chart-operator/blob/a1d1fad8274ac310ee6fcee24c171761587e8c32/helm/chart-operator/templates/priorityclass.yaml#L1

**Comment by alex-dabija** [comment]
Meeting scheduled for Tuesday, the 7th of June at 13:00 CEST.

**Comment by cornelius-keller** [comment]
I discussed the PSP issue with sig-security.
We don't have a timeline for a PSP replacement yet, and we don't want our product to be less secure than on the other providers by disabling them completely. 
@giantswarm/team-rocket  the decision is that we need PSP for openstack. Please use the same approach as team-phoenix so that we are aligned here.

**Comment by kopiczko** [comment]
Let's have a separate issues for those 2 things then and close that one.

**Comment by cornelius-keller** [comment]
Ticket for PSP in openstack https://github.com/giantswarm/roadmap/issues/1148

**Comment by cornelius-keller** [comment]
Ticket for encryption keys

**Comment by gawertm** [comment]
followed up in the other 2 tickets as suggested by Pawel
