### ISSUE TITLE
Managed EFK - Improve in production

### ISSUE THREAD

**Issue by piontec** [giantswarm/roadmap#68]
## Status as of Wed, 28. Oct 2020

* We get alerted when it is "red" or "yellow". We improved the ops recipe so it is more actionable for ops to either fix or inform customer when the app is in trouble and customer might risk losing logs.
* We've added some basic tests (described below) and adding some more in order to make upgrades more reliable and smooth.
* We enabled PDBs https://github.com/giantswarm/efk-stack-app/blob/master/CHANGELOG.md#added to prevent cluster upgrades breaking Elasticsearch. Will be released soon.

The rest of the work will be adding tests and improving the monitoring and alerting.

More details below.

- [x] Enable PDB and pod anti-affinity by default to improve reliability of upgrades https://github.com/giantswarm/giantswarm/issues/13918

## Testing
**Make upgrades more reliable and smooth, by implementing the test suite and adding automated tests.**

https://github.com/giantswarm/giantswarm/issues/10348

- [x]  At first just get the internal health-check of Elasticsearch via the rest-api. Two tests, one for a setup with security-plugin enabled and the other for disabled.
- [x]  Run a test-pod that just logs some specific lines. Test if those lines can then be queried via Elasticsearch. This shows that the flow from app output, then fluentd and in the end Elasticsearch works.
- [x]  Test deleting one node of an Elasticsearch cluster, create a fresh one and check if cluster reaches green again after some time.
- [ ]  Test to prevent when trouble arose when cluster started rebalancing.

## Monitoring and Alerting
Improve our Monitoring and Alerting to (1) Catch common problems ahead of customer (2) Improve internal ops recipes so oncallers have actionable mitigations when problems arise.

- [x] Improve ops recipes https://github.com/giantswarm/giantswarm/issues/12305

**Add Monitoring and Alerting**
https://github.com/giantswarm/giantswarm/issues/13454

Includes: 
- [ ] Monitor and alert on managed EFK CronJobs & Jobs running in customer namespace on TC https://github.com/giantswarm/giantswarm/issues/13130
- [ ] Kibana erorring https://github.com/giantswarm/giantswarm/issues/11372
- [ ] [Explore storage threshold alerts to prevent ES red alert from triggering unnecessarily.](https://github.com/giantswarm/giantswarm/issues/13454#issuecomment-702043231) 
- [ ] We should notice when storage might be full before it’s too late, perhaps within 1 day.
- [ ] Monitor and alert when there is 30% or less storage (soft alert to inform customer and for them to do the action)
- [ ] During node replacement, there is some extra overhead ~30% when it needs more storage. When it doesn’t have this extra storage, Elastic turns red and other things need to be deleted manually to free up storage.
- [ ] Monitor metrics on performance
- [ ] Performance issues (new) - Queries take too long to execute. Seems harsh advertising from Elastic to get license.

## Align w Best Practices

- [ ] Use cert manager in OpenDistro / Managed EFK https://github.com/giantswarm/roadmap/issues/199, to align w upstream and reduce operational overhead

## Learning and Documentation

- [ ] Learn EFK effective limits to start defining SLIs https://github.com/giantswarm/giantswarm/issues/13452
- [ ] Define EFK Service Levels and Shared Responsibilities and share with customers https://github.com/giantswarm/giantswarm/issues/12418

---

**State as of Feb 19.**

What can the app do currently? What is included?
- OpenDistro Elasticsearch with security enabled
- Transport certificates autogenerated for 5 years
- Curator will delete indices older than 7 days
- Fluentd will collect all logs from pods not deployed in the namespaces: default, giantswarm, efk-stack-app, kube-node-lease, kube-public and kube-system.

**Comment by cokiengchiara** [comment]
> If possible I would keep this one in playground

EFK was [moved to Playground](https://github.com/giantswarm/giantswarm/issues/8762) instead of Giant Swarm Catalog b/c maybe @paurosello thought it couldn't meet the giant swarm catalog's requirements yet.

> sure, will push to giantswarm catalog once it meets the requirements hopefully finished by next week

I think it's fine for this app and Pau is in the process of moving it to Giant Swarm catalog anyway. 

For future apps, @paurosello would preview maturity level have been a good interim step? https://github.com/giantswarm/giantswarm/issues/new?assignees=&labels=area%2Fmanaged-services%2C+mission%2Fmanaged-services%2Fapps%2C+team%2Fhalo&template=new-app-giantswarm-catalog-preview.md&title=

**Comment by cokiengchiara** [comment]
@webwurst just want to clarify, will it be you or @paurosello who will be moving this app to Giant Swarm Catalog this Cycle?

**Comment by cokiengchiara** [comment]
EFK the Giant Swarm app. @webwurst will move. Tobiasz can choose to use or not.
EFK the customer app. Is shifting. Tobiasz is looking what makes sense for customer.

**Comment by cokiengchiara** [comment]
@T-Kukawka @paurosello (cc @webwurst ), these are the latest next todos for EFK app. 

- [ ] Preview quality
- [ ] With basic testing
- [ ] With basic monitoring
- [ ] Generate certificates with cert-manager
- [ ] Read the admin password from a secret in all components, not hardcoded

I would like to schedule a call with you to understand (1) how your customer testing has gone and (2) what else is missing (if any). Would also like to understand their use case, what's same and what's different.

**Comment by paurosello** [comment]
Helo @cokiengchiara I have been doing some work to upgrade the chart and fix the password management: https://github.com/giantswarm/efk-stack-app/pull/4

Let's see how we can manage the others

**Comment by cokiengchiara** [comment]
@webwurst is adding tests to EFK stack this week

**Comment by cokiengchiara** [comment]
@giantswarm/team-halo cc @puja108 @othylmann , I just talked to @paurosello and @webwurst and wanted to share EFK status.

## Status of EFK

1. Panamax had some concerns. Luckily, upstream made a fix for that. Pau added changes to our EFK. Pau just released the version.
	1. Pau is waiting for customer to give feedback if their concerns are addressed.
2. Now, in theory, we can already provide EFK for other customers to test. But EFK is a beast. Before we provide it as a “fully managedJ” app, we want experience running managing it. Ideas:
	1. Would like to dogfood, maybe in some test clusters. Any ideas how to proceed? e.g. install in gauss for two weeks?
	2. Maybe we ask one customer at a time to test it, without expectations, so we could get more experience? Any candidates? 
		1. Only concern is when there are takers, there won’t be anyone from Halo to take care of and learn. (Until Halo is confident to shift attention from NGINX IC to EFK)

How we tackle #2 is in theory how we would tackle getting experience in any future app we want to manage.

**Comment by cokiengchiara** [comment]
@webwurst looking at your comment [here](https://github.com/giantswarm/g8s-efk/pull/102#issuecomment-576631270). 

Seems to me like this is a product thing:  How to make EFK useful? For us and for customers. Just installing it is not enough. Ex -- Breakdown log messages for special fields so we can make use of the powerful filtering and searching, etc.

WDYT? Worth talking about? I'm thinking let's take ownership on how Giant Swarm can make use of its power, sell it internally, dogfood it and become experts on it. Help customers do the same. cc @piontec even though you love Loki

**Comment by piontec** [comment]
About dogfooding: WDYT about deploying it to the prod cluster that runs our website? It's note really customer-critical, yet an opportunity to learn on a real-life deployment.

**Comment by paurosello** [comment]
I would love to deploy it on Gauss, it's our testing environment and I need to follow logs from operators usually. I think we could benefit from that

**Comment by piontec** [comment]
> I would love to deploy it on Gauss, it's our testing environment and I need to follow logs from operators usually. I think we could benefit from that

That sounds good as well!

**Comment by cokiengchiara** [comment]
> I would love to deploy it on Gauss, it's our testing environment and I need to follow logs from operators usually. I think we could benefit from that

What's the "process" for EFK to be deployed on Gauss? Who should we talk to? Do we even need "permission"? etc.

**Comment by othylmann** [comment]
If it is supposed to be a managed app, which it is, why would we not use it ourselves.

**Comment by cokiengchiara** [comment]
> If it is supposed to be a managed app, which it is, why would we not use it ourselves.

SIG Monitoring had it before and removed it. We did not set it up to serve our needs, so it created more noise than value. It's also been said to be too powerful (bringing complexity w it) for our needs. For example, retaining logs for a long time which we don't need (but a bank might need for regulators).

**Comment by paurosello** [comment]
My idea is to get involved in SIG Monitoring shortly to achieve the installation on Gauss at least to give it a try

**Comment by paurosello** [comment]
Audit logging requested by Orange could be solved with logging

Thred: https://gigantic.slack.com/archives/CAN5CRF98/p1587724476133000

**Comment by cokiengchiara** [comment]
@ced0ps cc @giantswarm/team-halo 

Status of EFK: 
* Available to Panamax and GK Software. They are testing. SEs @webwurst , @paurosello , and @T-Kukawka are taking care of that. Nothing specific for Halo to do.
* For making it available to other customers, we're in limbo. Uncertain if it's the logging solution we want to provide (I don’t think it is). I'm working on clarifying overall Halo priorities now. 
* Halo thing we could do here is: GS quality bars checklist: https://github.com/giantswarm/giantswarm/issues/new?assignees=&labels=area%2Fmanaged-apps%2C+team%2Fhalo&template=new-app-in-catalog.md&title=

Does this make it clear what we can do here? :)

**Comment by othylmann** [comment]
I think we should provide that. Two are already using it. We can limit the performance guarantee we can give. And I agree that we might want to push people to something else. but this is not going away.

And remember we can see if we need to charge for this down the road.

**Comment by piontec** [comment]
Current [2020-10-27] status of what we want to achieve by the end of cycle:

Must do:
- [ ] Tests - #10348 (top of description)
- [ ] enable PDBs #13918
- [ ] create values validation schema
  - create the schema
  - validate with `kubectl gs` the schema against all our current deployments
- [ ] ops-recipe improvements #13723
- [ ] check effective limits of the current setup and the baseline performance #10348
- [ ] learn basic exporter's metrics valuable for asserting EFK's state

Stretch goals:
- [ ] Tests - #10348 (top of description)

**Comment by cokiengchiara** [comment]
EFK is improved in production. For specifics, see changelog: https://github.com/giantswarm/efk-stack-app/blob/master/CHANGELOG.md#035---2020-11-25

I also opened an issue on how to better communicate this value https://github.com/giantswarm/giantswarm/issues/14610

**Comment by cokiengchiara** [comment]
@giantswarm/team-halo I am closing this issue. I believe other ideas for improving EFK are in different issues https://github.com/giantswarm/giantswarm/labels/component%2Felasticsearch please check if there's anything in this issue you want to save :)
