### ISSUE TITLE
[EPIC] CI/CD for  Management cluster creation

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#685]
User Story:
- As a giant swarm developer I want my changes to CAPO management cluster creation to be tested automatically so that I am sure I don't introduce a regression 
# Tasks
- [x] #1354
- [x] #1383
- [x] https://github.com/giantswarm/giantswarm/issues/23743
- [ ] #1638
- [ ] #1639

# Acceptance criteria 
- [x] If a make a change to the mc-bootstrap repository there is a CI job running that makes sure managment cluster creation is still working for
    - [x] CAPO
    - [ ] CAPG
    - [ ] CAPA
    - [x] CAPVCD
    - [ ] CAPV
- [ ] These jobs are executed also on a regular basis to make sure that changes done outside of mc-bootstrap (app-collections) don't affect management cluster creation

**Comment by cornelius-keller** [comment]
@ericgraf  please explain current status and current limitations

**Comment by gawertm** [comment]
@yulianedyalkova FYI. this is the epic that we have in Rocket on the CI topic, @ericgraf worked on for a while already.

**Comment by yulianedyalkova** [comment]
Closing in favour of https://github.com/giantswarm/roadmap/issues/2119.
