### ISSUE TITLE
Enable different alerting depending on a cluster type

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#688]
### User story

_-As a GS engineer, I don’t want to get paged with all the alerts on a development cluster that customer is using for testing so that I can minimize noise and focus on real issues._

The use case is coming from the team Honey-badger where customers use development clusters to play with fluxcd and the team gets a lot of false alerts.

### TODO

- [ ] add new cluster label to labeling schema (dev, production, prod)
- [ ] https://github.com/giantswarm/giantswarm/issues/15687 Allow to set cluster labels on cluster creation
- [ ] label existing clusters according to the info from the customers
- [ ] adjust our alerting to diff cluster types (build inhibitions etc)
