### ISSUE TITLE
Replace oidc-client-js with something future-proof

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#694]
### Description
The [OIDC client package](https://github.com/IdentityModel/oidc-client-js) we use is no longer being actively maintained, and has now been officially archived. While we probably won't need to rely on new OIDC features being implemented, this also means that the dependencies this package requires also won't be actively updated, including for security-related patches.

As there doesn't seem to be a stable and direct replacement for the package, we can consider a few options:
1. Maintain our own fork of `oidc-client-js` to keep the package dependencies updated ourselves
2. Replace with a similar package - [`AppAuth-js`](https://github.com/openid/AppAuth-JS) looks to be an alternative other projects are turning to, though it also has less built-in features. This would require us to implement and test the features we need ourselves.

### TODO
- [x] https://github.com/giantswarm/roadmap/issues/887
- [x] Keep an eye out for other promising alternatives(`oidc-client-ts` is a fork of the original `oidc-client-js` repo and ported to TS)
- [x] Replace with `oidc-client-ts`
- [x] archive our fork of`oidc-client-js`

**Comment by PrashantR31** [comment]
Actions points:

1. Investigation
2. Estimation

**Comment by PrashantR31** [comment]
Thanks @kuosandys for the info, I'll plan for this task soon, just after we know the teams preference on the options. But personally I prefer option 1 at the moment then when we have some time we do option 2.

**Comment by kuosandys** [comment]
I talked about this with @gusevda today and we both agreed that the effort of replacing `oidc-client-js` with `AppAuth-JS` outweighs the benefits it would bring us. We won't be taking advantage of any new features, and there's also the added risk of introducing new errors with the new code we'd add.

The best course of action currently is to fork the `oidc-client-js` repo and keep the dependencies up to date ourselves. We can then continue to keep an eye out for other alternatives better suited to our needs.

**Comment by PrashantR31** [comment]
Cool, thanks @kuosandys , let us enumerate the tasks related to this decision. Do you think we should have some kind of monitoring or reminder to check on the dependencies to tell us that new versions are available, or we are already alerted ?

**Comment by kuosandys** [comment]
> Cool, thanks @kuosandys , let us enumerate the tasks related to this decision. Do you think we should have some kind of monitoring or reminder to check on the dependencies to tell us that new versions are available, or we are already alerted ?

As a start, I've enabled dependabot alerts and updates for security vulnerabilities.

**Comment by kuosandys** [comment]
Released with happa `v1.57.3`
