### ISSUE TITLE
take ownership of cluster-openstack helm chart 

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#696]
- [ ] check the difference between the current kubectl-gs templated clusters with this helm chart
- [ ] check if all requirements we are aware of are met
- [ ] use it to create and upgrade clusters
- [ ] #702
