### ISSUE TITLE
Introduce tests for the dex app

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#701]
- [x] schema validation giantswarm/dex-app#146
- [x] add tests for our changes to our fork giantswarm/dex#41
- [x]  add app-test-suite with smoke test scenario giantswarm/dex-app#147
- [x] upgrade scenario https://github.com/giantswarm/dex-app/pull/153

**Comment by PrashantR31** [comment]
Command and examples : https://github.com/giantswarm/giantswarm/issues/20068

**Comment by PrashantR31** [comment]
One of the test that I am thinking is:

1. Check if the SSO endpoints are working correctly after a dex version upgrade or change.
2. Given we dex has a dependency on running Oauth2-proxy, we should check that, after a change or upgrade, the proxy is doing its job within the k8s system

I do not know complexity but if we could integrate that in the cicd pipeline

**Comment by PrashantR31** [comment]
Adding test on helm chart as well.

**Comment by PrashantR31** [comment]
So we have test already for our helm chart as a smoke test
Next action:
To add upgrade test

Notes:
We close the testing part here and will cater for additional testing later on. As we will know (from logs and alerting) when the the app breaks.
