### ISSUE TITLE
Add monitoring for `loki`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#718]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [x] Loki setup on Azure
- [ ] Loki setup on AWS
- [x] ensure it is scraped by Prometheus
- [ ] Create Grafana dashboards
- [x] make sure there are basic alerts

**Comment by TheoBrigitte** [comment]
We had a very hard time trying to make `loki` work in the first place. The aws s3 bucket setup is "complicated".

We already spent lot of time here, do we want to continue ? We feel like loki is important to us and that we should proceed.

### Suggestions

- Try to make `loki` work without aws, just output the log to some "simple" output like a local directory.
- Move on with monitoring then
- Ask help from phoenix to demystify how the aws s3 bucket setup works.

**Comment by hervenicol** [comment]
### Done
* Loki deployment procedure works on Azure.
* I've seen scraped metrics
* I've tested a mixin-generated Loki dashboard (loki-reads from https://monitoring.mixins.dev/loki/), and some labels are different than on our setup.

### Todo (open to discussion)
* Setup official Loki dashboards
  * Generate / document generation for official mixins
  * Update / Document update procudure to make official mixin dashboards work for us
* Setup official recordingrules from Loki mixins?
* Setup official alerts from Loki mixins

**Comment by hervenicol** [comment]
Note about S3 access issues:
Marian told me GS v17 changed IAM management on AWS from KIAM to something else. Probably [IAM roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html) as suggested on [KIAM's page](https://github.com/uswitch/kiam).

So, regarding AWS compatibility:
* test using GS v16 if we need to work on AWS
* upgrade to latest IAM management system for the long-run
* maybe we need to be compatible with both systems, if customers are still using GS v16.

**Comment by hervenicol** [comment]
## Dashboards status

Issues with mixins dashboards so far:
* cluster label name hardcoded to "cluster" => upstream PR https://github.com/grafana/loki/issues/6352 would fix that. We can maintain a fork if needed.
* dashboards rely on rewrite rules. The rewrite rules are provided with the mixins :+1: but how to set them up on our installations?
* queries filter on jobnames. Different jobname for each component (like `job=~"($namespace)/cortex-gw"`. What to do with that? To be investigated if we want to propose a clever way to override these.

## Rewriterules status
* dashboards and alerts rely on them. Setting them up would ease next steps.
* should we use mixins for the rewriteRules? It seems they would work as-is.

## Alerts status
* I've duplicated the simple alert rules from the mixins to our rules set (https://github.com/giantswarm/prometheus-rules/pull/368), so we are not using mixins for the alerts for the moment.
* mixins-generated alert rules don't contain all the tags we need, we should find a way to enrich them from mixins config
* Some of the mixin-generated alert rules rely on rewriteRules.

**Comment by hervenicol** [comment]
* Loki setup for AWS = https://github.com/giantswarm/giantswarm/issues/22410

**Comment by hervenicol** [comment]
To be continued on different issues.
There is a lot of room for improvement with loki graphing / monitoring, but we need to better understand our loki usage before we go further.
