### ISSUE TITLE
Add monitoring for `fluent-logshipping-app`

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#719]
Towards https://github.com/giantswarm/roadmap/issues/601 Ensure monitoring for all managed apps

### TODO

- [x] ensure it is scraped by Prometheus
- [x] make sure there are basic alerts

**Comment by hervenicol** [comment]
- basic "up" alert created
- TooManyErrors alert to be checked
- opsrecipes to be created
- dashboard maybe also ?

**Comment by mcbenjemaa** [comment]
TODO:
- [ ] Change alert to point to ops-recipe.
