### ISSUE TITLE
Ensure CLI guide to inspect azure clusters contains all relevant resources

### ISSUE THREAD

**Issue by ghost** [giantswarm/roadmap#758]
Our CLI guide `Inspect this cluster via the Management API` looks like this:

<img width="957" alt="image" src="https://user-images.githubusercontent.com/273727/157008995-269bc1fe-901d-4a82-a2b6-48c6841d560c.png">

Example URL: https://happa.g8s.gollum.westeurope.azure.gigantic.io/organizations/giantswarm/clusters/c68pn

Should add a CLI guide to inspect control plane nodes in an Azure cluster (azuremachine CRs)

## Tasks

- [ ] Verify whether this includes all relevant resources
- [ ] If not, specify which commands should be added to inspect resources
- [ ] Implement in the web UI

**Comment by marians** [comment]
In happa on azure we expose information from AzureMachine CRs. However so far we are missing the according CLI guide on the cluster details / node pools page.

Please contact me for details.

**Comment by PrashantR31** [comment]
Hii @alex-dabija , grateful if you can please take this in your team, so as to provide the appropriate guides and to make the solution more complete. Thanks.

**Comment by PrashantR31** [comment]
Hello @marians, if you can please tell me if this is still necessary to work on at the moment. Thanks.

**Comment by marians** [comment]
I'm not sure. This is one of the cases where the provider team has a better understanding. I will pick an Azure expert for a call and clarify this.

**Comment by PrashantR31** [comment]
Let me check with @alex-dabija, we can then remove from our board, if Pheinix is taking this onboard

**Comment by marians** [comment]
Got this picture in a secret channel ;-)

![image](https://user-images.githubusercontent.com/273727/157003709-69b3bdc4-db6b-4efc-9858-193e1fbc3289.png)

**Comment by PrashantR31** [comment]
Hii @giantswarm/team-rainbow ,

My bad, the requirement was not captured at the opening of the ticket, grateful if more details cane be added to help @T-Kukawka who will be taking care of the guide creation.

e.g What is missing and where do we need the CLI guide to be added (intranet, customer docs ?)
Thanks

**Comment by marians** [comment]
Main description updated

**Comment by marians** [comment]
Closing, as we minimize the effort we put into happa. @weatherhog
