### ISSUE TITLE
Happa Access Control

### ISSUE THREAD

**Issue by PrashantR31** [giantswarm/roadmap#760]
Mission: Provide ReadOnly user access on Happa

Description:
Currently Happa provides Admin access all CR's and we would like to limit the access to read only so that a user can limit their actions on the CR's which is available within the NameSpaces allowed to the user.

The following are the epics to accomplish the mission successfully:

- [x] #551
- [x] #742
- [x] #602
- [x] https://github.com/giantswarm/giantswarm/issues/20087
- [x] #766
- [x] #811
- [x] #800
- [x] #859
- [x] Happa RO - Customer announcement
- [x] Show RO feature to @LolloneS 
- [x] #929
- [ ] https://github.com/giantswarm/giantswarm/issues/21397
- [ ] https://github.com/giantswarm/giantswarm/issues/18357
- [ ] AE/SA Approach customer directly to show the feature and advantage and push the customer to use it.
- [ ] Attend Service review call who are in SSO already

Prashant - checklist 
Start thinking on shared permission

**Comment by anvddriesch** [comment]
This will be a continuous effort.
