### ISSUE TITLE
Epic: implement automatic App Quality Enforcement

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#777]
Implement automation to enforce quality guidelines

- [ ] https://github.com/giantswarm/giantswarm/issues/19851
- [x] https://github.com/giantswarm/giantswarm/issues/19682
- [x] https://github.com/giantswarm/giantswarm/issues/19559

**Comment by gianfranco-l** [comment]
@piontec as agreed, please link here all the issues that are included within the scope of this epic

**Comment by piontec** [comment]
Quick notes from our discussion:
* toolkit
  * abs - enforcement tool
    * we add more enforcement tools to it
  * ats
    *pre-commit
* more dynamic creation of new app repos (than app-template)
  * check the https://cookiecutter.readthedocs.io/en/1.7.2/
* existing docs
  * https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/application-quality-bars/
  * https://intranet.giantswarm.io/docs/dev-and-releng/app-developer-processes/adding_app_to_appcatalog/

**Comment by weatherhog** [comment]
@piontec is this issue still valid?

**Comment by piontec** [comment]
Yes, we should do that in `abs`

**Comment by weatherhog** [comment]
@piontec one year has passed. Nothing happened. Do we really still want to work on this ?

**Comment by piontec** [comment]
Yeap, unrealistic and too low priority. Closing
