### ISSUE TITLE
Avoid rbac-operator from assigning a default admin group for shared installation

### ISSUE THREAD

**Issue by ghost** [giantswarm/roadmap#804]
Avoid rbac-operator from assigning a default admin group because that concept cannot work in a shared installation.

Ref: https://github.com/giantswarm/giantswarm/issues/16765

## Tasks

- [x] Make rbac-operator work without the `oidc.customer.write_all_group` setting
- [x] Remove `oidc.customer.write_all_group` setting from shared installations
- [ ] remove write_all_group attribute from all shared installations including test installations

**Comment by marians** [comment]
This is done, we only forgot to close this.

**Comment by marians** [comment]
I was wrong, this isn't done yet.

The `write_all_group` setting still has to be removed from test installations' rbac-operator config.

**Comment by gawertm** [comment]
not needed anymore bc of rolebinding templates
