### ISSUE TITLE
Allow reviewing of Management API permissions in the web UI

### ISSUE THREAD

**Issue by ghost** [giantswarm/roadmap#808]
## User stories

1. As an admin, I want to see which permissions a user or group member will have when accessing the Management API, so that I can tweak the permissions if needed.

2. As a user of WebUI, I want to see which permissions I have in the Management API, so that I can talk to my admin about adding permissions, if needed.

3. As an admin, I want to see which permissions a service account will have when accessing the Management API, so that I can tweak the permissions if needed.

## Details

- Permissions on the technical level (resource types, verbs) are only meaningful in very specific cases. Instead we want to aggregate them into use cases. For example, "creating a workload cluster". For this use case, users need create permissions for several different resource types.

- Use cases could be further grouped by topics. E. g. "workload clusters", which would include creating, updating, deleting, and reading of clusters and node pools.

- Related to user story (1): It should be easily visible whether the user has enough permissions to use the web UI, and if not, which permissions are missing.

- Some use cases have to be evaluated per organization. For example, a user could be permitted to create clusters in some organizations, but not in others.

### First milestone

- [x] #1049
- [x] #1050
- [x] #1051
- [x] #1067
- [x] #1068

### Second milestone

- [x] #1085
- [x] #1086
- [x] #1071
- [x] #1066

### Not yet planned

- [x] #1185
- [x] #1122
- [ ] Use full width of viewport, to account for many organizations
- [ ] Show which RBAC permission is missing in case of `No`, allow copying
- [ ] Allow selecting known group and user names instead of typing

### Go To Market
- [ ] #1118

### Documentation
- [x] https://github.com/giantswarm/giantswarm/issues/22169

**Comment by PrashantR31** [comment]
Some ideas (could be it is implemented already, I need to check) so as to make the support easy on this kind of situation:

1. Having logs entry to show a user does not have the required permissions to access Happa. These logs can be tagged as warning and can be made available on Happa, so that an admin user can easily view and find out about the issue.
2. As well, I did not check by myself on happa, but if it does not exist, then we can have a page to list the users/groups/rolebindings relationship, so as to find out if a user has the permission to have access to Happa.

**Comment by marians** [comment]
For reference, here is the list of use cases I'm using:
https://docs.google.com/spreadsheets/d/1yLDlaWNAamON1NabkJiYGsmqi0RuIbSZt1R5_gz58dY/edit#gid=0

**Comment by marians** [comment]
Dumping some commands for the Management API guide (CLI guide) spec

```
# For myself
$ kubectl --context gs-foo auth can-i --list
$ kubectl --context gs-foo auth can-i --all-namespaces
$ kubectl --context gs-foo auth can-i --namespace org-acme

# For a user
$ kubectl --context gs-foo auth can-i --list --as username@mydomain.tld
$ kubectl --context gs-foo auth can-i --list --as username@mydomain.tld --all-namespaces
$ kubectl --context gs-foo auth can-i --list --as username@mydomain.tld --namespace org-acme

# For a group
$ kubectl --context gs-foo auth can-i --list --as dummy --as-group customer:mygroup
$ kubectl --context gs-foo auth can-i --list --as dummy --as-group customer:mygroup --all-namespaces
$ kubectl --context gs-foo auth can-i --list --as dummy --as-group customer:mygroup --namespace org-acme
```

**Comment by PrashantR31** [comment]
We chat about this in a refinement today 12th April:

1. Possibly we could make the UI customization per customer accessing a specific organisation (e.g using yml and loading at Happa Boot-time/ Runtime)
2. A customer could want to have a view per organisation or per installation
3. Provide CLI guides in the UI
4. We could have a smarter version of `kubectl gs can-i` to enhance the formatting

Next Step will be doing a Mockup by Marian

**Comment by anvddriesch** [comment]
next step: set up a call to slice and dice this story

**Comment by marians** [comment]
### Refinement / slicing & dicing

#### Step 1

- [ ] Create a spec for our "use cases file" format to define use cases (and groups of use cases) and the permissions required @kuosandys 
- [ ] Define permissions required per use case @marians, maybe @anvddriesch 
   - [Some input](https://fe-docs.giantswarm.io/?path=/story/development-permissions-for-user-actions--page)
- [ ] UI implementation: add page with static content, add user menu entry @gusevda 
- [ ] UI implementation: CLI guide
- [ ] Implement a parser for the "use case file"
- [ ] UI implementation: Show permissions for the current user only
   - First attempt to fetch permissions from cluster scope and non-org namespaces
   - Iterate over org namespaces to fetch permission, in the background (tab content is not visible initially)
   - Re-use the helper function(s) we already have

#### Step 2

- Decide how to configure happa per installation with the "use cases file" (e. g. YAML files in giantswarm/config)
- Ability to impersonate user or group for showing their permission
   - Fetch permissions from cluster scope (= all namespaces)
- Make use case groups expansible/collapsible

#### Future improvements

- Display instructions on how to add missing permissions per use case
- Display instructions on how to remove permissions per use case

**Comment by marians** [comment]
UI prototype is available in https://www.figma.com/community/file/1098235384151181688/Inspect-user-permissions

**Comment by marians** [comment]
I would close this one. We have https://github.com/giantswarm/roadmap/issues/1118 for the remaining communications items.

**Comment by weatherhog** [comment]
closing this issue
