### ISSUE TITLE
Remove unused variables from dex-app values.yaml and schema

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#829]
We have several `write_all_group` values in dex-app's `values.yaml` file, but they don't seem to be used. (They seem to have crept in from rbac-operator config during a migration.)

## Tasks

- [x] Remove `oidc.customer.write_all_group` from all dex-app configs in giantswarm/config
- [x] Remove `write_all_group` from https://github.com/giantswarm/dex-app/blob/main/helm/dex-app/values.yaml
- [x] Remove `write_all_group` from https://github.com/giantswarm/dex-app/blob/main/helm/dex-app/values.yaml
- [x] Remove `write_all_group` fields from https://github.com/giantswarm/dex-app/blob/main/helm/dex-app/values.schema.json
- [x] Make sure that customer configmaps/secrets for dex-app in workload clusters do not contain any `write_all_group` fields

**Comment by teemow** [comment]
@marians  this issue is in no projects. So maybe it fell through the cracks.

**Comment by marians** [comment]
Thanks @teemow ! I'll move it to Rainbow's board, but think that we've solved it already.

**Comment by marians** [comment]
I checked and we still have work to do. The task list is updated.
