### ISSUE TITLE
Epic: Promotion of releases between environments for GitOps

### ISSUE THREAD

**Issue by gianfranco-l** [giantswarm/roadmap#830]
User story:
As a developer, I want to have a process to implement promotion of releases between environments so that I can ensure smooth quality assurance on my applications before releasing them into production environment

Marcel research on the topic:
Currently, GitOps does not define how it is supposed to work to promote releases.
Some resources and various perspectives on the topic:
- https://codefresh.io/about-gitops/pains-gitops-1-0/ -> undefined process for release promotion
- https://www.gitops.tech/#how-does-gitops-handle-dev-to-prod-propagation -> dev to prod is your problem, not gitops
- https://livebook.manning.com/book/gitops-and-kubernetes/chapter-3/94 -> separation from dev to prod either through branches or folders, no automation
- https://www.reddit.com/r/GitOps/comments/ljlqxa/how_do_you_promote_code_to_environments/ -> discussion on the same issue, no solution recommended
- https://github.com/freiheit-com/kuberpult -> posted earlier, used by customer -> simply copies code around to achieve promotion
- https://codefresh.io/about-gitops/branches-gitops-environments/ -> codefresh says "don't use branches, use folders" does not elaborate HOW
- https://github.com/argoproj/argo-cd/discussions/5667 -> giant discussion in Argo about the exact issue
- https://en.sokube.ch/post/promoting-changes-and-releases-with-gitops -> very in depth article describing different solution approaches
- there is also [Kubevela](https://kubevela.io/blog/2021/10/10/kubevela-gitops#gitops-with-kubevela) and [Open Application Model (OAM)](https://oam.dev/)

Update June 8th:
Flux v0.31 introduces support promotion of HelmReleases via GitHub actions between environments. 
Use case description [here](https://fluxcd.io/docs/use-cases/gh-actions-helm-promotion/), full release notes [here](https://github.com/fluxcd/flux2/releases)

Update July 13th: Scope refinement below

## TODO

- [x] https://github.com/giantswarm/gitops-template/pull/41
- [x] https://github.com/giantswarm/giantswarm/issues/22593
- [x] create platform releases using the new `app-operator` with config lists
- [ ] add multi-base example to `gitops-template` repo based on the `stage` and `region` environment cluster templates
- [ ] Documentation for customer
- [ ] Announce to the customer

Related (?): KaaS Staged Deployments https://github.com/giantswarm/roadmap/issues/620

**Comment by gianfranco-l** [comment]
closing this ticket as this was implemented within the scope of [this](https://github.com/giantswarm/giantswarm/issues/21243). There are some missing docs to be produced which are in the scope of[ this ticket.](https://github.com/giantswarm/giantswarm/issues/22879)
