### ISSUE TITLE
Cluster API clusters with proper alerts

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#840]
## Story

_*- As a cluster admin, I want the alerts being triggered for Cluster API clusters to be fixed in order to not treat them as special clusters and to reduce the gap between existing Giant Swarm and Cluster API clusters.*_

## Background
Cluster API clusters can be created on AWS, Azure and GCP, but our monitoring system is triggering alerts because these clusters don't respect all the characteristics of Giant Swarm existing clusters.

```
## Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/29204
- [ ] #3172
- [ ] Alert for Cluster Upgrade Failures
```

```[tasklist]
### Tasks
- [ ] https://github.com/giantswarm/giantswarm/issues/29204
- [ ] https://github.com/giantswarm/roadmap/issues/3172
- [ ] https://github.com/giantswarm/roadmap/issues/3173
- [ ] https://github.com/giantswarm/roadmap/issues/3174
- [ ] https://github.com/giantswarm/roadmap/issues/3354
```

**Comment by fiunchinho** [comment]
Story for CAPG https://github.com/giantswarm/roadmap/issues/1145

**Comment by T-Kukawka** [comment]
We have all prometheus rules installed, we are receiving the alerts (but silenced for now). We are still missing the operators erroring.
