### ISSUE TITLE
Migrate dex to GS catalog

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#854]
***Towards STORY_URL***

https://github.com/giantswarm/roadmap/issues/547

### TODO

- [x] Release to both catalogs
- [x] Migrate GS instances (talk to owner of operations cluster dex)
  - [x] gollum
  - [x] gorilla
- [ ] Talk to customers and migrate them
  - [x] flamingo
  - [x] fox
  - [x] icecream
  - [x] check https://giantswarm.grafana.net/d/Iuahg6J7z/app-status?orgId=1
