### ISSUE TITLE
Get rid of ClusterClass

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#860]
- We want to get rid of cluster class  because we are not using it properly 
# Tasks
- [x] talk to phenix about 
- [x] check if helm upgrade works @ericgraf 
- [x] check if we can upgrade the control plane @ericgraf 
- [x] update cluster-openstack app 

Acceptance Criteria
- [x] Kubernetes version upgrades need to work with `cluster-openstack` helm chart
- [x] Changes to the ControlPlane need to work with updating the helm chart.

**Comment by cornelius-keller** [comment]
Communication with phenix happened in KAAS sync and CAPI sync.

**Comment by tfussell** [comment]
This is done.
