### ISSUE TITLE
Clean up resources left behind by RBAC-operator changes

### ISSUE THREAD

**Issue by anvddriesch** [giantswarm/roadmap#866]
***Towards https://github.com/giantswarm/giantswarm/issues/20087***

### Description

We are making some changes to `rbac-operator` that will leave behind orphaned resources that have to be cleaned up manually

### TODO
Cleaning up

- [x] roleBinding `flux-crd-controller` in cluster namespaces
- [x] roleBinding `flux-namespace-reconciler` in cluster namespaces
- [x] serviceAccount `automation` in cluster namespaces
- [x] rolebinding `default-catalogs-organization-$CLUSTER-read` in default namespace (only for $CLUSTER, not $ORGANIZATION)
- [x] clusterrolebinding `releases-organization-$CLUSTER-read` (only for $CLUSTER, not $ORGANIZATION)
- [x] role `write-cluster-apps-in-cluster-ns` in all namespaces
- [x] role `read-cluster-apps-in-cluster-ns` in all namespaces
- [x] clusterrole `write-cluster-apps-in-cluster-ns`
- [x] clusterrole `read-cluster-apps-in-cluster-ns`
- [x] roleBinding `read-cluster-apps` in all namespaces
- [x] roleBinding `write-cluster-apps` in all namespaces
- [x] roleBindings and clusterRoleBindings referencing above roles and clusterRoles

**Comment by marians** [comment]
All done, except for buffalo, which is [broken](https://github.com/giantswarm/giantswarm/issues/20044)
