### ISSUE TITLE
Maintain our own fork of oidc-client-js

### ISSUE THREAD

**Issue by kuosandys** [giantswarm/roadmap#887]
This is an interim step towards https://github.com/giantswarm/roadmap/issues/694. Please see the related issue for background information.

## TODO:
- [x] Fork oidc-client-js and set up the repo according to GS standards outlined [here](https://github.com/giantswarm/github/blob/master/README.md)
- [x] Configure dependabot alerts for security vulnerabilities
- [x] Configure CODEOWNERS to @gusevda and @kuosandys
- [x] Add GitHub actions workflow to run tests
- [x] Update `happa`: replace `oidc-client-js` with our forked version

**Comment by kuosandys** [comment]
Replaced `oidc-client-js` with our fork. Will continue tracking the overall topic of finding a suitable long term replacement in the original issue mentioned above.
