### ISSUE TITLE
Azure: Node Pools

### ISSUE THREAD

**Issue by J-K-C** [giantswarm/roadmap#9]
### Epic User Story

As a user creating multiple clusters, I want to be able to define the individual character of each of these clusters, so I can have multiple clusters use cases in one cluster.

## Acceptance Criteria

I can have different node pools in a cluster which: 
- are spread across different availability zones 
- have different levels of storage 
- have different availability zones which I can manage through the UI Happa, GSCTL, API.

## Implementation Plan
- [x] Split master and workers management into two different resources (effectively: split `instance` resource)
- [x] Sort out CRDs(both Cluster API and ours) that are required for `MachinePool` (and provider-specific parts of it). #161 
- [ ] Create controllers required for `MachinePool` (provider-independent stuff to `cluster-operator` and rest provider-specific stuff to `azure-operator`). #157 
- [x] Copy workers `instance` resource to the machine pool controller.
- [x] Copy `ipam` resource from `aws-operator` and adapt it to `azure-operator`.
- [ ] Refactor the machine pool controller's workers resource to fully manage node pool
  - [x] Allocate and create subnet for workers.
  - [x] Configure security groups if needed.
  - [x] Configure routing if needed.
  - [ ] Handle the specific VMSS and its status.
- [ ] Create migration resource in `AzureConfig` controller
  - [ ] Create `MachinePool` (and required related) CRs to mirror existing worker VMSS.
  - [ ] When created machine pool CRs have `Status` such that all workers are up & running `Ready`, then `Drain` the old workers.
  - [ ] When old workers are drained, delete the old worker VMSS.

## Links
- Dimensions of Complexity analysis: [report](https://docs.google.com/spreadsheets/d/1RHLo6SnWdEALYiMY-Xo_j-yS2B0JYLnKGIcC2u-bxjU/edit#gid=1343219569)

- Please view this slide-deck for an overview of the 'AS-IS - TO-BE' design: [design](https://docs.google.com/presentation/d/1bvlLhb9CBRYqA9cX77rH5WVOEcU9QaSRrbE1J9DLxhs/edit#slide=id.p)

**Comment by MartaD** [comment]
In the face of recent issues we all experienced on Azure, we revised the expected delivery date for the Node Pools functionality from Q2 to Q3.

It took a month to mitigate API throttling (error 429) and protect clusters from its effects. Then we had to focus on replacing CoreOS, which is going EoL, to Flatcar. To make it a non-breaking change with minimal impact on your workloads, we had to invest a significant effort. Although we already started working on Node Pools, these two issues greatly impacted the progress we were able to make so far.
