### ISSUE TITLE
Migrate GS API to Kubernetes API

### ISSUE THREAD

**Issue by snizhana-dynnyk** [giantswarm/roadmap#90]
## User Story

- _As a Giant Swarm Customer, I want to have write access to K8S API on a Control Plane so that I can edit custom resources to manage workload clusters._
- _As a Giant Swarm Customer, I want to use K8S API directly so that I can automate my infrastructure using tools (like Terraform) which have integrations with K8S API._
- _As a Giant Swarm user, I want to have public documentation available so that I can work with CRDs on Control Plane._
- _As a Giant Swarm Engineer, I want to develop new features against K8S API directly so that I can avoid coding the API layer and deliver features faster_

## TODO  

- [x] Enable SSO authentification
- [x] Customer authorization towards Control Plane API
- [x] Document our current CRDs
- [x] #104 [Spec] Namespaced catalogs
- [x] #148 Add support for cluster resources namespaced by organization 
- [x] #112 Enable an App installation with K8S API
- [x] Enable a node pool cluster creation with K8S API
- [x] #28 Enable direct write access to App Catalog through Kubernetes API of the Control Plane

## Details, Background

We give customers access to the Kubernetes API of the management cluster and deprecate our own microservice-based API layer. All business logic will move either to the operators or will be augmented with Open Policy Agent.

Extending the Kubernetes API with operators and custom resources is already the core development model at Giant Swarm. By exposing the Kubernetes API to our customers and discontinuing working on the microservice-based API layer we get a clearer architecture as the business logic will be in one place and not shared between the API service and the operators. Coding the API layer after a feature is implemented takes a lot of time. By using the Kubernetes API we save time and resources improve our time to market for new features.

## Deliverables

- Deployed software
- API changes
- Public documentation
- Internal documentation
- Frontend changes

## Provider

- all

**Comment by marians** [comment]
## Update on documentation of Custom Resource Definitions (CRD)

We just published the first iteration of our Control Plane API reference at https://docs.giantswarm.io/reference/cp-k8s-api/ .

Currently only a small subset of our CRDs is covered, and the information right now is not guaranteed to be accurate or complete. We are working on adding documentation for more CRDs and enhancing the value of the provided information.

**Comment by snizhana-dynnyk** [comment]
This was an issue for POC and now there are separate issues for the rest of the work - 
https://github.com/giantswarm/roadmap/projects/1?card_filter_query=label%3Atopic%2Fmanagement-api

Closing this.
