### ISSUE TITLE
Cluster API compatible giant swarm infrastructure providers

### ISSUE THREAD

**Issue by cornelius-keller** [giantswarm/roadmap#91]
## User Story

As a customer I want to create g8s clusters using the Cluster API tooling.
As a giant swarm engineer I want to use infrastructure providers provided by the community to speed up the adaption of new clouds infrastructures.

# TODO

- [ ] Create an Cluster API compatible bootstrap operator (ignition operator ) 
- [ ] Create a MachinePool compatible Cluster API implementation for all providers
- [ ] Roll out cluster API controllers to all control planes and 
- [ ] Roll out cluster API compatible g8s infrastructure controllers to all management clusters

## Details, Background

The Kubernetes community is about to standardize the management of Kubernetes clusters with Kubernetes itself. As we are doing this from the very beginning we want to share our experiences with the community. We also want to benefit from the bigger development community in the future and want to be able to integrate work that was done in the community into our product.
In order to do this we want our CRDs and operators used to manage Kubernetes clusters to be compatible with the ones provided by the [Cluster API Project](https://cluster-api.sigs.k8s.io/)

## Deliverables

- Cluster API compatible infrastructure providers ( operators ) for kvm azure and aws

## Management cluster / workload cluster

- Control Plane 

## Provider

- AWS
- Azure
- KVM / bare metal

**Comment by puja108** [comment]
As we are going for a direct move to upstream Cluster API (CAPI) implementations, I'd say this story gets cut at least for AWS and Azure. @cornelius-keller you might want to make it a KVM-only issue if you want to keep it.

**Comment by cornelius-keller** [comment]
Yes I think this one is obsolete. I'll create a new one for KVM if needed.
