### ISSUE TITLE
[EPIC] Cluster API for GCP (CAPG)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#950]
## User Story
_*-As a giant swarm customer, I want to create Kubernetes clusters on GCP in order to deploy applications on GCP.*_

## Details, Background

...

## Blocked by / depends on

...

# Tasks / Milestones

**Milestone: Alpha**

- [x] https://github.com/giantswarm/roadmap/issues/659
- [x] https://github.com/giantswarm/roadmap/issues/838
- [x] https://github.com/giantswarm/roadmap/issues/899
- [x] https://github.com/giantswarm/roadmap/issues/898
- [x] https://github.com/giantswarm/roadmap/issues/883
- [x] https://github.com/giantswarm/roadmap/issues/877
- [x] https://github.com/giantswarm/roadmap/issues/918
- [x] https://github.com/giantswarm/roadmap/issues/943
- [x] https://github.com/giantswarm/roadmap/issues/919
- [ ] https://github.com/giantswarm/roadmap/issues/840
