### ISSUE TITLE
[EPIC] Cluster API for AWS (CAPA)

### ISSUE THREAD

**Issue by alex-dabija** [giantswarm/roadmap#951]
## User Story
_*-As a giant swarm customer, I want to create Kubernetes clusters on AWS in order to deploy applications on AWS.*_

## Details, Background

...

## Blocked by / depends on

...

# Tasks / Milestones

**Milestone: Alpha**

- [x] https://github.com/giantswarm/roadmap/issues/914
- [x] https://github.com/giantswarm/roadmap/issues/543
- [x] https://github.com/giantswarm/roadmap/issues/524
- [x] https://github.com/giantswarm/roadmap/issues/706
- [x] https://github.com/giantswarm/roadmap/issues/506
- [x] https://github.com/giantswarm/roadmap/issues/299
- [x] https://github.com/giantswarm/roadmap/issues/933
- [x] https://github.com/giantswarm/roadmap/issues/925
- [x] https://github.com/giantswarm/roadmap/issues/840
- [x] https://github.com/giantswarm/giantswarm/issues/21298
- [x] https://github.com/giantswarm/giantswarm/issues/19507
- [x] https://github.com/giantswarm/giantswarm/issues/19480
- [x] https://github.com/giantswarm/giantswarm/issues/19463
- [x] https://github.com/giantswarm/giantswarm/issues/19313
- [x] https://github.com/giantswarm/roadmap/issues/492
- [x] https://github.com/giantswarm/roadmap/issues/491
- [x] https://github.com/giantswarm/roadmap/issues/487
- [x] https://github.com/giantswarm/roadmap/issues/481
- [x] https://github.com/giantswarm/roadmap/issues/474
- [x] https://github.com/giantswarm/roadmap/issues/469
- [x] https://github.com/giantswarm/roadmap/issues/468
- [x] https://github.com/giantswarm/roadmap/issues/467
- [x] https://github.com/giantswarm/giantswarm/issues/19315
- [x] https://github.com/giantswarm/giantswarm/issues/19219
- [x] https://github.com/giantswarm/giantswarm/issues/19133
- [x] https://github.com/giantswarm/giantswarm/issues/18665

**Milestone: Beta**
- [x] https://github.com/giantswarm/roadmap/issues/114

**Later**
- [x] https://github.com/giantswarm/roadmap/issues/502
- [x] https://github.com/giantswarm/roadmap/issues/881
- [x] https://github.com/giantswarm/roadmap/issues/21
- [x] https://github.com/giantswarm/roadmap/issues/21
