### ISSUE TITLE
UX guideline for placeholders in CLI commands

### ISSUE THREAD

**Issue by marians** [giantswarm/roadmap#991]
We often want to present CLI commands to the user where some parts have to be adapted by the user in order to match their use case. This happens often in documentation and in the web UI.

## Requirements

We want users to be able to spot the placeholders easily, so they are aware and can replace them appropriately.

It's not required to automatically replace the placeholders in a shell etc.

## Proposal

Let's use `SCREAMING_SNAKE_CASE` (all uppercase letters, underscores as separators) for depicting placeholders. In textual instructions, let's format these placeholders as code literals.

Example:

> `$ kubectl gs --context gs-INSTALLATION --namespace org-ORGANIZATION_NAME get clusters`
>
> Replace `INSTALLATION` with the installation's alias and `ORGANIZATION_NAME` with the name of the organization.

## TODO

- [x] Document this in the intranet
- [x] Implement in documentation
- [x] Implement in the web UI
  - [x] Management API guides
  - [x] Getting Started guide

**Comment by marians** [comment]
We discussed my proposal in SIG UX. @ubergesundheit suggested that wrapping a placeholder with `<` and `>` would help prevent copying/pasting and executing a command with placeholders, as shells would not execute them.

So the decision is to use `<SCREAMING_SNAKE_CASE>` as the format for placeholders.

**Comment by ubergesundheit** [comment]
Some more background information:

`<` and `>` are valid characters in most shells for output/input redirection. Turns out I was wrong and these commands execute just fine in theory. 

Example:
Create files named `INSTALLATION` and `ORGANIZATION_NAME`, then run `kubectl gs --context gs-<INSTALLATION> --namespace org-<ORGANIZATION_NAME> get clusters`

**Comment by marians** [comment]
Is this actually a risk? Do we want to revise the guideline?

**Comment by ubergesundheit** [comment]
Mh unsure, lets ask our unix gurus in slack

**Comment by TheoBrigitte** [comment]
Trying to make the shell not execute the command is way to complex IMO, shells have various different implementation and interprets special character differently.

IMO the goal should be for the user to understand clearly this is a placeholder. If you are worried user would not consider plain `SCREAMING_SNAKE_CASE` a placeholder then yes wrap it with some special characters.

`<SCREAMING_SNAKE_CASE>` and `{SCREAMING_SNAKE_CASE}` are common

**Comment by whites11** [comment]
In general I am used to the `<NAME>` structure, but looking at random unix man pages, it seems ALL_CAPS is the way to go.
Example:

```
$ grep --help
Usage: grep [OPTION]... PATTERNS [FILE]...
Search for PATTERNS in each FILE.
Example: grep -i 'hello world' menu.h main.c
PATTERNS can contain multiple patterns separated by newlines.

Pattern selection and interpretation:
  -E, --extended-regexp     PATTERNS are extended regular expressions
  -F, --fixed-strings       PATTERNS are strings
  -G, --basic-regexp        PATTERNS are basic regular expressions
  -P, --perl-regexp         PATTERNS are Perl regular expressions
  -e, --regexp=PATTERNS     use PATTERNS for matching
...
```

**Comment by marians** [comment]
@ubergesundheit What's your preference now?

**Comment by ubergesundheit** [comment]
I stand by my preference adding < and > but there is no hard veto from my side if you find plain screaming snake case better :)

**Comment by marians** [comment]
Looks like SCREAMING_SNAKE_CASE is a widespread convention. I also found [Google's guidelines](https://developers.google.com/style/code-syntax#required-items) using it.

I still prefer not using `<>`, not only because it's cleaner without, but also it leaves the option for using `[` and `]` as a wrapper for optional arguments. `[OPTION]` is much simpler than `[<OPTION>]` or `<[OPTION]>`.

**Comment by marians** [comment]
And for reference, here is the Google section on placeholders: https://developers.google.com/style/placeholders

**Comment by marians** [comment]
Labelled as task candidate for Moritz. Let's talk about details in Rainbow.
